import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
const code=stripTypeScriptTypes(readFileSync('apps/app/src/prototype/assistant-draft-controller.ts','utf8'),{mode:'transform'});
const {AssistantDraftController}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const record=(text,revision='1')=>({version:1,binding:'test',revision,text});
function fixture(){let text='',saved=null;const store={async read(){return saved;},async save(expected,value){assert.deepEqual(expected,saved);return saved=record(value,String(Number(saved?.revision||0)+1));}};const c=new AssistantDraftController(async()=>store,()=>text,value=>{text=value;},()=>{});return {c,store,set:value=>{text=value;},get:()=>text,saved:()=>saved,external:value=>{saved=record(value,'external');}};}
test('reload restores text and consume durably clears before dispatch can proceed',async()=>{const f=fixture();f.external('Retained');await f.c.open('one');assert.equal(f.get(),'Retained');await f.c.consume('Retained');assert.equal(f.get(),'');assert.equal(f.saved().text,'');});
test('late loads cannot install another conversation draft',async()=>{let text='',release;const a=new Promise(resolve=>{release=resolve;});const c=new AssistantDraftController(async key=>({read:()=>key==='a'?a:Promise.resolve(record('B')),save:async()=>null}),()=>text,value=>{text=value;},()=>{});const old=c.open('a');await tick();await c.open('b');release(record('A'));await old;assert.equal(text,'B');});
test('typing while load is pending preserves both versions for explicit review',async()=>{const f=fixture();let release;f.store.read=()=>new Promise(resolve=>{release=resolve;});const opened=f.c.open('one');await tick();f.set('New typing');f.c.edit('New typing');release(record('Saved'));await opened;assert.equal(f.get(),'New typing');assert.equal(f.c.state.savedText,'Saved');assert.equal(f.c.state.conflict,true);});
test('concurrent changes stop autosave and consume until the saved copy is reviewed',async()=>{const f=fixture();await f.c.open('one');f.external('Other tab');f.set('This tab');f.c.edit('This tab');await tick();assert.equal(f.c.state.conflict,true);assert.equal(f.get(),'This tab');await assert.rejects(f.c.consume('This tab'));f.c.keepCurrent();await tick();assert.equal(f.saved().text,'This tab');assert.equal(f.c.state.conflict,false);});
test('queued writes retain their old binding without publishing into a new conversation',async()=>{const f=fixture();await f.c.open('old');let release;const save=f.store.save;f.store.save=async(...args)=>{await new Promise(resolve=>{release=resolve;});return save(...args);};f.set('Old draft');f.c.edit('Old draft');await tick();f.c.retire();f.set('New conversation');release();await tick();assert.equal(f.get(),'New conversation');assert.equal(f.saved().text,'Old draft');});

test('retirement immediately hides the previous identity recovery preview',async()=>{const f=fixture();await f.c.open('old');f.external('Private saved copy');f.set('Current copy');f.c.edit('Current copy');await tick();assert.equal(f.c.state.conflict,true);f.c.retire();assert.equal(f.c.state.conflict,false);assert.equal(f.c.state.savedText,'');assert.equal(f.c.state.opening,true);});

test('retirement during a known clear restores the old draft without sending or touching the new composer',async()=>{const f=fixture();f.external('Old draft');await f.c.open('old');const save=f.store.save;let release;f.store.save=async(expected,text)=>{if(text==='')await new Promise(resolve=>{release=resolve;});return save(expected,text);};const sending=f.c.consume('Old draft');await tick();f.c.retire();f.set('New owner draft');release();await assert.rejects(sending,/Nothing was sent/);assert.equal(f.saved().text,'Old draft');assert.equal(f.get(),'New owner draft');});

test('an invalidated send context refuses clearing even if text and binding still match',async()=>{const f=fixture();f.external('Keep draft');await f.c.open('one');await assert.rejects(f.c.consume('Keep draft',()=>false),/draft changed/);assert.equal(f.saved().text,'Keep draft');assert.equal(f.get(),'Keep draft');});
