import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import {build} from 'esbuild';
const bundle=await build({entryPoints:['apps/app/src/runtime/automations-protocol.ts'],bundle:true,write:false,format:'esm',platform:'neutral',logLevel:'silent'}),protocol=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const transformed=file=>stripTypeScriptTypes(fs.readFileSync(file,'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,''),{mode:'transform'}),source=fs.readFileSync('test/automations-unified.test.mjs','utf8');
const makeFixture=vm.runInNewContext('('+source.slice(source.indexOf('function adapterFixture('),source.indexOf('const wait=async fn=>'))+')',{protocol,transformed,fs,vm,stripTypeScriptTypes,queueMicrotask,AbortController,Date,crypto,Event,console});
const wait=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,2));}throw Error('Owned Home fixture did not settle');};
const oldEmpty={homeWorkflowHasRows:false,homeWorkflowRows:[],homeWorkflowTitle:'No workflows yet',homeWorkflowTime:''};
function fixture(options={}){const calls=[];let held,fail=false;const request=async(path,method)=>{calls.push({path,method});if(held)await held.promise;if(fail)throw Object.assign(Error('Synthetic unavailable source'),{status:503});return path==='/api/automations'?{automations:[]}:path.includes('scheduled-tasks')?{tasks:[]}:{reminders:[]};};return {calls,app:makeFixture(request,{},options),hold(){held=Promise.withResolvers();},release(){held?.resolve();held=undefined;},fail(){fail=true;}};}
test('unloaded unified overview overrides legacy empty copy without starting a Home fetch',async()=>{const f=fixture({view:null,homeFallback:oldEmpty});try{for(let i=0;i<3;i++){const home=f.app.home();assert.equal(home.homeWorkflowTitle,'Workflows');assert.equal(home.homeWorkflowTime,'Open to view');assert.equal(home.homeWorkflowLabel,'Open workflows and automations');f.app.render();}await Promise.resolve();assert.equal(f.calls.length,0);f.app.home().goFlows();assert.equal(f.calls.length,0);f.app.render();await wait(()=>f.app.home().homeWorkflowHasRows===true);assert.equal(f.calls.length,3);}finally{f.app.close();}});
test('a ready empty overview remains an authoritative empty state',async()=>{const f=fixture({homeFallback:oldEmpty,deviceReminders:[]});try{f.app.render();await wait(()=>!f.app.render().automation.loading);assert.equal(f.app.home().homeWorkflowTitle,'No automations yet');assert.equal(f.app.home().homeWorkflowHasRows,false);assert.equal(f.calls.length,3);}finally{f.app.close();}});
test('ready cached phone rows and stale refresh wording remain visible without Home refetch',async()=>{const f=fixture({homeFallback:oldEmpty});try{f.app.render();await wait(()=>f.app.home().homeWorkflowHasRows===true);const rows=JSON.stringify(f.app.home().homeWorkflowRows);assert.match(rows,/On-device reminder/);f.hold();f.app.render().automation.refresh();await wait(()=>f.calls.length===6);assert.equal(f.app.home().homeWorkflowTime,'Last loaded items');assert.equal(JSON.stringify(f.app.home().homeWorkflowRows),rows);for(let i=0;i<3;i++)f.app.home();assert.equal(f.calls.length,6);f.release();await wait(()=>f.app.home().homeWorkflowTime==='View automations');}finally{f.release();f.app.close();}});
test('account retirement hides cached rows and late old reads cannot restore an empty claim',async()=>{const f=fixture({homeFallback:oldEmpty});try{f.app.render();await wait(()=>f.app.home().homeWorkflowHasRows===true);f.hold();f.app.render().automation.refresh();await wait(()=>f.calls.length===6);f.app.retire();assert.equal(f.app.home().homeWorkflowTitle,'Workflows');assert.equal(f.app.home().homeWorkflowHasRows,false);assert.equal(JSON.stringify(f.app.home().homeWorkflowRows),'[]');f.release();await new Promise(resolve=>setTimeout(resolve,5));assert.equal(f.app.home().homeWorkflowTitle,'Workflows');assert.equal(f.calls.length,6);}finally{f.release();f.app.close();}});
test('an available inherited workflow cache remains visible before unified overview loads',()=>{const known={homeWorkflowHasRows:true,homeWorkflowRows:[{name:'Owned cached workflow',status:'Paused'}],homeWorkflowTitle:'',homeWorkflowTime:'View workflow'},f=fixture({view:null,homeFallback:known});try{assert.equal(f.app.home().homeWorkflowRows,known.homeWorkflowRows);assert.equal(f.app.home().homeWorkflowTime,'View workflow');assert.equal(f.calls.length,0);}finally{f.app.close();}});
test('failed remote reads preserve cached phone rows and their real partial status',async()=>{const f=fixture({homeFallback:oldEmpty});try{f.fail();f.app.render();await wait(()=>f.app.home().homeWorkflowHasRows===true);assert.equal(f.app.home().homeWorkflowTime,'Some items unavailable');assert.match(JSON.stringify(f.app.home().homeWorkflowRows),/On-device reminder/);assert.equal(f.calls.length,3);}finally{f.app.close();}});
