import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import vm from 'node:vm';
import fs from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import {build} from 'esbuild';

const bundle=await build({entryPoints:['apps/app/src/runtime/automations-protocol.ts'],bundle:true,write:false,format:'esm',platform:'neutral',logLevel:'silent'});
const protocol=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const {AutomationsProtocol}=protocol;
const workflow={id:'workflow:flow',type:'workflow',title:'Reviewed workflow',description:'Existing typed steps',enabled:false,status:'paused',workflowId:'flow',schedules:[]};
const prompt={id:'trigger:prompt',type:'coordinator_text',title:'Owner prompt',description:'Review a supplied document',enabled:false,status:'paused',triggerId:'prompt',schedules:[{triggerType:'cron',cronExpression:'0 9 * * 1',timezone:'UTC'}]};
const schedule={taskId:'scheduled-task',kind:'recap',promptInstructions:'Manual recap',trigger:{kind:'manual'},state:{status:'scheduled'},source:'default_pack',ownerVisible:true,metadata:{recordKey:'weekly-review'}};
const reminder={definition:{id:'definition',title:'Check the draft',description:'',status:'active',timezone:'UTC',cadence:{kind:'once',dueAt:'2020-01-01T12:00:00Z'}},occurrence:{id:'occurrence'},latestAttempt:null};
const future=()=>new Date(Date.now()+3600000).toISOString();
async function fixture(handler){
 const calls=[];
 const server=http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const call={path:req.url,method:req.method,body:raw?JSON.parse(raw):undefined};calls.push(call);assert.equal(req.headers.authorization,'Bearer synthetic-owner');
  try{const result=await handler(call,req,res);if(res.destroyed)return;res.writeHead(result?.status||200,{'Content-Type':'application/json'});res.end(JSON.stringify(result?.body??result??{}));}catch(error){res.writeHead(500);res.end(JSON.stringify({error:error.message}));}
 });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const request=async(path,method,body,signal)=>{const response=await fetch(`http://127.0.0.1:${server.address().port}`+path,{method,body:body===undefined?undefined:JSON.stringify(body),headers:{Authorization:'Bearer synthetic-owner','Content-Type':'application/json'},signal});const result=await response.json();if(!response.ok)throw Object.assign(Error('Fixture request refused'),{status:response.status});return result;};
 return {calls,request,client:new AutomationsProtocol(request),close:async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}};
}
const read=({path})=>path==='/api/automations'?{automations:[workflow,prompt]}:path.startsWith('/api/lifeops/scheduled-tasks')?{tasks:[schedule]}:path==='/api/lifeops/reminders'?{reminders:[reminder]}:path==='/api/triggers/prompt'?{trigger:{id:'prompt',displayName:'Owner prompt',instructions:'Keep the original selection',triggerType:'cron',cronExpression:'0 9 * * 1',timezone:'UTC'}}:path.endsWith('/runs')?{runs:[{status:'success',startedAtIso:'2026-10-08T12:00:00Z'}]}:{};
const signal=()=>new AbortController().signal;

test('unified read uses all three canonical sources and keeps stable source identities',async()=>{const f=await fixture(read);try{const snapshot=await f.client.list(signal());assert.deepEqual(snapshot.rows.map(row=>row.kind).sort(),['prompt','reminder','schedule','workflow']);assert.equal(snapshot.issues.length,0);assert.deepEqual(f.calls.map(call=>call.path).sort(),['/api/automations','/api/lifeops/reminders','/api/lifeops/scheduled-tasks?ownerVisibleOnly=1']);assert.equal(snapshot.rows.find(row=>row.kind==='schedule').enabled,false);assert.equal(snapshot.rows.find(row=>row.kind==='schedule').key,'scheduled:scheduled-task');}finally{await f.close();}});
test('missing capability and denied owner remain distinct while other sources stay usable',async()=>{const f=await fixture(call=>call.path.includes('scheduled-tasks')?{status:404,body:{}}:call.path.includes('/reminders')?{status:403,body:{}}:read(call));try{const snapshot=await f.client.list(signal());assert.equal(snapshot.rows.length,2);assert.deepEqual(snapshot.issues.map(issue=>[issue.source,issue.unavailable]),[['schedules',true],['reminders',false]]);assert.match(snapshot.issues[1].message,/owner/);}finally{await f.close();}});
test('unlisted scheduled rows and malformed identities fail their source instead of leaking into a healthy empty list',async()=>{const f=await fixture(call=>call.path.includes('scheduled-tasks')?{tasks:[{...schedule,ownerVisible:false}]}:read(call));try{const snapshot=await f.client.list(signal());assert.equal(snapshot.rows.some(row=>row.kind==='schedule'),false);assert.equal(snapshot.issues[0].source,'schedules');for(const id of ['../other','a/b','a%2fb','a?x=1',' a','a..b'])assert.throws(()=>protocol.automationId(id));}finally{await f.close();}});
test('prompt creation is paused, edits preserve wake/enable policy, and invalid dates never send',async()=>{const f=await fixture(call=>({trigger:{id:'prompt',...call.body}}));try{const draft={title:'  Draft review  ',instructions:'Read only the supplied document',triggerType:'once',scheduledAt:future(),cron:'',eventKind:'',timezone:'UTC'};await f.client.savePrompt(draft,signal());assert.equal(f.calls[0].method,'POST');assert.equal(f.calls[0].body.enabled,false);assert.equal(f.calls[0].body.wakeMode,'inject_now');await f.client.savePrompt({...draft,triggerType:'cron',cron:'0 9 * * 1'},signal(),'prompt');assert.equal(f.calls[1].method,'PUT');assert.equal(Object.hasOwn(f.calls[1].body,'enabled'),false);assert.equal(Object.hasOwn(f.calls[1].body,'wakeMode'),false);await assert.rejects(f.client.savePrompt({...draft,scheduledAt:'2020-01-01'},signal()),/future/);assert.equal(f.calls.length,2);}finally{await f.close();}});
test('scheduled Run uses fire rather than acknowledgment and reports a non-fired outcome',async()=>{const f=await fixture(()=>({fire:{kind:'skipped',reason:'Owner paused this item'}}));try{await assert.rejects(f.client.scheduledVerb('scheduled-task','fire',signal()),/Owner paused/);assert.deepEqual(f.calls.map(call=>call.path),['/api/lifeops/scheduled-tasks/scheduled-task/fire']);}finally{await f.close();}});
test('LifeOps reminders use the existing in-app definition/idempotency contract and preserve unchanged past due dates',async()=>{const f=await fixture(call=>call.path.includes('/occurrences/')?{occurrence:{id:'occurrence'}}:{definition:{id:call.method==='POST'?'created':'definition',...call.body}});try{await f.client.createReminder({message:'Review this draft',due:future(),timezone:'UTC',idempotencyKey:'same-owned-key'},signal());assert.equal(f.calls[0].body.idempotencyKey,'same-owned-key');assert.equal(f.calls[0].body.metadata.nativeProjection,'in_app_only');assert.equal(f.calls[0].body.reminderPlan.steps[0].channel,'in_app');const row=(await new AutomationsProtocol(async()=>({reminders:[reminder],automations:[],tasks:[]})).list(signal())).rows[0];await f.client.editReminder(row,'Changed message',reminder.definition.cadence.dueAt,signal());assert.deepEqual(f.calls[1].body,{title:'Changed message'});await f.client.snoozeReminder('occurrence',signal());await f.client.cancelReminder('definition',signal());assert.deepEqual(f.calls.slice(1).map(call=>[call.path,call.method]),[['/api/lifeops/definitions/definition','PUT'],['/api/lifeops/occurrences/occurrence/snooze','POST'],['/api/lifeops/definitions/definition','PUT']]);}finally{await f.close();}});

const transformed=file=>stripTypeScriptTypes(fs.readFileSync(file,'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,''),{mode:'transform'});
function adapterFixture(request,storage={}){
 const listeners=new Set(),events=new Map(),session={sessionId:'session',origin:'https://synthetic.invalid',ownerId:'owner',agentId:'agent'};
 const controller={getAutomationsClient:()=>({sessionId:session.sessionId,request}),getSnapshot:()=>({session,open:false}),subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},open:()=>{throw Error('Unexpected account chooser');}};
 const localStorage=new Proxy({getItem:key=>storage[key]??null,setItem:(key,value)=>storage[key]=value,removeItem:key=>delete storage[key]},{ownKeys:()=>Object.keys(storage),getOwnPropertyDescriptor:()=>({configurable:true,enumerable:true})});
 let view='workflows',workflowOpened='',deviceOpened='',newWorkflow=0;
 class Shell{live=true;componentDidMount(){}componentWillUnmount(){}S(){return {view};}vset(){}vget(){return {};}api(){return api;}openView(next){view=next;}refreshReminders(id){deviceOpened=id;}newDeviceReminderDraft(){deviceOpened='new-draft';}}
 const api={track:()=>'',kx:()=>0,isActive:()=>true};
 const views={workflows:{render:()=>({cards:[],managementCards:[],openWorkflow:id=>workflowOpened=id,newFlow:()=>newWorkflow++,detail:false,builder:false,runOpen:false}),back:()=>false,onLeave(){}}};
 const context={...protocol,connectionController:controller,DailyApps:{listReminders:async()=>({reminders:[{id:'device',title:'On-device reminder',body:'Existing phone row',at:Date.now()+10000,status:'scheduled'}]})},Capacitor:{getPlatform:()=> 'android'},localStorage,window:{dispatchEvent(){},addEventListener(){},removeEventListener(){}},document:{hidden:false,addEventListener:(name,fn)=>events.set(name,fn),removeEventListener(){}},queueMicrotask,AbortController,Date,crypto,Event,console};
 vm.runInNewContext(transformed('apps/app/src/runtime/workflow-intents.ts')+'\nglobalThis.WorkflowIntentStore=WorkflowIntentStore;globalThis.workflowIntentKey=workflowIntentKey;',context);
 vm.runInNewContext(transformed('.eliza/client-features/packages/ui/src/utils/automation-feed-filter.ts')+'\nglobalThis.FEED_FILTERS=FEED_FILTERS;globalThis.passesFilter=passesFilter;',context);
 vm.runInNewContext(transformed('apps/app/src/prototype/automations-adapter.ts')+'\nglobalThis.install=installAutomationsAdapter;',context);
 context.install(Shell,views);const shell=new Shell();shell.componentDidMount();
 return {home:()=>shell.renderVals(),render:()=>views.workflows.render({},api),close:()=>shell.componentWillUnmount(),storage,retire:()=>{session.sessionId='replacement';session.ownerId='other';for(const fn of listeners)fn();},back:()=>views.workflows.back(),get workflowOpened(){return workflowOpened;},get deviceOpened(){return deviceOpened;},get newWorkflow(){return newWorkflow;}};
}
const wait=async fn=>{for(let count=0;count<300;count++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,5));}throw Error('Unified automation UI did not settle.');};
test('actual Alpha adapter unifies five kinds, filters, delegates workflow/device detail and reviews canonical actions',async()=>{const f=await fixture(read),app=adapterFixture(f.request);try{app.render();await wait(()=>app.render().cards.length===5&&!app.render().automation.loading);assert.equal(app.home().homeWorkflowHasRows,true);assert.equal(app.home().homeWorkflowRows.length,2);assert.equal(app.home().homeWorkflowTime,'+3 more');app.render().automation.filters.find(filter=>filter.name==='Schedules').pick();assert.deepEqual(Array.from(app.render().cards,card=>card.name),['Weekly review']);app.render().automation.filters.find(filter=>filter.name==='All').pick();app.render().cards.find(card=>card.name==='Reviewed workflow').open();assert.equal(app.workflowOpened,'flow');app.render().cards.find(card=>card.name==='On-device reminder').open();assert.equal(app.deviceOpened,'device');}finally{app.close();await f.close();}});
test('unknown mutation stays locked in the existing owner request journal after adapter recreation',async()=>{let writes=0;const f=await fixture((call,_req,res)=>{if(call.method!=='GET'){writes++;res.destroy();return;}return read(call);});const storage={};let app=adapterFixture(f.request,storage);try{app.render();await wait(()=>app.render().cards.length===5&&!app.render().automation.loading);app.render().cards.find(card=>card.name==='Owner prompt').open();app.render().automation.actions.find(action=>action.label==='Enable').run();assert.equal(writes,0);app.render().automation.confirm();await wait(()=>writes===1&&!app.render().automation.busy);assert.equal(app.render().automation.locked,true);assert.equal(Object.keys(storage).length,1);app.close();app=adapterFixture(f.request,storage);app.render();await wait(()=>app.render().cards.length===5&&!app.render().automation.loading);app.render().cards.find(card=>card.name==='Owner prompt').open();assert.equal(app.render().automation.actions.find(action=>action.label==='Enable').disabled,true);assert.equal(writes,1);}finally{app.close();await f.close();}});
test('retiring an owner while a detail read waits cannot open an editor or dispatch a late mutation',async()=>{let release;const paused=new Promise(resolve=>release=resolve);let detailStarted=false;const f=await fixture(async call=>{if(call.path==='/api/triggers/prompt'){detailStarted=true;await paused;}return read(call);});const app=adapterFixture(f.request);try{app.render();await wait(()=>app.render().cards.length===5&&!app.render().automation.loading);app.render().cards.find(card=>card.name==='Owner prompt').open();app.render().automation.actions.find(action=>action.label==='Edit prompt').run();await wait(()=>detailStarted);app.retire();assert.equal(app.home().homeWorkflowHasRows,undefined);release();await new Promise(resolve=>setTimeout(resolve,20));assert.equal(app.render().automation.editing,false);assert.equal(f.calls.filter(call=>call.method!=='GET').length,0);}finally{release();app.close();await f.close();}});
