import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {build} from 'esbuild';
const bundle=await build({entryPoints:['apps/app/src/runtime/automations-protocol.ts'],bundle:true,write:false,format:'esm',platform:'neutral',logLevel:'silent'});
const {AutomationsProtocol}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
async function row(trigger,source='schedule'){
 const original={taskId:'owned-qa',kind:'recap',promptInstructions:'Synthetic only',trigger,state:{status:'scheduled'},ownerVisible:true,metadata:{recordKey:'gm'}},before=JSON.stringify(original),calls=[];
 const client=new AutomationsProtocol(async(path,method,body)=>{calls.push({path,method,body});if(source==='schedule')return path.includes('scheduled-tasks')?{tasks:[original]}:path==='/api/automations'?{automations:[]}:{reminders:[]};return path==='/api/automations'?{automations:[{id:'trigger:owned-qa',type:'coordinator_text',title:'Synthetic prompt',enabled:false,schedules:[trigger]}]}:path.includes('scheduled-tasks')?{tasks:[]}:{reminders:[]};});
 const snapshot=await client.list(new AbortController().signal);assert.equal(snapshot.issues.length,0);assert.equal(snapshot.rows.length,1);assert.equal(JSON.stringify(original),before);assert.ok(calls.every(call=>call.method==='GET'&&call.body===undefined));return snapshot.rows[0];
}
test('common saved cron schedules use the exact pinned OG formatter for task and automation records',async()=>{
 const cases=[['0 8 * * *','Every day at 8am'],['30 14 * * 1-5','Every weekday at 2:30pm'],['0 9 * * 0,6','Every weekend at 9am'],['0 20 * * 1','Every Monday at 8pm'],['*/15 * * * *','Every 15 minutes'],['0 * * * *','Every hour'],['0 */6 * * *','Every 6 hours']];
 for(const source of ['schedule','automation'])for(const [expression,expected] of cases){const trigger=source==='schedule'?{kind:'cron',expression,tz:'UTC'}:{triggerType:'cron',cronExpression:expression,timezone:'UTC'};assert.equal((await row(trigger,source)).schedule,expected+' · UTC');}
});
test('complex, uneven and unsupported cron forms retain the exact expression with an honest label',async()=>{for(const expression of ['*/45 * * * *','0 */5 * * *','0,30 9 * * *','0 9-17 * * *','0 9 1 * *','0 9 * JAN MON','0 0 8 * * *'])assert.equal((await row({kind:'cron',expression,tz:'UTC'})).schedule,'Cron: '+expression+' · UTC');});
test('regional recurrence keeps its stored zone through DST and never substitutes the phone zone or a fixed offset',async()=>{const previous=process.env.TZ;try{for(const phoneZone of ['UTC','Asia/Tokyo','America/Los_Angeles']){process.env.TZ=phoneZone;assert.equal((await row({kind:'cron',expression:'0 8 * * *',tz:'America/Los_Angeles'})).schedule,'Every day at 8am · America/Los_Angeles');}}finally{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous;}});
test('missing cron/zone and unrecognized zones do not invent a schedule or local time authority',async()=>{assert.equal((await row({kind:'cron',expression:'',tz:'UTC'})).schedule,'Schedule unavailable · UTC');assert.equal((await row({kind:'cron',expression:'0 8 * * *'})).schedule,'Every day at 8am · Time zone not specified');assert.equal((await row({kind:'cron',expression:'0 8 * * *',tz:'Not/AZone'})).schedule,'Every day at 8am · Not/AZone (unrecognized time zone)');});
test('manual schedules remain Manual and paused; interval and event triggers retain their actual kind',async()=>{const manual=await row({kind:'manual'});assert.equal(manual.schedule,'Manual');assert.equal(manual.enabled,false);assert.equal(manual.status,'paused');assert.equal((await row({kind:'interval',everyMinutes:15})).schedule,'Every 15 minutes');assert.equal((await row({kind:'event',eventKind:'calendar.updated'})).schedule,'On calendar.updated');});
test('friendly cron source is authenticated by the normal pinned client producer',()=>{const source=JSON.parse(fs.readFileSync('.eliza/client-features/.source.json','utf8')),pin=JSON.parse(fs.readFileSync('upstream.lock.json','utf8')).commit;assert.equal(source.baseCommit,pin);assert.ok(source.files['packages/ui/src/utils/cron-format.ts']);});
