import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
const tick=()=>new Promise(r=>setTimeout(r,0));
function fixture(kind='paired') {const document=Object.assign(new EventTarget(),{hidden:false}),subscriptions=new Set(),listeners=new Map(),f={calls:[],stops:[],plays:[],binding:{origin:'https://agent.test',ownerId:'owner',expiresAt:Date.now()+60000,sessionId:'session'},credential:'credential',open:false,active:null};
 const synth=async(input,route)=>{f.calls.push({input,route});if(f.wait)await f.wait();const result={playbackId:'audio-'+input.requestId};f.active={...result,requestId:input.requestId};return result;};
 const native={cancel:async()=>{},stopPlayback:async input=>{f.stops.push(input);if(f.active?.requestId===input?.requestId)f.active=null;},cancelRecording:async()=>{},pairedVoiceStatus:async()=>({ready:true}),pairedTranscriptionStatus:async()=>({ready:true,provider:'standalone-whisper.cpp'}),transcribePairedRecording:async()=>({text:'Transcript',local:true,provider:'standalone-whisper.cpp'}),synthesizePaired:input=>synth(input,'paired'),synthesizeBrowserReading:input=>synth(input,'reading'),synthesize:input=>synth(input,'cloud'),play:async input=>f.plays.push(input),addListener:async(event,callback)=>{const set=listeners.get(event)||new Set();set.add(callback);listeners.set(event,set);return {remove:async()=>set.delete(callback)};}};
 const controller={getPairedVoiceBinding:()=>f.binding,getSnapshot:()=>({open:f.open}),getCloudEnvironment:()=> 'production',getCloudClient:()=>({sessionId:f.binding?.sessionId,credentialId:f.credential}),subscribe:cb=>{subscriptions.add(cb);return ()=>subscriptions.delete(cb);}};
 const box={Capacitor:{isNativePlatform:()=>true},registerPlugin:()=>native,connectionController:controller,crypto,AbortController,DOMException,setTimeout,clearTimeout,document};
 for(const [file,name] of [['local-speech-playback.ts','playOwnedSpeech'],['runtime/'+kind+'-voice.ts',kind==='paired'?'createPairedVoice':'createCloudVoice']]){let s=fs.readFileSync('apps/app/src/'+file,'utf8').replace(/^import .*;\n/gm,'').replaceAll('export async function','async function').replaceAll('export function','function').replaceAll('export type','type');vm.runInNewContext('{'+stripTypeScriptTypes(s,{mode:'transform'})+'\nglobalThis.'+name+'='+name+';}',box);}
 f.voice=kind==='paired'?box.createPairedVoice():box.createCloudVoice();f.native=native;f.document=document;f.emit=(event,id=f.active?.playbackId)=>{for(const cb of listeners.get(event)||[])cb({playbackId:id});};f.changed=()=>{for(const cb of subscriptions)cb();};return f;
}
async function until(check){for(let i=0;i<100&&!check();i++)await new Promise(r=>setTimeout(r,5));assert.ok(check());}
for(const kind of ['paired','cloud']){
 test(kind+' ignores unrelated completion and retires its exact replacement without stopping newer audio',async()=>{const f=fixture(kind);let done=false;const pending=f.voice.speak('Reviewed text',new AbortController().signal).finally(()=>done=true);void pending.catch(()=>{});await until(()=>f.plays.length===1);f.emit('playbackEnded','other');await tick();assert.equal(done,false);const old=f.active;f.active={playbackId:'new',requestId:'new'};f.emit('playbackStopped',old.playbackId);await assert.rejects(pending);assert.equal(f.active.requestId,'new');assert.ok(f.stops.every(s=>s.requestId===old.requestId));});
 test(kind+' cancellation settles stalled listener setup and removes a late handle',async()=>{const f=fixture(kind);let release,removed=0;f.native.addListener=()=>new Promise(r=>release=r);const c=new AbortController(),pending=f.voice.speak('Text',c.signal);await until(()=>release);c.abort();await assert.rejects(pending);release({remove:async()=>removed++});await tick();assert.equal(removed,1);assert.equal(f.calls.length,0);});
 test(kind+' late synthesis cannot start after cancellation',async()=>{const f=fixture(kind);let release;f.wait=()=>new Promise(r=>release=r);const c=new AbortController(),pending=f.voice.speak('Text',c.signal);await until(()=>release);c.abort();await assert.rejects(pending);release();await tick();assert.equal(f.plays.length,0);assert.ok(f.stops.every(s=>s.requestId===f.calls[0].input.requestId));});
 test(kind+' visibility and changed authorization cancel bound speech',async()=>{for(const mode of ['hidden','authorization']){const f=fixture(kind),pending=f.voice.speak('Text',new AbortController().signal);await until(()=>f.plays.length===1);if(mode==='hidden'){f.document.hidden=true;f.document.dispatchEvent(new Event('visibilitychange'));}else{if(kind==='paired')f.binding={...f.binding,sessionId:'new'};else f.credential='rotated';f.changed();}await assert.rejects(pending);}});
}
test('paired browser reading sends only the approved token through its distinct native endpoint',async()=>{const f=fixture(),pending=f.voice.speak('Must not use this text',new AbortController().signal,'review-token');await until(()=>f.plays.length===1);assert.equal(f.calls[0].route,'reading');assert.equal(f.calls[0].input.readingToken,'review-token');assert.equal(f.calls[0].input.text,undefined);assert.equal(f.calls[0].input.ownerId,'owner');f.emit('playbackEnded');await pending;});
test('cancelling paired readiness/transcription and Cloud recording does not stop unrelated audio',async()=>{for(const method of ['ready','transcriptionReady','transcribe']){const f=fixture();f.native[{ready:'pairedVoiceStatus',transcriptionReady:'pairedTranscriptionStatus',transcribe:'transcribePairedRecording'}[method]]=()=>new Promise(()=>{});const c=new AbortController(),pending=method==='transcribe'?f.voice.transcribe('recording',c.signal):f.voice[method](c.signal);c.abort();await assert.rejects(pending);assert.deepEqual(f.stops,[]);}const f=fixture('cloud');await f.voice.cancelRecording();assert.deepEqual(f.stops,[]);});
