import test from 'node:test';
import assert from 'node:assert/strict';
import {cloudVoiceViewFixture} from './fixtures/cloud-voice-view.mjs';
import {voiceFakeClock} from './fixtures/shared-batch-voice.mjs';
function fixture(options={}){const clock=voiceFakeClock(),f=cloudVoiceViewFixture({clock,transcript:'Hello Alpha.',...options});return Object.assign(f,{clock});}
const settle=f=>f.clock.flush();
async function utterance(f){f.peak=.25;await f.clock.advance(900);f.peak=0;await f.clock.advance(750);await settle(f);}
async function stop(f){f.renderChat()?.discard();await settle(f);}
for(const view of [null,'calendar','browser'])test(`explicit chat mic starts one Cloud conversation in ${view||'Home'} without consuming text or Notes`,async()=>{
 const f=fixture({holdPlayback:true});try{const reply={id:'reply'},edit={id:'edit'};Object.assign(f.shell.state,{view,chat:'input',draft:'Unsent draft'});f.shell.messageReplyTarget=reply;f.shell.messageEditTarget=edit;const notes=JSON.stringify(f.shell.notes);
 await f.shell.startVoice();assert.equal(f.starts,1);assert.equal(f.renderChat().state,'listening');assert.equal(f.uploads,0);assert.equal(f.shell.S().view,view);assert.equal(f.render().rec,undefined);
 await utterance(f);assert.equal(f.uploads,1);assert.equal(f.sends,1);assert.equal(f.sendInputs[0].text,'Hello Alpha.');assert.notEqual(f.sendInputs[0].text,'Unsent draft');assert.equal(f.cloudSpeech,1);assert.equal(f.renderChat().state,'speaking');assert.equal(f.starts,1);
 assert.equal(f.shell.S().draft,'Unsent draft');assert.equal(f.shell.messageReplyTarget,reply);assert.equal(f.shell.messageEditTarget,edit);assert.equal(JSON.stringify(f.shell.notes),notes);assert.equal(f.audioSaves,0);assert.equal(f.localFactories,0);assert.equal(f.pairedFactories,0);
 f.finishPlayback();await settle(f);await f.clock.advance(249);assert.equal(f.starts,1);await f.clock.advance(1);assert.equal(f.starts,2);await stop(f);assert.equal(f.renderChat(),null);assert.equal(f.shell.S().chat,'input');
 }finally{f.close();await settle(f);}
});
test('unsigned conversation offers explicit Cloud account connection without capture or local fallback',async()=>{const f=fixture({account:null});try{await f.shell.startVoice();assert.equal(f.renderChat().primaryLabel,'Connect Eliza Cloud');f.renderChat().stop();await settle(f);assert.equal(f.accountOpens,1);assert.equal(f.starts,0);assert.equal(f.uploads,0);assert.equal(f.localFactories,0);}finally{f.close();await settle(f);}});
for(const duringSpeech of [false,true])test(`metrics failure ${duringSpeech?'during':'before'} speech retires without upload/send/rearm`,async()=>{const f=fixture();try{await f.shell.startVoice();if(duringSpeech){f.peak=.2;await f.clock.advance(900);}f.metricsError=Error('Synthetic meter failure');await f.clock.advance(100);assert.equal(f.renderChat().state,'error');assert.equal(f.uploads,0);assert.equal(f.sends,0);const count=f.starts;await f.clock.advance(60000);assert.equal(f.starts,count);await stop(f);}finally{f.close();await settle(f);}});
test('owned native recording failure before speech is an error, not a quiet rearm',async()=>{const f=fixture();try{await f.shell.startVoice();for(const callback of f.events.get('recordingStopped')||[])callback({recordingId:f.activeRecording});await settle(f);assert.equal(f.renderChat().state,'error');await f.clock.advance(60000);assert.equal(f.starts,1);assert.equal(f.uploads,0);}finally{f.close();await settle(f);}});
test('account replacement discards held old ASR and never sends or resumes it',async()=>{const f=fixture({holdTranscript:true});try{f.shell.state.draft='Keep text';await f.shell.startVoice();await utterance(f);assert.equal(f.uploads,1);f.account='other-account';f.credential='other-credential';f.changed();f.releaseTranscript({text:'Old account words.',local:false});await settle(f);assert.equal(f.sends,0);assert.equal(f.shell.S().draft,'Keep text');await f.clock.advance(60000);assert.equal(f.starts,1);assert.equal(f.renderChat(),null);}finally{f.close();await settle(f);}});
test('Stop retires a held reply with no speech or replay',async()=>{const f=fixture({holdReply:true});try{await f.shell.startVoice();await utterance(f);assert.equal(f.sends,1);await stop(f);f.releaseReply();await settle(f);await f.clock.advance(60000);assert.equal(f.cloudSpeech,0);assert.equal(f.starts,1);assert.equal(f.sends,1);}finally{f.releaseReply?.();f.close();await settle(f);}});
for(const badReply of [{requestId:'wrong'},{conversationId:'other-room'},{assistantMessageId:''},{complete:false},{interrupted:true}])test(`only a complete matching new reply may speak: ${JSON.stringify(badReply)}`,async()=>{const f=fixture({badReply});try{await f.shell.startVoice();await utterance(f);assert.equal(f.renderChat().state,'error');assert.equal(f.cloudSpeech,0);await f.clock.advance(60000);assert.equal(f.starts,1);assert.equal(f.sends,1);}finally{f.close();await settle(f);}});
test('held playback cleanup stays visible and blocks new mic across Stop/new coordinator',async()=>{const f=fixture({holdPlayback:true});try{await f.shell.startVoice();await utterance(f);f.holdPlaybackCleanup=true;f.renderChat().discard();await settle(f);assert.equal(f.renderChat().state,'stopping');await f.clock.advance(700);assert.equal(f.renderChat().state,'stopping');await f.shell.startVoice();assert.equal(f.starts,1);f.holdPlaybackCleanup=false;f.releasePlaybackCleanup();await settle(f);assert.equal(f.renderChat(),null);await f.shell.startVoice();assert.equal(f.starts,2);assert.equal(f.activeRecording,'synthetic-clip-2');await settle(f);assert.equal(f.activeRecording,'synthetic-clip-2');}finally{f.holdPlaybackCleanup=false;f.releasePlaybackCleanup?.();f.close();await settle(f);}});
test('natural unconfirmed speaker cleanup persists a fail-closed lease after speech pointer clears',async()=>{const f=fixture({holdPlayback:true});try{await f.shell.startVoice();await utterance(f);f.playbackCleanupError=Error('Synthetic cleanup refusal');f.finishPlayback();await settle(f);assert.equal(f.renderChat().state,'error');await f.shell.startVoice();assert.equal(f.starts,1);f.renderChat().stop();await settle(f);assert.equal(f.renderChat().state,'error');assert.match(f.renderChat().lines[0].t,/Could not confirm voice media stopped/);await f.shell.startVoice();assert.equal(f.starts,1);}finally{f.playbackCleanupError=undefined;f.close();await settle(f);}});
test('Notes retains its reviewed recording and refuses a second chat microphone owner',async()=>{const f=fixture();try{f.render().record();f.render().rec.stop();await settle(f);assert.equal(f.starts,1);const notes=JSON.stringify(f.shell.notes);await f.shell.startVoice();assert.equal(f.starts,1);assert.equal(f.renderChat(),null);assert.equal(f.render().rec.primaryLabel,'Stop recording');assert.equal(JSON.stringify(f.shell.notes),notes);}finally{f.close();await settle(f);}});
for(const action of ['keyboard','minimize','hidden'])test(`${action} retires media and never resumes on foreground`,async()=>{const f=fixture();try{f.shell.state.draft='Retained';await f.shell.startVoice();if(action==='keyboard')f.renderChat().keyboard();else if(action==='minimize')f.shell.renderVals().closeChat();else{f.box.document.hidden=true;f.shell.componentDidUpdate();}await settle(f);assert.equal(f.renderChat(),null);assert.equal(f.activeRecording,null);f.box.document.hidden=false;f.shell.componentDidUpdate();await f.clock.advance(60000);assert.equal(f.starts,1);assert.equal(f.shell.S().draft,'Retained');assert.equal(f.sends,0);}finally{f.close();await settle(f);}});
test('stale old failure arriving before a new start ID never consumes the new owned capture',async()=>{const f=fixture({holdStart:true});try{const pending=f.shell.startVoice();await settle(f);for(const callback of f.events.get('recordingStopped')||[])callback({recordingId:'retired-clip'});f.holdStart=false;f.releaseStart({recordingId:'current-clip',maxDurationMs:59000});await pending;await settle(f);assert.equal(f.renderChat().state,'listening');assert.equal(f.activeRecording,'current-clip');assert.equal(f.uploads,0);}finally{f.releaseStart?.({recordingId:'current-clip',maxDurationMs:59000});f.close();await settle(f);}});

for(const change of ['navigation','account','detent'])test(`delayed media retirement never restores old detent over ${change}`,async()=>{const f=fixture({holdPlayback:true});try{Object.assign(f.shell.state,{view:null,chat:'input'});await f.shell.startVoice();await utterance(f);f.holdPlaybackCleanup=true;f.renderChat().discard();await settle(f);if(change==='navigation'){f.shell.openView('photos');f.shell.setState({chat:'hidden'});}else if(change==='account'){f.account='new-owner';f.credential='new-key';f.shell.setState({chat:'hidden'});f.changed();}else f.shell.setState({chat:'full'});f.shell.componentDidUpdate();assert.equal(f.renderChat().state,'stopping');assert.equal(f.shell.renderVals().conversationHidden,false);f.holdPlaybackCleanup=false;f.releasePlaybackCleanup();await settle(f);assert.equal(f.renderChat(),null);assert.equal(f.shell.S().chat,change==='detent'?'full':'hidden');}finally{f.holdPlaybackCleanup=false;f.releasePlaybackCleanup?.();f.close();await settle(f);}});
test('prior Cloud Read aloud drains beyond500ms before conversational capture',async()=>{const f=fixture({holdPlayback:true,native:false,platform:'web'});try{f.shell.renderVals().msgs[0].localSpeech();await settle(f);assert.equal(f.cloudSpeech,1);f.holdPlaybackCleanup=true;const starting=f.shell.startVoice();await settle(f);await f.clock.advance(700);assert.equal(f.starts,0);f.holdPlaybackCleanup=false;f.releasePlaybackCleanup();await starting;assert.equal(f.starts,1);await stop(f);}finally{f.holdPlaybackCleanup=false;f.releasePlaybackCleanup?.();f.close();await settle(f);}});
test('unconfirmed prior Read aloud retirement remains blocked for subsequent conversation attempts',async()=>{const f=fixture({holdPlayback:true});try{f.shell.renderVals().msgs[0].localSpeech();await settle(f);f.playbackCleanupError=Error('Synthetic prior speaker refusal');f.finishPlayback();await settle(f);f.shell.renderVals().msgs[0].localSpeech();await settle(f);assert.equal(f.cloudSpeech,1);assert.match(f.shell.renderVals().msgs[0].localSpeechMessage,/cleanup could not be confirmed/);await f.shell.startVoice();assert.equal(f.starts,0);assert.equal(f.renderChat().state,'error');await stop(f);await f.shell.startVoice();assert.equal(f.starts,0);assert.equal(f.renderChat().state,'error');}finally{f.playbackCleanupError=undefined;f.close();await settle(f);}});
test('discarding Notes transcript playback drains its owned speaker before new chat capture',async()=>{const f=fixture({holdPlayback:true});try{f.render().record();f.render().rec.stop();await settle(f);f.render().rec.stop();await settle(f);f.render().rec.stop();await settle(f);assert.equal(f.render().rec.review,true);f.render().rec.toggle();await settle(f);assert.equal(f.cloudSpeech,1);f.holdPlaybackCleanup=true;f.render().rec.discard();await settle(f);const notes=JSON.stringify(f.shell.notes);const starting=f.shell.startVoice();await settle(f);await f.clock.advance(700);assert.equal(f.starts,1);f.holdPlaybackCleanup=false;f.releasePlaybackCleanup();await starting;assert.equal(f.starts,2);assert.equal(JSON.stringify(f.shell.notes),notes);await stop(f);}finally{f.holdPlaybackCleanup=false;f.releasePlaybackCleanup?.();f.close();await settle(f);}});
test('saved Notes playback late admission and retirement both drain before conversational microphone',async()=>{const f=fixture({holdSavedStart:true,holdSavedStop:true});try{f.shell.notes={list:[{id:'note',body:'Saved transcript',audio:{audioId:'saved-audio',transcript:'Saved transcript'}}],open:'note',audioDeletionChecked:true};f.render().vo.play();await settle(f);assert.equal(f.savedAudioStarts,1);const starting=f.shell.startVoice();await settle(f);await f.clock.advance(700);assert.equal(f.starts,0);f.holdSavedStart=false;f.releaseSavedStart();await settle(f);assert.equal(f.savedAudioStops,1);assert.equal(f.starts,0);f.holdSavedStop=false;f.releaseSavedStop();await starting;assert.equal(f.activeSavedAudio,null);assert.equal(f.starts,1);await stop(f);}finally{f.holdSavedStart=false;f.holdSavedStop=false;f.releaseSavedStart?.();f.releaseSavedStop?.();f.close();await settle(f);}});
test('unconfirmed saved Notes speaker retirement blocks all new conversational capture',async()=>{const f=fixture();try{f.shell.notes={list:[{id:'note',body:'Saved transcript',audio:{audioId:'saved-audio',transcript:'Saved transcript'}}],open:'note',audioDeletionChecked:true};f.render().vo.play();await settle(f);f.savedStopError=Error('Synthetic saved audio stop failure');await f.shell.startVoice();assert.equal(f.starts,0);assert.equal(f.renderChat().state,'error');await stop(f);await f.shell.startVoice();assert.equal(f.starts,0);}finally{f.savedStopError=undefined;f.close();await settle(f);}});

for(const change of ['account','hidden','unmount'])test(`pending Read aloud never admits old text after ${change}`,async()=>{const f=fixture(),held=Promise.withResolvers();try{f.shell.stopVoiceConversation=()=>held.promise;f.shell.renderVals().msgs[0].localSpeech();await settle(f);assert.equal(f.cloudSpeech,0);if(change==='account'){f.account='new-account';f.credential='new-credential';f.changed();}else if(change==='hidden')f.box.document.hidden=true;else f.shell.componentWillUnmount();held.resolve();await settle(f);assert.equal(f.cloudSpeech,0);}finally{held.resolve();f.close();await settle(f);}});
test('overlapping pending Read aloud intents admit only the latest selected message',async()=>{const f=fixture(),held=Promise.withResolvers();try{f.shell.state.msgs=[{id:'old',text:'Old selected reply',from:'agent'},{id:'new',text:'New selected reply',from:'agent'}];f.shell.stopVoiceConversation=()=>held.promise;f.shell.renderVals().msgs[0].localSpeech();await settle(f);f.shell.renderVals().msgs[1].localSpeech();await settle(f);held.resolve();await settle(f);assert.equal(f.cloudSpeech,1);assert.equal(f.speechInputs[0].text,'New selected reply');}finally{held.resolve();f.close();await settle(f);}});
test('failed capture admission with unconfirmed microphone cancellation blocks every retry',async()=>{const f=fixture({startError:Error('Synthetic start admission failure'),captureCancelError:Error('Synthetic cancel refusal')});try{await f.shell.startVoice();assert.equal(f.starts,1);assert.equal(f.renderChat().state,'error');await stop(f);await f.shell.startVoice();assert.equal(f.starts,1);assert.equal(f.uploads,0);}finally{f.captureCancelError=undefined;f.close();await settle(f);}});

function pausedFixture(){return fixture({badReply:{complete:false,userMessageId:'original-user',assistantMessageId:'queued-assistant',awaitingUserInput:{proposalId:'proposal',digest:'a'.repeat(64)}}});}
test('actual prepared shared controller pauses Alpha at reviewed Notes input, displays history and admits only the matching answer once',async()=>{const f=pausedFixture();try{await f.shell.startVoice();await utterance(f);assert.equal(f.renderChat().state,'awaiting-user-input');assert.equal(f.renderChat().live,false);assert.equal(f.renderChat().flex,'0 0 auto');assert.equal(f.shell.renderVals().showChatHistory,true);assert.equal(f.starts,1);assert.equal(f.cloudSpeech,0);await f.clock.advance(10000);assert.equal(f.starts,1);const requestId=f.sendInputs[0].turnId,reply={version:1,requestId,conversationId:f.conversation,inReplyTo:'original-user',messageId:'completed-assistant',text:'Matching approved answer'};assert.equal(f.shell.resumeReadReplyVoice({version:1,requestId,conversationId:f.conversation,inReplyTo:'original-user',proposalId:'proposal-other',digest:'a'.repeat(64),attemptId:'attempt'},reply),false);assert.equal(f.cloudSpeech,0);assert.equal(f.shell.resumeReadReplyVoice({version:1,requestId:reply.requestId,conversationId:reply.conversationId,inReplyTo:reply.inReplyTo,proposalId:'proposal',digest:'a'.repeat(64),attemptId:'attempt'},reply),true);assert.equal(f.shell.resumeReadReplyVoice({version:1,requestId:reply.requestId,conversationId:reply.conversationId,inReplyTo:reply.inReplyTo,proposalId:'proposal',digest:'a'.repeat(64),attemptId:'attempt'},reply),false);await settle(f);assert.equal(f.cloudSpeech,1);assert.equal(f.speechInputs[0].text,reply.text);await stop(f);}finally{f.close();await settle(f);}});
for(const action of ['stop','keyboard','minimize','account','private-review'])test(`paused original reply cannot start audio after ${action}`,async()=>{const f=pausedFixture();try{let cancelled=0;f.shell.cancelReadReplyCompletions=()=>cancelled++;await f.shell.startVoice();await utterance(f);const reply={version:1,requestId:f.sendInputs[0].turnId,conversationId:f.conversation,inReplyTo:'original-user',messageId:'completed-assistant',text:'Approved answer'};if(action==='stop')f.renderChat().stop();if(action==='keyboard')f.renderChat().keyboard();if(action==='minimize'){f.shell.state.chat='input';f.shell.componentDidUpdate();}if(action==='account'){f.account='replacement';f.changed();}if(action==='private-review'){f.reviewOpen={};f.renderChat().keyboard();await settle(f);await f.shell.startVoice();}await settle(f);assert.equal(f.shell.resumeReadReplyVoice({version:1,requestId:reply.requestId,conversationId:reply.conversationId,inReplyTo:reply.inReplyTo,proposalId:'proposal',digest:'a'.repeat(64),attemptId:'attempt'},reply),false);await f.clock.advance(10000);assert.equal(f.cloudSpeech,0);assert.equal(f.starts,1);assert.equal(cancelled,action==='stop'?1:0);}finally{f.close();await settle(f);}});

test('private Notes review preserves only its exact shared pause and never opens another microphone',async()=>{const f=pausedFixture();try{await f.shell.startVoice();await utterance(f);const before=f.starts;await f.shell.prepareDeviceReadReview('proposal','a'.repeat(64),new AbortController().signal);assert.equal(f.renderChat().state,'awaiting-user-input');assert.equal(f.starts,before);assert.equal(f.cloudSpeech,0);await f.clock.advance(10000);assert.equal(f.starts,before);await stop(f);}finally{f.close();await settle(f);}});
test('unbound pending voice review stays exposed with no speech, resume or rearm',async()=>{const f=fixture({badReply:{complete:false,reviewRequired:true}});try{await f.shell.startVoice();await utterance(f);assert.equal(f.renderChat().state,'error');assert.equal(f.shell.renderVals().showChatHistory,true);assert.equal(f.shell.renderVals().chatHistoryInert,false);assert.equal(f.renderChat().primaryLabel,'Stop voice conversation');await f.clock.advance(10000);assert.equal(f.starts,1);assert.equal(f.cloudSpeech,0);await stop(f);}finally{f.close();await settle(f);}});

test('an owned approval private review blocks new capture after switching paused voice to keyboard',async()=>{const f=pausedFixture();try{await f.shell.startVoice();await utterance(f);f.shell.pendingActionApproval=new AbortController();f.renderChat().keyboard();await settle(f);await f.shell.startVoice();assert.equal(f.starts,1);assert.equal(f.cloudSpeech,0);f.shell.pendingActionApproval=null;}finally{f.close();await settle(f);}});

test('legacy private Notes review waits beyond500ms for owned ReadAloud cleanup without recording or inference',async()=>{const f=fixture({holdPlayback:true,holdPlaybackCleanup:true});try{f.shell.renderVals().msgs[0].localSpeech();await settle(f);assert.equal(f.cloudSpeech,1);let admitted=false;const review=f.shell.prepareDeviceReadReview('legacy-proposal',undefined,new AbortController().signal).then(()=>{admitted=true;});await settle(f);await f.clock.advance(700);assert.equal(admitted,false);assert.equal(f.starts,0);f.holdPlaybackCleanup=false;f.releasePlaybackCleanup();await review;assert.equal(admitted,true);assert.equal(f.starts,0);assert.equal(f.uploads,0);}finally{f.holdPlaybackCleanup=false;f.releasePlaybackCleanup?.();f.close();await settle(f);}});
