import test from 'node:test';
import assert from 'node:assert/strict';
import {cloudVoiceViewFixture} from './fixtures/cloud-voice-view.mjs';
const until=async(check)=>{for(let count=0;count<250;count++){if(check())return;await new Promise(resolve=>setTimeout(resolve,2));}assert.ok(check(),'Synthetic chat recorder did not settle');};
async function reviewed(f){f.renderChat().stop();await until(()=>f.renderChat()?.primaryLabel==='Stop recording');assert.equal(f.uploads,0);f.renderChat().stop();await until(()=>f.renderChat()?.primaryLabel==='Transcribe with Eliza Cloud');assert.equal(f.uploads,0);f.renderChat().stop();await until(()=>f.renderChat()?.review===true);}

for(const view of [null,'calendar','browser'])test(`composer voice stays in ${view||'Home'} and applying reviewed text never touches Notes or sends chat`,async()=>{
 const f=cloudVoiceViewFixture();try{
  const reply={id:'reply'},edit={id:'edit'};Object.assign(f.shell.state,{view,chat:'input',draft:'Typed draft'});f.shell.messageReplyTarget=reply;f.shell.messageEditTarget=edit;const notes=JSON.stringify(f.shell.notes);
  await f.shell.startVoice();assert.equal(f.shell.S().view,view);assert.equal(f.render().rec,undefined);assert.equal(f.renderChat().primaryLabel,'Start recording');assert.equal(f.shell.renderVals().showChatHistory,false);assert.equal(f.starts,0);assert.equal(f.localFactories,0);
  await reviewed(f);assert.equal(f.shell.S().draft,'Typed draft');f.renderChat().onTranscript({target:{value:'Reviewed Cloud transcript'}});f.renderChat().stop();await until(()=>!f.renderChat());
  assert.equal(f.shell.S().view,view);assert.equal(f.shell.S().draft,'Typed draft\nReviewed Cloud transcript');assert.equal(f.shell.messageReplyTarget,reply);assert.equal(f.shell.messageEditTarget,edit);assert.equal(JSON.stringify(f.shell.notes),notes);assert.equal(f.sends,0);assert.equal(f.audioSaves,0);assert.equal(f.shell.renderVals().showChatHistory,true);
 }finally{f.close();}
});
test('unsigned chat voice connects the account without opening Notes or attempting recording',async()=>{
 const f=cloudVoiceViewFixture({account:null});try{Object.assign(f.shell.state,{view:'calendar',chat:'input',draft:'Keep this draft'});const notes=JSON.stringify(f.shell.notes);await f.shell.startVoice();assert.equal(f.renderChat().primaryLabel,'Connect Eliza Cloud');assert.equal(f.renderChat().manualChoice,false);assert.equal(f.renderChat().routeChoice,false);f.renderChat().stop();await f.tick();assert.equal(f.accountOpens,1);assert.equal(f.starts,0);assert.equal(f.uploads,0);assert.equal(f.localFactories,0);assert.equal(f.shell.S().view,'calendar');assert.equal(f.shell.S().draft,'Keep this draft');assert.equal(JSON.stringify(f.shell.notes),notes);}finally{f.close();}
});
for(const action of ['discard','keyboard','back'])test(`chat ${action} preserves the typed draft and reply/edit targets`,async()=>{
 const f=cloudVoiceViewFixture();try{const reply={id:'reply'},edit={id:'edit'};Object.assign(f.shell.state,{view:'browser',chat:'input',draft:'Retained draft'});f.shell.messageReplyTarget=reply;f.shell.messageEditTarget=edit;await f.shell.startVoice();if(action==='back')f.shell.back();else f.renderChat()[action]();await f.tick();assert.equal(f.renderChat(),null);assert.equal(f.shell.S().view,'browser');assert.equal(f.shell.S().chat,'input');assert.equal(f.shell.S().draft,'Retained draft');assert.equal(f.shell.messageReplyTarget,reply);assert.equal(f.shell.messageEditTarget,edit);assert.equal(f.starts,0);assert.equal(f.sends,0);}finally{f.close();}
});
test('an account switch retires a pending chat transcript and stale callbacks cannot start the next capture',async()=>{
 const f=cloudVoiceViewFixture({holdTranscript:true});try{Object.assign(f.shell.state,{view:'calendar',chat:'input',draft:'Current text'});await f.shell.startVoice();f.renderChat().stop();await until(()=>f.renderChat()?.primaryLabel==='Stop recording');f.renderChat().stop();await until(()=>f.renderChat()?.primaryLabel==='Transcribe with Eliza Cloud');const stale=f.renderChat();stale.stop();await until(()=>typeof f.releaseTranscript==='function');f.account='other-account';f.credential='other-credential';f.changed();f.releaseTranscript({text:'Late old-account text',local:false});await f.tick();assert.equal(f.renderChat(),null);assert.equal(f.shell.S().draft,'Current text');assert.equal(f.shell.S().view,'calendar');f.holdTranscript=false;await f.shell.startVoice();stale.stop();await f.tick();assert.equal(f.starts,1);assert.equal(f.uploads,1);assert.equal(f.renderChat().primaryLabel,'Start recording');assert.equal(f.sends,0);}finally{f.close();}
});
test('opening and closing the account chooser never resumes an owned chat recording automatically',async()=>{
 const f=cloudVoiceViewFixture();try{await f.shell.startVoice();f.open=true;f.changed();assert.equal(f.renderChat(),null);f.open=false;f.changed();await f.tick();assert.equal(f.renderChat(),null);assert.equal(f.starts,0);assert.equal(f.uploads,0);await f.shell.startVoice();assert.equal(f.renderChat().primaryLabel,'Start recording');assert.equal(f.starts,0);}finally{f.close();}
});
test('pending native start is retired before a new capture can start, and late cleanup cannot cancel the new capture',async()=>{
 const f=cloudVoiceViewFixture({holdStart:true});try{await f.shell.startVoice();f.renderChat().stop();await until(()=>typeof f.releaseStart==='function');f.renderChat().discard();f.holdStart=false;await f.shell.startVoice();f.renderChat().stop();await f.tick();assert.equal(f.starts,1,'second start waits for the first native lease');f.releaseStart({recordingId:'old-private-clip',maxDurationMs:59000});await until(()=>f.starts===2&&f.renderChat()?.primaryLabel==='Stop recording');await f.tick();assert.equal(f.activeRecording,'synthetic-clip-2');assert.ok(f.recordingCancels.includes('old-private-clip'));assert.equal(f.recordingCancels.includes('synthetic-clip-2'),false);assert.equal(f.uploads,0);assert.equal(f.sends,0);}finally{f.releaseStart?.({recordingId:'old-private-clip',maxDurationMs:59000});f.close();}
});
