import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
function method(file,start,end,extras={}){const source=fs.readFileSync('apps/app/src/runtime/'+file,'utf8'),from=source.indexOf(start),to=end?source.indexOf(end,from):source.indexOf('\n  }\n',from)+5;assert.ok(from>=0&&to>from);const box={string:v=>v,identifier:v=>v,record:v=>v,object:v=>v,crypto,AbortController,Error,...extras};vm.runInNewContext(stripTypeScriptTypes('globalThis.port={'+source.slice(from,to)+'};',{mode:'transform'}),box);return box.port;}
for(const [name,file,start,end] of [['remote','remote-protocol.ts','  async send(',null],['cloud','cloud-protocol.ts','  async send(','  async initiateGmail('],['local','local-agent.ts','  async send(',null]])for(const channel of [undefined,'VOICE_DM'])test(`${name} actual serializer preserves ${channel||'default DM'} and scoped metadata`,async()=>{
 const port=method(file,start,end,{RemoteProtocolError:Error,CloudProtocolError:Error}),calls=[],signal=new AbortController().signal,metadata={nativeUserTextFormat:{version:1},voiceTurnSignal:{turnId:'voice-turn'}};
 const reply={text:'Matching reply',agentName:'Alpha'};
 port.authorized=async(...args)=>{calls.push(args[2]);return reply;};port.runtimeCall=async(...args)=>{calls.push(args[3]);return reply;};port.json=async(...args)=>{calls.push(args[1]);return reply;};port.bridge={};
 const options={signal,metadata,clientMessageId:'owned-request',...(channel?{channelType:channel}:{})};
 if(name==='cloud')await port.send('agent','room','Only new speech',options);else await port.send('room','Only new speech',options);
 assert.equal(calls.length,1);assert.equal(calls[0].channelType,channel||'DM');assert.equal(calls[0].text,'Only new speech');assert.equal(calls[0].clientMessageId,'owned-request');assert.equal(calls[0].metadata,metadata);
});
for(const channel of [undefined,'VOICE_DM'])test(`local stream uses ${channel||'default DM'} without changing owner headers or delta protocol`,async()=>{const port=method('local-agent.ts','  async send(',null),calls=[];Object.assign(port,{session:{ownerId:'owner'},generation:1,streams:new Set(),deviceHeaders:{'X-Eliza-Device-Id':'device'},bridge:{stream:async input=>{calls.push(input);return {text:'Reply',agentName:'Alpha'};}}});await port.send('room','New speech',{channelType:channel,clientMessageId:'request',metadata:{nativeUserTextFormat:{version:1}},onText(){}});assert.equal(calls[0].ownerId,'owner');assert.equal(calls[0].headers,port.deviceHeaders);const body=JSON.parse(calls[0].body);assert.equal(body.channelType,channel||'DM');assert.equal(body.streamProtocol,'delta-v2');assert.equal(body.clientMessageId,'request');assert.deepEqual(body.metadata,{nativeUserTextFormat:{version:1}});assert.equal(port.streams.size,0);});
test('cold selected saved conversation is pinned before voice binding is published, without creating a room or sending',async()=>{const source=fs.readFileSync('apps/app/src/runtime/connection-ui.tsx','utf8'),begin=source.indexOf('function conversationKey('),end=source.indexOf('/** Only remove an exact',begin),conversationMemory=new Map(),calls=[],session={origin:'https://owned.invalid',ownerId:'owner',agentId:'agent'};const box={conversationMemory,captureConversationChoice:async()=>({id:'saved-room'}),selectConversation:async()=>{throw Error('Saved selection must remain unchanged');},update(){},globalThis:null};box.globalThis=box;vm.runInNewContext(stripTypeScriptTypes(source.slice(begin,end)+'globalThis.prepare=ensureSelectedConversation;',{mode:'transform'}),box);const selected={kind:'local',remote:{createConversation:async()=>calls.push('created')}};const room=await box.prepare(selected,session,new AbortController().signal,()=>{});assert.equal(room,'saved-room');assert.equal(conversationMemory.get(JSON.stringify([session.origin,session.ownerId,session.agentId])),room);assert.deepEqual(calls,[]);});
