import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
const source=fs.readFileSync('apps/app/src/prototype/agent-adapter.ts','utf8');
function fixture(){
 const session={origin:'https://owned.invalid',sessionId:'owner-session',ownerId:'owner',agentId:'agent'},binding={session,conversationId:'room',connectionEpoch:1};
 const f={queue:[],sent:[],claims:0,acks:0,current:true,hold:false,context:{view:'home',revision:1,sensitive:false}};
 const shell={live:true,state:{view:null,chat:'sheet',draft:'Saved unsent text',msgs:[],typing:false},messageReplyTarget:{id:'retained-reply'},messageEditTarget:{id:'retained-edit'},S(){return this.state;},setState(patch,done){const apply=()=>{const next=typeof patch==='function'?patch(this.state):patch;if(next)Object.assign(this.state,next);done?.();};if(f.hold)f.queue.push(apply);else apply();},openView(view){this.state.view=view;f.context={...f.context,view,revision:2};f.current=false;},goHome(){this.openView(null);},toast(){},agentSay(){throw Error('No proposal expected');}};
 const alphaClient={getState:()=>({context:f.context,pending:false}),send:async(...args)=>{f.sent.push(args);f.onText=args[1];if(f.send)await f.send();return {messageId:'assistant-id',userMessageId:'user-id',messageBinding:{conversationId:'room',session},text:'Matching complete reply',actionResults:f.navigate?[{}]:[]};}};
 const connectionController={voiceConversationCurrent:()=>f.current,captureViewNavigation:()=>({attempt:{current(){if(!f.current)throw Error('Retired');}},client:{async deliver(_results,attempt,apply){attempt.current();f.claims++;const done=await apply('photos',attempt.current);if(done)f.acks++;return {status:done?'delivered':'unknown',label:'Photos'};}}})};
 const box={p:shell,alphaClient,connectionController,document:{hidden:false},crypto,context(){},isMvpView:view=>view==='photos',views:{photos:{}}};
 const helpers=source.slice(source.indexOf('  function openInternalView('),source.indexOf('  function context('));
 const method=source.slice(source.indexOf('  p.sendVoiceTurn ='),source.indexOf('  p.send =',source.indexOf('  p.sendVoiceTurn =')));
 vm.runInNewContext(stripTypeScriptTypes(helpers+method,{mode:'transform'}),box);
 const controller=new AbortController();return Object.assign(f,{shell,binding,controller,flush(){const q=this.queue.splice(0);for(const apply of q)apply();},start(){return shell.sendVoiceTurn({text:'Only new recognized words.',turnId:'voice-turn',voiceTurnSignal:{},signal:controller.signal,binding,context:f.context,assertCurrent(){if(!f.current)throw Error('Retired');}});}});
}
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
test('voice delivery uses only new transcript and VOICE_DM with exact request/room; composer targets remain untouched',async()=>{const f=fixture(),before={draft:f.shell.state.draft,reply:f.shell.messageReplyTarget,edit:f.shell.messageEditTarget};const result=await f.start();assert.deepEqual({...result},{requestId:'voice-turn',conversationId:'room',userMessageId:'user-id',assistantMessageId:'assistant-id',text:'Matching complete reply',complete:true});const args=f.sent[0];assert.equal(args[0],'Only new recognized words.');assert.equal(args[2],undefined);assert.equal(args[4].channelType,'VOICE_DM');assert.equal(args[4].requestId,'voice-turn');assert.equal(args[4].expectedConversationId,'room');assert.equal(args[4].signal,f.controller.signal);assert.deepEqual({draft:f.shell.state.draft,reply:f.shell.messageReplyTarget,edit:f.shell.messageEditTarget},before);assert.equal(f.shell.state.typing,false);});
for(const stage of ['user','stream','final'])test(`queued ${stage} updater cannot publish old voice rows after owner replacement`,async()=>{const f=fixture(),held=Promise.withResolvers();f.send=()=>held.promise;if(stage==='user')f.hold=true;const sending=f.start();const rejected=assert.rejects(sending);await flush();if(stage!=='user'){f.hold=true;if(stage==='stream')f.onText('Old streamed voice row');else{held.resolve();await flush();}}f.current=false;f.shell.state={...f.shell.state,msgs:[],typing:false,draft:'Replacement owner draft'};f.flush();held.resolve();await flush();f.flush();await rejected;assert.deepEqual(f.shell.state.msgs,[]);assert.equal(f.shell.state.draft,'Replacement owner draft');assert.equal(f.shell.state.typing,false);assert.equal(f.claims,0);});
test('Stop while reply held prevents navigation/ACK and voice reply completion',async()=>{const f=fixture(),held=Promise.withResolvers();f.navigate=true;f.send=()=>held.promise;const sending=f.start(),rejected=assert.rejects(sending);await flush();f.controller.abort();held.resolve();await rejected;assert.equal(f.claims,0);assert.equal(f.acks,0);assert.equal(f.shell.state.view,null);});
test('a current owned navigation applies once and drains its exact ACK before retiring voice',async()=>{const f=fixture();f.navigate=true;await assert.rejects(f.start());assert.equal(f.shell.state.view,'photos');assert.equal(f.claims,1);assert.equal(f.acks,1);});
