import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
const tick=()=>new Promise(r=>setTimeout(r,0));
function fixture(native=true){
 const listeners=new Map(),f={calls:[],stops:[],cancelled:[],active:null,hold:false,release:null,hangCleanup:false};
 const voice={addListener:async(event,callback)=>{const set=listeners.get(event)||new Set();set.add(callback);listeners.set(event,set);return {remove:async()=>{if(f.hangCleanup)return new Promise(()=>{});set.delete(callback);}};},cancel:async({requestId})=>{f.cancelled.push(requestId);},stopPlayback:async(input)=>{f.stops.push(input);if(f.hangCleanup)return new Promise(()=>{});if(f.active?.requestId===input.requestId)f.active=null;},synthesizeLocal:async(input)=>{if(input.replace===false&&f.active)throw Object.assign(Error('Busy'),{code:'playback-busy'});f.calls.push(input);if(f.hold)await new Promise(r=>f.release=r);f.active={...input,playbackId:'audio-'+input.requestId};return {playbackId:f.active.playbackId};},play:async({playbackId})=>{assert.equal(playbackId,f.active?.playbackId);}};
 const box={Capacitor:{isNativePlatform:()=>native},registerPlugin:()=>voice,crypto,AbortController,DOMException,setTimeout,clearTimeout,console};
 function load(file,expose){const source=fs.readFileSync(new URL('../'+file,import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export async function','async function').replaceAll('export function','function');vm.runInNewContext('{'+stripTypeScriptTypes(source,{mode:'transform'})+'\n'+expose+'}',box);}
 load('apps/app/src/runtime/local-speech-text.ts','globalThis.planLocalSpeech=planLocalSpeech;');load('apps/app/src/local-speech-playback.ts','globalThis.speakLocalText=speakLocalText;');
 f.emit=(event,id=f.active?.playbackId)=>{if(f.active?.playbackId===id)f.active=null;for(const cb of listeners.get(event)||[])cb({playbackId:id});};f.speak=box.speakLocalText;f.plan=box.planLocalSpeech;f.voice=voice;return f;
}
async function until(check){for(let i=0;i<200&&!check();i++)await new Promise(r=>setTimeout(r,5));assert.ok(check(),'Expected fixture state');}
test('native full passage is preflighted and completed sequentially with one start callback',async()=>{
 const f=fixture(),text='This is a complete synthetic sentence. '.repeat(100),expected=Array.from(f.plan(text));assert.ok(text.length>500&&text.length<=5000);let starts=0,done=false;const speech=f.speak(text,new AbortController().signal,()=>starts++,true).then(()=>done=true);
 for(let i=0;i<expected.length;i++){await until(()=>f.calls.length===i+1);await tick();assert.equal(f.calls[i].text,expected[i]);assert.ok(f.calls[i].text.length<=300);assert.equal(done,false);assert.equal(f.calls[i].replace,false);f.emit('playbackEnded');}
 await speech;assert.equal(done,true);assert.equal(starts,1);assert.equal(new Set(f.calls.map(c=>c.requestId)).size,expected.length);
});
test('unsupported trailing text fails before any partial native speech',async()=>{const f=fixture();await assert.rejects(f.speak('Supported English. '.repeat(80)+'🙂',new AbortController().signal));assert.equal(f.calls.length,0);});
test('queued native synthesis waits without replacing another consumer',async()=>{const f=fixture();f.active={playbackId:'other',requestId:'other'};const controller=new AbortController();const speaking=f.speak('Approved text',controller.signal,undefined,true);await new Promise(r=>setTimeout(r,150));assert.equal(f.calls.length,0);assert.equal(f.active.requestId,'other');f.active=null;await until(()=>f.calls.length===1);await tick();f.emit('playbackEnded');await speaking;assert.ok(f.stops.every(s=>s.requestId!=='other'));});
test('cancelling queued native speech leaves other playback untouched',async()=>{const f=fixture();f.active={playbackId:'other',requestId:'other'};const controller=new AbortController();const speech=f.speak('Approved text',controller.signal,undefined,true);void speech.catch(()=>{});await tick();controller.abort();await assert.rejects(speech);assert.equal(f.calls.length,0);assert.equal(f.active.requestId,'other');});
test('replacement and failure events stop the passage without starting another chunk',async()=>{for(const event of ['playbackStopped','playbackFailed']){const f=fixture(),speech=f.speak('A complete synthetic sentence. '.repeat(80),new AbortController().signal,undefined,true);void speech.catch(()=>{});await until(()=>f.calls.length===1);await tick();const old=f.active.playbackId;f.active={playbackId:'new',requestId:'new'};f.emit(event,old);await assert.rejects(speech);assert.equal(f.calls.length,1);assert.equal(f.active.requestId,'new');}});
test('abort settles with hung cleanup and late synthesis cannot play',async()=>{const f=fixture();f.hold=true;f.hangCleanup=true;const c=new AbortController(),speech=f.speak('Approved text',c.signal,undefined,true);void speech.catch(()=>{});await until(()=>!!f.release);c.abort();await Promise.race([assert.rejects(speech),new Promise((_,reject)=>setTimeout(()=>reject(Error('Abort stalled')),900))]);f.release();await tick();assert.equal(f.calls.length,1);assert.ok(f.stops.length>=1);});
test('browser speech retains its original text and single utterance',async()=>{const f=fixture(false),text='Browser text 🙂 https://example.test';const speech=f.speak(text,new AbortController().signal);await until(()=>f.calls.length===1);await tick();f.emit('playbackEnded');await speech;assert.equal(f.calls[0].text,text);assert.equal(f.calls.length,1);});
test('abort during listener registration removes a late handle without synthesizing',async()=>{const f=fixture();let release,removed=0;f.voice.addListener=()=>new Promise(resolve=>release=resolve);const controller=new AbortController(),speech=f.speak('Approved text',controller.signal);void speech.catch(()=>{});await until(()=>!!release);controller.abort();await assert.rejects(speech);release({remove:async()=>{removed++;}});await tick();assert.equal(removed,1);assert.equal(f.calls.length,0);});
test('a stopped prepared utterance exits the playback queue immediately',async()=>{const f=fixture(false);f.voice.play=async()=>{throw Object.assign(Error('Busy'),{code:'playback-busy'});};const c=new AbortController(),speech=f.speak('Queued browser text',c.signal,undefined,true);void speech.catch(()=>{});await until(()=>f.calls.length===1);await tick();f.emit('playbackStopped');try{await Promise.race([assert.rejects(speech),new Promise((_,reject)=>setTimeout(()=>reject(Error('Stopped playback remained queued')),800))]);}finally{c.abort();}});

test('play admission error is preserved when its cleanup emits a stopped event',async()=>{const f=fixture(false);f.voice.play=async()=>{f.emit('playbackStopped');await tick();throw Error('No local browser voice is available. Read the reply as text.');};await assert.rejects(f.speak('Private reviewed text',new AbortController().signal),/No local browser voice/);});

test('local speech starts with a complete sentence without dropping the remainder',()=>{
 const f=fixture(),text='Alpha phone, local voice verification please. Remember to water the plants tomorrow morning.';
 const chunks=Array.from(f.plan(text));
 assert.deepEqual(chunks,['Alpha phone, local voice verification please.','Remember to water the plants tomorrow morning.']);
 assert.equal(chunks.join(' '),text);
 const unpunctuated='Water the plants tomorrow morning '.repeat(30).trim(),bounded=Array.from(f.plan(unpunctuated));
 assert.ok(bounded.every(chunk=>chunk.length<=300));assert.equal(bounded.join(' '),unpunctuated);
 assert.throws(()=>f.plan(text+' Unsupported 🙂'));
});
