import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const native=path.resolve('android/app/src/main/java/ai/elizaresearch/alphaphone');
const plugin=fs.readFileSync(path.join(native,'AlphaLocalAgentPlugin.java'),'utf8');
const connection=fs.readFileSync(path.join(native,'AlphaConnectionPlugin.java'),'utf8');
function method(source,start){const at=source.indexOf(start);assert.ok(at>=0,start);let depth=0;for(let i=source.indexOf('{',at);i<source.length;i++){if(source[i]==='{')depth++;else if(source[i]==='}'&&--depth===0)return source.slice(at,i+1);}throw Error('Unclosed method');}
test('actual native credential mutation waits for full shutdown and fences stale stores, launches and identities',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'alpha-credential-retirement-'));
 const java=process.env.JAVA_HOME||'/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home';
 const jar=process.env.ALPHA_JSON_JAR||fs.globSync(path.join(os.homedir(),'.gradle/caches/modules-2/files-2.1/org.json/json/20250517/*/json-20250517.jar'))[0];assert.ok(jar);
 const write=(name,text)=>{const file=path.join(dir,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);return file;};
 try{
 const files=[write('android/content/Context.java','package android.content;public class Context {public Context getApplicationContext(){return this;}public java.io.File getNoBackupFilesDir(){return new java.io.File(".");}public static final int MODE_PRIVATE=0;public Context getSharedPreferences(String s,int m){return this;}public Context edit(){return this;}public Context putString(String k,String v){return this;}public void apply(){}}'),write('android/util/AtomicFile.java','package android.util;public class AtomicFile {}'),write('android/os/SystemClock.java','package android.os;public class SystemClock {static long now;public static synchronized long elapsedRealtime(){return now+=1000;}}')];
 files.push(write('ai/eliza/plugins/securestore/nativeonly/JsonCredentialSlots.java',`package ai.eliza.plugins.securestore.nativeonly;import java.util.*;import java.io.*;import android.util.AtomicFile;
public class JsonCredentialSlots {public static final Object LOCK=new Object();public interface Limits{int maxBytes(String n);}public static final Map<String,String> values=new HashMap<>();public static String failWrite;public JsonCredentialSlots(File f,String a,Limits l){}public String slotHash(String n){return n;}public AtomicFile slotFile(String n){return null;}public String read(String n){synchronized(LOCK){return values.get(n);}}public void write(String n,String v)throws Exception{synchronized(LOCK){if(n.equals(failWrite))throw new IOException("Synthetic storage failure");values.put(n,v);}}public void remove(String n){synchronized(LOCK){values.remove(n);}}}`));
 for(const name of ['AlphaCredentialStore','LocalAgentProviderAdmission'])files.push(write(`ai/elizaresearch/alphaphone/${name}.java`,fs.readFileSync(path.join(native,name+'.java'),'utf8')));
 const constants=['CLOUD_PROVIDER_MODEL','PROVIDER_MODEL_PATTERN','CEREBRAS_PROVIDER_MODEL'].map(name=>plugin.match(new RegExp(' static final String '+name+'=[^;]+;'))[0]).join('\n');
 const mutation=plugin.slice(plugin.indexOf(' static long reserveCredentialIntent()'),plugin.indexOf(' private void requireCurrent'));
 files.push(write('ai/elizaresearch/alphaphone/AlphaLocalAgentPlugin.java',`package ai.elizaresearch.alphaphone;import org.json.*;import com.getcapacitor.*;import android.content.Context;
class AlphaLocalAgentPlugin {
 final java.util.Set<String> cancelledStarts=new java.util.HashSet<>();static java.util.Set<com.getcapacitor.PluginCall> pending=new java.util.HashSet<>();static long startRequestEpoch;boolean disposed;java.util.concurrent.ExecutorService workers=java.util.concurrent.Executors.newSingleThreadExecutor();Context getContext(){return CredentialRetirementTest.context;}boolean runtimePackaged(){return true;}void requireCurrent(long epoch)throws Superseded{throw new Superseded();}boolean rejectStartupRefusal(com.getcapacitor.PluginCall c,long e,JSONObject s)throws Exception{throw new Superseded();}void authenticatedStatus(long e,String t)throws Exception{throw new Superseded();}void enroll(long e)throws Exception{throw new Superseded();}void resolveCurrent(com.getcapacitor.PluginCall c,long e,Object v)throws Superseded{throw new Superseded();}static void rejectSuperseded(com.getcapacitor.PluginCall c){}static void rejectPending(com.getcapacitor.PluginCall c,String m){}
 static final Object lifecycleLock=new Object();static long lifecycleEpoch,credentialIntentEpoch,credentialShutdownRequest=-1;static volatile long credentialMutationEpoch=-1;static String startRequestId;static boolean startOwnsLaunch,accepting=true,stopping;static int invalidations;static String ownerToken="owned";
 static class Superseded extends Exception{}static void invalidateCalls(){invalidations++;}static void clearEnrollment(){ownerToken=null;}
 ${constants}\n${mutation}\n${[' static String saveVerifiedProvider(',' static JSObject providerIdentity(',' static boolean validProviderToken(',' static String cloudProviderToken(',' static void bindCloudProvider(',' static void bindDirectProvider(',' private static boolean shutdownConfirmed('].map(start=>method(plugin,start)).join('\n')}
 interface ProviderCheck {String check(String key,String model);}
 static String checkCerebrasKey(String key,String model){return null;}
 static void retire(){synchronized(lifecycleLock){lifecycleEpoch++;accepting=false;clearEnrollment();}}
 ${method(plugin,' @PluginMethod public void start(').replace('@PluginMethod ','')}
 ${method(plugin,' @PluginMethod public void getStatus(').replace('@PluginMethod ','')}
}`));
 const identityMethods=[' private static URI validatedUrl(',' private static byte[] readBounded(',' private static Object parseJson(',' static JSONObject readCloudIdentity('].map(start=>method(connection,start)).join('\n');
 files.push(write('ai/elizaresearch/alphaphone/AlphaConnectionPlugin.java',`package ai.elizaresearch.alphaphone;import java.net.*;import java.io.*;import java.nio.charset.*;import org.json.*;class AlphaConnectionPlugin {static final int RESPONSE_LIMIT=2*1024*1024;static String required(String v,int max){if(v==null||v.isEmpty()||v.length()>max)throw new IllegalArgumentException();return v;}${identityMethods}}`));
 const bridgeMethods=[' @PluginMethod public void secureWrite(',' private long credentialIntent(',' private AlphaCredentialStore storage(long intent)',' @PluginMethod public void secureRemove('].map(start=>method(connection,start).replace('@PluginMethod ','')).join('\n');
 files.push(write('com/getcapacitor/PluginCall.java',`package com.getcapacitor;public class PluginCall {public final java.util.Map<String,String> data=new java.util.HashMap<>();public int resolved,rejected;public Object result;public PluginCall(String slot,String value){data.put("slot",slot);data.put("value",value);}public String getString(String name){return data.get(name);}public String getString(String name,String fallback){return data.getOrDefault(name,fallback);}public void resolve(){resolved++;}public void resolve(Object value){result=value;resolved++;}public void reject(String message){rejected++;}public void reject(String message,String code){rejected++;}}`));
 files.push(write('com/getcapacitor/JSObject.java',`package com.getcapacitor;public class JSObject extends org.json.JSONObject {public JSObject(){}public JSObject(String value)throws org.json.JSONException{super(value);}public JSObject put(String key,Object value){try{super.put(key,value);return this;}catch(Exception e){throw new IllegalArgumentException(e);}}public JSObject put(String key,boolean value){try{super.put(key,value);return this;}catch(Exception e){throw new IllegalArgumentException(e);}}}`));
 files.push(write('ai/elizaresearch/alphaphone/ConnectionMutationBridge.java',`package ai.elizaresearch.alphaphone;import com.getcapacitor.*;class ConnectionMutationBridge {static final String STORAGE_FULL="storage-full",STORAGE_FULL_MESSAGE="Storage full";boolean destroyed;java.util.List<Runnable> queued=new java.util.ArrayList<>();android.content.Context getContext(){return CredentialRetirementTest.context;}boolean submit(PluginCall call,Runnable task){queued.add(task);return true;}${bridgeMethods}}`));
 files.push(write('ai/elizaresearch/alphaphone/RendererCredentialSlots.java',fs.readFileSync(path.join(native,'RendererCredentialSlots.java'),'utf8')));
 const configMethods=[' @PluginMethod public void configureCloudProvider(',' @PluginMethod public void configureProvider('].map(start=>method(plugin,start).replace('@PluginMethod ','')).join('\n');
 files.push(write('ai/elizaresearch/alphaphone/ConfigurationBridge.java',`package ai.elizaresearch.alphaphone;import com.getcapacitor.*;import static ai.elizaresearch.alphaphone.AlphaLocalAgentPlugin.*;class ConfigurationBridge {boolean disposed;static final Object lifecycleLock=AlphaLocalAgentPlugin.lifecycleLock;class Workers{java.util.List<Runnable> queued=new java.util.ArrayList<>();void execute(Runnable task){queued.add(task);}}Workers workers=new Workers();android.content.Context getContext(){return CredentialRetirementTest.context;}boolean runtimePackaged(){return true;}${configMethods}}`));
 files.push(write('ai/elizaresearch/alphaphone/BuildConfig.java','package ai.elizaresearch.alphaphone;class BuildConfig {static final boolean ELIZA_DEV_ALLOW_TEST_MOCKS=false;}'));
 files.push(write('ai/elizaresearch/alphaphone/ElizaAgentService.java',`package ai.elizaresearch.alphaphone;import org.json.*;import ai.eliza.plugins.securestore.nativeonly.JsonCredentialSlots;class ElizaAgentService {static int stops,starts;static boolean service,socket,throwStop,confirmStop=true;static long request;static boolean proof;static long stopForCredentialChange(android.content.Context c){proof=false;stop(c);proof=confirmStop;return ++request;}static boolean isCredentialShutdownConfirmed(long value){return value==request&&proof;}static String state="dead";static Runnable observe=()->{};static String localAgentToken(){return "fixture-root";}static void start(android.content.Context c){starts++;}static void stop(android.content.Context c){if(Thread.holdsLock(JsonCredentialSlots.LOCK))throw new AssertionError("Stop holds vault lock");stops++;if(throwStop)throw new IllegalStateException("Stop unavailable");if(confirmStop){state="dead";service=socket=false;}}static JSONObject getLocalAgentBootState(android.content.Context c)throws Exception{if(Thread.holdsLock(JsonCredentialSlots.LOCK)||Thread.holdsLock(AlphaLocalAgentPlugin.lifecycleLock))throw new AssertionError("Shutdown observation holds lock");observe.run();return new JSONObject().put("state",state).put("serviceActive",service).put("socketListening",socket);}}`));
 files.push(write('ai/elizaresearch/alphaphone/CredentialRetirementTest.java',`package ai.elizaresearch.alphaphone;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import java.net.*;import java.io.*;import org.json.*;import ai.eliza.plugins.securestore.nativeonly.JsonCredentialSlots;
public class CredentialRetirementTest {
 static final String CLOUD="cloud:production",PROVIDER="local-agent-provider:v1",ID="d32f7f34-962b-47b7-8f0d-f2fe7f12610a",USER="cf67e311-fec4-40a9-87fa-c6f02f6f11f0",ORG="90b3f419-2590-4276-87ae-0e3c2f61ed1a";static int cases;static android.content.Context context=new android.content.Context();static AlphaCredentialStore store=new AlphaCredentialStore(context);
 interface Task{void run()throws Exception;}static void check(boolean b,String message){if(!b)throw new AssertionError(message);}static void refuses(Task task)throws Exception{try{task.run();}catch(Exception expected){return;}throw new AssertionError("Expected refusal");}
 static String credential(String token)throws Exception{return new JSONObject().put("credentialId",ID).put("token",token).put("userId",USER).put("organizationId",ORG).toString();}
 static void bind()throws Exception{AlphaLocalAgentPlugin.bindCloudProvider(store,ID,AlphaLocalAgentPlugin.CLOUD_PROVIDER_MODEL);}
 static class FakeConnection extends HttpURLConnection {
  static String response;static int code=200,calls;static Runnable after=()->{};static boolean disconnected;FakeConnection(URL u){super(u);calls++;}public void connect(){}public boolean usingProxy(){return false;}public void disconnect(){disconnected=true;}public int getResponseCode(){check(!Thread.holdsLock(JsonCredentialSlots.LOCK)&&!Thread.holdsLock(AlphaLocalAgentPlugin.lifecycleLock),"Identity request holds mutation lock");check(url.toString().equals("https://api.eliza.app/api/v1/user"),"Wrong Cloud origin/path");check(getRequestMethod().equals("GET")&&!getInstanceFollowRedirects()&&!getUseCaches()&&getConnectTimeout()==20000&&getReadTimeout()==20000,"Unbounded/redirected transport");check(getRequestProperty("Authorization").equals("Bearer synthetic-token"),"Wrong protected credential");after.run();return code;}public InputStream getInputStream(){return new ByteArrayInputStream(response.getBytes(java.nio.charset.StandardCharsets.UTF_8));}public long getContentLengthLong(){return -1;}
 }
 static void reset()throws Exception{JsonCredentialSlots.values.clear();JsonCredentialSlots.failWrite=null;AlphaLocalAgentPlugin.lifecycleEpoch++;AlphaLocalAgentPlugin.credentialMutationEpoch=-1;AlphaLocalAgentPlugin.credentialShutdownRequest=-1;AlphaLocalAgentPlugin.accepting=true;AlphaLocalAgentPlugin.stopping=false;AlphaLocalAgentPlugin.ownerToken="owned";ElizaAgentService.stops=ElizaAgentService.starts=0;ElizaAgentService.service=ElizaAgentService.socket=ElizaAgentService.throwStop=false;ElizaAgentService.state="dead";ElizaAgentService.confirmStop=true;ElizaAgentService.observe=()->{};FakeConnection.code=200;FakeConnection.after=()->{};FakeConnection.response=new JSONObject().put("success",true).put("data",new JSONObject().put("id",USER).put("organization_id",ORG)).toString();store.writeCredentialSlot(CLOUD,credential("synthetic-token"));bind();ElizaAgentService.stops=0;ElizaAgentService.state="listening";ElizaAgentService.service=ElizaAgentService.socket=true;}
 static Thread async(Task task,AtomicReference<Throwable> failure){Thread thread=new Thread(()->{try{task.run();}catch(Throwable e){failure.set(e);}});thread.start();return thread;}
 public static void main(String[] args)throws Exception {
  URL.setURLStreamHandlerFactory(protocol->protocol.equals("https")?new URLStreamHandler(){protected URLConnection openConnection(URL url){return new FakeConnection(url);}}:null);
  reset();String original=store.readCredentialSlot(CLOUD),provider=store.readCredentialSlot(PROVIDER),gen=store.providerAdmissionGeneration();
  check(store.providerAdmissionSnapshot().getString("accountRef").contains(USER)&&!store.providerAdmissionSnapshot().getString("accountRef").contains(ID),"Credential handle used as account identity");cases++;
  for(String field:new String[]{"state","service","socket"}){reset();original=store.readCredentialSlot(CLOUD);provider=store.readCredentialSlot(PROVIDER);ElizaAgentService.state=field.equals("state")?"ready":"dead";ElizaAgentService.service=field.equals("service");ElizaAgentService.socket=field.equals("socket");ElizaAgentService.confirmStop=false;refuses(()->store.writeCredentialSlot(CLOUD,credential("replacement-token")));check(original.equals(store.readCredentialSlot(CLOUD))&&provider.equals(store.readCredentialSlot(PROVIDER)),"Unconfirmed shutdown overwrote credential/provider");check(!AlphaLocalAgentPlugin.accepting&&AlphaLocalAgentPlugin.ownerToken==null,"Requests/enrollment remained live");cases++;}
  reset();original=store.readCredentialSlot(CLOUD);ElizaAgentService.throwStop=true;refuses(()->store.removeCredentialSlot(CLOUD));check(original.equals(store.readCredentialSlot(CLOUD)),"Stop failure deleted credential");cases++;
  reset();gen=store.providerAdmissionGeneration();String metadata=new JSONObject(store.readCredentialSlot(CLOUD)).put("expiresAt",System.currentTimeMillis()+600000).put("email","synthetic@example.invalid").toString();store.writeCredentialSlot(CLOUD,metadata);bind();check(gen.equals(store.providerAdmissionGeneration())&&ElizaAgentService.stops==0,"Logical metadata restore stopped runtime/retired generation");cases++;
  reset();store.writeCredentialSlot(CLOUD,credential("replacement-token"));check(ElizaAgentService.stops==1&&store.providerAdmissionGeneration()==null&&!AlphaLocalAgentPlugin.accepting,"Replacement did not stop/retire");cases++;
  reset();store.removeCredentialSlot(CLOUD);check(ElizaAgentService.stops==1&&store.providerAdmissionGeneration()==null,"Logout did not stop/retire");cases++;
  reset();String old=store.readCredentialSlot(PROVIDER);store.removeCredentialSlot(CLOUD);store.writeCredentialSlot(CLOUD,credential("synthetic-token"));store.writeCredentialSlot(PROVIDER,old);refuses(()->store.providerAdmissionSnapshot());cases++;
  reset();store.writeCredentialSlot(CLOUD,new JSONObject(credential("synthetic-token")).put("userId","forged-owner").put("organizationId","forged-org").toString());bind();check(store.providerAdmissionSnapshot().getString("accountRef").contains(USER)&&!store.providerAdmissionSnapshot().getString("accountRef").contains("forged"),"Renderer identity became authority");cases++;
  reset();for(Object bad:new Object[]{"not-a-uuid",123,JSONObject.NULL}){FakeConnection.response=new JSONObject().put("success",true).put("data",new JSONObject().put("id",bad)).toString();refuses(()->bind());}check(ElizaAgentService.stops==0,"Invalid identity changed runtime");cases++;
  reset();FakeConnection.code=302;refuses(()->bind());check(ElizaAgentService.stops==0,"Redirect configured identity");cases++;
  reset();FakeConnection.after=()->{try{store.writeCredentialSlot(CLOUD,credential("replacement-token"));}catch(Exception e){throw new RuntimeException(e);}};refuses(()->bind());check(store.providerAdmissionGeneration()==null,"Held identity bound replacement credential");cases++;
  reset();CountDownLatch entered=new CountDownLatch(1),release=new CountDownLatch(1);AtomicReference<Throwable> failure=new AtomicReference<>();AtomicBoolean first=new AtomicBoolean(true);ElizaAgentService.observe=()->{if(first.getAndSet(false)){entered.countDown();try{check(release.await(5,TimeUnit.SECONDS),"Held stop timeout");}catch(InterruptedException e){throw new RuntimeException(e);}}};Thread replacing=async(()->store.writeCredentialSlot(CLOUD,credential("replacement-token")),failure);check(entered.await(5,TimeUnit.SECONDS),"No shutdown observation");com.getcapacitor.PluginCall launch=new com.getcapacitor.PluginCall("","");new AlphaLocalAgentPlugin().start(launch);check(launch.rejected==1&&ElizaAgentService.starts==0,"Actual start crossed credential barrier");store.writeCredentialSlot(CLOUD,credential("newer-winner-token"));release.countDown();replacing.join(5000);check(!replacing.isAlive()&&failure.get()!=null&&store.readCredentialSlot(CLOUD).contains("newer-winner-token")&&ElizaAgentService.starts==0,"Old held write/launch replaced winner");cases++;
  reset();CountDownLatch entered2=new CountDownLatch(1),release2=new CountDownLatch(1);AtomicReference<Throwable> teardownFailure=new AtomicReference<>();AtomicBoolean alive=new AtomicBoolean(true);AlphaCredentialStore owned=new AlphaCredentialStore(context,()->{if(!alive.get())throw new IllegalStateException("Destroyed");});ElizaAgentService.observe=()->{entered2.countDown();try{release2.await(5,TimeUnit.SECONDS);}catch(InterruptedException e){throw new RuntimeException(e);}};Thread tearing=async(()->owned.removeCredentialSlot(CLOUD),teardownFailure);entered2.await(5,TimeUnit.SECONDS);alive.set(false);release2.countDown();tearing.join(5000);check(teardownFailure.get()!=null&&store.readCredentialSlot(CLOUD)!=null,"Destroyed queued write committed");cases++;
  reset();ElizaAgentService.observe=()->AlphaLocalAgentPlugin.retire();refuses(()->store.removeCredentialSlot(CLOUD));check(store.readCredentialSlot(CLOUD)!=null,"Retired epoch wrote credential");cases++;
  reset();String selected=store.readCredentialSlot(PROVIDER);store.writeCredentialSlot(PROVIDER,LocalAgentProviderAdmission.withoutAdmission(selected));refuses(()->store.providerAdmissionSnapshot());cases++;
  reset();check(!store.providerAdmissionSnapshot().toString().contains("synthetic-token")&&!store.providerAdmissionSnapshot().toString().contains("admissionFingerprint"),"Private credential leaked");cases++;
  reset();ConnectionMutationBridge bridge=new ConnectionMutationBridge();com.getcapacitor.PluginCall staleWrite=new com.getcapacitor.PluginCall(CLOUD,credential("old-queued-token")),newWrite=new com.getcapacitor.PluginCall(CLOUD,credential("new-queued-token"));bridge.secureWrite(staleWrite);bridge.secureWrite(newWrite);bridge.queued.get(0).run();check(staleWrite.rejected==1&&ElizaAgentService.stops==0,"Old queued write admitted");bridge.queued.get(1).run();check(newWrite.resolved==1&&store.readCredentialSlot(CLOUD).contains("new-queued-token"),"New queued winner lost");cases++;
  reset();ConnectionMutationBridge destroyed=new ConnectionMutationBridge();com.getcapacitor.PluginCall removal=new com.getcapacitor.PluginCall(CLOUD,null);destroyed.secureRemove(removal);destroyed.destroyed=true;destroyed.queued.get(0).run();check(removal.rejected==1&&store.readCredentialSlot(CLOUD)!=null&&ElizaAgentService.stops==0,"Queued destroyed removal dispatched");cases++;
  reset();ConnectionMutationBridge cross=new ConnectionMutationBridge();ConfigurationBridge configuration=new ConfigurationBridge();com.getcapacitor.PluginCall oldConfig=new com.getcapacitor.PluginCall("","");oldConfig.data.put("credentialId",ID);oldConfig.data.put("model",AlphaLocalAgentPlugin.CLOUD_PROVIDER_MODEL);configuration.configureCloudProvider(oldConfig);com.getcapacitor.PluginCall latestRemove=new com.getcapacitor.PluginCall(CLOUD,null);cross.secureRemove(latestRemove);int requests=FakeConnection.calls;configuration.workers.queued.get(0).run();check(oldConfig.rejected==1&&FakeConnection.calls==requests,"Old config sent identity after newer logout intent");cross.queued.get(0).run();check(latestRemove.resolved==1&&store.readCredentialSlot(CLOUD)==null,"Cross-plugin winner lost");cases++;
  reset();ConfigurationBridge closingConfig=new ConfigurationBridge();com.getcapacitor.PluginCall closedConfig=new com.getcapacitor.PluginCall("","");closedConfig.data.put("credentialId",ID);closedConfig.data.put("model",AlphaLocalAgentPlugin.CLOUD_PROVIDER_MODEL);closingConfig.configureCloudProvider(closedConfig);closingConfig.disposed=true;requests=FakeConnection.calls;closingConfig.workers.queued.get(0).run();check(closedConfig.rejected==1&&requests==FakeConnection.calls,"Destroyed config sent identity");cases++;
  reset();String prior=store.providerAdmissionGeneration();FakeConnection.response=new JSONObject().put("success",true).put("data",new JSONObject().put("id",UUID.randomUUID().toString())).toString();bind();check(!prior.equals(store.providerAdmissionGeneration())&&ElizaAgentService.stops==1&&!store.providerAdmissionSnapshot().getString("accountRef").contains(ORG),"Verified account change retained binding or guessed organization");cases++;
  reset();ElizaAgentService.state="dead";ElizaAgentService.service=ElizaAgentService.socket=false;store.removeCredentialSlot(CLOUD);check(ElizaAgentService.stops==1&&store.readCredentialSlot(CLOUD)==null,"Cold credential write omitted strict absence proof");cases++;
  reset();ConnectionMutationBridge heldBridge=new ConnectionMutationBridge();com.getcapacitor.PluginCall heldOld=new com.getcapacitor.PluginCall(CLOUD,credential("old-held-token")),heldNew=new com.getcapacitor.PluginCall(CLOUD,credential("new-held-token"));heldBridge.secureWrite(heldOld);ElizaAgentService.observe=()->{ElizaAgentService.observe=()->{};heldBridge.secureWrite(heldNew);};heldBridge.queued.get(0).run();check(heldOld.rejected==1&&store.readCredentialSlot(CLOUD).contains("synthetic-token"),"Superseded held public write committed");heldBridge.queued.get(1).run();check(heldNew.resolved==1&&store.readCredentialSlot(CLOUD).contains("new-held-token"),"Held public winner lost");cases++;
  reset();ConfigurationBridge heldConfiguration=new ConfigurationBridge();ConnectionMutationBridge logoutBridge=new ConnectionMutationBridge();com.getcapacitor.PluginCall heldConfigure=new com.getcapacitor.PluginCall("","");heldConfigure.data.put("credentialId",ID);heldConfigure.data.put("model",AlphaLocalAgentPlugin.CLOUD_PROVIDER_MODEL);com.getcapacitor.PluginCall heldLogout=new com.getcapacitor.PluginCall(CLOUD,null);heldConfiguration.configureCloudProvider(heldConfigure);FakeConnection.after=()->logoutBridge.secureRemove(heldLogout);String protectedBefore=store.readCredentialSlot(PROVIDER);heldConfiguration.workers.queued.get(0).run();check(heldConfigure.rejected==1&&protectedBefore.equals(store.readCredentialSlot(PROVIDER))&&ElizaAgentService.stops==0,"Held identity ignored newer logout intent");FakeConnection.after=()->{};logoutBridge.queued.get(0).run();check(heldLogout.resolved==1&&store.readCredentialSlot(CLOUD)==null,"Held logout failed");cases++;
  reset();protectedBefore=store.readCredentialSlot(PROVIDER);FakeConnection.response=" ".repeat(2*1024*1024+1);refuses(()->bind());check(protectedBefore.equals(store.readCredentialSlot(PROVIDER))&&FakeConnection.disconnected&&ElizaAgentService.stops==0,"Oversized identity mutated binding/leaked connection");cases++;
  reset();protectedBefore=store.readCredentialSlot(CLOUD);refuses(()->store.writeCredentialSlot(CLOUD,null));check(protectedBefore.equals(store.readCredentialSlot(CLOUD))&&ElizaAgentService.stops==0,"Invalid write became logout");cases++;
  reset();ElizaAgentService.throwStop=true;refuses(()->store.removeCredentialSlot(CLOUD));com.getcapacitor.PluginCall refusedStart=new com.getcapacitor.PluginCall("","");new AlphaLocalAgentPlugin().start(refusedStart);check(refusedStart.rejected==1&&ElizaAgentService.starts==0,"Uncertain stop dispatch admitted new start");cases++;
  reset();ElizaAgentService.state="dead";ElizaAgentService.service=ElizaAgentService.socket=false;ElizaAgentService.confirmStop=false;String beforeUnknown=store.readCredentialSlot(CLOUD);refuses(()->store.writeCredentialSlot(CLOUD,credential("replacement-token")));com.getcapacitor.PluginCall status=new com.getcapacitor.PluginCall("","");new AlphaLocalAgentPlugin().getStatus(status);check(status.resolved==1&&((JSONObject)status.result).getString("state").equals("stopping")&&beforeUnknown.equals(store.readCredentialSlot(CLOUD)),"Weak triad claimed stopped or overwrote credential without proof");cases++;
  System.out.println("PASS "+cases+" actual Java credential lifecycle/identity cases");
 }
}`));
 execFileSync(path.join(java,'bin/javac'),['--release','17','-cp',jar,'-d',dir,...files],{timeout:20000});
 const output=execFileSync(path.join(java,'bin/java'),['-cp',dir+path.delimiter+jar,'ai.elizaresearch.alphaphone.CredentialRetirementTest'],{encoding:'utf8',timeout:30000});t.diagnostic(output.trim());assert.match(output,/PASS 30 actual Java credential lifecycle\/identity cases/);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});

test('actual pinned Core boot-state refuses an active service, surviving socket or launch worker at credential commit',t=>{
 const core=fs.readFileSync('vendor/eliza/packages/app/platforms/android/app/src/main/java/ai/elizaos/app/ElizaAgentService.java','utf8');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'alpha-core-shutdown-boundary-'));
 const java=process.env.JAVA_HOME||'/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home';
 const jar=process.env.ALPHA_JSON_JAR||fs.globSync(path.join(os.homedir(),'.gradle/caches/modules-2/files-2.1/org.json/json/20250517/*/json-20250517.jar'))[0];assert.ok(jar);
 try{
 fs.writeFileSync(path.join(dir,'ElizaAgentService.java'),`import org.json.*;
public class ElizaAgentService {
 static class Context {static final int MODE_PRIVATE=0;static long stamp;Context getSharedPreferences(String name,int mode){return this;}long getLong(String name,long fallback){return stamp;}}
 static class IpcStartupRecovery {static final String RETENTION_LIMIT="retention-limit";}
 static final String EXIT_INFO_PREFS="fixture",DETACHED_LAUNCH_STAMP_KEY="fixture";static final long AGENT_BOOT_GRACE_MS=120000;
 static ElizaAgentService activeInstance;static boolean socket;final Object processLock=new Object();String currentStatus="unknown";int restartAttempts;boolean detachedAgentMode;long detachedLaunchStartedAtMs;Thread startWorker;
 static void initializeLocalAgentTransport(Context c){}static boolean isLocalAgentSocketListening(){return socket;}
 ${method(core,'    public static JSONObject getLocalAgentBootState(')}
 ${method(core,'    private static boolean isTerminalBootStatus(')}
 ${method(plugin,' private static boolean shutdownConfirmed(')}
 static void check(boolean value){if(!value)throw new AssertionError("Actual Core lifecycle boundary mismatch");}
 public static void main(String[] args)throws Exception {
  activeInstance=new ElizaAgentService();activeInstance.currentStatus="fatal";check(getLocalAgentBootState(null).getString("state").equals("dead")&&!shutdownConfirmed(getLocalAgentBootState(null)));
  activeInstance=null;socket=true;check(!shutdownConfirmed(getLocalAgentBootState(null)));
  socket=false;Context.stamp=System.currentTimeMillis();check(getLocalAgentBootState(new Context()).getString("state").equals("booting")&&!shutdownConfirmed(getLocalAgentBootState(new Context())));
  Context.stamp=0;activeInstance=new ElizaAgentService();Object wait=new Object();Thread worker=new Thread(()->{synchronized(wait){try{wait.wait(5000);}catch(InterruptedException ignored){}}});worker.start();activeInstance.startWorker=worker;try{check(getLocalAgentBootState(null).getString("state").equals("booting")&&!shutdownConfirmed(getLocalAgentBootState(null)));}finally{worker.interrupt();worker.join(5000);}
  activeInstance=new ElizaAgentService();check(!shutdownConfirmed(getLocalAgentBootState(null)));
  activeInstance=null;check(shutdownConfirmed(getLocalAgentBootState(null)));
  Context.stamp=System.currentTimeMillis()-240000;check(shutdownConfirmed(getLocalAgentBootState(new Context())));
  check(!shutdownConfirmed(new JSONObject().put("state","dead"))&&!shutdownConfirmed(null));
  System.out.println("PASS 8 actual Core shutdown-status boundary cases");
 }
}`);
 execFileSync(path.join(java,'bin/javac'),['--release','17','-cp',jar,'-d',dir,path.join(dir,'ElizaAgentService.java')],{timeout:20000});
 const output=execFileSync(path.join(java,'bin/java'),['-cp',dir+path.delimiter+jar,'ElizaAgentService'],{encoding:'utf8',timeout:20000});assert.match(output,/PASS 8 actual Core/);t.diagnostic(output.trim());
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
