import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
const source=fs.readFileSync('apps/app/src/prototype/agent-adapter.ts','utf8');
const origin={version:1,requestId:'original-request',conversationId:'original-room',inReplyTo:'original-user'},digest='a'.repeat(64),hint={...origin,proposalId:'proposal',digest,attemptId:'attempt'};
function fixture(){
 const f={room:'original-room',account:'cloud-account',environment:'production',session:{origin:'https://owned.invalid',ownerId:'owner',agentId:'agent',sessionId:'session'},context:{view:'home',revision:1,sensitive:false},completions:0,cancels:0,resumes:0,queue:[],holdUpdates:false,document:{hidden:false},reply:{...origin,messageId:'canonical-answer',text:'Actual canonical original-request answer'}};
 const binding=()=>({conversationId:f.room,session:{...f.session},connectionEpoch:1,cloudAccount:JSON.stringify([f.account,f.environment])});
 const controller={getSnapshot:()=>({session:f.session,open:false}),readReplyBinding:room=>{assert.equal(room,f.room);return binding();},readReplyCurrent:b=>JSON.stringify(b)===JSON.stringify(binding()),async completeReadReply(_hint,_binding,signal){f.completions++;if(f.held)await f.held;signal.throwIfAborted();if(f.failure)throw Error('Connection lost after admission');return f.reply;},async cancelReadReply(){f.cancels++;},async approvePendingAction(){f.approvals=(f.approvals||0)+1;return {proposalId:'proposal',status:'succeeded',summary:'Shared the reviewed note.',readReply:hint};},actionReceipt:async()=>null};
 const shell={live:true,state:{view:null,chat:'full',draft:'Keep unsent text',msgs:[{id:origin.inReplyTo,from:'user',text:'Original request',messageBinding:{conversationId:f.room,session:f.session}},{id:'review-card',from:'agent',text:'Review',card:{proposalId:'proposal',recovered:true,proposalSession:f.session,expiresAt:Date.now()+60000}}]},messageReplyTarget:{id:'keep-reply'},messageEditTarget:{id:'keep-edit'},S(){return this.state;},setState(patch,done){const apply=()=>{const next=typeof patch==='function'?patch(this.state):patch;if(next)Object.assign(this.state,next);done?.();};if(f.holdUpdates)f.queue.push(apply);else apply();},agentSay(){f.localSummaries=(f.localSummaries||0)+1;},toast(){},resumeReadReplyVoice(){f.resumes++;}};
 const p={};const box={p,connectionController:controller,alphaClient:{getState:()=>({context:f.context}),approve:controller.approvePendingAction},document:f.document,structuredClone,AbortController,crypto,Date,context(){}};
 const helpers=source.slice(source.indexOf('  function retainReadReply('),source.indexOf('  function recoverPendingActions('));
 const card=source.slice(source.indexOf('  p.cardAct ='),source.indexOf('  p.startVoice =',source.indexOf('  p.cardAct =')));
 vm.runInNewContext(stripTypeScriptTypes(helpers+card,{mode:'transform'})+'\nglobalThis.retain=retainReadReply;globalThis.complete=completeReadReply;',box);Object.assign(shell,p);
 const proposal={id:'proposal',readReply:{origin,digest}};box.retain(shell,proposal);
 return Object.assign(f,{shell,box,controller,retain:()=>box.retain(shell,proposal),complete:()=>box.complete(shell,{proposalId:'proposal',status:'succeeded',summary:'Shared',readReply:hint}),approve:()=>shell.cardAct(shell.state.msgs.find(m=>m.id==='review-card')),flush(){const q=f.queue.splice(0);for(const update of q)update();}});
}
const settle=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
test('approval projects exactly one canonical original-room reply and preserves draft, reply/edit targets and receipt card',async()=>{const f=fixture(),draft=f.shell.state.draft,reply=f.shell.messageReplyTarget,edit=f.shell.messageEditTarget;await f.approve();assert.equal(f.completions,1);assert.equal(f.localSummaries||0,0);const row=f.shell.state.msgs.find(m=>m.id==='canonical-answer');assert.equal(row.inReplyTo,origin.inReplyTo);assert.equal(row.messageBinding.conversationId,origin.conversationId);assert.equal(f.shell.state.msgs.find(m=>m.id==='review-card').card.done,true);assert.equal(f.shell.state.draft,draft);assert.equal(f.shell.messageReplyTarget,reply);assert.equal(f.shell.messageEditTarget,edit);assert.equal(f.resumes,1);await f.approve();assert.equal(f.completions,1);});
for(const change of ['account','environment','room','session','private','hidden','unmount','stop'])test(`held original answer cannot publish after ${change}`,async()=>{const f=fixture(),held=Promise.withResolvers();f.held=held.promise;const pending=f.complete(),rejected=assert.rejects(pending);await settle();if(change==='account')f.account='replacement';if(change==='environment')f.environment='staging';if(change==='room')f.room='replacement';if(change==='session')f.session={...f.session,sessionId:'replacement'};if(change==='private')f.context.sensitive=true;if(change==='hidden')f.document.hidden=true;if(change==='unmount')f.shell.live=false;if(change==='stop')f.shell.cancelReadReplyCompletions();held.resolve();await rejected;assert.equal(f.shell.state.msgs.some(m=>m.id==='canonical-answer'),false);assert.equal(f.resumes,0);assert.equal(f.shell.state.draft,'Keep unsent text');});
test('deferred React reply updater rechecks room ownership at commit',async()=>{const f=fixture();f.holdUpdates=true;const pending=f.complete(),rejected=assert.rejects(pending);await settle();assert.equal(f.queue.length,1);f.room='replacement';f.shell.state.msgs=[];f.flush();await rejected;assert.deepEqual(f.shell.state.msgs,[]);assert.equal(f.resumes,0);});
test('completion uncertainty retains succeeded Shared receipt, no local fake answer and no replay',async()=>{const f=fixture();f.failure=true;await f.approve();const card=f.shell.state.msgs.find(m=>m.id==='review-card').card;assert.equal(card.done,true);assert.equal(card.title,'Completed');assert.match(card.sub,/Shared.*answer is unconfirmed/);assert.equal(f.localSummaries||0,0);await f.approve();assert.equal(f.completions,1);assert.equal(f.resumes,0);});
test('unbound/recovered proposal without original canonical user row cannot autoquote',async()=>{const f=fixture();f.shell.readReplyLeases.clear();f.shell.state.msgs=f.shell.state.msgs.filter(m=>m.from!=='user');f.retain();await f.approve();assert.equal(f.completions,0);assert.equal(f.localSummaries,1);});
test('keyboard/minimized chat preserves eligible same-room text completion with unsent draft unchanged',async()=>{for(const chat of ['input','hidden']){const f=fixture();f.shell.state.chat=chat;await f.complete();assert.equal(f.completions,1);assert.equal(f.shell.state.chat,chat);assert.equal(f.shell.state.draft,'Keep unsent text');}});

test('queued unconfirmed-answer publication cannot touch an old card after a same-session room replacement',async()=>{const f=fixture();f.failure=true;f.shell.setState=function(patch,done){const apply=()=>{const next=typeof patch==='function'?patch(this.state):patch;if(next)Object.assign(this.state,next);done?.();};if(f.holdUpdates)f.queue.push(apply);else apply();};f.holdUpdates=true;await f.approve();f.room='replacement';f.shell.state.msgs=[{id:'review-card',from:'agent',text:'Replacement',card:{title:'Replacement review'}}];f.flush();assert.equal(f.shell.state.msgs[0].card.title,'Replacement review');assert.equal(f.shell.state.msgs[0].card.sub,undefined);});
