import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
test('native reading token is one-use and bound to route, owner, session, expiry and current page',()=>{
 const source=fs.readFileSync('android/app/src/main/java/ai/elizaresearch/alphaphone/BrowserReading.java','utf8');const binding=source.slice(source.indexOf(' static String binding('),source.indexOf(' void review('));const consume=source.slice(source.indexOf(' private boolean valid()'),source.indexOf(' void check()'));const dir=fs.mkdtempSync(path.join(os.tmpdir(),'alpha-reading-token-'));try{fs.writeFileSync(path.join(dir,'TokenHarness.java'),`
import java.util.*;import java.util.function.*;
public class TokenHarness{
 static class BuildConfig{static final boolean DEBUG=false;static final boolean ELIZA_DEV_ALLOW_TEST_MOCKS=false;}static class JSONObject{TreeMap<String,Object> v=new TreeMap<>();JSONObject put(String k,Object x){v.put(k,x);return this;}public String toString(){return v.toString();}}
 static class PluginCall{Map<String,Object> data=new HashMap<>();String getString(String k){return (String)data.get(k);}Long getLong(String k){return (Long)data.get(k);}PluginCall put(String k,Object v){data.put(k,v);return this;}}
 interface Click{void call(Object d,int which);}interface Cancel{void call(Object d);}static class AlertDialog{void show(){}static class Builder{Builder(Object a){}Builder setTitle(String x){return this;}Builder setMessage(String x){return this;}Builder setNegativeButton(String x,Click c){return this;}Builder setOnCancelListener(Cancel c){return this;}AlertDialog create(){return new AlertDialog();}}}
 long generation,timeout;void scheduleTimeout(long expected,long delay){timeout=delay;}Object activity;AlertDialog dialog;BooleanSupplier current=()->true;boolean approved=true;String binding,token="token",text="Exact reviewed passage",requestId;long expires=System.currentTimeMillis()+120000;void cancel(){}
 ${binding}\n${consume}
 static void check(boolean x){if(!x)throw new AssertionError();}interface Attempt{void run()throws Exception;}static void fails(Attempt f)throws Exception{try{f.run();throw new AssertionError("Expected rejection");}catch(IllegalArgumentException|IllegalStateException expected){}}
 static PluginCall local(){return new PluginCall().put("execution","device").put("ownerId","owner").put("sessionId","session").put("expiresAt",System.currentTimeMillis()+60000).put("readingToken","token").put("requestId","request");}
 public static void main(String[] args)throws Exception{
  PluginCall c=local();TokenHarness h=new TokenHarness();h.binding=binding(c);c.put("text","Caller supplied text");check(h.consume(c).equals("Exact reviewed passage"));check(h.text==null&&!h.approved&&h.token==null&&h.generation==1&&h.timeout==20*60*1000&&h.expires>System.currentTimeMillis()+19*60*1000);fails(()->h.consume(c));
  for(String field:new String[]{"ownerId","sessionId","readingToken","execution"}){TokenHarness next=new TokenHarness();PluginCall input=local();next.binding=binding(input);input.put(field,"wrong");fails(()->next.consume(input));}
  TokenHarness stale=new TokenHarness();PluginCall input=local();stale.binding=binding(input);stale.current=()->false;fails(()->stale.consume(input));
  fails(()->binding(local().put("origin","https://remote.invalid")));fails(()->binding(local().put("expiresAt",0L)));fails(()->binding(local().put("expiresAt",System.currentTimeMillis()+300000)));fails(()->binding(local().put("requestId",null).put("ownerId","")));
  PluginCall remote=local().put("execution",null).put("origin","https://remote.invalid");TokenHarness paired=new TokenHarness();paired.binding=binding(remote);check(paired.consume(remote).equals("Exact reviewed passage"));
  System.out.println("PASS native approval token binding");}
}`);const home=process.env.JAVA_HOME||(process.platform==='darwin'?'/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home':'');const bin=n=>home?path.join(home,'bin',n):n;execFileSync(bin('javac'),['--release','11','-d',dir,path.join(dir,'TokenHarness.java')],{stdio:'pipe',timeout:15000});assert.match(execFileSync(bin('java'),['-cp',dir,'TokenHarness'],{encoding:'utf8',timeout:10000}),/^PASS/);}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
