import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
const tick=()=>new Promise(r=>setTimeout(r,0));
function fixture(){const listeners=new Map(),subscriptions=new Set(),document=Object.assign(new EventTarget(),{hidden:false,documentElement:{dataset:{connectionMode:'resident'}}});const f={session:'session',calls:[],stops:[],active:null,execution:'device',open:false};const native={localSpeechStatus:async()=>({ready:true,execution:'device'}),transcribeLocalRecording:async()=>({text:'Synthetic transcript',local:true,execution:'device'}),releaseLocalSpeech:async()=>{},cancel:async()=>{},stopPlayback:async input=>{f.stops.push(input);if(input?.requestId===f.active?.requestId)f.active=null;},addListener:async(event,cb)=>{const set=listeners.get(event)||new Set();set.add(cb);listeners.set(event,set);return {remove:async()=>set.delete(cb)};},synthesizeLocal:async input=>{f.calls.push(input);if(f.synthesis)await f.synthesis();f.active={...input,playbackId:'audio-'+input.requestId};return {...f.active,execution:f.execution};},play:async()=>{f.played=(f.played||0)+1;}};const box={Capacitor:{isPluginAvailable:()=>true,isNativePlatform:()=>true},registerPlugin:()=>native,connectionController:{getSnapshot:()=>({session:{sessionId:f.session},open:f.open}),getCloudClient:()=>null,subscribe:cb=>{subscriptions.add(cb);return ()=>subscriptions.delete(cb);}},document,crypto,AbortController,DOMException,setTimeout,clearTimeout};
for(const [file,name] of [['runtime/local-speech-text.ts','planLocalSpeech'],['local-speech-playback.ts','speakLocalText'],['runtime/local-voice.ts','createOnDeviceVoice']]){const source=fs.readFileSync('apps/app/src/'+file,'utf8').replace(/^import .*;\n/gm,'').replaceAll('export async function','async function').replaceAll('export function','function');vm.runInNewContext('{'+stripTypeScriptTypes(source,{mode:'transform'})+'\nglobalThis.'+name+'='+name+';}',box);}f.voice=box.createOnDeviceVoice();f.native=native;f.document=document;f.changed=()=>{for(const cb of subscriptions)cb();};f.emit=(event,id=f.active?.playbackId)=>{for(const cb of listeners.get(event)||[])cb({playbackId:id});};return f;}
async function until(fn){for(let n=0;n<100&&!fn();n++)await new Promise(r=>setTimeout(r,5));assert.ok(fn());}
test('resident speech waits for its own completion and cleans only its own request',async()=>{const f=fixture();let done=false;const pending=f.voice.speak('Reviewed sentence',new AbortController().signal).then(()=>done=true);await until(()=>f.played===1);f.emit('playbackEnded','unrelated');await tick();assert.equal(done,false);const request=f.active.requestId;f.emit('playbackEnded');await pending;assert.equal(done,true);assert.ok(f.stops.length);assert.ok(f.stops.every(input=>input.requestId===request));});
test('resident cancellation during hung listener setup settles and removes late handles',async()=>{const f=fixture();let release,removed=0;f.native.addListener=()=>new Promise(r=>release=r);const c=new AbortController(),pending=f.voice.speak('Reviewed sentence',c.signal);await until(()=>release);c.abort();await assert.rejects(pending);release({remove:async()=>removed++});await tick();assert.equal(removed,1);assert.equal(f.calls.length,0);});
test('late synthesis after resident cancellation cannot play or clear another consumer',async()=>{const f=fixture();let release;f.synthesis=()=>new Promise(r=>release=r);const c=new AbortController(),pending=f.voice.speak('Reviewed sentence',c.signal);await until(()=>release);c.abort();await assert.rejects(pending);release();await tick();assert.equal(f.played,undefined);assert.ok(f.stops.every(input=>input?.requestId===f.calls[0].requestId));});
test('resident voice preserves provider execution checks before playback',async()=>{const f=fixture();f.execution='hosted';await assert.rejects(f.voice.speak('Reviewed sentence',new AbortController().signal),/Invalid local speech execution/);assert.equal(f.played,undefined);});
test('replacement and hidden-device cancellation settle resident speech',async()=>{for(const mode of ['replace','hidden','chooser']){const f=fixture(),pending=f.voice.speak('Reviewed sentence',new AbortController().signal);await until(()=>f.played===1);const old=f.active;f.active={requestId:'other',playbackId:'other'};if(mode==='replace')f.emit('playbackStopped',old.playbackId);else if(mode==='hidden'){f.document.hidden=true;f.document.dispatchEvent(new Event('visibilitychange'));}else{f.open=true;f.changed();}await assert.rejects(pending);assert.equal(f.active.requestId,'other');assert.ok(f.stops.every(input=>input?.requestId===old.requestId));}});
test('cancelling readiness or transcription never stops unrelated audio',async()=>{for(const kind of ['ready','transcribe']){const f=fixture();f.native[kind==='ready'?'localSpeechStatus':'transcribeLocalRecording']=()=>new Promise(()=>{});const c=new AbortController(),pending=kind==='ready'?f.voice.ready(c.signal):f.voice.transcribe('recording',c.signal);c.abort();await assert.rejects(pending);assert.deepEqual(f.stops,[]);}});
