import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {cloudVoiceViewFixture} from './fixtures/cloud-voice-view.mjs';
import {voiceFakeClock} from './fixtures/shared-batch-voice.mjs';
const flush=f=>f.clock.flush();
async function utterance(f){f.peak=.25;await f.clock.advance(900);f.peak=0;await f.clock.advance(750);await flush(f);}
function fixture(options={}){const clock=voiceFakeClock();return cloudVoiceViewFixture({clock,transcript:'Open the owned view.',holdPlayback:true,...options});}
for(const target of ['notes','calendar','home','inbox','workflows','browser','camera','photos','maps','settings','files'])for(const detent of ['sheet','full'])test(`owned acknowledged ${target} navigation keeps ${detent} voice visible and takes fresh next-turn context`,async()=>{const f=fixture({navigationTarget:target});try{Object.assign(f.shell.state,{view:target==='home'?'notes':null,chat:detent,draft:'Retained typed draft'});const reply={id:'reply'},edit={id:'edit'};f.shell.messageReplyTarget=reply;f.shell.messageEditTarget=edit;await f.shell.startVoice();await utterance(f);assert.equal(f.claims,1);assert.equal(f.acks,1);assert.equal(f.shell.S().view,target==='home'?null:target);assert.equal(f.shell.S().chat,detent);assert.equal(f.renderChat().state,'speaking');assert.equal(f.renderChat().primaryLabel,'Stop voice conversation');assert.equal(f.cloudSpeech,1);const original=JSON.stringify(f.sendInputs[0].context),oldView=f.sendInputs[0].context.view;assert.notEqual(oldView,target);assert.equal(f.shell.S().draft,'Retained typed draft');assert.equal(f.shell.messageReplyTarget,reply);assert.equal(f.shell.messageEditTarget,edit);f.navigationTarget=null;f.finishPlayback();await flush(f);await f.clock.advance(250);assert.equal(f.starts,2);await f.clock.advance(1600);await utterance(f);assert.equal(f.sends,2);assert.equal(f.sendInputs[1].context.view,target);assert.equal(JSON.stringify(f.sendInputs[0].context),original);f.renderChat().discard();await flush(f);}finally{f.close();await flush(f);}});
for(const retirement of ['stop','user-navigation','account','environment','hidden','room','selection','minimize'])test(`held own navigation ACK cannot continue voice after ${retirement}`,async()=>{const f=fixture({navigationTarget:'notes',holdAck:true});try{await f.shell.startVoice();await utterance(f);assert.equal(f.shell.S().view,'notes');assert.equal(f.acks,1);assert.equal(f.cloudSpeech,0);assert.equal(f.renderChat().primaryLabel,'Stop voice conversation');if(retirement==='stop')f.renderChat().discard();else if(retirement==='user-navigation')f.shell.openView('calendar');else if(retirement==='account'){f.account='replacement';f.credential='replacement';f.changed();}else if(retirement==='environment'){f.environment='staging';f.changed();}else if(retirement==='hidden'){f.box.document.hidden=true;f.shell.componentDidUpdate();}else if(retirement==='room'){f.conversation='replacement';f.shell.componentDidUpdate();}else if(retirement==='selection'){f.contextRevision++;f.selectedObject={kind:'note',id:'new-selection',revision:'2'};f.shell.componentDidUpdate();}else f.shell.renderVals().closeChat();f.releaseAck();await flush(f);await f.clock.advance(60000);assert.equal(f.cloudSpeech,0);assert.equal(f.starts,1);assert.equal(f.acks,1);}finally{f.releaseAck?.();f.close();await flush(f);}});
test('Stop while canonical claim is held cannot apply a view or ACK',async()=>{const f=fixture({navigationTarget:'notes',holdClaim:true});try{await f.shell.startVoice();await utterance(f);assert.equal(f.claims,1);f.renderChat().discard();f.releaseClaim();await flush(f);assert.equal(f.shell.S().view,null);assert.equal(f.acks||0,0);assert.equal(f.cloudSpeech,0);await f.clock.advance(60000);assert.equal(f.starts,1);}finally{f.releaseClaim?.();f.close();await flush(f);}});
test('unconfirmed own navigation ACK cannot speak or rearm',async()=>{const f=fixture({navigationTarget:'notes',unknownAck:true});try{await f.shell.startVoice();await utterance(f);assert.equal(f.shell.S().view,'notes');assert.equal(f.cloudSpeech,0);await f.clock.advance(60000);assert.equal(f.starts,1);}finally{f.close();await flush(f);}});

test('selection change interposed after own React callback but before ACK cannot be adopted',async()=>{const f=fixture({navigationTarget:'notes',interposeSelection:true});try{await f.shell.startVoice();await utterance(f);assert.equal(f.cloudSpeech,0);await f.clock.advance(60000);assert.equal(f.starts,1);}finally{f.close();await flush(f);}});

test('ordinary Home remains input while owned visible chat detents are explicit',()=>{const source=fs.readFileSync('apps/app/src/prototype/model.js','utf8'),method=source.slice(source.indexOf('  goHome('),source.indexOf('  openView(')),p=vm.runInNewContext('({'+method+'})');for(const value of [undefined,'hidden',new Event('click'),'sheet','full']){let state;const shell={clear(){},leave(){},S:()=>({secure:false}),setState:next=>state=next};p.goHome.call(shell,value);assert.equal(state.chat,['sheet','full'].includes(value)?value:'input');}});
