import { InboxOperation } from '../runtime/inbox-operation';
import { secureConnectionStore } from '../runtime/native-connection';
import { connectionController } from '../runtime/connection-ui';
import type { GmailInboxCapabilities } from '../runtime/cloud-protocol';
type Bag=Record<string,any>;
/** Explicit provider review; state never enters prototype persistence or agent context. */
export function inboxProviderControls(publish:()=>void,toast:(message:string)=>void){
 let editor:((proposal:Bag,reference:{draftId:string;providerDigest:string})=>Promise<boolean>)|null=null;
 let selected='',session='',epoch=0,operation:InboxOperation|null=null,caps:GmailInboxCapabilities|null=null,busy=false,visible=false,status='';
 function reset(){epoch++;operation?.stop();operation=null;selected=session='';caps=null;busy=visible=false;status='';}
 async function bind(grant:string){
  const binding=connectionController.getCloudClient(),account=connectionController.getSnapshot().cloudAccount;
  if(binding&&grant===selected&&binding.sessionId===session&&operation){const token=epoch;try{const next=await binding.client.gmailInboxCapabilities(grant,new AbortController().signal);if(token===epoch){caps=next;publish();}}catch{if(token===epoch){caps=null;publish();}}return;}
  reset();if(!binding||!account||!grant||document.documentElement.dataset.connectionMode==='mock')return;
  selected=grant;session=binding.sessionId;const token=epoch;
  operation=new InboxOperation({owner:JSON.stringify([account.environment,account.userId,account.organizationId||'']),grantId:grant,store:secureConnectionStore,client:binding.client,active:()=>epoch===token&&session===connectionController.getCloudClient()?.sessionId&&document.documentElement.dataset.connectionMode!=='mock'});
  try{await operation.load();if(token!==epoch)return;
   if(operation.snapshot()){status='Saved mail operation. Check its exact review and receipt before continuing.';visible=true;}
   const next=await binding.client.gmailInboxCapabilities(grant,new AbortController().signal);if(token!==epoch)return;caps=next;
  }catch{if(token===epoch)status='Provider actions unavailable. Your local drafts remain on this device.';}
  if(token===epoch)publish();
 }
 async function run(task:()=>Promise<unknown>){if(busy||!operation)return;const token=epoch;busy=true;publish();try{await task();if(token===epoch)status='';}catch(error){if(token===epoch){status=error instanceof Error?error.message:'Mail operation unavailable';toast(status);}}finally{if(token===epoch){busy=false;publish();}}}
 async function prepare(proposal:Bag){if(!operation)return;const kind=proposal.kind;if(!(kind==='send'?caps?.send:kind.startsWith('draft-')?caps?.providerDrafts:caps?.mailboxMutations)){toast('The selected account has not granted this provider action.');return;}visible=true;await run(()=>operation!.prepare(proposal));}
 async function editSavedDraft(){await run(async()=>{const record=operation!.snapshot(),reference=record?.receipt?.providerResult,binding=connectionController.getCloudClient();if(!record||!binding||!reference||typeof reference.draftId!=='string'||typeof reference.providerDigest!=='string')throw new Error('No provider draft receipt');const current=await binding.client.gmailDraft(selected,reference.draftId,new AbortController().signal);if(current.providerDigest!==reference.providerDigest)throw new Error('Gmail draft changed outside this app. The saved content will not overwrite it. Open Gmail to inspect the conflict.');if(!await editor?.(record.proposal,current))throw new Error('Save or discard changed local edits before opening this provider draft.');await operation!.clear();visible=false;});}
 async function followup(kind:'delete-draft'|'undo'){await run(async()=>{const record=operation!.snapshot(),result=record?.receipt?.providerResult;if(!record||!result)throw new Error('No confirmed provider result');const proposal=kind==='delete-draft'?{kind:'draft-delete',draftId:result.draftId,expectedDigest:result.providerDigest,confirmPermanentDelete:true}:{kind:record.proposal.kind==='archive'?'unarchive':'untrash',messageId:result.messageId,expectedHistoryId:result.historyId};await operation!.clear();await operation!.prepare(proposal);});}
 return {bind,reset,prepare,setEditor:(value:typeof editor)=>{editor=value;},capabilities:()=>caps,
 close(){if(!visible)return false;visible=false;publish();return true;},
 chips(chip:(label:string,action:()=>void)=>Bag){return operation?.snapshot()?[chip('Mail review / receipt',()=>{visible=true;publish();})]:[];},
 render(){const record=operation?.snapshot(),review=record?.review;const uncertain=record&&(record.phase==='dispatching'||record.receipt?.state==='outcome-unknown'||record.receipt?.state==='dispatched');return {providerReview:visible,provider:{busy,status:status||(uncertain?'Delivery outcome is unknown. Check the saved receipt; do not send this message again.':record?.receipt?.state==='succeeded'?'Provider confirmed this operation.':record?.receipt?.state==='rejected'?'Provider rejected this operation.':'Review every field before confirming. No mail has been sent.'),
  title:({send:'Send email','draft-create':'Save Gmail draft','draft-replace':'Replace Gmail draft','draft-delete':'Delete Gmail draft',archive:'Archive message',unarchive:'Restore to Inbox',trash:'Move message to Trash',untrash:'Restore from Trash'} as Bag)[String(review?.kind||record?.proposal.kind)]||'Mail review',confirmLabel:review?.kind==='send'?'Send this email':review?.kind==='draft-delete'?'Permanently delete draft':'Confirm this change',replacementWarning:review?.kind==='draft-replace',deletionWarning:review?.kind==='draft-delete',clearLabel:record?.phase==='review'||record?.phase==='preparing'?'Cancel unsent review':'Close receipt',kind:review?.kind||record?.proposal.kind||'Mail operation',from:review?.from||'',to:Array.isArray(review?.to)?review.to.join(', '):'',cc:Array.isArray(review?.cc)?review.cc.join(', '):'',bcc:Array.isArray(review?.bcc)?review.bcc.join(', '):'',subject:review?.subject||'',body:review?.bodyText||'',target:review?.messageId||review?.replyMessageId||review?.draftId||'',requestId:record?.requestId||'',result:record?.receipt?.providerResult?JSON.stringify(record.receipt.providerResult):'',attachments:Array.isArray(review?.attachments)&&review.attachments.length?review.attachments.map((a:Bag)=>`${a.name} · ${a.mimeType} · ${a.size} bytes · SHA-256 ${a.sha256}`).join('\n'):'No attachments.',
  canEditDraft:record?.receipt?.state==='succeeded'&&['draft-create','draft-replace'].includes(record.receipt.kind),editDraft:()=>void editSavedDraft(),deleteDraft:()=>void followup('delete-draft'),canUndo:record?.receipt?.state==='succeeded'&&['archive','trash'].includes(record.receipt.kind)&&typeof record.receipt.providerResult?.historyId==='string',undo:()=>void followup('undo'),
  confirm:()=>void run(()=>operation!.confirm()),canConfirm:!!record&&record.phase==='review'&&record.receipt?.state==='prepared',check:()=>void run(()=>operation!.refresh()),reload:()=>void run(()=>operation!.reloadReview()),canReload:record?.phase==='preparing',clear:()=>void run(async()=>{await operation!.clear();visible=false;}),canClear:record?.phase==='review'||record?.phase==='preparing'||['succeeded','rejected'].includes(record?.receipt?.state||''),close:()=>{visible=false;publish();}}};}
 };
}
