import './scan-dialog.css';
import {copyScanTextLayers} from '../browser/scan-draft';
import {recognizeLocalText} from './local-ocr';
import {exportScanPdf,ScanPdfExportError} from './scan-pdf';
import type {ScanTextLine} from './scan-text-layer';
/** Saved lines are presented for review; persistence and export both require explicit actions. */
type ReviewResult={status:string;message:string;textLayers?:ScanTextLine[][]};
export function reviewSearchableScan(input:Blob[],parent:AbortSignal,saved?:(ScanTextLine[]|null)[]):Promise<ReviewResult|undefined>{
 const images=[...input],initial=copyScanTextLayers(saved,input.length);return new Promise(resolve=>{
  const controller=new AbortController(),dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Review searchable PDF');dialog.className='scan-dialog';
  const previous=document.activeElement,heading=document.createElement('h2');heading.textContent='Review searchable PDF';const help=document.createElement('p');help.textContent='English recognition runs locally on each current page. Correct each line before downloading. These reviewed lines become selectable, searchable text over the unchanged images. Keep reviewed text to return to the document, then save its draft to retain your corrections. Notes stay unchanged. Clear a line to exclude it from search.';
  const status=document.createElement('p');status.setAttribute('role','status');const pages=document.createElement('div'),fields:HTMLTextAreaElement[]=[],layers:ScanTextLine[][]=[],urls:string[]=[];let closed=false,ready=false,busy=false;
  const button=(label:string,action:()=>void)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=action;return b;};
  const finish=(value?:ReviewResult)=>{if(closed)return;closed=true;controller.abort();parent.removeEventListener('abort',abort);window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',abort);document.removeEventListener('visibilitychange',visibility);urls.forEach(url=>URL.revokeObjectURL(url));dialog.remove();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();resolve(value??(busy?{status:'unconfirmed',message:'Searchable PDF export unconfirmed. Check Downloads before exporting again.'}:undefined));};
  const abort=()=>finish(),back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();finish();},visibility=()=>{if(document.hidden)finish();};
  const download=button('Download reviewed searchable PDF',()=>{if(!ready||busy||closed)return;busy=true;keep.disabled=true;download.disabled=true;fields.forEach(f=>f.disabled=true);status.textContent='Preparing searchable PDF…';void exportScanPdf(images,controller.signal,'Alpha searchable document '+new Date().toISOString().replace(/[:.]/g,'-'),layers).then(result=>{if(closed)return;if(result.status==='cancelled'){busy=false;keep.disabled=false;download.disabled=false;fields.forEach(f=>f.disabled=false);status.textContent=result.message;}else finish({...result,textLayers:layers});},error=>{if(closed)return;if(error instanceof ScanPdfExportError){status.textContent='Export unconfirmed. Check Downloads before trying again.';cancel.textContent='Close review';}else{busy=false;keep.disabled=false;download.disabled=false;fields.forEach(f=>f.disabled=false);status.textContent=error instanceof Error?error.message:'Could not prepare searchable PDF.';}});});download.disabled=true;
  const keep=button('Keep reviewed text',()=>{if(!ready||busy||closed)return;try{const textLayers=copyScanTextLayers(layers,images.length) as ScanTextLine[][];finish({status:'reviewed',message:'Reviewed text kept. Save the document draft to retain it after closing.',textLayers});}catch(error){status.textContent=error instanceof Error?error.message:'Could not keep reviewed text.';}});keep.disabled=true;
  const cancel=button('Cancel searchable PDF',abort);const content=document.createElement('div');content.className='scan-dialog-content';const tools=document.createElement('div');tools.className='scan-dialog-tools';tools.append(keep);const actions=document.createElement('div');actions.className='scan-dialog-actions';download.className='primary';actions.append(download,cancel);content.append(help,status,pages,tools);dialog.append(heading,content,actions);dialog.oncancel=e=>{e.preventDefault();finish();};parent.addEventListener('abort',abort,{once:true});window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',abort);document.addEventListener('visibilitychange',visibility);(document.querySelector('.os')||document.body).append(dialog);dialog.showModal();cancel.focus();if(parent.aborted){finish();return;}
  void(async()=>{for(const [index,image]of images.entries()){
   controller.signal.throwIfAborted();status.textContent=`Recognizing page ${index+1} of ${images.length}…`;
   const lines=initial?.[index]??(await recognizeLocalText(image,controller.signal,p=>{if(!closed)status.textContent=`Page ${index+1} · ${Math.round(p.progress*100)}% · ${p.status}`;},true)).lines!;controller.signal.throwIfAborted();
   layers.push(lines);const section=document.createElement('section'),title=document.createElement('h3');title.textContent=`Page ${index+1}`;const preview=document.createElement('img'),url=URL.createObjectURL(image);urls.push(url);preview.src=url;preview.alt=`Searchable document page ${index+1}`;preview.style.cssText='width:100%;max-height:30dvh;object-fit:contain';section.append(title,preview);
   if(!lines.length){const empty=document.createElement('p');empty.textContent='No text recognized on this page. Its image will still be included.';section.append(empty);}
   lines.forEach((line,i)=>{const label=document.createElement('label');label.textContent=`Page ${index+1} line ${i+1}`;const field=document.createElement('textarea');field.rows=2;field.maxLength=4000;field.value=line.text;field.className='scan-dialog-text';field.oninput=()=>{line.text=field.value;};label.append(field);fields.push(field);section.append(label);});pages.append(section);
  }if(!closed){ready=true;keep.disabled=false;download.disabled=false;status.textContent='Review every line, then keep the text or download the searchable PDF.';}})().catch(error=>{if(!closed)status.textContent=error instanceof Error?error.message:'Local text recognition failed. Close and try again.';});
 });
}
