import {recognizeLocalText} from './local-ocr';
import {exportScanPdf,ScanPdfExportError} from './scan-pdf';
import type {ScanTextLine} from './scan-text-layer';
/** Review each positional line before publishing a searchable layer. No draft text is silently reused. */
export function reviewSearchableScan(input:Blob[],parent:AbortSignal):Promise<{status:string;message:string}|undefined>{
 const images=[...input];return new Promise(resolve=>{
  const controller=new AbortController(),dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Review searchable PDF');dialog.style.cssText='box-sizing:border-box;width:min(92vw,560px);max-height:85dvh;overflow:auto;padding:20px;border:1px solid #aaa;border-radius:20px;background:var(--bg,#fff);color:var(--fg,#111);font:16px system-ui';
  const previous=document.activeElement,heading=document.createElement('h2');heading.textContent='Review searchable PDF';const help=document.createElement('p');help.textContent='English recognition runs locally on each current page. Correct each line before downloading. These reviewed lines become selectable, searchable text over the unchanged images. Corrections here are used for this PDF only; Notes and saved document drafts stay unchanged. Clear a line to exclude it from search.';
  const status=document.createElement('p');status.setAttribute('role','status');const pages=document.createElement('div'),fields:HTMLTextAreaElement[]=[],layers:ScanTextLine[][]=[],urls:string[]=[];let closed=false,ready=false,busy=false;
  const button=(label:string,action:()=>void)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='min-height:44px;padding:8px;margin:4px;border:1px solid #aaa;border-radius:8px;background:var(--s2,#eee);color:inherit;font:inherit';b.onclick=action;return b;};
  const finish=(value?:{status:string;message:string})=>{if(closed)return;closed=true;controller.abort();parent.removeEventListener('abort',abort);window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',abort);document.removeEventListener('visibilitychange',visibility);urls.forEach(url=>URL.revokeObjectURL(url));dialog.remove();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();resolve(value??(busy?{status:'unconfirmed',message:'Searchable PDF export unconfirmed. Check Downloads before exporting again.'}:undefined));};
  const abort=()=>finish(),back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();finish();},visibility=()=>{if(document.hidden)finish();};
  const download=button('Download reviewed searchable PDF',()=>{if(!ready||busy||closed)return;busy=true;download.disabled=true;fields.forEach(f=>f.disabled=true);status.textContent='Preparing searchable PDF…';void exportScanPdf(images,controller.signal,'Alpha searchable document '+new Date().toISOString().replace(/[:.]/g,'-'),layers).then(result=>{if(closed)return;if(result.status==='cancelled'){busy=false;download.disabled=false;fields.forEach(f=>f.disabled=false);status.textContent=result.message;}else finish(result);},error=>{if(closed)return;if(error instanceof ScanPdfExportError){status.textContent='Export unconfirmed. Check Downloads before trying again.';cancel.textContent='Close review';}else{busy=false;download.disabled=false;fields.forEach(f=>f.disabled=false);status.textContent=error instanceof Error?error.message:'Could not prepare searchable PDF.';}});});download.disabled=true;
  const cancel=button('Cancel searchable PDF',abort);dialog.append(heading,help,status,pages,download,cancel);dialog.oncancel=e=>{e.preventDefault();finish();};parent.addEventListener('abort',abort,{once:true});window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',abort);document.addEventListener('visibilitychange',visibility);(document.querySelector('.os')||document.body).append(dialog);dialog.showModal();cancel.focus();if(parent.aborted){finish();return;}
  void(async()=>{for(const [index,image]of images.entries()){
   controller.signal.throwIfAborted();status.textContent=`Recognizing page ${index+1} of ${images.length}…`;
   const result=await recognizeLocalText(image,controller.signal,p=>{if(!closed)status.textContent=`Page ${index+1} · ${Math.round(p.progress*100)}% · ${p.status}`;},true);controller.signal.throwIfAborted();
   const lines=result.lines!;layers.push(lines);const section=document.createElement('section'),title=document.createElement('h3');title.textContent=`Page ${index+1}`;const preview=document.createElement('img'),url=URL.createObjectURL(image);urls.push(url);preview.src=url;preview.alt=`Searchable document page ${index+1}`;preview.style.cssText='width:100%;max-height:30dvh;object-fit:contain';section.append(title,preview);
   if(!lines.length){const empty=document.createElement('p');empty.textContent='No text recognized on this page. Its image will still be included.';section.append(empty);}
   lines.forEach((line,i)=>{const label=document.createElement('label');label.textContent=`Page ${index+1} line ${i+1}`;const field=document.createElement('textarea');field.rows=2;field.maxLength=4000;field.value=line.text;field.style.cssText='box-sizing:border-box;display:block;width:100%;min-height:44px;margin:6px 0 12px;padding:8px;background:inherit;color:inherit;font:inherit;border:1px solid #aaa;border-radius:8px';field.oninput=()=>{line.text=field.value;};label.append(field);fields.push(field);section.append(label);});pages.append(section);
  }if(!closed){ready=true;download.disabled=false;status.textContent='Review every line, then download the searchable PDF.';}})().catch(error=>{if(!closed)status.textContent=error instanceof Error?error.message:'Local text recognition failed. Close and try again.';});
 });
}
