import {reviewSearchableScan} from './scan-searchable-review';
import {reviewScanCorrection} from './scan-correction-review';
import {readScanDraft,saveScanDraft,deleteScanDraft} from '../browser/scan-draft';
import {captureScanPage} from './scan-page-camera';
import {inputFiles,runFilePicker} from '../browser/file-picker';
import {exportScanPdf,ScanPdfExportError} from './scan-pdf';
/** Ordered image-only document review. Every export uses an immutable page snapshot. */
export function openScanDocument(first?:Blob):()=>void{
 const controller=new AbortController(),dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Review scan document');dialog.style.cssText='box-sizing:border-box;width:min(92vw,560px);max-height:85dvh;overflow:auto;border:1px solid #aaa;border-radius:20px;padding:20px;background:var(--bg,#fff);color:var(--fg,#111);font:16px system-ui';
 const previous=document.activeElement,heading=document.createElement('h2');heading.textContent='Scan document';const description=document.createElement('p');description.textContent='Review the page order. Image PDF keeps these pages unchanged. Searchable PDF lets you review recognized text for each page before exporting.';
 const list=document.createElement('div'),status=document.createElement('p');status.setAttribute('role','status');let pages=first?[{image:first,url:URL.createObjectURL(first)}]:[],draftRevision:string|undefined,busy=false,closed=false,exported=false;
 const button=(label:string,action:()=>void)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='min-height:44px;padding:8px;margin:4px;border:1px solid #aaa;border-radius:8px;background:var(--s2,#eee);color:inherit;font:inherit';b.onclick=action;return b;};
 const render=()=>{list.replaceChildren();pages.forEach((page,index)=>{const section=document.createElement('section'),label=document.createElement('h3'),image=document.createElement('img');label.textContent=`Page ${index+1}`;image.src=page.url;image.alt=`Document page ${index+1}`;image.style.cssText='display:block;width:100%;height:130px;object-fit:contain';const up=button(`Move page ${index+1} earlier`,()=>{[pages[index-1],pages[index]]=[pages[index],pages[index-1]];render();}),down=button(`Move page ${index+1} later`,()=>{[pages[index],pages[index+1]]=[pages[index+1],pages[index]];render();}),correct=button(`Correct page ${index+1}`,()=>void correctPage(index)),replace=button(`Replace page ${index+1}`,()=>void pick(index)),retake=button(`Retake page ${index+1}`,()=>void pick(index,true)),remove=button(`Remove page ${index+1}`,()=>{URL.revokeObjectURL(pages.splice(index,1)[0].url);render();});up.disabled=busy||index===0||exported;down.disabled=busy||index===pages.length-1||exported;correct.disabled=retake.disabled=replace.disabled=remove.disabled=busy||exported;section.append(label,image,up,down,correct,replace,retake,remove);list.append(section);});capture.disabled=add.disabled=busy||exported||pages.length>=20;searchable.disabled=save.disabled=busy||exported||!pages.length;saveDraft.disabled=busy||!pages.length;loadDraft.disabled=busy;removeDraft.disabled=busy||!draftRevision;};
 const correctPage=async(index:number)=>{if(busy||closed||exported)return;busy=true;render();try{const corrected=await reviewScanCorrection(pages[index].image,controller.signal);controller.signal.throwIfAborted();if(!corrected)return;if(pages.reduce((total,p,i)=>total+(i===index?0:p.image.size),0)+corrected.size>64*1024*1024)throw Error('Corrected document exceeds 64 MB.');const next={image:corrected,url:URL.createObjectURL(corrected)};URL.revokeObjectURL(pages[index].url);pages[index]=next;status.textContent='Corrected page applied. Save the document draft to keep this change.';}catch(error){if(!closed)status.textContent=error instanceof Error?error.message:'Could not correct page.';}finally{if(!closed){busy=false;render();}}};
 const search=async()=>{if(busy||closed||exported||!pages.length)return;busy=true;render();try{const result=await reviewSearchableScan(pages.map(p=>p.image),controller.signal);if(closed||!result)return;exported=result.status!=='cancelled';status.textContent=result.message;}finally{if(!closed){busy=false;render();}}};
 const pick=async(index?:number,camera=false)=>{if(busy||closed||exported)return;busy=true;render();try{const image=camera?await captureScanPage(controller.signal):(await runFilePicker(signal=>inputFiles(AbortSignal.any([signal,controller.signal]),{photos:true}),[]))[0];controller.signal.throwIfAborted();if(!image)return;if(!['image/jpeg','image/png','image/webp'].includes(image.type)||!image.size||image.size>16*1024*1024)throw Error('Choose a JPEG, PNG or WebP image up to 16 MB.');if(pages.reduce((sum,p,i)=>sum+(i===index?0:p.image.size),0)+image.size>64*1024*1024)throw Error('Choose pages up to 64 MB total.');const bitmap=await createImageBitmap(image);try{controller.signal.throwIfAborted();if(!bitmap.width||!bitmap.height||bitmap.width*bitmap.height>32000000)throw Error('Image dimensions are too large.');}finally{bitmap.close();}const page={image,url:URL.createObjectURL(image)};if(index===undefined)pages.push(page);else{URL.revokeObjectURL(pages[index].url);pages[index]=page;}status.textContent='';}catch(error){if(!closed)status.textContent=error instanceof Error?error.message:'Could not add page.';}finally{if(!closed){busy=false;render();}}};
 const draftAction=async(action:()=>Promise<void>)=>{if(busy||closed)return;busy=true;render();try{await action();}catch(error){if(!closed)status.textContent=error instanceof Error?error.message:'Draft action failed.';}finally{if(!closed){busy=false;render();}}};
 const saveDraft=button('Save document draft',()=>void draftAction(async()=>{const draft=await saveScanDraft(pages.map(p=>p.image),draftRevision,controller.signal);if(closed)return;draftRevision=draft.revision;status.textContent='Document draft saved in this browser.';}));
 const loadDraft=button('Load saved draft',()=>void draftAction(async()=>{const draft=await readScanDraft();if(closed)return;if(!draft){status.textContent='No saved document draft.';return;}if(pages.length&&!window.confirm('Replace the current review with the saved draft?'))return;const next=draft.pages.map(image=>({image,url:URL.createObjectURL(image)}));pages.forEach(p=>URL.revokeObjectURL(p.url));pages=next;draftRevision=draft.revision;exported=false;status.textContent='Saved document draft loaded.';}));
 const removeDraft=button('Delete saved draft',()=>void draftAction(async()=>{if(!draftRevision||!window.confirm('Delete the saved draft? The current reviewed pages will remain open.'))return;await deleteScanDraft(draftRevision,controller.signal);if(closed)return;draftRevision=undefined;status.textContent='Saved draft deleted. Reviewed pages remain open.';}));
 const dispose=()=>{if(closed)return;closed=true;controller.abort();pages.forEach(page=>URL.revokeObjectURL(page.url));pages=[];dialog.remove();window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',dispose);document.removeEventListener('visibilitychange',visibility);if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};
 const back=(event:Event)=>{if(document.querySelector('dialog[aria-label="Capture document page"],dialog[aria-label="Correct document page"],dialog[aria-label="Review searchable PDF"]'))return;event.preventDefault();event.stopImmediatePropagation();dispose();},visibility=()=>{if(document.hidden)dispose();};
 const searchable=button('Download searchable PDF',()=>void search());
 const add=button('Add page',()=>void pick()),capture=button('Capture new page',()=>void pick(undefined,true)),save=button('Download document PDF',()=>{if(busy||closed||exported||!pages.length)return;busy=true;render();status.textContent='Preparing document…';void exportScanPdf(pages.map(page=>page.image),controller.signal,'Alpha document '+new Date().toISOString().replace(/[:.]/g,'-')).then(result=>{if(closed)return;exported=result.status!=='cancelled';status.textContent=result.message;busy=false;render();},error=>{if(closed)return;exported=error instanceof ScanPdfExportError;busy=false;status.textContent=exported?'Export unconfirmed. Check Downloads before exporting again.':error instanceof Error?error.message:'Could not prepare the PDF. Try again.';render();});}),close=button('Close document',dispose);
 dialog.append(heading,description,list,status,add,capture,saveDraft,loadDraft,removeDraft,save,searchable,close);dialog.oncancel=event=>{event.preventDefault();dispose();};window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',dispose);document.addEventListener('visibilitychange',visibility);(document.querySelector('.os')||document.body).append(dialog);render();dialog.showModal();add.focus();return dispose;
}
