import {detectScanEdges} from '../browser/scan-edges';
import {correctScanPage,fullPageCorners,type ScanCorners} from '../browser/scan-correction';
/** Correction affects only the reviewed document page after explicit adoption. */
export function reviewScanCorrection(image:Blob,parent:AbortSignal):Promise<Blob|undefined>{
 return new Promise(resolve=>{
  const controller=new AbortController(),dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Correct document page');dialog.style.cssText='box-sizing:border-box;width:min(92vw,560px);max-height:85dvh;overflow:auto;padding:20px;border:1px solid #aaa;border-radius:20px;background:var(--bg,#fff);color:var(--fg,#111);font:16px system-ui';
  const previous=document.activeElement,heading=document.createElement('h2');heading.textContent='Correct page edges';const help=document.createElement('p');help.textContent='Move the four corners to the page edges, or enter their positions as percentages. Preview before applying. This changes only this document page; the original photo stays unchanged.';
  const frame=document.createElement('div');frame.style.cssText='position:relative;line-height:0;margin:auto';const source=document.createElement('img');const sourceUrl=URL.createObjectURL(image);source.src=sourceUrl;source.alt='Original page with correction corners';source.style.cssText='display:block;width:100%;height:auto';source.onload=()=>{if(source.naturalHeight)frame.style.width=`min(100%, ${40*source.naturalWidth/source.naturalHeight}dvh)`;};
  const ns='http://www.w3.org/2000/svg',overlay=document.createElementNS(ns,'svg');overlay.setAttribute('viewBox','0 0 100 100');overlay.setAttribute('preserveAspectRatio','none');overlay.setAttribute('aria-hidden','true');overlay.style.cssText='position:absolute;inset:0;width:100%;height:100%;touch-action:none';const polygon=document.createElementNS(ns,'polygon');polygon.setAttribute('fill','#087dff22');polygon.setAttribute('stroke','#087dff');polygon.setAttribute('stroke-width','1');overlay.append(polygon);frame.append(source,overlay);
  const fields=document.createElement('div');fields.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0';let corners=fullPageCorners(),closed=false,busy=false,corrected:Blob|undefined,previewUrl:string|undefined;const inputs:HTMLInputElement[]=[],handles:SVGCircleElement[]=[];
  const preview=document.createElement('img');preview.alt='Corrected page preview';preview.hidden=true;preview.style.cssText='width:100%;height:auto;max-height:40dvh;object-fit:contain';preview.onload=()=>{if(!closed&&!preview.hidden)preview.scrollIntoView({block:'start'});};const status=document.createElement('p');status.setAttribute('role','status');
  const button=(label:string,action:()=>void)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='min-height:44px;padding:8px;margin:4px;border:1px solid #aaa;border-radius:8px;background:var(--s2,#eee);color:inherit;font:inherit';b.onclick=action;return b;};
  const clearPreview=()=>{corrected=undefined;preview.hidden=true;preview.removeAttribute('src');if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=undefined;apply.disabled=true;status.textContent='';};
  const draw=()=>{polygon.setAttribute('points',corners.map(p=>`${p.x*100},${p.y*100}`).join(' '));handles.forEach((h,i)=>{h.setAttribute('cx',String(corners[i].x*100));h.setAttribute('cy',String(corners[i].y*100));});};
  const labels=['Top left','Top right','Bottom right','Bottom left'];
  labels.forEach((name,i)=>{
   for(const axis of ['x','y'] as const){const label=document.createElement('label');label.textContent=`${name} ${axis==='x'?'horizontal':'vertical'} (%)`;const field=document.createElement('input');field.type='number';field.min='0';field.max='100';field.step='0.1';field.value=String(corners[i][axis]*100);field.style.cssText='display:block;box-sizing:border-box;width:100%;min-height:44px;font:inherit';field.oninput=()=>{clearPreview();corners[i][axis]=field.valueAsNumber/100;draw();};label.append(field);fields.append(label);inputs.push(field);}
   const handle=document.createElementNS(ns,'circle');handle.setAttribute('r','5');handle.setAttribute('fill','#087dff');handle.setAttribute('stroke','white');handle.setAttribute('stroke-width','1');handle.style.cursor='move';let pointer:number|undefined;
   handle.onpointerdown=event=>{if(busy)return;pointer=event.pointerId;handle.setPointerCapture(pointer);event.preventDefault();};handle.onpointermove=event=>{if(pointer!==event.pointerId||busy)return;const box=overlay.getBoundingClientRect();if(!box.width||!box.height)return;clearPreview();corners[i]={x:Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-box.top)/box.height))};inputs[i*2].value=(corners[i].x*100).toFixed(1);inputs[i*2+1].value=(corners[i].y*100).toFixed(1);draw();};handle.onpointerup=handle.onpointercancel=()=>{pointer=undefined;};handles.push(handle);overlay.append(handle);
  });
  const finish=(value?:Blob)=>{if(closed)return;closed=true;controller.abort();parent.removeEventListener('abort',abort);window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',abort);document.removeEventListener('visibilitychange',visibility);URL.revokeObjectURL(sourceUrl);if(previewUrl)URL.revokeObjectURL(previewUrl);dialog.remove();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();resolve(value);};const abort=()=>finish(),back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();finish();},visibility=()=>{if(document.hidden)finish();};
  const renderBusy=()=>{inputs.forEach(input=>input.disabled=busy);detect.disabled=reset.disabled=generate.disabled=busy;apply.disabled=busy||!corrected;};
  const detect=button('Detect page edges',()=>{if(busy||closed)return;busy=true;renderBusy();status.textContent='Finding page edges…';void detectScanEdges(image,controller.signal).then(found=>{if(closed)return;if(!found){status.textContent='No clear page boundary found. Move the corners manually.';return;}clearPreview();corners=found;inputs.forEach((input,i)=>input.value=(corners[Math.floor(i/2)][i%2?'y':'x']*100).toFixed(1));draw();status.textContent='Suggested edges ready. Adjust the corners and preview before applying.';},error=>{if(!closed)status.textContent=error instanceof Error?error.message:'Page detection failed.';}).finally(()=>{if(!closed){busy=false;renderBusy();}});});
  const reset=button('Reset corners',()=>{corners=fullPageCorners();inputs.forEach((input,i)=>input.value=String(corners[Math.floor(i/2)][i%2?'y':'x']*100));clearPreview();draw();});
  const generate=button('Preview correction',()=>{if(busy||closed)return;clearPreview();busy=true;renderBusy();status.textContent='Correcting page…';void correctScanPage(image,corners as ScanCorners,controller.signal).then(blob=>{if(closed)return;corrected=blob;previewUrl=URL.createObjectURL(blob);preview.src=previewUrl;preview.hidden=false;status.textContent='Review the corrected page. Apply to replace this document page.';},error=>{if(!closed)status.textContent=error instanceof Error?error.message:'Page correction failed.';}).finally(()=>{if(!closed){busy=false;renderBusy();}});});
  const apply=button('Use corrected page',()=>{if(corrected&&!busy)finish(corrected);});apply.disabled=true;const cancel=button('Cancel correction',abort);
  dialog.append(heading,help,frame,fields,status,preview,detect,reset,generate,apply,cancel);dialog.oncancel=e=>{e.preventDefault();finish();};parent.addEventListener('abort',abort,{once:true});window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',abort);document.addEventListener('visibilitychange',visibility);(document.querySelector('.os')||document.body).append(dialog);draw();dialog.showModal();if(parent.aborted)finish();else inputs[0].focus();
 });
}
