/** A document capture owns cloned preview tracks or its own camera request. */
export function captureScanPage(signal:AbortSignal):Promise<Blob|undefined>{
 return new Promise(resolve=>{
  const dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Capture document page');dialog.style.cssText='box-sizing:border-box;width:min(92vw,560px);max-height:85dvh;overflow:auto;padding:20px;border-radius:20px;background:var(--bg,#fff);color:var(--fg,#111);font:16px system-ui';const heading=document.createElement('h2');heading.textContent='Capture page';const video=document.createElement('video');video.playsInline=true;video.muted=true;video.style.cssText='width:100%;max-height:48dvh;object-fit:contain;background:#111';const preview=document.createElement('img');preview.alt='Review captured document page';preview.hidden=true;preview.style.cssText=video.style.cssText;const status=document.createElement('p');status.setAttribute('role','status');status.textContent='Starting camera…';let closed=false,stream:MediaStream|undefined,blob:Blob|undefined,url:string|undefined,busy=false;
  const button=(name:string,action:()=>void)=>{const b=document.createElement('button');b.type='button';b.textContent=name;b.style.cssText='min-height:44px;margin:4px;padding:8px;font:inherit';b.onclick=action;return b;};
  const finish=(result?:Blob)=>{if(closed)return;closed=true;clearTimeout(deadline);signal.removeEventListener('abort',abort);window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',abort);document.removeEventListener('visibilitychange',visibility);stream?.getTracks().forEach(t=>t.stop());video.pause();video.srcObject=null;if(url)URL.revokeObjectURL(url);dialog.remove();resolve(result);};const abort=()=>finish(),back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();finish();},visibility=()=>{if(document.hidden)finish();};
  const capture=button('Capture page',()=>{if(busy||video.readyState<2||closed||!stream?.getVideoTracks().some(t=>t.readyState==='live'))return;busy=true;capture.disabled=true;const canvas=document.createElement('canvas');const scale=Math.min(1,2048/Math.max(video.videoWidth,video.videoHeight));canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);const ctx=canvas.getContext('2d');if(!ctx||!canvas.width||!canvas.height){busy=false;capture.disabled=false;status.textContent='Camera frame could not be captured. Try again.';return;}ctx.drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(value=>{if(closed)return;busy=false;if(!value){capture.disabled=false;status.textContent='Camera frame could not be captured. Try again.';return;}blob=value;url=URL.createObjectURL(value);preview.src=url;preview.hidden=false;video.hidden=true;video.pause();capture.hidden=true;retake.hidden=false;use.disabled=false;status.textContent='Review this page before adding it.';},'image/jpeg',.9);});capture.disabled=true;
  const retake=button('Retake capture',()=>{if(url)URL.revokeObjectURL(url);url=undefined;blob=undefined;preview.removeAttribute('src');preview.hidden=true;video.hidden=false;capture.hidden=false;capture.disabled=false;retake.hidden=true;use.disabled=true;void video.play().catch(()=>{status.textContent='Camera preview could not resume. Close and try again.';});});retake.hidden=true;
  const use=button('Use captured page',()=>{if(blob)finish(blob);});use.disabled=true;const cancel=button('Cancel capture',abort);
  const deadline=setTimeout(()=>{if(!closed&&!stream){status.textContent='Camera is still waiting. You can cancel and choose an image instead.';}},15000);
  signal.addEventListener('abort',abort,{once:true});window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',abort);document.addEventListener('visibilitychange',visibility);dialog.oncancel=e=>{e.preventDefault();finish();};dialog.append(heading,video,preview,status,capture,retake,use,cancel);(document.querySelector('.os')||document.body).append(dialog);dialog.showModal();if(signal.aborted){finish();return;}
  const existing=document.querySelector<HTMLVideoElement>('[aria-label^="Viewfinder."] video')?.srcObject as MediaStream|null|undefined;const tracks=existing?.getVideoTracks().filter(t=>t.readyState==='live');
  let request:Promise<MediaStream>|undefined;try{request=tracks?.length?Promise.resolve(new MediaStream(tracks.map(t=>t.clone()))):navigator.mediaDevices?.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1600},height:{ideal:1200}}});}catch{status.textContent='Choose an image or close and try camera access again.';return;}
  if(!request){status.textContent='Choose an image to add this page.';return;}
  void request.then(async value=>{if(closed){value.getTracks().forEach(t=>t.stop());return;}stream=value;video.srcObject=value;try{await video.play();if(closed)return;clearTimeout(deadline);capture.disabled=false;status.textContent='Frame the page, then capture.';value.getVideoTracks().forEach(t=>t.addEventListener('ended',()=>{if(!closed){capture.disabled=true;status.textContent='Camera stopped. Keep the reviewed capture or choose another image.';}},{once:true}));}catch{if(!closed){value.getTracks().forEach(t=>t.stop());status.textContent='Camera preview could not start. Close and try again.';}}},()=>{if(!closed){clearTimeout(deadline);status.textContent='Choose an image or close and try camera access again.';}});
 });
}
