import {proposedRecordingSummary} from './recording-summary';
import {summarySourceOf,webSourceOf,recordingSourceOf,type SummarySource,type WebSource,type RecordingSource} from './summary-source';
import type {Source} from './note-source-adapter';
/** A direct user edit/save, separate from an agent proposal. Never saves on reply arrival. */
export function reviewSummaryNote(input:{text:string;source:SummarySource;current:()=>boolean;save:(note:{title:string;body:string;documentSource?:Source;webSource?:WebSource;recordingSource?:RecordingSource;actions?:{t:string;done:boolean}[]})=>Promise<boolean>;complete:()=>void}){
 const source=summarySourceOf(input.source);if(!source||!input.current())throw Error('Source review expired. Ask about the source again.');
 const recording=recordingSourceOf(source),proposed=recording?proposedRecordingSummary(input.text):undefined;
 const dialog=document.createElement('dialog');dialog.className='note-source-dialog';dialog.setAttribute('aria-label','Save reviewed summary note');
 const theme=document.querySelector('.os');if(theme){const style=getComputedStyle(theme);for(const token of ['bg','fg'])dialog.style.setProperty('--source-'+token,style.getPropertyValue('--'+token));}
 const heading=document.createElement('h2');heading.textContent='Review summary note';const content=document.createElement('div');content.className='note-source-content';content.tabIndex=0;content.setAttribute('role','region');content.setAttribute('aria-label','Summary note review');
 const description=document.createElement('p');description.textContent='Review and edit the answer before saving it on this device. The note will link to '+source.name+(webSourceOf(source)?'. Opening the source visits the current page; its contents may have changed.':('reference' in source&&source.reference?'. The library link can reopen while access remains available; changed bytes are rejected.':'. Reopening the source requires choosing matching file bytes.'));
 const title=document.createElement('input');title.setAttribute('aria-label','Summary note title');title.maxLength=200;title.value=('Summary · '+source.name).slice(0,200);
 const body=document.createElement('textarea');body.setAttribute('aria-label','Summary note text');body.maxLength=32000;body.rows=8;body.value=proposed?.summary??input.text.slice(0,32000);for(const field of [title,body])field.style.cssText='box-sizing:border-box;width:100%;font:inherit;color:inherit;background:inherit;padding:8px;margin:8px 0';
 const actions=document.createElement('textarea');actions.setAttribute('aria-label','Action items, one per line');actions.maxLength=4000;actions.rows=4;actions.value=proposed?.actions.join('\n')||'';actions.style.cssText=body.style.cssText;
 if(recording){heading.textContent='Review recording summary';title.hidden=true;description.textContent='Edit the summary and action items you want to keep, one per line. Saving updates this recording on this device, preserves its audio and transcript, and replaces any earlier summary and action items. It does not schedule reminders.';}
 const status=document.createElement('p');status.setAttribute('role','status');if(recording&&!proposed)status.textContent='The answer did not provide a usable action list. Review its text and copy any action items you want to keep.';if(input.text.length>32000&&!proposed)status.textContent='The answer exceeds the note limit. Review the first 32,000 characters before saving.';
 const footer=document.createElement('footer'),save=document.createElement('button'),cancel=document.createElement('button');save.textContent='Save reviewed note';cancel.textContent='Cancel';footer.append(save,cancel);content.append(heading,description,title,body);dialog.append(content,footer);
 if(recording){save.textContent='Save recording summary';const label=document.createElement('label');label.textContent='Action items · one per line';label.append(actions);content.append(label);}
 content.append(status);
 const report=(message:string)=>{status.textContent=message;status.scrollIntoView({block:'nearest'});};
 let closed=false,busy=false;const previous=document.activeElement;
 const close=()=>{if(closed)return;closed=true;dialog.remove();window.removeEventListener('pagehide',close);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('alpha-back',back,true);if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};
 const visibility=()=>{if(document.hidden)close();};document.addEventListener('visibilitychange',visibility);
 const back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();close();};cancel.onclick=close;dialog.oncancel=event=>{event.preventDefault();close();};window.addEventListener('pagehide',close);window.addEventListener('alpha-back',back,true);
 const update=()=>save.disabled=busy||!title.value.trim()||!body.value.trim();title.oninput=update;body.oninput=update;
 save.onclick=async()=>{if(busy||closed)return;if(!input.current()){report(recording?'Recording, agent or conversation changed. Ask about the source again.':'Agent or conversation changed. Close this review and ask about the source again.');save.disabled=true;return;}const items=actions.value.split(/\r?\n/).map(t=>t.trim()).filter(Boolean);if(recording&&(items.length>20||items.some(t=>t.length>500))){report('Keep at most 20 action items, each up to 500 characters.');return;}busy=true;update();title.disabled=body.disabled=actions.disabled=true;try{const saved=await input.save({title:title.value.trim(),body:body.value,...(recording?{recordingSource:recording,actions:items.map(t=>({t,done:false}))}:webSourceOf(source)?{webSource:webSourceOf(source)!}:{documentSource:source as Source})});if(saved){input.complete();close();}else if(!closed)report('Save is unconfirmed. Reopen Notes before trying again.');}catch{if(!closed)report('Save is unconfirmed. Reopen Notes before trying again.');}};
 document.body.append(dialog);dialog.showModal();(recording?body:title).focus();update();return close;
}
