import './scan-dialog.css';
import type {VideoEdit} from '../browser/video-edit';
import {validateVideoEdit,drawEditedVideo} from '../browser/video-edit';
export function openVideoEditReview(source:{path:string;duration:number},save:(edit:VideoEdit,signal:AbortSignal)=>Promise<boolean>,onClose:()=>void=()=>{}){
 const controller=new AbortController(),dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Edit video');dialog.className='scan-dialog';
 const heading=document.createElement('h2');heading.textContent='Edit video';const video=document.createElement('video');video.preload='auto';video.controls=true;video.playsInline=true;video.style.cssText='width:100%;height:240px;object-fit:contain';const preview=document.createElement('div');preview.style.cssText='overflow:hidden;background:black';const canvas=document.createElement('canvas');canvas.style.cssText='width:100%;height:240px;object-fit:contain';canvas.setAttribute('aria-label','Edited video preview');preview.append(canvas);video.hidden=true;preview.append(video);
 const status=document.createElement('p');status.setAttribute('role','status');status.textContent='Save a new copy with audio. The original stays unchanged.';
 const edit:VideoEdit={start:0,end:source.duration,rotation:0,crop:false};let busy=false,closed=false,sourceUrl:string|undefined;
 const controls:HTMLButtonElement[]=[];const button=(name:string,action:()=>void)=>{const b=document.createElement('button');b.textContent=name;b.type='button';b.onclick=action;controls.push(b);return b;};
 const field=(name:string,key:'start'|'end')=>{const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='number';input.min='0';input.max=String(source.duration);input.step='.1';input.value=String(edit[key]);input.oninput=()=>{edit[key]=input.valueAsNumber;};label.append(input);return {label,input};};const start=field('Start seconds','start'),end=field('End seconds','end');
 const update=()=>{if(video.readyState>=2)drawEditedVideo(video,edit,canvas);};const previewTimer=setInterval(update,33);
 const rotate=button('Rotate video',()=>{edit.rotation=(edit.rotation+90)%360;update();}),crop=button('Crop video',()=>{edit.crop=!edit.crop;crop.setAttribute('aria-pressed',String(edit.crop));update();}),play=button('Preview trim',()=>{try{validateVideoEdit(edit,source.duration);video.currentTime=edit.start;void video.play().catch(()=>{status.textContent='Press play to preview.';});}catch(error){status.textContent=(error as Error).message;}});
 video.ontimeupdate=()=>{if(video.currentTime>=edit.end)video.pause();};
 const dispose=()=>{if(closed)return;closed=true;clearInterval(previewTimer);controller.abort();video.pause();video.removeAttribute('src');video.load();if(sourceUrl)URL.revokeObjectURL(sourceUrl);dialog.remove();onClose();window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',dispose);document.removeEventListener('visibilitychange',visibility);};const back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();dispose();},visibility=()=>{if(document.hidden)dispose();};
 const commit=button('Save video copy',()=>{if(busy)return;try{validateVideoEdit(edit,source.duration);}catch(error){status.textContent=(error as Error).message;return;}busy=true;video.pause();controls.forEach(b=>b.disabled=true);start.input.disabled=end.input.disabled=true;status.textContent='Saving video copy…';void save({...edit},controller.signal).then(saved=>{if(closed)return;if(saved)dispose();else status.textContent='Copy was not saved. Close and reopen the editor to try again.';},()=>{if(!closed)status.textContent='Save outcome could not be confirmed. Reopen Photos to check the existing operation.';});});
 const pause=button('Pause preview',()=>video.pause());
 const close=button('Close video editor',dispose);controls.pop();commit.className='primary';const content=document.createElement('div');content.className='scan-dialog-content';content.tabIndex=0;content.setAttribute('role','region');content.setAttribute('aria-label','Review details');const fields=document.createElement('div');fields.className='scan-dialog-fields';fields.append(start.label,end.label);const tools=document.createElement('div');tools.className='scan-dialog-tools';tools.append(rotate,crop,play,pause);content.append(preview,fields,tools,status);const actions=document.createElement('div');actions.className='scan-dialog-actions';actions.append(commit,close);dialog.append(heading,content,actions);dialog.oncancel=e=>{e.preventDefault();dispose();};window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',dispose);document.addEventListener('visibilitychange',visibility);(document.querySelector('.os')||document.body).append(dialog);dialog.showModal();void fetch(source.path,{signal:controller.signal}).then(response=>response.blob()).then(blob=>{if(closed)return;sourceUrl=URL.createObjectURL(blob);video.src=sourceUrl;}).catch(()=>{if(!closed)status.textContent='Video could not load. Close and reopen the editor to try again.';});return dispose;
}
