import {browserWorkflowDraftStore} from '../browser/workflow-drafts';
import {browserDevProfile} from '../browser/dev-profile';
import { registerPlugin } from '../platform-plugins';
import { browserLocalAgentEnabled } from '../runtime/local-agent';
import { developmentWorkflowDraftStore } from '../runtime/local-agent-storage';
import { connectionController } from '../runtime/connection-ui';
import { normalizePhoneSpec, assertPhoneCapabilities, type PhoneSpec, type PhoneStep, type PhoneCatalog } from '../runtime/phone-workflow-authoring';
import { workflowSha, workflowBytes } from '../runtime/workflow-device-contract';
import type { RemoteWorkflow } from '../runtime/workflow-protocol';
type Bag=Record<string,any>;
type Pending={mutationId:string;specDigest:string;compilerRevision:string;workflowId?:string;versionId?:string};
type Draft={format:1;identity:string;spec:PhoneSpec;workflowId?:string;versionId?:string;pending?:Pending};
const secure=browserLocalAgentEnabled?developmentWorkflowDraftStore:registerPlugin<{secureRead(v:{slot:string}):Promise<{value:string|null}>;secureCompareExchange(v:{slot:string;expectedValue:string|null;value:string|null}):Promise<{status:string}>}>('AlphaConnection');
const draftStorageDescription=browserDevProfile?'in this browser development profile':browserLocalAgentEnabled?'in the private development profile on this computer (not encrypted)':'encrypted on this phone';
const calendar=registerPlugin<{workflowCalendars():Promise<{status:string;calendars:Bag[]}>;requestWorkflowReadAccess():Promise<{status:string}>}>('AlphaCalendar');
const palette=['Read','If','Write','Send','Notify','Speak','Do'];
const icons:Record<string,string>={Read:'wfRead',If:'wfIf',Write:'edit',Send:'send',Notify:'bell',Speak:'wave',Do:'wfDo'};
const known=new Set(['supplied_text','selected_notes','calendar_range','contains','compose_draft','model_draft','save_note']);
/** Typed local authoring. No prototype natural-language parser or arbitrary source is executed. */
export function createWorkflowAuthoring(owner:()=>any,publish:()=>void,onSaved:(id:string)=>Promise<unknown>){
 let active=false,draft:Draft|null=null,catalog:PhoneCatalog|null=null,sheet:string|null=null,busy=false,status='',review:string|null=null,discard=false,generation=0,controller:AbortController|null=null;
 let calendars:Bag[]=[],storage:{slot:string;raw:string|null;failed:boolean;queue:Promise<void>;secure:typeof secure}|null=null;
 const toast=(value:string)=>owner()?.toast?.(value);
 const selected=()=>draft?.spec.steps.find(s=>s.id===sheet);
 const locked=()=>busy||!!draft?.pending||!!storage?.failed;
 function persist(){if(!draft||!storage)return;const target=storage,snapshot=JSON.stringify(draft);target.queue=target.queue.then(async()=>{if(target.failed)throw new Error('Local draft needs recovery');if(new TextEncoder().encode(snapshot).length>100000)throw new Error('Local draft is too large');const result=await target.secure.secureCompareExchange({slot:target.slot,expectedValue:target.raw,value:snapshot});if(result.status!=='saved')throw new Error('Draft changed in another window. Close and reopen it before editing.');target.raw=snapshot;}).catch(error=>{target.failed=true;status=error instanceof Error?error.message:'Local draft could not be saved';if(storage===target)publish();});}
 function change(run:()=>void){if(locked()||!draft)return;run();review=null;discard=false;status=`Draft stays ${draftStorageDescription} until you confirm Save.`;persist();publish();}
 async function localSaved(){await storage?.queue;if(!storage||storage.failed)throw new Error('Resolve local draft storage before saving');}
 function close(){active=false;generation++;controller?.abort();controller=null;busy=false;sheet=null;review=null;discard=false;calendars=[];publish();}
 async function open(workflow?:RemoteWorkflow){
  if(active||busy)return;const binding=connectionController.getWorkflowClient(),session=connectionController.getSnapshot().session;if(!binding||!session){connectionController.open();return;}
  active=true;busy=true;draft=null;catalog=null;storage=null;status='Loading this agent’s workflow capabilities…';const token=++generation;controller=new AbortController();const signal=controller.signal;publish();
  const valid=()=>token===generation&&!signal.aborted&&connectionController.getWorkflowClient()?.sessionId===binding.sessionId&&!document.hidden&&!connectionController.getSnapshot().open;
  try{const [cap,identity]=await Promise.all([binding.client.phoneCatalog(signal),workflowSha([session.origin,session.ownerId,session.agentId])]);if(!valid())return;catalog=cap;const slot='workflow-draft:v1:'+identity,draftSecure=browserDevProfile&&JSON.parse(localStorage.getItem('alpha.connection.selection.v1')||'null')?.kind==='development'?await browserWorkflowDraftStore(session):secure,saved=await draftSecure.secureRead({slot});if(!valid())return;storage={slot,raw:saved.value,failed:false,queue:Promise.resolve(),secure:draftSecure};
   if(saved.value!==null){if(new TextEncoder().encode(saved.value).length>100000)throw new Error('Saved draft exceeds the recovery limit');const retained=JSON.parse(saved.value);if(retained.format!==1||retained.identity!==identity||!retained.spec||retained.spec.version!==1||!Array.isArray(retained.spec.steps)||retained.spec.steps.length>32)throw new Error('Saved draft requires recovery');draft=retained;status=draft!.pending?'Save outcome unknown. Refresh its exact receipt; another save is blocked.':`Restored the draft stored ${draftStorageDescription}. Resume it or discard it explicitly.`;}
   else{const spec=workflow?normalizePhoneSpec(workflow.phoneSpec):{version:1 as const,name:'New workflow',description:'',trigger:{kind:'manual' as const},steps:[]};draft={format:1,identity,spec,...(workflow?{workflowId:workflow.id,versionId:workflow.versionId}:{})};status='Build a manual workflow. It will be saved paused.';persist();}
  }catch(error){if(valid()){status=error instanceof Error?error.message:'Typed workflow authoring is unavailable on this agent';draft=null;toast(status);}}finally{if(token===generation){busy=false;controller=null;publish();}}
 }
 function ensureDevice(){const target=connectionController.getWorkflowDeviceTarget();if(!target)throw new Error('Reconnect this agent to verify phone enrollment');if(draft)draft.spec.device=target;}
 function operation(kind:string,id:string,stepId:string,index:number):PhoneStep{
  const source=draft?.spec.steps[index-1]?.id;if(kind!=='Read'&&!source)throw new Error('Add a Read step first');
  const common={id:stepId,kind:kind as PhoneStep['kind'],operation:id};
  if(id==='supplied_text')return {...common,text:''};
  if(id==='selected_notes'){ensureDevice();return {...common,notes:[]};}
  if(id==='calendar_range'){ensureDevice();const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);return {...common,range:{calendarIds:[],start:start.toISOString(),end:end.toISOString(),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,maximumEvents:100}};}
  if(id==='contains')return {...common,source,text:'',caseSensitive:false};
  if(id==='compose_draft')return {...common,source,prefix:'',suffix:''};
  if(id==='model_draft')return {...common,source,instruction:''};
  if(id==='save_note'){ensureDevice();return {...common,source,title:'Workflow note'};}
  throw new Error('This operation needs a newer qualified phone capability');
 }
 function add(kind:string){if(locked()||!draft||!catalog)return;const available=catalog.palette.find(k=>k.kind===kind)?.operations.find(o=>o.available&&known.has(o.id));if(!available){toast(catalog.palette.find(k=>k.kind===kind)?.operations[0]?.reason||'This capability is not available on the selected agent');return;}if(draft.spec.steps.length>=32){toast('A workflow supports at most 32 steps');return;}try{const step=operation(kind,available.id,'s'+crypto.randomUUID().replaceAll('-',''),draft.spec.steps.length);change(()=>{draft!.spec.steps.push(step);sheet=step.id;});}catch(error){toast((error as Error).message);}}
 function chooseOperation(id:string){const step=selected();if(!step||!draft||!catalog||locked())return;const option=catalog.palette.find(p=>p.kind===step.kind)?.operations.find(o=>o.id===id);if(!option?.available||!known.has(id)){toast(option?.reason||'This operation is unavailable');return;}try{const replacement=operation(step.kind,id,step.id,draft.spec.steps.indexOf(step));change(()=>{draft!.spec.steps[draft!.spec.steps.indexOf(step)]=replacement;});}catch(error){toast((error as Error).message);}}
 function remove(){const step=selected();if(!step||!draft||locked())return;if(draft.spec.steps.some(s=>s.source===step.id)){toast('Change the later steps that use this input before deleting it');return;}change(()=>{draft!.spec.steps=draft!.spec.steps.filter(s=>s!==step);sheet=null;});}
 function move(offset:number){const step=selected();if(!step||!draft||locked())return;const list=[...draft.spec.steps],index=list.indexOf(step),next=index+offset;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];const seen=new Set<string>();for(const item of list){if(item.source&&!seen.has(item.source)){toast('A step must stay after its selected input');return;}seen.add(item.id);}change(()=>{draft!.spec.steps=list;});}
 async function chooseNote(id:string){const step=selected();if(step?.operation!=='selected_notes'||!draft||locked())return;const expected=generation,target=step;if(step.notes.some((n:Bag)=>n.id===id)){change(()=>{step.notes=step.notes.filter((n:Bag)=>n.id!==id);});return;}if(step.notes.length>=16){toast('Choose at most 16 notes');return;}try{const host=owner();await host.notesStore?.assertCurrent();const raw=host.notesStore?.raw;if(host.notesStorageFailed||host.notesPending||host.notesRaw!==raw)throw new Error('Notes changed. Reopen Notes before selecting');const found=host.vget('notes').list.filter((n:Bag)=>n.id===id);if(found.length!==1||typeof found[0].title!=='string'||typeof found[0].body!=='string')throw new Error('Note text is unavailable');const revision=await workflowSha([found[0].title,found[0].body]);await host.notesStore.assertCurrent();if(expected!==generation||target!==selected()||locked()||host.notesStore.raw!==raw)return;change(()=>{ensureDevice();step.notes.push({id,revision});});}catch(error){toast((error as Error).message);}}
 async function loadCalendars(request=false){const step=selected();if(step?.operation!=='calendar_range'||locked())return;const token=generation;try{if(request&&(await calendar.requestWorkflowReadAccess()).status!=='granted')throw new Error('Calendar read permission was not granted');const result=await calendar.workflowCalendars();if(token!==generation||selected()!==step)return;if(result.status!=='ready')throw new Error('Choose Connect calendars to grant read access');calendars=result.calendars;status=calendars.length?'Select only the calendars this workflow may read':'No calendars are available on this phone';publish();}catch(error){if(token===generation){status=(error as Error).message;publish();}}}
 async function save(){if(!draft||!catalog||locked())return;const binding=connectionController.getWorkflowClient(),session=connectionController.getSnapshot().session;if(!binding||!session)return;let spec:PhoneSpec;const draftAtStart=draft,revisionAtStart=JSON.stringify(draft.spec),generationAtStart=generation;try{spec=normalizePhoneSpec(draft.spec);assertPhoneCapabilities(spec,catalog);await localSaved();if(draft!==draftAtStart||generation!==generationAtStart||JSON.stringify(draft.spec)!==revisionAtStart)return;}catch(error){status=(error as Error).message;publish();return;}const encoded=JSON.stringify(spec);if(review!==encoded){review=encoded;sheet=null;status=`Review this full specification. Tap Save again to send it to ${session.origin} for owner ${session.ownerId}. It will be saved paused; phone reads/writes still require separate run approval.`;publish();return;}
  const token=generation,expectedCatalog=catalog;controller=new AbortController();const signal=controller.signal;busy=true;publish();const valid=()=>token===generation&&!signal.aborted&&connectionController.getWorkflowClient()?.sessionId===binding.sessionId&&!document.hidden;
  try{const validation=await binding.client.validatePhone(spec,expectedCatalog,signal);if(!valid())return;const pending:Pending={mutationId:crypto.randomUUID(),specDigest:validation.specDigest,compilerRevision:expectedCatalog.compilerRevision,...(draft.workflowId?{workflowId:draft.workflowId,versionId:draft.versionId}:{})};draft.spec=validation.spec;draft.pending=pending;persist();await localSaved();if(!valid())return;const receipt=await binding.client.savePhone(validation.spec,expectedCatalog,pending,signal);if(!valid())return;await committed(receipt.workflowId,token);}
  catch(error){if(valid()){status=draft?.pending?'Save outcome unknown. Refresh the exact save receipt. The app will not submit a second workflow.':(error as Error).message;toast(status);}}finally{if(token===generation){busy=false;controller=null;publish();}}
 }
 async function committed(id:string,token:number){await localSaved();const target=storage!;const result=await target.secure.secureCompareExchange({slot:target.slot,expectedValue:target.raw,value:null});if(result.status!=='saved')throw new Error('Saved on agent; local draft cleanup needs recovery');target.raw=null;if(token!==generation)return;draft=null;close();await onSaved(id);toast('Workflow saved paused');}
 async function recover(){if(!draft?.pending||busy)return;const binding=connectionController.getWorkflowClient();if(!binding)return;const token=generation,pending=draft.pending;controller=new AbortController();busy=true;publish();try{const receipt=await binding.client.phoneSaveReceipt(pending,controller.signal);if(token!==generation||binding.sessionId!==connectionController.getWorkflowClient()?.sessionId||document.hidden)return;if(receipt)await committed(receipt.workflowId,token);else{status='No committed receipt yet. This save stays locked; no new POST was sent.';publish();}}catch{if(token===generation){status='Save receipt unavailable. The draft and original mutation identity remain on this phone.';publish();}}finally{if(token===generation){busy=false;controller=null;publish();}}}
 async function discardDraft(){if(!draft||busy||draft.pending)return;if(!discard){discard=true;status='Tap Discard local draft again to remove only this local draft.';publish();return;}try{await localSaved();const result=await storage!.secure.secureCompareExchange({slot:storage!.slot,expectedValue:storage!.raw,value:null});if(result.status!=='saved')throw new Error('Draft changed elsewhere');draft=null;close();}catch(error){toast((error as Error).message);}}
 function field(label:string,value:string,onChange:(value:string)=>void,type='text',multiline=false){return {label,value,type,multiline,single:!multiline,change:(event:Bag)=>change(()=>onChange(String(event.target.value)))};}
 function render(api:Bag){const step=selected(),index=step&&draft?draft.spec.steps.indexOf(step):-1,fields:Bag[]=[];if(step){
  if(step.operation==='supplied_text')fields.push(field('Text supplied to workflow',step.text,v=>step.text=v,'text',true));
  if(step.operation==='contains')fields.push(field('Text to match',step.text,v=>step.text=v));
  if(step.operation==='compose_draft')fields.push(field('Text before input',step.prefix,v=>step.prefix=v,'text',true),field('Text after input',step.suffix,v=>step.suffix=v,'text',true));
  if(step.operation==='model_draft')fields.push(field('Drafting instruction',step.instruction,v=>step.instruction=v,'text',true));
  if(step.operation==='save_note')fields.push(field('New note title',step.title,v=>step.title=v));
  if(step.operation==='calendar_range'){fields.push(field('Range start (UTC ISO)',step.range.start,v=>step.range.start=v),field('Range end, exclusive (UTC ISO)',step.range.end,v=>step.range.end=v),field('Review time zone',step.range.timeZone,v=>step.range.timeZone=v),field('Maximum events (1–200)',String(step.range.maximumEvents),v=>step.range.maximumEvents=Number(v),'number'));}
 }
 const enabledOptions=step?catalog?.palette.find(p=>p.kind===step.kind)?.operations??[]:[];
 const rows:Bag[]=draft?.spec.steps.map(s=>({k:s.kind,t:`${s.kind}: ${s.operation.replaceAll('_',' ')}`,d:api.ic[icons[s.kind]],dotCss:'background:var(--s2)',boxCss:'background:var(--s2)',tap:()=>{if(locked())return;sheet=s.id;review=null;if(s.operation==='calendar_range')void loadCalendars();publish();}}))??[];
 rows.unshift({k:'When',t:'Only when you explicitly choose Run now',d:api.ic.clock,dotCss:'background:var(--s2)',boxCss:'background:var(--s2)',tap:()=>{sheet='trigger';publish();}});
 return {typed:true,fullEditor:true,metadataOnly:false,name:draft?.spec.name||'',onName:(event:Bag)=>change(()=>{draft!.spec.name=String(event.target.value);}),description:draft?.spec.description||'',onDescription:(event:Bag)=>change(()=>{draft!.spec.description=String(event.target.value);}),saveOff:locked()||!draft||!draft.spec.steps.length,saveCss:locked()?'background:var(--s2);color:var(--mut)':'background:var(--acc);color:#fff',save,cancel:close,typedStatus:status,typedReview:review||'',hasTypedReview:!!review,unknown:!!draft?.pending,refresh:recover,discard:discardDraft,canDiscard:!!draft&&!draft.pending&&!busy,steps:rows,palette:palette.map(k=>({k,d:api.ic[icons[k]],label:'Add '+k+' step',add:()=>add(k)})),hasApps:false,empty:!draft?.spec.steps.length,describe:()=>toast('Choose explicit typed steps from the palette. Natural-language workflow generation is not connected.'),sheetOn:!!sheet,closeSheet:()=>{sheet=null;publish();},isTrig:sheet==='trigger',isStep:!!step,
  tr:{kinds:(catalog?.triggers??[]).map(t=>({label:t.kind,css:t.kind==='manual'?'background:var(--acc);color:#fff':'background:var(--s2);color:var(--mut)',pick:()=>toast(t.kind==='manual'?'This workflow runs only when you explicitly start it':t.reason||'This trigger is unavailable')})),text:'Run manually after reviewing the workflow',isTime:false,isEvent:false,isPlace:false,isMsg:false,isEmail:false},
  sp:step?{typed:true,freeTextStyle:"display:none",k:step.kind,d:api.ic[icons[step.kind]],up:()=>move(-1),down:()=>move(1),upCss:index===0?'opacity:.3':'',downCss:index===draft!.spec.steps.length-1?'opacity:.3':'',presets:enabledOptions.map(o=>({label:o.label||o.id.replaceAll('_',' '),css:o.id===step.operation?'background:var(--acc);color:#fff':o.available&&known.has(o.id)?'background:var(--s2)':'background:var(--s2);opacity:.5',pick:()=>chooseOperation(o.id)})),text:'',onText:()=>{},fields,hasSource:!!step.source,sources:draft!.spec.steps.slice(0,index).map(s=>({label:s.kind+': '+s.operation.replaceAll('_',' '),selected:step.source===s.id,pick:()=>change(()=>{step.source=s.id;})})),caseMatch:step.operation==='contains',caseLabel:step.caseSensitive?'Case-sensitive match':'Ignore letter case',toggleCase:()=>change(()=>{step.caseSensitive=!step.caseSensitive;}),isNotes:step.operation==='selected_notes',notes:step.operation==='selected_notes'?(owner()?.vget('notes').list??[]).map((n:Bag)=>({label:n.title||'Untitled note',selected:step.notes.some((chosen:Bag)=>chosen.id===n.id),pick:()=>void chooseNote(n.id)})):[],isCalendar:step.operation==='calendar_range',connectCalendars:()=>void loadCalendars(true),calendars:step.operation==='calendar_range'?calendars.map(c=>({label:c.name+' · '+c.account,selected:step.range.calendarIds.includes(c.id),pick:()=>change(()=>{const chosen=step.range.calendarIds;step.range.calendarIds=chosen.includes(c.id)?chosen.filter((id:string)=>id!==c.id):chosen.length<16?[...chosen,c.id]:chosen;})})):[],del:remove}:null};
 }
 return {get active(){return active;},open,close,render};
}
