import './calendar-meeting.css';
import {BrowserMicrophone} from './sensor-policy';
/** Origin-local meeting room: browser preview media never leaves this page. */
export function openCalendarMeeting(title:string,people:string[]){
 document.querySelector<HTMLDialogElement>('[data-calendar-meeting]')?.dispatchEvent(new Event('close'));
 const dialog=document.createElement('dialog');dialog.dataset.calendarMeeting='true';dialog.setAttribute('aria-label','Calendar meeting');dialog.className='alpha-calendar-meeting';const theme=document.querySelector('.os');if(theme){const style=getComputedStyle(theme);for(const token of ['bg','fg','s2','line'])dialog.style.setProperty('--meeting-'+token,style.getPropertyValue('--'+token));dialog.style.colorScheme=style.getPropertyValue('--bg').trim().toUpperCase()==='#000000'?'dark':'light';}const heading=document.createElement('h2');heading.textContent=title;const summary=document.createElement('p');summary.textContent='Local preview only. Other people are not connected, and camera and microphone media stay on this page.';const guests=document.createElement('p');guests.textContent=people.length?people.join(', '):'Just you';const video=document.createElement('video');video.autoplay=true;video.muted=true;video.playsInline=true;video.style.cssText='width:100%;max-height:280px;object-fit:cover;border-radius:12px';video.hidden=true;const status=document.createElement('p');status.setAttribute('role','status');const content=document.createElement('div'),controls=document.createElement('div'),footer=document.createElement('footer');content.className='alpha-meeting-content';controls.className='alpha-meeting-controls';content.append(heading,summary,guests,video,controls,status);dialog.append(content,footer);const showError=(message:string)=>{status.textContent=message;status.scrollIntoView({block:'nearest'});};
 const button=(name:string)=>{const b=document.createElement('button');b.textContent=name;controls.append(b);return b;};const camera=button('Turn camera on'),microphone=button('Unmute microphone'),leave=button('Leave meeting');footer.append(leave);
 let alive=true,cameraEpoch=0,cameraStream:MediaStream|undefined,mic:BrowserMicrophone|undefined;
 const stopCamera=()=>{++cameraEpoch;cameraStream?.getTracks().forEach(track=>track.stop());cameraStream=undefined;video.srcObject=null;video.hidden=true;camera.textContent='Turn camera on';camera.disabled=false;};
 const stopMic=()=>{mic?.close();mic=undefined;microphone.textContent='Unmute microphone';microphone.disabled=false;};
 camera.onclick=async()=>{if(cameraStream){stopCamera();return;}const epoch=++cameraEpoch;camera.disabled=true;status.textContent='';try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});if(!alive||epoch!==cameraEpoch){stream.getTracks().forEach(track=>track.stop());return;}cameraStream=stream;for(const track of stream.getVideoTracks())track.addEventListener('ended',()=>{if(cameraStream===stream)stopCamera();},{once:true});video.srcObject=stream;video.hidden=false;camera.textContent='Turn camera off';camera.disabled=false;await video.play();}catch{if(alive&&epoch===cameraEpoch){stopCamera();showError('Camera could not start. Try again.');}}finally{if(alive&&epoch===cameraEpoch)camera.disabled=false;}};
 microphone.onclick=async()=>{if(mic){stopMic();return;}const lease=new BrowserMicrophone(stopMic);mic=lease;microphone.disabled=true;status.textContent='';try{const stream=await lease.open();for(const track of stream.getAudioTracks())track.addEventListener('ended',()=>{if(mic===lease)stopMic();},{once:true});if(alive&&mic===lease){microphone.textContent='Mute microphone';microphone.disabled=false;}}catch{if(alive&&mic===lease){stopMic();showError('Microphone could not start. Try again.');}}};
 const previous=document.activeElement as HTMLElement|null;
 const close=()=>{if(!alive)return;alive=false;stopCamera();stopMic();window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',close);window.removeEventListener('alpha:device-state',close);document.removeEventListener('visibilitychange',visibility);dialog.remove();if(previous?.isConnected)previous.focus();};const back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();close();},visibility=()=>{if(document.hidden)close();};leave.onclick=close;dialog.oncancel=close;dialog.onclose=close;window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',close);window.addEventListener('alpha:device-state',close);document.addEventListener('visibilitychange',visibility);document.body.append(dialog);dialog.showModal();leave.focus();return {status:'opened'};
}
