export interface EditableCalendarEvent {title:string;body:string;location:string;begin:number;end:number;allDay?:boolean;timeZone?:string}
function wall(instant:number,zone:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone,calendar:'iso8601',numberingSystem:'latn',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(instant).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}.${String(((instant%1000)+1000)%1000).padStart(3,'0')}`;}
function civil(text:string){const n=Date.parse(text+'Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==text.slice(0,10))throw Error('Choose valid dates and times.');return n;}
/** Explicit saved-zone conversion: reject gaps and preserve the original overlap instant. */
export function calendarInstant(value:string,zone:string,original:number){const desired=civil(value),normalized=new Date(desired).toISOString().slice(0,-1);if(wall(original,zone)===normalized)return original;const offsets=new Set<number>();for(let h=-48;h<=48;h+=6){const probe=desired+h*3600000;offsets.add(civil(wall(probe,zone))-probe);}const candidates=[...offsets].map(o=>desired-o).filter(n=>wall(n,zone)===normalized).sort((a,b)=>a-b);if(!candidates.length)throw Error('That time does not exist in this time zone. Choose another time.');return candidates[0];}
export function editCalendarEvent(row:EditableCalendarEvent,commit:(next:EditableCalendarEvent,current:()=>boolean)=>Promise<void>):Promise<{status:'saved'|'cancelled'}>{
 const zone=row.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone;
 const dialog=document.createElement('dialog');dialog.setAttribute('aria-label','Edit calendar event');dialog.style.cssText='width:min(440px,85vw);max-height:85vh;overflow:auto;border:0;border-radius:20px;padding:20px;font:16px system-ui';
 const theme=document.querySelector('.os');if(theme){const style=getComputedStyle(theme);dialog.style.background=style.getPropertyValue('--bg');dialog.style.color=style.getPropertyValue('--fg');}
 const heading=document.createElement('h2');heading.textContent='Edit calendar event';dialog.append(heading);
 const field=(label:string,type:string,value:string)=>{const wrapper=document.createElement('label');wrapper.style.cssText='display:flex;flex-direction:column;gap:6px;margin:12px 0';wrapper.append(label);const input=document.createElement('input');input.type=type;input.value=value;input.style.cssText='font:inherit;padding:10px;min-width:0';wrapper.append(input);dialog.append(wrapper);return input;};
 const title=field('Event title','text',row.title),description=field('Event description','text',row.body),location=field('Event location','text',row.location),allDay=field('All day','checkbox','');allDay.checked=!!row.allDay;
 const start=field('Starts','datetime-local',''),end=field('Ends','datetime-local',''),timeZone=field('Time zone','text',zone);start.step=end.step='0.001';
 const initialize=()=>{start.type=end.type=allDay.checked?'date':'datetime-local';start.value=allDay.checked?new Date(row.begin).toISOString().slice(0,10):wall(row.begin,timeZone.value);end.value=allDay.checked?new Date(row.end-86400000).toISOString().slice(0,10):wall(row.end,timeZone.value);timeZone.disabled=allDay.checked;};initialize();allDay.onchange=()=>{try{initialize();}catch{timeZone.value=zone;initialize();}};
 const hint=document.createElement('p');hint.textContent='All-day end dates include the selected day. For repeated clock times, unchanged values keep their original occurrence; edited values use the first occurrence.';hint.style.fontSize='13px';dialog.append(hint);
 const error=document.createElement('p');error.setAttribute('role','status');dialog.append(error);const save=document.createElement('button'),cancel=document.createElement('button');save.textContent='Save event';cancel.textContent='Cancel';for(const button of [save,cancel])button.style.cssText='font:inherit;padding:12px;margin-right:10px';dialog.append(save,cancel);
 const previous=document.activeElement as HTMLElement|null;let alive=true,busy=false;
 return new Promise(resolve=>{const finish=(status:'saved'|'cancelled')=>{if(!alive)return;alive=false;window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',close);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('alpha:device-state',close);dialog.remove();if(previous?.isConnected)previous.focus();resolve({status});};const close=()=>finish('cancelled'),back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();close();},visibility=()=>{if(document.hidden)close();};
 cancel.onclick=close;dialog.oncancel=close;window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',close);document.addEventListener('visibilitychange',visibility);window.addEventListener('alpha:device-state',close);
 save.onclick=async()=>{if(busy)return;try{if(!title.value.trim())throw Error('Enter an event title.');const begin=allDay.checked?civil(start.value+'T00:00:00'):calendarInstant(start.value,timeZone.value,row.begin),finishAt=allDay.checked?civil(end.value+'T00:00:00')+86400000:calendarInstant(end.value,timeZone.value,row.end);if(finishAt<=begin)throw Error('The end must be after the start.');busy=true;save.disabled=true;await commit({title:title.value.trim(),body:description.value,location:location.value,begin,end:finishAt,allDay:allDay.checked,timeZone:allDay.checked?zone:timeZone.value},()=>alive&&!document.hidden);finish('saved');}catch(e){if(alive)error.textContent=e instanceof Error?e.message:'The event could not be saved. Try again.';}finally{busy=false;if(alive)save.disabled=false;}};
 document.body.append(dialog);dialog.showModal();title.focus();});
}
