import './calendar-editor.css';
export interface EditableCalendarEvent {title:string;body:string;location:string;begin:number;end:number;allDay?:boolean;timeZone?:string;repeat?:'none'|'daily'|'weekdays'|'weekly';alert?:number|null;who?:string[];video?:boolean}
export type CalendarPerson={id:string;name:string};
export function calendarWall(instant:number,zone:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone,calendar:'iso8601',numberingSystem:'latn',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(instant).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}.${String(((instant%1000)+1000)%1000).padStart(3,'0')}`;}
function civil(text:string){const n=Date.parse(text+'Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==text.slice(0,10))throw Error('Choose valid dates and times.');return n;}
/** Explicit saved-zone conversion: reject gaps and preserve the original overlap instant. */
export function calendarInstant(value:string,zone:string,original:number,gap:'reject'|'forward'='reject'){const desired=civil(value),normalized=new Date(desired).toISOString().slice(0,-1);if(Number.isFinite(original)&&calendarWall(original,zone)===normalized)return original;const offsets=new Set<number>();for(let h=-48;h<=48;h+=6){const probe=desired+h*3600000;offsets.add(civil(calendarWall(probe,zone))-probe);}const candidates=[...offsets].map(o=>desired-o).filter(n=>calendarWall(n,zone)===normalized).sort((a,b)=>a-b);if(!candidates.length){if(gap==='forward'){const after=[...offsets].map(o=>desired-o).filter(n=>civil(calendarWall(n,zone))>desired).sort((a,b)=>a-b);if(after.length)return after[0];}throw Error('That time does not exist in this time zone. Choose another time.');}return candidates[0];}
export function editCalendarEvent(row:EditableCalendarEvent,commit:(next:EditableCalendarEvent,current:()=>boolean)=>Promise<void>,people:CalendarPerson[]=[]):Promise<{status:'saved'|'cancelled'}>{
 const zone=row.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone;
 const dialog=document.createElement('dialog');dialog.className='alpha-calendar-editor';dialog.setAttribute('aria-label','Edit calendar event');
 const theme=document.querySelector('.os');if(theme){const style=getComputedStyle(theme);for(const token of ['bg','fg','s2','line','mut'])dialog.style.setProperty('--editor-'+token,style.getPropertyValue('--'+token));dialog.style.colorScheme=style.getPropertyValue('--bg').trim().toUpperCase()==='#000000'?'dark':'light';}
 const header=document.createElement('header'),heading=document.createElement('h2'),dismiss=document.createElement('button');heading.textContent='Edit calendar event';dismiss.type='button';dismiss.className='alpha-calendar-dismiss';dismiss.setAttribute('aria-label','Close calendar editor');dismiss.textContent='×';header.append(heading,dismiss);dialog.append(header);
 const form=document.createElement('div');form.className='alpha-calendar-fields';dialog.append(form);
 function field(label:string,type:'textarea',value:string):HTMLTextAreaElement;
 function field(label:string,type:string,value:string):HTMLInputElement;
 function field(label:string,type:string,value:string):HTMLInputElement|HTMLTextAreaElement{
   const wrapper=document.createElement('label');wrapper.className='alpha-calendar-field'+(type==='checkbox'?' alpha-calendar-checkbox':'');wrapper.append(label);
   const input=type==='textarea'?document.createElement('textarea'):document.createElement('input');if(input instanceof HTMLInputElement)input.type=type;else input.rows=3;input.value=value;input.addEventListener('focus',()=>requestAnimationFrame(()=>{if(document.activeElement===input)wrapper.scrollIntoView({block:'nearest'});}));wrapper.append(input);form.append(wrapper);return input;
 }
 const title=field('Event title','text',row.title),description=field('Event description','textarea',row.body),location=field('Event location','text',row.location),allDay=field('All day','checkbox','');allDay.checked=!!row.allDay;
 const start=field('Starts','datetime-local',''),end=field('Ends','datetime-local',''),timeZone=field('Time zone','text',zone);start.step=end.step='0.001';
 const setDates=(isAllDay:boolean,begin:string,finish:string)=>{start.type=end.type=isAllDay?'date':'datetime-local';start.value=begin;end.value=finish;timeZone.disabled=isAllDay;};
 setDates(!!row.allDay,row.allDay?new Date(row.begin).toISOString().slice(0,10):calendarWall(row.begin,zone),row.allDay?new Date(row.end-1).toISOString().slice(0,10):calendarWall(row.end,zone));
 // Keep the unsaved timed draft when toggling presentation; date-only changes
 // intentionally become midnight boundaries in the selected civil time zone.
 let timedDraft:{start:string;end:string;firstDay:string;lastDay:string}|undefined;
 allDay.onchange=()=>{
   if(allDay.checked){
     const firstDay=start.value.slice(0,10),lastDay=end.value?new Date(civil(end.value)-1).toISOString().slice(0,10):'';
     timedDraft={start:start.value,end:end.value,firstDay,lastDay};setDates(true,firstDay,lastDay);
   }else if(timedDraft&&start.value===timedDraft.firstDay&&end.value===timedDraft.lastDay){setDates(false,timedDraft.start,timedDraft.end);}
   else{const begin=start.value?start.value+'T00:00:00':'',finish=end.value?new Date(civil(end.value+'T00:00:00')+86400000).toISOString().slice(0,-1):'';setDates(false,begin,finish);}
 };

 const repeat=document.createElement('select');repeat.setAttribute('aria-label','Repeat');if(row.repeat&&row.repeat!=='none'){const label=document.createElement('label');label.textContent='Repeat';label.className='alpha-calendar-field';for(const [value,text] of [['none','Once'],['daily','Daily'],['weekdays','Weekdays'],['weekly','Weekly']]){const option=document.createElement('option');option.value=value;option.textContent=text;repeat.append(option);}repeat.value=row.repeat;label.append(repeat);form.append(label);}
 const alert=document.createElement('select');alert.setAttribute('aria-label','Event alert');const alertLabel=document.createElement('label');alertLabel.textContent='Event alert';alertLabel.className='alpha-calendar-field';for(const [value,text] of [['none','None'],['0','At start'],['10','10 minutes before'],['60','1 hour before']]){const option=document.createElement('option');option.value=value;option.textContent=text;alert.append(option);}alert.value=row.alert==null?'none':String(row.alert);alertLabel.append(alert);form.append(alertLabel);
 const video=field('Local meeting room','checkbox','');video.checked=!!row.video;
 const attendees=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent='Attendees';attendees.append(legend);const selected=new Set(row.who||[]),choices=new Map(people.map(person=>[person.id,person.name]));for(const id of selected)if(!choices.has(id))choices.set(id,id);
 for(const [id,name] of choices){const label=document.createElement('label');label.className='alpha-calendar-person';const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(id);check.onchange=()=>{if(check.checked)selected.add(id);else selected.delete(id);};label.append(check,document.createTextNode(name));attendees.append(label);}if(!choices.size){const empty=document.createElement('p');empty.textContent='Add people in Contacts to select attendees.';attendees.append(empty);}form.append(attendees);
 const hint=document.createElement('p');hint.textContent='All-day end dates include the selected day. For repeated clock times, unchanged values keep their original occurrence; edited values use the first occurrence.';hint.className='alpha-calendar-hint';form.append(hint);
 const error=document.createElement('p');error.setAttribute('role','status');error.className='alpha-calendar-error';form.append(error);const save=document.createElement('button'),cancel=document.createElement('button');save.textContent='Save event';cancel.textContent='Cancel';const actions=document.createElement('footer');actions.append(save,cancel);dialog.append(actions);
 const previous=document.activeElement as HTMLElement|null;let alive=true,busy=false;
 return new Promise(resolve=>{const finish=(status:'saved'|'cancelled')=>{if(!alive)return;alive=false;window.removeEventListener('alpha-back',back,true);window.removeEventListener('pagehide',close);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('alpha:device-state',close);dialog.remove();if(previous?.isConnected)previous.focus();resolve({status});};const close=()=>finish('cancelled'),back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();close();},visibility=()=>{if(document.hidden)close();};
 cancel.onclick=close;dismiss.onclick=close;dialog.oncancel=close;window.addEventListener('alpha-back',back,true);window.addEventListener('pagehide',close);document.addEventListener('visibilitychange',visibility);window.addEventListener('alpha:device-state',close);
 save.onclick=async()=>{if(busy)return;try{if(!title.value.trim())throw Error('Enter an event title.');const begin=allDay.checked?civil(start.value+'T00:00:00'):calendarInstant(start.value,timeZone.value,row.begin),finishAt=allDay.checked?civil(end.value+'T00:00:00')+86400000:calendarInstant(end.value,timeZone.value,row.end);if(finishAt<=begin)throw Error('The end must be after the start.');busy=true;save.disabled=true;await commit({title:title.value.trim(),body:description.value,location:location.value,begin,end:finishAt,allDay:allDay.checked,timeZone:timeZone.value,alert:alert.value==='none'?null:Number(alert.value),who:[...selected],video:video.checked,...(repeat.isConnected?{repeat:repeat.value as EditableCalendarEvent['repeat']}:{})},()=>alive&&!document.hidden);finish('saved');}catch(e){if(alive){error.textContent=e instanceof Error?e.message:'The event could not be saved. Try again.';error.scrollIntoView({block:'nearest'});}}finally{busy=false;if(alive)save.disabled=false;}};
 document.body.append(dialog);dialog.showModal();title.focus();});
}
