import {useEffect,useRef,useState} from 'react';
import {CloudPersonalSetup,type PersonalSetupState} from '../runtime/cloud-personal-setup';
import type {CloudPersonalProtocol,PersonalView} from '../runtime/cloud-personal-protocol';
import {openDomainRecovery} from './domain-recovery';
import {configureDevelopmentCloud,developmentCloudSetupDocument,readDevelopmentCloudAccount,developmentAccountRecovery,type DevelopmentScenario,developmentCloudAccount,developmentPersonal,selectDevelopmentCloud,type DevelopmentAccount} from './development-cloud';
/** Local account fixture uses the production quote/receipt parser and review component. */
export function DevelopmentCloudSetup({connect}:{connect:()=>Promise<void>}){
 const [account,setAccount]=useState<ReturnType<typeof developmentCloudAccount>>(null),[choice,setChoice]=useState<DevelopmentAccount>('first'),[setup,setSetup]=useState<PersonalSetupState>({view:null,blocked:false,declined:false}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false);
 const [scenario,setScenario]=useState<DevelopmentScenario>('new');
 const client=useRef<CloudPersonalProtocol|null>(null),pending=useRef<AbortController|null>(null),generation=useRef(0),recovery=useRef<AbortController|null>(null);
 const retire=()=>{recovery.current?.abort();generation.current++;pending.current?.abort();pending.current=null;client.current=null;setBusy(false);setSetup({view:null,blocked:false,declined:false});};
 useEffect(()=>{
  const lifetime=new AbortController();
  const load=async()=>{const token=generation.current;setReady(false);setAccount(null);try{const saved=await readDevelopmentCloudAccount(lifetime.signal);if(lifetime.signal.aborted||token!==generation.current)return;setAccount(saved);setReady(true);setError('');if(saved){setChoice(saved.account);client.current=developmentPersonal(saved);}}catch(e){if(!lifetime.signal.aborted&&token===generation.current)setError((e as Error).message);}};
  const changed=()=>{retire();void load();};
  const hidden=()=>{if(document.hidden)retire();};window.addEventListener('alpha:development-account-invalidated',changed);document.addEventListener('visibilitychange',hidden);void load();
  return()=>{lifetime.abort();recovery.current?.abort();generation.current++;pending.current?.abort();window.removeEventListener('alpha:development-account-invalidated',changed);document.removeEventListener('visibilitychange',hidden);};
 },[]);
 async function work(run:(signal:AbortSignal)=>Promise<void>){if(pending.current)return;const controller=new AbortController(),token=generation.current;pending.current=controller;setBusy(true);setError('');try{await run(controller.signal);}catch(e){if(!controller.signal.aborted&&token===generation.current)setError((e as Error).message);}finally{if(pending.current===controller){pending.current=null;setBusy(false);}}}
 const publish=(view:PersonalView)=>setSetup({view,blocked:false,declined:false});
 async function inspect(signal:AbortSignal){const saved=await readDevelopmentCloudAccount(signal);if(!saved)throw Error('Choose a development account.');const next=developmentPersonal(saved);const view=await next.inspect(signal);signal.throwIfAborted();client.current=next;setAccount(saved);publish(view);}
 return <section aria-label="Development Cloud account"><h2>Development Cloud account</h2><p>Local setup with sample hosting amounts.</p><label>Sample account<select aria-label="Sample account" value={choice} disabled={busy||!ready} onChange={e=>setChoice(e.target.value as DevelopmentAccount)}><option value="first">First account</option><option value="second">Second account</option></select></label><button disabled={busy||!ready} onClick={()=>void work(async signal=>{const selected=await selectDevelopmentCloud(choice,signal);signal.throwIfAborted();setAccount(selected);await inspect(signal);})}>Use development account</button><button disabled={busy} onClick={()=>{retire();const controller=recovery.current=new AbortController();openDomainRecovery(developmentAccountRecovery,'Cloud account','Development Cloud account recovery','Download the saved sample account selection before resetting. Reset signs out development Cloud selection; it does not delete provisioning state, conversations or real provider credentials.',controller.signal);}}>Cloud account recovery</button>
 {account&&<><p>Connected development account: {account.account}</p><button disabled={busy} onClick={()=>void work(inspect)}>Refresh development setup</button><button disabled={busy} onClick={()=>void work(async signal=>{await selectDevelopmentCloud(null,signal);signal.throwIfAborted();setAccount(null);client.current=null;setSetup({view:null,blocked:false,declined:false});})}>Sign out development account</button>
 <button disabled={busy} onClick={()=>{if(!account)return;retire();const controller=recovery.current=new AbortController();openDomainRecovery(developmentCloudSetupDocument(account),'Cloud setup','Development Cloud setup recovery','Download this sample account’s provisioning state before resetting. Reset affects only local development setup; it does not stop hosted compute, revoke real credentials or clear conversations.',controller.signal);}}>Cloud setup recovery</button>
 <details><summary>Development setup scenario</summary><label>Setup scenario<select aria-label="Setup scenario" disabled={busy} value={scenario} onChange={e=>setScenario(e.target.value as DevelopmentScenario)}><option value="new">New Dedicated</option><option value="existing">Existing Dedicated</option><option value="insufficient">Insufficient balance</option><option value="failed">Provisioning failure</option><option value="changed">Changed quote</option></select></label><button disabled={busy} onClick={()=>void work(async signal=>{await configureDevelopmentCloud(scenario,signal);await inspect(signal);})}>Reset development setup</button></details>
 <CloudPersonalSetup setup={setup} busy={busy} onDecline={()=>setSetup({view:null,blocked:false,declined:true})} onAccept={()=>void work(async signal=>{if(setup.view?.kind!=='review'||!client.current)return;try{const next=await client.current.accept(setup.view.review,signal);signal.throwIfAborted();publish(next);}catch(e){if(!signal.aborted)setSetup(s=>({...s,blocked:true}));throw e;}})} onPoll={()=>void work(async signal=>{if(setup.view?.kind==='pending'&&client.current){const next=await client.current.poll(setup.view.receipt,signal);signal.throwIfAborted();publish(next);}else await inspect(signal);})} onFinalize={()=>void work(async signal=>{if(setup.view?.kind==='pending'&&client.current){try{const next=await client.current.finalize(setup.view.receipt,signal);signal.throwIfAborted();publish(next);}catch(e){if(!signal.aborted)setSetup(s=>({...s,blocked:true}));throw e;}}})} onConnect={()=>void work(async signal=>{const saved=await readDevelopmentCloudAccount(signal);if(!saved||saved.session!==account.session)throw Error('Development account changed.');const view=await developmentPersonal(saved).inspect(signal);signal.throwIfAborted();if(view.kind!=='ready')throw Error('Finish development setup first.');await connect();})}/></>}
 {busy&&<button onClick={()=>{retire();}}>Cancel development setup</button>}{error&&<p role="alert">{error}</p>}
 </section>;
}
