import {developmentDigestRequest} from './development-digests';
import {authorWorkflowProposal,existingWorkflowProposal,developmentProposal,developmentCredential} from './development-actions';
import {validateWorkflowResult} from '../runtime/workflow-device-contract';
import type {DeviceOperation} from '../runtime/device-actions';
import {normalizePhoneSpec,type PhoneSpec,type PhoneSaveReceipt} from '../runtime/phone-workflow-authoring';
import {workflowSha} from '../runtime/workflow-device-contract';
import {assertDevelopmentIdentity,type DevelopmentIdentity} from './development-identity';
import {editStore,readStore} from './store';
type Workflow={removed?:boolean;triggerCleanup?:'complete';id:string;name:string;description:string;active:boolean;versionId:string;phoneSpec:PhoneSpec;steps:Array<{label:string}>};
type Run={proposalIds?:Record<string,string>;id:string;workflowId:string;workflowVersionId:string;submissionId:string;status:string;finished:boolean;startedAt:string;stoppedAt?:string;output?:string;error?:{message:string};spec:PhoneSpec;stepIndex:number;values:Record<string,string>;events:Array<{runId:string;workflowId:string;type:string;timestamp:string;nodeId?:string}>};
type State={mutations?:Array<{id:string;input:string;receipt:Record<string,any>}>;runs?:Run[];workflows:Workflow[];receipts:Array<{input:string;receipt:PhoneSaveReceipt}>};
const publicWorkflow=(workflow:Workflow)=>({...workflow,metadata:{elizaPhoneWorkflowSpec:JSON.stringify(workflow.phoneSpec)}});
const catalog={specVersion:1,catalogRevision:'development-v1',compilerRevision:'development-v1',maximumSteps:32,maximumSpecBytes:65536,triggers:[{kind:'manual',available:true}],palette:[{kind:'Read',operations:['supplied_text','selected_notes','calendar_range'].map(id=>({id,available:true}))},{kind:'Notify',operations:[{id:'app_notification',available:true}]},{kind:'Speak',operations:[{id:'read_aloud',available:true}]},{kind:'If',operations:[{id:'contains',available:true}]},{kind:'Write',operations:['compose_draft','model_draft','save_note'].map(id=>({id,available:true}))}]};
/** Local owner-scoped workflow authoring protocol. Execution is added at the same seam. */
export async function developmentWorkflowRequest(identity:DevelopmentIdentity,path:string,body:any,signal?:AbortSignal){return navigator.locks.request('alpha.browser.workflow-admission.'+identity.namespace,{...(signal?{signal}:{})},()=>workflowRequest(identity,path,body,signal));}
async function workflowRequest(identity:DevelopmentIdentity,path:string,body:any,signal?:AbortSignal){
 const check=()=>{signal?.throwIfAborted();assertDevelopmentIdentity(identity);const selected=JSON.parse(localStorage.getItem('alpha.connection.selection.v1')||'null');if(selected?.kind!=='development'||selected.profile!==identity.profile)throw Error('Workflow connection changed.');};check();
 const key=`alpha.browser.workflows.${identity.namespace}.v1`,initial=():State=>({workflows:[],receipts:[]});
 const read=()=>{const state=readStore(key,initial);if(!Array.isArray(state.workflows)||!Array.isArray(state.receipts)||state.workflows.length>100||state.receipts.length>500)throw Error('Development workflows need recovery.');return state;};
 if(path.startsWith('/api/workflow/hosted/'))return developmentDigestRequest(identity,path,body,signal);
 if(path==='/api/workflow/status')return {hostedDigestProtocol:1,engine:'smthrs',status:'ready',manualSubmissionProtocol:1,metadataMutationProtocol:1,lifecycleMutationProtocol:1};
 if(path==='/api/workflow/phone/catalog')return catalog;
 if(path==='/api/workflow/workflows'&&body===undefined)return {workflows:read().workflows.filter(w=>!w.removed).map(publicWorkflow)};
 if(path==='/api/workflow/removed-workflows'&&body===undefined)return {workflows:read().workflows.filter(w=>w.removed).map(publicWorkflow)};

 const event=(run:Run,type:string,nodeId?:string)=>run.events.push({runId:run.id,workflowId:run.workflowId,type,timestamp:new Date().toISOString(),...(nodeId?{nodeId}:{})});
 const execute=(run:Run)=>{for(;run.stepIndex<run.spec.steps.length;run.stepIndex++){
  const step=run.spec.steps[run.stepIndex],source=run.values[step.source]||'';let output:string;
  if(['selected_notes','calendar_range','save_note','app_notification','read_aloud'].includes(step.operation)){(run.proposalIds??={})[step.id]??=crypto.randomUUID();run.status='waiting_for_approval';event(run,'phone_approval_required',step.id);return;}
  event(run,'step_started',step.id);
  if(step.operation==='supplied_text')output=step.text;
  else if(step.operation==='contains'){const matched=step.caseSensitive?source.includes(step.text):source.toLowerCase().includes(step.text.toLowerCase());if(!matched){run.status='skipped';run.finished=true;run.stoppedAt=new Date().toISOString();event(run,'condition_not_met',step.id);return;}output=source;}
  else if(step.operation==='compose_draft')output=step.prefix+source+step.suffix;
  else if(step.operation==='model_draft'){const configured=readStore<{reply:string}>(`alpha.browser.agent.${identity.namespace}.v1`,()=>({reply:'Development reply. Edit this response in Agent connection.'}));output=configured.reply;}
  else throw Error('Unknown development workflow step.');
  if(typeof output!=='string'||output.length>16000)throw Error('Workflow step output exceeds 16000 characters.');run.values[step.id]=output;run.output=output;event(run,'step_completed',step.id);
 }run.status='succeeded';run.finished=true;run.stoppedAt=new Date().toISOString();event(run,'execution_completed');};
 const operationFor=(run:Run):DeviceOperation=>{const step=run.spec.steps[run.stepIndex];if(step.operation==='selected_notes')return {type:'read_selected_notes',notes:step.notes};if(step.operation==='calendar_range')return {type:'read_calendar_range',...step.range};if(step.operation==='save_note')return {type:'create_note',title:step.title,body:run.values[step.source]||''};if(step.operation==='app_notification')return {type:'post_notification',title:step.title,body:run.values[step.source]||''};if(step.operation==='read_aloud')return {type:'speak_text',text:run.values[step.source]||''};throw Error('No phone step is pending.');};
 const advance=async(id:string)=>editStore(key,initial,async data=>{check();const run=data.runs?.find(r=>r.id===id);if(!run)throw Error('Execution not found.');if(!run.finished&&run.status==='waiting_for_approval'){
  const step=run.spec.steps[run.stepIndex];(run.proposalIds??={})[step.id]??=existingWorkflowProposal(identity,run.id,step.id)?.id||crypto.randomUUID();const proposal=developmentProposal(identity,run.proposalIds[step.id]);
  if(proposal?.state==='completed'){const operation=operationFor(run);let output:string;if(operation.type==='read_selected_notes'||operation.type==='read_calendar_range')output=JSON.stringify(await validateWorkflowResult(operation,proposal.receipt?.result));else output=run.values[step.source]||'';check();run.values[step.id]=output;run.output=output;event(run,'phone_step_completed',step.id);run.stepIndex++;try{execute(run);}catch(error){run.status='failed';run.finished=true;run.error={message:(error as Error).message};run.stoppedAt=new Date().toISOString();event(run,'execution_failed');}}
  else if(proposal&&(['rejected','failed','not_applied'].includes(proposal.state)||proposal.state==='pending'&&Date.parse(proposal.expiresAt)<=Date.now())){run.status='failed';run.finished=true;run.error={message:'The phone step was denied, failed or expired.'};run.stoppedAt=new Date().toISOString();event(run,'phone_step_failed',step.id);}
 }return run;},signal);
 const phoneReview=/^\/api\/workflow\/executions\/([a-f0-9-]+)\/phone-review$/.exec(path);if(phoneReview&&body===undefined){const run=await advance(phoneReview[1]),credential=developmentCredential(identity.profile,identity),spec=run.spec.device?run.spec:{device:{installationId:credential.installationId,enrollmentId:credential.enrollmentId},...run.spec},specDigest=await workflowSha(spec);check();if(!run.finished&&run.status==='waiting_for_approval'){const step=run.spec.steps[run.stepIndex];if(!run.proposalIds?.[step.id])throw Error('Execution needs a phone proposal identity.');await authorWorkflowProposal(identity,run.proposalIds[step.id],operationFor(run),{workflowId:run.workflowId,versionId:run.workflowVersionId,runId:run.id,stepId:step.id,specDigest},signal);}return {runId:run.id,workflowId:run.workflowId,versionId:run.workflowVersionId,specDigest,spec,status:run.status,finished:run.finished,cancellationRequestedAt:run.status==='cancelled'?run.stoppedAt:null};}
 const history=/^\/api\/workflow\/workflows\/([a-f0-9-]+)\/executions$/.exec(path);if(history&&body===undefined)return {executions:(read().runs||[]).filter(r=>r.workflowId===history[1])};
 const submission=/^\/api\/workflow\/workflows\/([a-f0-9-]+)\/submissions\/([a-f0-9-]+)$/.exec(path);if(submission&&body===undefined)return {submissionId:submission[2],execution:(read().runs||[]).find(r=>r.workflowId===submission[1]&&r.submissionId===submission[2])||null};
 const execution=/^\/api\/workflow\/executions\/([a-f0-9-]+)(\/cancel)?$/.exec(path);if(execution){
  if(!execution[2]&&body===undefined){const run=await advance(execution[1]);return {execution:run};}
  if(execution[2]&&body!==undefined)return editStore(key,initial,data=>{check();const run=data.runs?.find(r=>r.id===execution[1]);if(!run)throw Error('Execution not found.');if(!run.finished){run.status='cancelled';run.finished=true;run.stoppedAt=new Date().toISOString();event(run,'execution_cancelled');}return {execution:run};},signal);
 }
 const control=/^\/api\/workflow\/workflows\/([a-f0-9-]+)\/(run|activate|deactivate)$/.exec(path);if(control&&body!==undefined)return editStore(key,initial,data=>{check();const workflow=data.workflows.find(w=>w.id===control[1]);if(!workflow||workflow.removed)throw Error('Workflow not found.');if(control[2]!=='run'){workflow.active=control[2]==='activate';return publicWorkflow(workflow);}
  if(typeof body.submissionId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(body.submissionId))throw Error('Invalid submission identity.');const prior=(data.runs||[]).find(r=>r.submissionId===body.submissionId);if(prior){if(prior.workflowId!==workflow.id||prior.workflowVersionId!==body.expectedVersionId)throw Error('Submission identity changed.');return {submissionId:body.submissionId,execution:prior};}
  if(workflow.versionId!==body.expectedVersionId)throw Object.assign(Error('Workflow version changed.'),{status:409,data:{code:'WORKFLOW_VERSION_NOT_ADMITTED',workflowId:workflow.id,submissionId:body.submissionId,expectedVersionId:body.expectedVersionId}});
  if((data.runs||[]).length>=100)throw Error('Development execution history is full.');const run:Run={id:crypto.randomUUID(),workflowId:workflow.id,workflowVersionId:workflow.versionId,submissionId:body.submissionId,status:'running',finished:false,startedAt:new Date().toISOString(),spec:structuredClone(workflow.phoneSpec),stepIndex:0,values:{},events:[]};event(run,'execution_started');try{execute(run);}catch(error){run.status='failed';run.finished=true;run.stoppedAt=new Date().toISOString();run.error={message:(error as Error).message};event(run,'execution_failed');}(data.runs??=[]).push(run);return {submissionId:body.submissionId,execution:run};
 },signal);
 const retained=/^\/api\/workflow\/workflows\/([a-f0-9-]+)\/(metadata|lifecycle)-mutations\/([a-f0-9-]+)$/.exec(path);if(retained&&body===undefined){const prior=(read().mutations||[]).find(m=>m.id===retained[3]&&m.receipt.workflowId===retained[1]&&JSON.parse(m.input)[1]===retained[2]);return {mutationId:retained[3],receipt:prior?.receipt||null};}
 const mutationControl=/^\/api\/workflow\/workflows\/([a-f0-9-]+)\/(metadata|lifecycle)$/.exec(path);if(mutationControl&&body!==undefined){
  if(typeof body.mutationId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(body.mutationId))throw Error('Invalid mutation identity.');const input=JSON.stringify([mutationControl[1],mutationControl[2],body]);
  return editStore(key,initial,data=>{check();const prior=(data.mutations||[]).find(m=>m.id===body.mutationId);if(prior){if(prior.input!==input)throw Error('Mutation content changed.');return {mutationId:body.mutationId,receipt:prior.receipt};}const refuse=()=>Object.assign(Error('Workflow change was not applied.'),{status:409,data:{code:mutationControl[2]==='metadata'?'WORKFLOW_METADATA_NOT_APPLIED':'WORKFLOW_LIFECYCLE_NOT_APPLIED',workflowId:mutationControl[1],mutationId:body.mutationId,expectedVersionId:body.expectedVersionId}});const row=data.workflows.find(w=>w.id===mutationControl[1]);if(!row||row.versionId!==body.expectedVersionId||(data.mutations||[]).length>=500)throw refuse();const previousVersionId=row.versionId;let fields:Record<string,unknown>;
   if(mutationControl[2]==='metadata'){if(row.removed||typeof body.name!=='string'||!body.name.trim()||body.name.length>200||typeof body.description!=='string'||body.description.length>4000)throw Error('Invalid metadata.');row.name=body.name.trim();row.description=body.description;row.phoneSpec={...row.phoneSpec,name:row.name,description:row.description};fields={name:row.name,description:row.description,active:row.active};}
   else{if(!['remove','restore'].includes(body.operation)||!!row.removed!==(body.operation==='restore')||(data.runs||[]).some(r=>r.workflowId===row.id&&!r.finished))throw refuse();row.removed=body.operation==='remove';row.active=false;row.triggerCleanup='complete';fields={operation:body.operation};}
   row.versionId=crypto.randomUUID();const receipt={mutationId:body.mutationId,workflowId:row.id,previousVersionId,versionId:row.versionId,appliedAt:new Date().toISOString(),...fields};(data.mutations??=[]).push({id:body.mutationId,input,receipt});return {mutationId:body.mutationId,receipt};
  },signal);
 }
 const detail=/^\/api\/workflow\/workflows\/([a-f0-9-]+)$/.exec(path);if(detail&&body===undefined){const row=read().workflows.find(w=>w.id===detail[1]);if(!row)throw Error('Workflow not found.');return publicWorkflow(row);}
 const mutation=/^\/api\/workflow\/phone\/mutations\/([a-f0-9-]+)$/.exec(path);if(mutation&&body===undefined)return {mutationId:mutation[1],receipt:read().receipts.find(r=>r.receipt.mutationId===mutation[1])?.receipt||null};
 const edit=/^\/api\/workflow\/workflows\/([a-f0-9-]+)\/phone-spec$/.exec(path);
 if(path==='/api/workflow/phone/validate'||path==='/api/workflow/phone/workflows'||edit){
  if(body?.catalogRevision!==catalog.catalogRevision||body.compilerRevision!==catalog.compilerRevision)throw Error('Workflow catalog changed.');const spec=normalizePhoneSpec(body.spec),specDigest=await workflowSha(spec);check();
  if(path==='/api/workflow/phone/validate')return {spec,specDigest,compilerRevision:catalog.compilerRevision,catalogRevision:catalog.catalogRevision,active:false};
  if(typeof body.mutationId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(body.mutationId))throw Error('Invalid workflow save identity.');
  const input=JSON.stringify([edit?.[1]||null,body.expectedVersionId||null,spec]);
  return editStore(key,initial,data=>{check();const prior=data.receipts.find(r=>r.receipt.mutationId===body.mutationId);if(prior){if(prior.input!==input)throw Error('Workflow mutation changed.');return {receipt:prior.receipt};}if(data.receipts.length>=500||!edit&&data.workflows.length>=100)throw Error('Development workflow history is full.');const existing=edit?data.workflows.find(w=>w.id===edit[1]):undefined;if(edit&&(!existing||existing.removed||existing.versionId!==body.expectedVersionId))throw Error('Workflow version changed.');const id=existing?.id||crypto.randomUUID(),versionId=crypto.randomUUID(),receipt:PhoneSaveReceipt={mutationId:body.mutationId,workflowId:id,operation:existing?'edit':'create',previousVersionId:existing?.versionId||null,versionId,specDigest,compilerRevision:catalog.compilerRevision,appliedAt:new Date().toISOString()};const row:Workflow={id,name:spec.name,description:spec.description,active:false,versionId,phoneSpec:spec,steps:spec.steps.map(s=>({label:s.kind+': '+s.operation}))};data.workflows=data.workflows.filter(w=>w.id!==id);data.workflows.push(row);data.receipts.push({input,receipt});return {receipt};},signal);
 }
 throw Error('This development workflow request is not configured.');
}
