import {useEffect,useRef,useState} from 'react';
import {editStore,readStore} from './store';
import type {HostedDigestProtocol} from '../runtime/hosted-digests';
type Pending={mutationId:string;kinds:string[];phase:'start'|'review'|'complete';state?:string;expiresAt?:string};
export function BrowserDigestDelegation({client,scope,signal,current,onConnected}:{client:HostedDigestProtocol;scope:string;signal:AbortSignal;current:()=>boolean;onConnected:()=>void}){
 const key='alpha.browser.cloud-delegation:'+scope,[pending,setPending]=useState<Pending|null>(null),[email,setEmail]=useState(true),[calendar,setCalendar]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('Choose which browser app data this agent may read.'),[grantId,setGrantId]=useState(''),[expanded,setExpanded]=useState(false);const locked=useRef(false),alive=useRef(true);const valid=()=>alive.current&&!signal.aborted&&current();
 const save=async(expected:Pending|null,next:Pending|null)=>{await editStore(key,()=>({pending:null as Pending|null}),data=>{if(!valid())throw Error('Connection changed.');if(JSON.stringify(data.pending)!==JSON.stringify(expected))throw Error('Authorization changed in another tab.');data.pending=next;},signal);if(valid()){setPending(next);if(next)setExpanded(true);}};
 const run=async(work:()=>Promise<void>)=>{if(locked.current||!valid())return;locked.current=true;setBusy(true);try{await work();}catch{if(valid())setMessage('The request is saved. Retry it to recover the exact authorization.');}finally{locked.current=false;if(valid())setBusy(false);}};
 const finish=async(record:Pending)=>{let response=await client.delegation('status',{state:record.state},signal);if(!valid())return;if(response.status==='waiting'&&record.phase==='complete')response=await client.delegation('complete',{state:record.state,confirmed:true},signal);if(!valid())return;if(response.status==='complete'){await save(record,null);if(valid()){setGrantId(String(response.grantId));setMessage('Cloud read access is connected. Choose its account and source below.');onConnected();}}else if(response.status==='failed'){await save(record,null);if(valid())setMessage('Authorization expired or was cancelled. Start a new review.');}else setMessage('Review the requested read access to continue.');};
 const resume=async(record:Pending)=>{if(record.phase!=='start'){await finish(record);return;}const result=await client.delegation('start',{mutationId:record.mutationId,kinds:record.kinds,confirmed:true},signal);if(!valid())return;const next:Pending={...record,phase:'review',state:String(result.state),expiresAt:String(result.expiresAt)};await save(record,next);};
 useEffect(()=>{alive.current=true;const saved=readStore(key,()=>({pending:null as Pending|null})).pending;setPending(saved);if(saved)setExpanded(true);if(saved&&saved.phase!=='review')void run(()=>resume(saved));const refresh=(event:StorageEvent)=>{if(event.key===key&&valid()&&!locked.current)setPending(readStore(key,()=>({pending:null as Pending|null})).pending);};window.addEventListener('storage',refresh);return()=>{alive.current=false;window.removeEventListener('storage',refresh);};},[key,client]);
 return <details open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Connect Cloud for scheduled reads</summary><p>{message}</p>{!pending?<><label><input type="checkbox" checked={email} disabled={busy} onChange={e=>setEmail(e.target.checked)}/>Inbox subjects and snippets</label><label><input type="checkbox" checked={calendar} disabled={busy} onChange={e=>setCalendar(e.target.checked)}/>Calendar events</label><button disabled={busy||!email&&!calendar} onClick={()=>void run(async()=>{const record:Pending={mutationId:crypto.randomUUID(),phase:'start',kinds:[...(email?['email']:[]),...(calendar?['calendar']:[])]};await save(null,record);await resume(record);})}>Review Cloud read access</button></>:<><p>Allow this agent to read {pending.kinds.join(' and ')} from Browser Inbox and Calendar for seven days.</p><p>No sending or calendar changes are included.</p>{pending.phase==='review'&&<button disabled={busy} onClick={()=>void run(async()=>{const next:Pending={...pending,phase:'complete'};await save(pending,next);await finish(next);})}>Approve browser read access</button>}<button disabled={busy} onClick={()=>void run(()=>resume(pending))}>Check authorization status</button><button disabled={busy||pending.phase==='complete'} onClick={()=>void run(async()=>{if(pending.state){const result=await client.delegation('cancel',{state:pending.state,confirmed:true},signal);if(result.status==='complete'){await finish(pending);return;}}else{const result=await client.delegation('start',{mutationId:pending.mutationId,kinds:pending.kinds,confirmed:true},signal);await client.delegation('cancel',{state:result.state,confirmed:true},signal);}await save(pending,null);if(valid())setMessage('Authorization cancelled.');})}>Cancel authorization</button></>}{grantId&&<button disabled={busy} onClick={()=>void run(async()=>{await client.delegation('revoke',{grantId,confirmed:true},signal);if(valid()){setGrantId('');setMessage('Cloud read access revoked.');onConnected();}})}>Revoke this Cloud read grant</button>}</details>;
}
