import {reviewMailAttachment,type MailAttachment} from '../runtime/inbox-attachment';
import {browserDevProfile} from './dev-profile';
type Api=Record<string,any>;
/** Incoming data stays in the same durable local stores used by the development apps. */
export function openIncomingSimulation(kind:'message'|'email',api:Api){
 if(!browserDevProfile)return;
 const dialog=document.createElement('dialog');dialog.setAttribute('aria-label',kind==='message'?'Incoming message':'Incoming email');dialog.style.cssText='box-sizing:border-box;width:min(380px,92vw);max-height:85dvh;overflow:auto;border:0;border-radius:20px;padding:20px;background:var(--bg,#fff);color:var(--fg,#111);font:16px/1.4 system-ui';
 const shell=document.querySelector('.os');if(shell){const theme=getComputedStyle(shell);for(const name of ['--bg','--fg','--s2'])dialog.style.setProperty(name,theme.getPropertyValue(name));}
 const heading=document.createElement('h2');heading.textContent=dialog.getAttribute('aria-label');dialog.append(heading);
 const field=(name:string,control:HTMLElement)=>{control.setAttribute('aria-label',name);control.style.cssText='box-sizing:border-box;width:100%;padding:8px;font:inherit;background:var(--bg,#fff);color:inherit';const label=document.createElement('label');label.textContent=name;label.style.cssText='display:grid;gap:4px;margin:10px 0';label.append(control);dialog.append(label);};
 const sender=document.createElement('select');for(const person of api.get('contacts').list||api.people||[])sender.add(new Option(person.name,person.id));sender.value='maya';if(!sender.value)sender.selectedIndex=0;field('From',sender);
 const subject=document.createElement('input');subject.maxLength=500;if(kind==='email')field('Subject',subject);
 const body=document.createElement('textarea');body.rows=5;body.maxLength=12000;field(kind==='message'?'Message':'Email body',body);
 let attachments:Api[]=[],selection=0,busy=false,retired=false;
 const files=document.createElement('input');files.type='file';files.multiple=true;files.accept='.pdf,.png,.jpg,.jpeg,.webp,.txt';
 const attachmentList=document.createElement('div');attachmentList.setAttribute('aria-label','Selected attachments');
 const renderAttachments=()=>{attachmentList.replaceChildren();attachments.forEach((file,index)=>{const row=document.createElement('div'),label=document.createElement('span'),remove=document.createElement('button');label.textContent=file.name+' · '+file.size;row.style.cssText='display:flex;align-items:center;gap:12px;margin:8px 0';label.style.cssText='min-width:0;flex:1;overflow-wrap:anywhere';remove.style.cssText='flex:none;min-height:44px;padding:8px 12px;border:1px solid #aaa;border-radius:8px;font:inherit;color:inherit;background:var(--s2,#eee)';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+file.name);remove.onclick=()=>{selection++;busy=false;deliver.disabled=false;files.value='';attachments=attachments.filter((_,i)=>i!==index);renderAttachments();status.textContent=attachments.length?attachments.length+' attachment'+(attachments.length===1?'':'s')+' ready':'No attachments selected';};row.append(label,remove);attachmentList.append(row);});};
 if(kind==='email'){field('Attachments',files);dialog.append(attachmentList);}
 files.onchange=async()=>{const chosen=Array.from(files.files||[]);if(!chosen.length)return;const ticket=++selection;busy=true;deliver.disabled=true;status.textContent='Reading attachments';try{
  if(chosen.length>5||chosen.reduce((size,file)=>size+file.size,0)>5*1024*1024)throw Error('Choose up to 5 attachments totaling at most 5 MiB.');
  const next:Api[]=[];for(const file of chosen){const bytes=new Uint8Array(await file.arrayBuffer());if(retired||ticket!==selection)return;let raw='';for(let offset=0;offset<bytes.length;offset+=32768)raw+=String.fromCharCode(...bytes.subarray(offset,offset+32768));const extension=file.name.split('.').pop()?.toLowerCase(),mimeType=file.type||({txt:'text/plain',pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'} as Record<string,string>)[extension||'']||'';const attachment:MailAttachment={name:file.name,mimeType,dataBase64:btoa(raw)},checked=await reviewMailAttachment(attachment);if(retired||ticket!==selection)return;next.push({...attachment,sha256:checked.sha256,size:checked.size+' bytes',browserAttachment:true});}
  attachments=next;renderAttachments();status.textContent=next.length+' attachment'+(next.length===1?'':'s')+' ready';
 }catch(error){if(!retired&&ticket===selection)status.textContent=error instanceof Error?error.message:'Attachments could not be read.';}finally{if(!retired&&ticket===selection){busy=false;deliver.disabled=false;files.value='';}}};
 const status=document.createElement('p');status.setAttribute('role','status');const deliver=document.createElement('button');deliver.textContent='Deliver';deliver.onclick=()=>{if(busy||retired)return;try{
  const person=(api.get('contacts').list||api.people||[]).find((p:Api)=>p.id===sender.value);if(!person)throw Error('Choose a sender.');if(!body.value.trim())throw Error('Enter a message.');if(kind==='email'&&!subject.value.trim())throw Error('Enter a subject.');
  const id=crypto.randomUUID(),now=new Date();
  if(kind==='message'){const state=api.get('messages'),threads=state.threads||{},k=Math.max(now.getHours()*60+now.getMinutes()-1,...Object.values(threads).flat().map((row:any)=>Number(row.k)||0))+1;api.setView('messages',{threads:{...threads,[person.id]:[...(threads[person.id]||[]),{id,k,me:false,text:body.value,receivedAt:now.getTime()}]},unread:{...state.unread,[person.id]:(state.unread?.[person.id]||0)+1}});}
  else{const state=api.get('inbox');api.setView('inbox',{mails:[...(state.mails||[]),{id,pid:person.id,acct:'work',k:now.getTime(),time:now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),unread:true,subj:subject.value,body:body.value,atts:structuredClone(attachments),receivedAt:now.getTime()}]});}dialog.close();
 }catch(error){status.textContent=error instanceof Error?error.message:'Incoming data could not be saved.';}};
 const cancel=document.createElement('button');cancel.textContent='Cancel';cancel.onclick=()=>dialog.close();for(const button of [deliver,cancel])button.style.cssText='min-height:44px;margin:4px;padding:8px 12px;font:inherit';dialog.append(status,deliver,cancel);
 const retire=()=>{retired=true;selection++;dialog.close();},hidden=()=>{if(document.hidden)retire();},events=['pagehide','alpha:device-state','launcher-home','alpha:dev-incoming-call'];const back=(event:Event)=>{event.preventDefault();event.stopImmediatePropagation();retire();};events.forEach(event=>window.addEventListener(event,retire));document.addEventListener('visibilitychange',hidden);window.addEventListener('alpha-back',back,true);dialog.onclose=()=>{retired=true;selection++;attachments=[];events.forEach(event=>window.removeEventListener(event,retire));document.removeEventListener('visibilitychange',hidden);window.removeEventListener('alpha-back',back,true);dialog.remove();};document.body.append(dialog);dialog.showModal();
}
