import {DailyApps} from '../daily';
import {registerPlugin} from '../platform-plugins';
import {reviewMailAttachment} from '../runtime/inbox-attachment';
type Bag=Record<string,any>;
const attachments=registerPlugin<any>('AlphaMailAttachments');
const address=(value:unknown):value is string=>typeof value==='string'&&value.length<=254&&/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(value);
/** Local development messages never enter a provider transport. */
export function installSimulatedInbox(view:Bag){
 const render=view.render,leave=view.onLeave;let busy=false,epoch=0,status='',confirm=false;
 view.onLeave=(...args:any[])=>{epoch++;busy=false;confirm=false;return leave?.(...args);};
 view.render=(state:Bag,api:Bag)=>{const out=render(state,api),repaint=()=>api.set({localMailRevision:Date.now()}),setDraft=(patch:Bag)=>{status='Unsaved local draft';api.set({compose:{...api.get('inbox').compose,...patch}});};
 if(!state.compose&&state.localDrafts?.length)out.chips.push({label:'Restore local draft',css:'background:var(--s2)',pick:()=>{api.set({compose:structuredClone(state.localDrafts[0]),composeLocal:true,toQ:''});status='Restored local draft';}});
 const compose=out.compose;out.compose=()=>{status='Unsaved local draft';confirm=false;compose();};
 const contacts=api.get('contacts')?.list,people=contacts?.length?contacts:api.people||[],validRecipient=(value:unknown)=>address(value)||people.some((person:Bag)=>person.id===value&&address(person.email));
 if(out.c){const base=out.c;out.c={...base,local:true,busy,status,confirm,cc:state.compose.cc||'',bcc:state.compose.bcc||'',onCc:(e:Bag)=>setDraft({cc:e.target.value}),onBcc:(e:Bag)=>setDraft({bcc:e.target.value}),
 save:()=>{try{const draft=structuredClone(api.get('inbox').compose),raw=String(api.get('inbox').toQ||'').trim();if(raw){if(!/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(raw)){api.toast('Add a valid recipient.');return;}draft.to=[...(Array.isArray(draft.to)?draft.to:draft.to?[draft.to]:[]),raw];}if((Array.isArray(draft.to)?draft.to:draft.to?[draft.to]:[]).some((value:unknown)=>!validRecipient(value))){api.toast('Add valid recipients.');return;}api.set({localDrafts:[draft],compose:draft,toQ:''});status='Saved locally';repaint();}catch{}},
 discard:()=>{confirm=true;repaint();},cancelDiscard:()=>{confirm=false;repaint();},confirmDiscard:()=>{try{api.set({localDrafts:[],compose:null,toQ:''});confirm=false;status='';}catch{}},
 attach:async()=>{if(busy)return;busy=true;const ticket=epoch,draft=api.get('inbox').compose;repaint();let selectionId:string|undefined;try{const selection=await DailyApps.perform({action:'files'});selectionId=selection.selectionId;if(ticket!==epoch||api.get('inbox').compose!==draft||selection.status==='cancelled')return;if(!selectionId)throw Error('Choose a file.');const file=await attachments.readSelected({selectionId});await reviewMailAttachment(file);if(ticket!==epoch||api.get('inbox').compose!==draft)return;setDraft({atts:[{name:file.name,mimeType:file.mimeType,dataBase64:file.dataBase64,sha256:file.sha256,size:file.size+' bytes',browserAttachment:true}],attach:[]});status='Attachment ready';}catch(error){if(ticket===epoch)api.toast(error instanceof Error?error.message:'Could not attach file.');}finally{if(selectionId)await DailyApps.forgetSelected({selectionId}).catch(()=>{});if(ticket===epoch){busy=false;repaint();}}},
 send:()=>{if(busy)return;const draft=api.get('inbox').compose,to=Array.isArray(draft.to)?[...draft.to]:draft.to?[draft.to]:[],raw=String(api.get('inbox').toQ||'').trim();if(raw)to.push(raw);const cc=String(draft.cc||'').split(',').map(v=>v.trim()).filter(Boolean),bcc=String(draft.bcc||'').split(',').map(v=>v.trim()).filter(Boolean);if(!to.length||to.some((value:unknown)=>!validRecipient(value))||raw&&!/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(raw)||[...cc,...bcc].some(v=>!/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(v))){api.toast('Add valid recipients.');return;}const current=api.get('inbox'),message={id:crypto.randomUUID(),sent:true,to,cc,bcc,acct:draft.acct||'personal',subj:draft.subject||'(no subject)',body:draft.body||'',time:'Now',k:Date.now(),atts:draft.atts||[]};try{api.set({sent:[message,...current.sent],localDrafts:[],compose:null,toQ:'',mails:current.mails.map((m:Bag)=>m.id===draft.replyTo?{...m,unread:false,replied:true}:m)});status='';api.toast('Sent locally');}catch{}}
 };for(const key of ['onTo','toKey','onSubj','onBody','addRaw'])out.c[key]=(...args:any[])=>{status='Unsaved local draft';return base[key]?.(...args);};out.c.atts=base.atts.map((item:Bag)=>({...item,rm:()=>{status='Unsaved local draft';item.rm();}}));}
 if(out.d?.atts){const source=[...(state.mails||[]),...(state.sent||[])].find((m:Bag)=>String(m.id)===String(state.open));out.d.atts=out.d.atts.map((item:Bag,index:number)=>{const file=source?.atts?.[index];return file?.browserAttachment?{...item,open:()=>void attachments.openReviewed({...file,size:undefined,reviewed:true}).catch((error:Error)=>api.toast(error.message))}:item;});}
 return out;};
}
