import type { PersonalView } from './cloud-personal-protocol';

export interface PersonalSetupState { view: PersonalView | null; blocked: boolean; declined: boolean }
export {personalIntent,savePersonalIntent,clearPersonalIntent} from './cloud-personal-intent';
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:4}).format(value);
export function CloudPersonalSetup({setup,busy,onAccept,onDecline,onPoll,onFinalize,onConnect}:{setup:PersonalSetupState;busy:boolean;onAccept:()=>void;onDecline:()=>void;onPoll:()=>void;onFinalize:()=>void;onConnect:()=>void}) {
 const view=setup.view;
 if(setup.declined)return <p role="status">Cloud account connected. Dedicated setup was not started.</p>;
 if(!view)return setup.blocked?<p role="status">Setup could not be confirmed. Check status before taking another action.</p>:null;
 if(view.kind==='ready')return <section className="alpha-connection-agent"><strong>{view.identity.agentName}</strong><span>Dedicated ready</span><button disabled={busy||setup.blocked} onClick={onConnect}>Connect this agent</button></section>;
 if(view.kind==='pending')return <section className="alpha-connection-agent"><strong>Dedicated setup accepted</strong><p>{setup.blocked?'The last setup response could not be confirmed. Check status; the request will not be repeated.':view.phase==='provisioning'?'Your agent is starting. Check its status to continue.':'Your agent is ready to finish moving your personal history and reminders.'}</p><button disabled={busy} onClick={onPoll}>Check setup status</button>{view.phase==='cutover'&&!setup.blocked&&<button disabled={busy} onClick={onFinalize}>Continue setup</button>}</section>;
 const review=view.review,adoption=review.action==='adopt_existing_dedicated';
 return <section className="alpha-connection-agent" aria-label="Dedicated hosting review"><strong>{adoption?'Use your existing Dedicated Eliza':'Start your Dedicated Eliza'}</strong><p>{adoption?'This reuses the existing Dedicated instance selected for this account.':'This starts Dedicated hosting for your personal Eliza.'}</p>{adoption&&<p>{review.startsCompute?'This starts hosting for the existing instance.':'Hosting is already active. This does not start another server.'}</p>}<p>{money(review.dailyRateUsd)}/day · {money(review.hourlyRateUsd)}/hour</p><p>Balance: {money(review.balanceUsd)} · Minimum to start: {money(review.minimumBalanceUsd)}</p><p>Minimum charge per successful start: {money(review.minimumActivationChargeUsd)}. Applies again after stopping and restarting.</p>{adoption&&<p>{review.requiresCatalogRestore?'The reviewed setup requires restoring the existing instance.':review.stateDisposition==='fresh_boot_no_verified_backup'?'No verified backup is available; this starts with fresh state.':'The existing instance will be reused.'}</p>}{setup.blocked&&<p role="status">A previous setup request is unconfirmed. Refresh status; it will not be repeated.</p>}{view.kind==='unavailable'&&<p role="status">Dedicated setup is unavailable under this quote. Check your account and refresh status.</p>}<button disabled={busy||setup.blocked||view.kind==='unavailable'} onClick={onAccept}>{adoption?'Use existing Dedicated':'Start Dedicated'}</button><button disabled={busy||setup.blocked} onClick={onDecline}>Not now</button></section>;
}
