import {HostedDigestProtocol} from './hosted-digests';
import { normalizePhoneSpec, assertPhoneCapabilities, parsePhoneCatalog, verifyPhoneValidation, parsePhoneReceipt, type PhoneSpec, type PhoneCatalog } from './phone-workflow-authoring';
import { parseWorkflowPhoneReview, workflowBytes, type WorkflowDeviceTarget } from './workflow-device-contract';
/** Source: plugin-workflow routes/workflow-routes.ts. Remote OWNER session only. */
export interface RemoteWorkflow { id: string; name: string; description: string; active: boolean; removed?:boolean; triggerCleanup?:'pending'|'complete'; versionId: string; steps: Array<{label:string;description?:string}>;phoneSpec?:unknown;hostedDigest?:boolean }
/** Upstream host-process reconciliation (plugin-workflow WorkflowExecution.reconciliation). It never replaces the canonical receipt. */
export type WorkflowRunReconciliation={state:'worker-running'|'outcome-unknown';message:string};
export interface WorkflowRun { id:string; workflowId:string; status:string; startedAt:string; finished:boolean; versionId:string; stoppedAt?:string; error?:string; output?:string; reconciliation?:WorkflowRunReconciliation; events:Array<{type:string;at:string;node?:string}> }
/** An interrupted run whose effects cannot be known. The agent does not replay it; neither does this phone. */
export const runOutcomeUnknown=(run:WorkflowRun)=>!run.finished&&run.reconciliation?.state==='outcome-unknown';
/** A worker that outlived its host is still being reconciled by the agent. */
export const runWorkerRunning=(run:WorkflowRun)=>!run.finished&&run.reconciliation?.state==='worker-running';
/** Typed phone operations that only read selected sources or draft text. Writes, notifications and speech are excluded. */
export const READ_ONLY_PHONE_OPERATIONS:ReadonlySet<string>=new Set(['supplied_text','selected_notes','calendar_range','contains','compose_draft','model_draft']);
/** True only for a typed phone workflow whose every step reads or drafts text (a read-only digest). Hosted digests are excluded: the agent admits them only at their scheduled occurrence. */
export function readOnlyDigestWorkflow(workflow:RemoteWorkflow|null|undefined):boolean{
 if(!workflow||workflow.hostedDigest||workflow.removed)return false;
 const spec=workflow.phoneSpec as {trigger?:{kind?:unknown};steps?:unknown}|undefined;
 if(!spec||typeof spec!=='object'||!Array.isArray(spec.steps)||!spec.steps.length||spec.trigger?.kind!=='manual')return false;
 return spec.steps.every(step=>!!step&&typeof step==='object'&&READ_ONLY_PHONE_OPERATIONS.has(String((step as {operation?:unknown}).operation)));
}
function reconciliation(value:unknown):WorkflowRunReconciliation|undefined{
 if(value===undefined||value===null)return undefined;
 if(typeof value!=='object'||Array.isArray(value))throw new Error('Invalid execution reconciliation');
 const r=value as Record<string,unknown>;
 if((r.state!=='worker-running'&&r.state!=='outcome-unknown')||typeof r.message!=='string')throw new Error('Invalid execution reconciliation');
 return {state:r.state,message:r.message.slice(0,2000)};
}
export interface WorkflowApproval {runId:string;workflowId:string;workflowVersionId:string;nodeId:string;iteration:number;requestDigest:string;status:'pending'|'approved'|'denied';title:string;summary:string;operation:string;target:string;account:string;supported:boolean;decidedBy?:string}
export interface WorkflowApprovalReceipt {runId:string;workflowId:string;workflowVersionId:string;finished:boolean;cancellationRequested:boolean;approvals:WorkflowApproval[]}
const obj=(value:unknown):Record<string,any>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid workflow response');return value as Record<string,any>;};
const str=(value:unknown):string=>{if(typeof value!=='string'||!value)throw new Error('Invalid workflow field');return value;};
/** Only bounded public refusal identity crosses the native error boundary. */
export class WorkflowHttpError extends Error {
 readonly clarification?:string;readonly code?:string;readonly workflowId?:string;readonly submissionId?:string;readonly mutationId?:string;readonly expectedVersionId?:string;
 constructor(readonly status:number,body:unknown){super('Workflow request unavailable. Check execution history before repeating a run.');if(body&&typeof body==='object'&&!Array.isArray(body)){const data=body as Record<string,unknown>;if(status===422&&typeof data.error==='string'&&data.error.startsWith('Workflow needs clarification: ')&&data.error.length<=1100&&!data.error.includes('\0'))this.clarification=data.error;for(const key of ['code','workflowId','submissionId','mutationId','expectedVersionId'] as const){const value=data[key];if(typeof value==='string'&&value.length>0&&value.length<=200)this[key]=value;}}}
}
export class WorkflowAdmissionRejected extends Error {constructor(){super('Workflow changed before acceptance. Refresh and review the current steps before a new run.');}}
export class WorkflowMetadataRejected extends Error {constructor(){super('Workflow changed before saving. Reopen Change and review the current name and description.');}}
export interface WorkflowMetadataReceipt {mutationId:string;workflowId:string;previousVersionId:string;versionId:string;name:string;description:string;active:boolean;appliedAt:string}
export class WorkflowLifecycleRejected extends Error {constructor(){super('Removal or restore was not applied. Refresh the workflow and review its version, cleanup and any ongoing executions.');}}
export interface WorkflowLifecycleReceipt {mutationId:string;workflowId:string;previousVersionId:string;versionId:string;operation:'remove'|'restore';appliedAt:string}
/** Present the typed worker's final text; intermediate step inputs remain in the agent receipt. */
function workflowOutput(value:unknown,runId:string):string {
 if(typeof value==='string')return value.slice(0,4000);
 if(Array.isArray(value)&&value.length===1){const item=value[0];if(item&&typeof item==='object'&&item.nodeId==='typed-steps'&&item.runId===runId&&typeof item.text==='string')return item.text.slice(0,4000);}
 return JSON.stringify(value).slice(0,4000);
}
export class WorkflowProtocol {
 hosted(){return new HostedDigestProtocol(this.request);}

 async supportsSubmissionReconciliation(signal:AbortSignal){const status=obj(await this.request('/api/workflow/status',undefined,signal));if(status.engine!=='smthrs'||status.status!=='ready')throw new Error('Workflow capability unavailable');return status.manualSubmissionProtocol===1;}
 async phoneReview(run:WorkflowRun,signal:AbortSignal){return parseWorkflowPhoneReview(await this.request(`/api/workflow/executions/${encodeURIComponent(run.id)}/phone-review`,undefined,signal),run);}
 async phoneCatalog(signal:AbortSignal){return parsePhoneCatalog(await this.request('/api/workflow/phone/catalog',undefined,signal));}
 async generatePhone(prompt:string,catalog:PhoneCatalog,operations:string[],signal:AbortSignal,existing?:PhoneSpec,device?:WorkflowDeviceTarget){
  if(catalog.generationProtocol!==1)throw new Error('Typed generation is unavailable on this agent');
  if(!prompt.trim()||prompt.length>4000||prompt.includes('\0'))throw new Error('Describe the workflow in 1–4000 characters');
  if(existing)existing=normalizePhoneSpec(existing);
  let response:unknown;
  try{response=await this.request('/api/workflow/phone/generate',{prompt,operations,...(existing?{existing}:{}),...(device?{device}:{}),catalogRevision:catalog.catalogRevision,compilerRevision:catalog.compilerRevision},signal);}
  catch(error){if(error instanceof WorkflowHttpError)throw new Error(error.status===422?error.clarification??'The request needs clarification. Select any Notes or Calendar scope first, and describe a manual workflow using the available steps.':'The agent could not generate a valid draft. Your current draft is unchanged.');throw error;}
  signal.throwIfAborted();if(workflowBytes(response)>75000)throw new Error('Generated draft exceeds the response limit');
  const spec=normalizePhoneSpec(obj(response).spec);assertPhoneCapabilities(spec,catalog);
  if(JSON.stringify(spec.device)!==JSON.stringify(device??existing?.device)||spec.steps.some(s=>!operations.includes(s.operation)))throw new Error('Generated draft changed the available device or operations');
  for(const step of spec.steps){if(step.operation!=='selected_notes'&&step.operation!=='calendar_range')continue;const scope=(s:typeof step)=>JSON.stringify(s.operation==='selected_notes'?s.notes:s.range);if(!existing?.steps.some(s=>s.operation===step.operation&&scope(s)===scope(step)))throw new Error('Generated draft changed a selected read scope');}
  return (await verifyPhoneValidation(response,spec,catalog)).spec;
 }
 async validatePhone(spec:PhoneSpec,catalog:PhoneCatalog,signal:AbortSignal){return verifyPhoneValidation(await this.request('/api/workflow/phone/validate',{spec,catalogRevision:catalog.catalogRevision,compilerRevision:catalog.compilerRevision},signal),spec,catalog);}
 async savePhone(spec:PhoneSpec,catalog:PhoneCatalog,expected:{mutationId:string;specDigest:string;compilerRevision:string;workflowId?:string;versionId?:string},signal:AbortSignal){const response=obj(await this.request(expected.workflowId?`/api/workflow/workflows/${encodeURIComponent(expected.workflowId)}/phone-spec`:'/api/workflow/phone/workflows',{spec,catalogRevision:catalog.catalogRevision,compilerRevision:catalog.compilerRevision,mutationId:expected.mutationId,...(expected.workflowId?{expectedVersionId:expected.versionId}:{})},signal));return parsePhoneReceipt(response.receipt,expected);}
 async phoneSaveReceipt(expected:{mutationId:string;specDigest:string;compilerRevision:string;workflowId?:string;versionId?:string},signal:AbortSignal){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(expected.mutationId))throw new Error('Invalid save identity');const result=obj(await this.request(`/api/workflow/phone/mutations/${expected.mutationId}`,undefined,signal));if(result.mutationId!==expected.mutationId)throw new Error('Save identity changed');return result.receipt===null?null:parsePhoneReceipt(result.receipt,expected);}
 constructor(private request:(path:string,body:unknown|undefined,signal:AbortSignal)=>Promise<unknown>){}
 private workflow(value:unknown):RemoteWorkflow {const p=obj(value);if(typeof p.active!=='boolean'||(p.removed!==undefined&&typeof p.removed!=='boolean')||(p.removed===true&&!['pending','complete'].includes(p.triggerCleanup))||!Array.isArray(p.steps??[]))throw new Error('Invalid workflow');return {id:str(p.id),name:str(p.name),description:typeof p.description==='string'?p.description:'',active:p.active,removed:p.removed===true,triggerCleanup:p.triggerCleanup==='pending'?'pending':'complete',versionId:str(p.versionId),...(typeof p.metadata?.elizaPhoneWorkflowSpec==='string'&&p.metadata.elizaPhoneWorkflowSpec.length<=65536?{phoneSpec:JSON.parse(p.metadata.elizaPhoneWorkflowSpec)}:{}),...(typeof p.metadata?.elizaHostedDigestV1==='string'?{hostedDigest:true}:{}),steps:(p.steps??[]).map((x:unknown)=>({label:str(obj(x).label),...(typeof obj(x).description==='string'?{description:obj(x).description}:{})}))};}
 private runResult(value:unknown):WorkflowRun {
  const p=obj(value);if(typeof p.finished!=='boolean')throw new Error('Invalid execution');
  const id=str(p.id),workflowId=str(p.workflowId);
  const events=(p.events??[]);if(!Array.isArray(events))throw new Error('Invalid execution events');
  return {id,workflowId,status:str(p.status),startedAt:str(p.startedAt),finished:p.finished,versionId:str(p.workflowVersionId),
   ...(typeof p.stoppedAt==='string'?{stoppedAt:p.stoppedAt}:{}),
   ...(typeof p.error?.message==='string'?{error:p.error.message.slice(0,2000)}:{}),
   ...(p.output===undefined?{}:{output:workflowOutput(p.output,id)}),
   ...(()=>{const r=reconciliation(p.reconciliation);return r?{reconciliation:r}:{};})(),
   events:events.slice(-100).map((event:unknown)=>{const e=obj(event);if(e.runId!==id||e.workflowId!==workflowId)throw new Error('Execution event identity mismatch');return {type:str(e.type).slice(0,120),at:str(e.timestamp),...(typeof e.nodeId==='string'?{node:e.nodeId.slice(0,200)}:{})};})};
 }

 async approvals(run:WorkflowRun,signal:AbortSignal):Promise<WorkflowApprovalReceipt|null>{const capability=obj(await this.request('/api/workflow/status',undefined,signal));if(capability.approvalReceiptProtocol!==1)return null;return this.approvalResult(await this.request(`/api/workflow/executions/${encodeURIComponent(run.id)}/approvals`,undefined,signal),run);}
 private approvalResult(value:unknown,run:WorkflowRun):WorkflowApprovalReceipt{const p=obj(value);if(p.runId!==run.id||p.workflowId!==run.workflowId||p.workflowVersionId!==run.versionId||typeof p.finished!=='boolean'||typeof p.cancellationRequested!=='boolean'||!Array.isArray(p.approvals)||p.approvals.length>100)throw new Error('Approval receipt identity mismatch');const approvals=p.approvals.map((value:unknown)=>{const a=obj(value);if(a.runId!==run.id||a.workflowId!==run.workflowId||a.workflowVersionId!==run.versionId||!Number.isSafeInteger(a.iteration)||a.iteration<0||!['pending','approved','denied'].includes(a.status)||typeof a.supported!=='boolean'||!(/^[a-f0-9]{64}$/).test(a.requestDigest))throw new Error('Approval identity mismatch');for(const [key,max]of Object.entries({nodeId:200,title:500,summary:4000,operation:500,target:1000,account:500})){if(typeof a[key]!=='string'||a[key].length>max)throw new Error('Unsupported approval field');}if(!a.nodeId)throw new Error('Missing approval node');return {...a,supported:a.supported&&['title','summary','operation','target','account'].every(key=>a[key].trim().length>0)} as WorkflowApproval;});return {runId:run.id,workflowId:run.workflowId,workflowVersionId:run.versionId,finished:p.finished,cancellationRequested:p.cancellationRequested,approvals};}
 async decideApproval(run:WorkflowRun,approval:WorkflowApproval,approved:boolean,signal:AbortSignal){if(approval.runId!==run.id||approval.workflowVersionId!==run.versionId||approval.workflowId!==run.workflowId||approval.status!=='pending'||(approved&&!approval.supported))throw new Error('Approval is not reviewable');const result=this.approvalResult(await this.request(`/api/workflow/executions/${encodeURIComponent(run.id)}/approvals/${encodeURIComponent(approval.nodeId)}/${approval.iteration}`,{approved,expectedVersionId:run.versionId,requestDigest:approval.requestDigest},signal),run);const confirmed=result.approvals.find(a=>a.nodeId===approval.nodeId&&a.iteration===approval.iteration&&a.requestDigest===approval.requestDigest);if(confirmed?.status!==(approved?'approved':'denied'))throw new Error('Decision not confirmed');return result;}
 async metadataSupported(signal:AbortSignal){const status=obj(await this.request('/api/workflow/status',undefined,signal));return status.engine==='smthrs'&&status.status==='ready'&&status.metadataMutationProtocol===1;}
 private metadataResult(value:unknown,id:string,version:string,mutationId:string):WorkflowMetadataReceipt{const p=obj(value);if(p.workflowId!==id||p.previousVersionId!==version||p.mutationId!==mutationId||typeof p.name!=='string'||!p.name.trim()||p.name.length>200||typeof p.description!=='string'||p.description.length>4000||typeof p.active!=='boolean')throw new Error('Metadata receipt mismatch');return {workflowId:id,previousVersionId:version,mutationId,versionId:str(p.versionId),name:p.name,description:p.description,active:p.active,appliedAt:str(p.appliedAt)};}
 async changeMetadata(id:string,version:string,name:string,description:string,signal:AbortSignal,beforeSubmit:(mutationId:string)=>void){if(!await this.metadataSupported(signal))throw new Error('Metadata editing unavailable');name=name.trim();if(!name||name.length>200||description.length>4000)throw new Error('Invalid workflow metadata');signal.throwIfAborted();const mutationId=crypto.randomUUID();beforeSubmit(mutationId);let data;try{data=obj(await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/metadata`,{mutationId,expectedVersionId:version,name,description},signal));}catch(error){if(error instanceof WorkflowHttpError&&error.status===409&&error.code==='WORKFLOW_METADATA_NOT_APPLIED'&&error.workflowId===id&&error.mutationId===mutationId&&error.expectedVersionId===version)throw new WorkflowMetadataRejected();throw error;}const receipt=this.metadataResult(data.receipt,id,version,mutationId);if(receipt.name!==name||receipt.description!==description)throw new Error('Metadata values mismatch');return receipt;}
 async reconcileMetadata(id:string,version:string,mutationId:string,signal:AbortSignal){if(!await this.metadataSupported(signal))throw new Error('Metadata reconciliation unavailable');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(mutationId))throw new Error('Invalid metadata mutation');const data=obj(await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/metadata-mutations/${mutationId}`,undefined,signal));if(data.mutationId!==mutationId)throw new Error('Metadata identity mismatch');return data.receipt===null?null:this.metadataResult(data.receipt,id,version,mutationId);}
 async lifecycleSupported(signal:AbortSignal){const p=obj(await this.request('/api/workflow/status',undefined,signal));return p.engine==='smthrs'&&p.status==='ready'&&p.lifecycleMutationProtocol===1;}
 async removedWorkflows(signal:AbortSignal){if(!await this.lifecycleSupported(signal))throw new Error('Removed workflow history unavailable');const p=obj(await this.request('/api/workflow/removed-workflows',undefined,signal));if(!Array.isArray(p.workflows))throw new Error('Invalid removed workflows');return p.workflows.map((v:unknown)=>{const w=this.workflow(v);if(!w.removed)throw new Error('Removed state mismatch');return w;});}
 private lifecycleResult(value:unknown,id:string,version:string,mutationId:string,operation:'remove'|'restore'):WorkflowLifecycleReceipt|null{const p=obj(value);if(p.mutationId!==mutationId)throw new Error('Mutation identity mismatch');if(p.receipt===null)return null;const r=obj(p.receipt);if(r.workflowId!==id||r.previousVersionId!==version||r.mutationId!==mutationId||r.operation!==operation)throw new Error('Lifecycle receipt mismatch');return {workflowId:id,previousVersionId:version,mutationId,operation,versionId:str(r.versionId),appliedAt:str(r.appliedAt)};}
 async lifecycle(id:string,version:string,operation:'remove'|'restore',signal:AbortSignal,beforeSubmit:(mutationId:string)=>void){if(!await this.lifecycleSupported(signal))throw new Error('Reviewed removal unavailable');signal.throwIfAborted();const mutationId=crypto.randomUUID();beforeSubmit(mutationId);let result;try{result=await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/lifecycle`,{mutationId,expectedVersionId:version,operation},signal);}catch(error){if(error instanceof WorkflowHttpError&&error.status===409&&error.code==='WORKFLOW_LIFECYCLE_NOT_APPLIED'&&error.workflowId===id&&error.mutationId===mutationId&&error.expectedVersionId===version)throw new WorkflowLifecycleRejected();throw error;}const r=this.lifecycleResult(result,id,version,mutationId,operation);if(!r)throw new Error('Lifecycle outcome unknown');return r;}
 async reconcileLifecycle(id:string,version:string,mutationId:string,operation:'remove'|'restore',signal:AbortSignal){if(!await this.lifecycleSupported(signal)||!['remove','restore'].includes(operation)||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(mutationId))throw new Error('Invalid lifecycle reconciliation');return this.lifecycleResult(await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/lifecycle-mutations/${mutationId}`,undefined,signal),id,version,mutationId,operation);}
 async list(signal:AbortSignal){const status=obj(await this.request('/api/workflow/status',undefined,signal));if(status.engine!=='smthrs'||status.status!=='ready')throw new Error('Workflow capability unavailable');const data=obj(await this.request('/api/workflow/workflows',undefined,signal));if(!Array.isArray(data.workflows))throw new Error('Invalid workflow list');return data.workflows.map((x:unknown)=>this.workflow(x));}
 async detail(id:string,signal:AbortSignal){const workflow=this.workflow(await this.request(`/api/workflow/workflows/${encodeURIComponent(str(id))}`,undefined,signal));if(workflow.id!==id)throw new Error('Workflow identity changed');return workflow;}
 async pause(id:string,signal:AbortSignal){const workflow=this.workflow(await this.request(`/api/workflow/workflows/${encodeURIComponent(str(id))}/deactivate`,{},signal));if(workflow.id!==id||workflow.active)throw new Error('Pause was not confirmed');return workflow;}
 async activate(id:string,version:string,signal:AbortSignal){const current=await this.detail(id,signal);if(current.versionId!==version)throw new Error('Workflow changed. Review it again before enabling.');const workflow=this.workflow(await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/activate`,{},signal));if(workflow.id!==id||!workflow.active)throw new Error('Activation was not confirmed');return workflow;}
 async run(id:string,version:string,signal:AbortSignal,beforeSubmit?:(submissionId?:string)=>void){const current=await this.detail(id,signal);if(current.versionId!==version)throw new Error('Workflow changed. Review it again before running.');signal.throwIfAborted();const submissionId=await this.supportsSubmissionReconciliation(signal)?crypto.randomUUID():undefined;signal.throwIfAborted();beforeSubmit?.(submissionId);let response:Record<string,any>;try{response=obj(await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/run`,{input:{},...(submissionId?{submissionId,expectedVersionId:version}:{})},signal));}catch(error){if(submissionId&&error instanceof WorkflowHttpError&&error.status===409&&error.code==='WORKFLOW_VERSION_NOT_ADMITTED'&&error.workflowId===id&&error.submissionId===submissionId&&error.expectedVersionId===version)throw new WorkflowAdmissionRejected();throw error;}if(submissionId&&response.submissionId!==submissionId)throw new Error('Submission identity mismatch');const run=this.runResult(response.execution);if(run.workflowId!==id||(submissionId&&run.versionId!==version))throw new Error('Execution identity or reviewed version changed');return run;}
 async reconcile(id:string,version:string,submissionId:string,signal:AbortSignal){if(!await this.supportsSubmissionReconciliation(signal))throw new Error('Agent does not support submission reconciliation');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(submissionId))throw new Error('Invalid retained submission');const data=obj(await this.request(`/api/workflow/workflows/${encodeURIComponent(id)}/submissions/${submissionId}`,undefined,signal));if(data.submissionId!==submissionId)throw new Error('Submission identity changed');if(data.execution===null)return null;const run=this.runResult(data.execution);if(run.workflowId!==id||run.versionId!==version)throw new Error('Reconciled execution mismatch');return run;}

 async executions(id:string,signal:AbortSignal){const data=obj(await this.request(`/api/workflow/workflows/${encodeURIComponent(str(id))}/executions`,undefined,signal));if(!Array.isArray(data.executions))throw new Error('Invalid execution list');return data.executions.map((x:unknown)=>{const run=this.runResult(x);if(run.workflowId!==id)throw new Error('Execution identity mismatch');return run;});}
 async cancel(id:string,workflowId:string,signal:AbortSignal){const current=await this.receipt(id,workflowId,signal);if(current.finished)return current;const data=obj(await this.request(`/api/workflow/executions/${encodeURIComponent(id)}/cancel`,{},signal));const run=this.runResult(data.execution);if(run.id!==id||run.workflowId!==workflowId)throw new Error('Cancellation identity mismatch');return run;}
 async receipt(id:string,workflowId:string,signal:AbortSignal){const data=obj(await this.request(`/api/workflow/executions/${encodeURIComponent(str(id))}`,undefined,signal));const run=this.runResult(data.execution);if(run.id!==id||run.workflowId!==workflowId)throw new Error('Execution identity mismatch');return run;}
}
