import {test,expect,type Page} from '@playwright/test';
async function boot(page:Page){
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');
 await page.evaluate(async()=>{const {developmentBridge}=await import('/src/browser/development-connection.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'local'}));const identity=developmentIdentity('local'),bridge=developmentBridge('local',identity);(window as any).agentFixture={identity,call:async(path:string,body?:unknown)=>JSON.parse((await bridge.request({path,method:body===undefined?'GET':'POST',...(body===undefined?{}:{body:JSON.stringify(body)}),headers:{},timeoutMs:30000,ownerId:identity.ownerId},new AbortController().signal)).body)};});
}
test('reading an empty development profile creates no saved history',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).agentFixture,{developmentAgentDocument,readDevelopmentAgent}=await import('/src/browser/development-agent-document.ts');return {conversations:(await readDevelopmentAgent(f.identity)).conversations,listed:await f.call('/api/conversations'),snapshot:(await developmentAgentDocument(f.identity).capture()).snapshot??null};})).toEqual({conversations:[],listed:{conversations:[]},snapshot:null});
});
test('two tabs retain concurrent message pairs and replay receipts without duplicates',async({page,context})=>{
 await boot(page);const id=await page.evaluate(async()=>(await (window as any).agentFixture.call('/api/conversations',{title:'Shared'})).conversation.id),other=await context.newPage();await boot(other);
 await Promise.all([page,other].map((tab,index)=>tab.evaluate(async({id,index})=>{const f=(window as any).agentFixture;for(let i=0;i<10;i++){const message={text:`Message ${index}/${i}`,clientMessageId:`m-${index}-${i}`};await f.call(`/api/conversations/${id}/messages`,message);await f.call(`/api/conversations/${id}/messages`,message);}}, {id,index})));
 expect(await page.evaluate(async()=>{const {readDevelopmentAgent}=await import('/src/browser/development-agent-document.ts'),state=await readDevelopmentAgent((window as any).agentFixture.identity),row=state.conversations[0];return {messages:row.messages.length,receipts:Object.keys(row.receipts).length,unique:new Set(row.messages.map(m=>m.id)).size,legacy:localStorage.getItem('alpha.browser.agent.local.v1')};})).toEqual({messages:40,receipts:20,unique:40,legacy:null});
});
test('a failed message commit saves neither message pair nor replay receipt',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).agentFixture,{developmentAgentDocument,readDevelopmentAgent}=await import('/src/browser/development-agent-document.ts'),id=(await f.call('/api/conversations',{title:'Retained'})).conversation.id,domain=developmentAgentDocument(f.identity),before=await domain.capture(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.agent.local.v1')throw Error('Full');return put.call(this,value,key);};let rejected=false;try{await f.call(`/api/conversations/${id}/messages`,{text:'Unconfirmed',clientMessageId:'original'});}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}const after=await domain.capture(),row=(await readDevelopmentAgent(f.identity)).conversations[0];return {rejected,same:JSON.stringify(before.snapshot)===JSON.stringify(after.snapshot),messages:row.messages,receipts:row.receipts};})).toEqual({rejected:true,same:true,messages:[],receipts:{}});
});
test('migration retains exact legacy bytes and refuses a later older-copy edit',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).agentFixture,{developmentAgentDocument,readDevelopmentAgent}=await import('/src/browser/development-agent-document.ts'),{saveDevelopmentReply}=await import('/src/browser/development-connection.ts'),raw='{ "version": 1, "reply": "Original", "conversations": [] }';localStorage.setItem('alpha.browser.agent.local.v1',raw);const initial=await readDevelopmentAgent(f.identity);await saveDevelopmentReply('local','New');const domain=developmentAgentDocument(f.identity),before=await domain.capture();localStorage.setItem('alpha.browser.agent.local.v1','{changed');let rejected=false;try{await readDevelopmentAgent(f.identity);}catch{rejected=true;}return {initial:initial.reply,exact:JSON.parse(before.snapshot!.raw!).legacy===raw,rejected,saved:JSON.parse((await domain.capture()).raw!).reply};})).toEqual({initial:'Original',exact:true,rejected:true,saved:'New'});
});
test('a stale recovery cannot erase newer conversation history',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).agentFixture,{developmentAgentDocument,readDevelopmentAgent}=await import('/src/browser/development-agent-document.ts'),domain=developmentAgentDocument(f.identity),capture=await domain.capture();await f.call('/api/conversations',{title:'Retained'});let rejected=false;try{await domain.reset(capture);}catch{rejected=true;}return {rejected,titles:(await readDevelopmentAgent(f.identity)).conversations.map(c=>c.title)};})).toEqual({rejected:true,titles:['Retained']});
});
test('an account switch during a pending history read discards the old account response',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {selectDevelopmentCloud}=await import('/src/browser/development-cloud.ts'),{developmentBridge,saveDevelopmentReply}=await import('/src/browser/development-connection.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{browserDocuments}=await import('/src/browser/documents.ts'),signal=new AbortController().signal;await selectDevelopmentCloud('first',signal);await saveDevelopmentReply('cloud','First only');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'cloud'}));const identity=developmentIdentity('cloud'),bridge=developmentBridge('cloud',identity),read=browserDocuments.read.bind(browserDocuments);let release!:()=>void,queued!:()=>void;const waiting=new Promise<void>(resolve=>queued=resolve);browserDocuments.read=async(...args)=>{const value=await read(...args);if(args[0]==='alpha.browser.agent.cloud.first.v1'){queued();await new Promise<void>(resolve=>release=resolve);}return value;};const request=bridge.request({path:'/api/conversations',method:'GET',ownerId:identity.ownerId,headers:{},timeoutMs:30000},signal).then(()=>false,()=>true);await waiting;await selectDevelopmentCloud('second',signal);release();return request;})).toBe(true);
});
test('changing the selected profile cannot show a late scripted reply from the previous profile',async({page})=>{
 await boot(page);await page.evaluate(async()=>{const {saveDevelopmentReply}=await import('/src/browser/development-connection.ts'),{browserDocuments}=await import('/src/browser/documents.ts');await saveDevelopmentReply('local','Old local reply');await saveDevelopmentReply('remote','Remote reply');const read=browserDocuments.read.bind(browserDocuments);let first=true;browserDocuments.read=async(...args)=>{const value=await read(...args);if(first&&args[0]==='alpha.browser.agent.local.v1'){first=false;(window as any).replyQueued=true;await new Promise<void>(resolve=>(window as any).releaseReply=resolve);}return value;};});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).replyQueued)).toBe(true);await expect(page.getByRole('textbox',{name:'Scripted reply'})).toBeDisabled();await page.getByRole('combobox',{name:'Development profile'}).selectOption('remote');await expect(page.getByRole('textbox',{name:'Scripted reply'})).toHaveValue('Remote reply');await page.evaluate(()=>(window as any).releaseReply());await expect(page.getByRole('textbox',{name:'Scripted reply'})).toHaveValue('Remote reply');
});
test('damaged agent history remains recoverable through exact-byte backup and reviewed reset',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!sessionStorage.getItem('seeded')){localStorage.setItem('alpha.browser.agent.local.v1','{damaged history');sessionStorage.setItem('seeded','1');}});await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Development data could not be read.');await expect(page.getByRole('button',{name:'Save development reply'})).toBeDisabled();await page.getByRole('button',{name:'Agent history recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Development agent history recovery'}),pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download agent history backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe('{damaged history');await dialog.getByRole('button',{name:'Reset app agent history',exact:true}).click();await dialog.getByRole('button',{name:'Confirm agent history reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>{const {readDevelopmentAgent}=await import('/src/browser/development-agent-document.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');return {state:await readDevelopmentAgent(developmentIdentity('local')),legacy:localStorage.getItem('alpha.browser.agent.local.v1')};})).toEqual({state:{version:1,reply:'Development reply. Edit this response in Agent connection.',conversations:[]},legacy:'{damaged history'});
});
