import {test,expect,type Page} from '@playwright/test';
async function boot(page:Page){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?tools=1');}
test('two tabs retain all concurrently created albums across reload',async({page,context})=>{
 await boot(page);const other=await context.newPage();await other.goto('/');await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');for(let i=0;i<10;i++)await p.changeAlbum({operation:'create',name:`Album ${index}-${i}`});},index)));await page.reload();expect(await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return new Set((await p.albums()).items.map(row=>row.name)).size;})).toBe(20);expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.albums.v1'))).toBeNull();
});
test('failed album writes retain the prior name and revision',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts'),{albumDocument}=await import('/src/browser/preference-documents.ts');const album=await p.changeAlbum({operation:'create',name:'Retained'}),before=await albumDocument.capture(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.albums.v1')throw Error('Full');return put.call(this,value,key);};let rejected=false;try{await p.changeAlbum({operation:'rename',id:album.id,revision:album.revision,name:'Lost'});}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}const after=await albumDocument.capture();return {rejected,unchanged:before.raw===after.raw&&before.snapshot?.revision===after.snapshot?.revision,name:(await p.albums()).items[0].name};})).toEqual({rejected:true,unchanged:true,name:'Retained'});
});
test('visible album names refresh after another tab commits a rename',async({page,context})=>{
 await boot(page);const album=await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return p.changeAlbum({operation:'create',name:'Original'});});await page.getByRole('button',{name:'Photos',exact:true}).click();await page.getByRole('button',{name:'Albums',exact:true}).click();await expect(page.getByRole('button',{name:'Original',exact:true})).toBeVisible();const other=await context.newPage();await other.goto('/');await other.evaluate(async album=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');await p.changeAlbum({operation:'rename',id:album.id,revision:album.revision,name:'Renamed elsewhere'});},album);await expect(page.getByRole('button',{name:'Renamed elsewhere',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Original',exact:true})).toHaveCount(0);
});
test('changed older albums refuse access and stale recovery cannot erase a newer album',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {albumDocument}=await import('/src/browser/preference-documents.ts'),{browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts'),raw='[ ]';localStorage.setItem('alpha.browser.albums.v1',raw);await p.albums();const old=await albumDocument.capture();await p.changeAlbum({operation:'create',name:'Newer'});let stale=false;try{await albumDocument.reset(old);}catch{stale=true;}const before=await albumDocument.capture();localStorage.setItem('alpha.browser.albums.v1','{changed');let refused=false;try{await p.albums();}catch{refused=true;}return {stale,refused,retained:(await albumDocument.capture()).raw===before.raw,exact:JSON.parse(old.snapshot!.raw!).legacy===raw};})).toEqual({stale:true,refused:true,retained:true,exact:true});
});
test('album recovery downloads exact bytes and preserves the saved photo library',async({page})=>{
 await boot(page);await page.evaluate(async()=>{const {importBrowserPhoto}=await import('/src/prototype/browser-camera.ts'),canvas=document.createElement('canvas');canvas.width=16;canvas.height=16;canvas.getContext('2d')!.fillRect(0,0,16,16);await importBrowserPhoto({original:new File([],'fixture.jpg'),image:canvas.toDataURL('image/jpeg'),width:16,height:16},new AbortController().signal);localStorage.setItem('alpha.browser.albums.v1','{damaged albums');});
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Photo album recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Photo album recovery'});const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download photo albums backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe('{damaged albums');
 await dialog.getByRole('button',{name:'Reset app photo albums',exact:true}).click();await dialog.getByRole('button',{name:'Confirm photo albums reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return {albums:(await p.albums()).items.length,photos:(await p.list()).items.length,legacy:localStorage.getItem('alpha.browser.albums.v1')};})).toEqual({albums:0,photos:1,legacy:'{damaged albums'});
});
