import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));});
test('loading browser voice preserves DeviceApps, system and hosted result factories',async({page})=>{
 await page.goto('/?mode=dev');await expect(page.getByRole('textbox',{name:'Ask Alpha',exact:true})).toBeVisible();
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const {DeviceApps,System}=await import('/src/native.ts');const apps=await DeviceApps.list();const roles=await System.getStatus();const hosted=await registerPlugin<any>('AlphaHostedResults').status();return {apps:apps.apps.length,roles:roles.roles.length,enabled:hosted.enabled};});expect(result.apps).toBeGreaterThan(0);expect(result.roles).toBeGreaterThan(0);expect(typeof result.enabled).toBe('boolean');
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await expect(page.getByRole('dialog',{name:'Development device controls',exact:true})).toBeVisible();
});
test('cancellation before deferred voice dependency resolves does not start host speech',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {BrowserVoice}=await import('/src/browser/voice.ts');const {connectionController}=await import('/src/runtime/connection-ui.tsx');const original=connectionController.getBrowserSpeechAgent;let requests=0;(connectionController as any).getBrowserSpeechAgent=()=>({speechRequest:async()=>{requests++;return {ready:true};}});const voice=new BrowserVoice();try{const pending=voice.localSpeechStatus();await voice.cancel();try{await pending;return {cancelled:false,requests};}catch(error){return {cancelled:(error as Error).name==='AbortError',requests};}}finally{connectionController.getBrowserSpeechAgent=original;await voice.releaseLocalSpeech();}});expect(result).toEqual({cancelled:true,requests:0});
});

test('cancelling deferred synthesis cannot start host TTS or create prepared audio',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {BrowserVoice}=await import('/src/browser/voice.ts');const {connectionController}=await import('/src/runtime/connection-ui.tsx');const original=connectionController.getBrowserSpeechAgent;let requests=0;(connectionController as any).getBrowserSpeechAgent=()=>({session:{sessionId:'synthetic'},synthesizeSpeech:async()=>{requests++;return new Blob();}});const voice=new BrowserVoice();try{const pending=voice.synthesizeLocal({text:'Synthetic speech'});await voice.cancel();try{await pending;return {cancelled:false,requests};}catch(error){return {cancelled:(error as Error).name==='AbortError',requests};}}finally{connectionController.getBrowserSpeechAgent=original;await voice.releaseLocalSpeech();}});expect(result).toEqual({cancelled:true,requests:0});
});
