import {test,expect} from '@playwright/test';
import {cloudNotesVoiceFixture,notesRecorder,openNotesRecorder,recordClosedClip,noPhysicalOrLocalVoice} from './cloud-notes-voice-fixture';
// Default Notes UI is Cloud-only. Optional real Whisper qualification remains
// separately in browser-speech-engine.spec.ts; it is not exercised by these ports.
test('unsigned Notes voice offers Cloud sign-in before any capture or local preparation',async({page})=>{
 const f=await cloudNotesVoiceFixture(page,false);await openNotesRecorder(page);await expect(notesRecorder(page).getByRole('button',{name:'Connect Eliza Cloud',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:/Start recording|Record without transcription|Use browser voice|Use development voice/})).toHaveCount(0);await noPhysicalOrLocalVoice(page);expect(f.foreign).toEqual([]);
});
test('Cloud Notes transcript stays reviewable and saves edited text with Cloud provenance',async({page})=>{
 const f=await cloudNotesVoiceFixture(page);await openNotesRecorder(page);await recordClosedClip(page);expect(await page.evaluate(()=>(window as any).cloudNotesVoice.uploads)).toBe(0);await notesRecorder(page).getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();const review=notesRecorder(page).getByRole('textbox',{name:'Review transcript',exact:true});await expect(review).toHaveValue('Closed Cloud transcript');await review.fill('Reviewed Cloud transcript.');await notesRecorder(page).getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByRole('button',{name:'Play recording',exact:true})).toBeVisible();
 const saved=await page.evaluate(async()=>JSON.parse((await(await import('/src/runtime/browser-notes-document.ts')).readBrowserNotesRaw())!).records.find((n:any)=>n.kind==='voice'));expect(saved.body).toBe('Reviewed Cloud transcript.');expect(saved.transcription).toMatchObject({route:'eliza-cloud',edited:true});await noPhysicalOrLocalVoice(page);expect(f.foreign).toEqual([]);
});
test('empty Cloud transcript retains the recording without automatic local or manual fallback',async({page})=>{
 await cloudNotesVoiceFixture(page);await page.evaluate(()=>(window as any).cloudNotesVoice.empty=true);await openNotesRecorder(page);await recordClosedClip(page);await notesRecorder(page).getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();await expect(notesRecorder(page).getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true})).toBeEnabled();await expect(notesRecorder(page).getByRole('textbox',{name:'Review transcript'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Type transcript instead',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).cloudNotesVoice.uploads)).toBe(1);await noPhysicalOrLocalVoice(page);
});
test('microphone denial is visible without a transcription or provider fallback',async({page})=>{
 await cloudNotesVoiceFixture(page);await page.evaluate(()=>(window as any).cloudNotesVoice.denied=true);await openNotesRecorder(page);await notesRecorder(page).getByRole('button',{name:'Start recording',exact:true}).click();await expect(notesRecorder(page)).toContainText(/microphone/i);expect(await page.evaluate(()=>(window as any).cloudNotesVoice.uploads)).toBe(0);await noPhysicalOrLocalVoice(page);
});
test('Cloud credit refusal retains the clip and an explicit retry uses the same Cloud route',async({page})=>{
 await cloudNotesVoiceFixture(page);await page.evaluate(()=>(window as any).cloudNotesVoice.billing=true);await openNotesRecorder(page);await recordClosedClip(page);await notesRecorder(page).getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();await expect(notesRecorder(page)).toContainText('Cloud voice needs credits');await expect(page.getByRole('button',{name:/Type transcript instead|Use browser voice|Use development voice/})).toHaveCount(0);await page.evaluate(()=>(window as any).cloudNotesVoice.billing=false);await notesRecorder(page).getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();await expect(notesRecorder(page).getByRole('textbox',{name:'Review transcript',exact:true})).toHaveValue('Closed Cloud transcript');expect(await page.evaluate(()=>(window as any).cloudNotesVoice.uploads)).toBe(2);await noPhysicalOrLocalVoice(page);
});
for(const exit of ['cancel','background','account'] as const)test(`${exit} during Cloud transcription retires late words without saving`,async({page})=>{
 await cloudNotesVoiceFixture(page);await page.evaluate(()=>(window as any).cloudNotesVoice.hold=true);await openNotesRecorder(page);await recordClosedClip(page);await notesRecorder(page).getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof(window as any).cloudNotesVoice.release)).toBe('function');
 if(exit==='cancel')await notesRecorder(page).getByRole('button',{name:'Cancel transcription',exact:true}).click();
 else await page.evaluate(async exit=>{if(exit==='background'){Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));}else{(window as any).cloudNotesVoice.owner='b';(await import('/src/runtime/connection-ui.tsx')).connectionController.close();}},exit);
 await page.evaluate(()=>(window as any).cloudNotesVoice.release());await expect(notesRecorder(page).getByRole('textbox',{name:'Review transcript',exact:true})).toHaveCount(0);expect(await page.evaluate(async()=>JSON.parse((await(await import('/src/runtime/browser-notes-document.ts')).readBrowserNotesRaw())||'{"records":[]}').records.length)).toBe(0);await noPhysicalOrLocalVoice(page);
});
