import {test,expect} from '@playwright/test';
for(const theme of ['light','dark'])for(const height of [640,360])test(`calendar editor preserves multiline text and reachable actions: ${theme} ${height}`,async({page},info)=>{
 await page.setViewportSize({width:360,height});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&theme='+theme);
 await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent:150});});
 const trigger=page.getByRole('button',{name:'Calendar',exact:true});await trigger.focus();
 await page.evaluate(async()=>{const {editCalendarEvent}=await import('/src/browser/calendar-editor.ts');(window as any).calendarDraftResult=editCalendarEvent({title:'Synthetic multiline event',body:'First line\n\nLast line',location:'Test location',begin:Date.parse('2026-10-04T16:00:00Z'),end:Date.parse('2026-10-04T17:00:00Z'),timeZone:'America/New_York',repeat:'weekly'},async next=>{(window as any).savedCalendarDraft=next;},[{id:'person',name:'Alexandra Montgomery'}]);});
 const dialog=page.getByRole('dialog',{name:'Edit calendar event'}),title=dialog.getByLabel('Event title',{exact:true}),description=dialog.getByLabel('Event description',{exact:true});
 await expect(title).toHaveCSS('font-size','24px');await expect(title).toHaveCSS('color-scheme',theme);await expect(description).toHaveValue('First line\n\nLast line');expect(await description.evaluate(el=>el.tagName)).toBe('TEXTAREA');
 await expect(title).toHaveCSS('color',theme==='dark'?'rgb(255, 255, 255)':'rgb(0, 0, 0)');expect(await title.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(theme==='dark'?'rgb(255, 255, 255)':'rgb(0, 0, 0)');
 const checkActions=async()=>{for(const name of ['Close calendar editor','Save event','Cancel']){const button=dialog.getByRole('button',{name,exact:true});await expect(button).toBeInViewport();const bounds=await button.boundingBox();expect(bounds!.height).toBeGreaterThanOrEqual(44);expect(await button.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit===el||el.contains(hit);})).toBe(true);}};
 await checkActions();
 for(const control of await dialog.locator('input,textarea,select').all()){
  await control.scrollIntoViewIfNeeded();const [box,outer]=await Promise.all([control.boundingBox(),dialog.boundingBox()]);expect(box!.x).toBeGreaterThanOrEqual(outer!.x);expect(box!.x+box!.width).toBeLessThanOrEqual(outer!.x+outer!.width);await checkActions();
 }
 for(const label of ['All day','Local meeting room','Alexandra Montgomery'])expect(await dialog.getByLabel(label,{exact:true}).evaluate(el=>el.closest('label')!.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);
 await dialog.getByRole('button',{name:'Cancel',exact:true}).focus();await title.focus();await title.fill('Edited multiline event');await expect.poll(()=>title.evaluate(el=>el.closest('label')!.getBoundingClientRect().top)).toBeGreaterThanOrEqual((await dialog.locator('header').boundingBox())!.y+(await dialog.locator('header').boundingBox())!.height-1);await page.screenshot({path:info.outputPath('calendar-editor-themed.png'),animations:'disabled'});await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(()=>(window as any).calendarDraftResult)).toEqual({status:'saved'});expect(await page.evaluate(()=>(window as any).savedCalendarDraft.body)).toBe('First line\n\nLast line');await expect(trigger).toBeFocused();
});
test('calendar editor exposes validation, keeps the draft and returns keyboard focus on close',async({page})=>{
 await page.goto('/?mode=dev');const trigger=page.getByRole('button',{name:'Calendar',exact:true});await trigger.focus();await page.evaluate(async()=>{const {editCalendarEvent}=await import('/src/browser/calendar-editor.ts');(window as any).calendarDraftResult=editCalendarEvent({title:'Draft',body:'Original\nDescription',location:'',begin:Date.now(),end:Date.now()+3600000},async()=>{throw Error('Synthetic save failure');});});
 const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await dialog.getByLabel('Event description',{exact:true}).fill('Unsaved\n\nMultiline draft');await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog.getByRole('status',{name:'Calendar editor save status'})).toHaveText('Synthetic save failure');await expect(dialog.getByRole('status',{name:'Calendar editor save status'})).toBeInViewport();await expect(dialog.getByLabel('Event description',{exact:true})).toHaveValue('Unsaved\n\nMultiline draft');await dialog.getByRole('button',{name:'Close calendar editor',exact:true}).focus();await page.keyboard.press('Enter');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();expect(await page.evaluate(()=>(window as any).calendarDraftResult)).toEqual({status:'cancelled'});
});
