import {test,expect} from '@playwright/test';
const dialog=(page:any)=>page.getByRole('dialog',{name:'Edit calendar event'});
const status=(page:any)=>dialog(page).getByRole('status',{name:'Calendar editor draft status'});
async function open(page:any,seed=false){
 if(seed){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');await page.evaluate(async()=>{const {BrowserCalendar}=await import('/src/browser/calendar.ts');const calendar=new BrowserCalendar();await calendar.save({creationId:crypto.randomUUID(),calendarId:'local',title:'All-day original',body:'Original notes',location:'Desk',begin:Date.parse('2027-03-13T00:00Z'),end:Date.parse('2027-03-15T00:00Z'),allDay:true,repeat:'weekly'});});}
 await page.evaluate(async()=>{const {calendarDocument}=await import('/src/browser/calendar-store.ts'),{BrowserCalendar}=await import('/src/browser/calendar.ts');const row=JSON.parse((await calendarDocument.readRaw())!).events[0];(window as any).editorOutcome=new BrowserCalendar().edit({id:row.id,revision:row.revision});});await expect(dialog(page)).toBeVisible();
}
async function draft(page:any){await open(page,true);await dialog(page).getByLabel('Event title',{exact:true}).fill('Retained all-day edits');await dialog(page).getByLabel('Event description',{exact:true}).fill('First line\nRetained second line');await dialog(page).getByLabel('Ends',{exact:true}).fill('2027-03-16');await expect(status(page)).toHaveText('Draft saved locally.');}
async function restore(page:any){await page.reload();await open(page);await dialog(page).getByRole('button',{name:'Restore saved editor',exact:true}).click();await expect(dialog(page).getByLabel('Event title',{exact:true})).toHaveValue('Retained all-day edits');}
test('all-day recurring editor restores fields and saves only the existing event',async({page})=>{
 await draft(page);await restore(page);await expect(dialog(page).getByLabel('Event description',{exact:true})).toHaveValue('First line\nRetained second line');await expect(dialog(page).getByLabel('Ends',{exact:true})).toHaveValue('2027-03-16');await dialog(page).getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog(page)).toHaveCount(0);const events=await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events);expect(events).toHaveLength(1);expect(events[0]).toMatchObject({title:'Retained all-day edits',allDay:true,repeat:'weekly',end:Date.parse('2027-03-17T00:00Z')});await open(page);await expect(dialog(page).getByRole('button',{name:'Save event',exact:true})).toBeEnabled();await expect(dialog(page).getByRole('button',{name:'Restore saved editor',exact:true})).toBeHidden();
});
test('restored older editor cannot overwrite a newer event revision',async({page})=>{
 await draft(page);await page.evaluate(async()=>{const {calendarDocument}=await import('/src/browser/calendar-store.ts');await calendarDocument.edit(()=>({events:[]}),data=>{data.events[0].title='Newer saved event';data.events[0].revision=crypto.randomUUID();});});await restore(page);await dialog(page).getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog(page).getByRole('status',{name:'Calendar editor save status'})).toContainText('older event revision');expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].title)).toBe('Newer saved event');
});
test('explicit discard leaves the event unchanged and permits fresh editing',async({page})=>{
 await draft(page);await page.reload();await open(page);page.once('dialog',d=>d.dismiss());await dialog(page).getByRole('button',{name:'Discard saved editor',exact:true}).click();await expect(dialog(page).getByRole('button',{name:'Restore saved editor',exact:true})).toBeVisible();page.once('dialog',d=>d.accept());await dialog(page).getByRole('button',{name:'Discard saved editor',exact:true}).click();await expect(dialog(page).getByRole('button',{name:'Save event',exact:true})).toBeEnabled();await expect(dialog(page).getByLabel('Event title',{exact:true})).toHaveValue('All-day original');await dialog(page).getByRole('button',{name:'Cancel',exact:true}).click();await open(page);await expect(dialog(page).getByRole('button',{name:'Restore saved editor',exact:true})).toBeHidden();
});
test('another tab requires explicit conflict review before replacing its editor draft',async({page,context})=>{
 await draft(page);const other=await context.newPage();await other.goto('/');await open(other);await dialog(other).getByRole('button',{name:'Restore saved editor',exact:true}).click();await dialog(other).getByLabel('Event title',{exact:true}).fill('Newer draft from other tab');await expect(status(other)).toHaveText('Draft saved locally.');await dialog(page).getByLabel('Event title',{exact:true}).fill('My unsaved conflicting edit');await expect(dialog(page).getByRole('button',{name:'Restore saved editor',exact:true})).toBeVisible();await expect(dialog(page).getByRole('button',{name:'Save event',exact:true})).toBeDisabled();await dialog(page).getByRole('button',{name:'Restore saved editor',exact:true}).click();await expect(dialog(page).getByLabel('Event title',{exact:true})).toHaveValue('Newer draft from other tab');
});
test('known save with failed draft cleanup cannot dispatch again',async({page})=>{
 await draft(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(String(key).startsWith('alpha.browser.assistant-draft:'))throw Error('Draft storage unavailable');return put.call(this,value,key);};});await dialog(page).getByRole('button',{name:'Save event',exact:true}).click();await expect(status(page)).toContainText('Event saved. Retained edits could not be cleared');await expect(dialog(page).getByRole('button',{name:'Save event',exact:true})).toBeDisabled();expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].title)).toBe('Retained all-day edits');await dialog(page).getByRole('button',{name:'Close calendar editor',exact:true}).click();
});
test('oversized edits remain visible until shortening restores persistence',async({page})=>{
 await draft(page);await dialog(page).getByLabel('Event title',{exact:true}).fill('x'.repeat(2100));await expect(status(page)).toContainText('too large to retain');await expect(dialog(page).getByRole('button',{name:'Save event',exact:true})).toBeDisabled();await dialog(page).getByLabel('Event title',{exact:true}).fill('Retained all-day edits');await expect(status(page)).toHaveText('Draft saved locally.');await restore(page);
});
test('retained recovery controls and save remain reachable on a small screen',async({page})=>{
 await page.setViewportSize({width:360,height:360});await draft(page);await page.reload();await open(page);const restoreButton=dialog(page).getByRole('button',{name:'Restore saved editor',exact:true});await expect(restoreButton).toBeInViewport();await restoreButton.click();const description=dialog(page).getByLabel('Event description',{exact:true});await description.focus();await expect.poll(()=>description.evaluate(el=>el.closest('label')!.getBoundingClientRect().top)).toBeGreaterThanOrEqual((await dialog(page).getByRole('region',{name:'Calendar editor draft recovery'}).boundingBox())!.y+(await dialog(page).getByRole('region',{name:'Calendar editor draft recovery'}).boundingBox())!.height-1);await expect(dialog(page).getByRole('button',{name:'Save event',exact:true})).toBeInViewport();await expect(dialog(page).getByRole('button',{name:'Cancel',exact:true})).toBeInViewport();await page.screenshot({path:test.info().outputPath('retained-modal-compact.png'),animations:'disabled'});
});
