import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {replaceCalendarBytes} from './calendar-fixture';
const key='alpha.browser.calendar.v1',raw='{broken calendar';
const saved=(page:Page)=>page.evaluate(async()=>(await (await import('/src/browser/calendar-storage.ts')).calendarSnapshot()).raw);
test.beforeEach(async({page})=>{await page.addInitScript(({key,raw})=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!sessionStorage.getItem('calendar-recovery-seed')){localStorage.setItem(key,raw);localStorage.setItem('unrelated-recovery-test','retain');sessionStorage.setItem('calendar-recovery-seed','1');}},{key,raw});await page.goto('/');});
async function open(page:Page){await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Calendar recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Browser calendar recovery'});await expect(dialog.getByRole('button',{name:'Reset browser calendar',exact:true})).toBeEnabled();return dialog;}
test('backup preserves damaged bytes and reviewed reset restores an empty usable calendar',async({page},info)=>{
 await page.getByRole('button',{name:'Open your calendar',exact:true}).click();await page.getByRole('button',{name:'Recover browser calendar',exact:true}).click();const d=page.getByRole('dialog',{name:'Browser calendar recovery'});const downloading=page.waitForEvent('download');await d.getByRole('button',{name:'Download calendar backup'}).click();const download=await downloading;expect(await readFile((await download.path())!,'utf8')).toBe(raw);
 await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();expect(await saved(page)).toBe(raw);await page.screenshot({path:info.outputPath('calendar-recovery.png')});await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d).toHaveCount(0);await expect(page.getByRole('button',{name:'Open your calendar',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaCalendar').list({begin:Date.now(),end:Date.now()+86400000})).status;})).toBe('ready');expect(await page.evaluate(()=>localStorage.getItem('unrelated-recovery-test'))).toBe('retain');expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(raw);await page.getByRole('button',{name:'Open your calendar',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-active-view','calendar');
});
test('another tab changing the saved calendar invalidates the reset confirmation',async({page,context})=>{
 const d=await open(page);await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();const other=await context.newPage();await other.goto(page.url());const replacement=JSON.stringify({sourceRevision:'new-owner',events:[]});await other.evaluate(replaceCalendarBytes,replacement);await page.bringToFront();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('status')).toContainText('Calendar data changed');expect(await saved(page)).toBe(replacement);
});
test('closing recovery while a transaction is queued cancels the reset',async({page})=>{
 const d=await open(page);
 await page.evaluate(async()=>{
  const request=indexedDB.open('alpha.browser.documents.v1',1);
  const db=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
  const tx=db.transaction('documents','readwrite');let release=false;
  (window as any).releaseRecovery=()=>{release=true;};
  (window as any).recoveryLock=new Promise<void>(resolve=>{tx.oncomplete=()=>{db.close();resolve();};});
  const keep=()=>{if(!release)tx.objectStore('documents').get('alpha.browser.calendar.v1').onsuccess=keep;};keep();
 });
 await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('button',{name:'Confirm calendar reset'})).toBeDisabled();await d.getByRole('button',{name:'Close recovery',exact:true}).click();await page.evaluate(async()=>{(window as any).releaseRecovery();await (window as any).recoveryLock;});expect(await saved(page)).toBe(raw);
});
test('failed reset transaction retains the original and does not claim success',async({page})=>{
 const d=await open(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.calendar.v1')throw new DOMException('Blocked','SecurityError');return put.call(this,value,key);};});await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('status')).toContainText('Blocked');expect(await saved(page)).toBe(raw);
});
test('reset renews calendar authority and rejects a proposal bound to the deleted source',async({page})=>{
 await page.evaluate(replaceCalendarBytes,null);const old=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaCalendar').prepareAgentSource();});const d=await open(page);await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d).toHaveCount(0);await expect(page.getByRole('button',{name:'Open your calendar',exact:true})).toBeVisible();const result=await page.evaluate(async(old)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const c=registerPlugin<any>('AlphaCalendar'),fresh=await c.prepareAgentSource();const proposal=await c.executeAgent({operationId:crypto.randomUUID(),operation:{type:'calendar_create',source:{sourceId:old.sourceId,sourceRevision:old.sourceRevision},fields:{title:'Retired proposal',description:'',location:'',start:new Date(Date.now()+60000).toISOString(),end:new Date(Date.now()+120000).toISOString(),timeZone:'UTC'}}});return {fresh,old,proposal};},old);expect(result.fresh.sourceRevision).not.toBe(result.old.sourceRevision);expect(result.proposal.status).toBe('conflict');
});
test('unavailable IndexedDB leaves original bytes untouched and refuses reset',async({page})=>{
 await page.evaluate(()=>Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Blocked','SecurityError');},configurable:true}));await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Calendar recovery',exact:true}).click();const d=page.getByRole('dialog',{name:'Browser calendar recovery'});await expect(d.getByRole('status')).toContainText('Saved data could not be read');await expect(d.getByRole('button',{name:'Reset browser calendar'})).toBeDisabled();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(raw);
});
