import {expectSavedCalendarDraft,guardCalendarFixture} from './calendar-draft-readiness';
import {test,expect} from '@playwright/test';
test.use({timezoneId:'UTC'});
test.beforeEach(async({context})=>guardCalendarFixture(context));
const status=(page:any)=>page.getByRole('status',{name:'Calendar edit draft status'});
async function edit(page:any,kind:'event'|'reminder'){
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');
 await page.evaluate(async kind=>{if(kind==='event'){const {BrowserCalendar}=await import('/src/browser/calendar.ts');const c=new BrowserCalendar(),id=crypto.randomUUID();await c.save({creationId:id,calendarId:'local',title:'Original event',body:'Original body',location:'Room',begin:Date.parse('2027-03-13T10:00Z'),end:Date.parse('2027-03-13T11:00Z')});await c.acknowledgeCreation({creationId:id});}else{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DailyApps').scheduleReminder({id:'draft-reminder',title:'Original reminder',body:'Original body',at:Date.parse('2027-03-13T10:00Z'),dueAt:Date.parse('2027-03-13T10:00Z'),alertMinutes:null});}},kind);
 await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:kind==='event'?/^Original event,/:/^Original reminder,/}).click();await page.getByRole('button',{name:'Edit event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Retained edits');await expectSavedCalendarDraft(page,'edit');await expect(page.getByRole('button',{name:'Back to calendar',exact:true})).toHaveCount(1);
}
async function resume(page:any){await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'Resume unsaved calendar edits',exact:true}).click();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Retained edits');}
for(const kind of ['event','reminder'] as const)test(`${kind} edits survive reload and save to their existing item`,async({page})=>{
 await edit(page,kind);await resume(page);await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Resume unsaved calendar edits',exact:true})).toHaveCount(0);
 const rows=await page.evaluate(async kind=>kind==='event'?(await new (await import('/src/browser/calendar.ts')).BrowserCalendar().list({begin:0,end:Date.parse('2030-01-01')})).events:(await new (await import('/src/browser/daily.ts')).BrowserDaily().listReminders()).reminders,kind);expect(rows).toHaveLength(1);expect(rows[0].title).toBe('Retained edits');
});
for(const kind of ['event','reminder'] as const)test(`restored ${kind} edits cannot overwrite a newer revision`,async({page})=>{
 await edit(page,kind);await page.evaluate(async kind=>{if(kind==='event'){const {calendarDocument}=await import('/src/browser/calendar-store.ts');await calendarDocument.edit(()=>({events:[]}),data=>{data.events[0].title='Newer saved event';data.events[0].revision=crypto.randomUUID();});}else{const {registerPlugin}=await import('/src/platform-plugins.ts'),daily=registerPlugin<any>('DailyApps');const target=await daily.selectedReminder({id:'draft-reminder'});await daily.operateReminder({operationId:crypto.randomUUID(),bindingHash:'a'.repeat(64),operation:{type:'reminder_update',target,fields:{title:'Newer saved reminder',body:'Newer body'}}});}},kind);
 await resume(page);await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByText(kind==='event'?'This event changed. Reload it before editing. Nothing was overwritten.':'This reminder changed. Reopen it before saving.',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Retained edits');const title=await page.evaluate(async kind=>kind==='event'?(await new (await import('/src/browser/calendar.ts')).BrowserCalendar().list({begin:0,end:Date.parse('2030-01-01')})).events[0].title:(await new (await import('/src/browser/daily.ts')).BrowserDaily().listReminders()).reminders[0].title,kind);expect(title).toBe('Newer saved '+kind);
});
test('reminder title-only recovery on another day preserves its original schedule',async({page})=>{
 await edit(page,'reminder');await page.clock.setFixedTime(new Date('2027-03-14T00:00Z'));await resume(page);await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveCount(0);expect(await page.evaluate(async()=>(await new (await import('/src/browser/daily.ts')).BrowserDaily().listReminders()).reminders[0].at)).toBe(Date.parse('2027-03-13T10:00Z'));
});
test('discarding retained edits leaves the original saved item intact',async({page})=>{
 await edit(page,'event');await resume(page);await page.getByRole('button',{name:'Back to calendar',exact:true}).click();page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Discard retained calendar edits',exact:true}).click();await expect(page.getByRole('button',{name:'Resume unsaved calendar edits',exact:true})).toBeVisible();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Discard retained calendar edits',exact:true}).click();await expect(page.getByRole('button',{name:'Resume unsaved calendar edits',exact:true})).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await expect(page.getByRole('button',{name:/^Original event,/})).toBeVisible();await expect(page.getByRole('button',{name:'Resume unsaved calendar edits',exact:true})).toHaveCount(0);
});
test('discard cannot erase newer edits retained by another tab',async({page,context})=>{
 await edit(page,'event');await resume(page);const other=await context.newPage();await other.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await other.goto('/');await other.getByRole('button',{name:'Calendar',exact:true}).click();await other.getByRole('button',{name:'Resume unsaved calendar edits',exact:true}).click();await other.getByRole('textbox',{name:'Title',exact:true}).fill('Newer retained edits');await expectSavedCalendarDraft(other,'edit');await page.getByRole('button',{name:'Back to calendar',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Discard retained calendar edits',exact:true}).click();await expect(page.getByText('The retained form changed or could not be cleared. Resume it to review both copies.',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'Resume unsaved calendar edits',exact:true}).click();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Newer retained edits');
});
test('a committed reminder edit reconciled on reload cannot repeat its mutation',async({page})=>{
 await edit(page,'reminder');await page.evaluate(async()=>{const {BrowserDaily}=await import('/src/browser/daily.ts');const operate=BrowserDaily.prototype.operateReminder;BrowserDaily.prototype.operateReminder=async function(input){await operate.call(this,input);throw Error('Response lost');};BrowserDaily.prototype.reminderOperationReceipt=async()=>{throw Error('Receipt unavailable');};});await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByText('Reminder edit is unconfirmed. Check action status in Calendar; it will not be repeated.',{exact:true})).toBeVisible();
 await resume(page);await page.evaluate(async()=>{const {BrowserDaily}=await import('/src/browser/daily.ts');(window as any).replayed=0;BrowserDaily.prototype.operateReminder=async()=>{(window as any).replayed++;throw Error('Must not replay');};});await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByText('This reminder changed. Reopen it before saving.',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Retained edits');expect(await page.evaluate(()=>(window as any).replayed)).toBe(0);expect(await page.evaluate(async()=>(await new (await import('/src/browser/daily.ts')).BrowserDaily().listReminders()).reminders.map(r=>r.title))).toEqual(['Retained edits']);
});
