import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const key='alpha.browser.calendar.v1',raw='{broken calendar';
test.beforeEach(async({page})=>{await page.addInitScript(({key,raw})=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!sessionStorage.getItem('calendar-recovery-seed')){localStorage.setItem(key,raw);localStorage.setItem('unrelated-recovery-test','retain');sessionStorage.setItem('calendar-recovery-seed','1');}},{key,raw});await page.goto('/');});
async function open(page:any){await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Calendar recovery',exact:true}).click();return page.getByRole('dialog',{name:'Browser calendar recovery'});}
test('backup preserves damaged bytes and reviewed reset restores an empty usable calendar',async({page},info)=>{
 await page.getByRole('button',{name:'Open your calendar',exact:true}).click();await page.getByRole('button',{name:'Recover browser calendar',exact:true}).click();const d=page.getByRole('dialog',{name:'Browser calendar recovery'});const downloading=page.waitForEvent('download');await d.getByRole('button',{name:'Download calendar backup'}).click();const download=await downloading;expect(await readFile((await download.path())!,'utf8')).toBe(raw);
 await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(raw);await page.screenshot({path:info.outputPath('calendar-recovery.png')});await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d).toHaveCount(0);await expect(page.getByRole('button',{name:'Open your calendar',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const c=registerPlugin<any>('AlphaCalendar');return (await c.list({begin:Date.now(),end:Date.now()+86400000})).status;})).toBe('ready');expect(await page.evaluate(()=>localStorage.getItem('unrelated-recovery-test'))).toBe('retain');await page.getByRole('button',{name:'Open your calendar',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-active-view','calendar');
});
test('another tab changing the saved calendar invalidates the reset confirmation',async({page,context})=>{
 const d=await open(page);await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();const other=await context.newPage();await other.goto(page.url());const replacement=JSON.stringify({sourceRevision:'new-owner',events:[]});await other.evaluate(({key,replacement})=>localStorage.setItem(key,replacement),{key,replacement});await page.bringToFront();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('status')).toContainText('Calendar data changed');expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(replacement);
});
test('closing recovery while a writer holds the lock cancels the queued reset',async({page})=>{
 const d=await open(page);await page.evaluate(async(key)=>{let ready!:()=>void;const started=new Promise<void>(r=>ready=r);(window as any).recoveryLock=navigator.locks.request(key,async()=>{ready();await new Promise<void>(r=>(window as any).releaseRecovery=r);});await started;},key);await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('button',{name:'Confirm calendar reset'})).toBeDisabled();await d.getByRole('button',{name:'Close recovery',exact:true}).click();await page.evaluate(async(key)=>{(window as any).releaseRecovery();await (window as any).recoveryLock;await navigator.locks.request(key,()=>{});},key);expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(raw);
});
test('failed removal retains the original and does not claim success',async({page})=>{
 const d=await open(page);await page.evaluate(key=>{const remove=Storage.prototype.removeItem;Storage.prototype.removeItem=function(k){if(k===key)throw new DOMException('Blocked','SecurityError');return remove.call(this,k);};},key);await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('status')).toContainText('Blocked');expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(raw);
});
test('reset renews calendar authority and rejects a proposal bound to the deleted source',async({page})=>{
 const old=await page.evaluate(async(key)=>{localStorage.removeItem(key);const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaCalendar').prepareAgentSource();},key);const d=await open(page);await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d).toHaveCount(0);await expect(page.getByRole('button',{name:'Open your calendar',exact:true})).toBeVisible();const result=await page.evaluate(async(old)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const c=registerPlugin<any>('AlphaCalendar'),fresh=await c.prepareAgentSource();const proposal=await c.executeAgent({operationId:crypto.randomUUID(),operation:{type:'calendar_create',source:{sourceId:old.sourceId,sourceRevision:old.sourceRevision},fields:{title:'Retired proposal',description:'',location:'',start:new Date(Date.now()+60000).toISOString(),end:new Date(Date.now()+120000).toISOString(),timeZone:'UTC'}}});return {fresh,old,proposal};},old);expect(result.fresh.sourceRevision).not.toBe(result.old.sourceRevision);expect(result.proposal.status).toBe('conflict');
});
test('missing cross-tab locks leaves backup available but refuses reset',async({page})=>{
 const d=await open(page);await page.evaluate(()=>Object.defineProperty(navigator,'locks',{value:undefined,configurable:true}));await d.getByRole('button',{name:'Reset browser calendar',exact:true}).click();await d.getByRole('button',{name:'Confirm calendar reset',exact:true}).click();await expect(d.getByRole('status')).toContainText('Safe browser storage is unavailable');expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(raw);await expect(d.getByRole('button',{name:'Download calendar backup'})).toBeEnabled();
});
