import {test,expect} from '@playwright/test';
for(const theme of ['light','dark'])test(`calendar draft retains reachable fields and actions at large text: ${theme}`,async({page},info)=>{
 await page.setViewportSize({width:360,height:430});
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));
 await page.goto('/?mode=dev&theme='+theme);
 await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent:150});});await page.reload();
 await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'New event',exact:true}).click();
 const save=page.getByRole('button',{name:'Save event',exact:true});expect((await save.boundingBox())!.height).toBeGreaterThanOrEqual(44);
 const fields=page.getByRole('region',{name:'Event details',exact:true});await expect(fields).toBeVisible();await fields.focus();await page.keyboard.press('End');
 const notes=page.getByRole('textbox',{name:'Notes',exact:true});await notes.fill('First paragraph\n\nLong reference '+'abc'.repeat(80));await notes.scrollIntoViewIfNeeded();await expect(notes).toBeInViewport();
 expect(await fields.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);
 for(const name of ['In this app','Once','None','Add people']){const button=fields.getByRole('button',{name,exact:true});await button.scrollIntoViewIfNeeded();await expect(button).toBeInViewport();const box=(await button.boundingBox())!;expect(box.height).toBeGreaterThanOrEqual(44);expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(360);}
 const video=fields.getByRole('switch',{name:'Video link',exact:true});await video.scrollIntoViewIfNeeded();await expect(video).toHaveAttribute('aria-checked','false');const target=(await video.boundingBox())!,track=(await video.locator('.calendar-video-track').boundingBox())!,thumb=(await video.locator('.calendar-video-thumb').boundingBox())!;expect(target.width).toBeGreaterThanOrEqual(44);expect(target.height).toBeGreaterThanOrEqual(44);expect(await video.locator('.calendar-video-track').evaluate(el=>({width:getComputedStyle(el).width,height:getComputedStyle(el).height}))).toEqual({width:'52px',height:'32px'});expect(await video.locator('.calendar-video-thumb').evaluate(el=>({width:getComputedStyle(el).width,height:getComputedStyle(el).height}))).toEqual({width:'26px',height:'26px'});expect(track.width/track.height).toBeCloseTo(52/32,2);expect(thumb.width/track.width).toBeCloseTo(26/52,2);expect(thumb.width/thumb.height).toBeCloseTo(1,2);expect(await video.locator('.calendar-video-track').evaluate(el=>getComputedStyle(el).borderRadius)).toBe('16px');await page.screenshot({path:info.outputPath('video-off.png'),animations:'disabled'});await video.focus();await page.keyboard.press('Space');await expect(video).toHaveAttribute('aria-checked','true');await expect(video.locator('.calendar-video-thumb')).toHaveCSS('transform','matrix(1, 0, 0, 1, 20, 0)');await page.screenshot({path:info.outputPath('video-on.png'),animations:'disabled'});await page.keyboard.press('Space');await expect(video).toHaveAttribute('aria-checked','false');
 await notes.scrollIntoViewIfNeeded();const notesBox=(await notes.boundingBox())!,dockBox=(await page.locator('[data-alpha-layer="pill"]').boundingBox())!;expect(notesBox.y+notesBox.height).toBeLessThanOrEqual(dockBox.y);await page.screenshot({path:info.outputPath('draft-notes.png'),animations:'disabled'});await expect(save).toBeInViewport();await page.getByRole('button',{name:'Back to calendar',exact:true}).click();await expect(fields).toHaveCount(0);
});

for(const theme of ['light','dark'])test(`Calendar timeline fades only clipped content after scrolling: ${theme}`,async({page},info)=>{
 await page.setViewportSize({width:360,height:600});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?theme='+theme);await page.getByRole('button',{name:'Calendar',exact:true}).click();
 const timeline=page.getByRole('region',{name:'Calendar timeline',exact:true}),create=page.getByRole('button',{name:'New event',exact:true});await expect(timeline).toBeVisible();expect(await page.evaluate(()=>CSS.supports('animation-timeline','scroll()'))).toBe(true);await timeline.evaluate(el=>el.scrollTop=0);await expect.poll(()=>timeline.evaluate(el=>parseFloat(getComputedStyle(el).getPropertyValue('--calendar-scroll-fade-top')))).toBe(0);await expect(create).toBeVisible();expect(await create.evaluate(el=>getComputedStyle(el).maskImage)).toBe('none');await page.screenshot({path:info.outputPath('calendar-scroll-start.png'),animations:'disabled'});
 await timeline.evaluate(el=>el.scrollTop=96);await expect.poll(()=>timeline.evaluate(el=>parseFloat(getComputedStyle(el).getPropertyValue('--calendar-scroll-fade-top')))).toBeGreaterThan(0);expect(await timeline.evaluate(el=>getComputedStyle(el).maskImage)).toContain('linear-gradient');await expect(create).toBeInViewport();expect(await create.evaluate(el=>getComputedStyle(el).maskImage)).toBe('none');await page.screenshot({path:info.outputPath('calendar-scroll-middle.png'),animations:'disabled'});
 await create.click();const save=page.getByRole('button',{name:'Save event',exact:true}),fields=page.getByRole('region',{name:'Event details',exact:true});await expect(save).toBeInViewport();expect(await save.evaluate(el=>getComputedStyle(el).maskImage)).toBe('none');expect(await fields.evaluate(el=>getComputedStyle(el).maskImage)).toBe('none');
});
