import {test,expect} from '@playwright/test';
for(const theme of ['light','dark'])for(const height of [915,420])test(`month picker owns keyboard focus ${theme} ${height}`,async({page},info)=>{
 await page.setViewportSize({width:412,height});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?theme='+theme);await page.getByRole('button',{name:'Calendar',exact:true}).click();
 const trigger=page.getByRole('button',{name:'Month view',exact:true});await trigger.click();const dialog=page.getByRole('dialog',{name:'Choose calendar date'});await expect(dialog).toBeVisible();await expect(page.locator('[data-alpha-layer="pill"]')).toBeHidden();await expect(page.locator('[data-alpha-layer="composer"]')).toBeHidden();
 await expect(page.getByRole('region',{name:'Calendar timeline',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'New event',exact:true})).toHaveCount(0);
 await expect.poll(()=>dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);
 const first=dialog.getByRole('button').first(),last=dialog.getByRole('button').last();await last.focus();await page.keyboard.press('Tab');await expect(first).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused();
 await dialog.getByRole('button',{name:'Next month',exact:true}).click();await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Previous month',exact:true}).click();await dialog.getByRole('button',{name:'Close month',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('month-dialog.png')});
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();await expect(page.getByRole('button',{name:'New event',exact:true})).toBeVisible();
 await trigger.click();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
 await trigger.click();await dialog.getByRole('button',{name:/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) /}).first().click();await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
 await trigger.click();await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'Calendar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('button',{name:'Calendar',exact:true})).toBeVisible();
});
