import {test,expect,type Page} from '@playwright/test';
const key='alpha.browser.cloud.setup.first.v1';
async function boot(page:Page){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.evaluate(async()=>{const {readDevelopmentCloudAccount,selectDevelopmentCloud,developmentCloudSetupDocument,developmentPersonal}=await import('/src/browser/development-cloud.ts');const account=await readDevelopmentCloudAccount()||await selectDevelopmentCloud('first',new AbortController().signal);(window as any).cloudSetupFixture={account,store:developmentCloudSetupDocument(account!),client:developmentPersonal(account!)};});}
test('reading an empty setup leaves its recovery revision unclaimed',async({page})=>{await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).cloudSetupFixture;await f.client.inspect(new AbortController().signal);return (await f.store.capture()).snapshot??null;})).toBeNull();});
test('two tabs cannot activate the same reviewed setup twice',async({page,context})=>{
 await boot(page);const other=await context.newPage();await boot(other);for(const tab of [page,other])await tab.evaluate(async()=>{const f=(window as any).cloudSetupFixture;f.review=(await f.client.inspect(new AbortController().signal)).review;});const accepted=await Promise.all([page,other].map(tab=>tab.evaluate(async()=>{const f=(window as any).cloudSetupFixture;try{await f.client.accept(f.review,new AbortController().signal);return true;}catch{return false;}})));expect(accepted.filter(Boolean)).toHaveLength(1);expect(await page.evaluate(async()=>{const f=(window as any).cloudSetupFixture;return (await f.store.read()).phase;})).toBe('provisioning');
});
test('setup preserves exact legacy bytes and refuses a changed old copy',async({page})=>{await boot(page);expect(await page.evaluate(async key=>{const f=(window as any).cloudSetupFixture,raw=' { "phase":"review", "quote":"'+'1'.repeat(64)+'" } ';localStorage.setItem(key,raw);await f.store.read();const capture=await f.store.capture();await f.store.edit((data:any)=>{data.scenario='existing';});localStorage.setItem(key,'{damaged older setup');let rejected=false;try{await f.store.read();}catch{rejected=true;}const after=await f.store.capture();return {exact:capture.raw===raw,rejected,changed:after.legacyChanged,scenario:JSON.parse(after.raw).scenario};},key)).toEqual({exact:true,rejected:true,changed:true,scenario:'existing'});});
test('failed setup edit preserves the provisioning receipt and revision',async({page})=>{await boot(page);expect(await page.evaluate(async key=>{const f=(window as any).cloudSetupFixture;await f.store.edit((data:any)=>{data.phase='provisioning';data.startedAt=Date.now();});const before=await f.store.capture(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(v,k){if(k===key)throw Error('Full');return put.call(this,v,k);};let rejected=false;try{await f.store.edit((data:any)=>{data.phase='ready';});}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}return {rejected,same:JSON.stringify((await f.store.capture()).snapshot)===JSON.stringify(before.snapshot),phase:(await f.store.read()).phase};},key)).toEqual({rejected:true,same:true,phase:'provisioning'});});
test('a new sample-account session rejects a queued setup read and recovery',async({page})=>{await boot(page);expect(await page.evaluate(async key=>{const f=(window as any).cloudSetupFixture,{browserDocuments}=await import('/src/browser/documents.ts'),{selectDevelopmentCloud}=await import('/src/browser/development-cloud.ts');const read=browserDocuments.read.bind(browserDocuments);let release!:()=>void,queued!:()=>void;const started=new Promise<void>(resolve=>queued=resolve);browserDocuments.read=async(...args)=>{const result=await read(...args);if(args[0]===key){queued();await new Promise<void>(resolve=>release=resolve);}return result;};const reading=f.store.read().then(()=>false,()=>true);await started;await selectDevelopmentCloud('second',new AbortController().signal);release();const rejected=await reading;let recoveryRejected=false;try{await f.store.capture();}catch{recoveryRejected=true;}return {rejected,recoveryRejected};},key)).toEqual({rejected:true,recoveryRejected:true});});
test('stale setup recovery cannot discard a newer provisioning state',async({page})=>{await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).cloudSetupFixture,capture=await f.store.capture();await f.store.edit((data:any)=>{data.phase='provisioning';data.startedAt=Date.now();});let rejected=false;try{await f.store.reset(capture);}catch{rejected=true;}return {rejected,phase:(await f.store.read()).phase};})).toEqual({rejected:true,phase:'provisioning'});});
test('unreadable Cloud setup exposes exact backup and explicit reset above connection settings',async({page})=>{
 await boot(page);await page.evaluate(key=>localStorage.setItem(key,' {broken provisioning '),key);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Refresh development setup',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();const trigger=page.getByRole('button',{name:'Cloud setup recovery',exact:true});await trigger.click();const dialog=page.getByRole('dialog',{name:'Development Cloud setup recovery'});await expect(dialog.getByRole('button',{name:'Close recovery',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Development connections'})).toBeVisible();await trigger.click();const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download Cloud setup backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe(' {broken provisioning ');await dialog.getByRole('button',{name:'Reset browser Cloud setup',exact:true}).click();await dialog.getByRole('button',{name:'Confirm Cloud setup reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async key=>{const {browserDocuments}=await import('/src/browser/documents.ts');return {value:JSON.parse((await browserDocuments.read(key))!.raw!).value,legacy:localStorage.getItem(key)};},key)).toEqual({value:null,legacy:' {broken provisioning '});
});
