import {test,expect} from '@playwright/test';
const key='alpha.connection.conversations.v1',owner=JSON.stringify(['http://local','owner','agent']);
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('empty selection does not initialize storage',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const m=await import('/src/runtime/conversation-selection.ts');return {choice:await m.captureConversationChoice(owner),document:(await(await import('/src/browser/documents.ts')).browserDocuments.read(key))??null};},{key,owner})).toEqual({choice:null,document:null});
});
test('concurrent owners retain both choices without a writable legacy mirror',async({page,context})=>{
 const other=await context.newPage();await other.goto('/?mode=dev');
 await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const m=await import('/src/runtime/conversation-selection.ts');await m.selectConversation(JSON.stringify(['http://local','owner-'+index,'agent']),null,'chat-'+index,new AbortController().signal,()=>{});},index)));
 expect(await page.evaluate(async key=>{const m=await import('/src/runtime/conversation-selection.ts');return {ids:await Promise.all([0,1].map(async i=>(await m.captureConversationChoice(JSON.stringify(['http://local','owner-'+i,'agent'])))?.id)),legacy:localStorage.getItem(key)};},key)).toEqual({ids:['chat-0','chat-1'],legacy:null});
});
test('a delayed same-owner choice cannot overwrite a newer selection or an ABA revision',async({page})=>{
 expect(await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts'),signal=new AbortController().signal;await m.selectConversation(owner,null,'first',signal,()=>{});const old=await m.captureConversationChoice(owner);await m.selectConversation(owner,old,'first',signal,()=>{});let refused=false;try{await m.selectConversation(owner,old,'stale',signal,()=>{});}catch{refused=true;}return {refused,id:(await m.captureConversationChoice(owner))?.id};},owner)).toEqual({refused:true,id:'first'});
});
test('retired ownership at commit prevents persistence',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const m=await import('/src/runtime/conversation-selection.ts');let refused=false;try{await m.selectConversation(owner,null,'retired',new AbortController().signal,()=>{throw Error('Owner retired');});}catch{refused=true;}return {refused,stored:(await(await import('/src/browser/documents.ts')).browserDocuments.read(key))??null};},{key,owner})).toEqual({refused:true,stored:null});
});
test('failed write keeps the original selection',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const m=await import('/src/runtime/conversation-selection.ts'),signal=new AbortController().signal;await m.selectConversation(owner,null,'original',signal,()=>{});const old=await m.captureConversationChoice(owner),put=IDBObjectStore.prototype.put;let failed=false;IDBObjectStore.prototype.put=function(value,k){if(k===key)throw Error('Full');return put.call(this,value,k);};try{await m.selectConversation(owner,old,'unsaved',signal,()=>{});}catch{failed=true;}finally{IDBObjectStore.prototype.put=put;}return {failed,retained:JSON.stringify(await m.captureConversationChoice(owner))===JSON.stringify(old)};},{key,owner})).toEqual({failed:true,retained:true});
});
test('legacy choices remain exact and stale reset cannot erase a newer selection',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const raw=JSON.stringify({[owner]:'legacy'});localStorage.setItem(key,raw);const m=await import('/src/runtime/conversation-selection.ts'),old=await m.captureConversationChoice(owner),domain=await m.conversationSelectionDocument(),snapshot=await domain.capture();await m.selectConversation(owner,old,'new',new AbortController().signal,()=>{});let refused=false;try{await domain.reset(snapshot);}catch{refused=true;}return {old,refused,id:(await m.captureConversationChoice(owner))?.id,legacy:localStorage.getItem(key)===raw};},{key,owner})).toEqual({old:{id:'legacy'},refused:true,id:'new',legacy:true});
});
test('malformed selection has exact backup and explicit cache-only recovery',async({page})=>{
 await page.evaluate(key=>localStorage.setItem(key,' broken choices '),key);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Conversation selection recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Conversation selection recovery'});await expect(dialog).toContainText('conversations remain on their agents');const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download conversation selections backup'}).click();const stream=await(await download).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual({raw:' broken choices '});await dialog.getByRole('button',{name:'Reset browser conversation selections'}).click();await dialog.getByRole('button',{name:'Confirm conversation selections reset'}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async owner=>(await import('/src/runtime/conversation-selection.ts')).captureConversationChoice(owner),owner)).toBeNull();
});
test('delayed conversation creation preserves another owner selection',async({page})=>{
 await page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');await connectionController.initialize();await connectionController.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');const original=LocalAgentProtocol.prototype.createConversation;LocalAgentProtocol.prototype.createConversation=async function(...args){(window as any).createWaiting=true;await new Promise<void>(resolve=>(window as any).releaseCreate=resolve);return original.apply(this,args);};});
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Keep both histories');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).createWaiting)).toBe(true);
 await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts');await m.selectConversation(owner,null,'other-owner-chat',new AbortController().signal,()=>{});(window as any).releaseCreate();},owner);
 await expect(page.getByText('Development reply. Edit this response in Agent connection.',{exact:true}).first()).toBeVisible();
 expect(await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts'),{connectionController}=await import('/src/runtime/connection-ui.tsx'),session=connectionController.getSnapshot().session!;return {other:(await m.captureConversationChoice(owner))?.id,current:!!await m.captureConversationChoice(JSON.stringify([session.origin,session.ownerId,session.agentId]))};},owner)).toEqual({other:'other-owner-chat',current:true});
});
for(const mode of ['disconnect','recovery'])test(`${mode} during conversation creation prevents late cache writes and sending`,async({page})=>{
 await page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');await connectionController.initialize();await connectionController.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');(window as any).lateSends=0;LocalAgentProtocol.prototype.createConversation=async()=>{(window as any).createWaiting=true;await new Promise<void>(resolve=>(window as any).releaseCreate=resolve);(window as any).createFinished=true;return {id:'late-conversation',title:'Late'};};LocalAgentProtocol.prototype.send=async()=>{(window as any).lateSends++;return {text:'Unexpected send'};};});
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Cancelled message');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).createWaiting)).toBe(true);
 if(mode==='disconnect')await page.evaluate(async()=>(await import('/src/runtime/connection-ui.tsx')).connectionController.disconnect());
 else{await page.evaluate(async()=>(await import('/src/runtime/connection-ui.tsx')).connectionController.open());await page.getByRole('button',{name:'Conversation selection recovery',exact:true}).click();await expect(page.getByRole('dialog',{name:'Conversation selection recovery'})).toBeVisible();}
 await page.evaluate(()=>(window as any).releaseCreate());await expect.poll(()=>page.evaluate(()=>(window as any).createFinished)).toBe(true);
 expect(await page.evaluate(async key=>({sends:(window as any).lateSends,stored:(await(await import('/src/browser/documents.ts')).browserDocuments.read(key))??null}),key)).toEqual({sends:0,stored:null});
});
