import {test,expect} from '@playwright/test';
const key='alpha.connection.conversations.v1';
test.beforeEach(async({page})=>{await page.addInitScript(()=>{if(!localStorage.getItem('alpha.connection.selection.v1'))localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));});await page.goto('/');});
test('empty reads do not initialize the cache',async({page})=>{
 expect(await page.evaluate(async key=>{const m=await import('/src/runtime/conversation-selection.ts');return {choice:await m.readConversationChoice('owner')??null,saved:!!await(await import('/src/browser/documents.ts')).browserDocuments.read(key)};},key)).toEqual({choice:null,saved:false});
});
test('independent tabs retain every owner choice across reload',async({page,context})=>{
 const other=await context.newPage();await other.goto('/');
 await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const m=await import('/src/runtime/conversation-selection.ts');for(let i=0;i<12;i++)await m.saveConversationChoice('owner-'+index+'-'+i,'conversation-'+i);},index)));
 await page.reload();expect(await page.evaluate(async()=>{const m=await import('/src/runtime/conversation-selection.ts');const values=[];for(let owner=0;owner<2;owner++)for(let i=0;i<12;i++)values.push(await m.readConversationChoice('owner-'+owner+'-'+i)==='conversation-'+i);return values.every(Boolean);})).toBe(true);
 expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBeNull();
});
test('a delayed creation save merges with choices committed after its read',async({page,context})=>{
 const other=await context.newPage();await other.goto('/');
 expect(await page.evaluate(async()=>(await import('/src/runtime/conversation-selection.ts')).readConversationChoice('slow-owner'))).toBeUndefined();
 await other.evaluate(async()=>{await(await import('/src/runtime/conversation-selection.ts')).saveConversationChoice('other-owner','retained');});
 await page.evaluate(async()=>{await(await import('/src/runtime/conversation-selection.ts')).saveConversationChoice('slow-owner','created');});
 expect(await page.evaluate(async()=>{const m=await import('/src/runtime/conversation-selection.ts');return Promise.all(['other-owner','slow-owner'].map(owner=>m.readConversationChoice(owner)));})).toEqual(['retained','created']);
});
test('failed writes retain previous selections',async({page})=>{
 expect(await page.evaluate(async key=>{const m=await import('/src/runtime/conversation-selection.ts');await m.saveConversationChoice('owner','previous');const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(v,k){if(k===key)throw Error('full');return put.call(this,v,k);};let failed=false;try{await m.saveConversationChoice('owner','new');}catch{failed=true;}finally{IDBObjectStore.prototype.put=put;}return {failed,choice:await m.readConversationChoice('owner')};},key)).toEqual({failed:true,choice:'previous'});
});
test('cancelled queued writes do not change the selected conversation',async({page})=>{
 expect(await page.evaluate(async key=>{const m=await import('/src/runtime/conversation-selection.ts');await m.saveConversationChoice('owner','previous');let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let locked!:()=>void;const ready=new Promise<void>(resolve=>locked=resolve);const lock=navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),async()=>{locked();await held;});await ready;const controller=new AbortController();const save=m.saveConversationChoice('owner','cancelled',controller.signal).then(()=>false,()=>true);controller.abort();release();await lock;return {cancelled:await save,choice:await m.readConversationChoice('owner')};},key)).toEqual({cancelled:true,choice:'previous'});
});
test('legacy bytes stay exact and later legacy changes require recovery',async({page})=>{
 expect(await page.evaluate(async key=>{const raw=' { "owner" : "old" }\n';localStorage.setItem(key,raw);const m=await import('/src/runtime/conversation-selection.ts');const old=await m.readConversationChoice('owner');await m.saveConversationChoice('owner','new');const unchanged=localStorage.getItem(key)===raw;localStorage.setItem(key,'{"owner":"late"}');let refused=false;try{await m.readConversationChoice('owner');}catch{refused=true;}const capture=await(await m.conversationSelectionDocument()).capture();return {old,unchanged,refused,changed:capture.legacyChanged,retained:JSON.parse(JSON.parse(capture.raw!).raw).owner};},key)).toEqual({old:'old',unchanged:true,refused:true,changed:true,retained:'new'});
});
test('recovery backs up malformed bytes and resets only local choices',async({page})=>{
 await page.evaluate(key=>localStorage.setItem(key,'broken bytes'),key);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Conversation selection recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Conversation selection recovery'});await expect(dialog).toContainText('does not delete conversations');const downloaded=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download conversation selections backup'}).click();const stream=await(await downloaded).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual({raw:'broken bytes'});await dialog.getByRole('button',{name:'Reset browser conversation selections'}).click();await dialog.getByRole('button',{name:'Confirm conversation selections reset'}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>(await import('/src/runtime/conversation-selection.ts')).readConversationChoice('owner'))).toBeUndefined();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe('broken bytes');
});
test('send preserves another owner choice while provider creation is delayed',async({page})=>{
 await page.goto('/?mode=dev');const owner=await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');await c.startDevelopment('local');const session=c.getSnapshot().session!;const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');const create=LocalAgentProtocol.prototype.createConversation;LocalAgentProtocol.prototype.createConversation=async function(...args){(window as any).creationWaiting=true;await new Promise<void>(resolve=>(window as any).releaseCreation=resolve);return create.apply(this,args);};return JSON.stringify([session.origin,session.ownerId,session.agentId]);});
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Delayed creation');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).creationWaiting)).toBe(true);
 await page.evaluate(async()=>{await(await import('/src/runtime/conversation-selection.ts')).saveConversationChoice('another-owner','retained');(window as any).releaseCreation();});await expect(page.getByText('Development reply. Edit this response in Agent connection.',{exact:true}).first()).toBeVisible();
 expect(await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts');return {other:await m.readConversationChoice('another-owner'),current:!!await m.readConversationChoice(owner)};},owner)).toEqual({other:'retained',current:true});
});
test('connection retirement cancels a queued selection and prevents message dispatch',async({page})=>{
 await page.goto('/?mode=dev');await page.evaluate(async key=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');await c.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');LocalAgentProtocol.prototype.send=async()=>{(window as any).sentAfterRetirement=true;throw Error('Unexpected send');};await new Promise<void>(ready=>{void navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),async()=>{ready();await new Promise<void>(release=>(window as any).releaseChoices=release);});});},key);
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Must not dispatch');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(async key=>(await navigator.locks.query()).pending?.some(lock=>lock.name===JSON.stringify(['browser-document','alpha.browser.documents.v1',key])),key)).toBe(true);
 await page.evaluate(async()=>{await(await import('/src/runtime/connection-ui.tsx')).connectionController.offline();(window as any).releaseChoices();});
 await page.evaluate(key=>navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),()=>{}),key);expect(await page.evaluate(async key=>({sent:!!(window as any).sentAfterRetirement,saved:!!await(await import('/src/browser/documents.ts')).browserDocuments.read(key)}),key)).toEqual({sent:false,saved:false});
});
test('cancelled history restore cannot silently switch the active conversation',async({page})=>{
 await page.goto('/?mode=dev');await page.evaluate(async key=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');await c.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');LocalAgentProtocol.prototype.listConversations=async()=>[{id:'original',title:'Original'},{id:'cancelled',title:'Cancelled'}];LocalAgentProtocol.prototype.messages=async()=>({messages:[]});LocalAgentProtocol.prototype.send=async id=>{(window as any).sentConversation=id;return {text:'Selection receipt'};};await c.restoreHistory('original');await new Promise<void>(ready=>{void navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),async()=>{ready();await new Promise<void>(release=>(window as any).releaseRestore=release);});});(window as any).restoring=c.restoreHistory('cancelled');},key);
 await expect.poll(()=>page.evaluate(async key=>(await navigator.locks.query()).pending?.some(lock=>lock.name===JSON.stringify(['browser-document','alpha.browser.documents.v1',key])),key)).toBe(true);
 await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');c.cancel();(window as any).releaseRestore();await(window as any).restoring;c.close();});await page.getByRole('textbox',{name:'Message Alpha',exact:true}).fill('Keep original');await page.getByRole('textbox',{name:'Message Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).sentConversation)).toBe('original');
});
