import {test,expect} from '@playwright/test';
const key='alpha.connection.conversations.v1',owner=JSON.stringify(['http://local','owner','agent']);
test.beforeEach(async({page})=>{await page.addInitScript(()=>{if(!localStorage.getItem('alpha.connection.selection.v1'))localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));});await page.goto('/?mode=dev');});
test('empty selection does not initialize storage',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const m=await import('/src/runtime/conversation-selection.ts');return {choice:await m.captureConversationChoice(owner),document:(await(await import('/src/browser/documents.ts')).browserDocuments.read(key))??null};},{key,owner})).toEqual({choice:null,document:null});
});
test('independent tabs retain every owner choice across reload',async({page,context})=>{
 const other=await context.newPage();await other.goto('/');
 await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const m=await import('/src/runtime/conversation-selection.ts');for(let i=0;i<12;i++)await m.selectConversation('owner-'+index+'-'+i,null,'conversation-'+i,new AbortController().signal,()=>{});},index)));
 await page.reload();expect(await page.evaluate(async()=>{const m=await import('/src/runtime/conversation-selection.ts');const values=[];for(let owner=0;owner<2;owner++)for(let i=0;i<12;i++)values.push((await m.captureConversationChoice('owner-'+owner+'-'+i))?.id==='conversation-'+i);return values.every(Boolean);})).toBe(true);
 expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBeNull();
});
test('a delayed same-owner choice cannot overwrite a newer selection or an ABA revision',async({page})=>{
 expect(await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts'),signal=new AbortController().signal;await m.selectConversation(owner,null,'first',signal,()=>{});const old=await m.captureConversationChoice(owner);await m.selectConversation(owner,old,'first',signal,()=>{});let refused=false;try{await m.selectConversation(owner,old,'stale',signal,()=>{});}catch{refused=true;}return {refused,id:(await m.captureConversationChoice(owner))?.id};},owner)).toEqual({refused:true,id:'first'});
});
test('retired ownership at commit prevents persistence',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const m=await import('/src/runtime/conversation-selection.ts');let refused=false;try{await m.selectConversation(owner,null,'retired',new AbortController().signal,()=>{throw Error('Owner retired');});}catch{refused=true;}return {refused,stored:(await(await import('/src/browser/documents.ts')).browserDocuments.read(key))??null};},{key,owner})).toEqual({refused:true,stored:null});
});
test('failed write keeps the original selection',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const m=await import('/src/runtime/conversation-selection.ts'),signal=new AbortController().signal;await m.selectConversation(owner,null,'original',signal,()=>{});const old=await m.captureConversationChoice(owner),put=IDBObjectStore.prototype.put;let failed=false;IDBObjectStore.prototype.put=function(value,k){if(k===key)throw Error('Full');return put.call(this,value,k);};try{await m.selectConversation(owner,old,'unsaved',signal,()=>{});}catch{failed=true;}finally{IDBObjectStore.prototype.put=put;}return {failed,retained:JSON.stringify(await m.captureConversationChoice(owner))===JSON.stringify(old)};},{key,owner})).toEqual({failed:true,retained:true});
});
test('legacy choices remain exact and stale reset cannot erase a newer selection',async({page})=>{
 expect(await page.evaluate(async({key,owner})=>{const raw=JSON.stringify({[owner]:'legacy'});localStorage.setItem(key,raw);const m=await import('/src/runtime/conversation-selection.ts'),old=await m.captureConversationChoice(owner),domain=await m.conversationSelectionDocument(),snapshot=await domain.capture();await m.selectConversation(owner,old,'new',new AbortController().signal,()=>{});let refused=false;try{await domain.reset(snapshot);}catch{refused=true;}return {old,refused,id:(await m.captureConversationChoice(owner))?.id,legacy:localStorage.getItem(key)===raw};},{key,owner})).toEqual({old:{id:'legacy'},refused:true,id:'new',legacy:true});
});
test('malformed selection has exact backup and explicit cache-only recovery',async({page})=>{
 await page.evaluate(key=>localStorage.setItem(key,' broken choices '),key);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Conversation selection recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Conversation selection recovery'});await expect(dialog).toContainText('conversations remain on their agents');const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download conversation selections backup'}).click();const stream=await(await download).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual({raw:' broken choices '});await dialog.getByRole('button',{name:'Reset app conversation selections'}).click();await dialog.getByRole('button',{name:'Confirm conversation selections reset'}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async owner=>(await import('/src/runtime/conversation-selection.ts')).captureConversationChoice(owner),owner)).toBeNull();
});
test('delayed conversation creation preserves another owner selection',async({page})=>{
 await page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');await connectionController.initialize();await connectionController.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');const original=LocalAgentProtocol.prototype.createConversation;LocalAgentProtocol.prototype.createConversation=async function(...args){(window as any).createWaiting=true;await new Promise<void>(resolve=>(window as any).releaseCreate=resolve);return original.apply(this,args);};});
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Keep both histories');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).createWaiting)).toBe(true);
 await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts');await m.selectConversation(owner,null,'other-owner-chat',new AbortController().signal,()=>{});(window as any).releaseCreate();},owner);
 await expect(page.getByText('Development reply. Edit this response in Agent connection.',{exact:true}).first()).toBeVisible();
 expect(await page.evaluate(async owner=>{const m=await import('/src/runtime/conversation-selection.ts'),{connectionController}=await import('/src/runtime/connection-ui.tsx'),session=connectionController.getSnapshot().session!;return {other:(await m.captureConversationChoice(owner))?.id,current:!!await m.captureConversationChoice(JSON.stringify([session.origin,session.ownerId,session.agentId]))};},owner)).toEqual({other:'other-owner-chat',current:true});
});
for(const mode of ['disconnect','recovery'])test(`${mode} during conversation creation prevents late cache writes and sending`,async({page})=>{
 await page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');await connectionController.initialize();await connectionController.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');(window as any).lateSends=0;LocalAgentProtocol.prototype.createConversation=async()=>{(window as any).createWaiting=true;await new Promise<void>(resolve=>(window as any).releaseCreate=resolve);(window as any).createFinished=true;return {id:'late-conversation',title:'Late'};};LocalAgentProtocol.prototype.send=async()=>{(window as any).lateSends++;return {text:'Unexpected send'};};});
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Cancelled message');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).createWaiting)).toBe(true);
 if(mode==='disconnect')await page.evaluate(async()=>(await import('/src/runtime/connection-ui.tsx')).connectionController.disconnect());
 else{await page.evaluate(async()=>(await import('/src/runtime/connection-ui.tsx')).connectionController.open());await page.getByRole('button',{name:'Conversation selection recovery',exact:true}).click();await expect(page.getByRole('dialog',{name:'Conversation selection recovery'})).toBeVisible();}
 await page.evaluate(()=>(window as any).releaseCreate());await expect.poll(()=>page.evaluate(()=>(window as any).createFinished)).toBe(true);
 expect(await page.evaluate(async key=>({sends:(window as any).lateSends,stored:(await(await import('/src/browser/documents.ts')).browserDocuments.read(key))??null}),key)).toEqual({sends:0,stored:null});
});

test('cancelled queued writes do not change the selected conversation',async({page})=>{
 expect(await page.evaluate(async key=>{const m=await import('/src/runtime/conversation-selection.ts');await m.selectConversation('owner',null,'previous',new AbortController().signal,()=>{});const expected=await m.captureConversationChoice('owner');let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);let locked!:()=>void;const ready=new Promise<void>(resolve=>locked=resolve);const lock=navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),async()=>{locked();await held;});await ready;const controller=new AbortController();const save=m.selectConversation('owner',expected,'cancelled',controller.signal,()=>{}).then(()=>false,()=>true);controller.abort();release();await lock;return {cancelled:await save,choice:(await m.captureConversationChoice('owner'))?.id};},key)).toEqual({cancelled:true,choice:'previous'});
});
test('legacy bytes stay exact and later legacy changes require recovery',async({page})=>{
 expect(await page.evaluate(async key=>{const raw=' { "owner" : "old" }\n';localStorage.setItem(key,raw);const m=await import('/src/runtime/conversation-selection.ts');const old=await m.captureConversationChoice('owner');await m.selectConversation('owner',old,'new',new AbortController().signal,()=>{});const unchanged=localStorage.getItem(key)===raw;localStorage.setItem(key,'{"owner":"late"}');let refused=false;try{await m.captureConversationChoice('owner');}catch{refused=true;}const capture=await(await m.conversationSelectionDocument()).capture();return {old:old?.id,unchanged,refused,changed:capture.legacyChanged,retained:JSON.parse(JSON.parse(capture.raw!).raw).owner.id};},key)).toEqual({old:'old',unchanged:true,refused:true,changed:true,retained:'new'});
});
test('connection retirement cancels a queued selection and prevents message dispatch',async({page})=>{
 await page.goto('/?mode=dev');await page.evaluate(async key=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');await c.initialize();await c.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');LocalAgentProtocol.prototype.send=async()=>{(window as any).sentAfterRetirement=true;throw Error('Unexpected send');};await new Promise<void>(ready=>{void navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),async()=>{ready();await new Promise<void>(release=>(window as any).releaseChoices=release);});});},key);
 await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Must not dispatch');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(async key=>(await navigator.locks.query()).pending?.some(lock=>lock.name===JSON.stringify(['browser-document','alpha.browser.documents.v1',key])),key)).toBe(true);
 await page.evaluate(async()=>{await(await import('/src/runtime/connection-ui.tsx')).connectionController.offline();(window as any).releaseChoices();});
 await page.evaluate(key=>navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),()=>{}),key);expect(await page.evaluate(async key=>({sent:!!(window as any).sentAfterRetirement,saved:!!await(await import('/src/browser/documents.ts')).browserDocuments.read(key)}),key)).toEqual({sent:false,saved:false});
});
test('cancelled history restore cannot silently switch the active conversation',async({page})=>{
 await page.goto('/?mode=dev');await page.evaluate(async key=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');await c.initialize();await c.startDevelopment('local');const {LocalAgentProtocol}=await import('/src/runtime/local-agent.ts');LocalAgentProtocol.prototype.listConversations=async()=>[{id:'original',title:'Original'},{id:'cancelled',title:'Cancelled'}];LocalAgentProtocol.prototype.messages=async()=>({messages:[]});LocalAgentProtocol.prototype.send=async id=>{(window as any).sentConversation=id;return {text:'Selection receipt'};};await c.restoreHistory('original');await new Promise<void>(ready=>{void navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1',key]),async()=>{ready();await new Promise<void>(release=>(window as any).releaseRestore=release);});});(window as any).restoring=c.restoreHistory('cancelled');},key);
 await expect.poll(()=>page.evaluate(async key=>(await navigator.locks.query()).pending?.some(lock=>lock.name===JSON.stringify(['browser-document','alpha.browser.documents.v1',key])),key)).toBe(true);
 await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');c.cancel();(window as any).releaseRestore();await(window as any).restoring;c.close();});await page.getByRole('textbox',{name:'Message Alpha',exact:true}).fill('Keep original');await page.getByRole('textbox',{name:'Message Alpha',exact:true}).press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).sentConversation)).toBe('original');
});
