import { returnToApps } from './app-navigation';
import {test,expect,type Page} from '@playwright/test';
async function setup(page:Page){await page.goto('/?mode=dev&workflows=agent');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await returnToApps(page);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'New workflow',exact:true}).click();await expect(page.getByText('Build a manual workflow. It will be saved paused.',{exact:true})).toBeVisible();}
async function savedDraft(page:Page){return page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');const {browserWorkflowDraftStore}=await import('/src/browser/workflow-drafts.ts');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const session=c.getSnapshot().session!,store=await browserWorkflowDraftStore(session),slot='workflow-draft:v1:'+await workflowSha([session.origin,session.ownerId,session.agentId]);return (await store.secureRead({slot})).value;});}
test('agent workflow editor saves a typed workflow through the development bridge',async({page})=>{await setup(page);await page.getByRole('button',{name:'Add Read step',exact:true}).click();await page.getByRole('textbox',{name:'Text supplied to workflow',exact:true}).fill('Development workflow input');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await expect(page.getByText(/Review this full specification/)).toBeVisible();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await expect(page.getByRole('button',{name:'Run now',exact:true})).toBeVisible();const data=await page.evaluate(async()=>(await (await import('/src/browser/development-execution-document.ts')).readExecutionPart({namespace:'local'} as any,'workflows',()=>({workflows:[],receipts:[],runs:[]}))));expect(data.workflows).toHaveLength(1);expect(data.workflows[0].active).toBe(false);expect(data.workflows[0].phoneSpec.steps[0].text).toBe('Development workflow input');expect(data.receipts).toHaveLength(1);await page.reload();await page.getByRole('button',{name:'Workflows',exact:true}).click();await expect(page.getByRole('button',{name:/New workflow Agent workflow/})).toBeVisible();});
test('browser draft compare exchange preserves other-tab edits and rejects another owner',async({page})=>{await setup(page);const result=await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');const {browserWorkflowDraftStore}=await import('/src/browser/workflow-drafts.ts');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const session=c.getSnapshot().session!,store=await browserWorkflowDraftStore(session),slot='workflow-draft:v1:'+await workflowSha([session.origin,session.ownerId,session.agentId]),saved=await store.secureRead({slot});const first=await store.secureCompareExchange({slot,expectedValue:saved.value,value:'first'}),second=await store.secureCompareExchange({slot,expectedValue:saved.value,value:'second'});localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));let refused=false;try{await store.secureRead({slot});}catch{refused=true;}return {first,second,refused};});expect(result).toEqual({first:{status:'saved'},second:{status:'conflict'},refused:true});});
test('workflow save retries reuse their receipt and reject changed payloads',async({page})=>{await setup(page);const result=await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const client=c.getWorkflowClient()!.client,signal=new AbortController().signal,catalog=await client.phoneCatalog(signal),spec={version:1 as const,name:'Receipt workflow',description:'',trigger:{kind:'manual' as const},steps:[{id:'read',kind:'Read' as const,operation:'supplied_text',text:'private input'}]},validation=await client.validatePhone(spec,catalog,signal),expected={mutationId:crypto.randomUUID(),specDigest:validation.specDigest,compilerRevision:catalog.compilerRevision};const first=await client.savePhone(spec,catalog,expected,signal),replay=await client.savePhone(spec,catalog,expected,signal),receipt=await client.phoneSaveReceipt(expected,signal);let refused=false;try{const changed={...spec,name:'Changed payload'};await client.savePhone(changed,catalog,{...expected,specDigest:await workflowSha(changed)},signal);}catch{refused=true;}return {same:JSON.stringify(first)===JSON.stringify(replay)&&JSON.stringify(first)===JSON.stringify(receipt),refused,count:(await (await import('/src/browser/development-execution-document.ts')).readExecutionPart({namespace:'local'} as any,'workflows',()=>({workflows:[],receipts:[],runs:[]}))).workflows.length};});expect(result).toEqual({same:true,refused:true,count:1});});
test('Describe preserves the draft when the fixture agent has no typed generator',async({page})=>{
 await setup(page);await page.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Retain this private draft');await page.getByRole('textbox',{name:'Workflow description',exact:true}).fill('Private description');await page.getByRole('button',{name:/Describe it to/}).click();
 await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain this private draft');await expect(page.getByRole('textbox',{name:'Workflow request',exact:true})).toHaveCount(0);
 expect(await page.evaluate(async()=>(await (await import('/src/browser/development-agent-document.ts')).readDevelopmentAgent((await import('/src/browser/development-identity.ts')).developmentIdentity('local'))).conversations.flatMap((c:any)=>c.messages))).toEqual([]);
 await page.reload();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'New workflow',exact:true}).click();await expect(page.getByText(/Restored the draft stored/)).toBeVisible();await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain this private draft');await expect(page.getByRole('textbox',{name:'Workflow description',exact:true})).toHaveValue('Private description');
});
for(const outcome of ['saved','failed','left'])test(`Describe preserves pending draft storage: ${outcome}`,async({page})=>{
 await setup(page);
 await expect.poll(()=>savedDraft(page)).not.toBeNull();
 await page.evaluate(outcome=>{const request=navigator.locks.request.bind(navigator.locks);let held=false;navigator.locks.request=(async(name:any,...args:any[])=>{if(String(name).startsWith('["browser-document","alpha.browser.documents.v1","alpha.browser.workflow-draft:')&&!held){held=true;await new Promise<void>(resolve=>(window as any).releaseDraft=resolve);if(outcome==='failed')throw Error('Synthetic draft storage failure');}return (request as any)(name,...args);}) as any;},outcome);
 await page.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Retain pending private draft');
 await expect.poll(()=>page.evaluate(async()=>typeof (window as any).releaseDraft)).toBe('function');
 await page.getByRole('button',{name:/Describe it to/}).click();
 await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toBeVisible();
 if(outcome==='left')await returnToApps(page);
 await page.evaluate(async()=>(window as any).releaseDraft());
 if(outcome==='saved'){await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain pending private draft');await expect.poll(async()=>JSON.parse((await savedDraft(page))!).spec.name).toBe('Retain pending private draft');await expect(page.getByRole('textbox',{name:'Message Alpha',exact:true})).toHaveCount(0);}
 else if(outcome==='failed'){await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain pending private draft');await expect(page.getByText('Synthetic draft storage failure',{exact:true}).first()).toBeVisible();}
 else{await expect.poll(async()=>JSON.parse((await savedDraft(page))!).spec.name).toBe('Retain pending private draft');await expect(page.getByRole('textbox',{name:'Message Alpha',exact:true})).toHaveCount(0);}
});
test('separate tabs cannot both replace the same workflow draft',async({page,context})=>{
 await setup(page);await returnToApps(page);
 const session=await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');return c.getSnapshot().session!;});
 const other=await context.newPage();await other.goto('/?mode=dev&workflows=agent');
 for(const tab of [page,other])await tab.evaluate(async session=>{const {browserWorkflowDraftStore}=await import('/src/browser/workflow-drafts.ts');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const slot='workflow-draft:v1:'+await workflowSha([session.origin,session.ownerId,session.agentId]),store=await browserWorkflowDraftStore(session);(window as any).draftRace={store,slot,value:(await store.secureRead({slot})).value};},session);
 const results=await Promise.all([page,other].map((tab,i)=>tab.evaluate(async i=>{const {store,slot,value}=(window as any).draftRace;return store.secureCompareExchange({slot,expectedValue:value,value:'winner-'+i});},i)));
 expect(results.map(r=>r.status).sort()).toEqual(['conflict','saved']);
 for(const tab of [page,other])expect(await tab.evaluate(async()=>{const {store,slot}=(window as any).draftRace;return (await store.secureRead({slot})).value;})).toBe('winner-'+results.findIndex(r=>r.status==='saved'));
});
test('a draft read finishing after an owner switch cannot reveal the old value',async({page})=>{
 await setup(page);await returnToApps(page);
 const result=await page.evaluate(async()=>{
  const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');const {browserWorkflowDraftStore}=await import('/src/browser/workflow-drafts.ts');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const {browserDocuments}=await import('/src/browser/documents.ts');
  const session=c.getSnapshot().session!,slot='workflow-draft:v1:'+await workflowSha([session.origin,session.ownerId,session.agentId]),store=await browserWorkflowDraftStore(session),before=await store.secureRead({slot});
  await store.secureCompareExchange({slot,expectedValue:before.value,value:'Private old-owner draft'});
  const read=browserDocuments.read.bind(browserDocuments);let release!:()=>void,entered!:()=>void;const started=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
  browserDocuments.read=async(key,signal)=>{const result=await read(key,signal);if(key==='alpha.browser.'+slot){entered();await gate;}return result;};
  try{const pending=store.secureRead({slot}).then(value=>({value:value.value,error:''}),error=>({value:null,error:error.message}));await started;localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));release();return await pending;}finally{browserDocuments.read=read;}
 });
 expect(result.value).toBeNull();expect(result.error).toContain('owner changed');
});
