import {test,expect,type Page} from '@playwright/test';
async function open(page:Page){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await expect(page.getByRole('heading',{name:'Development connections'})).toBeVisible();}
for(const profile of ['local','cloud','remote'])test(`${profile} development setup saves a reply, chats, reloads and restores history`,async({page})=>{
 const external:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().includes('127.0.0.1'))external.push(r.url());});await page.goto('/?mode=dev');await open(page);await page.getByLabel('Development profile',{exact:true}).selectOption(profile);if(profile==='local')await page.screenshot({path:test.info().outputPath('development-connections.png')});await page.getByRole('textbox',{name:'Scripted reply'}).fill('Saved development answer');await page.getByRole('button',{name:'Save development reply'}).click();await expect(page.getByRole('status').filter({hasText:'Development reply saved.'})).toBeVisible();await page.getByRole('button',{name:'Connect development profile'}).click();await expect(page.getByRole('dialog',{name:'Development connections'})).toHaveCount(0);await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Test message');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect(page.getByText('Saved development answer',{exact:true}).first()).toBeVisible();await page.reload();await open(page);await page.getByRole('button',{name:'Load conversations'}).click();await page.getByRole('button',{name:'Restore conversation'}).click();await expect(page.getByText('Saved development answer',{exact:true}).first()).toBeVisible();expect(external).toEqual([]);
});
test('failed development selection save cannot claim a connection',async({page})=>{
 await page.goto('/?mode=dev');await open(page);await page.evaluate(()=>{const write=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.connection.selection.v1')throw Error('full');return write.call(this,key,value);};});await page.getByRole('button',{name:'Connect development profile'}).click();await expect(page.getByRole('alert')).toBeVisible();expect(await page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');return connectionController.getSnapshot().session;})).toBeNull();
});
test('profile histories stay separate and disconnect survives reload',async({page})=>{
 await page.goto('/?mode=dev');await open(page);await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Local history');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect(page.getByText('Development reply. Edit this response in Agent connection.',{exact:true}).first()).toBeVisible();await page.reload();await open(page);await page.getByLabel('Development profile',{exact:true}).selectOption('remote');await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Load conversations'}).click();await expect(page.getByText('No saved conversations were returned.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Disconnect agent'}).click();await page.reload();expect(await page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');return connectionController.getSnapshot().session;})).toBeNull();
});
test('Home cancels a queued reply save without persistence',async({page})=>{
 await page.goto('/?mode=dev');await open(page);await page.getByRole('textbox',{name:'Scripted reply'}).fill('Must not save');await page.evaluate(async()=>{await new Promise<void>(ready=>{void navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1','alpha.browser.agent.local.v1']),async()=>{ready();await new Promise<void>(release=>(window as any).releaseAgent=release);});});});await page.getByRole('button',{name:'Save development reply'}).click();await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));await expect(page.getByRole('dialog',{name:'Development connections'})).toHaveCount(0);await page.evaluate(()=>(window as any).releaseAgent());await page.evaluate(()=>navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1','alpha.browser.agent.local.v1']),()=>{}));expect(await page.evaluate(async()=>((await import('/src/browser/documents.ts')).browserDocuments.read('alpha.browser.agent.local.v1')).then(value=>value??null))).toBeNull();
});
test('another tab selection retires the old development session',async({page,context})=>{
 await page.goto('/?mode=dev');await open(page);await page.getByRole('button',{name:'Connect development profile'}).click();const other=await context.newPage();await other.goto('/?mode=dev');await other.evaluate(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await expect.poll(()=>page.evaluate(async()=>{const {connectionController}=await import('/src/runtime/connection-ui.tsx');return connectionController.getSnapshot().session;})).toBeNull();
});
test('interactive development connection supplies a real workflow Write result',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:902,name:'Development connected note',on:true,trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Write',t:'A short message',apps:[]},{k:'Write',t:'A note in Notes',apps:['Notes']}],runs:[]}],localRuns:{}})));await page.goto('/?mode=dev');await open(page);await page.getByRole('textbox',{name:'Scripted reply'}).fill('A reviewed development response');await page.getByRole('button',{name:'Save development reply'}).click();await expect(page.getByText('Development reply saved.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Development connected note',{exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns).map((r:any)=>r.status))).toEqual(['ok']);expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/runtime/browser-notes-document.ts')).readBrowserNotesRaw())!).records.some((r:any)=>r.body==='A reviewed development response'))).toBe(true);
});
