import {test,expect,type Page} from '@playwright/test';
const panel=(page:Page)=>page.getByRole('dialog',{name:'Scheduled digests',exact:true});
async function setup(page:Page){await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.evaluate(async()=>window.dispatchEvent(new Event('alpha:hosted-digests')));await panel(page).getByText('Use live Google data',{exact:true}).click();await panel(page).getByText('Connect Cloud for scheduled reads',{exact:true}).click();}
test('local authorization review survives reload and revocation disables its sources',async({page})=>{
 await page.clock.install({time:new Date('2026-10-03T12:00:10Z')});await setup(page);await panel(page).getByRole('button',{name:'Review Cloud read access',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Approve browser read access',exact:true})).toBeVisible();await page.reload();await page.evaluate(async()=>window.dispatchEvent(new Event('alpha:hosted-digests')));await panel(page).getByText('Use live Google data',{exact:true}).click();await panel(page).getByRole('button',{name:'Approve browser read access',exact:true}).click();await expect(panel(page).getByText('Cloud read access is connected. Choose its account and source below.',{exact:true})).toBeVisible();await panel(page).getByRole('combobox',{name:'Google account',exact:true}).selectOption({label:'Browser Cloud read grant'});await panel(page).getByRole('button',{name:'Review live source',exact:true}).click();await panel(page).getByRole('button',{name:'Confirm',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Review morning schedule',exact:true})).toBeVisible();await panel(page).getByRole('combobox',{name:'Reviewed source',exact:true}).selectOption({index:1});await panel(page).getByLabel('Time zone',{exact:true}).fill('UTC');await panel(page).getByLabel('Morning',{exact:true}).fill('12:01');await panel(page).getByRole('button',{name:'Review morning schedule',exact:true}).click();await panel(page).getByRole('button',{name:'Confirm',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Review morning schedule',exact:true})).toBeVisible();await page.evaluate(async()=>localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[{id:'grant-mail',subj:'Granted source result',receivedAt:Date.now(),snippet:'Read under reviewed grant'}]})));await page.clock.runFor(60000);await panel(page).getByRole('button',{name:'Refresh',exact:true}).click();await expect(panel(page).getByText('Development reply. Edit this response in Agent connection.',{exact:true})).toBeVisible();await expect(panel(page).locator('article details pre')).toBeHidden();await panel(page).getByText('Execution details',{exact:true}).click();await expect(panel(page).locator('article details pre')).toContainText('Granted source result');
 await panel(page).getByText('Use live Google data',{exact:true}).click();await panel(page).getByRole('button',{name:'Refresh connected accounts',exact:true}).click();await panel(page).getByRole('combobox',{name:'Google account',exact:true}).selectOption({label:'Browser Cloud read grant'});await panel(page).getByRole('button',{name:'Revoke selected Cloud grant for all its sources',exact:true}).click();await expect(panel(page).getByText('Cloud grant revoked. All sources using it are disabled.',{exact:true})).toBeVisible();const state=await page.evaluate(async()=>(await (await import('/src/browser/development-digest-document.ts')).readDevelopmentDigests((await import('/src/browser/development-identity.ts')).developmentIdentity('local'))));expect(state.delegation.grants).toHaveLength(1);expect(state.delegation.grants[0].revoked).toBe(true);expect(state.sources[0].revoked).toBe(true);expect(state.results).toHaveLength(1);expect(state.results[0].source.live.accountId).toBe('cloud:'+state.delegation.grants[0].id);
});
test('cancelling local read authorization creates no grant',async({page})=>{await setup(page);await panel(page).getByRole('button',{name:'Review Cloud read access',exact:true}).click();await panel(page).getByRole('button',{name:'Cancel authorization',exact:true}).click();await expect(panel(page).getByText('Authorization cancelled.',{exact:true})).toBeVisible();expect(await page.evaluate(async()=>(await (await import('/src/browser/development-digest-document.ts')).readDevelopmentDigests((await import('/src/browser/development-identity.ts')).developmentIdentity('local'))).delegation.grants)).toEqual([]);});
test('lost completion response recovers the original grant after reload',async({page})=>{
 await setup(page);await page.evaluate(async()=>{const {HostedDigestProtocol}=await import('/src/runtime/hosted-digests.ts'),original=HostedDigestProtocol.prototype.delegation;HostedDigestProtocol.prototype.delegation=async function(path,body,signal){const result=await original.call(this,path,body,signal);if(path==='complete')throw Error('Lost completion response');return result;};});await panel(page).getByRole('button',{name:'Review Cloud read access',exact:true}).click();await panel(page).getByRole('button',{name:'Approve browser read access',exact:true}).click();await expect(panel(page).getByText('The request is saved. Retry it to recover the exact authorization.',{exact:true})).toBeVisible();const first=await page.evaluate(async()=>(await (await import('/src/browser/development-digest-document.ts')).readDevelopmentDigests((await import('/src/browser/development-identity.ts')).developmentIdentity('local'))).delegation.grants);expect(first).toHaveLength(1);await page.reload();await page.evaluate(async()=>window.dispatchEvent(new Event('alpha:hosted-digests')));await panel(page).getByText('Use live Google data',{exact:true}).click();await expect(panel(page).getByText('Cloud read access is connected. Choose its account and source below.',{exact:true})).toBeVisible();expect(await page.evaluate(async()=>(await (await import('/src/browser/development-digest-document.ts')).readDevelopmentDigests((await import('/src/browser/development-identity.ts')).developmentIdentity('local'))).delegation.grants)).toEqual(first);
});
test('expired authorization cannot grant and retired connection cannot complete a pending review',async({page})=>{
 await page.clock.install({time:new Date('2026-10-03T12:00:00Z')});await setup(page);await panel(page).getByRole('button',{name:'Review Cloud read access',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Approve browser read access',exact:true})).toBeEnabled();await page.clock.setFixedTime(new Date('2026-10-03T12:11:00Z'));await panel(page).getByRole('button',{name:'Check authorization status',exact:true}).click();await expect(panel(page).getByText('Authorization expired or was cancelled. Start a new review.',{exact:true})).toBeVisible();expect(await page.evaluate(async()=>(await (await import('/src/browser/development-digest-document.ts')).readDevelopmentDigests((await import('/src/browser/development-identity.ts')).developmentIdentity('local'))).delegation.grants)).toEqual([]);
 const refused=await page.evaluate(async()=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),identity=developmentIdentity('local');const started:any=await request(identity,'/api/workflow/hosted/cloud-delegation/start',{mutationId:crypto.randomUUID(),kinds:['email'],confirmed:true});localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));try{await request(identity,'/api/workflow/hosted/cloud-delegation/complete',{state:started.state,confirmed:true});return false;}catch{return true;}});expect(refused).toBe(true);
});
