import {test,expect,type Page} from '@playwright/test';
async function pin(page:Page){await page.goto('/?mode=dev');await page.getByRole('button',{name:'Maps',exact:true}).click();const q=page.getByRole('textbox',{name:'Search places',exact:true});await q.fill('43.7384, 7.4246');await q.press('Enter');}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));Object.defineProperty(navigator,'share',{configurable:true,value:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).copied=text;}}});});});
test('rendered place sharing copies exact coordinates and a usable map link',async({page})=>{await pin(page);await page.getByRole('button',{name:'Share',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).copied)).toBe('Dropped pin\n43.7384, 7.4246\nhttps://www.openstreetmap.org/?mlat=43.7384&mlon=7.4246#map=17/43.7384/7.4246');});
test('share sheet cancellation never writes the clipboard',async({page})=>{await pin(page);await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:async(data:any)=>{(window as any).shared=data;throw new DOMException('Cancelled','AbortError');}}));await page.getByRole('button',{name:'Share',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).shared?.title)).toBe('Dropped pin');expect(await page.evaluate(()=>(window as any).copied)).toBeUndefined();await expect(page.getByRole('dialog',{name:'Share Maps'})).toHaveCount(0);});
test('denied clipboard opens selectable text and exact downloadable bytes',async({page})=>{await pin(page);await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('Denied');}}}));await page.getByRole('button',{name:'Share',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Share Maps'});await expect(dialog).toBeVisible();await page.screenshot({path:'test-results/maps-share-fallback.png'});const text=await dialog.getByRole('textbox',{name:'Share text'}).inputValue();const href=await dialog.getByRole('link',{name:'Download text'}).getAttribute('href');expect(await page.evaluate(async(url)=>await(await fetch(url!)).text(),href)).toBe(text);await dialog.getByRole('button',{name:'Select text'}).click();expect(await dialog.getByRole('textbox').evaluate((el:HTMLTextAreaElement)=>el.selectionEnd-el.selectionStart)).toBe(text.length);await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(dialog).toHaveCount(0);expect(await page.evaluate(async(url)=>{try{await fetch(url!);return false;}catch{return true;}},href)).toBe(true);});
test('leaving Maps retires held share rejection without clipboard or dialog fallback',async({page})=>{await pin(page);await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:()=>new Promise((_,reject)=>{(window as any).rejectShare=reject;})}));await page.getByRole('button',{name:'Share',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof(window as any).rejectShare)).toBe('function');await page.getByRole('button',{name:'Home',exact:true}).click();await page.evaluate(()=>(window as any).rejectShare(Error('late')));expect(await page.evaluate(()=>(window as any).copied)).toBeUndefined();await expect(page.getByRole('dialog',{name:'Share Maps'})).toHaveCount(0);});
test('ready route sharing uses actual route instructions and rejects stale routes',async({page})=>{
 await page.goto('/?mode=dev');await page.evaluate(async()=>{const {configureMapsProvider}=await import('/src/maps/runtime.ts');const place={providerId:'fixture-region',id:'destination',name:'Test destination',coordinate:{latitude:43.739,longitude:7.425},attribution:'Fixture attribution',fetchedAt:Date.now()};configureMapsProvider({status:'configured',providerId:'fixture-region',connectionId:'conn_fixture_region_123456',revision:'fixture1',capabilities:{map:false,search:true,placeDetails:true,modes:['drive'],traffic:'none',transit:'none',offline:{map:false,search:false,routing:false}}},{providerId:'fixture-region',connectionId:'conn_fixture_region_123456',search:async()=>[place],detail:async()=>place,route:async(from,to,mode)=>({providerId:'fixture-region',id:'route',from,to,mode,geometry:[from,to],distanceMeters:307,durationSeconds:223,steps:[{instruction:'Turn toward the square',coordinate:to,distanceMeters:307}],attribution:'Fixture attribution',fetchedAt:Date.now(),traffic:'none'})});});
 await page.getByRole('button',{name:'Maps',exact:true}).click();const q=page.getByRole('textbox',{name:'Search places'});await q.fill('Test destination');await q.press('Enter');await page.getByRole('button',{name:/^Test destination/}).first().click();await page.getByRole('button',{name:'Directions',exact:true}).click();const origin=page.getByRole('textbox',{name:'Route origin coordinates'});await origin.fill('43.738, 7.424');await origin.press('Enter');await expect(page.getByText(/no live traffic/).first()).toBeVisible();await page.getByRole('button',{name:'Share route',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).copied)).toBe('Route to Test destination\ndrive: 43.738, 7.424 → 43.739, 7.425\n307 m · 223 s\n1. Turn toward the square\nTraffic: none\nFixture attribution');await page.evaluate(()=>(window as any).copied=undefined);await origin.fill('43.737, 7.423');await page.getByRole('button',{name:'Share route',exact:true}).click();expect(await page.evaluate(()=>(window as any).copied)).toBeUndefined();
});

test('successful native share uses its payload without a clipboard side effect',async({page})=>{await pin(page);await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:async(data:any)=>{(window as any).shared=data;}}));await page.getByRole('button',{name:'Share',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).shared?.text)).toBe('Dropped pin\n43.7384, 7.4246');expect(await page.evaluate(()=>(window as any).copied)).toBeUndefined();});
for(const event of ['pagehide','launcher-home','alpha:device-state','alpha:dev-incoming-call'])test(`share fallback retires on ${event}`,async({page})=>{await pin(page);await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('Denied');}}}));await page.getByRole('button',{name:'Share',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Share Maps'});await expect(dialog).toBeVisible();const url=await dialog.getByRole('link',{name:'Download text'}).getAttribute('href');await page.evaluate(event=>window.dispatchEvent(new Event(event)),event);await expect(dialog).toHaveCount(0);expect(await page.evaluate(async(url)=>{try{await fetch(url!);return false;}catch{return true;}},url)).toBe(true);});
