import {test,expect} from '@playwright/test';
test.use({timezoneId:'UTC'});
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-06-01T06:00Z'));await page.goto('/?mode=dev');});
async function open(page:any){await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'Clock alarms',exact:true}).click();return page.getByRole('dialog',{name:'Clock alarms',exact:true});}
test('browser Clock sets, lists, reloads and deletes an alarm through rendered controls',async({page},info)=>{
 let d=await open(page);await d.getByRole('textbox',{name:'Alarm label'}).fill('Morning');await d.getByLabel('Alarm time',{exact:true}).fill('07:15');await d.getByRole('button',{name:'Save alarm',exact:true}).click();await expect(d.getByText('Morning',{exact:true})).toBeVisible();await page.reload();d=await open(page);await expect(d.getByText('Morning',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('clock.png'),animations:'disabled'});await d.getByRole('button',{name:'Delete Morning',exact:true}).click();await expect(d.getByText('No alarms',{exact:true})).toBeVisible();await d.getByRole('button',{name:'Close Clock',exact:true}).click();await expect(d).toHaveCount(0);
});
test('due alarms ring in the foreground, snooze, ring again and dismiss without replaying stale actions',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DailyApps').scheduleReminder({id:'alarm_due',title:'Wake up',at:Date.now()+1000});});await page.clock.setFixedTime(new Date('2027-06-01T06:00:02Z'));const d=page.getByRole('dialog',{name:'Clock alarms',exact:true});await expect(d.getByText('Ringing',{exact:true})).toBeVisible();const row=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('DailyApps').listReminders()).reminders.find((r:any)=>r.id==='alarm_due');});await d.getByLabel('Snooze minutes',{exact:true}).fill('2');await d.getByRole('button',{name:'Snooze Wake up',exact:true}).click();await expect(d.getByText('Ringing',{exact:true})).toHaveCount(0);expect(await page.evaluate(async(row)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('DailyApps').clockDecision({id:row.id,revision:row.revision,action:'dismiss'});},row)).toEqual({status:'stale'});await page.clock.setFixedTime(new Date('2027-06-01T06:02:03Z'));await expect(d.getByText('Ringing',{exact:true})).toBeVisible();await d.getByRole('button',{name:'Dismiss Wake up',exact:true}).click();await expect(d.getByText('No alarms',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('dialog',{name:'Clock alarms',exact:true})).toHaveCount(0);
});
test('invalid and failed alarm changes cannot publish success or erase the prior alarm',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('DailyApps');let invalid=0;for(const input of [{action:'set',hour:99,minute:0,label:'No',reviewed:true},{action:'set',hour:7,minute:0,label:'No',reviewed:false},{action:'snooze',snoozeMinutes:0,reviewed:true}])try{await d.clockHandoff(input);}catch{invalid++;}await d.clockHandoff({action:'set',hour:7,minute:0,label:'Retained',reviewed:true});return invalid;});expect(result).toBe(3);const d=await open(page);await expect(d.getByText('Retained',{exact:true})).toBeVisible();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restoreStorage=()=>{Storage.prototype.setItem=set;};Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.reminders.v1')throw Error('Full');return set.call(this,key,value);};});await d.getByRole('button',{name:'Delete Retained',exact:true}).click();await expect(d.getByRole('status')).toContainText('could not');await expect(d.getByText('Retained',{exact:true})).toBeVisible();await page.evaluate(()=>(window as any).restoreStorage());await d.getByRole('button',{name:'Delete Retained',exact:true}).click();await expect(d.getByText('No alarms',{exact:true})).toBeVisible();
});
test('alarm audio respects volume and DND, and stops after dismiss',async({page})=>{
 await page.evaluate(()=>{const w=window as any;w.sounds=[];w.levels=[];w.AudioContext=class{state='running';currentTime=0;destination={};resume(){return Promise.resolve();}close(){return Promise.resolve();}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(value:number){w.levels.push(value);}},connect(){},disconnect(){}};}createOscillator(){const o={frequency:{value:0},connect(){},disconnect(){},start(){w.sounds.push(o.frequency.value);},stop(){}};return o;}};});const d=await open(page);await d.getByRole('button',{name:'Close Clock',exact:true}).click();await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const device=registerPlugin<any>('AlphaDevice');await device.setSensor({field:'doNotDisturb',enabled:true});await device.openSettings({page:'sound'});});const settings=page.getByRole('dialog',{name:'sound settings'});await settings.getByRole('slider',{name:'alarm',exact:true}).fill('20');await settings.getByRole('button',{name:'Done',exact:true}).click();await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DailyApps').scheduleReminder({id:'alarm_sound',title:'Sound test',at:Date.now()+1000});});await page.clock.setFixedTime(new Date('2027-06-01T06:00:02Z'));await expect(d.getByText('Ringing',{exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).sounds)).toEqual([]);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'doNotDisturb',enabled:false});});await expect.poll(()=>page.evaluate(()=>(window as any).sounds.length)).toBeGreaterThan(0);expect(await page.evaluate(()=>(window as any).levels)).toContain(.024);await d.getByRole('button',{name:'Dismiss Sound test',exact:true}).click();await expect(d.getByText('No alarms',{exact:true})).toBeVisible();const count=await page.evaluate(()=>(window as any).sounds.length);await page.waitForTimeout(1100);expect(await page.evaluate(()=>(window as any).sounds.length)).toBe(count);
});
test('only one tab owns a due alarm and backgrounding transfers foreground ownership',async({page,context})=>{
 const other=await context.newPage();await other.clock.setFixedTime(new Date('2027-06-01T06:00:00Z'));await other.goto('/?mode=dev');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DailyApps').scheduleReminder({id:'alarm_shared',title:'Shared alarm',at:Date.now()+1000});});await page.clock.setFixedTime(new Date('2027-06-01T06:00:02Z'));const dialog=(p:any)=>p.getByRole('dialog',{name:'Clock alarms',exact:true});await expect.poll(async()=>(await dialog(page).count())+(await dialog(other).count())).toBe(1);const owner=await dialog(page).count()?page:other,next=owner===page?other:page;await owner.evaluate(()=>{document.documentElement.dataset.devBackground='true';window.dispatchEvent(new Event('alpha:device-state'));});await expect(dialog(owner)).toHaveCount(0);await expect(dialog(next)).toBeVisible();await dialog(next).getByRole('button',{name:'Dismiss Shared alarm',exact:true}).click();await expect(dialog(next).getByText('No alarms',{exact:true})).toBeVisible();await other.close();
});
test('DND legacy-state toggle updates notification status and ring sounds do not replay on session changes',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');localStorage.setItem('alpha.browser.device.v1',JSON.stringify({music:70}));const d=registerPlugin<any>('AlphaDevice');await d.setSensor({field:'doNotDisturb'});return registerPlugin<any>('AlphaNotifications').status();});expect(result.interruption).toBe('none');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,apps:[{packageName:'browser.mail',preview:true}]});await n.inject({packageName:'browser.mail',title:'Notice',text:'Receipt test'});});await page.clock.setFixedTime(new Date('2027-06-01T06:00:02Z'));await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.alert-sounds.v1')||'{"seen":[]}').seen.length)).toBe(1);const before=await page.evaluate(()=>localStorage.getItem('alpha.browser.alert-sounds.v1'));await page.reload();await page.waitForTimeout(1200);expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.alert-sounds.v1'))).toBe(before);
});
test('dismissing a recurring alarm preserves the schedule and advances its occurrence',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DailyApps').scheduleReminder({id:'alarm_daily',title:'Daily alarm',at:Date.parse('2027-06-01T06:01Z'),recurrence:{rule:'daily',zone:'UTC',date:'2027-06-01',time:'06:01',leadMinutes:0}});});await page.clock.setFixedTime(new Date('2027-06-01T06:02Z'));const d=page.getByRole('dialog',{name:'Clock alarms',exact:true});await d.getByRole('button',{name:'Dismiss Daily alarm',exact:true}).click();await expect(d.getByText('Ringing',{exact:true})).toHaveCount(0);const row=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('DailyApps').listReminders()).reminders.find((r:any)=>r.id==='alarm_daily');});expect(row.status).toBe('scheduled');expect(row.at).toBe(Date.parse('2027-06-02T06:01Z'));expect(row.history).toHaveLength(1);
});
