import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{page.on('filechooser',()=>{});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('file chooser cancellation removes its input and a later chooser imports exact bytes',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');(window as any).pick=registerPlugin<any>('DailyApps').perform({action:'files'});});await page.locator('input[type=file]').dispatchEvent('cancel');expect(await page.evaluate(()=>(window as any).pick)).toMatchObject({status:'cancelled'});await expect(page.locator('input[type=file]')).toHaveCount(0);
 const chooser=page.waitForEvent('filechooser');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');(window as any).pick=registerPlugin<any>('DailyApps').perform({action:'files'});});await (await chooser).setFiles({name:'chosen.txt',mimeType:'text/plain',buffer:Buffer.from('Exact picked bytes')});const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const chosen=await (window as any).pick,files=registerPlugin<any>('AlphaFiles'),read=await files.readSelected(chosen);await files.forgetSelected(chosen);let revoked=false;try{await files.readSelected(chosen);}catch{revoked=true;}return {text:read.text,revoked};});expect(result).toEqual({text:'Exact picked bytes',revoked:true});
});
test('device retirement cancels the chooser and ignores its detached late change',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');const pending=files.pick();while(!document.querySelector('input[type=file]'))await new Promise(resolve=>setTimeout(resolve,0));const input=document.querySelector('input[type=file]') as HTMLInputElement;window.dispatchEvent(new Event('alpha:device-state'));const result=await pending;const transfer=new DataTransfer();transfer.items.add(new File(['late'],'late.txt',{type:'text/plain'}));input.files=transfer.files;input.dispatchEvent(new Event('change'));await new Promise(resolve=>setTimeout(resolve,30));return {result,inputs:document.querySelectorAll('input[type=file]').length,entries:(await files.list({})).entries};});expect(result).toMatchObject({result:{status:'cancelled'},inputs:0,entries:[]});
});
test('retiring a pending directory handle ignores a late grant without importing',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');let grant:any;(window as any).showDirectoryPicker=()=>new Promise(resolve=>grant=resolve);const files=registerPlugin<any>('AlphaFiles'),pending=files.importFolder();while(!grant)await new Promise(resolve=>setTimeout(resolve,0));window.dispatchEvent(new Event('alpha-back',{cancelable:true}));const cancelled=await pending;grant({name:'Late folder',async *values(){yield {kind:'file',name:'late.txt',getFile:async()=>new File(['late'],'late.txt')};}});await new Promise(resolve=>setTimeout(resolve,30));return {cancelled,entries:(await files.list({})).entries};});expect(result).toEqual({cancelled:{status:'cancelled'},entries:[]});
});
test('a replacement picker retires the old picker and directory read failures are atomic',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles'),first=files.pick();await Promise.resolve();const second=files.pick(true);await Promise.resolve();const cancelled=await first;const input=document.querySelector('input[type=file]') as HTMLInputElement;const accept=input.accept;input.dispatchEvent(new Event('cancel'));const cancelledSecond=await second;(window as any).showDirectoryPicker=async()=>({name:'Denied',async *values(){yield {kind:'file',name:'one.txt',getFile:async()=>new File(['one'],'one.txt')};yield {kind:'file',name:'two.txt',getFile:async()=>{throw new DOMException('Permission revoked','NotAllowedError');}};}});let rejected=false;try{await files.importFolder();}catch{rejected=true;}return {cancelled,cancelledSecond,accept,rejected,entries:(await files.list({})).entries};});expect(result).toMatchObject({cancelled:{status:'cancelled',action:'files'},cancelledSecond:{status:'cancelled',action:'photos'},accept:'image/*,video/*',rejected:true,entries:[]});
});
for(const supported of [true,false])test(`Inbox attachment consumer releases its selected-file capability (${supported?'accepted':'rejected'})`,async({page})=>{
 await page.evaluate(async()=>{const {inboxDrafts}=await import('/src/prototype/inbox-drafts.ts'),{connectionController}=await import('/src/runtime/connection-ui.tsx'),{secureConnectionStore}=await import('/src/runtime/native-connection.ts');const snapshot=connectionController.getSnapshot,client=connectionController.getCloudClient,read=secureConnectionStore.read;
 connectionController.getSnapshot=()=>({cloudAccount:{environment:'fixture',userId:'local',sessionId:'fixture'}} as any);connectionController.getCloudClient=()=>({sessionId:'fixture'} as any);secureConnectionStore.read=async()=>null;
 const draft=inboxDrafts(()=>{},()=>{});try{await draft.bind('local-account','Local fixture');draft.begin();}finally{connectionController.getSnapshot=snapshot;connectionController.getCloudClient=client;secureConnectionStore.read=read;}
 const original=URL.revokeObjectURL;(window as any).revoked=[];URL.revokeObjectURL=function(url){(window as any).revoked.push(url);original.call(URL,url);};(window as any).draft=draft;});
 const chooser=page.waitForEvent('filechooser');await page.evaluate(()=>(window as any).draft.render().c.attach());await (await chooser).setFiles({name:supported?'attachment.txt':'attachment.exe',mimeType:supported?'text/plain':'application/octet-stream',buffer:Buffer.from('Attachment bytes')});
 await expect.poll(()=>page.evaluate(()=>(window as any).draft.render().c.busy)).toBe(false);expect(await page.evaluate(()=>(window as any).draft.render().c.hasAtts)).toBe(supported);expect(await page.evaluate(()=>(window as any).revoked.length)).toBe(1);
});
