import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:navigator.mediaDevices});});await page.goto('/?mode=dev');});
test('Calendar attendees and video option persist through rendered creation, editing and reload',async({page},testInfo)=>{
 await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Team meeting');await page.getByRole('switch',{name:'Video link',exact:true}).click();await page.getByRole('button',{name:'Add people',exact:true}).click();await page.getByRole('textbox',{name:'Name or email',exact:true}).fill('Maya');await page.getByRole('button',{name:/^Add Maya/}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Join',exact:true})).toBeVisible();const before=await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0]);expect(before.video).toBe(true);expect(before.who).toHaveLength(1);await page.getByRole('button',{name:'Edit event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Renamed meeting');await page.getByRole('button',{name:'Save event',exact:true}).click();await expect.poll(()=>page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].title)).toBe('Renamed meeting');await expect(page.getByRole('button',{name:'Join',exact:true})).toBeVisible();await page.reload();await page.evaluate(async(id)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').open({id});},before.id);await page.getByRole('button',{name:'Join',exact:true}).click();const room=page.getByRole('dialog',{name:'Calendar meeting'});await expect(room).toContainText('Renamed meeting');await expect(room).toContainText('Maya');await page.screenshot({path:testInfo.outputPath('calendar-meeting.png')});await room.getByRole('button',{name:'Leave meeting',exact:true}).click();expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].who)).toEqual(before.who);
});
async function meeting(page:any){await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),result=await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'Preview meeting',body:'',location:'',begin:Date.now()+3600000,end:Date.now()+7200000,video:true});const row=JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0];await cal.joinMeeting({id:result.id,revision:row.revision});});}
test('meeting preview acquires media only on request and releases both sensors on leave',async({page})=>{
 await page.evaluate(()=>{const w=window as any;w.meetingStreams=[];w.mediaRequests=[];navigator.mediaDevices.getUserMedia=async constraints=>{w.mediaRequests.push(constraints);const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;canvas.getContext('2d')!.fillRect(0,0,100,100);const stream=constraints.video?canvas.captureStream():new AudioContext().createMediaStreamDestination().stream;w.meetingStreams.push(stream);return stream;};});await meeting(page);expect(await page.evaluate(()=>(window as any).mediaRequests)).toEqual([]);const room=page.getByRole('dialog',{name:'Calendar meeting'});await room.getByRole('button',{name:'Turn camera on',exact:true}).click();await expect(room.getByRole('button',{name:'Turn camera off',exact:true})).toBeVisible();await room.getByRole('button',{name:'Unmute microphone',exact:true}).click();await expect(room.getByRole('button',{name:'Mute microphone',exact:true})).toBeVisible();await room.getByRole('button',{name:'Leave meeting',exact:true}).click();expect(await page.evaluate(()=>(window as any).meetingStreams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);
});
test('late camera permission after leaving releases the granted stream',async({page})=>{
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{(window as any).grantMeetingCamera=()=>{const canvas=document.createElement('canvas');const stream=canvas.captureStream();(window as any).lateMeetingStream=stream;resolve(stream);};});});await meeting(page);const room=page.getByRole('dialog',{name:'Calendar meeting'});await room.getByRole('button',{name:'Turn camera on',exact:true}).click();await room.getByRole('button',{name:'Leave meeting',exact:true}).click();await page.evaluate(()=>(window as any).grantMeetingCamera());await expect.poll(()=>page.evaluate(()=>(window as any).lateMeetingStream.getTracks().every((t:MediaStreamTrack)=>t.readyState==='ended'))).toBe(true);await expect(room).toHaveCount(0);
});
test('denied meeting sensors retain a usable room and retry controls',async({page})=>{
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await meeting(page);const room=page.getByRole('dialog',{name:'Calendar meeting'});await room.getByRole('button',{name:'Turn camera on',exact:true}).click();await expect(room.getByRole('status')).toHaveText('Camera could not start. Try again.');await expect(room.getByRole('button',{name:'Turn camera on',exact:true})).toBeEnabled();await room.getByRole('button',{name:'Unmute microphone',exact:true}).click();await expect(room.getByRole('status')).toHaveText('Microphone could not start. Try again.');await expect(room.getByRole('button',{name:'Unmute microphone',exact:true})).toBeEnabled();await room.getByRole('button',{name:'Leave meeting',exact:true}).click();await expect(room).toHaveCount(0);
});
