import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('text size affects computed typography, persists after reload and scales new content without compounding',async({page})=>{
 const font=()=>page.getByRole('button',{name:'Settings',exact:true}).evaluate(el=>getComputedStyle(el.querySelector('span')||el).fontSize);
 const initial=await font();await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setTextScale({percent:150});});await expect.poll(font).toBe(parseFloat(initial)*1.5+'px');await page.reload();await expect.poll(font).toBe(parseFloat(initial)*1.5+'px');
 const dynamic=await page.evaluate(async()=>{const node=document.createElement('div');node.style.fontSize='20px';node.textContent='New content';document.body.append(node);await new Promise(resolve=>requestAnimationFrame(resolve));const first=getComputedStyle(node).fontSize;node.style.color='red';await new Promise(resolve=>requestAnimationFrame(resolve));const second=getComputedStyle(node).fontSize;node.remove();return {first,second};});expect(dynamic).toEqual({first:'30px',second:'30px'});
});
test('shade brightness and device display settings share a durable visible value and Back closes settings',async({page})=>{
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Notifications',exact:true}).click();const slider=page.getByRole('slider',{name:'Brightness',exact:true});await slider.fill('50');await expect.poll(()=>page.locator('.os').evaluate(el=>getComputedStyle(el).filter)).toBe('brightness(0.6)');await page.reload();await expect.poll(()=>page.locator('.os').evaluate(el=>getComputedStyle(el).filter)).toBe('brightness(0.6)');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').openSettings({page:'display'});});const dialog=page.getByRole('dialog',{name:'display settings'});await expect(dialog.getByRole('slider',{name:'brightness',exact:true})).toHaveValue('50');await dialog.getByRole('slider',{name:'brightness',exact:true}).fill('100');await expect.poll(()=>page.locator('.os').evaluate(el=>getComputedStyle(el).filter)).toBe('brightness(1)');await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(dialog).toHaveCount(0);
});
test('failed display persistence leaves the visual value unchanged',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const device=registerPlugin<any>('AlphaDevice');const before=getComputedStyle(document.querySelector('.os')!).filter;const save=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.device.v1')throw Error('Full');return save.call(this,key,value);};let failed=false;try{await device.setBrightness({percent:10});}catch{failed=true;}finally{Storage.prototype.setItem=save;}return {failed,before,after:getComputedStyle(document.querySelector('.os')!).filter};});expect(result.failed).toBe(true);expect(result.after).toBe(result.before);
});
test('device permission facts reflect browser grants without requesting access',async({page,context})=>{
 await context.grantPermissions(['geolocation']);const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const snapshot=await registerPlugin<any>('AlphaDevice').snapshot();const actual=await navigator.permissions.query({name:'camera' as PermissionName});return {snapshot,camera:actual.state};});expect(result.snapshot.permissionStates.Location).toBe('granted');expect(result.snapshot.permissions.Location).toBe(true);expect(result.snapshot.permissionStates.Camera).toBe(result.camera);expect(result.snapshot.permissions.Camera).toBe(result.camera==='granted');
});
test('rendered Display slider changes text size while its controls remain usable',async({page},info)=>{
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Display',exact:true}).click();const slider=page.getByRole('slider');await slider.fill('100');await expect.poll(()=>page.evaluate(()=>document.documentElement.style.getPropertyValue('--browser-text-scale'))).toBe('1.5');await expect(slider).toBeVisible();await expect(page.getByText('150%',{exact:true})).toBeVisible();await page.waitForFunction(()=>document.getAnimations().every(animation=>animation.effect?.getTiming().iterations===Infinity||animation.playState==='finished'));await page.screenshot({path:info.outputPath('display-large-text.png')});await slider.fill('0');await expect.poll(()=>page.evaluate(()=>document.documentElement.style.getPropertyValue('--browser-text-scale'))).toBe('0.75');
});
test('display changes in another tab update the current rendered device',async({page,context})=>{
 const other=await context.newPage();await other.goto(page.url());await other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const device=registerPlugin<any>('AlphaDevice');await device.setBrightness({percent:25});await device.setTextScale({percent:125});});await expect.poll(()=>page.locator('.os').evaluate(el=>getComputedStyle(el).filter)).toBe('brightness(0.4)');await expect.poll(()=>page.evaluate(()=>document.documentElement.style.getPropertyValue('--browser-text-scale'))).toBe('1.25');await other.close();
});
test('settings dialog rolls its control back when storage rejects a change',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').openSettings({page:'display'});(window as any).originalDisplaySave=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.device.v1')throw Error('Full');return (window as any).originalDisplaySave.call(this,key,value);};});const dialog=page.getByRole('dialog',{name:'display settings'});await dialog.getByRole('slider',{name:'brightness',exact:true}).fill('25');await expect(dialog.getByRole('status')).toContainText('could not be saved');await expect(dialog.getByRole('slider',{name:'brightness',exact:true})).toHaveValue('100');await page.evaluate(()=>{Storage.prototype.setItem=(window as any).originalDisplaySave;});
});
