import {test,expect,type Page} from '@playwright/test';
async function seed(page:Page){await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:navigator.mediaDevices});});await page.goto('/?mode=dev');return page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'Local test room',body:'',location:'',begin:Date.now()+3600000,end:Date.now()+7200000,who:['maya'],video:true});return JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0];});}
async function media(page:Page){await page.evaluate(()=>{const w=window as any;w.roomStreams=[];navigator.mediaDevices.getUserMedia=async c=>{const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;canvas.getContext('2d')!.fillRect(0,0,100,100);const s=c.video?canvas.captureStream():new AudioContext().createMediaStreamDestination().stream;w.roomStreams.push(s);return s;};});}
async function join(page:Page,row:any){await page.evaluate(async row=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').joinMeeting({id:row.id,revision:row.revision});},row);return page.getByRole('dialog',{name:'Calendar meeting'});}
for(const action of ['back','background'] as const)test(`meeting ${action} retires owned media and discloses the local-only preview`,async({page})=>{
 const row=await seed(page);await media(page);const room=await join(page,row);await expect(room).toContainText('Other people are not connected');await room.getByRole('button',{name:'Turn camera on',exact:true}).click();await room.getByRole('button',{name:'Unmute microphone',exact:true}).click();await expect(room.getByRole('button',{name:'Mute microphone',exact:true})).toBeVisible();await page.evaluate(action=>{if(action==='back')window.dispatchEvent(new Event('alpha-back',{cancelable:true}));else{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));}},action);await expect(room).toHaveCount(0);expect(await page.evaluate(()=>(window as any).roomStreams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);
});
test('ended camera and microphone tracks reset their controls and allow a fresh request',async({page})=>{
 const row=await seed(page);await media(page);const room=await join(page,row);await room.getByRole('button',{name:'Turn camera on',exact:true}).click();await expect(room.getByRole('button',{name:'Turn camera off',exact:true})).toBeVisible();await room.getByRole('button',{name:'Unmute microphone',exact:true}).click();await expect(room.getByRole('button',{name:'Mute microphone',exact:true})).toBeVisible();
 await page.evaluate(()=>{for(const s of (window as any).roomStreams)for(const t of s.getTracks()){t.stop();t.dispatchEvent(new Event('ended'));}});await expect(room.getByRole('button',{name:'Turn camera on',exact:true})).toBeEnabled();await expect(room.getByRole('button',{name:'Unmute microphone',exact:true})).toBeEnabled();await room.getByRole('button',{name:'Turn camera on',exact:true}).click();await expect(room.getByRole('button',{name:'Turn camera off',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).roomStreams.length)).toBe(3);await room.getByRole('button',{name:'Leave meeting',exact:true}).click();
});
test('local guest response commits only after Save and rejects a stale guest list',async({page})=>{
 const row=await seed(page);const open=async()=>page.evaluate(async row=>{const {registerPlugin}=await import('/src/platform-plugins.ts');(window as any).guestEdit=registerPlugin<any>('AlphaCalendar').editResponse({id:row.id,revision:row.revision,person:'maya',name:'Maya'});},row);await open();const dialog=page.getByRole('dialog',{name:'Local guest response'});await expect(dialog).toContainText('No invitation or response is sent');await dialog.getByLabel('Guest response',{exact:true}).selectOption('yes');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).guestEdit)).toEqual({status:'cancelled'});expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].responses)).toBeUndefined();
 await open();await dialog.getByLabel('Guest response',{exact:true}).selectOption('maybe');await page.evaluate(()=>{const key='alpha.browser.calendar.v1',data=JSON.parse(localStorage.getItem(key)!);data.events[0].revision='c'.repeat(64);localStorage.setItem(key,JSON.stringify(data));});await dialog.getByRole('button',{name:'Save response',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('changed');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();row.revision='c'.repeat(64);
 await open();await dialog.getByLabel('Guest response',{exact:true}).selectOption('yes');await dialog.getByRole('button',{name:'Save response',exact:true}).click();expect(await page.evaluate(()=>(window as any).guestEdit)).toEqual({status:'saved'});await page.reload();expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].responses)).toEqual({maya:'yes'});
});
