import {test,expect} from '@playwright/test';
for(const width of [360,601])for(const theme of ['light','dark'])for(const scale of [100,150])test(`device tools remain readable and reachable: ${theme} ${scale}% ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:640});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&theme=&tools=1'+theme);
 await page.evaluate(async percent=>{const {BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent});},scale);
 const opener=page.getByRole('button',{name:'Device controls',exact:true});await expect(page.getByText('Dev data',{exact:true})).toBeVisible();const box=await opener.boundingBox();const phone=await page.locator('.alpha-phone>[data-screen]').boundingBox(),toolbar=await page.locator('.alpha-dev-tools').boundingBox();expect(phone!.y+phone!.height).toBeLessThanOrEqual(toolbar!.y+.5);expect(box!.width).toBeGreaterThanOrEqual(44);expect(box!.height).toBeGreaterThanOrEqual(44);await expect(opener).toHaveCSS('color','rgb(255, 255, 255)');await expect(page.locator('.alpha-dev-tools')).toHaveCSS('background-color','rgb(0, 0, 255)');
 // The sole launcher must not cover the phone's Home navigation target.
 await page.getByRole('button',{name:'Notes',exact:true}).click();const home=page.getByRole('button',{name:'Home',exact:true});expect(await home.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);await home.click();await page.screenshot({path:info.outputPath('launcher.png')});
 await opener.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Development device controls'});await expect(dialog).toBeVisible();await expect(dialog).toHaveCSS('background-color',theme==='dark'?'rgb(0, 0, 0)':'rgb(255, 255, 255)');await expect(dialog).toHaveCSS('color',theme==='dark'?'rgb(255, 255, 255)':'rgb(0, 0, 0)');
 const bounds=await dialog.boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.y).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(width);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(640);
 for(const button of await dialog.getByRole('button').all()){await button.scrollIntoViewIfNeeded();const r=await button.boundingBox();expect(Math.round(r!.height*100)/100).toBeGreaterThanOrEqual(44);expect(await button.evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);}
 const close=dialog.getByRole('button',{name:'Close device controls'});expect(await close.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);
 await dialog.evaluate(el=>el.scrollTop=0);await page.screenshot({path:info.outputPath('tools.png')});await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(opener).toBeFocused();
});
test('device tools switch profiles and keep role-storage failures actionable',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?theme=dark&tools=1');await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Use development profile',exact:true}).click();await expect(page).toHaveURL(/mode=dev/);const opener=page.getByRole('button',{name:'Device controls',exact:true});await expect(page.getByText('Dev data',{exact:true})).toBeVisible();await opener.click();const dialog=page.getByRole('dialog',{name:'Development device controls'});
 await page.evaluate(()=>{const set=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(v,k){if(k==='alpha.browser.roles.v1')throw new DOMException('Full','QuotaExceededError');return set.call(this,v,k);};});await dialog.getByRole('button',{name:'Use as home',exact:true}).click();await expect(dialog.getByRole('status')).toHaveText('Role could not be saved. Try again.');await expect(dialog.getByRole('button',{name:'Use as home',exact:true})).toBeEnabled();
 await dialog.getByRole('button',{name:'Use app profile',exact:true}).click();await expect(page).not.toHaveURL(/mode=dev/);await expect(page.getByText('Tools',{exact:true})).toBeVisible();await expect(page.locator('.alpha-dev-tools')).toHaveCSS('background-color','rgb(255, 255, 255)');await expect(page.locator('.alpha-dev-tools')).toHaveCSS('color','rgb(17, 17, 17)');
});

test('toolbar clearance follows its bottom inset after resize and stays absent from mock mode',async({page})=>{
 await page.setViewportSize({width:360,height:640});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&tools=1');await page.addStyleTag({content:'.alpha-dev-tools{bottom:34px}'});await page.setViewportSize({width:360,height:641});
 await expect.poll(()=>page.evaluate(()=>{const phone=document.querySelector('.alpha-phone>[data-screen]')!.getBoundingClientRect(),tools=document.querySelector('.alpha-dev-tools')!.getBoundingClientRect();return tools.top-phone.bottom;})).toBeGreaterThanOrEqual(1);
 await page.goto('/?mode=mock&tools=1');await expect(page.locator('.alpha-dev-tools')).toHaveCount(0);
});
