import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-10-02T12:00:00Z'));await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
async function range(page:any){return page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaCalendar').list({begin:Date.parse('2026-10-02T00:00:00Z'),end:Date.parse('2026-10-05T00:00:00Z')});});}
test('rendered daily series creates, edits and deletes one occurrence while retaining the others',async({page})=>{
 await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Daily planning');await page.getByRole('button',{name:'Daily',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Edit event',exact:true})).toBeVisible();const initial=(await range(page)).events;expect(initial).toHaveLength(3);expect(new Set(initial.map((r:any)=>r.id)).size).toBe(3);await page.getByRole('button',{name:'Edit event',exact:true}).click();const editor=page.getByRole('dialog',{name:'Edit calendar event'});await editor.getByLabel('Event title',{exact:true}).fill('Only this date');await editor.getByRole('button',{name:'Save event',exact:true}).click();await expect(editor).toHaveCount(0);const edited=(await range(page)).events;expect(edited.map((r:any)=>r.title)).toEqual(['Only this date','Daily planning','Daily planning']);expect(edited[0].id).toBe(initial[0].id);await page.evaluate(async(id)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').open({id});},edited[0].id);await page.getByRole('button',{name:'Delete event',exact:true}).click();await expect.poll(async()=>(await range(page)).events.length).toBe(2);await page.reload();expect((await range(page)).events.map((r:any)=>r.id)).toEqual(initial.slice(1).map((r:any)=>r.id));
});
test('selected occurrence agent mutation and replay keep exact identity and leave sibling dates unchanged',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');await cal.save({calendarId:'local',title:'Series',body:'',location:'',begin:Date.parse('2026-10-02T12:00:00Z'),end:Date.parse('2026-10-02T13:00:00Z'),timeZone:'UTC',repeat:'daily'});});const initial=(await range(page)).events;await page.evaluate(async(row)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),source=await cal.prepareAgentSource();const operation={type:'calendar_update',target:{sourceId:source.sourceId,sourceRevision:source.sourceRevision,eventId:row.id,revision:row.revision},fields:{title:'Agent changed occurrence',description:'',location:'',start:new Date(row.begin+3600000).toISOString(),end:new Date(row.end+3600000).toISOString(),timeZone:'UTC'}};(window as any).seriesRequest={operation,operationId:'occurrence-update'};(window as any).seriesPending=cal.executeAgent((window as any).seriesRequest);},initial[1]);await page.getByRole('dialog',{name:'Review calendar change'}).getByRole('button',{name:'Confirm',exact:true}).click();const result=await page.evaluate(()=>(window as any).seriesPending);expect(result.status).toBe('applied');expect(result.result.eventId).toBe(initial[1].id);const after=(await range(page)).events;expect(after.map((r:any)=>r.title)).toEqual(['Series','Agent changed occurrence','Series']);expect(after[1].begin).toBe(initial[1].begin+3600000);expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaCalendar').executeAgent((window as any).seriesRequest);})).toEqual(result);expect((await range(page)).events).toEqual(after);
});
test('whole-series editing and deletion require explicit scope and preserve cancellation',async({page})=>{
 const id=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');const result=await cal.save({calendarId:'local',title:'Weekly review',body:'',location:'',begin:Date.parse('2026-10-02T12:00:00Z'),end:Date.parse('2026-10-02T13:00:00Z'),timeZone:'UTC',repeat:'daily'});await cal.open({id:result.id});return result.id;});await page.getByRole('button',{name:'Edit series',exact:true}).click();await page.getByRole('dialog',{name:'Edit repeating series'}).getByRole('button',{name:'Confirm',exact:true}).click();const editor=page.getByRole('dialog',{name:'Edit calendar event'});await editor.getByLabel('Event title',{exact:true}).fill('Whole series renamed');await editor.getByLabel('Repeat',{exact:true}).selectOption('weekly');await editor.getByRole('button',{name:'Save event',exact:true}).click();await expect(editor).toHaveCount(0);const rows=(await range(page)).events;expect(rows).toHaveLength(1);expect(rows[0].title).toBe('Whole series renamed');await page.evaluate(async(id)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').open({id});},id);await page.getByRole('button',{name:'Delete series',exact:true}).click();const review=page.getByRole('dialog',{name:'Delete repeating series'});await review.getByRole('button',{name:'Cancel',exact:true}).click();expect((await range(page)).events).toHaveLength(1);await page.getByRole('button',{name:'Delete series',exact:true}).click();await review.getByRole('button',{name:'Confirm',exact:true}).click();await expect.poll(async()=>(await range(page)).events.length).toBe(0);await page.reload();expect((await range(page)).events).toEqual([]);
});
test('series review detects concurrent occurrence edits and failed writes preserve the schedule',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');await cal.save({calendarId:'local',title:'Protected series',body:'',location:'',begin:Date.parse('2026-10-02T12:00:00Z'),end:Date.parse('2026-10-02T13:00:00Z'),repeat:'daily',timeZone:'UTC'});const rows=(await cal.list({begin:Date.parse('2026-10-02T00:00:00Z'),end:Date.parse('2026-10-05T00:00:00Z')})).events;(window as any).protectedRows=rows;(window as any).removeSeries=cal.removeSeries({id:rows[0].id,revision:rows[0].revision});});await expect(page.getByRole('dialog',{name:'Delete repeating series'})).toBeVisible();await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),row=(window as any).protectedRows[1];await cal.save({...row,expected:row,title:'Changed during review'});});await page.getByRole('dialog',{name:'Delete repeating series'}).getByRole('button',{name:'Confirm',exact:true}).click();expect(await page.evaluate(()=>(window as any).removeSeries)).toEqual({status:'conflict'});expect((await range(page)).events).toHaveLength(3);const preserved=await page.evaluate(()=>localStorage.getItem('alpha.browser.calendar.v1'));expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),row=(await cal.list({begin:Date.parse('2026-10-02T00:00:00Z'),end:Date.parse('2026-10-05T00:00:00Z')})).events[0],original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.calendar.v1')throw Error('Full');return original.call(this,key,value);};try{await cal.remove({...row,expected:row,revision:row.revision});return false;}catch{return true;}finally{Storage.prototype.setItem=original;}})).toBe(true);expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.calendar.v1'))).toBe(preserved);
});
test('moving the whole series keeps deleted dates and edited occurrences excluded from regeneration',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');await cal.save({calendarId:'local',title:'Schedule',body:'',location:'',begin:Date.parse('2026-10-02T12:00:00Z'),end:Date.parse('2026-10-02T13:00:00Z'),repeat:'daily',timeZone:'UTC'});let rows=(await cal.list({begin:Date.parse('2026-10-02T00:00:00Z'),end:Date.parse('2026-10-05T00:00:00Z')})).events;await cal.save({...rows[1],expected:rows[1],title:'Special occurrence'});rows=(await cal.list({begin:Date.parse('2026-10-02T00:00:00Z'),end:Date.parse('2026-10-05T00:00:00Z')})).events;await cal.remove({...rows[2],expected:rows[2]});rows=(await cal.list({begin:Date.parse('2026-10-02T00:00:00Z'),end:Date.parse('2026-10-05T00:00:00Z')})).events;(window as any).seriesEdit=cal.editSeries({id:rows[0].id,revision:rows[0].revision});});await page.getByRole('dialog',{name:'Edit repeating series'}).getByRole('button',{name:'Confirm',exact:true}).click();const editor=page.getByRole('dialog',{name:'Edit calendar event'});await editor.getByLabel('Starts',{exact:true}).fill('2026-10-02T14:00');await editor.getByLabel('Ends',{exact:true}).fill('2026-10-02T15:00');await editor.getByRole('button',{name:'Save event',exact:true}).click();expect(await page.evaluate(()=>(window as any).seriesEdit)).toEqual({status:'saved'});const events=(await range(page)).events;expect(events.map((r:any)=>r.title)).toEqual(['Schedule','Special occurrence']);expect(events.map((r:any)=>new Date(r.begin).toISOString())).toEqual(['2026-10-02T14:00:00.000Z','2026-10-03T12:00:00.000Z']);
});
test('overlapping multi-day occurrences resolve the selected date rather than an earlier sibling',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');await cal.save({calendarId:'local',title:'Three-day series',body:'',location:'',begin:Date.parse('2026-10-01T12:00:00Z'),end:Date.parse('2026-10-04T12:00:00Z'),repeat:'daily',timeZone:'UTC'});const row=(await cal.list({begin:Date.parse('2026-10-03T12:00:00Z'),end:Date.parse('2026-10-03T13:00:00Z')})).events.find((r:any)=>r.begin===Date.parse('2026-10-03T12:00:00Z'));const inspect=await cal.inspect({id:row.id,calendarId:'local',expected:row});const save=await cal.save({...row,expected:row,title:'Exact overlapping date'});return {inspect,save};});expect(result.inspect.status).toBe('ready');expect(result.save.status).toBe('saved');expect((await range(page)).events.filter((r:any)=>r.title==='Exact overlapping date')).toHaveLength(1);
});
