import {test,expect,Page} from '@playwright/test';
const flow={id:901,name:'Local execution',on:true,short:'Local state changes',summary:'Set and clear DND',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']},{k:'Do',t:'Turn off Do Not Disturb',apps:['Settings']}],runs:[]};
async function open(page:Page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Local execution',{exact:true}).click();}
const journal=(page:Page)=>page.evaluate(async()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]);
test.beforeEach(async({page})=>{await page.addInitScript(flow=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.dev.app.workflows'))localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[flow],localRuns:{}}));},flow);await page.goto('/?mode=dev');await open(page);});
test('local run changes the device and persists its actual step outputs after reload',async({page})=>{
 await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');const runs=await journal(page);expect(runs).toHaveLength(1);expect(runs[0].cursor).toBe(2);expect(runs[0].log.map((r:any)=>r[1])).toEqual(['Do Not Disturb on','Do Not Disturb off']);expect(await page.evaluate(async()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')!).doNotDisturb)).toBe(false);await page.reload();await open(page);expect(await journal(page)).toEqual(runs);
});
async function hold(page:Page){await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');const original=BrowserDevice.prototype.setSensor;let release:()=>void;const gate=new Promise<void>(resolve=>release=resolve);(window as any).releaseStep=()=>release();BrowserDevice.prototype.setSensor=async function(input:any){const result=await original.call(this,input);(window as any).stepApplied=true;await gate;return result;};});}
test('cancel during a held step preserves its effect and prevents later steps',async({page})=>{
 await hold(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(async()=>(window as any).stepApplied)).toBe(true);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await page.evaluate(async()=>(window as any).releaseStep());await expect.poll(async()=>(await journal(page))[0]?.status).toBe('cancelled');expect((await journal(page))[0].cursor).toBe(1);expect(await page.evaluate(async()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')!).doNotDisturb)).toBe(true);
});
test('reload interrupts a held run without replaying or executing the later steps',async({page})=>{
 await hold(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(async()=>(window as any).stepApplied)).toBe(true);await page.reload();await open(page);await expect.poll(async()=>(await journal(page))[0]?.status).toBe('interrupted');expect((await journal(page))[0].inflight).toBe(0);expect(await page.evaluate(async()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')!).doNotDisturb)).toBe(true);await expect(page.getByRole('button',{name:'Run now',exact:true})).toBeVisible();
});
test('action failure records a failed run with no invented completed step',async({page})=>{
 await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');BrowserDevice.prototype.setSensor=async()=>{throw Error('Device write failed');};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');const run=(await journal(page))[0];expect(run.log).toEqual([]);expect(run.cursor).toBe(0);expect(run.sum).toContain('Device write failed');
});
test('Run again from run history uses the executor and creates another durable receipt',async({page})=>{
 await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');await page.getByRole('button',{name:/, ok$/}).click();await page.getByRole('button',{name:'Run again',exact:true}).click();await expect.poll(async()=>(await journal(page)).filter(run=>run.status==='ok').length).toBe(2);expect((await journal(page)).every(run=>run.cursor===2)).toBe(true);
});
test('a false evaluated condition skips subsequent device effects',async({page})=>{
 await page.evaluate(async()=>{const state=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);state.flows[0].steps=[{k:'Read',t:"Today's calendar",apps:['Calendar']},{k:'If',t:'It mentions money',apps:[]},{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(state));});await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('skip');expect((await journal(page))[0].cursor).toBe(2);expect(await page.evaluate(async()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')||'{}').doNotDisturb||false)).toBe(false);
});
test('failure to save run intent prevents any device effect',async({page})=>{
 await page.evaluate(async()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.workflows')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect(page.getByRole('status',{name:'Workflow run status',exact:true})).toHaveText('Run state could not be saved. Reload to inspect its last saved step.');expect(await journal(page)).toEqual([]);expect(await page.evaluate(async()=>localStorage.getItem('alpha.browser.device.v1'))).toBeNull();
});

test('summary step cannot report success from a truncated input',async({page})=>{
 await page.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Write',t:'A short summary',apps:[]}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));});
 await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Workflow step result'})).toBeVisible();expect((await journal(page))[0].status).toBe('running');expect((await journal(page))[0].cursor).toBe(0);expect((await journal(page))[0].log).toEqual([]);await page.getByRole('dialog',{name:'Workflow step result'}).getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('cancelled');
});

for(const source of ['Calendar next 90 years','Unsupported mailbox'])test('unsupported read does not silently widen or narrow '+source,async({page})=>{
 await page.evaluate(source=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Read',t:source,apps:[]}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));},source);
 await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');expect((await journal(page))[0].cursor).toBe(0);expect((await journal(page))[0].sum).toContain('not supported');
});

async function sendFlow(page:Page){await page.evaluate(async()=>{const state=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);state.flows[0].steps=[{k:'Read',t:'Contacts',apps:['Contacts']},{k:'Send',t:'A message to Maya',apps:['Messages']},{k:'Send',t:'An email to me',apps:['Mail']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(state));});await page.reload();await open(page);}
test('workflow sends actual local message and email copies with replay-bound receipts',async({page})=>{
 await sendFlow(page);const requests:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))requests.push(r.url());});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');const run=(await journal(page))[0];expect(run.cursor).toBe(3);const result=await page.evaluate(async id=>{const msg=JSON.parse(localStorage.getItem('alpha.dev.app.messages')!).threads.maya.find((m:any)=>m.id===id+'-1');const mail=JSON.parse(localStorage.getItem('alpha.dev.app.inbox')!).sent.find((m:any)=>m.id===id+'-2');return {msg,mail};},run.id);expect(result.msg.text).toBe(run.out);expect(result.mail.body).toBe(run.out);expect(result.mail.to).toEqual(['you@alpha.local']);
 const replay=await page.evaluate(async({id,text})=>{const {sendWorkflowLocal}=await import('/src/browser/workflow-local-send.ts');const api={get:()=>({}),setView:()=>{throw Error('Replay tried to write');}};sendWorkflowLocal({t:'A message to Maya'},text,id+'-1',api,new AbortController().signal);sendWorkflowLocal({t:'An email to me'},text,id+'-2',api,new AbortController().signal);try{sendWorkflowLocal({t:'A message to Maya'},text+' changed',id+'-1',api,new AbortController().signal);return false;}catch{return true;}},{id:run.id,text:run.out});expect(replay).toBe(true);await page.reload();expect(await page.evaluate(async id=>JSON.parse(localStorage.getItem('alpha.dev.app.messages')!).threads.maya.filter((m:any)=>m.id===id+'-1').length,run.id)).toBe(1);expect(requests).toEqual([]);
});
test('failed destination save stops later sends and a fresh run creates only the successful copies',async({page})=>{
 await sendFlow(page);await page.evaluate(async()=>{const set=Storage.prototype.setItem;(window as any).restoreSend=()=>IDBObjectStore.prototype.put=set;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.messages')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');expect((await journal(page))[0].cursor).toBe(1);expect(await page.evaluate(async()=>localStorage.getItem('alpha.dev.app.inbox'))).toBeNull();await page.evaluate(async()=>(window as any).restoreSend());await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page)).filter(r=>r.status==='ok').length).toBe(1);expect(await page.evaluate(async()=>JSON.parse(localStorage.getItem('alpha.dev.app.inbox')!).sent.filter((m:any)=>m.workflowStep).length)).toBe(1);
});
test('journal capacity is reserved before a destination effect',async({page})=>{
 await page.evaluate(async()=>{const state=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);state.localRuns.archive={id:'archive',status:'ok',out:'x'.repeat(1_940_000)};localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(state));});await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page)).find(r=>r.flowId===901)?.status).toBe('fail');expect((await journal(page)).find(r=>r.flowId===901).sum).toContain('Workflow history is full');expect(await page.evaluate(async()=>localStorage.getItem('alpha.browser.device.v1'))).toBeNull();
});

async function noteFlow(page:Page){await page.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Read',t:'Contacts',apps:['Contacts']},{k:'Write',t:'A note in Notes',apps:['Notes']},{k:'Read',t:'Notes',apps:['Notes']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));});await page.reload();await open(page);}
test('workflow saves a real Notes record and reads it after reload',async({page})=>{
 await noteFlow(page);await page.evaluate(async()=>{const {Component}=await import('/src/prototype/model.js');const original=Component.prototype.api;Component.prototype.api=function(key:string){const api=original.call(this,key);if(key==='workflows')(window as any).workflowApi=api;return api;};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');const run=(await journal(page))[0];const notes=await page.evaluate(async()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records);const note=notes.find((n:any)=>n.id===run.id+'-1');expect(note.title).toBe('Workflow note');expect(JSON.parse(note.body)).toEqual(expect.any(Array));expect(JSON.parse(run.out)).toContainEqual(note);
 const replay=await page.evaluate(async(note:any)=>{const api=(window as any).workflowApi,signal=new AbortController().signal;const before=localStorage.getItem('alphaphone:notes:v2');const same=await api.localWorkflowNotes({operationId:note.id,text:note.body},signal);let conflict='';try{await api.localWorkflowNotes({operationId:note.id,text:'Changed'},signal);}catch(e){conflict=String(e);}const cancelled=new AbortController();cancelled.abort();let aborted=false;try{await api.localWorkflowNotes({operationId:'cancelled-note',text:'No write'},cancelled.signal);}catch{aborted=true;}return {same,conflict,aborted,unchanged:before===localStorage.getItem('alphaphone:notes:v2')};},note);expect(replay.same).toEqual(note);expect(replay.conflict).toContain('does not match');expect(replay.aborted).toBe(true);expect(replay.unchanged).toBe(true);await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Workflow note',exact:true}).click();await expect(page.getByText(note.body,{exact:true})).toBeVisible();expect(await page.evaluate(async id=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.filter((n:any)=>n.id===id),note.id)).toEqual([note]);
});
test('failed Notes persistence stops workflow without a completed write receipt',async({page})=>{
 await noteFlow(page);await page.evaluate(async()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='alphaphone:notes:v2')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');const run=(await journal(page))[0];expect(run.cursor).toBe(1);expect(run.sum).toContain('unconfirmed');expect(await page.evaluate(async id=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.some((n:any)=>n.id===id+'-1'),run.id)).toBe(false);
});
test('workflow preserves a newer Notes revision from another view',async({page})=>{
 await noteFlow(page);const external=await page.evaluate(async()=>{const key='alphaphone:notes:v2',s=JSON.parse(localStorage.getItem(key)!);s.records.unshift({id:'external-note',title:'Other view',kind:'text',body:'Keep this edit'});const raw=JSON.stringify(s);localStorage.setItem(key,raw);return raw;});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');expect((await journal(page))[0].cursor).toBe(1);expect(await page.evaluate(async()=>localStorage.getItem('alphaphone:notes:v2'))).toBe(external);
});
test('empty workflow input cannot create a blank Notes record',async({page})=>{
 await page.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Write',t:'A note in Notes',apps:['Notes']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));});await page.reload();await open(page);const before=await page.evaluate(async()=>localStorage.getItem('alphaphone:notes:v2'));await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');expect((await journal(page))[0].cursor).toBe(0);expect(await page.evaluate(async()=>localStorage.getItem('alphaphone:notes:v2'))).toBe(before);
});

test('workflow notification is retained, redacted, opened and never duplicated on replay',async({page})=>{
 await page.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']},{k:'Notify',t:'A notification',apps:[]}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));});await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');const run=(await journal(page))[0];
 const result=await page.evaluate(async(id)=>{const {publishWorkflowNotice}=await import('/src/browser/workflow-notices.ts');const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');const before=(await n.list()).items.find((r:any)=>r.id==='workflow:'+id);await publishWorkflowNotice(id,'Do Not Disturb on',new AbortController().signal);let conflict=false;try{await publishWorkflowNotice(id,'Changed',new AbortController().signal);}catch{conflict=true;}document.documentElement.dataset.devBackground='true';const hidden=(await n.list()).items.find((r:any)=>r.id===before.id);let blocked=false;try{await n.open(before);}catch{blocked=true;}delete document.documentElement.dataset.devBackground;return {before,hidden,conflict,blocked,count:(await n.list()).items.filter((r:any)=>r.id===before.id).length};},run.id+'-1');expect(result.before.text).toBe('Do Not Disturb on');expect(result.hidden.text).toBe('');expect(result.hidden.canOpen).toBe(false);expect(result.conflict&&result.blocked).toBe(true);expect(result.count).toBe(1);
 await page.reload();await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.open((await n.list()).items.find((r:any)=>r.id.startsWith('workflow:')));});await expect(page.locator('html')).toHaveAttribute('data-active-view','workflows');
 const after=await page.evaluate(async(id)=>{const {publishWorkflowNotice}=await import('/src/browser/workflow-notices.ts');const {registerPlugin}=await import('/src/platform-plugins.ts');await publishWorkflowNotice(id,'Do Not Disturb on',new AbortController().signal);return (await registerPlugin<any>('AlphaNotifications').list()).items;},run.id+'-1');expect(after.filter((r:any)=>r.id===result.before.id)).toEqual([]);
});
test('cancel while waiting for the notification store lock prevents publication',async({page})=>{
 const result=await page.evaluate(async()=>{const {publishWorkflowNotice}=await import('/src/browser/workflow-notices.ts');let release!:()=>void,acquired!:()=>void;const ready=new Promise<void>(r=>acquired=r);const held=navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1','alpha.browser.workflow-notices.v1']),async()=>{acquired();await new Promise<void>(r=>release=r);});await ready;const abort=new AbortController();const pending=publishWorkflowNotice('cancelled-step','Do not post',abort.signal).then(()=>false,()=>true);abort.abort();release();await held;return {cancelled:await pending,raw:(await (await import('/src/browser/workflow-notices.ts')).workflowNoticesDocument.readRaw())};});expect(result).toEqual({cancelled:true,raw:null});
});
test('workflow result renders in the shade and Clear all persists dismissal',async({page})=>{
 await page.evaluate(async()=>{const {publishWorkflowNotice}=await import('/src/browser/workflow-notices.ts');await publishWorkflowNotice('shade-step','Saved local output',new AbortController().signal);});await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Notifications',exact:true}).click();await expect(page.getByText('Saved local output',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Clear all',exact:true}).click();await expect(page.getByText('Saved local output',{exact:true})).toHaveCount(0);await page.reload();const rows=await page.evaluate(async()=>{const {publishWorkflowNotice}=await import('/src/browser/workflow-notices.ts');const {registerPlugin}=await import('/src/platform-plugins.ts');await publishWorkflowNotice('shade-step','Saved local output',new AbortController().signal);return (await registerPlugin<any>('AlphaNotifications').list()).items;});expect(rows.filter((r:any)=>r.id==='workflow:shade-step')).toEqual([]);
});
test('failed notification persistence leaves no posted receipt',async({page})=>{
 const result=await page.evaluate(async()=>{const {publishWorkflowNotice}=await import('/src/browser/workflow-notices.ts');const set=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(v,k){if(k==='alpha.browser.workflow-notices.v1')throw Error('Full');return set.call(this,v,k);};let failed=false;try{await publishWorkflowNotice('failed-step','Not saved',new AbortController().signal);}catch{failed=true;}finally{IDBObjectStore.prototype.put=set;}return {failed,raw:(await (await import('/src/browser/workflow-notices.ts')).workflowNoticesDocument.readRaw())};});expect(result).toEqual({failed:true,raw:null});
});
