import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('active device events survive reload and are rediscovered after collection changes',async({page})=>{
 const first=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');const posted=await n.inject({packageName:'browser.mail',title:'Retained event',text:'Exact payload',id:'retained'});return {posted,hidden:await n.list(),history:await n.notificationHistory()};});expect(first.posted.collected).toBe(false);expect(first.hidden.items).toEqual([]);expect(first.history.items).toEqual([]);
 await page.reload();const active=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true}]});return (await n.list()).items[0];});expect(active.title).toBe('Retained event');expect(active.text).toBe('Exact payload');
 await page.reload();const second=await page.evaluate(async(old)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');let stale=false;try{await n.open(old);}catch{stale=true;}const current=(await n.list()).items[0];await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:false});const hidden=(await n.list()).items;await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true});const restored=(await n.list()).items[0];await n.clearNotificationHistory();return {stale,current,hidden,restored,afterClear:(await n.list()).items,history:(await n.notificationHistory()).items,policy:await n.crossAppStatus()};},active);
 expect(second.stale).toBe(true);expect(second.current.id).toBe(active.id);expect(second.current.revision).not.toBe(active.revision);expect(second.hidden).toEqual([]);expect(second.restored.title).toBe('Retained event');expect(second.afterClear).toHaveLength(1);expect(second.history).toEqual([]);expect(JSON.stringify(second.policy)).not.toContain('Exact payload');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.dismiss((await n.list()).items[0]);});await page.reload();expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').list()).items;})).toEqual([]);
});
test('replacement keys are scoped to source apps and stale removals cannot erase a replacement',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true},{packageName:'browser.calendar',preview:true}]});const mail=await n.inject({packageName:'browser.mail',title:'First',text:'Sensitive source payload',id:'shared'});await n.inject({packageName:'browser.calendar',title:'Calendar',text:'Other app',id:'shared'});const before=(await n.deviceEvents()).items.find((row:any)=>row.id===mail.id);const replacement=await n.inject({packageName:'browser.mail',title:'Replacement',text:'New payload',id:'shared'});let stale=false;try{await n.removeDeviceEvent(before);}catch{stale=true;}const history=JSON.stringify((await n.notificationHistory()).items);return {sameId:mail.id===replacement.id,stale,items:(await n.list()).items.map((row:any)=>row.title).sort(),history};});expect(result.sameId).toBe(true);expect(result.stale).toBe(true);expect(result.items).toEqual(['Calendar','Replacement']);expect(result.history).not.toMatch(/Sensitive|payload|Replacement/);
});
test('ongoing, secret and keep-after-opening semantics survive device restart',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,apps:[{packageName:'browser.mail',preview:true}]});await n.inject({packageName:'browser.mail',title:'Secret body',text:'Hidden',secret:true});await n.inject({packageName:'browser.mail',title:'Ongoing',text:'Kept',clearable:false,autoCancel:false});});await page.reload();
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');const rows=(await n.list()).items,secret=rows.find((r:any)=>r.title==='Mail'),ongoing=rows.find((r:any)=>r.title==='Ongoing');let denied=false;try{await n.open(secret);}catch{denied=true;}await n.open(ongoing);const retained=(await n.list()).items.some((r:any)=>r.id===ongoing.id);const cleared=await n.clear({items:rows});return {secret,denied,retained,cleared,remaining:(await n.list()).items.map((r:any)=>r.title)};});expect(result.secret.text).toBe('');expect(result.secret.canOpen).toBe(false);expect(result.denied).toBe(true);expect(result.retained).toBe(true);expect(result.remaining).toEqual(['Ongoing']);expect(result.cleared.outcomes.some((row:any)=>row.status==='unavailable')).toBe(true);
});
test('failed opening commits do not navigate or remove the event; lock retires old action tokens',async({page})=>{
 const original=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true}]});await n.inject({packageName:'browser.mail',title:'Atomic open',text:'Body'});const row=(await n.list()).items[0];const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.notifications.v2')throw new DOMException('Full','QuotaExceededError');return original.call(this,key,value);};let failed=false;try{await n.open(row);}catch{failed=true;}finally{Storage.prototype.setItem=original;}return {row,failed,count:(await n.list()).items.length,history:(await n.notificationHistory()).items.map((e:any)=>e.state)};});expect(original.failed).toBe(true);expect(original.count).toBe(1);expect(original.history).toEqual(['posted']);await expect(page.locator('html')).toHaveAttribute('data-active-view','home');
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Power',exact:true}).click();await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Unlock',exact:true}).click();const stale=await page.evaluate(async(row)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');try{await n.open(row);return false;}catch{return true;}},original.row);expect(stale).toBe(true);
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.open((await n.list()).items[0]);});await expect(page.locator('html')).toHaveAttribute('data-active-view','inbox');
});
test('device event editor updates and removes durable events through its rendered controls',async({page})=>{
 const open=async()=>{await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Post notification',exact:true}).click();return page.getByRole('dialog',{name:'Development notification'});};let dialog=await open();await dialog.getByRole('textbox',{name:'Title',exact:true}).fill('Persistent draft');await dialog.getByRole('checkbox',{name:'Keep after opening',exact:true}).check();await dialog.getByRole('button',{name:'Post',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Posted to device.');await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.reload();dialog=await open();await dialog.getByRole('button',{name:'Edit Persistent draft',exact:true}).click();await expect(dialog.getByRole('checkbox',{name:'Keep after opening',exact:true})).toBeChecked();await dialog.getByRole('textbox',{name:'Title',exact:true}).fill('Updated draft');await dialog.getByRole('button',{name:'Post',exact:true}).click();await expect(dialog.getByRole('button',{name:'Edit Persistent draft',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Remove Updated draft',exact:true}).click();await expect(dialog.getByText('No active device events',{exact:true})).toBeVisible();
});
test('two browser tabs share one device queue and serialize source replacements',async({page,context})=>{
 const original=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true}]});return n.inject({packageName:'browser.mail',title:'Original',text:'Body',id:'cross-tab'});});
 const other=await context.newPage();await other.goto(page.url());
 const update=(target:typeof page,title:string)=>target.evaluate(async(title)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaNotifications').inject({packageName:'browser.mail',title,text:'Replacement',id:'cross-tab'});},title);
 const replacements=await Promise.all([update(page,'First tab'),update(other,'Second tab')]);expect(replacements[0].id).toBe(original.id);expect(replacements[1].id).toBe(original.id);await page.bringToFront();
 const result=await page.evaluate(async(old)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');let stale=false;try{await n.dismiss({...old,source:'external'});}catch{stale=true;}const rows=(await n.list()).items,history=(await n.notificationHistory()).items;await n.dismiss(rows[0]);return {stale,count:rows.length,title:rows[0].title,history:history.length};},original);expect(result.stale).toBe(true);expect(result.count).toBe(1);expect(['First tab','Second tab']).toContain(result.title);expect(result.history).toBe(3);expect(await other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').deviceEvents()).items;})).toEqual([]);await other.close();
});
