import {test,expect,type Page} from '@playwright/test';
const run=(page:Page)=>page.evaluate(()=>(Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[])[0]);
async function open(page:Page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Receipt test',{exact:true}).click();}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{
 if(localStorage.getItem('receiptTestSeeded'))return;localStorage.setItem('receiptTestSeeded','yes');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));
 localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:993,name:'Receipt test',on:true,trig:{kind:'email',match:'receipt'},steps:[{k:'Do',t:'Save the attachment to Files',apps:['Files']},{k:'Do',t:'Add the amount to Wallet',apps:['Wallet']}],runs:[]}],localRuns:{}}));
 localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[{id:801,from:'Shop',subj:'Receipt 42',body:'Thank you',atts:[{browserAttachment:true,name:'receipt.txt',mimeType:'text/plain',dataBase64:btoa('Receipt 42\nTotal USD 12.34')}]}],sent:[]}));
 });await page.goto('/?mode=dev');await open(page);});
async function review(page:Page){await page.getByRole('button',{name:'Run now',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Workflow receipt',exact:true});await dialog.getByLabel('Receipt attachment',{exact:true}).selectOption('0');await dialog.getByLabel('Merchant',{exact:true}).fill('Neighborhood Shop');await dialog.getByLabel('Amount (USD)',{exact:true}).fill('12.34');await dialog.getByLabel('Wallet card',{exact:true}).selectOption('blue');return dialog;}
async function files(page:Page){return page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaFiles').workflowFiles({recent:false})).files;});}
test('receipt review saves exact file bytes and selected Wallet amount, then survives reload',async({page})=>{
 const requests:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))requests.push(r.url());});const dialog=await review(page);await dialog.getByRole('button',{name:'Use receipt',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('ok');const saved=await run(page);expect(saved.cursor).toBe(2);expect(JSON.stringify(saved.context)).not.toContain('dataBase64');expect((await files(page))[0]).toMatchObject({name:'receipt.txt',text:'Receipt 42\nTotal USD 12.34'});
 const wallet=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!));expect((await wallet()).cards.find((c:any)=>c.id==='blue').tx[0]).toMatchObject({id:saved.id+'-1',m:'Neighborhood Shop',a:12.34});await page.reload();expect((await files(page))[0].text).toBe('Receipt 42\nTotal USD 12.34');await page.getByRole('button',{name:'Wallet',exact:true}).click();await page.getByRole('button',{name:'Alpha Blue card ending 4821',exact:true}).click();await expect(page.getByText('Neighborhood Shop',{exact:true})).toBeVisible();expect(requests).toEqual([]);
});
test('invalid amount cannot submit; cancellation has no destination effects',async({page})=>{const dialog=await review(page);for(const value of ['-1','1e3','12.345','0','99999999','1,00']){await dialog.getByLabel('Amount (USD)',{exact:true}).fill(value);await expect(dialog.getByRole('button',{name:'Use receipt',exact:true})).toBeDisabled();}await dialog.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('cancelled');expect(await files(page)).toEqual([]);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.wallet'))).toBeNull();});
test('HOME cancels pending receipt review and leaves no effects',async({page})=>{await review(page);await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));await expect(page.getByRole('dialog',{name:'Workflow receipt'})).toHaveCount(0);await expect.poll(async()=>(await run(page))?.status).toBe('cancelled');expect(await files(page)).toEqual([]);});
test('changed source attachment cannot be approved from a stale selection',async({page})=>{const dialog=await review(page);await page.evaluate(()=>{const key='alpha.dev.app.inbox',state=JSON.parse(localStorage.getItem(key)!);state.mails[0].atts[0].dataBase64=btoa('Different receipt');localStorage.setItem(key,JSON.stringify(state));});await dialog.getByRole('button',{name:'Use receipt',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('changed');expect(await files(page)).toEqual([]);await dialog.getByRole('button',{name:'Cancel run',exact:true}).click();});
test('Wallet persistence failure retains only the completed Files step',async({page})=>{const dialog=await review(page);await page.evaluate(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.wallet')throw Error('Wallet full');return set.call(this,key,value);};});await dialog.getByRole('button',{name:'Use receipt',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('fail');expect((await run(page)).cursor).toBe(1);expect(await files(page)).toHaveLength(1);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.wallet'))).toBeNull();});
test('file receipts serialize concurrent replay, reject conflicts and retain deletion tombstones',async({page})=>{const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles(),signal=new AbortController().signal,input={operationId:'test-file-step',name:'receipt.txt',mimeType:'text/plain',dataBase64:btoa('Exact receipt')};const copies=await Promise.all([f.saveWorkflowAttachment(input,signal),f.saveWorkflowAttachment(input,signal)]);let conflict=false;try{await f.saveWorkflowAttachment({...input,dataBase64:btoa('Changed')},signal);}catch{conflict=true;}const before=(await f.workflowFiles({recent:false})).files;await f.delete({id:before[0].id,expectedRevision:before[0].revision,confirmPermanent:true});const replay=await f.saveWorkflowAttachment(input,signal);const after=(await f.workflowFiles({recent:false})).files;const cancel=new AbortController();cancel.abort();let aborted=false;try{await f.saveWorkflowAttachment({...input,operationId:'cancelled-file'},cancel.signal);}catch{aborted=true;}return {copies,conflict,before,after,replay,aborted};});expect(result.copies[0]).toEqual(result.copies[1]);expect(result.conflict&&result.aborted).toBe(true);expect(result.before).toHaveLength(1);expect(result.after).toEqual([]);expect(result.replay).toEqual(result.copies[0]);});
test('Wallet receipt replay is exact and never recreates a removed transaction',async({page})=>{const dialog=await review(page);await dialog.getByRole('button',{name:'Use receipt',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('ok');const result=await page.evaluate(async()=>{const {recordWorkflowExpense}=await import('/src/browser/workflow-receipts.ts');const saved:any=Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns)[0],key='alpha.dev.app.wallet',wallet=JSON.parse(localStorage.getItem(key)!);wallet.cards.forEach((card:any)=>card.tx=card.tx.filter((t:any)=>!t.workflowStep));localStorage.setItem(key,JSON.stringify(wallet));const api={get:()=>wallet,setView:()=>{throw Error('Replay wrote');}},signal=new AbortController().signal;recordWorkflowExpense(saved.context.receipt,saved.id+'-1',api,signal);let conflict=false;try{recordWorkflowExpense({...saved.context.receipt,cents:999},saved.id+'-1',api,signal);}catch{conflict=true;}return {conflict,count:JSON.parse(localStorage.getItem(key)!).cards.flatMap((c:any)=>c.tx).filter((t:any)=>t.workflowStep).length};});expect(result).toEqual({conflict:true,count:0});});
test('duplicate filenames preserve both receipts and failure commits no partial folder',async({page})=>{const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles(),signal=new AbortController().signal,input={name:'receipt.txt',mimeType:'text/plain',dataBase64:btoa('Bytes')};await f.saveWorkflowAttachment({...input,operationId:'first'},signal);await f.saveWorkflowAttachment({...input,operationId:'second'},signal);const names=(await f.workflowFiles({recent:false})).files.map(r=>r.name).sort();const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args:any[]){if(this.name==='workflowReceipts')throw Error('No receipt space');return (add as any).apply(this,args);};let failed=false;try{await f.saveWorkflowAttachment({...input,operationId:'failed'},signal);}catch{failed=true;}finally{IDBObjectStore.prototype.add=add;}return {names,failed,count:(await f.workflowFiles({recent:false})).files.length};});expect(result).toEqual({names:['receipt (2).txt','receipt.txt'],failed:true,count:2});});
// WebKit cannot seed Blob rows; Chromium retains the historical Blob compatibility check.
test('version-one Files upgrade preserves existing bytes and adds atomic receipt storage',async({page,browserName})=>{const result=await page.evaluate(async browserName=>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.open('alpha.browser.files.v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('entries',{keyPath:'id'});request.onerror=()=>reject(request.error);request.onsuccess=()=>{const d=request.result,tx=d.transaction('entries','readwrite');tx.objectStore('entries').put({id:'legacy',parentId:'root',name:'legacy.txt',mimeType:'text/plain',directory:false,size:6,revision:'original',...(browserName==='webkit'?{bytes:new TextEncoder().encode('Legacy').buffer}:{blob:new Blob(['Legacy'])})});tx.oncomplete=()=>{d.close();resolve();};tx.onerror=()=>reject(tx.error);};});const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles();await f.saveWorkflowAttachment({operationId:'migrated-step',name:'new.txt',mimeType:'text/plain',dataBase64:btoa('New')},new AbortController().signal);return (await f.workflowFiles({recent:false})).files;},browserName);expect(result.find(row=>row.id==='legacy')).toMatchObject({name:'legacy.txt',text:'Legacy',revision:'original'});expect(result.find(row=>row.name==='new.txt')?.text).toBe('New');});
test('cancellation during the Files transaction rolls back folder, bytes and receipt',async({page})=>{const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles(),abort=new AbortController(),add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args:any[]){const result=(add as any).apply(this,args);if(this.name==='workflowReceipts')abort.abort();return result;};let cancelled=false;const input={operationId:'cancel-in-transaction',name:'receipt.txt',mimeType:'text/plain',dataBase64:btoa('Actual bytes')};try{await f.saveWorkflowAttachment(input,abort.signal);}catch{cancelled=true;}finally{IDBObjectStore.prototype.add=add;}const after=(await f.list({})).entries;await f.saveWorkflowAttachment(input,new AbortController().signal);return {cancelled,after,final:(await f.workflowFiles({recent:false})).files.length};});expect(result).toEqual({cancelled:true,after:[],final:1});});
test('source change after file commit retains that step and prevents Wallet write',async({page})=>{const dialog=await review(page);await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const save=BrowserFiles.prototype.saveWorkflowAttachment;BrowserFiles.prototype.saveWorkflowAttachment=async function(...args){const result=await save.apply(this,args);const key='alpha.dev.app.inbox',state=JSON.parse(localStorage.getItem(key)!);state.mails[0].atts[0].dataBase64=btoa('Replacement');localStorage.setItem(key,JSON.stringify(state));return result;};});await dialog.getByRole('button',{name:'Use receipt',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('fail');expect((await run(page)).cursor).toBe(1);expect((await run(page)).sum).toContain('changed');expect(await files(page)).toHaveLength(1);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.wallet'))).toBeNull();});
test('receipt review fits a compact dark display',async({page},testInfo)=>{await page.setViewportSize({width:320,height:640});await page.goto('/?mode=dev&theme=dark');await open(page);const dialog=await review(page);expect(await dialog.evaluate(element=>getComputedStyle(element).backgroundColor)).toBe('rgb(0, 0, 0)');await expect(dialog.getByRole('button',{name:'Use receipt',exact:true})).toBeEnabled();const box=await dialog.boundingBox();expect(box!.width).toBeLessThanOrEqual(320);expect(box!.height).toBeLessThanOrEqual(640);await dialog.getByRole('button',{name:'Cancel run',exact:true}).scrollIntoViewIfNeeded();await expect(dialog.getByRole('button',{name:'Cancel run',exact:true})).toBeInViewport();await expect(dialog.getByRole('button',{name:'Use receipt',exact:true})).toBeInViewport();await page.screenshot({path:testInfo.outputPath('receipt-review.png')});await dialog.getByRole('button',{name:'Cancel run',exact:true}).click();});
test.describe('New York receipt dates',()=>{test.use({timezoneId:'America/New_York'});test('receipt dates age by civil days through DST while seed dates remain intact',async({page})=>{const result=await page.evaluate(async()=>{const {datedReceiptWallet}=await import('/src/browser/workflow-receipts.ts');const wallet={cards:[{id:'blue',tx:[{id:'receipt',recordedAt:new Date(2026,2,7,12).getTime(),d:0},{id:'seed',d:4}]}]};return datedReceiptWallet(wallet,new Date(2026,2,8,12)).cards[0].tx;});expect(result.map((r:any)=>r.d)).toEqual([1,4]);});});

test('attachment save binds its receipt to the reviewed bytes despite caller mutation',async({page})=>{
 const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles(),input={operationId:'immutable-file',name:'receipt.txt',mimeType:'text/plain',dataBase64:btoa('Original')};const pending=f.saveWorkflowAttachment(input,new AbortController().signal);input.dataBase64=btoa('Changed!');await pending;return (await f.workflowFiles({recent:false})).files[0];});expect(result.text).toBe('Original');
});
test('deleted mail cannot supply a previously selected receipt',async({page})=>{
 const result=await page.evaluate(async()=>{const {receiptAttachment}=await import('/src/browser/workflow-receipts.ts');const {reviewMailAttachment}=await import('/src/runtime/inbox-attachment.ts');const key='alpha.dev.app.inbox',state=JSON.parse(localStorage.getItem(key)!);const checked=await reviewMailAttachment(state.mails[0].atts[0]);state.mails[0].del=true;localStorage.setItem(key,JSON.stringify(state));try{await receiptAttachment({mailId:'801',sent:false,index:0,name:checked.name,mimeType:checked.mimeType,sha256:checked.sha256},{get:()=>state},new AbortController().signal);return false;}catch{return true;}});expect(result).toBe(true);
});

test('blocked Files upgrade fails without losing legacy data and can retry after its owner closes',async({page,browserName})=>{
 const result=await page.evaluate(async browserName=>{const old=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('alpha.browser.files.v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('entries',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const tx=old.transaction('entries','readwrite');tx.objectStore('entries').put({id:'legacy',parentId:'root',name:'legacy.txt',mimeType:'text/plain',directory:false,size:6,revision:'old',...(browserName==='webkit'?{bytes:new TextEncoder().encode('Legacy').buffer}:{blob:new Blob(['Legacy'])})});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles();let message='';try{await f.list({});}catch(error){message=String(error);}old.close();await f.saveWorkflowAttachment({operationId:'after-upgrade',name:'new.txt',mimeType:'text/plain',dataBase64:btoa('New')},new AbortController().signal);return {message,files:(await f.workflowFiles({recent:false})).files};},browserName);expect(result.message).toContain('Close other Alpha tabs');expect(result.files.find(row=>row.id==='legacy')?.text).toBe('Legacy');expect(result.files.find(row=>row.name==='new.txt')?.text).toBe('New');
});

test('string trigger ids select numeric Inbox ids and ambiguous identities cannot be accepted',async({page})=>{
 await page.evaluate(async()=>{const {requestWorkflowReceipt}=await import('/src/browser/workflow-receipts.ts');const api={get:(name:string)=>name==='wallet'?{cards:[]}:JSON.parse(localStorage.getItem('alpha.dev.app.inbox')!)};(window as any).receiptResult=requestWorkflowReceipt(api,false,new AbortController().signal,'801').catch(()=>null);});
 const dialog=page.getByRole('dialog',{name:'Workflow receipt',exact:true});await dialog.getByLabel('Receipt attachment',{exact:true}).selectOption('0');
 await page.evaluate(()=>{const key='alpha.dev.app.inbox',state=JSON.parse(localStorage.getItem(key)!);state.mails.push({...state.mails[0],id:'801'});localStorage.setItem(key,JSON.stringify(state));});await dialog.getByRole('button',{name:'Use receipt',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('no longer in Inbox');await dialog.getByRole('button',{name:'Cancel run',exact:true}).click();expect(await page.evaluate(()=>(window as any).receiptResult)).toBeNull();expect(await files(page)).toEqual([]);
});
