import {test,expect,type Page} from '@playwright/test';
async function open(page:Page){await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();}
async function select(page:Page,account:string){await page.getByRole('combobox',{name:'Sample account'}).selectOption(account);await page.getByRole('button',{name:'Use development account'}).click();await expect(page.getByText(`Connected development account: ${account}`,{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Development profile'}).selectOption('cloud');}
async function connect(page:Page){await page.getByRole('button',{name:'Connect development profile'}).click();await expect(page.getByRole('dialog',{name:'Development connections'})).toHaveCount(0);}
const session=(page:Page)=>page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');return c.getSnapshot().session;});
test('sample Cloud accounts isolate conversations and proposals and retire on account changes',async({page})=>{
 await page.goto('/?mode=dev');await open(page);await select(page,'first');await connect(page);const first=await session(page);expect(first!.ownerId).toContain('cloud.first');await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('First account message');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect(page.getByText('Development reply. Edit this response in Agent connection.',{exact:true})).toBeVisible();await open(page);await page.getByText('Development device actions',{exact:true}).click();await page.getByRole('button',{name:'Queue action for review'}).click();await expect(page.getByText('Action queued. Send a chat message to review it on the current screen.',{exact:true})).toBeVisible();
 await select(page,'second');await expect.poll(()=>session(page)).toBeNull();await connect(page);expect((await session(page))!.ownerId).toContain('cloud.second');await open(page);await page.getByRole('button',{name:'Load conversations'}).click();await expect(page.getByRole('button',{name:'Restore conversation'})).toHaveCount(0);await page.getByText('Development device actions',{exact:true}).click();await page.getByRole('button',{name:'Refresh actions'}).click();await expect(page.getByRole('button',{name:'Reject proposal'})).toHaveCount(0);
 await select(page,'first');await connect(page);await open(page);await page.getByRole('button',{name:'Load conversations'}).click();await expect(page.getByRole('button',{name:'Restore conversation'})).toHaveCount(1);await page.getByText('Development device actions',{exact:true}).click();await page.getByRole('button',{name:'Refresh actions'}).click();await expect(page.getByRole('button',{name:'Reject proposal'})).toHaveCount(1);await page.getByRole('button',{name:'Sign out development account'}).click();await expect.poll(()=>session(page)).toBeNull();await page.reload();expect(await session(page)).toBeNull();
});
test('captured Cloud bridge refuses a changed account while old journals retain their namespace',async({page})=>{
 await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{const {selectDevelopmentCloud}=await import('/src/browser/development-cloud.ts');const {developmentBridge}=await import('/src/browser/development-connection.ts');const {developmentIdentity}=await import('/src/browser/development-identity.ts');const {developmentJournal,authorDevelopmentAction}=await import('/src/browser/development-actions.ts');const signal=new AbortController().signal;await selectDevelopmentCloud('first',signal);const identity=developmentIdentity('cloud'),bridge=developmentBridge('cloud',identity),journal=developmentJournal('cloud',identity);localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'cloud',account:'first'}));const proposalId=await authorDevelopmentAction('cloud',JSON.stringify({type:'open_view',view:'notes'}),signal);const proposal=JSON.parse(localStorage.getItem('alpha.browser.agent.actions.cloud.first.v1')!).proposals[0];await journal.reserve({scope:'a'.repeat(64),proposalId,operationId:'retained-operation',operationHash:proposal.digest,record:{digest:proposal.digest}});await selectDevelopmentCloud('second',signal);await journal.finish({scope:'a'.repeat(64),proposalId,status:'cancelled',summary:'Account changed before dispatch'});let refused=false;try{await bridge.request({path:'/api/auth/me',method:'GET',headers:{},timeoutMs:1000},signal);}catch{refused=true;}return {refused,status:(await journal.list({scope:'a'.repeat(64)})).entries[0].status,other:localStorage.getItem('alpha.browser.agent.actions.cloud.second.v1'),namespace:identity.namespace};});expect(result).toEqual({refused:true,status:'cancelled',other:null,namespace:'cloud.first'});
});
test('a queued reply save cannot cross into another Cloud account',async({page})=>{
 await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{const {selectDevelopmentCloud}=await import('/src/browser/development-cloud.ts');const {saveDevelopmentReply}=await import('/src/browser/development-connection.ts');const signal=new AbortController().signal;await selectDevelopmentCloud('first',signal);let release!:()=>void;const lock=navigator.locks.request('alpha.browser.agent.cloud.first.v1',()=>new Promise<void>(resolve=>release=resolve));while(!release)await new Promise(resolve=>setTimeout(resolve,0));const save=saveDevelopmentReply('cloud','first only',signal).then(()=>false,()=>true);await selectDevelopmentCloud('second',signal);release();await lock;return {refused:await save,first:localStorage.getItem('alpha.browser.agent.cloud.first.v1'),second:localStorage.getItem('alpha.browser.agent.cloud.second.v1')};});expect(result).toEqual({refused:true,first:null,second:null});
});
