import {test,expect,type Page} from '@playwright/test';
const run=(page:Page)=>page.evaluate(async()=>(Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[])[0]);
const notices=(page:Page)=>page.evaluate(async()=>JSON.parse((await (await import('/src/browser/workflow-notices.ts')).workflowNoticesDocument.readRaw())||'{"rows":[]}').rows);
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));localStorage.setItem('alphaphone:notes:v2',JSON.stringify({version:2,collectionId:'12345678-1234-4234-8234-123456789abc',deleted:[],records:[{id:'deadline',kind:'text',title:'Restart deadline',body:'Server restart deadline is in five minutes.'}]}));localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:982,name:'Urgency test',on:true,trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Read',t:'Notes',apps:['Notes']},{k:'Notify',t:'A notification, only if urgent',apps:[]},{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']}],runs:[]}],localRuns:{}}));});await page.goto('/?mode=dev');await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Urgency test',{exact:true}).click();});
async function start(page:Page){await page.getByRole('button',{name:'Run now',exact:true}).click();}
async function agent(page:Page){await page.evaluate(async()=>{const {alphaClient}=await import('/src/runtime/alpha-client.ts');(window as any).urgencyAgent={calls:0};alphaClient.attachVerifiedTransport({session:{ownerId:'fixture-owner',agentId:'fixture-agent',sessionId:'fixture-session',origin:'https://fixture.example'},send:input=>{const state=(window as any).urgencyAgent;state.calls++;state.input=input.text;state.signal=input.signal;return new Promise(resolve=>state.finish=resolve);},execute:async()=>{throw Error('No action execution');}});});await start(page);await expect.poll(()=>page.evaluate(async()=>(window as any).urgencyAgent.calls)).toBe(1);}
for(const urgent of [true,false])test(`offline review ${urgent?'posts':'omits'} the notification and continues`,async({page},info)=>{await start(page);const dialog=page.getByRole('dialog',{name:'Workflow urgency'});await expect(dialog.getByLabel('Notification content')).toHaveValue(/Server restart deadline/);if(urgent)await page.screenshot({path:info.outputPath('urgency-review.png')});await dialog.getByRole('button',{name:urgent?'Urgent':'Not urgent',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('ok');const saved=await run(page);expect(saved.cursor).toBe(3);expect(saved.context.urgency[saved.id+'-1']).toMatchObject({urgent,source:'development-review'});expect(await notices(page)).toHaveLength(urgent?1:0);expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw())!).doNotDisturb)).toBe(true);if(urgent)expect((await notices(page))[0].text).toContain('Server restart deadline');else expect(saved.log[1][1]).toContain('Notification not posted');});
for(const urgent of [true,false])test(`connected urgency decision ${urgent} uses the actual returned JSON`,async({page})=>{await agent(page);await expect(page.getByRole('dialog',{name:'Workflow urgency'})).toHaveCount(0);expect(await page.evaluate(async()=>(window as any).urgencyAgent.input)).toContain('Server restart deadline');await page.evaluate(urgent=>(window as any).urgencyAgent.finish({text:JSON.stringify({urgent,reason:urgent?'Time-sensitive deadline.':'No immediate action needed.'})}),urgent);await expect.poll(async()=>(await run(page))?.status).toBe('ok');const saved=await run(page);expect(saved.context.urgency[saved.id+'-1']).toMatchObject({urgent,source:'agent'});expect(await notices(page)).toHaveLength(urgent?1:0);expect(saved.cursor).toBe(3);});
for(const output of ['true','{"urgent":"true","reason":"Text"}','{"urgent":true,"reason":"Text","extra":1}'])test('malformed decision cannot publish: '+output,async({page})=>{await agent(page);await page.evaluate(text=>(window as any).urgencyAgent.finish({text}),output);await expect.poll(async()=>(await run(page))?.status).toBe('fail');expect((await run(page)).cursor).toBe(1);expect(await notices(page)).toEqual([]);expect(await page.evaluate(async()=>(await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw()))).toBeNull();});
test('cancelling offline review prevents notification and subsequent actions',async({page})=>{await start(page);await page.getByRole('dialog',{name:'Workflow urgency'}).getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('cancelled');expect((await run(page)).cursor).toBe(1);expect(await notices(page)).toEqual([]);expect(await page.evaluate(async()=>(await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw()))).toBeNull();});
test('late urgent result after cancellation cannot publish',async({page})=>{await agent(page);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await run(page))?.status).toBe('cancelled');await page.evaluate(async()=>(window as any).urgencyAgent.finish({text:'{"urgent":true,"reason":"Late"}'}));expect(await notices(page)).toEqual([]);expect(await page.evaluate(async()=>(window as any).urgencyAgent.signal.aborted)).toBe(true);});
test('failure to persist the decision prevents notification publication',async({page})=>{await start(page);await page.evaluate(async()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.workflows'&&value.includes('development-review'))throw Error('History full');return set.call(this,key,value);};});await page.getByRole('dialog',{name:'Workflow urgency'}).getByRole('button',{name:'Urgent',exact:true}).click();await expect(page.getByRole('status',{name:'Workflow run status',exact:true})).toHaveText('Run state could not be saved. Reload to inspect its last saved step.');expect(await notices(page)).toEqual([]);expect((await run(page)).context.urgency).toBeUndefined();});
for(const action of ['escape','back','home','background','incoming-call'])test(`${action} retires the offline urgency review without effects`,async({page})=>{
 await start(page);const dialog=page.getByRole('dialog',{name:'Workflow urgency'});await expect(dialog).toBeVisible();if(action==='escape')await page.keyboard.press('Escape');else await page.evaluate(action=>window.dispatchEvent(new Event(({back:'alpha-back',home:'launcher-home',background:'alpha:device-state','incoming-call':'alpha:dev-incoming-call'} as any)[action],{cancelable:true})),action);await expect(dialog).toHaveCount(0);await expect.poll(async()=>(await run(page))?.status).toBe('cancelled');expect(await notices(page)).toEqual([]);expect(await page.evaluate(async()=>(await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw()))).toBeNull();
});
test('externally edited workflow cannot publish an already pending urgent decision',async({page})=>{
 await agent(page);const raw=await page.evaluate(async()=>{const key='alpha.dev.app.workflows',state=JSON.parse(localStorage.getItem(key)!);state.flows[0].steps[1].t='Changed notification';const raw=JSON.stringify(state);localStorage.setItem(key,raw);(window as any).urgencyAgent.finish({text:'{"urgent":true,"reason":"Deadline now"}'});return raw;});await expect(page.getByRole('status',{name:'Workflow run status',exact:true})).toHaveText('Run state could not be saved. Reload to inspect its last saved step.');expect(await notices(page)).toEqual([]);expect(await page.evaluate(async()=>localStorage.getItem('alpha.dev.app.workflows'))).toBe(raw);
});
