import {test,expect,type Page} from '@playwright/test';
async function setup(page:Page){await page.goto('/?mode=dev&workflows=agent');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'New workflow',exact:true}).click();await expect(page.getByText('Build a manual workflow. It will be saved paused.',{exact:true})).toBeVisible();}
test('agent workflow editor saves a typed workflow through the development bridge',async({page})=>{await setup(page);await page.getByRole('button',{name:'Add Read step',exact:true}).click();await page.getByRole('textbox',{name:'Text supplied to workflow',exact:true}).fill('Development workflow input');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await expect(page.getByText(/Review this full specification/)).toBeVisible();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await expect(page.getByRole('button',{name:'Run now',exact:true})).toBeVisible();const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.workflows.local.v1')!));expect(data.workflows).toHaveLength(1);expect(data.workflows[0].active).toBe(false);expect(data.workflows[0].phoneSpec.steps[0].text).toBe('Development workflow input');expect(data.receipts).toHaveLength(1);await page.reload();await page.getByRole('button',{name:'Workflows',exact:true}).click();await expect(page.getByRole('button',{name:/New workflow Agent workflow/})).toBeVisible();});
test('browser draft compare exchange preserves other-tab edits and rejects another owner',async({page})=>{await setup(page);const result=await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');const {browserWorkflowDraftStore}=await import('/src/browser/workflow-drafts.ts');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const session=c.getSnapshot().session!,store=await browserWorkflowDraftStore(session),slot='workflow-draft:v1:'+await workflowSha([session.origin,session.ownerId,session.agentId]),saved=await store.secureRead({slot});const first=await store.secureCompareExchange({slot,expectedValue:saved.value,value:'first'}),second=await store.secureCompareExchange({slot,expectedValue:saved.value,value:'second'});localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));let refused=false;try{await store.secureRead({slot});}catch{refused=true;}return {first,second,refused};});expect(result).toEqual({first:{status:'saved'},second:{status:'conflict'},refused:true});});
test('workflow save retries reuse their receipt and reject changed payloads',async({page})=>{await setup(page);const result=await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');const {workflowSha}=await import('/src/runtime/workflow-device-contract.ts');const client=c.getWorkflowClient()!.client,signal=new AbortController().signal,catalog=await client.phoneCatalog(signal),spec={version:1 as const,name:'Receipt workflow',description:'',trigger:{kind:'manual' as const},steps:[{id:'read',kind:'Read' as const,operation:'supplied_text',text:'private input'}]},validation=await client.validatePhone(spec,catalog,signal),expected={mutationId:crypto.randomUUID(),specDigest:validation.specDigest,compilerRevision:catalog.compilerRevision};const first=await client.savePhone(spec,catalog,expected,signal),replay=await client.savePhone(spec,catalog,expected,signal),receipt=await client.phoneSaveReceipt(expected,signal);let refused=false;try{const changed={...spec,name:'Changed payload'};await client.savePhone(changed,catalog,{...expected,specDigest:await workflowSha(changed)},signal);}catch{refused=true;}return {same:JSON.stringify(first)===JSON.stringify(replay)&&JSON.stringify(first)===JSON.stringify(receipt),refused,count:JSON.parse(localStorage.getItem('alpha.browser.workflows.local.v1')!).workflows.length};});expect(result).toEqual({same:true,refused:true,count:1});});
test('Describe preserves the draft when the fixture agent has no typed generator',async({page})=>{
 await setup(page);await page.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Retain this private draft');await page.getByRole('textbox',{name:'Workflow description',exact:true}).fill('Private description');await page.getByRole('button',{name:/Describe it to/}).click();
 await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain this private draft');await expect(page.getByRole('textbox',{name:'Workflow request',exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.agent.local.v1')||'{"conversations":[]}').conversations.flatMap((c:any)=>c.messages))).toEqual([]);
 await page.reload();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'New workflow',exact:true}).click();await expect(page.getByText(/Restored the draft stored/)).toBeVisible();await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain this private draft');await expect(page.getByRole('textbox',{name:'Workflow description',exact:true})).toHaveValue('Private description');
});

for(const outcome of ['saved','failed','left'])test(`Describe preserves pending draft storage: ${outcome}`,async({page})=>{
 await setup(page);
 await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).some(key=>key.startsWith('alpha.browser.workflow-draft:')))).toBe(true);
 await page.evaluate(outcome=>{const request=navigator.locks.request.bind(navigator.locks);let held=false;navigator.locks.request=(async(name:any,...args:any[])=>{if(String(name).startsWith('alpha.browser.workflow-draft:')&&!held){held=true;await new Promise<void>(resolve=>(window as any).releaseDraft=resolve);if(outcome==='failed')throw Error('Synthetic draft storage failure');}return (request as any)(name,...args);}) as any;},outcome);
 await page.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Retain pending private draft');
 await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseDraft)).toBe('function');
 await page.getByRole('button',{name:/Describe it to/}).click();
 await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toBeVisible();
 if(outcome==='left')await page.getByRole('button',{name:'Home',exact:true}).click();
 await page.evaluate(()=>(window as any).releaseDraft());
 if(outcome==='saved'){await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain pending private draft');await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('alpha.browser.workflow-draft:')).map(key=>JSON.parse(JSON.parse(localStorage.getItem(key)!).value).spec.name))).toContain('Retain pending private draft');await expect(page.getByRole('textbox',{name:'Message Alpha',exact:true})).toHaveCount(0);}
 else if(outcome==='failed'){await expect(page.getByRole('textbox',{name:'Workflow name',exact:true})).toHaveValue('Retain pending private draft');await expect(page.getByText('Synthetic draft storage failure',{exact:true}).first()).toBeVisible();}
 else{await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('alpha.browser.workflow-draft:')).map(key=>JSON.parse(JSON.parse(localStorage.getItem(key)!).value).spec.name))).toContain('Retain pending private draft');await expect(page.getByRole('textbox',{name:'Message Alpha',exact:true})).toHaveCount(0);}
});
