import {test,expect} from '@playwright/test';
test.use({timezoneId:'America/New_York'});
const now=Date.parse('2026-10-02T16:00:00Z');
const output=(page:any)=>page.evaluate(()=>JSON.parse((Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]).at(-1)!.out));
for(const source of ["Today's notes",'Overnight inbox',"Overnight inbox and today's calendar","This week's calendar, notes and sent mail","Today's calendar, notes and sent mail"])test(`dated workflow source: ${source}`,async({page})=>{
 await page.clock.setFixedTime(new Date(now));await page.addInitScript(({source,now})=>{
 localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:991,name:'Dated read',on:true,trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Read',t:source,apps:[]}],runs:[]}],localRuns:{}}));
 localStorage.setItem('alphaphone:notes:v2',JSON.stringify({version:2,collectionId:'12345678-1234-4234-8234-123456789abc',deleted:[],records:[{id:'today',kind:'text',title:'Today',body:'Today body',createdAt:now-3600000},{id:'week',kind:'text',title:'Week',body:'Earlier this week',createdAt:now-2*86400000},{id:'old',kind:'text',title:'Old',body:'Last month',createdAt:now-20*86400000},{id:'unknown',kind:'text',title:'Unknown',body:'Undated'}]}));
 localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[{id:801,subj:'Night',body:'Overnight',receivedAt:Date.parse('2026-10-02T02:00:00Z')},{id:802,subj:'Day',body:'After morning',receivedAt:Date.parse('2026-10-02T15:00:00Z')},{id:803,subj:'Unknown',body:'No date'}],sent:[{id:'sent-today',sent:true,to:['you@alpha.local'],body:'Today sent',sentAt:now-3600000},{id:'sent-week',sent:true,to:['you@alpha.local'],body:'Week sent',k:now-2*86400000},{id:'sent-unknown',sent:true,to:['you@alpha.local'],body:'No date',k:2000}]}));
 },{source,now});await page.goto('/?mode=dev');await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Dated read',{exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[])[0]?.status)).toBe('ok');const result=await output(page);
 if(result.inbox){expect(result.inbox.items.map((r:any)=>r.id)).toEqual([801]);expect(result.inbox.undated).toBe(1);expect(result.inbox.end).toBe(Date.parse('2026-10-02T13:00:00Z'));}
 if(result.notes){expect(result.notes.items.map((r:any)=>r.id)).toEqual(source.startsWith('This week')?['today','week']:['today']);expect(result.notes.undated).toBe(1);}
 if(result.sentMail){expect(result.sentMail.items.map((r:any)=>r.id)).toEqual(source.startsWith('This week')?['sent-today','sent-week']:['sent-today']);expect(result.sentMail.undated).toBe(1);}
 if(source.includes('calendar'))expect(Array.isArray(result.calendar)).toBe(true);
});
test('local date boundaries follow DST and legacy notes keep unknown creation dates',async({page})=>{await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{const {workflowDateRange,datedRows}=await import('/src/browser/workflow-dated-sources.ts');const {stampNoteChanges}=await import('/src/runtime/note-dates.ts');const spring=workflowDateRange('today',new Date('2026-03-08T16:00:00Z')),fall=workflowDateRange('today',new Date('2026-11-01T16:00:00Z'));const note={id:'legacy',kind:'text',title:'Old',body:'Old'},same=stampNoteChanges([note],[{...note,pinned:true}],123)[0],edited=stampNoteChanges([note],[{...note,body:'New'}],456)[0],created=stampNoteChanges([],[{id:'new',kind:'text',title:'New'}],789)[0];return {spring:spring.end-spring.begin,fall:fall.end-fall.begin,same,edited,created,filtered:datedRows([{createdAt:100},{createdAt:199},{createdAt:200},{}],{begin:100,end:200},'notes')};});expect(result.spring).toBe(23*3600000);expect(result.fall).toBe(25*3600000);expect(result.same.modifiedAt).toBeUndefined();expect(result.edited.createdAt).toBeUndefined();expect(result.edited.modifiedAt).toBe(456);expect(result.created.createdAt).toBe(789);expect(result.filtered.items).toHaveLength(2);expect(result.filtered.undated).toBe(1);});
test('rendered Notes creation and edits retain exact dates across reload',async({page})=>{
 await page.clock.setFixedTime(new Date(now));await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Dated note');await page.getByRole('textbox',{name:'Note',exact:true}).fill('First content');const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.find((r:any)=>r.title==='Dated note'));await expect.poll(async()=>(await saved())?.createdAt).toBe(now);await expect.poll(async()=>(await saved())?.modifiedAt).toBe(now);await page.clock.setFixedTime(new Date(now+86400000));await page.getByRole('textbox',{name:'Note',exact:true}).fill('Next day edit');await expect.poll(async()=>(await saved())?.modifiedAt).toBe(now+86400000);await page.reload();expect((await saved()).createdAt).toBe(now);expect((await saved()).body).toBe('Next day edit');
});
test('approved Notes update timestamp is included in its exact returned revision',async({page})=>{await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{const {NotesStore}=await import('/src/runtime/notes-store.ts');const memory=new Map<string,string>(),store=new NotesStore({getItem:key=>memory.get(key)??null,setItem:(key,value)=>{memory.set(key,value);} },[{id:'note',kind:'text',title:'Before',body:'Before'}]);const target=await store.target('note');const receipt=await store.execute({type:'notes_update',target,fields:{title:'After',body:'After'}},'dated-operation',new AbortController().signal,()=>{});return {receipt,next:await store.target('note'),note:store.list[0]};});expect(result.receipt.revision).toBe(result.next.revision);expect(result.note.modifiedAt).toBeGreaterThan(0);expect(result.note.createdAt).toBeUndefined();});

test('approved no-op edits do not make an old note appear modified today',async({page})=>{
 await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{const {NotesStore}=await import('/src/runtime/notes-store.ts');const data=new Map<string,string>();const store=new NotesStore({getItem:key=>data.get(key)??null,setItem:(key,value)=>{data.set(key,value);}},[{id:'old',kind:'text',title:'Unchanged',body:'Same',modifiedAt:1000}]);const before=await store.target('old');const receipt=await store.execute({type:'notes_update',target:before,fields:{title:'Unchanged',body:'Same'}},'no-op',new AbortController().signal,()=>{});return {before,receipt,note:store.list[0]};});expect(result.note.modifiedAt).toBe(1000);expect(result.receipt.revision).toBe(result.before.revision);
});

test('overnight reads exclude deleted and archived messages in both source combinations',async({page})=>{
 await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{const {readDatedWorkflowSource}=await import('/src/browser/workflow-dated-sources.ts');localStorage.removeItem('alpha.dev.app.inbox');const receivedAt=Date.parse('2026-10-02T02:00:00Z');const api={get:()=>({mails:[{id:'visible',receivedAt},{id:'deleted',receivedAt,del:true},{id:'archived',receivedAt,arch:true}],sent:[]})};const results=[];for(const label of ['Overnight inbox',"Overnight inbox and today's calendar"]){const value=await readDatedWorkflowSource(label,api,{list:async()=>({events:[]})},new AbortController().signal,new Date('2026-10-02T16:00:00Z'));results.push(value?.inbox?.items.map((row:any)=>row.id));}return results;});expect(result).toEqual([['visible'],['visible']]);
});
