import {test,expect,Page} from '@playwright/test';
async function ring(page:Page){await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Incoming call',exact:true}).click();}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&tools=1');});
test('device incoming call accepts and ends as one incoming history entry',async({page})=>{
 await ring(page);await expect(page.getByRole('button',{name:'Accept',exact:true})).toBeVisible();await ring(page);await page.getByRole('button',{name:'Accept',exact:true}).click();await ring(page);await expect(page.getByRole('button',{name:'Decline',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'End call',exact:true}).click();const rows=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).recents.filter((r:any)=>r.at));expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({pid:'maya',dir:'in'});await page.reload();await page.getByRole('button',{name:'Phone',exact:true}).click();await expect(page.getByRole('button',{name:'End call',exact:true})).toHaveCount(0);
});
test('decline atomically saves missed call and voicemail, then read delete undo survive reload',async({page})=>{
 await ring(page);await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).writes=[];Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.phone')(window as any).writes.push(JSON.parse(v));return set.call(this,k,v);};});await page.getByRole('button',{name:'Decline',exact:true}).click();const writes=await page.evaluate(()=>(window as any).writes);expect(writes).toHaveLength(1);expect(writes[0].recents[0]).toMatchObject({pid:'maya',dir:'missed'});const voicemail=writes[0].vms[0];expect(voicemail).toMatchObject({pid:'maya',heard:false});await page.reload();await page.getByRole('button',{name:'Phone',exact:true}).click();await page.getByRole('button',{name:'Voicemail',exact:true}).click();await page.getByText(voicemail.text,{exact:true}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).vms[0].heard)).toBe(true);await page.getByRole('button',{name:'Delete voicemail',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.reload();expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).vms.filter((v:any)=>v.id===id),voicemail.id)).toEqual([{...voicemail,heard:true}]);
});
test('failed decline retains the incoming call and retry saves one matching voicemail',async({page})=>{
 await ring(page);await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restore=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.phone')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Decline',exact:true}).click();await expect(page.getByRole('button',{name:'Accept',exact:true})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.phone'))).toBeNull();await page.evaluate(()=>(window as any).restore());await page.getByRole('button',{name:'Decline',exact:true}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!));expect(saved.recents.filter((r:any)=>r.at)).toHaveLength(1);expect(saved.vms.filter((r:any)=>r.at)).toHaveLength(1);
});
test('screening retains its transcript after a failed history save and retry commits once',async({page})=>{
 const external:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))external.push(r.url());});await ring(page);await page.getByRole('button',{name:'Let Alpha answer',exact:true}).click();await expect(page.getByText("Hey, it's Maya. I'm running ten minutes late for three.",{exact:true})).toBeVisible();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restoreScreen=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.phone')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Hang up',exact:true}).click();await expect(page.getByRole('button',{name:'Hang up',exact:true})).toBeVisible();await expect(page.getByText("Nope, that's it. Thanks!",{exact:true})).toBeVisible();await page.evaluate(()=>(window as any).restoreScreen());await page.getByRole('button',{name:'Hang up',exact:true}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).recents.filter((r:any)=>r.at));expect(saved).toHaveLength(1);expect(saved[0]).toMatchObject({dir:'in',screened:true,note:"Maya's running ten minutes late for 3:00."});await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).recents[0])).toEqual(saved[0]);expect(external).toEqual([]);
});
test('failed voicemail Undo remains retryable and restores the original once',async({page})=>{
 await ring(page);await page.getByRole('button',{name:'Decline',exact:true}).click();
 const original=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).vms[0]);
 await page.getByRole('button',{name:'Voicemail',exact:true}).click();await page.getByText(original.text,{exact:true}).click();
 await page.getByRole('button',{name:'Delete voicemail',exact:true}).click();
 await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restoreUndo=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.phone')throw Error('Full');return set.call(this,k,v);};});
 await page.getByRole('button',{name:'Undo',exact:true}).click();
 await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeVisible();
 expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).vms.some((v:any)=>v.id===id),original.id)).toBe(false);
 await page.evaluate(()=>(window as any).restoreUndo());await page.getByRole('button',{name:'Undo',exact:true}).click();await page.reload();
 expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).vms.filter((v:any)=>v.id===id),original.id)).toEqual([{...original,heard:true}]);
});
