import {test,expect} from '@playwright/test';
for(const mode of ['all-day','multi-day','overlap'] as const)test(`browser complex Calendar editor preserves ${mode} dates`,async({page},testInfo)=>{
 await page.clock.setFixedTime(new Date('2026-11-01T12:00:00Z'));
 await page.addInitScript(mode=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.browser.calendar.v1'))(localStorage.getItem('alpha.browser.calendar.v1')===null&&localStorage.setItem('alpha.browser.calendar.v1',JSON.stringify({sourceRevision:'a'.repeat(64),events:[{id:'complex',calendarId:'local',title:'Complex event',body:'Description',location:'Desk',begin:Date.parse(mode==='all-day'?'2026-11-01T00:00:00Z':mode==='overlap'?'2026-11-01T06:30:00Z':'2026-11-01T23:30:00Z'),end:Date.parse('2026-11-03T00:00:00Z'),allDay:mode==='all-day',timeZone:'America/New_York',revision:'b'.repeat(64)}]})));},mode);
 await page.goto('/?mode=dev');await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:mode==='all-day'?'Complex event, All day':/^Complex event,/}).click();await page.getByRole('button',{name:'Edit event',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await expect(dialog).toBeVisible();const before=await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0]);await dialog.getByLabel('Event title',{exact:true}).fill('Edited complex event');if(mode!=='overlap')await dialog.getByLabel('Ends',{exact:true}).fill(mode==='all-day'?'2026-11-03':'2026-11-03T19:00');if(mode==='overlap')await page.screenshot({path:testInfo.outputPath('calendar-editor.png')});await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);const saved=await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0]);expect(saved).toMatchObject({...before,end:before.end+(mode==='overlap'?0:86400000),title:'Edited complex event',revision:expect.any(String)});expect(saved.revision).not.toBe(before.revision);await page.reload();expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0])).toEqual(saved);
});
test('editor rejects nonexistent times, stale saves, and cancellation without replacing the event',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'Original',body:'',location:'',begin:Date.parse('2027-03-14T06:30:00Z'),end:Date.parse('2027-03-15T06:30:00Z')});const row=JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0];(window as any).editing=cal.edit({id:row.id,revision:row.revision});});const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await dialog.getByLabel('Time zone',{exact:true}).fill('America/New_York');await dialog.getByLabel('Starts',{exact:true}).fill('2027-03-14T02:30');await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('does not exist');await dialog.getByLabel('Starts',{exact:true}).fill('2027-03-14T03:30');await page.evaluate(()=>{const key='alpha.browser.calendar.v1',data=JSON.parse(localStorage.getItem(key)!);data.events[0].revision='c'.repeat(64);data.events[0].title='Other tab';localStorage.setItem(key,JSON.stringify(data));});await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('This event changed');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).editing)).toEqual({status:'cancelled'});expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].title)).toBe('Other tab');
});
