import {test,expect} from '@playwright/test';
for(const kind of ['email','calendar'])test(`reviewed live ${kind} reads fresh bounded browser data`,async({page})=>{
 await page.clock.install({time:new Date('2026-10-03T12:00:10Z')});await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.evaluate(()=>window.dispatchEvent(new Event('alpha:hosted-digests')));const panel=page.getByRole('dialog',{name:'Scheduled digests',exact:true});
 await panel.getByText('Use live Google data',{exact:true}).click();await panel.getByRole('button',{name:'Refresh connected accounts',exact:true}).click();await panel.getByRole('combobox',{name:'Google account',exact:true}).selectOption({index:1});await panel.getByLabel('Read scope',{exact:true}).selectOption(kind);if(kind==='calendar'){await panel.getByRole('button',{name:'Load calendars',exact:true}).click();await panel.getByLabel('Calendar',{exact:true}).selectOption('local');}
 await panel.getByLabel('Maximum source items',{exact:true}).fill('1');await panel.getByLabel('Source window hours',{exact:true}).fill('1');await panel.getByRole('button',{name:'Review live source',exact:true}).click();await panel.getByRole('button',{name:'Confirm',exact:true}).click();await panel.getByRole('combobox',{name:'Reviewed source',exact:true}).selectOption({index:1});await panel.getByLabel('Time zone',{exact:true}).fill('UTC');await panel.getByLabel('Morning',{exact:true}).fill('12:01');await panel.getByRole('button',{name:'Review morning schedule',exact:true}).click();await panel.getByRole('button',{name:'Confirm',exact:true}).click();await expect(panel.getByRole('button',{name:'Review morning schedule',exact:true})).toBeVisible();
 await page.evaluate(kind=>{const now=Date.now();if(kind==='email')localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[{id:'new',subj:'Fresh selected item',snippet:'Approved snippet',body:'PRIVATE BODY',atts:[{name:'PRIVATE FILE'}],receivedAt:now},{id:'older',subj:'Second matching item',receivedAt:now-1000},{id:'outside',subj:'Outside window',receivedAt:now-7200000},{id:'deleted',subj:'Deleted',receivedAt:now+1,del:true}]}));else localStorage.setItem('alpha.browser.calendar.v1',JSON.stringify({sourceRevision:'a'.repeat(64),events:[{id:'new',calendarId:'local',title:'Fresh selected item',body:'PRIVATE DESCRIPTION',location:'Here',begin:now+120000,end:now+180000,revision:'1'},{id:'older',calendarId:'local',title:'Second matching item',begin:now+240000,end:now+300000,revision:'2'},{id:'foreign',calendarId:'other',title:'Other calendar',begin:now+60000,end:now+100000,revision:'3'}]}));},kind);
 await page.clock.runFor(60000);await panel.getByRole('button',{name:'Refresh',exact:true}).click();await expect(panel.locator('pre')).toContainText('Fresh selected item');const result=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.digests.local.v1')!).results[0]);expect(result.output.items).toHaveLength(1);expect(result.output.truncated).toBe(true);expect(JSON.stringify(result)).not.toContain('PRIVATE');expect(result.source.live.kind).toBe(kind);expect(result.source.observedAt).not.toBe('2026-10-03T12:00:10.000Z');
});
test('stale live account revisions fail before private reads and foreign sources are not admitted',async({page})=>{
 await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{
 const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'local'}));const identity=developmentIdentity('local'),call=(path:string,body?:any)=>request(identity,'/api/workflow/hosted/'+path,body),accounts:any=await call('live-accounts'),account=accounts.accounts[0],body={id:crypto.randomUUID(),kind:'email',label:'Reviewed scope',confirmed:true,observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),live:{provider:'google',accountId:account.accountId,accountRevision:account.accountRevision,kind:'email',windowHours:1,maxItems:1}};
 let rejected=false;try{await call('sources',{...body,live:{...body.live,accountId:'browser:remote'}});}catch(error){rejected=(error as any).code==='HOSTED_SOURCE_NOT_SAVED';}const source:any=await call('sources',body);await call('loops',{mutationId:crypto.randomUUID(),confirmed:true,spec:{version:1,template:'morning',sourceId:source.source.id,sourceRevision:source.source.revision,enabled:true,timeZone:'UTC',localTime:new Date().toISOString().slice(11,16)}});
 const key='alpha.browser.digests.local.v1',state=JSON.parse(localStorage.getItem(key)!);state.liveRevision='f'.repeat(64);state.loops[0].createdAt=Date.now()-120000;localStorage.setItem(key,JSON.stringify(state));let reads=0;const get=Storage.prototype.getItem;Storage.prototype.getItem=function(key){if(key==='alpha.dev.app.inbox')reads++;return get.call(this,key);};try{await call('tick');}finally{Storage.prototype.getItem=get;}const saved=JSON.parse(localStorage.getItem(key)!);return {rejected,reads,sources:saved.sources.length,status:saved.results[0].status,output:saved.results[0].output,error:saved.results[0].error};
 });expect(result).toEqual({rejected:true,reads:0,sources:1,status:'failed',output:null,error:'Source access changed.'});
});
