import { returnToApps } from './app-navigation';
import {test,expect} from '@playwright/test';
for(const mode of ['future','all-day','hidden'] as const)test(`browser Calendar opens the exact ${mode} event`,async({page})=>{
 await page.addInitScript(mode=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));(localStorage.getItem('alpha.browser.calendar.v1')===null&&localStorage.setItem('alpha.browser.calendar.v1',JSON.stringify({sourceRevision:'a'.repeat(64),preferences:{visible:mode!=='hidden',color:'fg'},events:[{id:'destination',calendarId:'local',title:'Distant destination',body:'Exact event details',location:'Desk',begin:Date.parse('2028-04-02T00:00:00Z'),end:Date.parse('2028-04-03T00:00:00Z'),allDay:mode==='all-day',revision:'b'.repeat(64)}]})));},mode);
 await page.goto('/?mode=dev');const opened=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaCalendar').open({id:'destination'});});expect(opened).toEqual({status:'opened'});await expect(page.getByRole('button',{name:'Back to calendar',exact:true})).toBeVisible();await expect(page.getByText('Exact event details',{exact:true})).toBeVisible();expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).preferences.visible)).toBe(mode!=='hidden');await page.getByRole('button',{name:'Back to calendar',exact:true}).click();if(mode==='hidden')await expect(page.getByRole('button',{name:/^Distant destination,/})).toHaveCount(0);
});
test('missing Calendar event cannot report a successful open',async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');try{await registerPlugin<any>('AlphaCalendar').open({id:'missing'});return false;}catch{return true;}})).toBe(true);});
test('a delayed event open cannot take over after navigation away',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');const result=await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'Delayed event',begin:Date.parse('2028-04-02T12:00:00Z'),end:Date.parse('2028-04-02T13:00:00Z')});const {BrowserCalendar}=await import('/src/browser/calendar.ts');const list=BrowserCalendar.prototype.list;const gate=new Promise<void>(resolve=>{(window as any).releaseCalendarOpen=resolve;});BrowserCalendar.prototype.list=async function(input:any){await gate;return list.call(this,input);};(window as any).pendingCalendarOpen=cal.open({id:result.id});});await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseCalendarOpen)).toBe('function');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');(window as any).otherCalendarRead=registerPlugin<any>('AlphaCalendar').list({begin:Date.now(),end:Date.now()+60000});});await returnToApps(page);await page.evaluate(()=>(window as any).releaseCalendarOpen());expect(await page.evaluate(()=>(window as any).pendingCalendarOpen)).toEqual({status:'cancelled'});await expect(page.getByRole('button',{name:'Calendar',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Back to calendar',exact:true})).toHaveCount(0);
});
