import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.getByRole('button',{name:'Wallet',exact:true}).click();});
test('development card add, lock, default and removal persist without credentials or external requests',async({page})=>{
 const external:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))external.push(r.url());});await page.getByRole('button',{name:'Add card',exact:true}).first().click();await expect(page.getByRole('textbox')).toHaveCount(0);await page.getByRole('button',{name:'Development card card ending 0000',exact:true}).click({position:{x:35,y:22}});await page.getByRole('button',{name:'Lock card',exact:true}).click();await page.getByRole('button',{name:'Default card',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Wallet',exact:true}).click();await page.getByRole('button',{name:'Development card card ending 0000',exact:true}).click({position:{x:35,y:22}});await expect(page.getByRole('button',{name:'Lock card',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'Default card',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Remove card',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Wallet',exact:true}).click();await expect(page.getByRole('button',{name:'Development card card ending 0000',exact:true})).toHaveCount(0);const cards=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).cards);expect(cards.filter((c:any)=>c.def)).toHaveLength(1);expect(external).toEqual([]);
});
test('transit credit and matching transaction use one saved update and survive reload',async({page})=>{
 await page.getByText('Transit',{exact:true}).click();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).walletWrites=0;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.wallet')(window as any).walletWrites++;return set.call(this,key,value);};});await page.getByRole('button',{name:'$20',exact:true}).click();const state=await page.evaluate(()=>({writes:(window as any).walletWrites,data:JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!)}));expect(state.writes).toBe(1);expect(state.data.transit).toBeCloseTo(43.4);expect(state.data.cards.flatMap((c:any)=>c.tx).filter((t:any)=>t.m==='Transit reload'&&t.d===0)).toHaveLength(1);await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).transit)).toBeCloseTo(43.4);
});
test('failed transit save changes neither balance nor transactions and retries once',async({page})=>{
 await page.getByText('Transit',{exact:true}).click();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restoreWallet=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.wallet')throw Error('Storage full');return set.call(this,key,value);};});await page.getByRole('button',{name:'$20',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.wallet'))).toBeNull();await page.evaluate(()=>(window as any).restoreWallet());await page.getByRole('button',{name:'$20',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).transit)).toBeCloseTo(43.4);
});
test('simulated payment commits its transaction and count together without a payment service',async({page})=>{
 await page.getByRole('button',{name:'Add card',exact:true}).first().click();await page.getByRole('button',{name:'Development card card ending 0000',exact:true}).click({position:{x:35,y:22}});await page.getByRole('button',{name:'Pay',exact:true}).last().click();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).payWrites=0;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.wallet')(window as any).payWrites++;return set.call(this,key,value);};});await page.getByRole('button',{name:'Confirm with fingerprint',exact:true}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).pays)).toBe(1);const result=await page.evaluate(()=>({writes:(window as any).payWrites,card:JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).cards.find((c:any)=>c.name==='Development card')}));expect(result.writes).toBe(1);expect(result.card.tx).toHaveLength(1);await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).pays)).toBe(1);
});
test('failed simulated payment returns to review and explicit retry commits exactly once',async({page})=>{
 await page.getByRole('button',{name:'Add card',exact:true}).first().click();await page.getByRole('button',{name:'Development card card ending 0000',exact:true}).click({position:{x:35,y:22}});await page.getByRole('button',{name:'Pay',exact:true}).last().click();const before=await page.evaluate(()=>localStorage.getItem('alpha.dev.app.wallet'));await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restorePay=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.wallet')throw Error('Storage full');return set.call(this,key,value);};});await page.getByRole('button',{name:'Confirm with fingerprint',exact:true}).click();await expect(page.getByRole('button',{name:'Confirm with fingerprint',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Confirm with fingerprint',exact:true})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.wallet'))).toBe(before);await page.evaluate(()=>(window as any).restorePay());await page.getByRole('button',{name:'Confirm with fingerprint',exact:true}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).pays)).toBe(1);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.wallet')!).cards.find((c:any)=>c.name==='Development card').tx.length)).toBe(1);
});
