import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');});
test('file mutations serialize races and invalidate old selections without partial folder imports',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');const selected=await files.importFile(new File(['original'],'race.txt',{type:'text/plain'}));const row=(await files.list({})).entries[0];const attempts=await Promise.allSettled([files.rename({id:row.id,expectedRevision:row.revision,name:'winner-a.txt'}),files.rename({id:row.id,expectedRevision:row.revision,name:'winner-b.txt'})]);let stale=false;try{await files.readSelected(selected);}catch{stale=true;}let duplicate=false;try{await files.importDirectory([{path:'same.txt',file:new File(['a'],'a')},{path:'same.txt',file:new File(['b'],'b')}],'No partial folder');}catch{duplicate=true;}const folder=await files.importDirectory([{path:'nested/one.txt',file:new File(['one'],'one.txt',{type:'text/plain'})}],'Imported');const nested=await files.list({id:folder.entries[0].id});const entry=nested.entries[0];const text=await files.readSelected(await files.select({id:entry.id}));const binary=await files.readSelected(await files.importFile(new File([new Uint8Array([0,255,1])],'binary.bin',{type:'application/octet-stream'})));return {successes:attempts.filter(r=>r.status==='fulfilled').length,stale,duplicate,names:(await files.list({})).entries.map((e:any)=>e.name),text:text.text,binary:binary.status};});
 expect(result.successes).toBe(1);expect(result.stale).toBe(true);expect(result.duplicate).toBe(true);expect(result.names).not.toContain('No partial folder');expect(result.text).toBe('one');expect(result.binary).toBe('binary');
 await page.reload();expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaFiles').list({})).entries.some((e:any)=>e.name==='Imported');})).toBe(true);
});
test('PDF selection renders actual pages and releases previews',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 300] /Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length 43 >>\nstream\nBT /F1 16 Tf 20 100 Td (Browser PDF) Tj ET\nendstream'];let pdf='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=pdf.length;pdf+='xref\n0 7\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const selected=await files.importFile(new File([pdf],'pages.pdf',{type:'application/pdf'}));const first=await files.pdfSelected({...selected,page:0});const blob=await (await fetch(first.imageUri)).blob(),bitmap=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d')!;context.drawImage(bitmap,0,0);const ink=Array.from(context.getImageData(0,0,canvas.width,canvas.height).data).filter((value,index)=>index%4!==3&&value<128).length>100;const second=await files.pdfSelected({...selected,page:1});let released=false;try{await fetch(first.imageUri);}catch{released=true;}await files.forgetSelected(selected);let forgotten=false;try{await files.pdfSelected({...selected,page:0});}catch{forgotten=true;}return {status:first.status,count:first.pageCount,width:bitmap.width,height:bitmap.height,page:second.page,ink,released,forgotten};});
 expect(result).toEqual({status:'rendered',count:2,width:400,height:600,page:1,ink:true,released:true,forgotten:true});
 await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByText('Browser files',{exact:true}).first().click();await page.getByRole('button',{name:'Open pages.pdf',exact:true}).click();await expect(page.getByRole('img',{name:'Page 1 of 2',exact:true})).toBeVisible();await page.getByRole('button',{name:'Next PDF page',exact:true}).click();await expect(page.getByRole('img',{name:'Page 2 of 2',exact:true})).toBeVisible();await page.screenshot({path:'test-results/dev-parity-ui/pdf.png'});
});
test('Files renderer confirms folder creation and closes its mutation dialog',async({page})=>{
 await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByText('Browser files',{exact:true}).first().click();
 await page.getByRole('button',{name:'View and sort',exact:true}).click();await page.getByText('New folder',{exact:true}).click();
 await page.getByRole('textbox',{name:'Folder or file name'}).fill('UI folder');await page.getByRole('button',{name:'Create folder',exact:true}).click();await expect(page.getByRole('button',{name:'Open UI folder',exact:true})).toBeVisible();
});
test('mail attachment bridge preserves exact bytes and validates reviewed hashes',async({page})=>{
 const attachment=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles'),mail=registerPlugin<any>('AlphaMailAttachments');const selection=await files.importFile(new File(['Café\r\nExact bytes'],'letter.txt',{type:'text/plain'}));const result=await mail.readSelected(selection);let rejected=false;try{await mail.openReviewed({...result,reviewed:true,sha256:'0'.repeat(64)});}catch{rejected=true;}await mail.openReviewed({...result,reviewed:true});return {...result,rejected};});
 expect(attachment.rejected).toBe(true);expect(Buffer.from(attachment.dataBase64,'base64').toString('utf8')).toBe('Café\r\nExact bytes');const dialog=page.getByRole('dialog',{name:'Reviewed attachment'});await expect(dialog.getByText('Café Exact bytes')).toBeVisible();await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(dialog).toHaveCount(0);
});
test('opening imported HTML cannot execute against the app origin',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');const selection=await files.importFile(new File(['<h1>Imported document</h1><script>localStorage.setItem("untrusted-file-ran","yes");parent.document.body.innerHTML="changed";</script>'],'document.html',{type:'text/html'}));await files.openSelected(selection);});
 const dialog=page.getByRole('dialog',{name:'Selected document'});await expect(dialog.locator('iframe')).toHaveAttribute('sandbox','');await expect(dialog.frameLocator('iframe').getByRole('heading',{name:'Imported document'})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('untrusted-file-ran'))).toBeNull();await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(dialog).toHaveCount(0);
});
