import {genericCloudSpeechFixture} from './generic-cloud-speech-fixture';
import { returnToApps } from './app-navigation';
import {test,expect,type Page} from '@playwright/test';
const spoken=(page:Page)=>page.evaluate(()=>(window as any).speechTest.spoken);
async function fix(page:Page,latitude=43.738,accuracy=5){await page.evaluate(({latitude,accuracy})=>(window as any).geoFix({coords:{latitude,longitude:7.424,accuracy},timestamp:Date.now()}),{latitude,accuracy});}
test.beforeEach(async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));const s=(window as any).speechTest={spoken:[],voices:[{name:'Device',lang:'en-US',localService:true}],utterance:null,cancelled:0};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>s.voices,speak:(u:any)=>{s.spoken.push(u.text);s.utterance=u;},cancel:()=>s.cancelled++});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class {constructor(public text:string){}}});Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'granted'})}});Object.defineProperty(navigator,'geolocation',{value:{watchPosition:(fn:any)=>{(window as any).geoFix=fn;return 17;},clearWatch:()=>{(window as any).geoCleared=true;}}});});
 await page.goto('/?mode=dev');await genericCloudSpeechFixture(page);await page.evaluate(async()=>{const {configureMapsProvider}=await import('/src/maps/runtime.ts');const place={providerId:'fixture-region',id:'destination',name:'Test destination',coordinate:{latitude:43.741,longitude:7.424},attribution:'Fixture attribution',fetchedAt:Date.now()};configureMapsProvider({status:'configured',providerId:'fixture-region',connectionId:'conn_fixture_region_123456',revision:'fixture1',capabilities:{map:false,search:true,placeDetails:true,modes:['drive'],traffic:'none',transit:'none',offline:{map:false,search:false,routing:false}}},{providerId:'fixture-region',connectionId:'conn_fixture_region_123456',search:async()=>[place],detail:async()=>place,route:async(from,to,mode)=>({providerId:'fixture-region',id:'route',from,to,mode,geometry:[from,{latitude:43.739,longitude:7.424},to],distanceMeters:333,durationSeconds:223,steps:[{instruction:'Start here',coordinate:from,distanceMeters:0},{instruction:'Turn right',coordinate:{latitude:43.739,longitude:7.424},distanceMeters:111},{instruction:'Continue to destination',coordinate:to,distanceMeters:222}],attribution:'Fixture attribution',fetchedAt:Date.now(),traffic:'none'})});});
 await page.getByRole('button',{name:'Maps',exact:true}).click();const q=page.getByRole('textbox',{name:'Search places'});await q.fill('Test destination');await q.press('Enter');await page.getByRole('button',{name:/^Test destination/}).first().click();await page.getByRole('button',{name:'Directions',exact:true}).click();const origin=page.getByRole('textbox',{name:'Route origin coordinates'});await origin.fill('43.738, 7.424');await origin.press('Enter');await expect(page.getByText(/no live traffic/).first()).toBeVisible();await page.getByRole('button',{name:'Start',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof(window as any).geoFix)).toBe('function');
});
test('fresh navigation fixes speak each actual step once and arrival stops owned speech',async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toEqual(['Turn right']);await fix(page);expect(await spoken(page)).toEqual(['Turn right']);await fix(page,43.739);await expect.poll(()=>spoken(page)).toEqual(['Turn right','Continue to destination']);const before=await page.evaluate(()=>(window as any).speechTest.cancelled);await fix(page,43.741);await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.cancelled)).toBeGreaterThan(before);expect(await page.evaluate(()=>(window as any).geoCleared)).toBe(true);});
test('mute stops speech and enabling repeats the current valid instruction',async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toHaveLength(1);await page.getByRole('button',{name:'Mute voice guidance'}).click();await fix(page,43.739);expect(await spoken(page)).toHaveLength(1);await page.getByRole('button',{name:'Enable voice guidance'}).click();await expect.poll(()=>spoken(page)).toEqual(['Turn right','Continue to destination']);});
for(const kind of ['inaccurate','off-route','home','background','provider'])test(`navigation speech retires on ${kind}`,async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toHaveLength(1);const before=await page.evaluate(()=>(window as any).speechTest.cancelled);if(kind==='inaccurate')await fix(page,43.738,100);else if(kind==='off-route')await fix(page,43.75);else if(kind==='home')await returnToApps(page);else if(kind==='background')await page.evaluate(()=>window.dispatchEvent(new Event('alpha:device-state')));else await page.evaluate(async()=>{const {configureMapsProvider}=await import('/src/maps/runtime.ts');configureMapsProvider({status:'unconfigured'});});await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.cancelled)).toBeGreaterThan(before);});
test('muting while Cloud synthesis is pending prevents late playback',async({page})=>{await page.evaluate(()=>(window as any).speechTest.holdSynthesis=true);await fix(page);await page.getByRole('button',{name:'Mute voice guidance'}).click();await page.evaluate(()=>{(window as any).speechTest.releaseSynthesis?.();});expect(await spoken(page)).toEqual([]);});
test('another consumer replacement remains playing when Maps leaves',async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toHaveLength(1);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const voice=registerPlugin<any>('AlphaVoiceCloud');await voice.play(await voice.synthesizeLocal({text:'Other consumer'}));});await expect(page.getByRole('button',{name:'Enable voice guidance'})).toBeVisible();const count=await page.evaluate(()=>(window as any).speechTest.cancelled);await returnToApps(page);expect(await page.evaluate(()=>(window as any).speechTest.cancelled)).toBe(count);});

test('poor initial accuracy stays silent until a valid fix arrives',async({page})=>{await fix(page,43.738,100);expect(await spoken(page)).toEqual([]);await fix(page);await expect.poll(()=>spoken(page)).toEqual(['Turn right']);});
test('speech failure offers an explicit retry of the same instruction',async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toHaveLength(1);await page.evaluate(()=>(window as any).speechTest.utterance.onerror());await page.getByRole('button',{name:'Enable voice guidance'}).click();await expect.poll(()=>spoken(page)).toEqual(['Turn right','Turn right']);});

test('a fix midway along a route segment keeps guidance active',async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toEqual(['Turn right']);const before=await page.evaluate(()=>(window as any).speechTest.cancelled);await fix(page,43.740);expect(await page.evaluate(()=>(window as any).speechTest.cancelled)).toBe(before);await expect(page.getByText('Off route. Stop and calculate a new route.')).toHaveCount(0);});

test('retired location callbacks cannot restart navigation speech',async({page})=>{await fix(page);await expect.poll(()=>spoken(page)).toHaveLength(1);await returnToApps(page);await fix(page,43.739);expect(await spoken(page)).toEqual(['Turn right']);});
