import {test,expect,type Page} from '@playwright/test';
const initial=Date.parse('2026-10-02T06:59:50'),due=Date.parse('2026-10-02T07:00:01');
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!));
const read={k:'Read',t:'Contacts',apps:['Contacts']},note={k:'Write',t:'A note in Notes',apps:['Notes']},pickupStep={k:'Speak',t:'Speak it when I pick up the phone',apps:[]};
const flow=(id:number,steps:any[],trig:any={kind:'time',t:7})=>({id,name:'Concurrent '+id,on:true,trig,steps,runs:[]});
async function setup(page:Page,flows:any[]){await page.clock.setFixedTime(new Date(initial));await page.addInitScript(flows=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows,localRuns:{}}));const s=(window as any).speechFixture={spoken:[]};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>[{name:'Local',lang:'en-US',localService:true}],speak:(utterance:any)=>{s.spoken.push(utterance.text);s.current=utterance;},cancel:()=>{}});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{constructor(public text:string){}}});},flows);await page.goto('/?mode=dev');await page.evaluate(async()=>{const {Component}=await import('/src/prototype/model.js');const old=Component.prototype.api;Component.prototype.api=function(key:string){const api=old.call(this,key);if(key==='workflows')(window as any).concurrentApi=api;return api;};});await expect.poll(async()=>(await saved(page)).triggerState?.cursors.length).toBe(flows.length);await expect.poll(()=>page.evaluate(()=>!!(window as any).concurrentApi)).toBe(true);}
async function dueNow(page:Page){await page.clock.setFixedTime(new Date(due));}
async function statuses(page:Page){return Object.values((await saved(page)).localRuns).map((run:any)=>run.status);}
async function pickup(page:Page){await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Pick up phone',exact:true}).click();}
test('a waiting pickup does not block another scheduled workflow or lose either run',async({page})=>{await setup(page,[flow(901,[read,pickupStep]),flow(902,[read,note])]);await dueNow(page);await expect.poll(()=>statuses(page)).toEqual(['running','ok']);expect((await saved(page)).triggerState.queue).toEqual([]);const records=await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records);const second:any=Object.values((await saved(page)).localRuns).find((run:any)=>run.flowId===902);expect(records.find((note:any)=>note.id===second.id+'-1')).toBeTruthy();await pickup(page);await expect.poll(()=>page.evaluate(()=>(window as any).speechFixture.spoken.length)).toBe(1);await page.evaluate(()=>(window as any).speechFixture.current.onend());await expect.poll(()=>statuses(page)).toEqual(['ok','ok']);});
test('simultaneous Notes effects retain all results with separate run receipts',async({page})=>{await setup(page,[flow(901,[read,note]),flow(902,[read,note]),flow(903,[read,note])]);await dueNow(page);await expect.poll(()=>statuses(page)).toEqual(['ok','ok','ok']);const runs:any[]=Object.values((await saved(page)).localRuns),notes=await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records);for(const run of runs)expect(notes.filter((note:any)=>note.id===run.id+'-1')).toHaveLength(1);expect((await saved(page)).triggerState.queue).toEqual([]);});
test('later occurrences of the same workflow stay queued while another workflow can finish',async({page})=>{await setup(page,[flow(901,[pickupStep],{kind:'message',person:'maya'}),flow(902,[read,note])]);await page.evaluate(()=>{const api=(window as any).concurrentApi;api.setView('messages',{threads:{...api.get('messages').threads,maya:[{id:'first',k:1,me:false,text:'One'},{id:'second',k:2,me:false,text:'Two'}]}});});await expect.poll(()=>statuses(page)).toEqual(['running']);await expect.poll(async()=>(await saved(page)).triggerState.queue.length).toBe(1);await dueNow(page);await expect.poll(()=>statuses(page)).toEqual(['running','ok']);await pickup(page);await expect.poll(()=>page.evaluate(()=>(window as any).speechFixture.spoken.length)).toBe(1);await page.evaluate(()=>(window as any).speechFixture.current.onend());await expect.poll(()=>statuses(page)).toEqual(['ok','ok','running']);await pickup(page);await expect.poll(()=>page.evaluate(()=>(window as any).speechFixture.spoken.length)).toBe(2);await page.evaluate(()=>(window as any).speechFixture.current.onend());await expect.poll(()=>statuses(page)).toEqual(['ok','ok','ok']);});
test('two connected workflows serialize generation and both commit their Notes outputs',async({page})=>{await setup(page,[flow(901,[read,{k:'Write',t:'A short summary',apps:[]},note]),flow(902,[read,{k:'Write',t:'A short summary',apps:[]},note])]);await page.evaluate(async()=>{const {alphaClient}=await import('/src/runtime/alpha-client.ts');const w=window as any;w.requests=[];alphaClient.attachVerifiedTransport({session:{ownerId:'owner',agentId:'agent',sessionId:'session',origin:'https://fixture.example'},send:input=>{w.requests.push(input);return new Promise(resolve=>w.resolveText=resolve);},execute:async()=>{throw Error('No actions');}});});await dueNow(page);await expect.poll(()=>page.evaluate(()=>(window as any).requests.length)).toBe(1);await page.evaluate(()=>(window as any).resolveText({text:'First result'}));await expect.poll(()=>page.evaluate(()=>(window as any).requests.length)).toBe(2);await page.evaluate(()=>(window as any).resolveText({text:'Second result'}));await expect.poll(()=>statuses(page)).toEqual(['ok','ok']);const notes=await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records);expect(notes.some((note:any)=>note.body==='First result')).toBe(true);expect(notes.some((note:any)=>note.body==='Second result')).toBe(true);});
test('many pickup workflows queue speech without evicting each other or losing histories',async({page})=>{await setup(page,Array.from({length:10},(_,i)=>flow(900+i,[read,pickupStep])));await dueNow(page);await expect.poll(async()=>Object.values((await saved(page)).localRuns).filter((run:any)=>run.sum==='Waiting for pickup').length,{timeout:20000}).toBe(10);await pickup(page);for(let count=1;count<=10;count++){await expect.poll(()=>page.evaluate(()=>(window as any).speechFixture.spoken.length)).toBe(count);await page.evaluate(()=>(window as any).speechFixture.current.onend());}await expect.poll(()=>statuses(page)).toEqual(Array(10).fill('ok'));expect((await saved(page)).flows.every((flow:any)=>flow.runs.length===1)).toBe(true);});

test('cancelling a queued Notes writer leaves its lock owner and another workflow intact',async({page})=>{await setup(page,[flow(901,[read,note]),flow(902,[read,note])]);await page.evaluate(()=>{const w=window as any;w.held=navigator.locks.request('alpha.dev.workflow-resource.notes',()=>new Promise<void>(resolve=>{w.releaseNotes=resolve;}));});await expect.poll(()=>page.evaluate(()=>!!(window as any).releaseNotes)).toBe(true);await dueNow(page);await expect.poll(()=>statuses(page)).toEqual(['running','running']);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Concurrent 901',{exact:true}).click();await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(()=>statuses(page)).toEqual(['cancelled','running']);await page.evaluate(()=>(window as any).releaseNotes());await expect.poll(()=>statuses(page)).toEqual(['cancelled','ok']);const rows:any[]=Object.values((await saved(page)).localRuns),notes=await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records);expect(notes.some((n:any)=>n.id===rows[0].id+'-1')).toBe(false);expect(notes.some((n:any)=>n.id===rows[1].id+'-1')).toBe(true);});
