import {test,expect} from '@playwright/test';
async function open(page:any){await page.goto('/?mode=dev');await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'Month view',exact:true}).click();}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.browser.calendar.v1')){const start=new Date();start.setHours(12,0,0,0);localStorage.setItem('alpha.browser.calendar.v1',JSON.stringify({sourceRevision:'a'.repeat(64),events:[{id:'prefs-event',calendarId:'local',title:'Preference event',body:'',location:'',begin:+start,end:+start+3600000,revision:'b'.repeat(64)}]}));}});});
test('calendar visibility and color affect the timeline and persist across reload',async({page})=>{
 await open(page);const toggle=page.getByRole('button',{name:'Show Browser calendar calendar',exact:true});await expect(toggle).toHaveAttribute('aria-pressed','true');await toggle.click();await expect(toggle).toHaveAttribute('aria-pressed','false');await page.getByRole('button',{name:'Close month',exact:true}).click();await expect(page.getByRole('button',{name:/^Preference event,/})).toHaveCount(0);
 await open(page);await expect(toggle).toHaveAttribute('aria-pressed','false');await toggle.click();await expect(toggle).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Change Browser calendar color',exact:true}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).preferences.color)).toBe('fg');await page.getByRole('button',{name:'Close month',exact:true}).click();const event=page.getByRole('button',{name:/^Preference event,/});await expect(event).toBeVisible();await expect(event.locator('span').first()).toHaveAttribute('style',/background: var\(--fg\)/);
 await open(page);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).preferences)).toEqual({visible:true,color:'fg'});
});
test('calendar preferences synchronize across tabs and failed writes preserve saved controls',async({page,context})=>{
 await open(page);const other=await context.newPage();await open(other);const toggle=other.getByRole('button',{name:'Show Browser calendar calendar',exact:true});await page.getByRole('button',{name:'Show Browser calendar calendar',exact:true}).click();await expect(toggle).toHaveAttribute('aria-pressed','false');await other.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.calendar.v1')throw Error('Full');return original.call(this,key,value);};});await toggle.click();await expect(other.getByText('Calendar settings could not be saved. Try again.',{exact:true})).toBeVisible();await expect(toggle).toHaveAttribute('aria-pressed','false');expect(await other.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).preferences.visible)).toBe(false);await other.close();
});
