import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
async function start(page:any,repeat='none') {return page.evaluate(async(repeat:string)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar');const result=await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'Complex guests',body:'',location:'',begin:Date.parse('2026-11-01T00:00:00Z'),end:Date.parse('2026-11-03T00:00:00Z'),allDay:true,timeZone:'UTC',repeat,who:['alice'],video:true});const key='alpha.browser.calendar.v1',state=JSON.parse(localStorage.getItem(key)!);state.events[0].responses={alice:'yes'};localStorage.setItem(key,JSON.stringify(state));const row=(await cal.list({begin:Date.parse('2026-11-01T00:00:00Z'),end:Date.parse('2026-11-02T00:00:00Z')})).events[0];(window as any).editing=cal.edit({id:row.id,revision:row.revision,people:[{id:'alice',name:'Alice'},{id:'bob',name:'Bob'}]});return result.id;},repeat);}
test('complex editor saves guests, prunes removed responses, and persists meeting and alert controls',async({page})=>{
 await start(page);const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await dialog.getByLabel('Alice',{exact:true}).uncheck();await dialog.getByLabel('Bob',{exact:true}).check();await dialog.getByLabel('Local meeting room',{exact:true}).uncheck();await dialog.getByLabel('Event alert',{exact:true}).selectOption('60');await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0]);expect(saved).toMatchObject({who:['bob'],responses:{},video:false,alert:60,allDay:true});expect(Object.keys(saved.responses)).toEqual([]);await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0])).toEqual(saved);
});
test('occurrence guest changes do not replace sibling guest lists',async({page})=>{
 await start(page,'daily');const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await dialog.getByLabel('Bob',{exact:true}).check();await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);const rows=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaCalendar').list({begin:Date.parse('2026-11-01T00:00:00Z'),end:Date.parse('2026-11-04T00:00:00Z')})).events;});expect(rows[0].who).toEqual(['alice','bob']);expect(rows[0].responses.alice).toBe('yes');expect(rows[1].who).toEqual(['alice']);
});
test('failed guest save retains selections and cancellation leaves the saved event unchanged',async({page})=>{
 await start(page);const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await dialog.getByLabel('Bob',{exact:true}).check();await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as any).restore=()=>Storage.prototype.setItem=original;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.calendar.v1')throw Error('Storage full');return original.call(this,key,value);};});await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Storage full');await expect(dialog.getByLabel('Bob',{exact:true})).toBeChecked();await page.evaluate(()=>(window as any).restore());await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).editing)).toEqual({status:'cancelled'});expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0].who)).toEqual(['alice']);
});
test('rendered all-day event edit receives the Calendar contact choices',async({page},testInfo)=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),begin=Date.UTC(new Date().getFullYear(),new Date().getMonth(),new Date().getDate());const saved=await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'All-day people',body:'',location:'',begin,end:begin+86400000,allDay:true,who:['maya']});await cal.open({id:saved.id});});await page.getByRole('button',{name:'Edit event',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit calendar event'});await expect(dialog.getByRole('checkbox',{name:/Maya/})).toBeChecked();expect(await dialog.locator('fieldset input').count()).toBeGreaterThan(1);await page.screenshot({path:testInfo.outputPath('complex-guests.png')});await dialog.getByRole('checkbox',{name:/Maya/}).uncheck();await dialog.getByLabel('Local meeting room',{exact:true}).check();await dialog.getByRole('button',{name:'Save event',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0])).toMatchObject({who:[],video:true});
});
