import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-10-02T12:00:00Z'));await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
async function notices(page:any){return page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').list()).items.filter((n:any)=>n.id.startsWith('calendar:'));});}
test('rendered Calendar alert becomes due and opens the exact event from the shade',async({page})=>{
 await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Alert event');await page.getByRole('button',{name:'10 min',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);const row=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0]);expect(row.alert).toBe(10);expect(await notices(page)).toEqual([]);await page.clock.setFixedTime(new Date(row.begin-600000));await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();await page.getByRole('button',{name:'Open Alert event',exact:true}).click();await expect(page.getByRole('button',{name:'Back to calendar',exact:true})).toBeVisible();await expect.poll(()=>notices(page)).toEqual([]);await page.reload();expect(await notices(page)).toEqual([]);
});
test('repeating alerts dismiss only one date and title changes do not replay dismissed schedules',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').save({calendarId:'local',title:'Daily alert',body:'',location:'',begin:Date.now(),end:Date.now()+3600000,repeat:'daily',timeZone:'UTC',alert:0});});const [first]=await notices(page);expect(first).toBeTruthy();await page.evaluate(async(notice)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaNotifications').dismiss(notice);const cal=registerPlugin<any>('AlphaCalendar'),row=(await cal.list({begin:Date.now()-1,end:Date.now()+1})).events[0];await cal.save({...row,expected:row,title:'Renamed alert'});},first);expect(await notices(page)).toEqual([]);await page.clock.setFixedTime(new Date('2026-10-03T12:00:00Z'));const next=await notices(page);expect(next).toHaveLength(1);expect(next[0].id).not.toBe(first.id);
});
test('rescheduling invalidates stale alerts and the Calendar channel suppresses delivery',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').save({calendarId:'local',title:'Changed alert',body:'',location:'',begin:Date.now(),end:Date.now()+3600000,alert:0});});const [old]=await notices(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),row=JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0];await cal.save({...row,expected:row,begin:row.begin+3600000,end:row.end+3600000});});expect(await notices(page)).toEqual([]);expect(await page.evaluate(async(old)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');try{await registerPlugin<any>('AlphaNotifications').open(old);return false;}catch{return true;}},old)).toBe(true);await page.clock.setFixedTime(new Date('2026-10-02T13:00:00Z'));expect(await notices(page)).toHaveLength(1);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaNotifications').openChannelSettings({id:'calendar'});});const dialog=page.getByRole('dialog',{name:'Calendar notifications'});await dialog.getByRole('checkbox',{name:'Show calendar alerts'}).uncheck();await dialog.getByRole('button',{name:'Done',exact:true}).click();expect(await notices(page)).toEqual([]);
});
test('all-day alerts use local midnight in the saved zone, including the international date line',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-02T09:59:00Z'));await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').save({calendarId:'local',title:'Date line alert',body:'',location:'',begin:Date.parse('2026-10-03T00:00:00Z'),end:Date.parse('2026-10-04T00:00:00Z'),allDay:true,timeZone:'Pacific/Kiritimati',alert:0});});expect(await notices(page)).toEqual([]);await page.clock.setFixedTime(new Date('2026-10-02T10:00:00Z'));const result=await notices(page);expect(result).toHaveLength(1);expect(result[0].at).toBe(Date.parse('2026-10-02T10:00:00Z'));
});
test('failed dismissal preserves the active alert and deletion removes it without a stale open',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').save({calendarId:'local',title:'Durable alert',body:'',location:'',begin:Date.now(),end:Date.now()+3600000,alert:0});});const [notice]=await notices(page);expect(await page.evaluate(async(notice)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.browser.calendar.v1')throw Error('Full');return original.call(this,key,value);};try{await registerPlugin<any>('AlphaNotifications').dismiss(notice);return false;}catch{return true;}finally{Storage.prototype.setItem=original;}},notice)).toBe(true);expect(await notices(page)).toHaveLength(1);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const row=JSON.parse(localStorage.getItem('alpha.browser.calendar.v1')!).events[0];await registerPlugin<any>('AlphaCalendar').remove({...row,expected:row});});expect(await notices(page)).toEqual([]);expect(await page.evaluate(async(notice)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');try{await registerPlugin<any>('AlphaNotifications').open(notice);return false;}catch{return true;}},notice)).toBe(true);
});
