import {readFileSync} from 'node:fs';
import {test,expect,type Page} from '@playwright/test';
const key='alpha.dev.app.workflows';
const state=(page:Page)=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key);
async function open(page:Page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('History flow',{exact:true}).click();}
async function history(page:Page){await page.getByRole('button',{name:'Workflow history',exact:true}).click();return page.getByRole('dialog',{name:'Workflow history',exact:true});}
test.beforeEach(async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-02T07:00:00'));
 await page.addInitScript(()=>{const revoke=URL.revokeObjectURL;(window as any).revokedHistory=[];URL.revokeObjectURL=url=>{(window as any).revokedHistory.push(url);revoke.call(URL,url);};localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.dev.app.workflows')){const runs=['ok','fail','skip','cancelled','interrupted'].map((status,i)=>({id:'run-'+i,flowId:996,status,when:'Saved',sum:status,dur:'1 s',out:'Exact output '+i,log:[],cursor:0,inflight:null}));localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:996,name:'History flow',on:true,short:'Recover local capacity',summary:'Local history',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']}],runs}],localRuns:Object.fromEntries(runs.map(run=>[run.id,run]))}));localStorage.setItem('alpha.browser.workflow-notices.v1',JSON.stringify({rows:[{id:'workflow:prior',text:'Keep receipt',revision:'r',phase:'dismissed'}]}));}});
 await page.goto('/?mode=dev');await open(page);await expect.poll(async()=>(await state(page)).triggerState?.cursors.length).toBe(1);
});
test('exports exact reviewed snapshot and removes only finished runs across reload',async({page})=>{
 const before=await state(page),exported={flows:before.flows,localRuns:before.localRuns},notice=await page.evaluate(()=>localStorage.getItem('alpha.browser.workflow-notices.v1'));const dialog=await history(page);
 await expect(dialog.getByRole('status',{name:'Run history status',exact:true})).toHaveText('4 finished runs can be removed.');const href=await dialog.getByRole('link',{name:'Download history'}).getAttribute('href');expect(JSON.parse(await page.evaluate(async href=>await(await fetch(href!)).text(),href))).toEqual(exported);
 const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('link',{name:'Download history'}).click()]);expect(download.suggestedFilename()).toBe('alpha-workflow-history.json');expect(JSON.parse(readFileSync((await download.path())!,'utf8'))).toEqual(exported);
 await page.screenshot({path:'test-results/workflow-history.png'});await dialog.getByRole('button',{name:'Remove finished runs',exact:true}).click();expect(await state(page)).toEqual(before);await dialog.getByRole('button',{name:'Confirm remove finished runs',exact:true}).click();await expect(dialog.getByRole('status',{name:'Run history status',exact:true})).toHaveText('Removed 4 finished runs.');
 const after=await state(page);expect(after.triggerState).toEqual(before.triggerState);expect(after.flows[0].steps).toEqual(before.flows[0].steps);expect(after.flows[0].runs.map((r:any)=>r.id)).toEqual(['run-4']);expect(Object.keys(after.localRuns)).toEqual(['run-4']);expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.workflow-notices.v1'))).toBe(notice);
 await dialog.getByRole('button',{name:'Close history'}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(()=>(window as any).revokedHistory)).toContain(href);expect(await page.evaluate(async href=>{try{await fetch(href!);return false;}catch{return true;}},href)).toBe(true);await page.reload();expect(await state(page)).toEqual(after);
});
test('stale persisted history refuses cleanup without overwriting newer data',async({page})=>{
 const dialog=await history(page);await dialog.getByRole('button',{name:'Remove finished runs',exact:true}).click();const changed=await page.evaluate(key=>{const s=JSON.parse(localStorage.getItem(key)!);s.flows[0].name='Newer name';const raw=JSON.stringify(s);localStorage.setItem(key,raw);return raw;},key);
 await dialog.getByRole('button',{name:'Confirm remove finished runs',exact:true}).click();await expect(dialog.getByRole('status',{name:'Run history status',exact:true})).not.toContainText('Removed');expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBe(changed);
});
test('failed storage write preserves all history',async({page})=>{
 const before=await state(page);const dialog=await history(page);await page.evaluate(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.workflows')throw new DOMException('Full','QuotaExceededError');return set.call(this,key,value);};});await dialog.getByRole('button',{name:'Remove finished runs',exact:true}).click();await dialog.getByRole('button',{name:'Confirm remove finished runs',exact:true}).click();await expect(dialog.getByRole('status',{name:'Run history status',exact:true})).not.toContainText('Removed');expect(await state(page)).toEqual(before);
});
test('full run journal can be reclaimed and execute a fresh run',async({page})=>{
 await page.evaluate(key=>{const s=JSON.parse(localStorage.getItem(key)!);s.flows[0].runs=[s.flows[0].runs[0]];s.flows[0].runs[0].out='x'.repeat(980000);s.localRuns={'run-0':s.flows[0].runs[0]};localStorage.setItem(key,JSON.stringify(s));},key);await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await state(page)).flows[0].runs[0].status).toBe('fail');expect((await state(page)).flows[0].runs[0].sum).toContain('history is full');
 const dialog=await history(page);await dialog.getByRole('button',{name:'Remove finished runs',exact:true}).click();await dialog.getByRole('button',{name:'Confirm remove finished runs',exact:true}).click();await dialog.getByRole('button',{name:'Close history'}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await state(page)).flows[0].runs[0].status).toBe('ok');expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw())!).doNotDisturb)).toBe(true);
});
test('a running workflow disables removal',async({page})=>{
 await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');BrowserDevice.prototype.setSensor=()=>new Promise(()=>{});});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await state(page)).flows[0].runs[0].status).toBe('running');const dialog=await history(page);await expect(dialog.getByRole('button',{name:'Remove finished runs',exact:true})).toBeDisabled();await expect(dialog.getByRole('status',{name:'Run history status',exact:true})).toContainText('Wait for running workflows');
});
test('backgrounding closes history and revokes its download',async({page})=>{const dialog=await history(page);const href=await dialog.getByRole('link',{name:'Download history'}).getAttribute('href');await page.evaluate(()=>window.dispatchEvent(new Event('alpha:device-state')));await expect(dialog).toHaveCount(0);expect(await page.evaluate(()=>(window as any).revokedHistory)).toContain(href);expect(await page.evaluate(async href=>{try{await fetch(href!);return false;}catch{return true;}},href)).toBe(true);});
