import {test,expect,type Page} from '@playwright/test';
// These complete setup journeys include browser startup and multiple persisted transitions.
// WebKit/Firefox cold starts can consume most of the default 30-second budget.
test.describe.configure({timeout:60_000});
async function setup(page:Page,scenario:string){await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Use development account'}).click();await page.getByText('Development setup scenario',{exact:true}).click();await page.getByRole('combobox',{name:'Setup scenario'}).selectOption(scenario);await page.getByRole('button',{name:'Reset development setup'}).click();await expect(page.getByRole('button',{name:'Reset development setup'})).toBeEnabled();}
async function finish(page:Page){await expect(page.getByText('Dedicated setup accepted',{exact:true})).toBeVisible();await expect.poll(async()=>{const check=page.getByRole('button',{name:'Check setup status'});await check.click();await expect(check).toBeEnabled();return page.getByRole('button',{name:'Continue setup',exact:true}).count();}).toBe(1);await page.getByRole('button',{name:'Continue setup',exact:true}).click();await expect(page.getByText('Dedicated ready',{exact:true})).toBeVisible();}
test('existing Dedicated adoption completes through the shared review',async({page})=>{await setup(page,'existing');await expect(page.getByText('Use your existing Dedicated Eliza',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Use existing Dedicated',exact:true}).click();await finish(page);});
test('insufficient sample balance disables activation and permits recovery',async({page})=>{await setup(page,'insufficient');await expect(page.getByRole('button',{name:'Start Dedicated',exact:true})).toBeDisabled();expect(await page.evaluate(async()=>{const {developmentCloudAccount,developmentCloudSetupDocument}=await import('/src/browser/development-cloud.ts');return (await developmentCloudSetupDocument(developmentCloudAccount()!).read()).phase;})).toBe('review');await page.getByRole('combobox',{name:'Setup scenario'}).selectOption('new');await page.getByRole('button',{name:'Reset development setup'}).click();await expect(page.getByRole('button',{name:'Start Dedicated',exact:true})).toBeEnabled();});
test('changed quote requires review of the new amounts before activation',async({page})=>{await setup(page,'changed');await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await expect(page.getByText('$4.80/day · $0.20/hour',{exact:true})).toBeVisible();expect(await page.evaluate(async()=>{const {developmentCloudAccount,developmentCloudSetupDocument}=await import('/src/browser/development-cloud.ts');return (await developmentCloudSetupDocument(developmentCloudAccount()!).read()).phase;})).toBe('review');await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await finish(page);});
test('failed provisioning refreshes into reviewed existing-instance recovery',async({page})=>{await setup(page,'failed');await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await expect(page.getByText('Dedicated setup accepted',{exact:true})).toBeVisible();await expect.poll(async()=>{const check=page.getByRole('button',{name:'Check setup status'});await check.click();await expect(check).toBeEnabled();return page.getByRole('alert').count();}).toBe(1);await page.getByRole('button',{name:'Refresh development setup'}).click();await expect(page.getByText('Use your existing Dedicated Eliza',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Use existing Dedicated',exact:true}).click();await finish(page);});
