import {test,expect} from '@playwright/test';
for(const provider of ['paired','cloud'] as const)test(`${provider} selection uses a complete local development recording route`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');
 await page.evaluate(async provider=>{
  const speech=(window as any).speechFixture={utterance:null as any};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>[{name:'Local',lang:'en-US',localService:true}],speak:(u:any)=>{speech.utterance=u;},cancel:()=>{}});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class {constructor(public text:string){}}});
  const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');
  if(provider==='cloud')c.getCloudEnvironment=()=> 'production' as any;
  else c.getPairedVoiceBinding=()=>({origin:'https://voice-fixture.invalid',ownerId:'fixture',sessionId:'fixture',expiresAt:Date.now()+60000});
  const ctx=new AudioContext(),osc=ctx.createOscillator(),sink=ctx.createMediaStreamDestination();osc.connect(sink);osc.start();await ctx.resume();Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>sink.stream}});(window as any).voiceFixture={ctx,osc};
 },provider);
 await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Record and transcribe',exact:true}).click();await page.getByRole('button',{name:'Use development voice',exact:true}).click();await expect(page.getByText('Development voice uses browser recording, transcript review and playback.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Start recording',exact:true}).click();await page.waitForTimeout(400);await page.getByRole('button',{name:'Stop recording',exact:true}).click();await page.getByRole('button',{name:'Review browser transcript',exact:true}).click();await page.getByRole('textbox',{name:'Transcript',exact:true}).fill('Development connected voice note');await page.getByRole('button',{name:'Use transcript',exact:true}).click();await expect(page.getByRole('button',{name:'Listen to transcript',exact:true})).toBeVisible();await page.getByRole('button',{name:'Listen to transcript',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).speechFixture.utterance?.text)).toBeTruthy();await page.evaluate(()=>(window as any).speechFixture.utterance.onend());await expect(page.getByRole('button',{name:'Listen to transcript',exact:true})).toBeVisible();await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByRole('button',{name:'Play recording',exact:true})).toBeVisible();await page.evaluate(async()=>{const f=(window as any).voiceFixture;f.osc.stop();await f.ctx.close();});expect(errors).toEqual([]);
});
