import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&tools=1&shell=launcher');});
async function shade(page:any){await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Notifications',exact:true}).click();}
test('shade and settings share persisted Wi-Fi and Bluetooth state',async({page})=>{
 await shade(page);const wifi=page.getByRole('button',{name:'Wi-Fi',exact:true}),bt=page.getByRole('button',{name:'Bluetooth',exact:true});await expect(wifi).toHaveAttribute('aria-pressed','true');await expect(bt).toHaveAttribute('aria-pressed','false');await wifi.click();await bt.click();await expect(wifi).toHaveAttribute('aria-pressed','false');await expect(bt).toHaveAttribute('aria-pressed','true');await page.reload();await shade(page);await expect(wifi).toHaveAttribute('aria-pressed','false');await expect(bt).toHaveAttribute('aria-pressed','true');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').openSettings({page:'wifi'});});const d=page.getByRole('dialog',{name:'wifi settings'});await expect(d.getByRole('checkbox',{name:'wifi Active',exact:true})).not.toBeChecked();await d.getByRole('checkbox',{name:'wifi Active',exact:true}).check();await d.getByRole('button',{name:'Done'}).click();await expect(wifi).toHaveAttribute('aria-pressed','true');
});
test('airplane mode disables radios atomically and restores its saved values after reload',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('AlphaDevice');await d.setNetwork({field:'bluetoothActive',enabled:true});await d.setNetwork({field:'cellularActive',enabled:true});});await shade(page);await page.getByRole('button',{name:'Airplane mode',exact:true}).click();for(const name of ['Wi-Fi','Bluetooth'])await expect(page.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','false');await page.reload();await shade(page);await expect(page.getByRole('button',{name:'Airplane mode',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Airplane mode',exact:true}).click();for(const name of ['Wi-Fi','Bluetooth'])await expect(page.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw())!).cellularActive)).toBe(true);
});
test('cross-tab changes update shade and open dialogs; failed writes preserve all network values',async({page,context})=>{
 await shade(page);const other=await context.newPage();await other.goto('/?mode=dev');await other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setNetwork({field:'wifiActive',enabled:false});});await expect(page.getByRole('button',{name:'Wi-Fi',exact:true})).toHaveAttribute('aria-pressed','false');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').openSettings({page:'wifi'});});await other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setNetwork({field:'wifiActive',enabled:true});});const d=page.getByRole('dialog',{name:'wifi settings'});await expect(d.getByRole('checkbox',{name:'wifi Active',exact:true})).toBeChecked();await d.getByRole('checkbox',{name:'airplane Mode',exact:true}).check();await expect(d.getByRole('checkbox',{name:'wifi Active',exact:true})).not.toBeChecked();
 await page.evaluate(()=>{const set=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.device.v1')throw Error('Full');return set.call(this,value,key);};});await d.getByRole('checkbox',{name:'airplane Mode',exact:true}).click();await expect(d.getByRole('status')).toContainText('could not be confirmed');await expect(d.getByRole('checkbox',{name:'airplane Mode',exact:true})).toBeChecked();await expect(d.getByRole('checkbox',{name:'wifi Active',exact:true})).not.toBeChecked();await other.close();
});
