import {test,expect,type Page} from '@playwright/test';
async function open(page:Page){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();}
async function start(page:Page){await page.goto('/?mode=dev');await open(page);await page.getByRole('button',{name:'Use development account'}).click();await expect(page.getByRole('region',{name:'Dedicated hosting review'})).toBeVisible();}
test('development Cloud review completes locally and connects the chat consumer',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await expect(page.getByText('Dedicated setup accepted',{exact:true})).toBeVisible();await expect.poll(async()=>{await page.getByRole('button',{name:'Check setup status'}).click();return await page.getByRole('button',{name:'Continue setup',exact:true}).count();}).toBe(1);await page.getByRole('button',{name:'Continue setup',exact:true}).click();await expect(page.getByText('Dedicated ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Connect this agent'}).click();await expect(page.getByRole('dialog',{name:'Development connections'})).toHaveCount(0);await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('hello');await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).press('Enter');await expect(page.getByText('Development reply. Edit this response in Agent connection.',{exact:true})).toBeVisible();
});
test('accepted setup recovers after reload and remains isolated across sample accounts',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await expect(page.getByText('Dedicated setup accepted',{exact:true})).toBeVisible();await page.reload();await open(page);await page.getByRole('button',{name:'Refresh development setup'}).click();await expect(page.getByText('Dedicated setup accepted',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Sample account'}).selectOption('second');await page.getByRole('button',{name:'Use development account'}).click();await expect(page.getByRole('region',{name:'Dedicated hosting review'})).toBeVisible();await page.getByRole('button',{name:'Not now',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.cloud.setup.second.v1'))).toBeNull();await page.getByRole('button',{name:'Sign out development account'}).click();await expect(page.getByRole('button',{name:'Refresh development setup'})).toHaveCount(0);await page.reload();await open(page);await expect(page.getByRole('button',{name:'Refresh development setup'})).toHaveCount(0);
});
test('failed setup persistence retains a review recovery path without starting hosting',async({page})=>{
 await start(page);await page.evaluate(()=>{const write=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='alpha.browser.cloud.setup.first.v1')throw Error('Full');return write.call(this,k,v);};});await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.cloud.setup.first.v1'))).toBeNull();await page.getByRole('button',{name:'Refresh development setup'}).click();await expect(page.getByRole('button',{name:'Start Dedicated',exact:true})).toBeEnabled();
});
test('Home cancels account selection waiting behind the storage lock',async({page})=>{
 await page.goto('/?mode=dev');await open(page);await page.evaluate(async()=>{await new Promise<void>(ready=>{void navigator.locks.request('alpha.browser.cloud.account.v1',async()=>{ready();await new Promise<void>(resolve=>(window as any).releaseCloud=resolve);});});});await page.getByRole('button',{name:'Use development account'}).click();await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));await expect(page.getByRole('dialog',{name:'Development connections'})).toHaveCount(0);await page.evaluate(()=>(window as any).releaseCloud());await page.evaluate(()=>navigator.locks.request('alpha.browser.cloud.account.v1',()=>{}));expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.cloud.account.v1'))).toBeNull();
});
test('another tab changing the account retires a queued setup write',async({page,context})=>{
 await start(page);const other=await context.newPage();await other.goto('/?mode=dev');await open(other);await page.evaluate(async()=>{await new Promise<void>(ready=>{void navigator.locks.request('alpha.browser.cloud.setup.first.v1',async()=>{ready();await new Promise<void>(resolve=>(window as any).releaseSetup=resolve);});});});await page.getByRole('button',{name:'Start Dedicated',exact:true}).click();await other.getByRole('combobox',{name:'Sample account'}).selectOption('second');await other.getByRole('button',{name:'Use development account'}).click();await expect(page.getByText('Connected development account: second',{exact:true})).toBeVisible();await page.evaluate(()=>(window as any).releaseSetup());await page.evaluate(()=>navigator.locks.request('alpha.browser.cloud.setup.first.v1',()=>{}));expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.cloud.setup.first.v1'))).toBeNull();await expect(page.getByRole('region',{name:'Dedicated hosting review'})).toHaveCount(0);
});
