import {test,expect,Page} from '@playwright/test';
const runs=(page:Page)=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]);
async function open(page:Page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Read files',{exact:true}).click();}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.dev.app.workflows'))localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:995,name:'Read files',on:true,short:'Managed Files input',summary:'Read local file data',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Read',t:'Recent files',apps:['Files']}],runs:[]}],localRuns:{}}));});await page.goto('/?mode=dev');await open(page);});
test('workflow reads nested text and binary metadata from actual Files after reload',async({page})=>{await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');await files.importDirectory([{path:'nested/a.txt',file:new File(['Exact UTF-8 café\nSecond line'],'a.txt',{type:'text/plain'})},{path:'image.png',file:new File([new Uint8Array([137,80,78,71])],'image.png',{type:'image/png'})}],'Imported');});await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await runs(page))[0]?.status).toBe('ok');const output=JSON.parse((await runs(page))[0].out);expect(output.files).toHaveLength(2);const text=output.files.find((f:any)=>f.name==='a.txt'),binary=output.files.find((f:any)=>f.name==='image.png');expect(text.text).toBe('Exact UTF-8 café\nSecond line');expect(text.contentStatus).toBe('text');expect(text.modifiedAt).toBeGreaterThan(0);expect(binary.contentStatus).toBe('binary');expect(binary.text).toBeUndefined();expect(binary.size).toBe(4);});
test('recent Files uses the latest twenty and rename updates its ordering',async({page})=>{for(let i=0;i<22;i++){await page.clock.setFixedTime(new Date(1800000000000+i*1000));await page.evaluate(async i=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');const selected=await f.importFile(new File(['Row '+i],i+'.txt',{type:'text/plain'}));await f.forgetSelected(selected);},i);}const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');const before=await f.workflowFiles({recent:true});const old=(await f.list({})).entries.find((e:any)=>e.name==='0.txt');await f.rename({id:old.id,expectedRevision:old.revision,name:'Renamed.txt'});return {before,after:await f.workflowFiles({recent:true}),all:await f.workflowFiles({recent:false})};});expect(result.before.files.map((f:any)=>f.name)).toEqual(Array.from({length:20},(_,i)=>(21-i)+'.txt'));expect(result.after.files).toHaveLength(20);expect(result.after.files.slice(0,2).some((f:any)=>f.name==='Renamed.txt')).toBe(true);expect(result.all.files).toHaveLength(22);});
async function held(page:Page){await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles'),selected=await f.importFile(new File(['Hold this workflow file read'],'held.txt',{type:'text/plain'}));await f.forgetSelected(selected);const original=Blob.prototype.arrayBuffer;let release!:()=>void;const gate=new Promise<void>(r=>release=r);(window as any).releaseFile=release;Blob.prototype.arrayBuffer=async function(){(window as any).fileHeld=true;await gate;return original.call(this);};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).fileHeld)).toBe(true);}
test('cancelled Files read cannot complete after bytes arrive',async({page})=>{await held(page);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');await page.evaluate(()=>(window as any).releaseFile());expect((await runs(page))[0].cursor).toBe(0);});
test('a rename during a held Files read rejects stale results',async({page})=>{await held(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles'),row=(await f.list({})).entries.find((e:any)=>e.name==='held.txt');await f.rename({id:row.id,expectedRevision:row.revision,name:'Changed.txt'});(window as any).releaseFile();});await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect((await runs(page))[0].sum).toContain('Files changed');expect((await runs(page))[0].cursor).toBe(0);});
test('oversized text rejects the complete Files read and invalid UTF-8 never invents content',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');
  for(const file of [new File(['Exact small source'],'small.txt',{type:'text/plain'}),new File([new Uint8Array([255,254])],'invalid.txt',{type:'text/plain'})]){
   const selected=await files.importFile(file);await files.forgetSelected(selected);
  }
  const before=await files.workflowFiles({recent:true});
  const selected=await files.importFile(new File(['x'.repeat(16001)],'large.txt',{type:'text/plain'}));await files.forgetSelected(selected);
  try{return {before,returned:await files.workflowFiles({recent:true}),error:null};}
  catch(error){return {before,returned:null,error:{name:error.name,message:error.message}};}
 });
 expect(result.before.files.find((row:any)=>row.name==='small.txt').text).toBe('Exact small source');
 const invalid=result.before.files.find((row:any)=>row.name==='invalid.txt');expect(invalid.contentStatus).toBe('binary');expect(invalid.text).toBeUndefined();
 expect(result.returned).toBeNull();expect(result.error?.name).toBe('FilesSourceReadError');expect(result.error?.message).toContain('No partial source was returned');
 await page.getByRole('button',{name:'Run now',exact:true}).click();
 await expect.poll(async()=>(await runs(page))[0]?.status).toBe('fail');
 const run=(await runs(page))[0];expect(run.cursor).toBe(0);expect(run.sum).toContain('16,000-byte');expect(run.out||'').not.toContain('Exact small source');
});
test('legacy files retain unknown dates instead of inventing recency',async({page})=>{const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');for(const name of ['legacy.txt','dated.txt']){const selected=await f.importFile(new File([name],name,{type:'text/plain'}));await f.forgetSelected(selected);}await new Promise<void>((resolve,reject)=>{const request=indexedDB.open('alpha.browser.files.v1');request.onsuccess=()=>{const database=request.result,tx=database.transaction('entries','readwrite'),store=tx.objectStore('entries'),get=store.getAll();get.onsuccess=()=>{const row=get.result.find((r:any)=>r.name==='legacy.txt');delete row.createdAt;delete row.modifiedAt;store.put(row);};tx.oncomplete=()=>{database.close();resolve();};tx.onerror=()=>reject(tx.error);};request.onerror=()=>reject(request.error);});return (await f.workflowFiles({recent:true})).files;});expect(result.map((r:any)=>r.name)).toEqual(['dated.txt','legacy.txt']);expect(result[1].createdAt).toBeNull();expect(result[1].modifiedAt).toBeNull();expect(result[1].text).toBe('legacy.txt');});

test('Files growing beyond the all-files limit cannot report a complete snapshot',async({page})=>{
 const error=await page.evaluate(async()=>{
  const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');await files.list({});
  const database=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('alpha.browser.files.v1');r.onupgradeneeded=()=>r.result.createObjectStore('entries',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  const put=async(rows:any[])=>new Promise<void>((resolve,reject)=>{const tx=database.transaction('entries','readwrite');for(const row of rows)tx.objectStore('entries').put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});
  const entry=(id:string)=>({id,parentId:'root',name:id+'.bin',mimeType:'application/octet-stream',directory:false,size:0,revision:id,modifiedAt:1});
  const rows=Array.from({length:2000},(_,i)=>entry('file-'+String(i).padStart(4,'0')));Object.assign(rows[0],{mimeType:'text/plain',size:1,bytes:new TextEncoder().encode('a').buffer});await put(rows);
  let start!:()=>void,release!:()=>void;const started=new Promise<void>(r=>start=r),gate=new Promise<void>(r=>release=r),original=Blob.prototype.arrayBuffer;
  Blob.prototype.arrayBuffer=async function(){start();await gate;return original.call(this);};
  const pending=files.workflowFiles({recent:false});await started;await put([entry('zz-new')]);release();
  try{await pending;return '';}catch(error){return String(error);}finally{Blob.prototype.arrayBuffer=original;database.close();}
 });expect(error).toContain('Choose a smaller Files source');
});

test('byte-backed imports preserve binary payloads through rename move and reload without leaking storage',async({page})=>{
 await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles();await f.importFile(new File([new Uint8Array([0,255,128,1,13,10])],'payload.bin',{type:'application/octet-stream'}));await f.createFolder({id:'root',name:'Destination'});const rows=(await f.list({})).entries;let file=rows.find(r=>r.name==='payload.bin')!;const folder=rows.find(r=>r.directory)!;await f.rename({id:file.id,expectedRevision:file.revision,name:'renamed.bin'});file=(await f.list({})).entries.find(r=>r.id===file.id)!;await f.move({id:file.id,expectedRevision:file.revision,destinationId:folder.id});});
 await page.reload();const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles(),folder=(await f.list({})).entries[0],row=(await f.list({id:folder.id})).entries[0],selected=await f.select({id:row.id}),attachment=await f.attachment(selected);await f.forgetSelected(selected);return {name:attachment.name,bytes:Array.from(atob(attachment.dataBase64),c=>c.charCodeAt(0)),exposesBytes:'bytes' in row||'blob' in row};});expect(result).toEqual({name:'renamed.bin',bytes:[0,255,128,1,13,10],exposesBytes:false});
});
test('cancelling late file and directory byte reads persists no partial imports',async({page})=>{
 const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles();const results=[];for(const directory of [false,true]){const file=new File(['late'],'late.txt',{type:'text/plain'}),abort=new AbortController();let release!:(bytes:ArrayBuffer)=>void;file.arrayBuffer=()=>new Promise(r=>release=r);const pending=(directory?f.importDirectory([{path:'first.txt',file:new File(['first'],'first.txt')},{path:'nested/late.txt',file}],'Cancelled folder',abort.signal):f.importFile(file,'root',abort.signal)).then(()=>false,error=>error.name==='AbortError');while(!release)await new Promise(r=>setTimeout(r,0));abort.abort();results.push(await pending);release(new TextEncoder().encode('late').buffer);await new Promise(r=>setTimeout(r,20));}return {results,entries:(await f.list({})).entries};});expect(result).toEqual({results:[true,true],entries:[]});
});
test('failed directory byte reads leave neither earlier files nor folders',async({page})=>{
 const result=await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles(),bad=new File(['bad'],'bad.txt');bad.arrayBuffer=async()=>{throw Error('Read revoked');};let error='';try{await f.importDirectory([{path:'first.txt',file:new File(['first'],'first.txt')},{path:'nested/bad.txt',file:bad}],'Failed folder');}catch(e){error=String(e);}return {error,entries:(await f.list({})).entries};});expect(result.error).toContain('Read revoked');expect(result.entries).toEqual([]);
});
