import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.getByRole('button',{name:'Contacts',exact:true}).click();});
async function add(page:any,name:string){await page.getByRole('button',{name:'New contact',exact:true}).click();await page.getByPlaceholder('First name',{exact:true}).fill(name);await page.getByPlaceholder('Email',{exact:true}).fill('local@example.test');await page.getByRole('button',{name:'Save',exact:true}).click();}
test('contact create, edit, favorite, delete and undo retain exact fields through reload',async({page})=>{
 await add(page,'Parity Contact');await page.getByRole('button',{name:'Edit contact',exact:true}).click();await page.getByPlaceholder('Last name',{exact:true}).fill('Updated');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Add to favorites',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Contacts',exact:true}).click();await page.getByText('Parity Contact Updated',{exact:true}).last().click();await expect(page.getByRole('button',{name:'Remove from favorites',exact:true})).toBeVisible();await expect(page.getByText('local@example.test',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Delete contact',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Edit contact',exact:true})).toBeVisible();await page.getByRole('button',{name:'Delete contact',exact:true}).click();await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.some((p:any)=>p.first==='Parity Contact'))).toBe(false);
});
test('same-name contacts created at the same clock value receive distinct identities',async({page})=>{
 await page.evaluate(()=>Date.now=()=>1790950000000);await add(page,'Duplicate Name');await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await add(page,'Duplicate Name');const rows=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.filter((p:any)=>p.first==='Duplicate Name'));expect(rows).toHaveLength(2);expect(new Set(rows.map((p:any)=>p.id)).size).toBe(2);await page.getByRole('button',{name:'Delete contact',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.filter((p:any)=>p.first==='Duplicate Name').length)).toBe(1);
});
test('failed contact edit keeps the draft and stored original until retry succeeds',async({page})=>{
 await add(page,'Edit Retry');await page.getByRole('button',{name:'Edit contact',exact:true}).click();await page.getByPlaceholder('Email',{exact:true}).fill('changed@example.test');await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restore=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.contacts')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByPlaceholder('Email',{exact:true})).toHaveValue('changed@example.test');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.find((p:any)=>p.first==='Edit Retry').email)).toBe('local@example.test');await page.evaluate(()=>(window as any).restore());await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByText('changed@example.test',{exact:true})).toBeVisible();
});
test('failed deletion undo stays retryable and restores one contact with the same identity',async({page})=>{
 await add(page,'Undo Retry');const original=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.find((p:any)=>p.first==='Undo Retry'));await page.getByRole('button',{name:'Delete contact',exact:true}).click();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restoreUndo=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(k,v){if(k==='alpha.dev.app.contacts')throw Error('Full');return set.call(this,k,v);};});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeVisible();expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.some((p:any)=>p.id===id),original.id)).toBe(false);await page.evaluate(()=>(window as any).restoreUndo());await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Edit contact',exact:true})).toBeVisible();expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.filter((p:any)=>p.id===id),original.id)).toEqual([original]);
});
