import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('first-use policy persists, stale edits reject, previews are explicit and history never retains text',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');const first=await notices.crossAppStatus();
  const selected=await notices.setNotificationPolicy({expectedRevision:first.revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:false}]});let stale=false;try{await notices.setNotificationPolicy({expectedRevision:first.revision,enabled:false});}catch{stale=true;}
  await notices.inject({packageName:'browser.mail',title:'Private title',text:'Private message',id:'one'});const hidden=(await notices.list()).items[0];
  await notices.setNotificationPolicy({expectedRevision:selected.revision,apps:[{packageName:'browser.mail',preview:true}]});const old=(await notices.list()).items[0];
  const updated=await notices.inject({packageName:'browser.mail',title:'Visible title',text:'Visible message',id:'one'});let changed=false;try{await notices.dismiss({id:hidden.id,revision:hidden.revision,source:'external'});}catch{changed=true;}
  const visible=(await notices.list()).items[0];await notices.dismiss({...updated,source:'external'});const history=(await notices.notificationHistory()).items;const stored=(await (await import('/src/browser/notification-store.ts')).notificationDocument.readRaw())!;
  return {stale,hidden,old,visible,changed,history,stored,remaining:(await notices.list()).items};
 });
 expect(result.stale).toBe(true);expect(result.hidden.title).toBe('Mail');expect(result.hidden.text).toBe('');expect(result.old.text).toBe('Private message');expect(result.visible.text).toBe('Visible message');expect(result.changed).toBe(true);expect(result.history.map((row:any)=>row.state)).toEqual(['dismissed','updated']);expect(result.stored).not.toMatch(/Private|Visible/);expect(result.remaining).toEqual([]);
 await page.reload();const persisted=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');return {policy:await notices.crossAppStatus(),history:await notices.notificationHistory(),list:await notices.list()};});expect(persisted.policy.enabled).toBe(true);expect(persisted.history.items).toHaveLength(2);expect(persisted.list.items).toEqual([]);
});
test('history obeys retention and settings revoke current events',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');await notices.setNotificationPolicy({expectedRevision:(await notices.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.calendar',preview:true}]});for(let i=0;i<105;i++)await notices.inject({packageName:'browser.calendar',title:'Event '+i,text:'Body',id:'event-'+i});const capped=(await notices.notificationHistory()).items.length;await (await import('/src/browser/notification-store.ts')).notificationDocument.edit(state=>{state.events[0].at=Date.now()-86400001;});const expired=(await notices.notificationHistory()).items.length;await notices.setNotificationPolicy({expectedRevision:(await notices.crossAppStatus()).revision,enabled:false,history:false});return {capped,expired,history:(await notices.notificationHistory()).items,list:(await notices.list()).items,ignored:await notices.inject({packageName:'browser.calendar',title:'Off',text:'Off'})};});
 expect(result).toMatchObject({capped:100,expired:99,history:[],list:[],ignored:{status:'posted',collected:false}});
});
test('locked notifications redact previews and stale or ongoing items cannot be cleared',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');await notices.setNotificationPolicy({expectedRevision:(await notices.crossAppStatus()).revision,enabled:true,apps:[{packageName:'browser.mail',preview:true}]});(window as any).notice=await notices.inject({packageName:'browser.mail',title:'Secret',text:'Body',clearable:false});});
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Power',exact:true}).click();
 const locked=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');let rejected=false;try{await notices.open({...((window as any).notice),source:'external'});}catch{rejected=true;}return {row:(await notices.list()).items[0],rejected};});expect(locked.row.text).toBe('');expect(locked.row.title).toBe('Mail');expect(locked.row.canOpen).toBe(false);expect(locked.rejected).toBe(true);
 await page.getByRole('button',{name:'Unlock with fingerprint'}).click();const cleared=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaNotifications').clear({items:[{...(window as any).notice,source:'external'}]});});expect(cleared.outcomes[0].status).toBe('unavailable');
});
test('notification settings and device event controls drive the rendered shade',async({page})=>{
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();
 await page.getByText('Enable selected-app collection',{exact:true}).click();await page.getByText('Choose notification apps',{exact:true}).click();await page.getByText('Select Mail (browser.mail)',{exact:true}).click();await page.getByText('Allow previews: Mail',{exact:true}).click();
 await page.getByText('Manage Reminders',{exact:true}).click();const settings=page.getByRole('dialog',{name:'Reminders notifications'});await settings.getByRole('checkbox',{name:'Show reminders'}).uncheck();await settings.getByRole('button',{name:'Done',exact:true}).click();
 expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').status()).channels[0].blocked;})).toBe(true);
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Post notification',exact:true}).click();const composer=page.getByRole('dialog',{name:'Development notification'});await composer.getByRole('textbox',{name:'Title',exact:true}).fill('Inbox delivery');await composer.getByRole('textbox',{name:'Message',exact:true}).fill('Ready in browser');await composer.getByRole('button',{name:'Post',exact:true}).click();await expect(composer.getByRole('status')).toHaveText('Posted to notification center.');await composer.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Notifications',exact:true}).click();await expect(page.getByText('Inbox delivery · Ready in browser',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/dev-parity-ui/notifications.png'});await page.getByRole('button',{name:'Clear all',exact:true}).click();await expect(page.getByText('Inbox delivery · Ready in browser',{exact:true})).toHaveCount(0);
});
test('history clear invalidates queued observations and failed writes do not publish events',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');await notices.setNotificationPolicy({expectedRevision:(await notices.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true}]});const first=await notices.inject({packageName:'browser.mail',title:'Existing',text:'Body'});
  let release!:()=>void;const held=navigator.locks.request(JSON.stringify(['browser-document','alpha.browser.documents.v1','alpha.browser.notifications.v2']),()=>new Promise<void>(resolve=>release=resolve));while(!release)await new Promise(resolve=>setTimeout(resolve,0));
  const clearing=notices.clearNotificationHistory(),queued=notices.inject({packageName:'browser.mail',title:'Queued',text:'Before clear'});while((await navigator.locks.query()).pending!.length<2)await new Promise(resolve=>setTimeout(resolve,0));release();await held;await clearing;const outcome=await queued;
  const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.notifications.v2')throw new DOMException('Full','QuotaExceededError');return original.call(this,value,key);};let failed=false;try{await notices.inject({packageName:'browser.mail',title:'Not committed',text:'Body'});}catch{failed=true;}finally{IDBObjectStore.prototype.put=original;}
  let stale=false;try{await notices.dismiss({...first,source:'external'});}catch{stale=true;}
  return {outcome,failed,stale,history:(await notices.notificationHistory()).items,items:(await notices.list()).items.map((item:any)=>item.title).sort()};
 });expect(result).toMatchObject({outcome:{status:'posted',collected:true},failed:true,stale:true,history:[],items:['Existing','Queued']});
});
test('access and channel controls change actual delivery and notification taps open the source app',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications'),daily=registerPlugin<any>('DailyApps');await daily.scheduleReminder({id:'channel-test',title:'Reminder delivery',at:Date.now()+10000});await (await import('/src/browser/reminder-store.ts')).reminderDocument.edit(()=>({reminders:[] as any[]}),data=>{data.reminders[0].at=Date.now()-1;});await notices.openChannelSettings({id:'reminders'});});
 const channel=page.getByRole('dialog',{name:'Reminders notifications'});await channel.getByRole('checkbox',{name:'Show reminders'}).uncheck();await channel.getByRole('button',{name:'Done',exact:true}).click();
 expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').list()).items;})).toEqual([]);
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');await notices.setNotificationPolicy({expectedRevision:(await notices.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true}]});await notices.inject({packageName:'browser.mail',title:'Open local inbox',text:'Browser event'});});
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Notifications',exact:true}).click();await page.getByRole('button',{name:'Open Mail',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-active-view','inbox');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');await notices.inject({packageName:'browser.mail',title:'Revoke me',text:'Private'});await notices.openNotificationAccess();});const access=page.getByRole('dialog',{name:'Notification access'});await access.getByRole('checkbox',{name:'Allow development app events'}).uncheck();await access.getByRole('button',{name:'Done',exact:true}).click();
 const revoked=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');return {items:(await notices.list()).items,history:(await notices.notificationHistory()).items,access:(await notices.crossAppStatus()).accessGranted};});expect(revoked).toEqual({items:[],history:[],access:false});
});
test('notification sources and installed development apps share launch identities',async({page})=>{
 const requests:string[]=[];page.on('request',request=>{if(!request.url().startsWith('http://127.0.0.1:'))requests.push(request.url());});
 const sources=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return {sources:(await registerPlugin<any>('AlphaNotifications').notificationApps()).apps,installed:(await registerPlugin<any>('DeviceApps').list()).apps};});expect(sources.sources).toEqual(sources.installed);expect(sources.sources.some((app:any)=>app.packageName==='browser.messages')).toBe(true);
 for(const [packageName,view] of [['browser.mail','inbox'],['browser.messages','messages']]){await page.evaluate(async(packageName)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DeviceApps').launch({packageName});},packageName);await expect(page.locator('html')).toHaveAttribute('data-active-view',view);}
 expect(requests).toEqual([]);
});
test('history can be inspected and cleared in Settings and Back dismisses access controls',async({page})=>{
 page.on('dialog',dialog=>void dialog.accept());await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const notices=registerPlugin<any>('AlphaNotifications');await notices.setNotificationPolicy({expectedRevision:(await notices.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:false}]});await notices.inject({packageName:'browser.mail',title:'Not retained',text:'Not retained'});});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();await page.getByText('View local metadata history',{exact:true}).click();await expect(page.getByText(/posted · .*no action available/)).toBeVisible();await page.getByText('Clear local metadata history',{exact:true}).click();await expect(page.getByText('No retained events',{exact:true})).toBeVisible();
 await page.getByText('Manage development notification access',{exact:true}).click();await expect(page.getByRole('dialog',{name:'Notification access'})).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('dialog',{name:'Notification access'})).toHaveCount(0);await expect(page.getByText('Manage development notification access',{exact:true})).toBeVisible();
});

test('notification settings visibly wait for policy persistence before accepting app choices',async({page})=>{
 await page.evaluate(async()=>{const {BrowserNotifications}=await import('/src/browser/notifications.ts');const original=BrowserNotifications.prototype.setNotificationPolicy;BrowserNotifications.prototype.setNotificationPolicy=async function(input){await new Promise<void>(resolve=>(window as any).releasePolicy=resolve);return original.call(this,input);};});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();await page.getByRole('button',{name:'Enable selected-app collection',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof (window as any).releasePolicy)).toBe('function');
 const choose=page.getByRole('button',{name:'Choose notification apps',exact:true});await expect(choose).toBeDisabled();await page.evaluate(()=>(window as any).releasePolicy());await expect(choose).toBeEnabled();await choose.click();await expect(page.getByRole('button',{name:'Select Mail (browser.mail)',exact:true})).toBeEnabled();
});
test('failed notification policy writes restore enabled settings controls',async({page})=>{
 await page.evaluate(async()=>{const {BrowserNotifications}=await import('/src/browser/notifications.ts');BrowserNotifications.prototype.setNotificationPolicy=async()=>{throw Error('Storage full');};});await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();await page.getByRole('button',{name:'Enable selected-app collection',exact:true}).click();const choose=page.getByRole('button',{name:'Choose notification apps',exact:true});await expect(choose).toBeEnabled();await choose.click();await expect(page.getByRole('button',{name:'Select Mail (browser.mail)',exact:true})).toBeEnabled();expect(await page.evaluate(async()=>{const {BrowserNotifications}=await import('/src/browser/notifications.ts');return (await new BrowserNotifications().crossAppStatus()).enabled;})).toBe(false);
});
