import {genericCloudSpeechFixture} from './generic-cloud-speech-fixture';
import {test,expect,Page} from '@playwright/test';
const runs=(page:Page)=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]);
test.beforeEach(async({page},testInfo)=>{
 await page.addInitScript(pickup=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.dev.app.workflows'))localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:991,name:'Read result',on:true,short:'Read local output',summary:'Read local output',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']},{k:'Speak',t:pickup?'Speak it when I pick up the phone':'Read it aloud',apps:['Speaker']},{k:'Do',t:'Turn off Do Not Disturb',apps:['Settings']}],runs:[]}],localRuns:{}}));const s=(window as any).speechTest={spoken:[],voices:[{name:'Device',lang:'en-US',localService:true}],utterance:null,cancelled:0};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>s.voices,speak:(u:any)=>{s.spoken.push(u.text);s.utterance=u;},cancel:()=>s.cancelled++});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class {constructor(public text:string){}}});},testInfo.title.includes('pickup'));
 await page.goto('/?mode=dev&tools=1');await genericCloudSpeechFixture(page);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Read result',{exact:true}).click();
});
async function start(page:Page){await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.spoken)).toEqual(['Do Not Disturb on']);}
test('workflow waits for actual speech completion before later steps',async({page})=>{await start(page);expect((await runs(page))[0].status).toBe('running');expect((await runs(page))[0].cursor).toBe(1);await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');expect((await runs(page))[0].log[1][1]).toBe('Finished reading aloud');expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw())!).doNotDisturb)).toBe(false);});
for(const kind of ['cancel','error','retire'])test('speech '+kind+' stops later workflow effects',async({page})=>{await start(page);if(kind==='cancel')await page.getByRole('button',{name:'Cancel run',exact:true}).click();else await page.evaluate(kind=>{if(kind==='error')(window as any).speechTest.utterance.onerror();else window.dispatchEvent(new Event('alpha:device-state'));},kind);await expect.poll(async()=>(await runs(page))[0].status).toBe(kind==='cancel'?'cancelled':'fail');expect((await runs(page))[0].cursor).toBe(1);expect(await page.evaluate(async()=>JSON.parse((await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw())!).doNotDisturb)).toBe(true);});
test('replacement speech fails the old workflow without stopping the replacement',async({page})=>{await start(page);const count=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const v=registerPlugin<any>('AlphaVoiceCloud');const prepared=await v.synthesizeLocal({text:'Replacement'});await v.play(prepared);return (window as any).speechTest.cancelled;});await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect(await page.evaluate(()=>(window as any).speechTest.cancelled)).toBe(count);expect(await page.evaluate(()=>(window as any).speechTest.utterance.text)).toBe('Replacement');});
test('cancelling while Cloud synthesis is pending prevents late playback',async({page})=>{await page.evaluate(()=>(window as any).speechTest.holdSynthesis=true);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await runs(page))[0]?.inflight).toBe(1);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await page.evaluate(()=>{(window as any).speechTest.releaseSynthesis?.();});await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);});
test('a stale completion after cancellation cannot complete a later run',async({page})=>{await start(page);await page.evaluate(()=>(window as any).oldSpeechEnd=(window as any).speechTest.utterance.onend);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.spoken.length)).toBe(2);await page.evaluate(()=>(window as any).oldSpeechEnd());expect((await runs(page))[1].status).toBe('running');await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[1].status).toBe('ok');expect((await runs(page))[0].status).toBe('cancelled');});
test('Cloud workflow speech is independent of installed OS voices',async({page})=>{await page.evaluate(()=>(window as any).speechTest.voices=[]);await start(page);expect((await runs(page))[0].cursor).toBe(1);await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');});
test('missing completion times out and stops its own utterance',async({page})=>{await page.clock.install();await start(page);const before=await page.evaluate(()=>(window as any).speechTest.cancelled);await page.clock.fastForward(20*60*1000+1);await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect((await runs(page))[0].sum).toContain('did not finish');expect(await page.evaluate(()=>(window as any).speechTest.cancelled)).toBeGreaterThan(before);});
async function awaitPickup(page:Page){await page.evaluate(async()=>{const {Component}=await import('/src/prototype/model.js');const original=Component.prototype.api;Component.prototype.api=function(key:string){const api=original.call(this,key);if(key==='workflows')(window as any).workflowApi=api;return api;};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await runs(page))[0]?.sum).toBe('Waiting for pickup');expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);}
async function pickup(page:Page){await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Pick up phone',exact:true}).click();}
test('pickup control releases waiting speech exactly once',async({page})=>{await awaitPickup(page);await pickup(page);await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.spoken)).toEqual(['Do Not Disturb on']);await expect.poll(async()=>(await runs(page))[0].sum).toBe('Reading aloud');await pickup(page);expect(await page.evaluate(()=>(window as any).speechTest.spoken.length)).toBe(1);await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');});
test('pickup after cancellation cannot start speech',async({page})=>{await awaitPickup(page);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');await pickup(page);expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);});
test('pickup while backgrounded is ignored until a foreground pickup',async({page})=>{await awaitPickup(page);await page.evaluate(()=>{document.documentElement.dataset.devBackground='true';window.dispatchEvent(new Event('alpha:dev-pickup'));});expect((await runs(page))[0].sum).toBe('Waiting for pickup');expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);await page.evaluate(()=>delete document.documentElement.dataset.devBackground);await pickup(page);await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.spoken.length)).toBe(1);await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');});
test('pickup cannot run a workflow edited during the wait',async({page})=>{await awaitPickup(page);await page.evaluate(()=>{const api=(window as any).workflowApi;api.set({flows:api.get('workflows').flows.map((f:any)=>({...f,name:'Changed while waiting'}))});});await pickup(page);await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect((await runs(page))[0].sum).toContain('changed');expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);});
test('pickup after reload cannot resume an interrupted wait',async({page})=>{await awaitPickup(page);await page.reload();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Read result',{exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('interrupted');await pickup(page);expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);expect((await runs(page))[0].cursor).toBe(1);});

test('pickup remains silent while powered off and locked, then works after unlock',async({page})=>{
 await awaitPickup(page);await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Power',exact:true}).click();await expect(page.getByRole('button',{name:'Unlock with fingerprint',exact:true})).toBeVisible();await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Power',exact:true}).click();await expect(page.getByRole('button',{name:'Wake',exact:true})).toBeVisible();
 await pickup(page);expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);expect((await runs(page))[0].sum).toBe('Waiting for pickup');
 await page.getByRole('button',{name:'Wake',exact:true}).click();await expect(page.getByRole('button',{name:'Unlock with fingerprint',exact:true})).toBeVisible();await pickup(page);expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);
 await page.getByRole('button',{name:'Unlock with fingerprint',exact:true}).click();await pickup(page);await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.spoken)).toEqual(['Do Not Disturb on']);await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');
});
