import {test,expect} from '@playwright/test';
test('reviewed snapshot schedule delivers one retained result and survives reload',async({page})=>{
 await page.clock.install({time:new Date('2026-10-03T12:00:10Z')});
 await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();
 await page.evaluate(()=>window.dispatchEvent(new Event('alpha:hosted-digests')));const panel=page.getByRole('dialog',{name:'Scheduled digests',exact:true});await panel.getByText('Share a snapshot',{exact:true}).click();await panel.getByLabel('Label',{exact:true}).fill('Daily source');await panel.getByLabel('Snapshot text',{exact:true}).fill('Reviewed snapshot content');await panel.getByRole('button',{name:'Review snapshot',exact:true}).click();await panel.getByRole('button',{name:'Confirm',exact:true}).click();
 await panel.getByRole('combobox',{name:'Reviewed source',exact:true}).selectOption({index:1});await panel.getByLabel('Time zone',{exact:true}).fill('UTC');await panel.getByLabel('Morning',{exact:true}).fill('12:01');await panel.getByRole('button',{name:'Review morning schedule',exact:true}).click();await panel.getByRole('button',{name:'Confirm',exact:true}).click();
 await panel.getByRole('button',{name:'Pause result checks',exact:true}).click();await page.clock.runFor(60000);await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.digests.local.v1')!).results.length)).toBe(1);await panel.getByRole('button',{name:'Refresh',exact:true}).click();await expect(panel.getByText('Development reply. Edit this response in Agent connection.',{exact:true})).toBeVisible();
 const first=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.digests.local.v1')!).results);expect(first).toHaveLength(1);await page.reload();await page.evaluate(()=>window.dispatchEvent(new Event('alpha:hosted-digests')));await expect(panel.getByText('Development reply. Edit this response in Agent connection.',{exact:true})).toBeVisible();await panel.getByRole('button',{name:'Refresh',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.digests.local.v1')!).results)).toEqual(first);
});
test('digest mutation replay, lost acknowledgements, revocation and account retirement retain exact identities',async({page})=>{
 await page.goto('/?mode=dev');const result=await page.evaluate(async()=>{
 const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'local'}));const identity=developmentIdentity('local'),call=(path:string,body?:any)=>request(identity,'/api/workflow/hosted/'+path,body),source={id:crypto.randomUUID(),kind:'notes',label:'Reviewed',text:'Saved text',observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),confirmed:true};const saved:any=await call('sources',source),again=await call('sources',source);let changed=false;try{await call('sources',{...source,text:'Different'});}catch{changed=true;}
 const time=new Date().toISOString().slice(11,16),body={mutationId:crypto.randomUUID(),confirmed:true,spec:{version:1,template:'morning',sourceId:saved.source.id,sourceRevision:saved.source.revision,timeZone:'UTC',localTime:time,enabled:true}},loop:any=await call('loops',body);const key='alpha.browser.digests.local.v1',state=JSON.parse(localStorage.getItem(key)!);state.loops[0].createdAt=Date.now()-120000;localStorage.setItem(key,JSON.stringify(state));
 const a:any=await call('results?clientId=reader'),b:any=await call('results?clientId=reader');await call('results/ack',{clientId:'reader',cursor:a.entries[0].cursor,runId:a.entries[0].runId});const empty:any=await call('results?clientId=reader');await call('sources/revoke',{id:source.id,confirmed:true});const after:any=await call('results?clientId=other');let stale=false;try{await call('loops',{...body,mutationId:crypto.randomUUID(),id:loop.loop.id,expectedVersionId:'old'});}catch{stale=true;}
 localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));let retired=false;try{await call('sources');}catch{retired=true;}
 return {replayed:JSON.stringify(saved)===JSON.stringify(again),changed,same:JSON.stringify(a)===JSON.stringify(b),one:a.entries.length,empty:empty.entries.length,retained:JSON.stringify(a)===JSON.stringify(after),stale,retired};});expect(result).toEqual({replayed:true,changed:true,same:true,one:1,empty:0,retained:true,stale:true,retired:true});
});
for(const scenario of [{name:'repeated clock time runs once at the earlier offset',start:'2026-11-01T05:29:00Z',time:'01:30',ticks:['2026-11-01T05:30:00Z','2026-11-01T06:30:00Z'],count:1},{name:'skipped clock time and missed days do not replay',start:'2026-03-08T06:59:00Z',time:'02:30',ticks:['2026-03-08T07:30:00Z','2026-03-09T06:32:00Z'],count:0}])test(scenario.name,async({page})=>{
 await page.clock.install({time:new Date(scenario.start)});await page.goto('/?mode=dev');await page.evaluate(async time=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'local'}));const i=developmentIdentity('local'),s:any=await request(i,'/api/workflow/hosted/sources',{id:crypto.randomUUID(),kind:'notes',label:'Clock source',text:'Clock text',observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3*86400000).toISOString(),confirmed:true});await request(i,'/api/workflow/hosted/loops',{mutationId:crypto.randomUUID(),confirmed:true,spec:{version:1,template:'morning',sourceId:s.source.id,sourceRevision:s.source.revision,enabled:true,timeZone:'America/New_York',localTime:time}});},scenario.time);
 for(const time of scenario.ticks){await page.clock.setFixedTime(new Date(time));await page.evaluate(async()=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');await request(developmentIdentity('local'),'/api/workflow/hosted/tick',undefined);});}expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.digests.local.v1')!).results.length)).toBe(scenario.count);
});
