import {test,expect, type Page} from '@playwright/test';
const key='alpha.browser.password-provider.v1';
async function settings(page:Page){await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Password manager',exact:true}).click();}
async function install(page:Page){await page.getByRole('button',{name:'Add development provider',exact:true}).click();await page.getByRole('button',{name:'Add provider',exact:true}).click();await expect(page.getByText('Development provider installed',{exact:true})).toBeVisible();}
async function select(page:Page){await page.getByRole('button',{name:'Choose password provider',exact:true}).click();await page.getByRole('button',{name:'Proton Pass · development',exact:true}).click();await expect(page.getByText('Development provider selected',{exact:true})).toBeVisible();}
test('development provider persists selection and fills only a disposable sample',async({page})=>{
 await settings(page);await install(page);await select(page);await settings(page);await expect(page.getByText('Development provider selected',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Open development vault',exact:true}).click();await page.getByRole('button',{name:'Unlock development vault',exact:true}).click();await page.getByRole('button',{name:'Fill sample sign-in',exact:true}).click();await expect(page.getByLabel('Sample sign-in')).toContainText('demo-only-password');expect(await page.locator('dialog input').count()).toBe(0);await page.getByRole('button',{name:'Lock vault',exact:true}).click();await page.getByRole('button',{name:'Open development vault',exact:true}).click();await expect(page.getByText('Vault locked',{exact:true})).toBeVisible();const data=await page.evaluate(key=>localStorage.getItem(key),key);expect(data).not.toContain('password');expect(data).not.toContain('alex');
});
test('cancel and failed storage never claim installation',async({page})=>{
 await settings(page);await page.getByRole('button',{name:'Add development provider',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBeNull();await page.evaluate(key=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error('full');return original.call(this,k,v);};},key);await page.getByRole('button',{name:'Add development provider',exact:true}).click();await page.getByRole('button',{name:'Add provider',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Settings could not be saved'})).toBeVisible();expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBeNull();
});
test('home and device state retire unlocked vault; selection required for fill',async({page})=>{
 await settings(page);await install(page);await page.getByRole('button',{name:'Open development vault',exact:true}).click();await page.getByRole('button',{name:'Unlock development vault',exact:true}).click();await page.getByRole('button',{name:'Fill sample sign-in',exact:true}).click();await expect(page.getByText('Choose the development provider before filling.',{exact:true})).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('alpha:device-state')));await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('another tab retires stale provider choice',async({page,context})=>{
 await settings(page);await install(page);await page.getByRole('button',{name:'Choose password provider',exact:true}).click();const other=await context.newPage();await other.goto('/?mode=dev');await other.evaluate(key=>{const state=JSON.parse(localStorage.getItem(key)!);state.revision='external';localStorage.setItem(key,JSON.stringify(state));},key);await expect(page.getByRole('dialog')).toHaveCount(0);expect(JSON.parse((await page.evaluate(key=>localStorage.getItem(key),key))!).selection).toBe('none');
});
test('Back cancels an installation queued behind another storage writer',async({page})=>{
 await settings(page);await page.evaluate(async key=>{await new Promise<void>(ready=>{void navigator.locks.request(key,async()=>{ready();await new Promise<void>(resolve=>{(window as any).releaseProviderLock=resolve;});});});},key);await page.getByRole('button',{name:'Add development provider',exact:true}).click();await page.getByRole('button',{name:'Add provider',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('dialog')).toHaveCount(0);await page.evaluate(()=>(window as any).releaseProviderLock());await page.evaluate(key=>navigator.locks.request(key,()=>{}),key);expect(await page.evaluate(key=>localStorage.getItem(key),key)).toBeNull();
});
test('Home clears sample contents and provider can be deselected',async({page})=>{
 await settings(page);await install(page);await select(page);await page.getByRole('button',{name:'Open development vault',exact:true}).click();await page.getByRole('button',{name:'Unlock development vault',exact:true}).click();await page.getByRole('button',{name:'Fill sample sign-in',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));await expect(page.getByLabel('Sample sign-in')).toHaveCount(0);await settings(page);await page.getByRole('button',{name:'Choose password provider',exact:true}).click();await page.getByRole('button',{name:'None',exact:true}).click();await expect(page.getByText('No provider selected',{exact:true})).toBeVisible();
});
