import {test,expect,Page} from '@playwright/test';
const journal=(page:Page)=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]);
async function open(page:Page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Message workflow',{exact:true}).click();}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.dev.app.workflows')){localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:994,name:'Message workflow',on:true,short:'Unread source',summary:'Read and reply',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Read',t:'New messages',apps:['Messages']}],runs:[]}],localRuns:{}}));localStorage.setItem('alpha.dev.app.messages',JSON.stringify({threads:{maya:[{id:'m1',k:1,me:false,text:'Old'},{id:'m2',k:2,me:false,text:'Latest Maya'},{id:'out',k:3,me:true,text:'Outgoing'}],priya:[{id:'p1',k:1,me:false,text:'Priya one'},{id:'p2',k:2,me:false,text:'Priya two'}],jordan:[{id:'j1',k:1,me:false,text:'Already read'}]},unread:{maya:1,priya:2},extra:[]}));}});await page.goto('/?mode=dev');await open(page);});
async function replyFlow(page:Page,filter=false){await page.evaluate(filter=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Read',t:'New messages',apps:['Messages']},...(filter?[{k:'If',t:"It's from Maya",apps:['Contacts']}]:[]),{k:'Write',t:'A draft reply',apps:[]},{k:'Send',t:'A reply to the sender',apps:['Messages']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));},filter);await page.reload();await open(page);}
test('New messages selects only unread incoming records and leaves read state intact',async({page})=>{const before=await page.evaluate(()=>localStorage.getItem('alpha.dev.app.messages'));await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');const messages=JSON.parse((await journal(page))[0].out);expect(Object.keys(messages)).toEqual(['maya','priya']);expect(messages.maya.map((r:any)=>r.id)).toEqual(['m2']);expect(messages.priya.map((r:any)=>r.id)).toEqual(['p1','p2']);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.messages'))).toBe(before);});
test('sender filtering narrows input and the supplied reply reaches only that sender',async({page})=>{await replyFlow(page,true);await page.getByRole('button',{name:'Run now',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Workflow step result'});await expect(dialog).toBeVisible();const input=await dialog.getByRole('textbox',{name:'Step input',exact:true}).inputValue();expect(Object.keys(JSON.parse(input))).toEqual(['maya']);await dialog.getByRole('textbox',{name:'Development result',exact:true}).fill('Reviewed reply');await dialog.getByRole('button',{name:'Use result',exact:true}).click();await expect.poll(async()=>(await journal(page))[0].status).toBe('ok');const run=(await journal(page))[0];const sent=await page.evaluate(id=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.messages')!);return Object.entries(s.threads).flatMap(([pid,rows]:any)=>rows.filter((r:any)=>r.id===id+'-3').map((r:any)=>({pid,text:r.text})));},run.id);expect(sent).toEqual([{pid:'maya',text:'Reviewed reply'}]);await page.reload();expect((await journal(page))[0].context.messages.maya[0].id).toBe('m2');});
test('an ambiguous sender cannot receive an invented reply destination',async({page})=>{await replyFlow(page);await page.getByRole('button',{name:'Run now',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Workflow step result'});await dialog.getByRole('textbox',{name:'Development result',exact:true}).fill('Ambiguous reply');await dialog.getByRole('button',{name:'Use result',exact:true}).click();await expect.poll(async()=>(await journal(page))[0].status).toBe('fail');expect((await journal(page))[0].sum).toContain('one sender');expect((await journal(page))[0].cursor).toBe(2);});
test('a deleted source message prevents a stale local reply',async({page})=>{await replyFlow(page,true);await page.getByRole('button',{name:'Run now',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Workflow step result'});await expect(dialog).toBeVisible();await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.messages')!);s.threads.maya=s.threads.maya.filter((r:any)=>r.id!=='m2');localStorage.setItem('alpha.dev.app.messages',JSON.stringify(s));});await dialog.getByRole('textbox',{name:'Development result',exact:true}).fill('Stale reply');await dialog.getByRole('button',{name:'Use result',exact:true}).click();await expect.poll(async()=>(await journal(page))[0].status).toBe('fail');expect((await journal(page))[0].sum).toContain('Source messages changed');expect((await journal(page))[0].cursor).toBe(3);});
test('reply receipts reject cross-recipient replay and accept the original recipient',async({page})=>{const result=await page.evaluate(async()=>{const {sendWorkflowLocal}=await import('/src/browser/workflow-local-send.ts');const key='alpha.dev.app.messages',state=JSON.parse(localStorage.getItem(key)!);state.threads.maya.push({id:'bound-step',me:true,text:'Reply',k:4});localStorage.setItem(key,JSON.stringify(state));const api={get:()=>({}),setView:()=>{throw Error('Unexpected write');}},signal=new AbortController().signal;const same=sendWorkflowLocal({t:'A reply to the sender'},'Reply','bound-step',api,signal,{maya:[state.threads.maya[1]]});let conflict=false;try{sendWorkflowLocal({t:'A reply to the sender'},'Reply','bound-step',api,signal,{priya:state.threads.priya});}catch(e){conflict=String(e).includes('another recipient');}return {same,conflict};});expect(result.same.output).toBe('Reply');expect(result.conflict).toBe(true);});
test('a later non-message read clears reply context',async({page})=>{await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Read',t:'New messages',apps:['Messages']},{k:'Read',t:'Contacts',apps:['Contacts']},{k:'Send',t:'A reply to the sender',apps:['Messages']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));});await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0].status).toBe('fail');expect((await journal(page))[0].context).toEqual({});expect((await journal(page))[0].cursor).toBe(2);expect((await journal(page))[0].sum).toContain('one sender');});
test('no unread conversations yields empty input without modifying Messages',async({page})=>{const before=await page.evaluate(()=>{const key='alpha.dev.app.messages',s=JSON.parse(localStorage.getItem(key)!);s.unread={};const raw=JSON.stringify(s);localStorage.setItem(key,raw);return raw;});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0].status).toBe('ok');expect((await journal(page))[0].out).toBe('{}');expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.messages'))).toBe(before);});

test('inconsistent unread counts fail before returning incomplete message input',async({page})=>{
 await page.evaluate(()=>{const key='alpha.dev.app.messages',s=JSON.parse(localStorage.getItem(key)!);s.unread={maya:3};localStorage.setItem(key,JSON.stringify(s));});
 await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');expect((await journal(page))[0].cursor).toBe(0);expect((await journal(page))[0].sum).toContain('Unread message counts need recovery');
});
