import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:navigator.mediaDevices});});await page.goto('/?mode=dev');});
test('microphone disable retires pending permission immediately and releases a late stream',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('AlphaDevice'),v=registerPlugin<any>('AlphaVoiceCloud');let calls=0,release!:(s:MediaStream)=>void;Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:()=>{calls++;return new Promise<MediaStream>(resolve=>release=resolve);}});await d.setSensor({field:'microphoneEnabled',enabled:false});let disabled=false;try{await v.startRecording();}catch{disabled=true;}const before=calls;await d.setSensor({field:'microphoneEnabled',enabled:true});const pending=v.startRecording().then(()=>false,()=>true);while(!release)await new Promise(r=>setTimeout(r,0));await d.setSensor({field:'microphoneEnabled',enabled:false});const cancelled=await pending;const ctx=new AudioContext(),sink=ctx.createMediaStreamDestination();release(sink.stream);await new Promise(r=>setTimeout(r,0));const stopped=sink.stream.getTracks().every(t=>t.readyState==='ended');await ctx.close();return {disabled,before,cancelled,stopped};});expect(result).toEqual({disabled:true,before:0,cancelled:true,stopped:true});
});
test('another tab can stop active microphone capture without changing host permission facts',async({page,context})=>{
 await page.evaluate(async()=>{const ctx=new AudioContext(),sink=ctx.createMediaStreamDestination();Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>sink.stream});(window as any).sensorFixture={ctx,stream:sink.stream};const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaVoiceCloud').startRecording();});const other=await context.newPage();await other.goto('/?mode=dev');await other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'microphoneEnabled',enabled:false});});await expect.poll(()=>page.evaluate(()=>(window as any).sensorFixture.stream.getAudioTracks()[0].readyState)).toBe('ended');const state=await page.evaluate(async()=>{Object.defineProperty(navigator.permissions,'query',{configurable:true,value:async()=>({state:'granted'})});const {registerPlugin}=await import('/src/platform-plugins.ts');await (window as any).sensorFixture.ctx.close();return registerPlugin<any>('AlphaDevice').snapshot();});expect(state.microphoneEnabled).toBe(false);expect(state.permissionStates.Microphone).toBe('granted');await other.close();
});
test('location disable settles permission requests, clears watches and ignores callbacks after disable or clear',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('AlphaDevice'),location=registerPlugin<any>('ElizaLocation');const callbacks:Function[]=[],cleared:number[]=[],events:any[]=[];Object.defineProperty(navigator.geolocation,'watchPosition',{configurable:true,value:(yes:Function)=>{callbacks.push(yes);return callbacks.length;}});Object.defineProperty(navigator.geolocation,'clearWatch',{configurable:true,value:(id:number)=>cleared.push(id)});await location.addListener('locationChange',(e:any)=>events.push(e));await location.watchPosition();const pending=location.requestPermissions();while(callbacks.length<2)await new Promise(r=>setTimeout(r,0));await d.setSensor({field:'locationEnabled',enabled:false});const permission=await pending;const value={coords:{latitude:1,longitude:2,accuracy:3},timestamp:4};callbacks.forEach(cb=>cb(value));const stale=events.length;await d.setSensor({field:'locationEnabled',enabled:true});const current=await location.watchPosition();callbacks[2](value);await location.clearWatch(current);callbacks[2](value);return {permission,stale,count:events.length,cleared};});expect(result.permission).toEqual({location:'denied',accuracy:'none'});expect(result.stale).toBe(0);expect(result.count).toBe(1);expect(result.cleared.sort()).toEqual([1,2,3]);
});
test('sensor switches are shared by shade and privacy settings and persist after reload',async({page})=>{
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Notifications',exact:true}).click();await page.getByRole('button',{name:'Agent can listen',exact:true}).click();await expect(page.getByRole('button',{name:'Agent can listen',exact:true})).toHaveAttribute('aria-pressed','false');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').openSettings({page:'privacy'});});const d=page.getByRole('dialog',{name:'privacy settings'});await expect(d.getByRole('checkbox',{name:'microphone Enabled'})).not.toBeChecked();await d.getByRole('checkbox',{name:'location Enabled'}).uncheck();await expect(d.getByRole('checkbox',{name:'location Enabled'})).toBeEnabled();await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')!))).toMatchObject({microphoneEnabled:false,locationEnabled:false});
});
test('video microphone policy releases owned recording tracks and preserves the camera source',async({page})=>{
 const result=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const camera=canvas.captureStream(10),ctx=new AudioContext(),sink=ctx.createMediaStreamDestination();Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>sink.stream});const {BrowserVideoCapture}=await import('/src/browser/video-capture.ts');const video=new BrowserVideoCapture();await video.start({srcObject:camera,readyState:4,videoWidth:64,videoHeight:64} as any,{audio:true,maxDuration:5,maxFileSize:1000000});const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'microphoneEnabled',enabled:false});const state=video.state(),microphone=sink.stream.getAudioTracks()[0].readyState,cameraState=camera.getVideoTracks()[0].readyState;camera.getTracks().forEach(t=>t.stop());await ctx.close();return {state,microphone,cameraState};});expect(result.state.isRecording).toBe(false);expect(result.microphone).toBe('ended');expect(result.cameraState).toBe('live');
});
test('media volume applies to owned playback and survives reload without controlling host volume',async({page})=>{
 await page.evaluate(()=>{const media=document.createElement('video');media.dataset.testMedia='true';document.querySelector('.os')!.append(media);media.dispatchEvent(new Event('play'));});await expect.poll(()=>page.locator('[data-test-media]').evaluate((m:HTMLVideoElement)=>m.volume)).toBe(.7);
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').openSettings({page:'sound'});});await page.getByRole('dialog',{name:'sound settings'}).getByRole('slider',{name:'music',exact:true}).fill('20');await expect.poll(()=>page.locator('[data-test-media]').evaluate((m:HTMLVideoElement)=>m.volume)).toBe(.2);await page.reload();expect(await page.evaluate(async()=>{const {browserMediaVolume}=await import('/src/browser/audio-settings.ts');return browserMediaVolume();})).toBe(.2);
});
test('disabling microphone exits the rendered Notes recording state',async({page})=>{
 await page.evaluate(()=>{const ctx=new AudioContext(),sink=ctx.createMediaStreamDestination();Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>sink.stream});(window as any).microphoneContext=ctx;});await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Record and transcribe',exact:true}).click();await page.getByRole('button',{name:'Record without transcription',exact:true}).click();await page.getByRole('button',{name:'Start recording',exact:true}).click();await expect(page.getByRole('button',{name:'Stop recording',exact:true})).toBeVisible();await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'microphoneEnabled',enabled:false});});await expect(page.getByRole('button',{name:'Start recording',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Stop recording',exact:true})).toHaveCount(0);await page.evaluate(()=>(window as any).microphoneContext.close());
});
