import {test,expect,Page} from '@playwright/test';
const runs=(page:Page)=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]);
test.beforeEach(async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:991,name:'Read result',on:true,short:'Read local output',summary:'Read local output',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']},{k:'Speak',t:'Read it aloud',apps:['Speaker']},{k:'Do',t:'Turn off Do Not Disturb',apps:['Settings']}],runs:[]}],localRuns:{}}));const s=(window as any).speechTest={spoken:[],voices:[{name:'Device',lang:'en-US',localService:true}],utterance:null,cancelled:0};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>s.voices,speak:(u:any)=>{s.spoken.push(u.text);s.utterance=u;},cancel:()=>s.cancelled++});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class {constructor(public text:string){}}});});
 await page.goto('/?mode=dev');await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Read result',{exact:true}).click();
});
async function start(page:Page){await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).speechTest.spoken)).toEqual(['Do Not Disturb on']);}
test('workflow waits for actual speech completion before later steps',async({page})=>{await start(page);expect((await runs(page))[0].status).toBe('running');expect((await runs(page))[0].cursor).toBe(1);await page.evaluate(()=>(window as any).speechTest.utterance.onend());await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');expect((await runs(page))[0].log[1][1]).toBe('Finished reading aloud');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')!).doNotDisturb)).toBe(false);});
for(const kind of ['cancel','error','retire'])test('speech '+kind+' stops later workflow effects',async({page})=>{await start(page);if(kind==='cancel')await page.getByRole('button',{name:'Cancel run',exact:true}).click();else await page.evaluate(kind=>{if(kind==='error')(window as any).speechTest.utterance.onerror();else window.dispatchEvent(new Event('alpha:device-state'));},kind);await expect.poll(async()=>(await runs(page))[0].status).toBe(kind==='cancel'?'cancelled':'fail');expect((await runs(page))[0].cursor).toBe(1);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')!).doNotDisturb)).toBe(true);});
test('replacement speech fails the old workflow without stopping the replacement',async({page})=>{await start(page);const count=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const v=registerPlugin<any>('AlphaVoiceCloud');const prepared=await v.synthesizeLocal({text:'Replacement'});await v.play(prepared);return (window as any).speechTest.cancelled;});await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect(await page.evaluate(()=>(window as any).speechTest.cancelled)).toBe(count);expect(await page.evaluate(()=>(window as any).speechTest.utterance.text)).toBe('Replacement');});
test('cancelling while local voices load prevents late playback',async({page})=>{await page.evaluate(()=>(window as any).speechTest.voices=[]);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await runs(page))[0]?.inflight).toBe(1);await page.getByRole('button',{name:'Cancel run',exact:true}).click();await page.evaluate(()=>{(window as any).speechTest.voices=[{name:'Late',lang:'en-US',localService:true}];speechSynthesis.dispatchEvent(new Event('voiceschanged'));});await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');expect(await page.evaluate(()=>(window as any).speechTest.spoken)).toEqual([]);});
