import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('local call controls and hangup persist one call without external traffic',async({page})=>{
 const requests:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))requests.push(r.url());});await page.getByRole('button',{name:'Phone',exact:true}).click();await page.getByRole('button',{name:'Call Maya Chen',exact:true}).first().click();await expect(page.getByRole('button',{name:'End call',exact:true})).toBeVisible();await page.getByRole('button',{name:'Mute',exact:true}).click();await expect(page.getByRole('button',{name:'Unmute',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Speaker',exact:true}).click();await expect(page.getByRole('button',{name:'Speaker',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Show keypad',exact:true}).click();await page.getByRole('button',{name:'Tone 1',exact:true}).click();await page.getByRole('button',{name:'End call',exact:true}).click();await expect(page.getByRole('button',{name:'End call',exact:true})).toHaveCount(0);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).recents);expect(saved[0]).toMatchObject({pid:'maya',dir:'out'});await page.reload();await page.getByRole('button',{name:'Phone',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).recents[0].id)).toBe(saved[0].id);await expect(page.getByRole('button',{name:'End call',exact:true})).toHaveCount(0);expect(requests).toEqual([]);
});
test('failed local hangup can be retried and records exactly one call',async({page})=>{
 await page.getByRole('button',{name:'Phone',exact:true}).click();await page.getByRole('button',{name:'Call Maya Chen',exact:true}).first().click();await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restorePhoneSave=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.phone')throw Error('Storage full');return set.call(this,key,value);};});await page.getByRole('button',{name:'End call',exact:true}).click();await expect(page.getByRole('button',{name:'End call',exact:true})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.phone'))).toBeNull();await page.evaluate(()=>(window as any).restorePhoneSave());await page.getByRole('button',{name:'End call',exact:true}).click();await expect(page.getByRole('button',{name:'End call',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.phone')!).recents.filter((r:any)=>r.at&&r.pid==='maya').length)).toBe(1);
});
test('local message send and reload preserve exactly the written message without external traffic',async({page})=>{
 const requests:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:'))requests.push(r.url());});await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByRole('button',{name:'New message',exact:true}).click();await page.getByRole('button',{name:'Text Maya Chen',exact:true}).click();await page.getByRole('textbox',{name:'Message',exact:true}).fill('Local development message');await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.getByText('Local development message',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByRole('button',{name:'New message',exact:true}).click();await page.getByRole('button',{name:'Text Maya Chen',exact:true}).click();await expect(page.getByText('Local development message',{exact:true})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.messages')!).threads.maya.filter((m:any)=>m.text==='Local development message').length)).toBe(1);expect(requests).toEqual([]);
});
test('failed local message save retains the typed draft and retry sends once',async({page})=>{
 await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByRole('button',{name:'New message',exact:true}).click();await page.getByRole('button',{name:'Text Maya Chen',exact:true}).click();await page.getByRole('textbox',{name:'Message',exact:true}).fill('Retain this failed draft');await page.evaluate(()=>{const set=Storage.prototype.setItem;(window as any).restoreMessageSave=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.messages')throw Error('Storage full');return set.call(this,key,value);};});await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.getByRole('textbox',{name:'Message',exact:true})).toHaveValue('Retain this failed draft');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.messages')!).threads.maya.filter((m:any)=>m.text==='Retain this failed draft').length)).toBe(0);await page.evaluate(()=>(window as any).restoreMessageSave());await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.getByRole('textbox',{name:'Message',exact:true})).toHaveValue('');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.messages')!).threads.maya.filter((m:any)=>m.text==='Retain this failed draft').length)).toBe(1);
});
