import {test,expect} from '@playwright/test';
for(const app of ['Files','Photos'])test(`${app} search Ask composes the user's query and sends only after review`,async({page})=>{
 await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:app,exact:true}).click();await page.getByRole('button',{name:'Search '+app.toLowerCase(),exact:true}).click();await page.getByRole('textbox',{name:'Search '+app.toLowerCase(),exact:true}).fill('mountain trip');await page.getByRole('button',{name:'Ask Alpha: “mountain trip”',exact:true}).click();const composer=page.getByRole('textbox',{name:'Message Alpha',exact:true});await expect(composer).toHaveValue(app==='Files'?'Find the file mountain trip':'mountain trip');
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.agent.local.v1')||'{"conversations":[]}').conversations.flatMap((c:any)=>c.messages))).toEqual([]);
 await composer.fill('Reviewed search question');await page.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.agent.local.v1')!).conversations.flatMap((c:any)=>c.messages).filter((m:any)=>m.role==='user').map((m:any)=>m.text.split('[USER MESSAGE]\n')[1]))).toEqual(['Reviewed search question']);
});
test('Home attention opens the local Inbox and tracks unread mail through reload',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('alpha.dev.app.inbox'))localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[{id:'visible',name:'Reader',ini:'R',email:'reader@example.test',acct:'personal',k:1,time:'Now',unread:true,subj:'Visible unread',body:'Local body'},{id:'archived',name:'Reader',ini:'R',acct:'personal',unread:true,arch:true,subj:'Archived unread'},{id:'deleted',name:'Reader',ini:'R',acct:'personal',unread:true,del:true,subj:'Deleted unread'}],sent:[],localDrafts:[]}));});
 await page.goto('/?mode=dev');const attention=page.getByRole('button',{name:'Open Inbox: 1 unread email',exact:true});await expect(attention).toContainText('1');await attention.click();await page.getByText('Visible unread',{exact:true}).click();await expect(page.getByText('Local body',{exact:true}).last()).toBeVisible();await page.getByRole('button',{name:'Home',exact:true}).click();await expect(page.getByRole('button',{name:'Open Inbox: 0 unread emails',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Open Inbox: 0 unread emails',exact:true})).toBeVisible();
});
