import {test,expect,type Page} from '@playwright/test';
const journal=(page:Page)=>page.evaluate(()=>(Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[])[0]);
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));Object.defineProperty(navigator,'geolocation',{configurable:true,value:{watchPosition:()=>{throw Error('Host location must not be requested');},clearWatch:()=>{}}});});await page.goto('/?mode=dev');});
async function configure(page:Page,latitude=0,accuracy=5){await page.evaluate(async({latitude,accuracy})=>{const {SavedPlaces}=await import('/src/maps/saved-places.ts');const home=new SavedPlaces().save({label:'My home',coordinate:{latitude:0,longitude:0}});const {saveLocationSimulation}=await import('/src/browser/location-simulation.ts');saveLocationSimulation({mode:'coordinates',latitude,longitude:0,accuracy,homeId:home.id,radius:200});},{latitude,accuracy});}
async function workflow(page:Page){await page.evaluate(()=>localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:984,name:'Away test',on:true,trig:{kind:'time',days:'Every day',t:8},steps:[{k:'If',t:"I'm not at home",apps:['Location']},{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']}],runs:[]}],localRuns:{}})));await page.reload();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Away test',{exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();}
for(const [latitude,status,cursor] of [[0,'skip',1],[.01,'ok',2]] as const)test(`home condition uses actual coordinate distance: ${status}`,async({page})=>{await configure(page,latitude);await workflow(page);await expect.poll(async()=>(await journal(page))?.status).toBe(status);expect((await journal(page)).cursor).toBe(cursor);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')||'{}').doNotDisturb||false)).toBe(status==='ok');});
test('uncertain Home boundary cannot enable later actions',async({page})=>{await configure(page,.0018,100);await workflow(page);await expect.poll(async()=>(await journal(page))?.status).toBe('fail');expect((await journal(page)).sum).toContain('accuracy overlaps');expect((await journal(page)).cursor).toBe(0);});
test('location controls select a saved Home and persist validated coordinates',async({page},info)=>{await page.evaluate(async()=>{const {SavedPlaces}=await import('/src/maps/saved-places.ts');new SavedPlaces().save({label:'Home fixture',coordinate:{latitude:43.738,longitude:7.424}});});await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('dialog',{name:'Development device controls'}).getByRole('button',{name:'Location',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Development location'});await dialog.getByLabel('Home place',{exact:true}).selectOption({label:'Home fixture'});await dialog.getByRole('button',{name:'Use Home coordinates'}).click();await expect(dialog.getByLabel('Latitude',{exact:true})).toHaveValue('43.738');await dialog.getByLabel('Latitude',{exact:true}).fill('100');await dialog.getByRole('button',{name:'Save location'}).click();await expect(dialog.getByRole('status')).not.toBeEmpty();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.location.v1'))).toBeNull();await dialog.getByLabel('Latitude',{exact:true}).fill('43.738');await page.screenshot({path:info.outputPath('location-controls.png')});await dialog.getByRole('button',{name:'Save location'}).click();await expect(dialog).toHaveCount(0);await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.location.v1')!))).toMatchObject({latitude:43.738,longitude:7.424,mode:'coordinates',radius:200});});
test('live coordinate updates drive location listeners and sensor off retires the watch',async({page})=>{await configure(page);const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const {saveLocationSimulation,readLocationSimulation}=await import('/src/browser/location-simulation.ts');const location=registerPlugin<any>('ElizaLocation'),events:any[]=[];const listener=await location.addListener('locationChange',(fix:any)=>events.push(fix));await location.watchPosition();await new Promise(r=>setTimeout(r,20));saveLocationSimulation({...readLocationSimulation(),latitude:.01});await new Promise(r=>setTimeout(r,20));await registerPlugin<any>('AlphaDevice').setSensor({field:'locationEnabled',enabled:false});const count=events.length;saveLocationSimulation({...readLocationSimulation(),latitude:.02});await new Promise(r=>setTimeout(r,1100));await listener.remove();return {latitudes:events.map(e=>e.coords.latitude),count,final:events.length,permission:await location.checkPermissions()};});expect(result.latitudes).toContain(0);expect(result.latitudes).toContain(.01);expect(result.final).toBe(result.count);expect(result.permission.location).toBe('denied');});
test('background prevents starting a coordinate watch',async({page})=>{await configure(page);const blocked=await page.evaluate(async()=>{document.documentElement.dataset.devBackground='true';const {registerPlugin}=await import('/src/platform-plugins.ts');try{await registerPlugin<any>('ElizaLocation').watchPosition();return false;}catch{return true;}});expect(blocked).toBe(true);});
test('normal browser profile ignores developer coordinates',async({page})=>{await configure(page);await page.goto('/');const state=await page.evaluate(async()=>{const {readLocationSimulation}=await import('/src/browser/location-simulation.ts');return readLocationSimulation();});expect(state.mode).toBe('browser');});
test('a cancelled location condition retires a pending host fix without accepting it late',async({page})=>{await configure(page);const result=await page.evaluate(async()=>{const {readLocationSimulation,saveLocationSimulation}=await import('/src/browser/location-simulation.ts');saveLocationSimulation({...readLocationSimulation(),mode:'browser'});let callback:Function|undefined,cleared=0;Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'granted'})}});Object.defineProperty(navigator,'geolocation',{value:{watchPosition:(fn:Function)=>{callback=fn;return 42;},clearWatch:()=>cleared++}});const {workflowAwayFromHome}=await import('/src/browser/workflow-location.ts');const abort=new AbortController(),pending=workflowAwayFromHome(abort.signal).then(()=>false,error=>error.name==='AbortError');while(!callback)await new Promise(r=>setTimeout(r,0));abort.abort();callback({coords:{latitude:1,longitude:1,accuracy:5},timestamp:Date.now()});return {cancelled:await pending,cleared};});expect(result.cancelled).toBe(true);expect(result.cleared).toBeGreaterThan(0);});
test('Maps Recenter displays the configured development coordinates',async({page})=>{await configure(page,.01);await page.getByRole('button',{name:'Maps',exact:true}).click();await page.getByRole('button',{name:'Recenter',exact:true}).click();await expect(page.getByText('Current location',{exact:true})).toBeVisible();await expect(page.getByText('0.01000, 0.00000',{exact:true})).toBeVisible();await expect(page.getByText('Location fix · accuracy ±5 m',{exact:true})).toBeVisible();});
test('another tab updates the active coordinate stream',async({page,context})=>{await configure(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const location=registerPlugin<any>('ElizaLocation');(window as any).positionEvents=[];(window as any).positionListener=await location.addListener('locationChange',(value:any)=>(window as any).positionEvents.push(value.coords.latitude));(window as any).positionWatch=await location.watchPosition();});const other=await context.newPage();await other.goto('/?mode=dev');await other.evaluate(async()=>{const {readLocationSimulation,saveLocationSimulation}=await import('/src/browser/location-simulation.ts');saveLocationSimulation({...readLocationSimulation(),latitude:.02});});await expect.poll(()=>page.evaluate(()=>(window as any).positionEvents.includes(.02))).toBe(true);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('ElizaLocation').clearWatch((window as any).positionWatch);await (window as any).positionListener.remove();});await other.close();});
test('Home edits during a pending host fix reject the outdated boundary',async({page})=>{await configure(page);const error=await page.evaluate(async()=>{const {readLocationSimulation,saveLocationSimulation}=await import('/src/browser/location-simulation.ts');saveLocationSimulation({...readLocationSimulation(),mode:'browser'});let callback:Function|undefined;Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'granted'})}});Object.defineProperty(navigator,'geolocation',{value:{watchPosition:(fn:Function)=>{callback=fn;return 42;},clearWatch:()=>{}}});const {workflowAwayFromHome}=await import('/src/browser/workflow-location.ts');const pending=workflowAwayFromHome(new AbortController().signal).then(()=>'',error=>error.message);while(!callback)await new Promise(r=>setTimeout(r,0));const {SavedPlaces}=await import('/src/maps/saved-places.ts');new SavedPlaces().rename(readLocationSimulation().homeId,'Edited Home');callback({coords:{latitude:1,longitude:1,accuracy:5},timestamp:Date.now()});return pending;});expect(error).toContain('Home changed');});

test('changing Home during a held fix rejects the old boundary',async({page})=>{
 await configure(page);const result=await page.evaluate(async()=>{const {readLocationSimulation,saveLocationSimulation}=await import('/src/browser/location-simulation.ts');saveLocationSimulation({...readLocationSimulation(),mode:'browser'});let callback:Function|undefined;Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'granted'})}});Object.defineProperty(navigator,'geolocation',{value:{watchPosition:(fn:Function)=>{callback=fn;return 91;},clearWatch:()=>{}}});const {workflowAwayFromHome}=await import('/src/browser/workflow-location.ts');const pending=workflowAwayFromHome(new AbortController().signal).then(()=>'',error=>error.message);while(!callback)await new Promise(r=>setTimeout(r,0));saveLocationSimulation({...readLocationSimulation(),radius:500});callback({coords:{latitude:1,longitude:1,accuracy:5},timestamp:Date.now()});return pending;});expect(result).toContain('Home changed');
});

test('cancelling a pending permission request immediately clears its browser watch',async({page})=>{
 await configure(page);const result=await page.evaluate(async()=>{const {readLocationSimulation,saveLocationSimulation}=await import('/src/browser/location-simulation.ts');saveLocationSimulation({...readLocationSimulation(),mode:'browser'});let called=false,cleared=0;Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'prompt'})}});Object.defineProperty(navigator,'geolocation',{value:{watchPosition:()=>{called=true;return 73;},clearWatch:(id:number)=>{if(id===73)cleared++;}}});const {workflowAwayFromHome}=await import('/src/browser/workflow-location.ts');const abort=new AbortController();const pending=workflowAwayFromHome(abort.signal).then(()=>false,error=>error.name==='AbortError');while(!called)await new Promise(r=>setTimeout(r,0));abort.abort();return {cancelled:await pending,cleared};});expect(result.cancelled).toBe(true);expect(result.cleared).toBe(1);
});

test('cancelling one permission request leaves another owner active',async({page})=>{
 const result=await page.evaluate(async()=>{const {BrowserLocation}=await import('/src/browser/location.ts');let next=0;const callbacks:Function[]=[],cleared:number[]=[];Object.defineProperty(navigator,'geolocation',{value:{watchPosition:(fn:Function)=>{callbacks.push(fn);return ++next;},clearWatch:(id:number)=>cleared.push(id)}});const location=new BrowserLocation();const a=location.requestPermissions({requestId:'first'}),b=location.requestPermissions({requestId:'second'});await location.cancelPermissionRequest({requestId:'first'});const before=[...cleared];callbacks[1]();return {first:await a,second:await b,before,cleared};});expect(result.first.location).toBe('denied');expect(result.second.location).toBe('granted');expect(result.before).toEqual([1]);expect(result.cleared).toEqual([1,2]);
});
