import {test,expect} from '@playwright/test';
for(const [zone,due] of [['America/Los_Angeles','2027-03-13T08:00:00Z'],['Asia/Tokyo','2027-03-12T15:00:00Z']])test.describe(zone,()=>{test.use({timezoneId:zone});test('all-day alert starts at the local civil date and dismisses durably',async({page})=>{
 const at=Date.parse(due);await page.clock.setFixedTime(new Date(at-1));await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').save({calendarId:'local',title:'Civil-date alert',allDay:true,begin:Date.parse('2027-03-13T00:00:00Z'),end:Date.parse('2027-03-14T00:00:00Z'),alert:0});});
 const notices=()=>page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').list()).items.filter((n:any)=>n.id.startsWith('calendar:'));});expect(await notices()).toEqual([]);await page.clock.setFixedTime(new Date(at));const [notice]=await notices();expect(notice).toMatchObject({title:'Civil-date alert',at});await page.evaluate(async notice=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaNotifications').dismiss(notice);},notice);await page.reload();expect(await notices()).toEqual([]);
});});
test('damaged Calendar data does not block other notices and exposes an actionable warning',async({page})=>{
 await page.clock.setFixedTime(new Date('2027-03-13T12:00:00Z'));await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('DailyApps').scheduleReminder({id:'healthy-notice',title:'Healthy reminder',at:Date.now()+1000});localStorage.setItem('alpha.browser.calendar.v1','{damaged calendar');});await page.clock.setFixedTime(new Date('2027-03-13T12:00:02Z'));
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaNotifications').list();});expect(result.calendarStatus).toBe('unavailable');expect(result.items.map((n:any)=>n.title)).toContain('Healthy reminder');await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Notifications',exact:true}).click();await expect(page.getByText('Calendar alerts could not load. Open Calendar to review the problem.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Open Healthy reminder',exact:true})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.calendar.v1'))).toBe('{damaged calendar');
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaNotifications').dismiss((await registerPlugin<any>('AlphaNotifications').list()).items.find((n:any)=>n.id==='healthy-notice'));});expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').list()).items;})).toEqual([]);
});
