import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
async function seed(page:any,repeat='none',hour:number|null=null){return page.evaluate(async({repeat,hour})=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),begin=hour===null?Math.ceil(Date.now()/3600000)*3600000:new Date().setHours(hour,0,0,0);const result=await cal.save({creationId:crypto.randomUUID(),separateCreation:true,calendarId:'local',title:'Response event',body:'',location:'',begin,end:begin+3600000,who:['maya'],repeat});await cal.open({id:result.id});return result.id;},{repeat,hour});}
for(const hour of [10,23])test(`rendered guest responses persist and clear through ${hour===10?'same-day':'overnight'} editing`,async({page})=>{
 const id=await seed(page,'none',hour);for(const [value,label] of [['invited','Invited'],['yes','Going'],['maybe','Maybe'],['no','Declined']]){await page.getByRole('button',{name:/^Set response for Maya/}).click();const dialog=page.getByRole('dialog',{name:'Local guest response'});await dialog.getByLabel('Guest response',{exact:true}).selectOption(value);await dialog.getByRole('button',{name:'Save response',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:/^Maya/})).toContainText(label);}await page.reload();await page.evaluate(async(id)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').open({id});},id);await expect(page.getByRole('button',{name:/^Maya/})).toContainText('Declined');await page.getByRole('button',{name:/^Set response for Maya/}).click();await page.getByRole('dialog',{name:'Local guest response'}).getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].responses)).toEqual({maya:'no'});await page.getByRole('button',{name:'Edit event',exact:true}).click();if(hour===23)await page.getByRole('dialog',{name:'Edit calendar event'}).getByRole('checkbox',{name:'Maya Chen',exact:true}).uncheck();else await page.getByRole('button',{name:/^Remove Maya/}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);await expect.poll(()=>page.evaluate(async ()=>JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0].responses)).toEqual({});await expect(page.getByRole('button',{name:/^Set response for Maya/})).toHaveCount(0);
});
test('a recurring attendee response changes only the selected occurrence',async({page})=>{
 await seed(page,'daily');await page.getByRole('button',{name:/^Set response for Maya/}).click();const dialog=page.getByRole('dialog',{name:'Local guest response'});await dialog.getByLabel('Guest response',{exact:true}).selectOption('yes');await dialog.getByRole('button',{name:'Save response',exact:true}).click();await expect(dialog).toHaveCount(0);const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return registerPlugin<any>('AlphaCalendar').list({begin:Date.now(),end:Date.now()+3*86400000});});expect(result.events).toHaveLength(3);expect(result.events.map((r:any)=>r.responses?.maya||'added')).toEqual(['yes','added','added']);
});
test('stale guest review and failed storage keep the prior record unchanged',async({page})=>{
 const id=await seed(page);await page.getByRole('button',{name:/^Set response for Maya/}).click();const dialog=page.getByRole('dialog',{name:'Local guest response'});await dialog.getByLabel('Guest response',{exact:true}).selectOption('yes');await page.evaluate(async(id)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),row=JSON.parse((await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw())!).events[0];await cal.save({...row,id,expected:row,title:'Changed elsewhere'});},id);await dialog.getByRole('button',{name:'Save response',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('guest list changed');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(async(id)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaCalendar').open({id});},id);await page.getByRole('button',{name:/^Set response for Maya/}).click();const before=await page.evaluate(async ()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.calendar.v1')throw Error('Storage full');return original.call(this,value,key);};return (await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw());});await dialog.getByLabel('Guest response',{exact:true}).selectOption('maybe');await dialog.getByRole('button',{name:'Save response',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Storage full');expect(await page.evaluate(async ()=>(await (await import('/src/browser/calendar-store.ts')).calendarDocument.readRaw()))).toBe(before);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
});
