import {test,expect,type Page} from '@playwright/test';
const initial=Date.parse('2026-10-02T10:59:50'),begin=Date.parse('2026-10-02T11:00:00'),end=begin+60000;
const steps=[{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']},{k:'If',t:'A message is from Maya, let it through',apps:['Messages']},{k:'Write',t:'A summary of what I missed',apps:[]},{k:'Notify',t:'A notification when the block ends',apps:[]}];
const state=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!));
const runs=async(page:Page)=>Object.values((await state(page)).localRuns) as any[];
async function effectiveDnd(page:Page){return page.evaluate(async()=>{const {browserDeviceState}=await import('/src/browser/device.ts');return browserDeviceState().doNotDisturb;});}
async function setup(page:Page,overlap=false){await page.clock.setFixedTime(new Date(initial));await page.addInitScript(({steps,overlap})=>{if(localStorage.getItem('focusSeed'))return;localStorage.setItem('focusSeed','1');localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:(overlap?[910,911]:[910]).map(id=>({id,name:'Focus '+id,on:true,trig:{kind:'event',ev:'A deep-work event starts'},steps,runs:[]})),localRuns:{}}));localStorage.setItem('alpha.dev.app.messages',JSON.stringify({threads:{maya:[],jordan:[]},unread:{}}));localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[],sent:[]}));},{steps,overlap});await page.goto('/?mode=dev&tools=1');await page.evaluate(async({begin,end})=>{const {registerPlugin}=await import('/src/platform-plugins.ts');(window as any).focusEvent=await registerPlugin<any>('AlphaCalendar').save({creationId:crypto.randomUUID(),calendarId:'local',title:'Deep work block',begin,end,allDay:false,repeat:'none'});const {Component}=await import('/src/prototype/model.js');const old=Component.prototype.api;Component.prototype.api=function(key:string){const api=old.call(this,key);if(key==='workflows')(window as any).focusApi=api;return api;};},{begin,end});await expect.poll(async()=>(await state(page)).triggerState?.cursors.length).toBe(overlap?2:1);await page.clock.setFixedTime(new Date(begin+1));await expect.poll(async()=>(await runs(page)).filter(run=>run.sum==='Focus active').length).toBe(overlap?2:1);await expect.poll(()=>effectiveDnd(page)).toBe(true);}
async function arrivals(page:Page){await page.evaluate(()=>{const api=(window as any).focusApi;api.setView('messages',{threads:{maya:[{id:'maya-new',k:1,me:false,text:'Maya delivery',receivedAt:Date.now()}],jordan:[{id:'jordan-new',k:2,me:false,text:'Jordan delivery',receivedAt:Date.now()}]}});api.setView('inbox',{mails:[{id:'mail-new',subj:'Contract update',body:'Actual incoming email',receivedAt:Date.now(),atts:[]}]});});await expect.poll(async()=>(await runs(page))[0].context.focus.arrivals.length).toBe(3);}
async function notices(page:Page){return page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNotifications').list()).items;});}
test('focus holds actual arrivals, allows only Maya, then reviews and posts one end summary',async({page})=>{await setup(page);await arrivals(page);const current=await notices(page);expect(current.filter((row:any)=>row.id.startsWith('focus:')).map((row:any)=>row.text)).toEqual(['Maya delivery']);expect(JSON.stringify(current)).not.toContain('Jordan delivery');expect(localStorageBaseline(await page.evaluate(async()=>(await (await import('/src/browser/preference-documents.ts')).devicePreferencesDocument.readRaw())))).toBe(false);await page.clock.setFixedTime(new Date(end+1));await expect.poll(()=>effectiveDnd(page)).toBe(false);await expect.poll(async()=>(await runs(page))[0].sum).toBe('Waiting for focus summary');await expect(page.getByRole('dialog',{name:'Workflow step result'})).toHaveCount(0);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Focus 910',{exact:true}).click();const dialog=page.getByRole('dialog',{name:'Workflow step result'});await expect(dialog.getByLabel('Step input')).toHaveValue(/Jordan delivery/);await expect(dialog.getByLabel('Step input')).toHaveValue(/Actual incoming email/);await page.screenshot({path:'test-results/focus-summary-review.png'});await dialog.getByLabel('Development result').fill('Jordan and the contract update need review.');await dialog.getByRole('button',{name:'Use result',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');const noticesNow=await notices(page);expect(noticesNow.filter((row:any)=>row.id.startsWith('workflow:'))).toHaveLength(1);expect(noticesNow.find((row:any)=>row.id.startsWith('workflow:')).text).toBe('Jordan and the contract update need review.');await page.reload();expect(await effectiveDnd(page)).toBe(false);expect((await notices(page)).filter((row:any)=>row.id.startsWith('workflow:'))).toHaveLength(1);});
function localStorageBaseline(raw:string|null){return raw?JSON.parse(raw).doNotDisturb===true:false;}
test('cancelling focus releases its policy and preserves manual DND',async({page})=>{await setup(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'doNotDisturb',enabled:true});});await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Focus 910',{exact:true}).click();await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');expect((await runs(page))[0].context.focus.phase).toBe('cancelled');expect(await effectiveDnd(page)).toBe(true);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'doNotDisturb',enabled:false});});expect(await effectiveDnd(page)).toBe(false);});
test('reload retires a focus policy without replaying or leaving DND on',async({page})=>{await setup(page);await arrivals(page);await page.reload();expect(await effectiveDnd(page)).toBe(false);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Focus 910',{exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('interrupted');expect((await runs(page))[0].context.focus.arrivals).toHaveLength(3);expect((await notices(page)).filter((row:any)=>row.id.startsWith('workflow:'))).toEqual([]);});
test('disabling a focus workflow releases it before the Calendar block ends',async({page})=>{await setup(page);await page.evaluate(()=>{const api=(window as any).focusApi;api.setView('workflows',{flows:api.get('workflows').flows.map((flow:any)=>({...flow,on:false}))});});await expect.poll(()=>effectiveDnd(page)).toBe(false);await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect((await runs(page))[0].sum).toContain('workflow changed');});
test('overlapping focus runs preserve the remaining policy and deduplicate Maya notices',async({page})=>{await setup(page,true);await arrivals(page);await expect.poll(async()=>(await notices(page)).filter((row:any)=>row.id.startsWith('focus:')).length).toBe(1);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Focus 910',{exact:true}).click();await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page)).map(run=>run.status)).toEqual(['cancelled','running']);expect(await effectiveDnd(page)).toBe(true);});
for(const action of ['edit','delete'])test('Calendar '+action+' retires the old block and releases its focus policy',async({page})=>{await setup(page);await page.evaluate(async action=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const cal=registerPlugin<any>('AlphaCalendar'),event=(await cal.list({begin:Date.now(),end:Date.now()+1})).events.find((row:any)=>row.title==='Deep work block');if(action==='delete')await cal.remove({...event,expected:event});else await cal.save({...event,expected:event,end:event.end+60000});},action);await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect((await runs(page))[0].sum).toContain('Calendar block changed');expect(await effectiveDnd(page)).toBe(false);});
test('connected empty-block summary runs from Home only when the block ends',async({page})=>{await setup(page);await page.evaluate(async()=>{const {alphaClient}=await import('/src/runtime/alpha-client.ts');(window as any).focusRequests=[];alphaClient.attachVerifiedTransport({session:{ownerId:'owner',agentId:'agent',sessionId:'session',origin:'https://fixture.example'},send:async input=>{(window as any).focusRequests.push(input);return {text:'No incoming activity during this block.'};},execute:async()=>{throw Error('No actions');}});});expect(await page.evaluate(()=>(window as any).focusRequests)).toEqual([]);await page.clock.setFixedTime(new Date(end+1));await expect.poll(async()=>(await runs(page))[0].status).toBe('ok');expect(await page.evaluate(()=>(window as any).focusRequests.length)).toBe(1);expect((await notices(page)).find((row:any)=>row.id.startsWith('workflow:')).text).toBe('No incoming activity during this block.');expect(await effectiveDnd(page)).toBe(false);});
test('external notifications obey collection policy, stay held, and are removed from capture on revocation',async({page})=>{await setup(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications'),app=(await n.notificationApps()).apps[0];(window as any).focusPackage=app.packageName;await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,apps:[{packageName:app.packageName,preview:true}]});await n.inject({packageName:app.packageName,title:'Held device event',text:'Actual device text'});});await expect.poll(async()=>(await runs(page))[0].context.focus.arrivals.filter((row:any)=>row.kind==='notification').length,{timeout:20_000}).toBe(1);expect(JSON.stringify(await notices(page))).not.toContain('Actual device text');expect(JSON.stringify((await runs(page))[0].context.focus.arrivals)).not.toContain('Actual device text');expect(JSON.stringify((await runs(page))[0].context.focus.arrivals)).not.toContain('Held device event');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:false});});await expect.poll(async()=>(await runs(page))[0].context.focus.arrivals.filter((row:any)=>row.kind==='notification').length,{timeout:20_000}).toBe(0);});
test('focus arrival notifications redact on lock and support a checked dismissal',async({page})=>{await setup(page);await arrivals(page);const notice=(await notices(page)).find((row:any)=>row.id.startsWith('focus:'));await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Power',exact:true}).click();const hidden=(await notices(page)).find((row:any)=>row.id===notice.id);expect(hidden.text).toBe('');expect(hidden.canOpen).toBe(false);await page.getByRole('button',{name:'Unlock with fingerprint',exact:true}).click();await page.evaluate(async notice=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaNotifications').dismiss(notice);},notice);expect((await notices(page)).some((row:any)=>row.id===notice.id)).toBe(false);});
test('failed focus-intent save cannot enable its DND policy',async({page})=>{await setup(page);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Focus 910',{exact:true}).click();await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.workflows'&&Object.values(JSON.parse(value).localRuns||{}).some((run:any)=>run.status==='running'&&run.context.focus))throw Error('Full');return original.call(this,key,value);};});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await runs(page)).length).toBe(2);expect(await effectiveDnd(page)).toBe(false);expect((await runs(page))[1].status).toBe('fail');});

test('focus reconciles edited messages and archived email without duplicate arrivals',async({page})=>{await setup(page);await arrivals(page);await page.evaluate(()=>{const api=(window as any).focusApi,threads=api.get('messages').threads;api.setView('messages',{threads:{...threads,jordan:threads.jordan.map((row:any)=>({...row,text:'Updated Jordan delivery'}))}});api.setView('inbox',{mails:api.get('inbox').mails.map((row:any)=>({...row,arch:true}))});});await expect.poll(async()=>(await runs(page))[0].context.focus.arrivals.length).toBe(2);expect((await runs(page))[0].context.focus.arrivals.find((row:any)=>row.person==='jordan').text).toBe('Updated Jordan delivery');expect(await effectiveDnd(page)).toBe(true);});
test('disabling after block end retires a pending summary without a notification',async({page})=>{await setup(page);await page.clock.setFixedTime(new Date(end+1));await expect.poll(async()=>(await runs(page))[0].sum).toBe('Waiting for focus summary');await page.evaluate(()=>{const api=(window as any).focusApi;api.setView('workflows',{flows:api.get('workflows').flows.map((flow:any)=>({...flow,on:false}))});});await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect((await notices(page)).filter((row:any)=>row.id.startsWith('workflow:'))).toHaveLength(0);await expect(page.getByRole('dialog',{name:'Workflow step result'})).toHaveCount(0);});

test('outgoing mail is not captured as missed incoming activity',async({page})=>{await setup(page);await page.evaluate(()=>{const api=(window as any).focusApi;api.setView('inbox',{mails:[{id:'sent-new',subj:'Sent draft',body:'Outgoing only',sent:true,receivedAt:Date.now(),atts:[]},{id:'incoming-new',subj:'Incoming',body:'Incoming only',receivedAt:Date.now(),atts:[]}]});});await expect.poll(async()=>(await runs(page))[0].context.focus.arrivals.length).toBeGreaterThan(0);expect((await runs(page))[0].context.focus.arrivals.map((row:any)=>row.text)).toEqual(['Incoming only']);});
test('deleting the active Calendar block releases focus without a summary effect',async({page})=>{await setup(page);expect(await page.evaluate(async({begin,end})=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const calendar=registerPlugin<any>('AlphaCalendar');const row=(await calendar.list({begin,end})).events.find((row:any)=>row.title==='Deep work block');return (await calendar.remove({id:row.id,calendarId:row.calendarId,revision:row.revision,expected:row})).status;},{begin,end})).toBe('deleted');await expect.poll(async()=>(await runs(page))[0].status).toBe('fail');expect(await effectiveDnd(page)).toBe(false);expect((await notices(page)).filter((row:any)=>row.id.startsWith('workflow:'))).toEqual([]);});

test('malformed workflow storage does not disable the independent device controls',async({page})=>{await setup(page);const result=await page.evaluate(async()=>{const {browserDeviceState}=await import('/src/browser/device.ts');const key='alpha.dev.app.workflows',original=localStorage.getItem(key)!;const values=[];for(const raw of ['{broken','null',JSON.stringify({flows:{},localRuns:{invalid:null}})]){localStorage.setItem(key,raw);try{values.push({dnd:browserDeviceState().doNotDisturb});}catch{values.push({error:true});}}localStorage.setItem(key,original);return values;});expect(result).toEqual([{dnd:false},{dnd:false},{dnd:false}]);});

test('an edit during asynchronous focus capture cannot persist the stale message',async({page})=>{await setup(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const {BrowserNotifications}=await import('/src/browser/notifications.ts');const original=BrowserNotifications.prototype.focusSnapshot;const w=window as any;w.captured=[];const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alpha.dev.app.workflows')for(const run of Object.values(JSON.parse(value).localRuns||{}) as any[])w.captured.push(...(run.context?.focus?.arrivals||[]).map((row:any)=>row.text));return set.call(this,key,value);};let held=false;BrowserNotifications.prototype.focusSnapshot=async function(){const result=await original.call(this);if(!held){held=true;await new Promise<void>(resolve=>w.releaseCapture=resolve);}return result;};const api=w.focusApi;api.setView('messages',{threads:{maya:[],jordan:[{id:'capture-race',k:1,me:false,text:'Stale during read',receivedAt:Date.now()}]}});});await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseCapture)).toBe('function');await page.evaluate(()=>{const w=window as any,api=w.focusApi;api.setView('messages',{threads:{maya:[],jordan:[{id:'capture-race',k:1,me:false,text:'Corrected during read',receivedAt:Date.now()}]}});w.releaseCapture();});await expect.poll(async()=>(await runs(page))[0].context.focus.arrivals.find((row:any)=>row.person==='jordan')?.text).toBe('Corrected during read');expect(await page.evaluate(()=>(window as any).captured)).not.toContain('Stale during read');});

for(const mode of ['removed','delayed','off'])test('focus policy follows the DND step: '+mode,async({page})=>{
 await setup(page);await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Focus 910',{exact:true}).click();await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[0].status).toBe('cancelled');
 await page.evaluate(mode=>{const api=(window as any).focusApi,flows=api.get('workflows').flows.map((flow:any)=>({...flow,steps:mode==='removed'?flow.steps.slice(1):mode==='delayed'?[{k:'Write',t:'Wait for reviewed input',apps:[]},...flow.steps]:[flow.steps[0],{k:'Do',t:'Turn off Do Not Disturb',apps:['Settings']},...flow.steps.slice(1)]}));api.setView('workflows',{flows});},mode);
 await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await runs(page)).length).toBe(2);
 if(mode==='delayed'){const dialog=page.getByRole('dialog',{name:'Workflow step result'});await expect(dialog).toBeVisible();expect(await effectiveDnd(page)).toBe(false);await dialog.getByLabel('Development result').fill('Reviewed input');await dialog.getByRole('button',{name:'Use result',exact:true}).click();await expect.poll(()=>effectiveDnd(page)).toBe(true);}
 else {await expect.poll(async()=>(await runs(page))[1].sum).toBe('Focus active');expect(await effectiveDnd(page)).toBe(false);}
 await page.getByRole('button',{name:'Cancel run',exact:true}).click();await expect.poll(async()=>(await runs(page))[1].status).toBe('cancelled');expect(await effectiveDnd(page)).toBe(false);
});
