import {test,expect,Page} from '@playwright/test';
test.use({timezoneId:'America/New_York'});
const journal=(page:Page)=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!).localRuns) as any[]);
async function open(page:Page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Calendar read',{exact:true}).click();}
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2027-03-13T17:00:00Z'));await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!localStorage.getItem('alpha.dev.app.workflows'))localStorage.setItem('alpha.dev.app.workflows',JSON.stringify({flows:[{id:993,name:'Calendar read',on:true,short:'Read actual dates',summary:'Calendar range',trig:{kind:'time',days:'Every day',t:8},steps:[{k:'Read',t:'Calendar next 3 days',apps:['Calendar']}],runs:[]}],localRuns:{}}));});await page.goto('/?mode=dev');await open(page);});
test('three-day read handles DST, all-day civil bounds, overlaps and recurrence',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const calendar=registerPlugin<any>('AlphaCalendar');for(const [title,begin,end,allDay,repeat] of [['Ends at start','2027-03-13T04:00Z','2027-03-13T05:00Z',false,'none'],['Crosses start','2027-03-13T04:30Z','2027-03-13T05:30Z',false,'none'],['Last timed','2027-03-16T03:00Z','2027-03-16T04:00Z',false,'none'],['At end','2027-03-16T04:00Z','2027-03-16T05:00Z',false,'none'],['All-day before','2027-03-12T00:00Z','2027-03-13T00:00Z',true,'none'],['All-day last','2027-03-15T00:00Z','2027-03-16T00:00Z',true,'none'],['All-day after','2027-03-16T00:00Z','2027-03-17T00:00Z',true,'none'],['Recurring','2027-03-12T17:00Z','2027-03-12T18:00Z',false,'daily']])await calendar.save({calendarId:'local',title,begin:Date.parse(begin as string),end:Date.parse(end as string),allDay,repeat,timeZone:'America/New_York'});});
 await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');const rows=JSON.parse((await journal(page))[0].out);expect(rows.map((r:any)=>r.title).sort()).toEqual(['All-day last','Crosses start','Last timed','Recurring','Recurring','Recurring']);expect(rows.filter((r:any)=>r.title==='Recurring').map((r:any)=>new Date(r.begin).toISOString())).toEqual(['2027-03-13T17:00:00.000Z','2027-03-14T16:00:00.000Z','2027-03-15T16:00:00.000Z']);
});
test('today tomorrow and Monday-week ranges preserve civil DST boundaries',async({page})=>{const result=await page.evaluate(async()=>{const {workflowCalendarRange}=await import('/src/browser/workflow-calendar.ts');return ["Today's calendar","Tomorrow’s calendar","This week's calendar"].map(label=>{const r=workflowCalendarRange(label)!;return [new Date(r.begin).toISOString(),new Date(r.end).toISOString(),new Date(r.civilBegin).toISOString(),new Date(r.civilEnd).toISOString()];});});expect(result).toEqual([['2027-03-13T05:00:00.000Z','2027-03-14T05:00:00.000Z','2027-03-13T00:00:00.000Z','2027-03-14T00:00:00.000Z'],['2027-03-14T05:00:00.000Z','2027-03-15T04:00:00.000Z','2027-03-14T00:00:00.000Z','2027-03-15T00:00:00.000Z'],['2027-03-08T05:00:00.000Z','2027-03-15T04:00:00.000Z','2027-03-08T00:00:00.000Z','2027-03-15T00:00:00.000Z']]);});
for(const [kind,matched] of [['guests',true],['video',true],['solo',false],['all-day',false],['ended',false],['future',false]] as const)test('meeting condition evaluates '+kind,async({page})=>{await page.evaluate(async(kind)=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const now=Date.now(),begin=kind==='all-day'?Date.parse('2027-03-13T00:00Z'):kind==='future'?now+60000:now-60000,end=kind==='all-day'?Date.parse('2027-03-14T00:00Z'):kind==='ended'?now:now+120000;await registerPlugin<any>('AlphaCalendar').save({calendarId:'local',title:'Calendar entry',begin,end,allDay:kind==='all-day',who:kind==='solo'||kind==='video'?[]:['maya'],video:kind==='video',timeZone:'America/New_York'});const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'If',t:"I'm in a meeting",apps:['Calendar']},{k:'Do',t:'Turn on Do Not Disturb',apps:['Settings']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));},kind);await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe(matched?'ok':'skip');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.device.v1')||'{}').doNotDisturb||false)).toBe(matched);});
test('truncated calendar input cannot report a complete read',async({page})=>{await page.evaluate(async()=>{const {BrowserCalendar}=await import('/src/browser/calendar.ts');BrowserCalendar.prototype.list=async()=>({status:'ready',calendars:[],events:[],truncated:true});});await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('fail');expect((await journal(page))[0].cursor).toBe(0);expect((await journal(page))[0].sum).toContain('supported range');});
test('fall-back calendar day spans 25 hours without widening its civil dates',async({page})=>{const range=await page.evaluate(async()=>{const {workflowCalendarRange}=await import('/src/browser/workflow-calendar.ts');return workflowCalendarRange("Today's calendar",new Date('2027-11-07T17:00Z'))!;});expect(range.end-range.begin).toBe(25*60*60*1000);expect(new Date(range.begin).toISOString()).toBe('2027-11-07T04:00:00.000Z');expect(new Date(range.end).toISOString()).toBe('2027-11-08T05:00:00.000Z');expect(range.civilEnd-range.civilBegin).toBe(86400000);});
test.describe('eastern civil dates',()=>{test.use({timezoneId:'Pacific/Kiritimati'});test('UTC+14 reads only the local date for all-day entries',async({page})=>{await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const calendar=registerPlugin<any>('AlphaCalendar');for(const day of [13,14,15])await calendar.save({calendarId:'local',title:'Day '+day,allDay:true,begin:Date.UTC(2027,2,day),end:Date.UTC(2027,2,day+1),timeZone:'UTC'});const s=JSON.parse(localStorage.getItem('alpha.dev.app.workflows')!);s.flows[0].steps=[{k:'Read',t:"Today's calendar",apps:['Calendar']}];localStorage.setItem('alpha.dev.app.workflows',JSON.stringify(s));});await page.reload();await open(page);await page.getByRole('button',{name:'Run now',exact:true}).click();await expect.poll(async()=>(await journal(page))[0]?.status).toBe('ok');expect(JSON.parse((await journal(page))[0].out).map((r:any)=>r.title)).toEqual(['Day 14']);});});
