import {test,expect,type Page} from '@playwright/test';
async function boot(page:Page){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&tools=1');}
test('empty device hydration does not invent persisted settings or roles',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const prefs=await import('/src/browser/device-preferences.ts'),{devicePreferencesDocument,deviceRolesDocument}=await import('/src/browser/preference-documents.ts');await prefs.refreshDevicePreferences();return {status:prefs.devicePreferencesStatus(),volume:prefs.cachedDevicePreferences()?.music,settings:(await devicePreferencesDocument.capture()).snapshot??null,roles:(await deviceRolesDocument.capture()).snapshot??null};})).toEqual({status:'ready',volume:70,settings:null,roles:null});
});
test('two tabs retain distinct setting changes and update the sensor cache',async({page,context})=>{
 await boot(page);const other=await context.newPage();await other.goto('/?mode=dev');await Promise.all([page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setBrightness({percent:35});}),other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'microphoneEnabled',enabled:false});})]);
 expect(await page.evaluate(async()=>(await import('/src/browser/device-preferences.ts')).readDevicePreferences())).toMatchObject({brightness:35,microphoneEnabled:false});await expect.poll(()=>page.evaluate(async()=>(await import('/src/browser/sensor-policy.ts')).browserSensorEnabled('microphoneEnabled'))).toBe(false);
});
test('partial legacy settings preserve exact bytes while edits hydrate missing defaults',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!sessionStorage.getItem('seeded')){localStorage.setItem('alpha.browser.device.v1','{ "music": 20 }');sessionStorage.setItem('seeded','1');}});await page.goto('/?mode=dev&tools=1');expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaDevice').setSensor({field:'doNotDisturb'});const {readDevicePreferences}=await import('/src/browser/device-preferences.ts'),{devicePreferencesDocument}=await import('/src/browser/preference-documents.ts'),state=await readDevicePreferences(),capture=await devicePreferencesDocument.capture();return {music:state.music,dnd:state.doNotDisturb,wifi:state.wifiActive,legacy:localStorage.getItem('alpha.browser.device.v1'),baseline:JSON.parse(capture.snapshot!.raw!).legacy};})).toEqual({music:20,dnd:true,wifi:true,legacy:'{ "music": 20 }',baseline:'{ "music": 20 }'});
});
for(const action of ['permission','watch'] as const)test(`retired location ${action} read cannot start geolocation`,async({page})=>{
 await boot(page);await page.evaluate(async action=>{const {devicePreferencesDocument:store}=await import('/src/browser/preference-documents.ts'),{BrowserLocation}=await import('/src/browser/location.ts'),prefs=await import('/src/browser/device-preferences.ts');await prefs.refreshDevicePreferences();const location=new BrowserLocation(),read=store.read.bind(store);(window as any).geoRequests=0;Object.defineProperty(navigator,'geolocation',{configurable:true,value:{watchPosition(){(window as any).geoRequests++;return 1;},clearWatch(){}}});let first=true;store.read=async(...args)=>{const value=await read(...args);if(first){first=false;(window as any).deviceReadQueued=true;await new Promise<void>(resolve=>(window as any).releaseDeviceRead=resolve);}return value;};(window as any).locationFixture=location;(window as any).locationRequest=(action==='permission'?location.requestPermissions({requestId:'owned'}):location.watchPosition()).catch(()=>({location:'denied'}));},action);
 await expect.poll(()=>page.evaluate(()=>(window as any).deviceReadQueued)).toBe(true);expect(await page.evaluate(async action=>{if(action==='permission')await (window as any).locationFixture.cancelPermissionRequest({requestId:'owned'});else window.dispatchEvent(new Event('alpha:device-state'));(window as any).releaseDeviceRead();const result=await (window as any).locationRequest;return {result,requests:(window as any).geoRequests};},action)).toMatchObject({result:{location:'denied'},requests:0});
});
test('Home retires a settings dialog before its canonical read completes',async({page})=>{
 await boot(page);await page.evaluate(async()=>{const {devicePreferencesDocument:store}=await import('/src/browser/preference-documents.ts'),{registerPlugin}=await import('/src/platform-plugins.ts'),read=store.read.bind(store);store.read=async(...args)=>{const value=await read(...args);if(args[1]){(window as any).deviceReadQueued=true;await new Promise<void>(resolve=>(window as any).releaseDeviceRead=resolve);}return value;};(window as any).settingsOpening=registerPlugin<any>('AlphaDevice').openSettings({page:'sound'}).then(()=>true,()=>false);});await expect.poll(()=>page.evaluate(()=>(window as any).deviceReadQueued)).toBe(true);expect(await page.evaluate(async()=>{window.dispatchEvent(new Event('launcher-home'));(window as any).releaseDeviceRead();return (window as any).settingsOpening;})).toBe(false);await expect(page.getByRole('dialog',{name:'sound settings'})).toHaveCount(0);
});
test('damaged settings keep recovery reachable and reset only after exact-byte backup',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!sessionStorage.getItem('seeded')){localStorage.setItem('alpha.browser.device.v1','{damaged settings');sessionStorage.setItem('seeded','1');}});await page.goto('/?mode=dev&tools=1');
 // Wait for the registered app controls before inspecting its hydration state.
 await expect(page.getByRole('button',{name:'Device controls',exact:true})).toBeVisible();
 await expect.poll(()=>page.evaluate(async()=>(await import('/src/browser/device-preferences.ts')).devicePreferencesStatus())).toBe('unavailable');expect(await page.evaluate(async()=>(await import('/src/browser/audio-settings.ts')).browserMediaVolume())).toBe(0);
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Device settings recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Device settings recovery'}),pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download device settings backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe('{damaged settings');await dialog.getByRole('button',{name:'Reset browser device settings',exact:true}).click();await dialog.getByRole('button',{name:'Confirm device settings reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>(await import('/src/browser/device-preferences.ts')).readDevicePreferences())).toMatchObject({music:70,microphoneEnabled:true});
});
test('late hydration cannot overwrite a newer committed sensor setting in the render cache',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const prefs=await import('/src/browser/device-preferences.ts'),{devicePreferencesDocument:store}=await import('/src/browser/preference-documents.ts');await prefs.refreshDevicePreferences();const read=store.read.bind(store);let release!:()=>void,queued!:()=>void,first=true;const waiting=new Promise<void>(resolve=>queued=resolve);store.read=async(...args)=>{const value=await read(...args);if(first){first=false;queued();await new Promise<void>(resolve=>release=resolve);}return value;};const old=prefs.refreshDevicePreferences();await waiting;await prefs.editDevicePreferences(state=>{state.microphoneEnabled=false;});release();await old;return {cached:prefs.cachedDevicePreferences()?.microphoneEnabled,stored:(await prefs.readDevicePreferences()).microphoneEnabled};})).toEqual({cached:false,stored:false});
});
test('concurrent simulated role selections retain both grants',async({page,context})=>{
 await boot(page);const other=await context.newPage();await other.goto('/?mode=dev');await Promise.all([page,other].map((tab,index)=>tab.evaluate(async role=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('ElizaSystem').requestRole({role});},index?'assistant':'home')));expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('ElizaSystem').getStatus()).roles.filter((row:any)=>row.held).map((row:any)=>row.role);})).toEqual(['home','assistant']);expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.roles.v1'))).toBeNull();
});
