import {test,expect,type Page} from '@playwright/test';
async function boot(page:Page){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.evaluate(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'local'})));}
async function due(page:Page){await page.evaluate(async()=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentDigestDocument,initialDevelopmentDigests}=await import('/src/browser/development-digest-document.ts'),identity=developmentIdentity('local'),now=Date.now(),source:any=await request(identity,'/api/workflow/hosted/sources',{id:crypto.randomUUID(),kind:'notes',label:'Reviewed notes',text:'Snapshot',observedAt:new Date(now).toISOString(),expiresAt:new Date(now+3600000).toISOString(),confirmed:true});await request(identity,'/api/workflow/hosted/loops',{mutationId:crypto.randomUUID(),confirmed:true,spec:{version:1,template:'morning',sourceId:source.source.id,sourceRevision:source.source.revision,enabled:true,timeZone:'UTC',localTime:new Date(now).toISOString().slice(11,16)}});await developmentDigestDocument(identity).edit(initialDevelopmentDigests,state=>{state.loops[0].createdAt=now-120000;});});}
test('empty digest polling and repeated unchanged reads preserve the absence of a document',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentDigestDocument}=await import('/src/browser/development-digest-document.ts'),identity=developmentIdentity('local');for(let i=0;i<5;i++)for(const path of ['tick','sources','loops','results?clientId=reader'])await request(identity,'/api/workflow/hosted/'+path,undefined);return (await developmentDigestDocument(identity).capture()).snapshot??null;})).toBeNull();
});
test('two tabs ticking the same occurrence retain one result and both delivery acknowledgements',async({page,context})=>{
 await page.clock.setFixedTime(new Date('2026-10-03T12:00:10Z'));await boot(page);await due(page);const other=await context.newPage();await other.clock.setFixedTime(new Date('2026-10-03T12:00:10Z'));await boot(other);
 await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),identity=developmentIdentity('local'),clientId='reader-'+index,result:any=await request(identity,'/api/workflow/hosted/results?clientId='+clientId,undefined);await request(identity,'/api/workflow/hosted/results/ack',{clientId,cursor:result.entries[0].cursor,runId:result.entries[0].runId});},index)));
 expect(await page.evaluate(async()=>{const {readDevelopmentDigests,developmentDigestDocument}=await import('/src/browser/development-digest-document.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),identity=developmentIdentity('local'),state=await readDevelopmentDigests(identity),before=await developmentDigestDocument(identity).capture();await request(identity,'/api/workflow/hosted/tick',undefined);return {runs:state.results.length,cursor:state.cursor,acks:state.acks,stable:JSON.stringify(before.snapshot)===JSON.stringify((await developmentDigestDocument(identity).capture()).snapshot),legacy:localStorage.getItem('alpha.browser.digests.local.v1')};})).toEqual({runs:1,cursor:1,acks:{'reader-0':1,'reader-1':1},stable:true,legacy:null});
});
test('failed occurrence commit rolls back the cursor, result and scheduled occurrence together',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-03T12:00:10Z'));await boot(page);await due(page);expect(await page.evaluate(async()=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentDigestDocument,readDevelopmentDigests}=await import('/src/browser/development-digest-document.ts'),identity=developmentIdentity('local'),domain=developmentDigestDocument(identity),before=await domain.capture(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.digests.local.v1')throw Error('Full');return put.call(this,value,key);};let rejected=false;try{await request(identity,'/api/workflow/hosted/tick',undefined);}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}const same=JSON.stringify(before.snapshot)===JSON.stringify((await domain.capture()).snapshot);await request(identity,'/api/workflow/hosted/tick',undefined);const state=await readDevelopmentDigests(identity);return {rejected,same,runs:state.results.length,cursor:state.cursor,occurrence:state.loops[0].lastOccurrence};})).toEqual({rejected:true,same:true,runs:1,cursor:1,occurrence:'2026-10-03T12:00'});
});
test('a retired digest run cannot commit a reply read for the prior connection',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-03T12:00:10Z'));await boot(page);await due(page);expect(await page.evaluate(async()=>{const {developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentDigestDocument}=await import('/src/browser/development-digest-document.ts'),{browserDocuments}=await import('/src/browser/documents.ts'),identity=developmentIdentity('local'),before=await developmentDigestDocument(identity).capture(),read=browserDocuments.read.bind(browserDocuments);let release!:()=>void,queued!:()=>void;const waiting=new Promise<void>(resolve=>queued=resolve);browserDocuments.read=async(...args)=>{const value=await read(...args);if(args[0]==='alpha.browser.agent.local.v1'){queued();await new Promise<void>(resolve=>release=resolve);}return value;};const pending=request(identity,'/api/workflow/hosted/tick',undefined).then(()=>false,()=>true);await waiting;localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));release();return {rejected:await pending,same:JSON.stringify(before.snapshot)===JSON.stringify((await developmentDigestDocument(identity).capture()).snapshot)};})).toEqual({rejected:true,same:true});
});
test('exact legacy digest bytes survive migration and later changes refuse access',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentDigestDocument,readDevelopmentDigests}=await import('/src/browser/development-digest-document.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),identity=developmentIdentity('local'),raw='{ "sources": [], "loops": [], "receipts": [], "results": [], "cursor": 0, "acks": {} }';localStorage.setItem('alpha.browser.digests.local.v1',raw);await readDevelopmentDigests(identity);const domain=developmentDigestDocument(identity),capture=await domain.capture();localStorage.setItem('alpha.browser.digests.local.v1','{changed');let rejected=false;try{await readDevelopmentDigests(identity);}catch{rejected=true;}return {exact:capture.raw===raw,rejected,retained:(await domain.capture()).raw===raw};})).toEqual({exact:true,rejected:true,retained:true});
});
test('a saved grant request prevents a stale digest reset',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentDigestDocument,readDevelopmentDigests}=await import('/src/browser/development-digest-document.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentDigestRequest:request}=await import('/src/browser/development-digests.ts'),identity=developmentIdentity('local'),domain=developmentDigestDocument(identity),before=await domain.capture();await request(identity,'/api/workflow/hosted/cloud-delegation/start',{mutationId:crypto.randomUUID(),kinds:['email'],confirmed:true});let rejected=false;try{await domain.reset(before);}catch{rejected=true;}return {rejected,requests:(await readDevelopmentDigests(identity)).delegation!.requests.length};})).toEqual({rejected:true,requests:1});
});
test('damaged digest schedules remain recoverable without discarding the original bytes',async({page})=>{
 await boot(page);await page.evaluate(()=>localStorage.setItem('alpha.browser.digests.local.v1','{damaged schedules'));await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Digest schedule recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Development digest schedule recovery'}),pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download digest schedules backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe('{damaged schedules');await dialog.getByRole('button',{name:'Reset app digest schedules',exact:true}).click();await dialog.getByRole('button',{name:'Confirm digest schedules reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>{const {readDevelopmentDigests}=await import('/src/browser/development-digest-document.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');return {state:await readDevelopmentDigests(developmentIdentity('local')),legacy:localStorage.getItem('alpha.browser.digests.local.v1')};})).toEqual({state:{sources:[],loops:[],receipts:[],results:[],cursor:0,acks:{}},legacy:'{damaged schedules'});
});
