import {test,expect,type Page} from '@playwright/test';
const scope='a'.repeat(64),key='alpha.browser.cloud-delegation:'+scope;
async function boot(page:Page){
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));
 await page.goto('/?mode=dev');
 await page.evaluate(async scope=>{const {digestAuthorizationDocument}=await import('/src/browser/digest-authorization-document.ts');const f=(window as any).authorizationFixture={current:true,controller:new AbortController(),record:{mutationId:'00000000-0000-4000-8000-000000000001',kinds:['email'],phase:'start'}};f.store=digestAuthorizationDocument(scope,()=>f.current,f.controller.signal);},scope);
}
test('empty authorization reads do not claim a document',async({page})=>{await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).authorizationFixture;return {pending:await f.store.read(),snapshot:(await f.store.capture()).snapshot??null};})).toEqual({pending:null,snapshot:null});});
test('concurrent tabs admit one authorization and notify the losing owner',async({page,context})=>{
 await boot(page);const other=await context.newPage();await boot(other);
 await page.evaluate(()=>{const f=(window as any).authorizationFixture;f.notifications=0;f.store.subscribe(()=>f.notifications++);});
 const results=await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const f=(window as any).authorizationFixture;try{await f.store.save(null,{...f.record,mutationId:'00000000-0000-4000-8000-00000000000'+(index+1)});return true;}catch{return false;}},index)));
 expect(results.filter(Boolean)).toHaveLength(1);
 const saved=await other.evaluate(async()=>{const f=(window as any).authorizationFixture;return f.store.read();});
 expect(await page.evaluate(async()=>{const f=(window as any).authorizationFixture;return f.store.read();})).toEqual(saved);
 await other.evaluate(async()=>{const f=(window as any).authorizationFixture;await f.store.save(await f.store.read(),null);});
 await expect.poll(()=>page.evaluate(()=>(window as any).authorizationFixture.notifications)).toBeGreaterThan(0);
 expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.cloud-delegation:'+'a'.repeat(64)))).toBeNull();
});
test('failed first authorization commit cannot claim a durable pending request',async({page})=>{
 await boot(page);expect(await page.evaluate(async key=>{const f=(window as any).authorizationFixture,put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,k){if(k===key)throw Error('Full');return put.call(this,value,k);};let rejected=false;try{await f.store.save(null,f.record);}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}return {rejected,pending:await f.store.read(),snapshot:(await f.store.capture()).snapshot??null};},key)).toEqual({rejected:true,pending:null,snapshot:null});
});
test('exact legacy authorization is retained and changed older bytes stop access',async({page})=>{
 await boot(page);expect(await page.evaluate(async key=>{const f=(window as any).authorizationFixture,raw=' { "pending": '+JSON.stringify(f.record)+' } ';localStorage.setItem(key,raw);await f.store.read();const before=await f.store.capture();await f.store.save(f.record,null);localStorage.setItem(key,'{damaged older');let rejected=false;try{await f.store.read();}catch{rejected=true;}const after=await f.store.capture();return {exact:before.raw===raw,rejected,changed:after.legacyChanged,pending:JSON.parse(after.raw).pending};},key)).toEqual({exact:true,rejected:true,changed:true,pending:null});
});
test('stale recovery cannot erase a newer authorization',async({page})=>{await boot(page);expect(await page.evaluate(async()=>{const f=(window as any).authorizationFixture,capture=await f.store.capture();await f.store.save(null,f.record);let rejected=false;try{await f.store.reset(capture);}catch{rejected=true;}return {rejected,retained:JSON.stringify(await f.store.read())===JSON.stringify(f.record)};})).toEqual({rejected:true,retained:true});});
test('retirement refuses a late read and all subsequent saves',async({page})=>{
 await boot(page);expect(await page.evaluate(async key=>{const f=(window as any).authorizationFixture,{browserDocuments}=await import('/src/browser/documents.ts');await f.store.save(null,f.record);const read=browserDocuments.read.bind(browserDocuments);let release!:()=>void,queued!:()=>void;const started=new Promise<void>(resolve=>queued=resolve);browserDocuments.read=async(...args)=>{const result=await read(...args);if(args[0]===key){queued();await new Promise<void>(resolve=>release=resolve);}return result;};const pending=f.store.read().then(()=>false,()=>true);await started;f.current=false;f.controller.abort();release();const readRejected=await pending;let saveRejected=false;try{await f.store.save(f.record,null);}catch{saveRejected=true;}return {readRejected,saveRejected};},key)).toEqual({readRejected:true,saveRejected:true});
});
const panel=(page:Page)=>page.getByRole('dialog',{name:'Scheduled digests',exact:true});
async function setup(page:Page){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.evaluate(()=>window.dispatchEvent(new Event('alpha:hosted-digests')));await panel(page).getByText('Use live Google data',{exact:true}).click();await panel(page).getByText('Connect Cloud for scheduled reads',{exact:true}).click();}
test('authorization recovery keeps keyboard and Back ownership above Scheduled digests',async({page})=>{
 await setup(page);const trigger=panel(page).getByRole('button',{name:'Authorization recovery',exact:true});await trigger.click();const recovery=page.getByRole('dialog',{name:'Development digest authorization recovery',exact:true});await expect(recovery).toBeVisible();await expect(recovery.getByRole('button',{name:'Close recovery',exact:true})).toBeFocused();await page.keyboard.press('Tab');await expect.poll(()=>page.evaluate(()=>!!document.activeElement?.closest('dialog[open]'))).toBe(true);await page.keyboard.press('Escape');await expect(recovery).toHaveCount(0);await expect(panel(page)).toBeVisible();await expect(trigger).toBeFocused();await trigger.click();await expect(recovery).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(recovery).toHaveCount(0);await expect(panel(page)).toBeVisible();
});
test('closing authorization aborts the pending request without losing its saved recovery',async({page})=>{
 await setup(page);await page.evaluate(async()=>{const {HostedDigestProtocol}=await import('/src/runtime/hosted-digests.ts'),original=HostedDigestProtocol.prototype.delegation;HostedDigestProtocol.prototype.delegation=async function(path,body,signal){if(path==='start'){(window as any).authorizationStarted=true;return new Promise((_,reject)=>signal.addEventListener('abort',()=>{(window as any).authorizationAborted=true;reject(Error('Aborted'));},{once:true}));}return original.call(this,path,body,signal);};});await panel(page).getByRole('button',{name:'Review Cloud read access',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).authorizationStarted)).toBe(true);await page.keyboard.press('Escape');await expect(panel(page)).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>(window as any).authorizationAborted)).toBe(true);
 expect(await page.evaluate(async()=>{const {developmentIdentity}=await import('/src/browser/development-identity.ts'),{actionScope}=await import('/src/runtime/device-actions.ts'),{digestAuthorizationDocument}=await import('/src/browser/digest-authorization-document.ts');const owner=developmentIdentity('local'),scope=await actionScope(JSON.stringify(['https://development.alpha.invalid',owner.ownerId,owner.agentId]));return (await digestAuthorizationDocument(scope,()=>true,new AbortController().signal).read())?.phase;})).toBe('start');
});
test('damaged authorization downloads exact bytes before confirmed reset',async({page})=>{
 await boot(page);await page.evaluate(async key=>{const f=(window as any).authorizationFixture;localStorage.setItem(key,' {damaged authorization ');const {openDomainRecovery}=await import('/src/browser/domain-recovery.ts');openDomainRecovery(f.store,'digest authorization','Development digest authorization recovery','Back up the saved request.',f.controller.signal);},key);const dialog=page.getByRole('dialog',{name:'Development digest authorization recovery'}),pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download digest authorization backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe(' {damaged authorization ');await dialog.getByRole('button',{name:'Reset browser digest authorization',exact:true}).click();await dialog.getByRole('button',{name:'Confirm digest authorization reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async key=>{const {browserDocuments}=await import('/src/browser/documents.ts');return {value:JSON.parse((await browserDocuments.read(key))!.raw!).value,legacy:localStorage.getItem(key)};},key)).toEqual({value:null,legacy:' {damaged authorization '});
});
test('backgrounding authorization aborts start and requires reopening before another action',async({page})=>{
 await setup(page);await page.evaluate(async()=>{const {HostedDigestProtocol}=await import('/src/runtime/hosted-digests.ts');HostedDigestProtocol.prototype.delegation=async function(_path,_body,signal){(window as any).authorizationStarted=true;return new Promise((_,reject)=>signal.addEventListener('abort',()=>{(window as any).authorizationAborted=true;reject(Error('Aborted'));},{once:true}));};});await panel(page).getByRole('button',{name:'Review Cloud read access',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).authorizationStarted)).toBe(true);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await expect.poll(()=>page.evaluate(()=>(window as any).authorizationAborted)).toBe(true);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await expect(panel(page).getByText('Authorization paused. Close and reopen scheduled digests to continue.',{exact:true})).toBeVisible();await expect(panel(page).getByRole('button',{name:'Check authorization status',exact:true})).toBeDisabled();
});
test('unreadable authorization keeps recovery reachable and blocks a replacement request',async({page})=>{
 await setup(page);await page.keyboard.press('Escape');await page.evaluate(async()=>{const {developmentIdentity}=await import('/src/browser/development-identity.ts'),{actionScope}=await import('/src/runtime/device-actions.ts');const owner=developmentIdentity('local'),scope=await actionScope(JSON.stringify(['https://development.alpha.invalid',owner.ownerId,owner.agentId]));localStorage.setItem('alpha.browser.cloud-delegation:'+scope,'{broken pending');window.dispatchEvent(new Event('alpha:hosted-digests'));});await panel(page).getByText('Use live Google data',{exact:true}).click();await panel(page).getByText('Connect Cloud for scheduled reads',{exact:true}).click();await expect(panel(page).getByText('Saved authorization could not be read. Use authorization recovery.',{exact:true})).toBeVisible();await expect(panel(page).getByRole('button',{name:'Review Cloud read access',exact:true})).toBeDisabled();await panel(page).getByRole('button',{name:'Authorization recovery',exact:true}).click();const recovery=page.getByRole('dialog',{name:'Development digest authorization recovery'});await expect(recovery.getByRole('button',{name:'Download digest authorization backup',exact:true})).toBeEnabled();await expect(recovery.getByText(/does not revoke a completed grant/)).toBeVisible();
});
