import {test,expect,type Page} from '@playwright/test';
async function boot(page:Page){await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');await page.evaluate(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'local'})));}
test('empty workflow and action reads do not create execution history',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentWorkflowRequest}=await import('/src/browser/development-workflows.ts'),{developmentActionRequest}=await import('/src/browser/development-actions.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentExecutionDocument}=await import('/src/browser/development-execution-document.ts'),identity=developmentIdentity('local');return {workflows:await developmentWorkflowRequest(identity,'/api/workflow/workflows',undefined),actions:await developmentActionRequest('local','/api/client-devices/proposals',undefined),snapshot:(await developmentExecutionDocument(identity).capture()).snapshot??null};})).toEqual({workflows:{workflows:[]},actions:{proposals:[]},snapshot:null});
});
test('concurrent workflow and proposal creation retain every receipt in the shared account document',async({page,context})=>{
 await boot(page);const other=await context.newPage();await boot(other);await Promise.all([page.evaluate(async()=>{const {developmentWorkflowRequest:request}=await import('/src/browser/development-workflows.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts');for(let i=0;i<10;i++)await request(developmentIdentity('local'),'/api/workflow/phone/workflows',{catalogRevision:'development-v1',compilerRevision:'development-v1',mutationId:crypto.randomUUID(),spec:{version:1,name:'Workflow '+i,description:'',trigger:{kind:'manual'},steps:[{id:'input',kind:'Read',operation:'supplied_text',text:'Local input'}]}});}),other.evaluate(async()=>{const {authorDevelopmentAction}=await import('/src/browser/development-actions.ts');for(let i=0;i<10;i++)await authorDevelopmentAction('local',JSON.stringify({type:'open_view',view:'notes'}),new AbortController().signal);})]);
 expect(await page.evaluate(async()=>{const {readExecutionPart}=await import('/src/browser/development-execution-document.ts'),identity={namespace:'local'} as any,actions:any=await readExecutionPart(identity,'actions',()=>null),workflows:any=await readExecutionPart(identity,'workflows',()=>null);return {proposals:actions.proposals.length,workflows:workflows.workflows.length,receipts:workflows.receipts.length,legacy:Object.keys(localStorage).filter(k=>/^alpha.browser.(agent.actions|workflows)./.test(k))};})).toEqual({proposals:10,workflows:10,receipts:10,legacy:[]});
});
test('a failed action commit cannot erase already saved workflow state',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {editExecutionPart,developmentExecutionDocument}=await import('/src/browser/development-execution-document.ts'),{authorDevelopmentAction}=await import('/src/browser/development-actions.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),identity=developmentIdentity('local');await editExecutionPart(identity,'workflows',()=>({workflows:[],receipts:[],retained:'original'}),()=>{});const document=developmentExecutionDocument(identity),before=await document.capture(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.execution.local.v1')throw Error('Full');return put.call(this,value,key);};let rejected=false;try{await authorDevelopmentAction('local',JSON.stringify({type:'open_view',view:'notes'}),new AbortController().signal);}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}return {rejected,same:JSON.stringify(before.snapshot)===JSON.stringify((await document.capture()).snapshot)};})).toEqual({rejected:true,same:true});
});
test('both legacy parts retain their exact bytes and an older workflow edit refuses action access',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentExecutionDocument,readExecutionPart}=await import('/src/browser/development-execution-document.ts'),identity={namespace:'local'} as any,actions=' { "version": 1, "proposals": [], "journal": [] } ',workflows=' { "workflows": [], "receipts": [] } ';localStorage.setItem('alpha.browser.agent.actions.local.v1',actions);localStorage.setItem('alpha.browser.workflows.local.v1',workflows);await readExecutionPart(identity,'actions',()=>null);const document=developmentExecutionDocument(identity),before=await document.capture();localStorage.setItem('alpha.browser.workflows.local.v1','{changed');let rejected=false;try{await readExecutionPart(identity,'actions',()=>null);}catch{rejected=true;}return {exact:JSON.parse(before.raw!).actions===actions&&JSON.parse(before.raw!).workflows===workflows,rejected,changed:(await document.capture()).legacyChanged};})).toEqual({exact:true,rejected:true,changed:true});
});
test('retired owner can finish an existing receipt but cannot reserve or begin another action',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {selectDevelopmentCloud}=await import('/src/browser/development-cloud.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{authorDevelopmentAction,developmentJournal,developmentActionRequest}=await import('/src/browser/development-actions.ts'),{readExecutionPart}=await import('/src/browser/development-execution-document.ts'),signal=new AbortController().signal;await selectDevelopmentCloud('first',signal);localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'cloud'}));const identity=developmentIdentity('cloud'),proposalId=await authorDevelopmentAction('cloud',JSON.stringify({type:'open_view',view:'notes'}),signal),journal=developmentJournal('cloud',identity),state:any=await readExecutionPart(identity,'actions',()=>null),input={scope:'a'.repeat(64),proposalId,operationId:'retained',operationHash:state.proposals[0].digest,record:{digest:state.proposals[0].digest}};await journal.reserve(input as any);await developmentActionRequest('cloud',`/api/client-devices/proposals/${proposalId}/decision`,{digest:state.proposals[0].digest,decision:'approve'},signal,identity);const claimed:any=await developmentActionRequest('cloud',`/api/client-devices/proposals/${proposalId}/claim`,{digest:state.proposals[0].digest},signal,identity);await selectDevelopmentCloud('second',signal);let reserve=false,begin=false;try{await journal.reserve(input as any);}catch{reserve=true;}try{await journal.markApplying({scope:input.scope,proposalId,attemptId:claimed.proposal.execution.attemptId});}catch{begin=true;}await journal.finish({scope:input.scope,proposalId,status:'cancelled',summary:'Account retired'});return {reserve,begin,status:(await journal.get({scope:input.scope,proposalId})).entry?.status,other:await readExecutionPart({namespace:'cloud.second'} as any,'actions',()=>null)};})).toEqual({reserve:true,begin:true,status:'cancelled',other:null});
});
test('recovery cannot erase a concurrent journal or workflow edit',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentExecutionDocument,editExecutionPart,readExecutionPart}=await import('/src/browser/development-execution-document.ts'),identity={namespace:'local'} as any,document=developmentExecutionDocument(identity),before=await document.capture();await editExecutionPart(identity,'workflows',()=>({workflows:['Retained']}),()=>{});let rejected=false;try{await document.reset(before);}catch{rejected=true;}return {rejected,state:await readExecutionPart(identity,'workflows',()=>null)};})).toEqual({rejected:true,state:{workflows:['Retained']}});
});
test('execution recovery backs up damaged parts and resets workflows and proposals together',async({page})=>{
 await boot(page);await page.evaluate(()=>{localStorage.setItem('alpha.browser.agent.actions.local.v1','{damaged actions');localStorage.setItem('alpha.browser.workflows.local.v1',' {damaged workflows ');});await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Execution history recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Development execution recovery'});await expect(dialog.getByText(/does not undo effects/)).toBeVisible();const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download execution history backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual({actions:'{damaged actions',workflows:' {damaged workflows '});await dialog.getByRole('button',{name:'Reset app execution history',exact:true}).click();await dialog.getByRole('button',{name:'Confirm execution history reset',exact:true}).click();await expect(dialog).toHaveCount(0);
 expect(await page.evaluate(async()=>{const {readExecutionPart}=await import('/src/browser/development-execution-document.ts'),identity={namespace:'local'} as any;return {actions:await readExecutionPart(identity,'actions',()=>null),workflows:await readExecutionPart(identity,'workflows',()=>null),legacy:localStorage.getItem('alpha.browser.agent.actions.local.v1')};})).toEqual({actions:null,workflows:null,legacy:'{damaged actions'});
});
test('retiring a workflow during its configured reply read cannot commit a failed or completed run',async({page})=>{
 await boot(page);expect(await page.evaluate(async()=>{const {developmentWorkflowRequest:request}=await import('/src/browser/development-workflows.ts'),{developmentIdentity}=await import('/src/browser/development-identity.ts'),{developmentExecutionDocument}=await import('/src/browser/development-execution-document.ts'),{browserDocuments}=await import('/src/browser/documents.ts'),identity=developmentIdentity('local'),saved:any=await request(identity,'/api/workflow/phone/workflows',{catalogRevision:'development-v1',compilerRevision:'development-v1',mutationId:crypto.randomUUID(),spec:{version:1,name:'Read then retire',description:'',trigger:{kind:'manual'},steps:[{id:'input',kind:'Read',operation:'supplied_text',text:'Input'},{id:'model',kind:'Write',operation:'model_draft',source:'input',instruction:'Draft'}]}}),before=await developmentExecutionDocument(identity).capture(),read=browserDocuments.read.bind(browserDocuments);let release!:()=>void,queued!:()=>void;const waiting=new Promise<void>(resolve=>queued=resolve);browserDocuments.read=async(...args)=>{const value=await read(...args);if(args[0]==='alpha.browser.agent.local.v1'){queued();await new Promise<void>(resolve=>release=resolve);}return value;};const running=request(identity,`/api/workflow/workflows/${saved.receipt.workflowId}/run`,{submissionId:crypto.randomUUID(),expectedVersionId:saved.receipt.versionId}).then(()=>false,()=>true);await waiting;localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'development',profile:'remote'}));release();return {rejected:await running,same:JSON.stringify(before.snapshot)===JSON.stringify((await developmentExecutionDocument(identity).capture()).snapshot)};})).toEqual({rejected:true,same:true});
});
