import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('selection downloads exact archive bytes, moves together and confirms deletion',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');await f.importFile(new File(['Café\n'],'one.txt',{type:'text/plain'}));await f.importFile(new File(['two'],'two.txt',{type:'text/plain'}));await f.createFolder({id:'root',name:'Destination'});});
 await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByText('App files',{exact:true}).first().click();await page.getByRole('button',{name:'Select files',exact:true}).click();
 for(const name of ['one.txt','two.txt'])await page.getByRole('button',{name:'Select '+name,exact:true}).click();
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Share selected',exact:true}).click();const download=await downloaded;expect(download.suggestedFilename()).toBe('Alpha files.zip');const path=await download.path();const contents=JSON.parse(execFileSync('python3',['-c','import zipfile,json,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; print(json.dumps({n:z.read(n).decode() for n in z.namelist()}))',path!],{encoding:'utf8'}));expect(contents).toEqual({'one.txt':'Café\n','two.txt':'two'});
 await page.getByRole('button',{name:'Move selected',exact:true}).click();await page.getByRole('button',{name:'Move into Destination',exact:true}).click();await page.getByRole('button',{name:'Move here',exact:true}).click();await expect(page.getByRole('button',{name:'Open one.txt',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Open Destination',exact:true}).click();await expect(page.getByRole('button',{name:'Open one.txt',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Select files',exact:true}).click();await page.getByRole('button',{name:'Select all',exact:true}).click();await page.getByRole('button',{name:'Delete selected',exact:true}).click();await page.getByRole('button',{name:'Delete permanently',exact:true}).click();await expect(page.getByRole('button',{name:'Open one.txt',exact:true})).toHaveCount(0);await page.reload();expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles'),root=await f.list({});return (await f.list({id:root.entries[0].id})).entries;})).toEqual([]);
});
test('stale revisions, collisions and nonempty folders roll back the entire batch',async({page})=>{
 const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');await f.importFile(new File(['a'],'a.txt'));await f.importFile(new File(['b'],'b.txt'));await f.createFolder({id:'root',name:'Target'});let rows=(await f.list({})).entries;const target=rows.find((r:any)=>r.directory),files=rows.filter((r:any)=>!r.directory),items=files.map((r:any)=>({id:r.id,expectedRevision:r.revision}));await f.importFile(new File(['collision'],'b.txt'),target.id);const failures=[];for(const operation of [{action:'move',destinationId:target.id},{action:'delete',confirmPermanent:true,items:[items[0],{...items[1],expectedRevision:'stale'}]},{action:'delete',confirmPermanent:true,items:[items[0],{id:target.id,expectedRevision:target.revision}]}]){try{await f.changeMany({items,...operation});failures.push(false);}catch{failures.push(true);}}return {failures,names:(await f.list({})).entries.map((r:any)=>r.name).sort()};});expect(result).toEqual({failures:[true,true,true],names:['Target','a.txt','b.txt']});
});
test('folder sharing preserves nested Unicode paths and empty directories',async({page})=>{
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');const folder=await f.importDirectory([{path:'nested/café.txt',file:new File(['nested bytes'],'café.txt')}],'Bundle');await f.createFolder({id:folder.folder.id,name:'Empty'});});
 const downloading=page.waitForEvent('download');await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');const row=(await f.list({})).entries[0];await f.shareMany({items:[{id:row.id,expectedRevision:row.revision}]});});const path=await(await downloading).path();const contents=JSON.parse(execFileSync('python3',['-c','import zipfile,json,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; print(json.dumps({n:z.read(n).decode() for n in z.namelist()}))',path!],{encoding:'utf8'}));expect(contents).toEqual({'Bundle/':'','Bundle/nested/':'','Bundle/nested/café.txt':'nested bytes','Bundle/Empty/':''});
});
test('normalized dot paths cannot enter Files or downloaded archives',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {BrowserFiles}=await import('/src/browser/files.ts');const f=new BrowserFiles();const rejected=[];
  for(const name of ['. ',' ..',' .. ']){try{await f.createFolder({id:'root',name});rejected.push(false);}catch{rejected.push(true);}}
  const {fileArchive}=await import('/src/browser/file-archive.ts');const archiveRejected=[];
  for(const path of ['../escape.txt','folder/../escape.txt','/absolute.txt','C:/escape.txt','folder\\escape.txt','folder//file.txt']){try{fileArchive([{path,bytes:new Uint8Array([1])}]);archiveRejected.push(false);}catch{archiveRejected.push(true);}}
  return {rejected,archiveRejected,entries:(await f.list({})).entries.length};
 });expect(result).toEqual({rejected:[true,true,true],archiveRejected:Array(6).fill(true),entries:0});
});
