import {test,expect,type Page} from '@playwright/test';
const home=(page:Page)=>page.getByRole('region',{name:'Home',exact:true});
const tile=(page:Page)=>home(page).getByRole('button',{name:/Open workflows|Retry workflows|Connect agent for workflows/});
async function setup(page:Page,theme='light'){
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&workflows=agent&theme='+theme);
 await page.evaluate(async()=>{
  const f=(window as any).homeWorkflowFixture={listCalls:0,statusCalls:0,rows:[],hold:false,error:false,writeCalls:0};
  const {WorkflowProtocol:P}=await import('/src/runtime/workflow-protocol.ts');
  P.prototype.lifecycleSupported=async()=>{f.statusCalls++;return false;};
  P.prototype.list=async()=>{f.listCalls++;const rows=structuredClone(f.rows);if(f.hold)await new Promise<void>(resolve=>f.release=resolve);if(f.error)throw Error('Synthetic metadata outage');return rows;};
  P.prototype.detail=async id=>f.rows.find((row:any)=>row.id===id);P.prototype.executions=async()=>[];
  for(const method of ['activate','pause','run','lifecycle','updateMetadata'])(P.prototype as any)[method]=async()=>{f.writeCalls++;throw Error('Writes are not part of Home');};
 });
}
async function rows(page:Page,values:any[]){await page.evaluate(values=>{(window as any).homeWorkflowFixture.rows=values;},values);}
const flow=(id:string,name:string,active=true)=>({id,name,active,description:'',versionId:id+'-version',steps:[]});
async function connect(page:Page){await page.evaluate(async()=>{const {connectionController:c}=await import('/src/runtime/connection-ui.tsx');await c.initialize();await c.startDevelopment('local');});}
async function back(page:Page){await page.getByRole('button',{name:'Back to apps',exact:true}).click();}
for(const theme of ['light','dark'])test(`Home shows actual workflow names and states, then opens the existing list: ${theme}`,async({page},info)=>{
 await setup(page,theme);await rows(page,[flow('morning','Morning brief'),flow('stretch','Stretch reminder',false),flow('notes','Weekly notes'),{...flow('removed','Removed routine'),removed:true}]);await connect(page);await expect(tile(page)).toContainText('Morning brief');await expect(tile(page)).toContainText('Enabled');await expect(tile(page)).toContainText('Stretch reminder');await expect(tile(page)).toContainText('Paused');await expect(tile(page)).toContainText('+1 more');await expect(tile(page)).not.toContainText('Routines and automations');await expect(tile(page)).not.toContainText('Review');await expect(tile(page)).not.toContainText('Removed routine');await expect(tile(page).locator('[aria-hidden="true"]')).toHaveCSS('mask-image',/lucide\/workflow\.svg/);await expect.poll(()=>tile(page).evaluate(element=>{const icon=element.querySelector('[aria-hidden="true"]')!.getBoundingClientRect(),box=element.getBoundingClientRect();return Math.round(box.right-icon.right);})).toBe(22);
 await tile(page).evaluate(element=>element.scrollIntoView({behavior:'instant',block:'nearest',inline:'start'}));await expect(tile(page)).toBeInViewport({ratio:1});await page.screenshot({path:info.outputPath('home-workflows-'+theme+'.png'),animations:'disabled'});await tile(page).click();await expect(page.locator('html')).toHaveAttribute('data-active-view','workflows');await expect(page.getByRole('button',{name:'Morning brief Agent workflow',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).homeWorkflowFixture.writeCalls)).toBe(0);
});
test('zero workflows is honest and rerenders do not refetch metadata',async({page})=>{
 await setup(page);await connect(page);await expect(tile(page)).toContainText('No workflows yet');await expect(tile(page)).toContainText('Create a workflow');const calls=await page.evaluate(()=>(window as any).homeWorkflowFixture.listCalls);await page.getByRole('textbox',{name:'Ask Alpha',exact:true}).fill('Unsent draft');await expect(page.getByRole('textbox',{name:'Ask Alpha',exact:true})).toHaveValue('Unsent draft');expect(await page.evaluate(()=>(window as any).homeWorkflowFixture.listCalls)).toBe(calls);expect(calls).toBe(1);
});
test('returning Home refreshes changed names once using the same metadata list',async({page})=>{
 await setup(page);await rows(page,[flow('morning','Morning brief')]);await connect(page);await expect(tile(page)).toContainText('Morning brief');await tile(page).click();await expect(page.locator('html')).toHaveAttribute('data-active-view','workflows');await expect(page.getByRole('button',{name:'Morning brief Agent workflow',exact:true})).toBeVisible();await rows(page,[flow('morning','Morning update',false)]);const before=await page.evaluate(()=>(window as any).homeWorkflowFixture.listCalls);await back(page);await expect(tile(page)).toContainText('Morning update');await expect(tile(page)).toContainText('Paused');expect(await page.evaluate(()=>(window as any).homeWorkflowFixture.listCalls)).toBe(before+1);
});
test('loading and metadata failure offer a real retry without running anything',async({page})=>{
 await setup(page);await page.evaluate(()=>{(window as any).homeWorkflowFixture.hold=true;(window as any).homeWorkflowFixture.error=true;});await connect(page);await expect(tile(page)).toContainText('Loading workflows…');await expect.poll(()=>page.evaluate(()=>typeof(window as any).homeWorkflowFixture.release)).toBe('function');await page.evaluate(()=>(window as any).homeWorkflowFixture.release());await expect(tile(page)).toContainText('Couldn’t load workflows');await expect(tile(page)).toContainText('Tap to retry');await page.evaluate(()=>{const f=(window as any).homeWorkflowFixture;f.hold=false;f.error=false;f.rows=[{id:'ready',name:'Recovered routine',active:true,description:'',versionId:'v1',steps:[]}];});await tile(page).click();await expect(tile(page)).toContainText('Recovered routine');expect(await page.evaluate(()=>(window as any).homeWorkflowFixture.writeCalls)).toBe(0);
});
test('disconnect retires names and a late old-account result cannot refill Home',async({page})=>{
 await setup(page);await rows(page,[flow('private','First owner routine')]);await page.evaluate(()=>(window as any).homeWorkflowFixture.hold=true);await connect(page);await expect.poll(()=>page.evaluate(()=>typeof(window as any).homeWorkflowFixture.release)).toBe('function');await page.evaluate(async()=>{await(await import('/src/runtime/connection-ui.tsx')).connectionController.offline();});await expect(tile(page)).toContainText('Connect your agent');await page.evaluate(()=>{const f=(window as any).homeWorkflowFixture;f.release();f.hold=false;f.rows=[{id:'second',name:'Second owner routine',active:false,description:'',versionId:'v2',steps:[]}];});await connect(page);await expect(tile(page)).toContainText('Second owner routine');await expect(tile(page)).not.toContainText('First owner routine');
});
test('leaving foreground retires metadata and resumes through one fresh list',async({page})=>{
 await setup(page);await rows(page,[flow('morning','Morning brief')]);await connect(page);await expect(tile(page)).toContainText('Morning brief');const before=await page.evaluate(()=>(window as any).homeWorkflowFixture.listCalls);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete(document as any).hidden;document.dispatchEvent(new Event('visibilitychange'));});await expect(tile(page)).toContainText('Morning brief');expect(await page.evaluate(()=>(window as any).homeWorkflowFixture.listCalls)).toBe(before+1);
});
