import {test,expect} from '@playwright/test';
for(const creating of [false,true])for(const applied of [true,false])test(`host journal reminder recovery uses retained receipt: ${applied}, creation:${creating}`,async({page})=>{
 test.skip(process.env.VITE_LOCAL_AGENT!=='1','Requires the host storage bridge');await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2026-10-03T12:00:00Z'));await page.goto('/');
 const result=await page.evaluate(async ({applied,creating})=>{
  const {developmentActionJournal:j}=await import('/src/runtime/local-agent-storage.ts');const {actionScope,validateDeviceOperation}=await import('/src/runtime/device-actions.ts');const {DailyApps:d}=await import('/src/daily.ts');const scope=await actionScope(crypto.randomUUID()),proposalId='proposal',operationId=crypto.randomUUID();await d.scheduleReminder({id:'host-recovery',title:'Host recovery',at:Date.now()+3600000});const operation=validateDeviceOperation(creating?{type:'reminder_create' as const,fields:{title:'Canonical host creation',body:'Reviewed',schedule:{at:Date.now()+3600000,dueAt:Date.now()+3600000,alertMinutes:null,recurrence:null}}}:{type:'reminder_complete' as const,target:await d.selectedReminder({id:'host-recovery'})});const record={ownerId:'owner',agentId:'agent',sessionId:'session',origin:'https://development.alpha.invalid',installationId:'installation',enrollmentId:'enrollment',digest:'d'.repeat(64),operation};const operationHash=await actionScope(JSON.stringify(operation));await j.reserve({scope,proposalId,operationId,operationHash,record});await j.markApplying({scope,proposalId,attemptId:'attempt'});const original=(await j.get({scope,proposalId})).entry;const bindingHash=await actionScope(JSON.stringify([scope,record.ownerId,record.agentId,record.sessionId,record.origin,record.installationId,record.enrollmentId,proposalId,record.digest,operationId]));const receipt=applied?await d.operateReminder({operationId,bindingHash,operation}):undefined;await j.finish({scope,proposalId,status:'unknown',summary:'Lost response'});const before=(await (await import('/src/browser/reminder-store.ts')).reminderDocument.readRaw());let wrongBinding=false;try{await j.recoverReminder!({scope,proposalId,bindingHash:'0'.repeat(64)});}catch{wrongBinding=true;}
  let staleRejected=true;if(applied){const response=await fetch('/__alpha-local-agent',{method:'POST',headers:{'Content-Type':'application/json','X-Alpha-Local-Agent':'1'},body:JSON.stringify({storage:{operation:'recoverReminder',scope,proposalId,bindingHash,expectedEntry:original,reminderResult:receipt!.result}})});staleRejected=!response.ok;}
  const recovered=await j.recoverReminder!({scope,proposalId,bindingHash}),replay=await j.recoverReminder!({scope,proposalId,bindingHash});return {status:recovered.entry?.status,wrongBinding,staleRejected,same:JSON.stringify(recovered)===JSON.stringify(replay),unchanged:before===(await (await import('/src/browser/reminder-store.ts')).reminderDocument.readRaw()),scope};
 },{applied,creating});expect(result).toMatchObject({status:applied?'succeeded':'unknown',wrongBinding:true,staleRejected:true,same:true,unchanged:true});await page.reload();expect(await page.evaluate(async scope=>{const {developmentActionJournal:j}=await import('/src/runtime/local-agent-storage.ts');return (await j.get({scope,proposalId:'proposal'})).entry?.status;},result.scope)).toBe(applied?'succeeded':'unknown');
});
