import {test,expect,type Page} from '@playwright/test';
async function setup(page:Page){
 await page.goto('/');await page.evaluate(async()=>{
  const{connectionController:c}=await import('/src/runtime/connection-ui.tsx');const{secureConnectionStore:s}=await import('/src/runtime/native-connection.ts');s.read=async()=>null;s.compareExchange=async()=>({status:'saved'});
  const{reviewMailAttachment}=await import('/src/runtime/inbox-attachment.ts');const input={name:'mail-source.txt',mimeType:'text/plain',dataBase64:btoa('Reviewed attachment bytes. <script>not executed</script>')};const file={...input,...await reviewMailAttachment(input)};
  const f=(window as any).saveFixture={file,mutations:0};const message={id:'selected',threadId:'thread',from:'Fixture sender',to:['reader@example.test'],subject:'Source document',snippet:'Review source',receivedAt:'2026-10-04T12:00:00Z',unread:false};
  const client={gmailAccounts:async()=>[{connectionId:'fixture-grant',label:'Fixture mailbox',connected:true,grantedCapabilities:['google.gmail.triage']}],gmailInboxCapabilities:async()=>({send:false,providerDrafts:false,mailboxMutations:false}),gmailSearch:async()=>({messages:[message],syncedAt:'1'}),gmailRead:async()=>({message,bodyText:'Choose this document.',historyId:'1',attachments:[{partId:'part',name:file.name,mimeType:file.mimeType,size:file.size,supported:true}]}),gmailAttachment:async()=>f.file,gmailPrepareOperation:async()=>{f.mutations++;throw Error('No provider writes');}};c.getCloudClient=()=>({client,sessionId:'fixture-session'} as any);const snapshot={...c.getSnapshot(),cloudAccount:{environment:'production',userId:'fixture-owner',sessionId:'fixture-session',credentialId:'fixture'}} as any;c.getSnapshot=()=>snapshot;
 });
 await page.getByRole('button',{name:'Inbox',exact:true}).click();await page.getByText('Source document',{exact:true}).click();await page.getByText('mail-source.txt',{exact:true}).click();
}
async function entries(page:Page){return page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');return(await registerPlugin<any>('AlphaFiles').list({})).entries;});}
test('reviewed Gmail attachment saves exact bytes once and survives reload in Files',async({page})=>{
 await setup(page);expect(await entries(page)).toEqual([]);const review=page.getByRole('dialog',{name:'Review attachment'}),save=review.getByRole('button',{name:'Save to Files',exact:true});await save.click();await expect(review.getByRole('status')).toHaveText('Saved in Files. Exact bytes verified.');await expect(save).toBeDisabled();expect((await entries(page)).map((e:any)=>e.name)).toEqual(['mail-source.txt']);expect(await page.evaluate(()=>(window as any).saveFixture.mutations)).toBe(0);
 await page.reload();await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByText('App files',{exact:true}).first().click();await page.getByRole('button',{name:'Open mail-source.txt',exact:true}).click();await expect(page.getByText('Reviewed attachment bytes. <script>not executed</script>',{exact:true})).toBeVisible();expect((await entries(page)).length).toBe(1);
});
test('leaving attachment review aborts a held browser file read before storage',async({page})=>{
 await setup(page);await page.evaluate(()=>{const read=File.prototype.arrayBuffer,w=window as any;w.held={started:false,finished:false};File.prototype.arrayBuffer=async function(){w.held.started=true;await new Promise(resolve=>w.held.release=resolve);const result=await read.call(this);w.held.finished=true;return result;};});
 const review=page.getByRole('dialog',{name:'Review attachment'});await review.getByRole('button',{name:'Save to Files',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).held.started)).toBe(true);await review.getByRole('button',{name:'Back to message',exact:true}).click();await page.evaluate(()=>(window as any).held.release());await expect.poll(()=>page.evaluate(()=>(window as any).held.finished)).toBe(true);await expect(review).toHaveCount(0);expect(await entries(page)).toEqual([]);
});
test('filename collision leaves the old file and prevents an uncertain automatic retry',async({page})=>{
 await setup(page);await page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles');const selected=await f.importFile(new File(['Keep original'],'mail-source.txt',{type:'text/plain'}));await f.forgetSelected(selected);});
 const review=page.getByRole('dialog',{name:'Review attachment'});await review.getByRole('button',{name:'Save to Files',exact:true}).click();await expect(review.getByRole('status')).toContainText('Save not confirmed');await expect(review.getByRole('button',{name:'Save to Files',exact:true})).toBeDisabled();expect((await entries(page)).length).toBe(1);
 const text=await page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles'),row=(await f.list({})).entries[0],selected=await f.select({id:row.id});try{return atob((await f.attachment(selected)).dataBase64);}finally{await f.forgetSelected(selected);}});expect(text).toBe('Keep original');
});
test('mismatched attachment digest is rejected before any file write',async({page})=>{
 await setup(page);await page.evaluate(()=>(window as any).saveFixture.file.sha256='0'.repeat(64));const review=page.getByRole('dialog',{name:'Review attachment'});await review.getByRole('button',{name:'Save to Files',exact:true}).click();await expect(review.getByRole('status')).toContainText('Save not confirmed');expect(await entries(page)).toEqual([]);
});
