import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
async function open(page:any,mode='available'){
 await page.evaluate(async(mode)=>{
  Object.defineProperty(navigator,'userAgent',{configurable:true,value:'Supported desktop speech fixture'});const w=window as any;if(mode==='missing'){w.SpeechRecognition=undefined;w.webkitSpeechRecognition=undefined;}w.recognitionFixture={started:0,aborted:0,installed:0,local:false,track:null,engine:null,availability:mode,microphone:0};const f=w.recognitionFixture;
  Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{f.microphone++;throw Error('Saved transcription must not request microphone');}});
  if(mode!=='missing')w.SpeechRecognition=class{processLocally=false;lang='';continuous=false;interimResults=false;onstart:any;onresult:any;onerror:any;onend:any;static async available(input:any){if(input.processLocally!==true)throw Error('Must be local');return f.availability;}static async install(input:any){if(input.processLocally!==true)throw Error('Must be local');f.installed++;f.availability='available';return true;}start(track:any){f.started++;f.local=this.processLocally;f.track=track;f.engine=this;this.onstart?.();}abort(){f.aborted++;}};
  const rate=8000,buffer=new ArrayBuffer(44+rate*2),v=new DataView(buffer);const text=(at:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(at+i,s.charCodeAt(i));};text(0,'RIFF');v.setUint32(4,buffer.byteLength-8,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,buffer.byteLength-44,true);
  const {BrowserTranscriptReview}=await import('/src/browser/transcript-review.ts');w.review=new BrowserTranscriptReview();w.clipBlob=new Blob([buffer],{type:'audio/wav'});w.reviewResult=w.review.open(w.clipBlob).then((text:string)=>({text}),()=>({cancelled:true}));
 },mode);
}
test('local recognition consumes the saved track, requires review and releases resources',async({page},info)=>{
 await open(page);await page.getByRole('button',{name:'Transcribe recording',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).recognitionFixture.started)).toBe(1);
 await page.evaluate(()=>{const f=(window as any).recognitionFixture;f.engine.onresult({resultIndex:0,results:[Object.assign([{transcript:'Recognized locally'}],{isFinal:true})]});f.engine.onend();});await expect(page.getByRole('textbox',{name:'Transcript',exact:true})).toHaveValue('Recognized locally');await page.screenshot({path:info.outputPath('local-transcript.png')});await page.getByRole('textbox',{name:'Transcript',exact:true}).fill('Reviewed and corrected');await page.getByRole('button',{name:'Use transcript',exact:true}).click();const value=await page.evaluate(async()=>{const f=(window as any).recognitionFixture;return {result:await (window as any).reviewResult,local:f.local,mic:f.microphone,track:f.track.readyState};});expect(value).toEqual({result:{text:'Reviewed and corrected'},local:true,mic:0,track:'ended'});
});
test('language pack setup is explicit and late recognition cannot overwrite a manual edit',async({page})=>{
 await open(page,'downloadable');await page.getByRole('button',{name:'Transcribe recording',exact:true}).click();await expect(page.getByRole('button',{name:'Set up local transcription',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).recognitionFixture.installed)).toBe(0);await page.getByRole('button',{name:'Set up local transcription',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).recognitionFixture.started)).toBe(1);await page.evaluate(()=>{(window as any).lateResult=(window as any).recognitionFixture.engine.onresult;});await page.getByRole('textbox',{name:'Transcript',exact:true}).fill('Keep my edit');await page.evaluate(()=>(window as any).lateResult({resultIndex:0,results:[Object.assign([{transcript:'Late result'}],{isFinal:true})]}));await expect(page.getByRole('textbox',{name:'Transcript',exact:true})).toHaveValue('Keep my edit');expect(await page.evaluate(()=>(window as any).recognitionFixture.track.readyState)).toBe('ended');
});
test('missing local recognition preserves the manual path without starting a speech service',async({page})=>{
 await open(page,'missing');await expect(page.getByRole('button',{name:'Transcribe recording',exact:true})).toHaveCount(0);await page.getByRole('textbox',{name:'Transcript',exact:true}).fill('Manual transcript');await page.getByRole('button',{name:'Use transcript',exact:true}).click();expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({text:'Manual transcript'});expect(await page.evaluate(()=>(window as any).recognitionFixture.microphone)).toBe(0);
});
test('Back, replacement and device lifecycle retire a transcript and its recognition owner',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Transcribe recording',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).recognitionFixture.started)).toBe(1);await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({cancelled:true});expect(await page.evaluate(()=>(window as any).recognitionFixture.track.readyState)).toBe('ended');await expect(page.getByRole('dialog',{name:'Recording transcript'})).toHaveCount(0);
 await open(page);const replaced=await page.evaluate(async()=>{const w=window as any,previous=w.reviewResult;w.reviewResult=w.review.open(w.clipBlob).then((text:string)=>({text}),()=>({cancelled:true}));return previous;});expect(replaced).toEqual({cancelled:true});await page.evaluate(()=>window.dispatchEvent(new Event('alpha:device-state')));expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({cancelled:true});
});
test('opening review never queries speech availability; cancelling setup retires its late resolution',async({page})=>{
 await open(page);await page.evaluate(()=>{const w=window as any;w.queries=0;w.SpeechRecognition.available=()=>{w.queries++;return new Promise(resolve=>{w.resolveAvailability=resolve;});};});
 expect(await page.evaluate(()=>(window as any).queries)).toBe(0);await page.getByRole('button',{name:'Transcribe recording',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).queries)).toBe(1);
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>(window as any).resolveAvailability('available'));expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({cancelled:true});expect(await page.evaluate(()=>(window as any).recognitionFixture.started)).toBe(0);await expect(page.getByRole('dialog',{name:'Recording transcript'})).toHaveCount(0);
});
test('recognition errors preserve the reviewed text and release audio before manual completion',async({page})=>{
 await open(page);await page.getByRole('textbox',{name:'Transcript',exact:true}).fill('Retain this draft');await page.getByRole('button',{name:'Transcribe recording',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).recognitionFixture.started)).toBe(1);await page.evaluate(()=>(window as any).recognitionFixture.engine.onerror());await expect(page.getByRole('textbox',{name:'Transcript',exact:true})).toHaveValue('Retain this draft');expect(await page.evaluate(()=>(window as any).recognitionFixture.track.readyState)).toBe('ended');await page.getByRole('button',{name:'Use transcript',exact:true}).click();expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({text:'Retain this draft'});
});
test('a completing voice cancellation cannot close a replacement transcript',async({page})=>{
 await open(page,'missing');await page.evaluate(async()=>{const w=window as any;w.review.cancel();const {BrowserVoice}=await import('/src/browser/voice.ts');const voice=new BrowserVoice();const cancelling=voice.cancel();w.reviewResult=(voice as any).transcript.open(w.clipBlob).then((text:string)=>({text}),()=>({cancelled:true}));await cancelling;});
 await expect(page.getByRole('dialog',{name:'Recording transcript'})).toBeVisible();await page.getByRole('textbox',{name:'Transcript',exact:true}).fill('New review survives');await page.getByRole('button',{name:'Use transcript',exact:true}).click();expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({text:'New review survives'});
});

for(const theme of ['light','dark'])for(const height of [640,360])test(`transcript controls fit large text: ${theme} ${height}`,async({page},info)=>{
 await page.setViewportSize({width:360,height});await page.goto('/?mode=dev&theme='+theme);await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent:150});});await open(page,'missing');
 const dialog=page.getByRole('dialog',{name:'Recording transcript'}),field=dialog.getByRole('textbox',{name:'Transcript',exact:true}),use=dialog.getByRole('button',{name:'Use transcript',exact:true}),cancel=dialog.getByRole('button',{name:'Cancel',exact:true});await field.fill('Long content '.repeat(500));expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await expect(use).toBeInViewport();await expect(cancel).toBeInViewport();await expect(use).toHaveCSS('font-size','24px');await expect(use).toHaveCSS('color-scheme',theme);expect((await use.boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.screenshot({path:info.outputPath('transcript-compact.png')});await use.click();expect(await page.evaluate(()=>(window as any).reviewResult)).toEqual({text:'Long content '.repeat(500).trim()});
});
