import {test,expect} from '@playwright/test';
async function native(page:any){await page.addInitScript(()=>{const w=window as any;w.androidBridge={};w.nativeCalls=[];const names=['DailyApps','AlphaConnection','AlphaHostedResults'];const methods=['surfaceInfo','pauseNotificationCollection','disableBackground','readSecret','secureRead','secureWrite','secureRemove','addListener','removeListener'];w.Capacitor={Plugins:{},PluginHeaders:names.map(name=>({name,methods:methods.map(name=>({name,rtype:name==='addListener'?'callback':'promise'}))})),nativeCallback:()=> 'fixture',nativePromise:async(plugin:string,method:string)=>{w.nativeCalls.push([plugin,method]);if(method==='surfaceInfo')return {topInset:28,bottomInset:48};if(method==='secureRead'||method==='readSecret')return {value:null};return {};}};});}
const status='[data-screen]>div[style*="height: 44px"][style*="pointer-events: none"]';
test('Android mock uses only native system chrome and reserves the banner across views',async({page},testInfo)=>{
 await native(page);await page.goto('/?mode=mock');await expect(page.getByRole('textbox',{name:'Ask Alpha',exact:true})).toBeVisible();await expect(page.locator(status)).toHaveCount(0);await expect(page.getByRole('button',{name:'Home',exact:true})).toHaveCount(0);
 const geometry=await page.evaluate(()=>{const banner=document.querySelector('.mock-mode-banner')!.getBoundingClientRect();const screen=document.querySelector('[data-screen]')!.getBoundingClientRect();return {bannerTop:banner.top,bannerHeight:banner.height,screenTop:screen.top,bottom:getComputedStyle(document.documentElement).getPropertyValue('--native-bottom-inset'),calls:(window as any).nativeCalls};});expect(geometry.bannerTop).toBe(28);expect(geometry.screenTop).toBe(geometry.bannerHeight);expect(geometry.bottom).toBe('48px');expect(geometry.calls).toEqual(expect.arrayContaining([['AlphaConnection','pauseNotificationCollection'],['AlphaHostedResults','disableBackground']]));await page.screenshot({animations:'disabled',path:testInfo.outputPath('native-mock-home.png')});
 await page.getByRole('button',{name:'Calendar',exact:true}).click();await expect(page.locator(status)).toHaveCount(0);await expect(page.getByRole('button',{name:'Exit mock mode',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'New event',exact:true})).toBeVisible();expect((await page.getByRole('button',{name:'New event',exact:true}).boundingBox())!.y).toBeGreaterThanOrEqual(await page.locator('.mock-mode-banner').evaluate(el=>el.getBoundingClientRect().bottom));await page.screenshot({animations:'disabled',path:testInfo.outputPath('native-mock-calendar.png')});
 await page.setViewportSize({width:360,height:800});await expect.poll(()=>page.evaluate(()=>{const b=document.querySelector('.mock-mode-banner')!.getBoundingClientRect();return Math.abs(document.querySelector('[data-screen]')!.getBoundingClientRect().top-b.height);})).toBeLessThan(1);await page.getByRole('button',{name:'Exit mock mode',exact:true}).click();await expect(page.locator('.mock-mode-banner')).toHaveCount(0);await expect(page).not.toHaveURL(/mode=mock/);
});
test('browser mock retains reference system chrome and visible exit',async({page})=>{await page.goto('/?mode=mock');await expect(page.getByRole('textbox',{name:'Ask Alpha',exact:true})).toBeVisible();await expect(page.locator(status)).toHaveCount(1);await expect(page.getByRole('button',{name:'Home',exact:true})).toBeVisible();await page.getByRole('button',{name:'Exit mock mode',exact:true}).click();await expect(page.locator('.mock-mode-banner')).toHaveCount(0);await expect(page).not.toHaveURL(/mode=mock/);});

for(const android of [true,false])test((android?'Android':'browser')+' mock lock preserves only the appropriate system chrome',async({page},testInfo)=>{if(android)await native(page);await page.goto('/?mode=mock&start=lock');await expect(page.getByRole('button',{name:'Unlock with fingerprint',exact:true})).toBeVisible();await expect(page.locator(status)).toHaveCount(android?0:1);await expect(page.getByRole('button',{name:'Home',exact:true})).toHaveCount(android?0:1);await page.screenshot({animations:'disabled',path:testInfo.outputPath('mock-lock.png')});await page.getByRole('button',{name:'Unlock with fingerprint',exact:true}).click();await expect(page.getByRole('textbox',{name:'Ask Alpha',exact:true})).toBeVisible();});
