import {test,expect,type Page} from '@playwright/test';
const bytes=Buffer.from('Original source bytes.\nA fact for the summary.'),file={name:'source.txt',mimeType:'text/plain',buffer:bytes};
async function choose(page:Page,label:string,input=file){const picker=page.waitForEvent('filechooser');await page.getByRole('dialog',{name:'Note source document'}).getByRole('button',{name:label,exact:true}).click();await(await picker).setFiles(input);}
async function saved(page:Page){return page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.find((n:any)=>n.title==='Source-linked summary'));}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));});
for(const theme of ['light','dark'])test(`source fingerprint survives reload, rejects changed bytes and opens exact source ${theme}`,async({page},info)=>{
 await page.setViewportSize({width:360,height:640});await page.goto('/?theme='+theme);await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Source-linked summary');await page.getByRole('textbox',{name:'Note',exact:true}).fill('Reviewed summary text.');
 await page.getByRole('button',{name:'Link source document',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Note source document'});await choose(page,'Link file');await expect(dialog.getByRole('status')).toContainText('Source linked.');const record=await saved(page);expect(record.body).toBe('Reviewed summary text.');expect(record.documentSource).toEqual({version:1,name:'source.txt',mimeType:'text/plain',sha256:requireHash(bytes),size:bytes.length});expect(JSON.stringify(record)).not.toContain(bytes.toString());expect(JSON.stringify(record)).not.toMatch(/selectionId|blob:|dataBase64/);
 await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Source-linked summary',exact:true}).click();await page.getByRole('button',{name:'Source document linked',exact:true}).click();await choose(page,'Choose source file to open',{...file,buffer:Buffer.from('Changed source')});await expect(dialog.getByRole('status')).toContainText('does not match');await expect(page.getByRole('dialog',{name:'Reviewed attachment'})).toHaveCount(0);expect(await saved(page)).toEqual(record);
 await choose(page,'Choose source file to open',{...file,name:'renamed-source.txt'});const preview=page.getByRole('dialog',{name:'Reviewed attachment'});await expect(preview).toContainText(bytes.toString());await preview.getByRole('button',{name:'Done',exact:true}).click();await page.evaluate(async()=>{const{BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent:150});});await page.setViewportSize({width:740,height:360});await expect(dialog).toHaveCSS('color-scheme',theme);for(const button of await dialog.locator('footer button').all()){await expect(button).toBeInViewport();expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);}await page.screenshot({path:info.outputPath('linked-source.png')});await dialog.getByRole('button',{name:'Remove source link',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('file was not deleted');expect((await saved(page)).documentSource).toBeUndefined();expect((await saved(page)).body).toBe(record.body);
});
import {createHash} from 'node:crypto';const requireHash=(value:Buffer)=>createHash('sha256').update(value).digest('hex');
test('closing the source review rejects a delayed file read',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Source-linked summary');
 await page.evaluate(()=>{const read=File.prototype.arrayBuffer;const w=window as any;w.sourceFixture={reading:false};File.prototype.arrayBuffer=async function(){w.sourceFixture.reading=true;await new Promise(resolve=>w.sourceFixture.release=resolve);const value=await read.call(this);w.sourceFixture.finished=true;return value;};});
 await page.getByRole('button',{name:'Link source document',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Note source document'});await choose(page,'Link file');await expect.poll(()=>page.evaluate(()=>(window as any).sourceFixture.reading)).toBe(true);await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.evaluate(()=>(window as any).sourceFixture.release());await expect.poll(()=>page.evaluate(()=>(window as any).sourceFixture.finished)).toBe(true);await expect(dialog).toHaveCount(0);expect((await saved(page)).documentSource).toBeUndefined();
});

test('source metadata save failure retains the persisted note and reports uncertainty',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Source-linked summary');await page.getByRole('textbox',{name:'Note',exact:true}).fill('Retain this summary.');
 const before=await saved(page);
 await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='alphaphone:notes:v2')throw new DOMException('Storage full','QuotaExceededError');return original.call(this,key,value);};});
 await page.getByRole('button',{name:'Link source document',exact:true}).click();await choose(page,'Link file');const dialog=page.getByRole('dialog',{name:'Note source document'});await expect(dialog.getByRole('status')).toContainText('save is unconfirmed');expect(await saved(page)).toEqual(before);await expect(dialog.getByText('No source linked',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Source-linked summary',exact:true}).click();await expect(page.getByRole('textbox',{name:'Note',exact:true})).toHaveValue('Retain this summary.');await expect(page.getByRole('button',{name:'Link source document',exact:true})).toBeVisible();
});
