import {test,expect} from '@playwright/test';
test('retired renderer delayed delete cannot undo explicit restored note',async({page,context})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');
 await page.evaluate(async()=>{const {openBrowserNotes,DocumentNotesStore:NotesStore}=await import('/src/runtime/browser-notes-document.ts');const {retainAudio}=await import('/src/browser/note-audio-store.ts');const audio=await retainAudio('late-audio','late-note','Text',{blob:new Blob(['synthetic']),durationMs:1000});await (await openBrowserNotes()).replace([{id:'late-note',kind:'voice',title:'Late recording',body:'Text',audio,dur:1,lines:[],summary:[],actions:[]}]);});
 await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Late recording',exact:true}).click();
 await page.evaluate(async()=>{const {BrowserVoice}=await import('/src/browser/voice.ts');BrowserVoice.prototype.remove=async function(input:any){(window as any).delayed=input;return new Promise(()=>{});};});
 await page.getByRole('button',{name:'Delete note',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).delayed?.operationId)).toBeTruthy();const delayed=await page.evaluate(()=>(window as any).delayed);
 const next=await context.newPage();await page.close();await next.goto('/');await next.getByRole('button',{name:'Notes',exact:true}).click();await next.getByRole('button',{name:'Restore note and recording',exact:true}).click();await expect(next.getByRole('button',{name:'Open Late recording',exact:true})).toBeVisible();
 const result=await next.evaluate(async(input)=>{const {BrowserVoice}=await import('/src/browser/voice.ts');const audio=new BrowserVoice();return {receipt:await audio.remove(input),metadata:await audio.describe({audioId:input.audioId}),status:await audio.deletionStatus(input)};},delayed);
 expect(result.receipt).toEqual({...delayed,status:'restored'});expect(result.status).toEqual(result.receipt);expect(result.metadata.deletedAt).toBeUndefined();await expect(next.getByRole('button',{name:'Open Late recording',exact:true})).toBeVisible();await next.close();
});
test('bounded receipts reject new admission and old restoration cannot undo newer deletion',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {retainAudio,changeAudioDeleted,audioDeletionStatus,audioRecord}=await import('/src/browser/note-audio-store.ts');await retainAudio('bounded','owner','Text',{blob:new Blob(['audio']),durationMs:1000});const first=crypto.randomUUID(),second=crypto.randomUUID();await changeAudioDeleted('bounded','owner',true,first);await changeAudioDeleted('bounded','owner',false,first);await changeAudioDeleted('bounded','owner',true,second);await changeAudioDeleted('bounded','owner',false,first);const preserved=!!(await audioRecord('bounded',true)).deletedAt;await changeAudioDeleted('bounded','owner',false,second);for(let i=2;i<128;i++)await changeAudioDeleted('bounded','owner',false,crypto.randomUUID());let full=false,missing=false;try{await changeAudioDeleted('bounded','owner',true,crypto.randomUUID());}catch{full=true;}try{await changeAudioDeleted('bounded','owner',true,undefined as any);}catch{missing=true;}return {preserved,full,missing,old:await audioDeletionStatus('bounded','owner',first),active:!!(await audioRecord('bounded',true)).deletedAt};});expect(result).toMatchObject({preserved:true,full:true,missing:true,old:{status:'restored'},active:false});
});

test('expired recording clears bytes but preserves replay fence',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const api=await import('/src/browser/note-audio-store.ts');const operation=crypto.randomUUID();await api.retainAudio('expired-fenced','owner','Private transcript',{blob:new Blob(['audio']),durationMs:1000});await api.changeAudioDeleted('expired-fenced','owner',true,operation);const now=Date.now;Date.now=()=>now()+31*24*60*60*1000;try{await api.migrateAudio();const row=await api.audioRecord('expired-fenced',true);let restored=false;try{await api.changeAudioDeleted('expired-fenced','owner',false,operation);restored=true;}catch{}return {bytes:row.blob.size,transcript:row.transcript,restored,receipt:await api.audioDeletionStatus('expired-fenced','owner',operation)};}finally{Date.now=now;}});expect(result).toMatchObject({bytes:0,transcript:'',restored:false,receipt:{status:'removed'}});
});
