import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');});
async function seed(page:any){await page.evaluate(async()=>{
 const rate=8000,buffer=new ArrayBuffer(44+rate*2),v=new DataView(buffer);const text=(at:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(at+i,s.charCodeAt(i));};text(0,'RIFF');v.setUint32(4,buffer.byteLength-8,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,buffer.byteLength-44,true);
 const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('alpha.browser.audio.v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('audio',{keyPath:'audioId'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const tx=db.transaction('audio','readwrite');tx.objectStore('audio').put({audioId:'retained-audio',noteId:'owner-note',blob:new Blob([buffer],{type:'audio/wav'}),durationMs:1000});tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);});db.close();
 const {registerPlugin}=await import('/src/platform-plugins.ts');(window as any).noteAudio=registerPlugin<any>('AlphaNoteAudio');
 });}
test('legacy metadata migrates without exposing bytes; save replay updates transcript and rejects another owner',async({page})=>{
 await seed(page);const result=await page.evaluate(async()=>{const a=(window as any).noteAudio,status=await a.migrationStatus(),before=await a.describe({audioId:'retained-audio'});await a.saveRecording({recordingId:'retained-audio',noteId:'owner-note',transcript:'Updated transcript'});let rejected=false;try{await a.saveRecording({recordingId:'retained-audio',noteId:'wrong',transcript:'Overwrite'});}catch{rejected=true;}return {status,before,after:await a.describe({audioId:'retained-audio'}),rejected};});
 expect(result.status).toEqual({state:'complete',failedRecords:0});expect(result.before).toMatchObject({audioId:'retained-audio',noteId:'owner-note',durationMs:1000,mimeType:'audio/wav',transcript:''});expect(result.before.blob).toBeUndefined();expect(result.before.createdAt).toBeGreaterThan(0);expect(result.after.transcript).toBe('Updated transcript');expect(result.rejected).toBe(true);await page.reload();expect(await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('AlphaNoteAudio').describe({audioId:'retained-audio'})).transcript;})).toBe('Updated transcript');
});
test('trash verifies ownership, rejects playback and save, survives reload and restores without replacing bytes',async({page})=>{
 await seed(page);const deleted=await page.evaluate(async()=>{const a=(window as any).noteAudio;let wrong=false;try{await a.remove({audioId:'retained-audio',noteId:'wrong'});}catch{wrong=true;}await a.remove({audioId:'retained-audio',noteId:'owner-note'});const record=await a.describe({audioId:'retained-audio'});let play=false,save=false;try{await a.play({audioId:'retained-audio'});}catch{play=true;}try{await a.saveRecording({recordingId:'retained-audio',noteId:'owner-note',transcript:'Hidden'});}catch{save=true;}return {wrong,play,save,deletedAt:record.deletedAt};});expect(deleted).toMatchObject({wrong:true,play:true,save:true});expect(deleted.deletedAt).toBeGreaterThan(0);
 await page.reload();const restored=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const a=registerPlugin<any>('AlphaNoteAudio');let wrong=false;try{await a.restore({audioId:'retained-audio',noteId:'wrong'});}catch{wrong=true;}await a.restore({audioId:'retained-audio',noteId:'owner-note'});return {wrong,record:await a.describe({audioId:'retained-audio'})};});expect(restored.wrong).toBe(true);expect(restored.record.deletedAt).toBeUndefined();expect(restored.record.durationMs).toBe(1000);
});
test('failed trash commit rolls back; expired trash is purged and malformed legacy rows are retained for recovery',async({page})=>{
 await seed(page);const result=await page.evaluate(async()=>{const a=(window as any).noteAudio,put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:any[]){const r=put.apply(this,args as any);if(this.name==='audio')this.transaction.abort();return r;};let failed=false;try{await a.remove({audioId:'retained-audio',noteId:'owner-note'});}catch{failed=true;}finally{IDBObjectStore.prototype.put=put;}const untouched=await a.describe({audioId:'retained-audio'});
 const db=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('alpha.browser.audio.v1');r.onsuccess=()=>resolve(r.result);});await new Promise<void>(resolve=>{const tx=db.transaction('audio','readwrite'),s=tx.objectStore('audio'),r=s.get('retained-audio');r.onsuccess=()=>s.put({...r.result,deletedAt:Date.now()-31*86400000});s.put({audioId:'broken',noteId:'owner-note'});tx.oncomplete=()=>resolve();});const status=await a.migrationStatus();const keys=await new Promise<any>(resolve=>{const r=db.transaction('audio').objectStore('audio').getAllKeys();r.onsuccess=()=>resolve(r.result);});db.close();return {failed,untouched,status,keys};});expect(result.failed).toBe(true);expect(result.untouched.deletedAt).toBeUndefined();expect(result.status).toEqual({state:'needs-recovery',failedRecords:1});expect(result.keys).toEqual(['broken']);
});
test('saved playback emits native started and ended events; deletion in another tab stops current playback',async({page,context})=>{
 await seed(page);await page.evaluate(async()=>{const a=(window as any).noteAudio,w=window as any;w.audioEvents=[];for(const name of ['started','ended','failed'])await a.addListener(name,(value:any)=>w.audioEvents.push({name,...value}));const b=document.createElement('button');b.textContent='Play audio contract';b.style.cssText='position:fixed;top:0;z-index:99999';b.onclick=()=>{w.playing=a.play({audioId:'retained-audio'});};document.body.append(b);});await page.getByRole('button',{name:'Play audio contract'}).click();await page.evaluate(()=>(window as any).playing);await expect.poll(()=>page.evaluate(()=>(window as any).audioEvents.map((e:any)=>e.name))).toEqual(['started','ended']);
 const other=await context.newPage();await other.goto('/');await page.getByRole('button',{name:'Play audio contract'}).click();await page.evaluate(()=>(window as any).playing);await other.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaNoteAudio').remove({audioId:'retained-audio',noteId:'owner-note'});});await expect.poll(()=>page.evaluate(async()=>(await (window as any).noteAudio.state()).playing)).toBe(false);expect(await page.evaluate(()=>(window as any).audioEvents.map((e:any)=>e.name))).toEqual(['started','ended','started']);await other.close();
});
