import {test,expect} from '@playwright/test';
for(const mode of ['legacy','empty-history','other-owner','expired','failed-commit'] as const)test(`explicit legacy voice recording restore: ${mode}`,async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');
 await page.evaluate(async()=>{const {NotesStore}=await import('/src/runtime/notes-store.ts');const {retainAudio}=await import('/src/browser/note-audio-store.ts');const audio=await retainAudio('legacy-audio','legacy-note','Keep text',{blob:new Blob(['synthetic']),durationMs:1000});new NotesStore(localStorage,[]).replace([{id:'legacy-note',kind:'voice',title:'Legacy recording',body:'Keep text',audio,dur:1,lines:[],summary:[],actions:[]}]);});
 await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Legacy recording',exact:true}).click();
 await page.evaluate(async mode=>{const {BrowserVoice}=await import('/src/browser/voice.ts');BrowserVoice.prototype.remove=async function(input){(window as any).legacyInput=input;await new Promise<void>((resolve,reject)=>{const open=indexedDB.open('alpha.browser.audio.v1');open.onsuccess=()=>{const db=open.result,tx=db.transaction('audio','readwrite'),store=tx.objectStore('audio'),get=store.get(input.audioId);get.onsuccess=()=>{const row=get.result;row.deletedAt=Date.now()-(mode==='expired'?31*86400000:0);delete row.deletionOperations;delete row.activeDeletionOperation;if(mode==='empty-history')row.deletionOperations={};if(mode==='other-owner')row.activeDeletionOperation=crypto.randomUUID();store.put(row);};tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>reject(tx.error);};});throw Error('Legacy delete response lost');};},mode);
 await page.getByRole('button',{name:'Delete note',exact:true}).click();await expect(page.getByRole('button',{name:'Restore note and recording',exact:true})).toBeVisible();
 const input=await page.evaluate(()=>(window as any).legacyInput);await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();
 if(mode==='failed-commit')await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(value?.deletionOperations&&Object.values(value.deletionOperations).includes('restored'))throw new DOMException('Full','QuotaExceededError');return put.call(this,value,...args);};});
 await page.getByRole('button',{name:'Restore note and recording',exact:true}).click();
 if(mode==='legacy'){await expect(page.getByRole('button',{name:'Open Legacy recording',exact:true})).toBeVisible();const result=await page.evaluate(async input=>{const {BrowserVoice}=await import('/src/browser/voice.ts');const voice=new BrowserVoice();return {late:await voice.remove(input),metadata:await voice.describe({audioId:input.audioId})};},input);expect(result.late.status).toBe('restored');expect(result.metadata.deletedAt).toBeUndefined();}
 else{await expect(page.getByText('Restore is unconfirmed. Reopen Notes and check deletion status. No newer note was replaced.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.length)).toBe(0);await expect(page.getByRole('button',{name:'Restore note and recording',exact:true})).toBeVisible();}
});
