import {test,expect,type Page} from '@playwright/test';
async function boot(page:Page,legacy?:{key:string;raw:string}){await page.addInitScript(legacy=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(legacy&&!sessionStorage.getItem('notification-seeded')){localStorage.setItem(legacy.key,legacy.raw);sessionStorage.setItem('notification-seeded','1');}},legacy);await page.goto('/?mode=dev');}
test('policy reads retain authority and document revision without writing a legacy mirror',async({page})=>{
 await boot(page);const result=await page.evaluate(async()=>{const {notificationState,notificationDocument}=await import('/src/browser/notification-store.ts');const first=await notificationState(),before=await notificationDocument.capture();await notificationState();await notificationState();const after=await notificationDocument.capture();return {stable:before.snapshot?.revision===after.snapshot?.revision,authority:first.revision===(await notificationState()).revision,legacy:localStorage.getItem('alpha.browser.notifications.v2')};});expect(result).toEqual({stable:true,authority:true,legacy:null});
});
test('simultaneous device events retain every source and matching history entry',async({page,context})=>{
 await boot(page);await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const n=registerPlugin<any>('AlphaNotifications');await n.setNotificationPolicy({expectedRevision:(await n.crossAppStatus()).revision,enabled:true,history:true,apps:[{packageName:'browser.mail',preview:true}]});});
 const other=await context.newPage();await other.goto('/?mode=dev');await Promise.all([page,other].map((tab,index)=>tab.evaluate(async index=>{const {registerPlugin}=await import('/src/platform-plugins.ts'),n=registerPlugin<any>('AlphaNotifications');for(let i=0;i<10;i++)await n.inject({packageName:'browser.mail',title:`Event ${index}-${i}`,text:'Retained',id:`event-${index}-${i}`});},index)));
 const result=await page.evaluate(async()=>{const {notificationState}=await import('/src/browser/notification-store.ts');const state=await notificationState();return {sources:state.deviceEvents.map(row=>row.sourceKey),history:state.events.length};});expect(new Set(result.sources).size).toBe(20);expect(result.history).toBe(20);
});
for(const key of ['alpha.browser.notification-policy.v1','alpha.browser.notifications.v2'])test(`imports exact ${key} bytes and refuses changed older data`,async({page})=>{
 const raw='{ "appEnabled": false, "channels": { "reminders": false } }';await boot(page,{key,raw});const result=await page.evaluate(async({key,raw})=>{const {notificationState,notificationDocument}=await import('/src/browser/notification-store.ts'),state=await notificationState(),before=await notificationDocument.capture();localStorage.setItem(key,'{changed old policy');let refused=false;try{await notificationState();}catch{refused=true;}const after=await notificationDocument.capture();return {disabled:!state.appEnabled&&!state.channels.reminders,exact:JSON.parse(before.snapshot!.raw!).legacy===raw,refused,retained:before.raw===after.raw,older:after.legacy};},{key,raw});expect(result).toEqual({disabled:true,exact:true,refused:true,retained:true,older:'{changed old policy'});
});
test('stale recovery cannot erase a newer policy and reset cannot reimport collection consent',async({page})=>{
 await boot(page);const result=await page.evaluate(async()=>{const {notificationState,notificationDocument}=await import('/src/browser/notification-store.ts');await notificationState();const before=await notificationDocument.capture();await notificationDocument.edit(state=>{state.enabled=true;state.apps=[{packageName:'browser.mail',preview:true}];});let rejected=false;try{await notificationDocument.reset(before);}catch{rejected=true;}const retained=(await notificationState()).enabled;await notificationDocument.reset(await notificationDocument.capture());const reset=await notificationState();return {rejected,retained,enabled:reset.enabled,apps:reset.apps};});expect(result).toEqual({rejected:true,retained:true,enabled:false,apps:[]});
});
test('damaged policy downloads its original bytes before an explicit recovery reset',async({page})=>{
 const raw='{damaged notification policy';await boot(page,{key:'alpha.browser.notifications.v2',raw});await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Notification recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Browser notification recovery'});
 const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download notifications backup',exact:true}).click();const download=await pending,stream=await download.createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe(raw);
 await dialog.getByRole('button',{name:'Reset browser notifications',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.notifications.v2'))).toBe(raw);await dialog.getByRole('button',{name:'Confirm notifications reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>{const {notificationState}=await import('/src/browser/notification-store.ts');return (await notificationState()).enabled;})).toBe(false);
});
