import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
for(const event of ['launcher-home','alpha-back','alpha:device-state','alpha:dev-incoming-call'])test(`pending password settings cannot open after ${event}`,async({page})=>{
 await page.evaluate(async()=>{const {passwordProviderDocument:store}=await import('/src/browser/preference-documents.ts'),{openPasswordProvider}=await import('/src/browser/password-provider.ts'),read=store.read.bind(store);store.read=async(...args)=>{const result=await read(...args);(window as any).providerReadQueued=true;await new Promise<void>(resolve=>(window as any).releaseProviderRead=resolve);return result;};(window as any).providerOpening=openPasswordProvider('install').then(()=>true,()=>false);});
 await expect.poll(()=>page.evaluate(()=>(window as any).providerReadQueued)).toBe(true);expect(await page.evaluate(async event=>{window.dispatchEvent(new Event(event,{cancelable:true}));(window as any).releaseProviderRead();return (window as any).providerOpening;},event)).toBe(false);await expect(page.getByRole('dialog',{name:'Development password provider'})).toHaveCount(0);
});
test('sample fill cannot restore retired vault content after an awaited read',async({page})=>{
 await page.evaluate(async()=>{const {passwordProviderDocument:store}=await import('/src/browser/preference-documents.ts'),{openPasswordProvider}=await import('/src/browser/password-provider.ts');await store.edit(()=>({installed:true,selection:'proton',revision:'test'}),()=>{});await openPasswordProvider('open');});
 await page.getByRole('button',{name:'Unlock development vault',exact:true}).click();
 await page.evaluate(async()=>{const {passwordProviderDocument:store}=await import('/src/browser/preference-documents.ts'),read=store.read.bind(store);store.read=async(...args)=>{const result=await read(...args);(window as any).providerReadQueued=true;await new Promise<void>(resolve=>(window as any).releaseProviderRead=resolve);return result;};});
 await page.getByRole('button',{name:'Fill sample sign-in',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).providerReadQueued)).toBe(true);await page.evaluate(()=>{window.dispatchEvent(new Event('launcher-home'));(window as any).releaseProviderRead();});await expect(page.getByLabel('Sample sign-in')).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Development password provider'})).toHaveCount(0);
});
test('provider recovery retains damaged bytes and resets installation only after confirmation',async({page})=>{
 await page.evaluate(()=>localStorage.setItem('alpha.browser.password-provider.v1','{damaged provider'));
 await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Password provider recovery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Development password provider recovery'});
 const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download password provider backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(Buffer.concat(chunks).toString()).toBe('{damaged provider');
 await dialog.getByRole('button',{name:'Reset browser password provider',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('alpha.browser.password-provider.v1'))).toBe('{damaged provider');await dialog.getByRole('button',{name:'Confirm password provider reset',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await page.evaluate(async()=>(await import('/src/browser/password-provider.ts')).passwordProviderStatus())).toEqual({installation:'absent',selection:'none',support:'available'});
});
