import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');
 await page.evaluate(async()=>{const {importBrowserPhoto}=await import('/src/prototype/browser-camera.ts');const canvas=document.createElement('canvas');canvas.width=100;canvas.height=80;canvas.getContext('2d')!.fillRect(0,0,100,80);const image=canvas.toDataURL('image/jpeg');const row=await importBrowserPhoto({original:new File([],'fixture.jpg'),image,width:100,height:80},new AbortController().signal);(window as any).albumPhoto=row;});
});
test('visible Photos album journey creates with selected media, renames, removes, adds and deletes without deleting the photo',async({page})=>{
 test.setTimeout(60000);await page.getByRole('button',{name:'Photos',exact:true}).click();await page.getByRole('button',{name:/Captured photo/}).click();await page.getByRole('button',{name:'Photo info',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Album management'});await dialog.getByRole('button',{name:'Add to album',exact:true}).click();await dialog.getByRole('button',{name:'New album',exact:true}).click();await dialog.getByRole('textbox',{name:'Album name',exact:true}).fill('Trip');await dialog.getByRole('button',{name:'Save album',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('button',{name:'Back from photo',exact:true}).click();await page.getByRole('button',{name:'Albums',exact:true}).click();await page.getByRole('button',{name:'Trip',exact:true}).click();await expect(page.getByRole('button',{name:/Captured photo/})).toHaveCount(1);
 await page.getByRole('button',{name:'Manage album',exact:true}).click();dialog=page.getByRole('dialog',{name:'Album management'});await dialog.getByRole('textbox',{name:'Album name',exact:true}).fill('Journey');await dialog.getByRole('button',{name:'Save album',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.reload();await page.getByRole('button',{name:'Photos',exact:true}).click();await page.getByRole('button',{name:'Albums',exact:true}).click();await page.getByRole('button',{name:'Journey',exact:true}).click();await page.getByRole('button',{name:/Captured photo/}).click();await page.getByRole('button',{name:'Photo info',exact:true}).click();dialog=page.getByRole('dialog',{name:'Album management'});await dialog.getByRole('button',{name:'Add to album',exact:true}).click();await dialog.getByRole('button',{name:'Remove from Journey',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('button',{name:'Photo info',exact:true}).click();dialog=page.getByRole('dialog',{name:'Album management'});await dialog.getByRole('button',{name:'Add to album',exact:true}).click();await dialog.getByRole('button',{name:'Add to Journey',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('button',{name:'Back from photo',exact:true}).click();await expect(page.getByRole('button',{name:/Captured photo/})).toHaveCount(1);await page.getByRole('button',{name:'Manage album',exact:true}).click();dialog=page.getByRole('dialog',{name:'Album management'});await dialog.getByRole('button',{name:'Delete album',exact:true}).click();await dialog.getByRole('button',{name:'Confirm delete album',exact:true}).click();await expect(dialog).toHaveCount(0);
 const result=await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return {albums:(await p.albums()).items.length,photos:(await p.list()).items.length};});expect(result).toEqual({albums:0,photos:1});
});
test('album counts and contents follow trash, restore and permanent deletion',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');const row=(window as any).albumPhoto,a=await p.changeAlbum({operation:'create',name:'Kept',mediaId:row.id,mediaRevision:row.mutationRevision});
  const count=async()=>({count:(await p.albums()).items[0].count,rows:(await p.list({album:'custom:'+a.id})).items.length});const initial=await count();const trashed=await p.setTrashed({id:row.id,revision:row.mutationRevision,trashed:true}),hidden=await count();const restored=await p.setTrashed({id:row.id,revision:trashed.mutationRevision,trashed:false}),visible=await count();await p.setTrashed({id:row.id,revision:restored.mutationRevision,trashed:true});await p.deletePreparedTrash(await p.prepareDeleteTrash());return {initial,hidden,visible,deleted:await count()};
 });expect(result).toEqual({initial:{count:1,rows:1},hidden:{count:0,rows:0},visible:{count:1,rows:1},deleted:{count:0,rows:0}});
});
test('invalid operations, stale album revisions and stale create selections cannot mutate membership',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');const row=(window as any).albumPhoto,a=await p.changeAlbum({operation:'create',name:'Original',mediaId:row.id,mediaRevision:row.mutationRevision});const failures:string[]=[];
  for(const request of [{operation:'erase',...a,mediaId:row.id,mediaRevision:row.mutationRevision},{operation:'rename',...a,name:' '},{operation:'rename',...a,name:'x'.repeat(81)}]){try{await p.changeAlbum(request);}catch{failures.push('rejected');}}
  const renamed=await p.changeAlbum({operation:'rename',id:a.id,revision:a.revision,name:'Renamed'});try{await p.changeAlbum({operation:'remove',id:a.id,revision:a.revision,mediaId:row.id,mediaRevision:row.mutationRevision});}catch{failures.push('stale album');}
  await p.setFavorite({id:row.id,revision:row.mutationRevision,favorite:true});try{await p.changeAlbum({operation:'create',name:'Stale',mediaId:row.id,mediaRevision:row.mutationRevision});}catch{failures.push('stale photo');}
  const albums=(await p.albums()).items;return {failures,albums:albums.map(a=>({name:a.name,count:a.count})),rows:(await p.list({album:'custom:'+renamed.id})).items.length};
 });expect(result).toEqual({failures:['rejected','rejected','rejected','stale album','stale photo'],albums:[{name:'Renamed',count:1}],rows:1});
});
