import {readFileSync} from 'node:fs';
import {test,expect} from '@playwright/test';
const native=readFileSync('android/app/src/main/java/ai/elizaresearch/alphaphone/BrowserReading.java','utf8').split('static final String EXTRACT = """')[1].split('""";')[0].replaceAll('\\\\','\\');
const cases=[['api-key','<article>API key: SYNTHETIC-ONLY</article>'],['access-token','<article>Access token: SYNTHETIC-ONLY</article>'],['refresh-token','<article>refresh_token: SYNTHETIC-ONLY</article>'],['vault','<article><h1>Password vault</h1><div>SYNTHETIC-ONLY</div></article>'],['otp','<main><span>Verification</span><span>code</span><div>001122</div></main>'],['recovery','<aside>Account recovery codes TEST-ONLY</aside><article>Garden journal</article>'],['hidden-field','<input type="password" hidden><article>Garden journal</article>'],['normalized','<article>Ｐａｓｓｗｏｒｄ: synthetic</article>'],['split-zero-width','<article>pass\u200Bword: synthetic</article>'],['bare-code','<article>001122</article>']]as const;
for(const [kind,body]of cases)test(`browser and native extraction refuse credential prose: ${kind}`,async({page,context})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');const url='https://public-fixture.test/article';await page.route(url,r=>r.fulfill({contentType:'text/html',headers:{'access-control-allow-origin':'*'},body}));
 await page.evaluate(async url=>{const {BrowserVoice}=await import('/src/browser/voice.ts');(window as any).speechCalls=[];BrowserVoice.prototype.synthesizeLocal=async function(input){(window as any).speechCalls.push(input.text);throw Error('No playback in fixture');};const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');const controller=new AbortController();void reviewBrowserReading(url,controller.signal,()=>controller.signal.throwIfAborted());},url);
 await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials or verification codes');await expect(page.getByRole('textbox',{name:'Excerpt to read'})).toHaveValue('');await expect(page.getByRole('textbox',{name:'Excerpt to read'})).toBeDisabled();await expect(page.getByRole('button',{name:'Read locally',exact:true})).toBeDisabled();expect(await page.evaluate(()=>(window as any).speechCalls)).toEqual([]);
 const document=await context.newPage();await document.setContent(body);expect(await document.evaluate(script=>(0,eval)(script),native)).toEqual({blocked:true});await document.close();
});
test('manual credential paste is refused before speech, normal article still reads',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');await page.route('https://public-fixture.test/**',r=>r.fulfill({contentType:'text/plain',headers:{'access-control-allow-origin':'*'},body:'A garden journal from 2027.'}));
 await page.evaluate(async()=>{const {BrowserVoice}=await import('/src/browser/voice.ts');(window as any).speechCalls=[];BrowserVoice.prototype.synthesizeLocal=async function(input){(window as any).speechCalls.push(input.text);throw Error('Fixture terminal');};const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');(window as any).openReading=()=>{const c=new AbortController();void reviewBrowserReading('https://public-fixture.test/article',c.signal,()=>c.signal.throwIfAborted());};(window as any).openReading();});
 const field=page.getByRole('textbox',{name:'Excerpt to read'});await expect(field).toHaveValue('A garden journal from 2027.');await page.getByRole('button',{name:'Read locally',exact:true}).click();await expect(page.getByRole('status',{name:'Reading status'})).toHaveText('Fixture terminal');expect(await page.evaluate(()=>(window as any).speechCalls)).toEqual(['A garden journal from 2027.']);await page.getByRole('button',{name:'Close',exact:true}).click();await page.evaluate(()=>(window as any).openReading());await expect(field).toHaveValue('A garden journal from 2027.');await field.fill('My recovery code TEST-ONLY');await page.getByRole('button',{name:'Read locally',exact:true}).click();await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials');expect(await page.evaluate(()=>(window as any).speechCalls)).toHaveLength(1);
});
test('a late refused document cannot be bypassed by editing while extraction is pending',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');let release!:()=>void;const gate=new Promise<void>(r=>release=r);await page.route('https://public-fixture.test/article',async r=>{await gate;await r.fulfill({contentType:'text/html',headers:{'access-control-allow-origin':'*'},body:'<article>Account recovery codes: TEST-ONLY</article>'});});await page.evaluate(async()=>{const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');const c=new AbortController();void reviewBrowserReading('https://public-fixture.test/article',c.signal,()=>c.signal.throwIfAborted());});await page.getByRole('textbox',{name:'Excerpt to read'}).fill('Edited text');await expect(page.getByRole('button',{name:'Read locally',exact:true})).toBeDisabled();release();await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials');await expect(page.getByRole('textbox',{name:'Excerpt to read'})).toHaveValue('');
});
for(const url of ['https://pass.proton.me/','https://example.com/%70assword','https://example.com/#/vault'])test(`sensitive address refuses reading before fetch: ${url}`,async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');let fetched=0;await page.route(url.split('#')[0],r=>{fetched++;return r.abort();});await page.evaluate(async url=>{const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');const c=new AbortController();void reviewBrowserReading(url,c.signal,()=>c.signal.throwIfAborted());},url);await expect(page.getByRole('button',{name:'Read locally',exact:true})).toBeDisabled();await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials');expect(fetched).toBe(0);});
for(const control of ['textarea','div contenteditable="true"','div role="textbox"'])test(`interactive content is excluded from browser and native reading: ${control}`,async({page})=>{
 await page.goto('/');const tag=control.split(' ')[0];const body=`<article><${control}>ABCD-EFGH-IJKL</${tag}><p>Garden journal</p></article>`;
 await page.route('https://public-fixture.test/article',r=>r.fulfill({contentType:'text/html',body}));
 const extracted=await page.evaluate(async()=>{const {browserReadingSource}=await import('/src/browser/reading-source.ts');return browserReadingSource('https://public-fixture.test/article',new AbortController().signal);});expect(extracted).toEqual({text:'Garden journal',truncated:false});
 await page.setContent(body);const result=await page.evaluate(script=>(0,eval)(script),native);expect(result.text).toBe('Garden journal');expect(JSON.stringify(result)).not.toContain('ABCD-EFGH-IJKL');
});
for(const declared of [true,false])test(`oversized ${declared?'declared':'streamed'} source blocks an edited pending excerpt`,async({page})=>{
 await page.goto('/');await page.evaluate(async declared=>{const original=window.fetch;let release!:()=>void;(window as any).releaseSource=()=>release();const gate=new Promise<void>(r=>release=r);window.fetch=async(input,init)=>{if(String(input)!=='https://public-fixture.test/article')return original(input,init);await gate;return new Response('x'.repeat(262145),{headers:{'content-type':'text/html',...(declared?{'content-length':'262145'}:{})}});};const {BrowserVoice}=await import('/src/browser/voice.ts');(window as any).speechCalls=[];BrowserVoice.prototype.synthesizeLocal=async function(input){(window as any).speechCalls.push(input.text);throw Error('No playback');};const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');const c=new AbortController();void reviewBrowserReading('https://public-fixture.test/article',c.signal,()=>c.signal.throwIfAborted());},declared);
 await page.getByRole('textbox',{name:'Excerpt to read'}).fill('Edited pending excerpt');await expect(page.getByRole('button',{name:'Read locally',exact:true})).toBeDisabled();await page.evaluate(()=>(window as any).releaseSource());await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials');await expect(page.getByRole('textbox',{name:'Excerpt to read'})).toHaveValue('');expect(await page.evaluate(()=>(window as any).speechCalls)).toEqual([]);
});

for(const key of ['api_key','api-key','api%20key','apikey','%61pi%5fkey','API+KEY'])test(`API key URL refuses source fetch and speech: ${key}`,async({page})=>{
 await page.goto('/');const url=`https://public-fixture.test/article?${key}=SYNTHETIC-ONLY`;
 await page.evaluate(async url=>{const original=window.fetch;(window as any).sourceFetches=[];(window as any).speechCalls=[];window.fetch=async(input,init)=>{if(String(input).includes('public-fixture.test')){(window as any).sourceFetches.push(String(input));return new Response('Garden journal',{headers:{'content-type':'text/plain'}});}return original(input,init);};const {BrowserVoice}=await import('/src/browser/voice.ts');BrowserVoice.prototype.synthesizeLocal=async function(input){(window as any).speechCalls.push(input.text);throw Error('No playback');};const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');const c=new AbortController();void reviewBrowserReading(url,c.signal,()=>c.signal.throwIfAborted());},url);
 await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials');await expect(page.getByRole('button',{name:'Read locally',exact:true})).toBeDisabled();expect(await page.evaluate(()=>(window as any).sourceFetches)).toEqual([]);expect(await page.evaluate(()=>(window as any).speechCalls)).toEqual([]);
});
