import {createServer} from 'node:http';
import {test,expect,type Page} from '@playwright/test';
const address='https://reading.test/article';
async function open(page:Page,url=address){await page.evaluate(async(url)=>{const {reviewBrowserReading}=await import('/src/browser/reading-review.ts');const w=window as any;w.readAbort=new AbortController();w.readDone=reviewBrowserReading(url,w.readAbort.signal,()=>w.readAbort.signal.throwIfAborted());},url);}
const field=(page:Page)=>page.getByRole('textbox',{name:'Excerpt to read'});
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
test('public HTML becomes inert reviewed article text without credentials or resource requests',async({page,context})=>{
 await context.addCookies([{name:'private',value:'do-not-send',domain:'reading.test',path:'/',secure:true,sameSite:'None'}]);const requests:string[]=[];page.on('request',r=>{if(r.url().includes('reading.test'))requests.push(r.url());});let cookie:string|undefined;
 await page.route(address,route=>{cookie=route.request().headers().cookie;return route.fulfill({contentType:'text/html',headers:{'access-control-allow-origin':'*'},body:'<nav>Site navigation</nav><article><h1>Article title</h1><p>Public &amp; readable.</p><p hidden>Hidden</p><span style="display:none">Secret</span><script>window.injected=true</script><img src="https://reading.test/tracker"><iframe src="https://reading.test/frame"></iframe><p>Second paragraph.</p></article><footer>Footer</footer>'});});
 await open(page);await expect(field(page)).toHaveValue('Article title\n\nPublic & readable.\n\nSecond paragraph.');expect(cookie).toBeUndefined();expect(requests).toEqual([address]);expect(await page.evaluate(()=>(window as any).injected)).toBeUndefined();await expect(page.getByRole('status',{name:'Reading status'})).toHaveText('Public page text loaded. Review before reading.');
});
for(const kind of ['binary','large'])test(`unreadable ${kind} source follows bounded review policy`,async({page})=>{await page.route(address,route=>route.fulfill({contentType:kind==='binary'?'application/pdf':'text/html',headers:{'access-control-allow-origin':'*'},body:kind==='large'?'x'.repeat(262145):'<p>Do not extract</p>'}));await open(page);if(kind==='large'){await expect(page.getByRole('status',{name:'Reading status'})).toContainText('may contain credentials');await expect(field(page)).toBeDisabled();return;}await expect(page.getByRole('status',{name:'Reading status'})).toContainText('Paste up to');await expect(field(page)).toHaveValue('');await field(page).fill('My excerpt');await expect(field(page)).toHaveValue('My excerpt');});
test('long readable text is explicitly bounded for review',async({page})=>{await page.route(address,route=>route.fulfill({contentType:'text/plain',headers:{'access-control-allow-origin':'*'},body:'a'.repeat(6000)}));await open(page);await expect(field(page)).toHaveValue('a'.repeat(5000));await expect(page.getByRole('status',{name:'Reading status'})).toContainText('First 5,000');});
test('late extraction cannot overwrite user edits',async({page})=>{let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);await page.route(address,async route=>{await gate;await route.fulfill({contentType:'text/plain',headers:{'access-control-allow-origin':'*'},body:'Late article'});});await open(page);await field(page).fill('My edited excerpt');const response=page.waitForResponse(address);release();await response;await expect(field(page)).toHaveValue('My edited excerpt');});
test('closing extraction aborts work and cannot reopen the review',async({page})=>{let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);await page.route(address,async route=>{await gate;await route.fulfill({contentType:'text/plain',headers:{'access-control-allow-origin':'*'},body:'Late article'}).catch(()=>{});});await open(page);await page.getByRole('button',{name:'Close',exact:true}).click();release();await page.evaluate(()=>(window as any).readDone);await expect(page.getByRole('dialog',{name:'Read page excerpt'})).toHaveCount(0);});

test('actual cross-origin server without CORS leaves paste usable',async({page})=>{const server=createServer((_request,response)=>{response.setHeader('Content-Type','text/html');response.end('<p>Not available across origins</p>');});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));try{const address=server.address();if(!address||typeof address==='string')throw Error('Missing server address');await open(page,`http://127.0.0.1:${address.port}/article`);await expect(page.getByRole('status',{name:'Reading status'})).toContainText('Paste up to');await expect(field(page)).toHaveValue('');await field(page).fill('Reviewed paste');await expect(field(page)).toHaveValue('Reviewed paste');}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}});

test('streamed sources enforce the byte limit and reject invalid UTF-8',async({page})=>{
 const result=await page.evaluate(async()=>{const {browserReadingSource}=await import('/src/browser/reading-source.ts');const original=window.fetch;let cancelled=0;const values=[];try{for(const bytes of [new Uint8Array(262145).fill(97),new Uint8Array([0xff])]){window.fetch=async()=>new Response(new ReadableStream({start(controller){controller.enqueue(bytes);},cancel(){cancelled++;}}),{headers:{'Content-Type':'text/plain'}});values.push(await browserReadingSource('https://reading.test/article',new AbortController().signal));}return {values,cancelled};}finally{window.fetch=original;}});
 expect(result.values).toEqual([{blocked:true},undefined]);expect(result.cancelled).toBe(2);
});
test('a source timeout leaves manual review available',async({page})=>{
 await page.route(address,()=>new Promise(()=>{}));await open(page);await expect(page.getByRole('status',{name:'Reading status'})).toContainText('Paste up to',{timeout:8000});await field(page).fill('My reviewed excerpt');await expect(field(page)).toHaveValue('My reviewed excerpt');
});

test('an actual redirect is not followed and leaves manual review available',async({page})=>{
 const requests:string[]=[];const server=createServer((request,response)=>{requests.push(request.url||'');response.setHeader('Access-Control-Allow-Origin','*');if(request.url==='/article'){response.writeHead(302,{Location:'/redirected'});response.end();}else{response.setHeader('Content-Type','text/plain');response.end('Must not load');}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const address=server.address();if(!address||typeof address==='string')throw Error('Missing server address');await open(page,`http://127.0.0.1:${address.port}/article`);await expect(page.getByRole('status',{name:'Reading status'})).toContainText('Paste up to');expect(requests).toEqual(['/article']);await expect(field(page)).toHaveValue('');await field(page).fill('Reviewed excerpt');await expect(field(page)).toHaveValue('Reviewed excerpt');}
 finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
