import {test,expect} from '@playwright/test';
test.use({timezoneId:'UTC'});
for(const alert of ['10 min','None'])test(`one-time reminder preserves reviewed alert ${alert} after reload`,async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));
 await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');
 await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'New event',exact:true}).click();
 await page.getByRole('textbox',{name:'Title',exact:true}).fill('One-time lead fixture');
 await page.getByRole('button',{name:'Reminders',exact:true}).click();await page.getByRole('button',{name:alert,exact:true}).click();
 await expect(page.getByText('1:00 AM',{exact:true}).first()).toBeVisible();
 await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);
 const row=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.reminders.v1')!).reminders[0]);
 await test.info().attach('saved-row.json',{body:JSON.stringify(row,null,2),contentType:'application/json'});
 expect(row.at).toBe(Date.parse(alert==='10 min'?'2027-03-13T00:50Z':'2027-03-13T01:00Z'));
 await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:/^One-time lead fixture,/}).click();
 if(alert==='10 min'){await expect(page.getByText('10 min before',{exact:true})).toBeVisible();expect(row.dueAt).toBe(Date.parse('2027-03-13T01:00Z'));}
 else await expect(page.getByText('Alert at start',{exact:true})).toHaveCount(0);
});
async function create(page:any,alert='None',repeat=false){
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Timing flow');await page.getByRole('button',{name:'Reminders',exact:true}).click();await page.getByRole('button',{name:alert,exact:true}).click();if(repeat)await page.getByRole('button',{name:'Daily',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:/^Timing flow,/}).click();
}
const row=(page:any)=>page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.reminders.v1')!).reminders[0]);
for(const repeat of [false,true])test(`no-alert metadata and completion preserve notification absence repeat=${repeat}`,async({page})=>{
 await create(page,'None',repeat);const before=await row(page);expect(before).toMatchObject({status:'pending',mode:'none',alertMinutes:null,dueAt:Date.parse('2027-03-13T01:00Z')});await expect(page.getByRole('button',{name:'Snooze reminder 10 minutes'})).toHaveCount(0);
 await page.getByRole('button',{name:'Edit event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Metadata only');await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);expect(await row(page)).toMatchObject({status:'pending',alertMinutes:null,at:before.at,dueAt:before.dueAt,occurrenceId:before.occurrenceId});
 await page.getByRole('button',{name:'Complete reminder occurrence',exact:true}).click();await expect.poll(async()=> (await row(page)).history?.length).toBe(1);const after=await row(page);expect(after.status).toBe(repeat?'pending':'completed');if(repeat){expect(after.occurrenceId).not.toBe(before.occurrenceId);expect(after.dueAt).toBe(Date.parse('2027-03-14T01:00Z'));expect(after.at).toBe(after.dueAt);}
 await page.clock.setFixedTime(new Date('2027-03-16T00:00Z'));const saved=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');return (await registerPlugin<any>('DailyApps').listReminders()).reminders[0];});expect(saved.status).toBe(repeat?'pending':'completed');expect(saved).not.toHaveProperty('postedAt');
});
test('numeric lead survives snooze, selected read and metadata edit',async({page})=>{
 await create(page,'10 min');const before=await row(page);await page.getByRole('button',{name:'Snooze reminder 10 minutes',exact:true}).click();await expect.poll(async()=> (await row(page)).snoozedAt).toBe(Date.parse('2027-03-13T00:00Z'));
 const read=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const {validateReminderResult}=await import('/src/runtime/reminder-contract.ts');const d=registerPlugin<any>('DailyApps'),r=(await d.listReminders()).reminders[0],op={type:'reminder_read_selected',target:r.target};const response=await d.operateReminder({operationId:crypto.randomUUID(),bindingHash:'a'.repeat(64),operation:op});return validateReminderResult(op,response.result);});expect(read.at).toBe(Date.parse('2027-03-13T00:10Z'));expect(read.fields.schedule).toMatchObject({at:before.at,dueAt:before.dueAt,alertMinutes:10});
 await page.getByRole('button',{name:'Edit event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Snoozed metadata');await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);expect(await row(page)).toMatchObject({at:read.at,dueAt:before.dueAt,alertMinutes:10,occurrenceId:before.occurrenceId});
});
test('no-alert edit enables only explicitly reviewed numeric alert',async({page})=>{
 await create(page);const before=await row(page);await page.getByRole('button',{name:'Edit event',exact:true}).click();await page.getByRole('button',{name:'10 min',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);const after=await row(page);expect(after).toMatchObject({status:'scheduled',mode:'inexact',alertMinutes:10,dueAt:before.dueAt,at:before.dueAt-600000});expect(after.occurrenceId).not.toBe(before.occurrenceId);
});
for(const loss of ['creation','edit'])test(`no-alert ${loss} lost response recovers without replay`,async({page})=>{
 if(loss==='edit')await create(page,'10 min');else{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');await page.getByRole('button',{name:'Calendar',exact:true}).click();}
 await page.evaluate(async loss=>{const {BrowserDaily}=await import('/src/browser/daily.ts');(window as any).dispatches=0;const method=loss==='creation'?'scheduleReminder':'operateReminder',original=BrowserDaily.prototype[method];BrowserDaily.prototype[method]=async function(input){(window as any).dispatches++;await original.call(this,input);throw Error('Synthetic response loss');};},loss);
 await page.getByRole('button',{name:loss==='edit'?'Edit event':'New event',exact:true}).click();if(loss==='creation'){await page.getByRole('textbox',{name:'Title',exact:true}).fill('Lost no-alert');await page.getByRole('button',{name:'Reminders',exact:true}).click();}await page.getByRole('button',{name:'None',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByRole('button',{name:'Save event',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).dispatches)).toBe(1);expect(await row(page)).toMatchObject({status:'pending',alertMinutes:null});const saved=await row(page);await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();expect(await row(page)).toEqual(saved);
});
test('legacy receipt stays unchanged; v2 downgrade, omitted marker and no-alert snooze refuse',async({page})=>{
 await create(page);const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('DailyApps'),current=(await d.listReminders()).reminders[0],before=localStorage.getItem('alpha.browser.reminders.v1');let rejected=0;const target={...current.target};delete target.timingVersion;
 for(const action of [()=>d.scheduleReminder({id:current.id,title:'Downgrade',at:current.at}),()=>d.operateReminder({operationId:crypto.randomUUID(),bindingHash:'b'.repeat(64),operation:{type:'reminder_update',target:current.target,fields:{title:'Downgrade',body:'',schedule:{at:current.at,recurrence:null}}}}),()=>d.operateReminder({operationId:crypto.randomUUID(),bindingHash:'b'.repeat(64),operation:{type:'reminder_complete',target}}),()=>d.reminderDecision({id:current.id,occurrenceId:current.occurrenceId,action:'snooze'})])try{await action();}catch{rejected++;}
 const preserved=localStorage.getItem('alpha.browser.reminders.v1')===before;await d.scheduleReminder({id:'legacy',title:'Legacy',at:Date.parse('2027-03-13T03:00Z')});const legacy=(await d.listReminders()).reminders.find(r=>r.id==='legacy'),operation={type:'reminder_read_selected',target:legacy.target},input={operationId:'legacy-read',bindingHash:'c'.repeat(64),operation};const receipt=await d.operateReminder(input),again=await d.reminderOperationReceipt(input);return {rejected,preserved,legacy,receipt,again};});expect(result.rejected).toBe(4);expect(result.preserved).toBe(true);expect(result.legacy).not.toHaveProperty('alertMinutes');expect(result.legacy.target).not.toHaveProperty('timingVersion');expect(result.receipt).toEqual(result.again);expect(result.receipt.result).not.toHaveProperty('alertMinutes');
});
test('negotiated peer and selected context marker gate every v2 proposal',async({page})=>{
 await create(page);const result=await page.evaluate(async()=>{
  const {DeviceActions}=await import('/src/runtime/device-actions.ts'),{registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('DailyApps'),r=(await d.listReminders()).reminders[0],t=r.target;
  const session={ownerId:'owner',agentId:'agent',sessionId:'session',origin:'https://agent.example'},credential={installationId:'installation',key:'a'.repeat(64),enrollmentId:'enrollment'},context={view:'calendar',sensitive:false,revision:1,selectedObject:{kind:'reminder',id:r.id,revision:t.revision,accountId:t.sourceId,sourceRevision:t.sourceRevision,occurrenceId:t.occurrenceId,timingVersion:2}};
  let operation:any={type:'reminder_read_selected',target:t};const request=async()=>({proposals:[{id:'proposal',digest:'b'.repeat(64),state:'pending',expiresAt:new Date(Date.now()+60000).toISOString(),subjectUserId:'owner',requestedBy:'agent',action:'device_action',payload:{action:'device_action',version:1,installationId:'installation',enrollmentId:'enrollment',operation}}]});let effects=0;const execute=async()=>{effects++;return {status:'unknown',summary:'No effect'};};const signal=new AbortController().signal;let refused=false;try{await new DeviceActions(session,credential,'scope',request,{} as any,execute,undefined,false).pending(context,signal);}catch{refused=true;}
  const supported=new DeviceActions(session,credential,'scope',request,{} as any,execute,undefined,true),accepted=await supported.pending(context,signal);const stale={...context,selectedObject:{...context.selectedObject}};delete stale.selectedObject.timingVersion;const staleCount=(await supported.pending(stale,signal)).length;operation={...operation,target:{...t}};delete operation.target.timingVersion;const strippedCount=(await supported.pending(context,signal)).length;return {refused,accepted:accepted.length,staleCount,strippedCount,effects};
 });expect(result).toEqual({refused:true,accepted:1,staleCount:0,strippedCount:0,effects:0});
});
test('partial and inconsistent explicit timing cannot create records',async({page})=>{
 await create(page);const results=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('DailyApps');const before=localStorage.getItem('alpha.browser.reminders.v1');let refused=0;
 for(const timing of [{dueAt:Date.parse('2027-03-13T04:00Z')},{alertMinutes:null},{dueAt:Date.parse('2027-03-13T04:00Z'),alertMinutes:10},{dueAt:Date.parse('2027-03-13T04:00Z'),alertMinutes:-1}])try{await d.scheduleReminder({id:'invalid',title:'Invalid',at:Date.parse('2027-03-13T04:00Z'),...timing});}catch{refused++;}return {refused,unchanged:localStorage.getItem('alpha.browser.reminders.v1')===before};});expect(results).toEqual({refused:4,unchanged:true});
});
test('uncertain no-alert edit receipt stays pending through reload and never dispatches twice',async({page})=>{
 await create(page,'10 min');await page.evaluate(async()=>{const {BrowserDaily}=await import('/src/browser/daily.ts');const original=BrowserDaily.prototype.operateReminder;(window as any).dispatches=0;BrowserDaily.prototype.operateReminder=async function(input){(window as any).dispatches++;await original.call(this,input);throw Error('Synthetic lost response');};BrowserDaily.prototype.reminderOperationReceipt=async()=>{throw Error('Synthetic receipt unavailable');};});
 await page.getByRole('button',{name:'Edit event',exact:true}).click();await page.getByRole('button',{name:'None',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByText('Reminder edit is unconfirmed. Check action status in Calendar; it will not be repeated.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save event',exact:true}).click();expect(await page.evaluate(()=>(window as any).dispatches)).toBe(1);expect(await row(page)).toMatchObject({status:'pending',alertMinutes:null});expect(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('alpha.browser.reminder-deletions.v1')!)).length)).toBe(1);const saved=await row(page);await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('alpha.browser.reminder-deletions.v1')!)).length)).toBe(0);expect(await row(page)).toEqual(saved);
});
test('no-alert creation refuses a provider readback claiming active notification',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.evaluate(async()=>{const {BrowserDaily}=await import('/src/browser/daily.ts');const list=BrowserDaily.prototype.listReminders;BrowserDaily.prototype.listReminders=async function(){const out=await list.call(this);return {...out,reminders:out.reminders.map(r=>({...r,status:'scheduled',mode:'inexact'}))};};});await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Readback mismatch');await page.getByRole('button',{name:'Reminders',exact:true}).click();await page.getByRole('button',{name:'None',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByText('Reminder creation is unconfirmed. Check new reminder status in Calendar; it will not be created again automatically.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save event',exact:true})).toBeVisible();expect(await row(page)).toMatchObject({status:'pending',mode:'none'});
});
test('forged v2 marker on legacy target cannot mutate or mint a receipt',async({page})=>{
 await create(page);const result=await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const d=registerPlugin<any>('DailyApps');await d.scheduleReminder({id:'legacy-marker',title:'Original legacy',at:Date.parse('2027-03-13T03:00Z')});const target=await d.selectedReminder({id:'legacy-marker'}),before=localStorage.getItem('alpha.browser.reminders.v1');let rejected=0;
 for(const type of ['reminder_read_selected','reminder_update','reminder_complete'])try{await d.operateReminder({operationId:crypto.randomUUID(),bindingHash:'d'.repeat(64),operation:{type,target:{...target,timingVersion:2},...(type==='reminder_update'?{fields:{title:'Forged replacement',body:''}}:{})}});}catch{rejected++;}return {rejected,unchanged:localStorage.getItem('alpha.browser.reminders.v1')===before};});expect(result).toEqual({rejected:3,unchanged:true});
});
for(const version of ['missing','malformed','error'])test(`older native timing support ${version} refuses before persistence or dispatch`,async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');await page.getByRole('button',{name:'Calendar',exact:true}).click();
 await page.evaluate(async mode=>{const {BrowserDaily}=await import('/src/browser/daily.ts');(window as any).timingDispatches=0;BrowserDaily.prototype.surfaceInfo=async()=>{if(mode==='error')throw Error('Unavailable');return {developmentBuild:true,assistant:false,...(mode==='malformed'?{reminderTimingVersion:'2'}:{})} as any;};BrowserDaily.prototype.scheduleReminder=async()=>{(window as any).timingDispatches++;throw Error('Must not dispatch');};},version);
 await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Old native refusal');await page.getByRole('button',{name:'Reminders',exact:true}).click();await page.getByRole('button',{name:'None',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect(page.getByText('Update Alpha to save reminders with this alert setting. Nothing was saved.',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>(window as any).timingDispatches)).toBe(0);expect(await page.evaluate(async()=>Object.keys(await (await import('/src/runtime/reminder-creations.ts')).reminderCreations()).length)).toBe(0);await expect(page.getByRole('button',{name:'Save event',exact:true})).toBeVisible();
});
test('late native timing admission cannot dispatch after draft navigation',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.clock.setFixedTime(new Date('2027-03-13T00:00Z'));await page.goto('/');await page.getByRole('button',{name:'Calendar',exact:true}).click();
 await page.evaluate(async()=>{const {BrowserDaily}=await import('/src/browser/daily.ts');(window as any).timingDispatches=0;BrowserDaily.prototype.surfaceInfo=async()=>new Promise(resolve=>{(window as any).releaseTiming=()=>resolve({developmentBuild:true,assistant:false,reminderTimingVersion:2});});BrowserDaily.prototype.scheduleReminder=async()=>{(window as any).timingDispatches++;throw Error('Must not dispatch');};});
 await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Late admission');await page.getByRole('button',{name:'Reminders',exact:true}).click();await page.getByRole('button',{name:'Save event',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseTiming)).toBe('function');await page.getByRole('button',{name:'Back to calendar',exact:true}).last().click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.evaluate(()=>(window as any).releaseTiming());
 expect(await page.evaluate(()=>(window as any).timingDispatches)).toBe(0);expect(await page.evaluate(async()=>Object.keys(await (await import('/src/runtime/reminder-creations.ts')).reminderCreations()).length)).toBe(0);
});
