import {test,expect} from '@playwright/test';
const key='alpha.browser.reminder-deletions.v1';
const target={sourceId:'browser',sourceRevision:'b'.repeat(64),reminderId:'saved',occurrenceId:'occurrence',revision:'c'.repeat(64)};
const row={operationId:'retained',bindingHash:'a'.repeat(64),operation:{type:'reminder_cancel' as const,target}};
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/');});
test('independent tabs retain every reminder action kind without replay',async({page,context})=>{
 const other=await context.newPage();await other.goto('/');
 await Promise.all([page,other].map((tab,index)=>tab.evaluate(async({index,target})=>{const {retainReminderDeletion}=await import('/src/runtime/reminder-deletions.ts');for(const type of ['reminder_cancel','reminder_complete','reminder_snooze','reminder_update'] as const){await retainReminderDeletion({operationId:`tab-${index}-${type}`,bindingHash:'a'.repeat(64),operation:type==='reminder_update'?{type,target,fields:{title:'Reviewed edit',body:''}}:{type,target}});}},{index,target})));
 await page.reload();expect(await page.evaluate(async key=>{const history=await import('/src/runtime/reminder-deletions.ts'),{BrowserDaily}=await import('/src/browser/daily.ts');return {count:Object.keys(await history.pendingReminderDeletions()).length,scheduled:(await new BrowserDaily().listReminders()).reminders.length,legacy:localStorage.getItem(key)};},key)).toEqual({count:8,scheduled:0,legacy:null});
});
test('failed removal and stale acknowledgement preserve exact pending action',async({page})=>{
 expect(await page.evaluate(async({key,row})=>{const history=await import('/src/runtime/reminder-deletions.ts');await history.retainReminderDeletion(row);const put=IDBObjectStore.prototype.put;let failed=false,stale=false;IDBObjectStore.prototype.put=function(v,k){if(k===key)throw Error('Full');return put.call(this,v,k);};try{await history.discardUndispatchedReminderDeletion(row);}catch{failed=true;}finally{IDBObjectStore.prototype.put=put;}try{await history.discardUndispatchedReminderDeletion({...row,bindingHash:'d'.repeat(64)});}catch{stale=true;}return {failed,stale,retained:JSON.stringify((await history.pendingReminderDeletions())[row.operationId])===JSON.stringify(row)};},{key,row})).toEqual({failed:true,stale:true,retained:true});
});
test('native action history still uses secure expected-value exchange',async({page})=>{
 expect(await page.evaluate(async row=>{const Capacitor=(window as any).Capacitor,{secureConnectionStore}=await import('/src/runtime/native-connection.ts'),history=await import('/src/runtime/reminder-deletions.ts');const platform=Capacitor.getPlatform,read=secureConnectionStore.read,exchange=secureConnectionStore.compareExchange;let saved:any=null;const slots:string[]=[];let conflict=false,rejected=false;Capacitor.getPlatform=()=> 'android';secureConnectionStore.read=async()=>structuredClone(saved);secureConnectionStore.compareExchange=async(slot,expected,value)=>{slots.push(slot);if(conflict||JSON.stringify(expected)!==JSON.stringify(saved))return {status:'conflict'};saved=structuredClone(value);return {status:'saved'};};try{await history.retainReminderDeletion(row);conflict=true;try{await history.discardUndispatchedReminderDeletion(row);}catch{rejected=true;}return {rejected,pending:Object.keys(await history.pendingReminderDeletions()),slots};}finally{Capacitor.getPlatform=platform;secureConnectionStore.read=read;secureConnectionStore.compareExchange=exchange;}},row)).toEqual({rejected:true,pending:['retained'],slots:['reminder-deletions:v1:device','reminder-deletions:v1:device']});
});
test('unreadable action history has an exact backup and explicit reset',async({page},testInfo)=>{
 await page.evaluate(key=>localStorage.setItem(key,' {broken action history '),key);await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'Recover browser reminder action history',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Browser reminder action recovery'});
 await expect(dialog).toContainText('may already have changed a reminder');await expect(dialog).toContainText('does not undo, repeat or cancel reminder actions');await page.screenshot({path:testInfo.outputPath('reminder-action-recovery.png')});
 const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download reminder action history backup',exact:true}).click();const stream=await (await pending).createReadStream(),chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual({raw:' {broken action history '});
 await dialog.getByRole('button',{name:'Reset app reminder action history',exact:true}).click();await dialog.getByRole('button',{name:'Confirm reminder action history reset',exact:true}).click();await expect(dialog).toHaveCount(0);
 expect(await page.evaluate(async key=>{const history=await import('/src/runtime/reminder-deletions.ts'),{BrowserDaily}=await import('/src/browser/daily.ts');return {pending:await history.pendingReminderDeletions(),scheduled:(await new BrowserDaily().listReminders()).reminders.length,legacy:localStorage.getItem(key)};},key)).toEqual({pending:{},scheduled:0,legacy:' {broken action history '});
});
