import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';
async function start(page:any){await page.goto('/');await expect(page.getByRole('button',{name:'Camera',exact:true})).toBeVisible();await page.evaluate(async()=>{const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument();});}
async function seed(page:any){await start(page);await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=1000;c.height=300;const ctx=c.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,1000,300);ctx.fillStyle='black';ctx.font='60px Arial';ctx.fillText('Replacement image text',40,100);const image=await new Promise<Blob>(r=>c.toBlob(b=>r(b!)));(window as any).imageBytes=await image.arrayBuffer();const {saveScanDraft}=await import('/src/browser/scan-draft.ts');await saveScanDraft([image,image],undefined,new AbortController().signal,[[{text:'First saved correction',x:.04,y:.1,width:.8,height:.2}],[{text:'Second saved correction',x:.04,y:.1,width:.8,height:.2}]]);});await page.getByRole('button',{name:'Load saved draft',exact:true}).click();}
test('reviewed lines persist with reordered images and export after reload without recognition',async({page})=>{
 await seed(page);await page.getByRole('button',{name:'Move page 2 earlier',exact:true}).click();await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('Second saved correction');await page.getByLabel('Page 1 line 1',{exact:true}).fill('Retained correction');await page.getByLabel('Page 2 line 1',{exact:true}).fill('');await page.getByRole('button',{name:'Keep reviewed text',exact:true}).click();await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('draft saved');await page.reload();await expect(page.getByRole('button',{name:'Camera',exact:true})).toBeVisible();await page.evaluate(async()=>{window.Worker=class{constructor(){throw Error('Saved lines must not re-run recognition');}} as any;const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument();});await page.getByRole('button',{name:'Load saved draft',exact:true}).click();await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('Retained correction');await expect(page.getByLabel('Page 2 line 1',{exact:true})).toHaveValue('');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download reviewed searchable PDF',exact:true}).click();const task=getDocument({data:new Uint8Array(await readFile((await(await download).path())!)),useSystemFonts:true}),pdf=await task.promise;const texts=[];for(let i=1;i<=pdf.numPages;i++)texts.push((await(await pdf.getPage(i)).getTextContent()).items.map((x:any)=>x.str).filter(Boolean).join(' '));await task.destroy();expect(texts).toEqual(['Retained correction','']);
});
test('cancel discards text edits and replacing one page invalidates only that page',async({page})=>{
 test.setTimeout(90000);await seed(page);await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await page.getByLabel('Page 1 line 1',{exact:true}).fill('Discard this edit');await page.getByRole('button',{name:'Cancel searchable PDF',exact:true}).click();await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('First saved correction');await page.getByRole('button',{name:'Cancel searchable PDF',exact:true}).click();const bytes=await page.evaluate(()=>Array.from(new Uint8Array((window as any).imageBytes)));const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Replace page 1',exact:true}).click();await(await chooser).setFiles({name:'replacement.png',mimeType:'image/png',buffer:Buffer.from(bytes)});await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('draft saved');expect(await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');return(await readScanDraft()).textLayers;})).toEqual([null,[{text:'Second saved correction',x:.04,y:.1,width:.8,height:.2}]]);await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('Replacement image text',{timeout:60000});await expect(page.getByLabel('Page 2 line 1',{exact:true})).toHaveValue('Second saved correction');
});
test('invalid text and stale saves cannot replace a valid draft, and input edits cannot race persistence',async({page})=>{
 await seed(page);const result=await page.evaluate(async()=>{const {readScanDraft,saveScanDraft}=await import('/src/browser/scan-draft.ts');const old=(await readScanDraft())!,errors:string[]=[];for(const layers of [[],[[{text:'bad',x:2,y:0,width:.1,height:.1}],null]]){try{await saveScanDraft(old.pages,old.revision,new AbortController().signal,layers);errors.push('accepted');}catch(e){errors.push((e as Error).message);}}const layers=old.textLayers!;const saving=saveScanDraft(old.pages,old.revision,new AbortController().signal,layers);layers[0]![0].text='racing mutation';const saved=await saving;let stale=false;try{await saveScanDraft(old.pages,old.revision,new AbortController().signal,layers);}catch{stale=true;}return {errors,stale,text:(await readScanDraft())!.textLayers![0]![0].text,revision:saved.revision!==old.revision};});expect(result.errors).toHaveLength(2);expect(result.errors).not.toContain('accepted');expect(result).toMatchObject({stale:true,text:'First saved correction',revision:true});
});
test('adopting a corrected image clears its old text while cancelling preserves it',async({page})=>{
 await seed(page);await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await page.getByRole('button',{name:'Cancel correction',exact:true}).click();await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('First saved correction');await page.getByRole('button',{name:'Cancel searchable PDF',exact:true}).click();await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await page.getByRole('button',{name:'Preview correction',exact:true}).click();await page.getByRole('button',{name:'Use corrected page',exact:true}).click();await expect(page.getByRole('status')).toContainText('Corrected page applied');await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('draft saved');expect(await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');return(await readScanDraft()).textLayers;})).toEqual([null,[{text:'Second saved correction',x:.04,y:.1,width:.8,height:.2}]]);
});
