import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';
async function textOf(bytes:Uint8Array){const task=getDocument({data:new Uint8Array(bytes),useSystemFonts:true}),pdf=await task.promise;const texts=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);texts.push((await page.getTextContent()).items.map((item:any)=>item.str).filter(Boolean).join(' '));}await task.destroy();return texts;}
async function open(page:any){await page.goto('/');await expect(page.getByRole('button',{name:'Camera',exact:true})).toBeVisible();await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=1200;c.height=600;const ctx=c.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='black';ctx.font='60px Arial';ctx.fillText('Alpha searchable document',50,100);ctx.fillText('Review the second line.',50,220);const image=await new Promise<Blob>(r=>c.toBlob(b=>r(b!)));(window as any).scanImage=image;const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument(image);});}
test('real local OCR exports only reviewed lines as searchable text',async({page},info)=>{
 test.setTimeout(90000);const remote:string[]=[];page.on('request',r=>{const u=new URL(r.url());if(u.protocol.startsWith('http')&&u.hostname!=='127.0.0.1')remote.push(u.origin);});await open(page);await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();const review=page.getByRole('dialog',{name:'Review searchable PDF'});await expect(review.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('Alpha searchable document',{timeout:60000});await expect(review.getByLabel('Page 1 line 2',{exact:true})).toHaveValue('Review the second line.');await review.getByLabel('Page 1 line 1',{exact:true}).fill('Reviewed searchable correction');await review.getByLabel('Page 1 line 2',{exact:true}).fill('');await page.screenshot({path:info.outputPath('searchable-review.png')});const download=page.waitForEvent('download');await review.getByRole('button',{name:'Download reviewed searchable PDF',exact:true}).click();const file=await download,bytes=await readFile((await file.path())!);expect(await textOf(bytes)).toEqual(['Reviewed searchable correction']);expect(remote).toEqual([]);await expect(page.getByRole('dialog',{name:'Review searchable PDF'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Download searchable PDF',exact:true})).toBeDisabled();
});
test('invisible text preserves rendered pixels and stays on the matching page',async({page})=>{
 await open(page);const source=await (await page.request.get('/src/browser/files.ts')).text();const moduleUrl=source.match(/import\("([^"]*pdfjs-dist[^"]*)"\)/)![1],workerUrl=source.match(/import pdfWorkerUrl from "([^"]+)"/)![1];const result=await page.evaluate(async({moduleUrl,workerUrl})=>{const {createScanPdf}=await import('/src/prototype/scan-pdf.ts');const image=(window as any).scanImage;const plain=await createScanPdf([image,image],new AbortController().signal),searchable=await createScanPdf([image,image],new AbortController().signal,[[{text:'First reviewed page',x:.05,y:.1,width:.7,height:.1}],[{text:'Second reviewed page',x:.05,y:.3,width:.7,height:.1}]]);const pdfjs=await import(moduleUrl);pdfjs.GlobalWorkerOptions.workerSrc=(await import(workerUrl)).default;async function render(data:Uint8Array){const task=pdfjs.getDocument({data,standardFontDataUrl:'/pdfjs-assets/standard_fonts/'}),doc=await task.promise;const results=[];for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),viewport=page.getViewport({scale:.5}),canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;const ctx=canvas.getContext('2d')!;await page.render({canvas,canvasContext:ctx,viewport}).promise;results.push({pixels:ctx.getImageData(0,0,canvas.width,canvas.height).data,text:(await page.getTextContent()).items.map((x:any)=>x.str).join(' ')});}await task.destroy();return results;}const a=await render(plain),b=await render(searchable);return {same:a.every((p,i)=>p.pixels.every((v,j)=>v===b[i].pixels[j])),texts:b.map(p=>p.text)};},{moduleUrl,workerUrl});expect(result).toEqual({same:true,texts:['First reviewed page','Second reviewed page']});
});
test('invalid positions and unsupported text reject before exporting',async({page})=>{
 await open(page);const result=await page.evaluate(async()=>{const {createScanPdf}=await import('/src/prototype/scan-pdf.ts');const image=(window as any).scanImage,errors=[];for(const layer of [[{text:'outside',x:.9,y:0,width:.5,height:.1}],[{text:'two\nlines',x:0,y:0,width:.5,height:.1}],[{text:'漢字',x:0,y:0,width:.5,height:.1}]]){try{await createScanPdf(image,new AbortController().signal,[layer]);errors.push('success');}catch(e){errors.push((e as Error).message);}}return errors;});expect(result.every((x:string)=>x!=='success')).toBe(true);expect(result[2]).toContain('supports English');
});
test('Back cancels recognition without closing the document or exporting',async({page})=>{
 await open(page);await page.evaluate(()=>{const Original=Worker;(window as any).terminated=0;window.Worker=class extends Original{postMessage(){}terminate(){(window as any).terminated++;super.terminate();}};});await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review searchable PDF'})).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('dialog',{name:'Review searchable PDF'})).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Review scan document'})).toBeVisible();await expect(page.getByRole('button',{name:'Download searchable PDF',exact:true})).toBeEnabled();expect(await page.evaluate(()=>(window as any).terminated)).toBe(1);
});
test('closing after export dispatch records an uncertain outcome and blocks another export',async({page})=>{
 test.setTimeout(90000);await open(page);await page.evaluate(async()=>{const {BrowserNoteDocuments}=await import('/src/runtime/browser-note-documents.ts');BrowserNoteDocuments.prototype.exportPdf=async()=>{(window as any).dispatched=true;await new Promise<void>(r=>(window as any).releaseExport=r);return {status:'requested',message:'Requested'};};});await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();const download=page.getByRole('button',{name:'Download reviewed searchable PDF',exact:true});await expect(download).toBeEnabled({timeout:60000});await download.click();await expect.poll(()=>page.evaluate(()=>(window as any).dispatched)).toBe(true);await page.getByRole('button',{name:'Cancel searchable PDF',exact:true}).click();await expect(page.getByRole('status')).toContainText('unconfirmed');await expect(page.getByRole('button',{name:'Download searchable PDF',exact:true})).toBeDisabled();await page.evaluate(()=>(window as any).releaseExport());
});

test('reordered document pages keep their own reviewed searchable text',async({page})=>{
 test.setTimeout(90000);await open(page);const bytes=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=400;const ctx=canvas.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,1000,400);ctx.fillStyle='black';ctx.font='60px Arial';ctx.fillText('Second searchable page',40,100);return canvas.toDataURL().split(',')[1];});const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add page',exact:true}).click();await(await chooser).setFiles({name:'second.png',mimeType:'image/png',buffer:Buffer.from(bytes,'base64')});await page.getByRole('button',{name:'Move page 2 earlier',exact:true}).click();await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();await expect(page.getByLabel('Page 1 line 1',{exact:true})).toHaveValue('Second searchable page',{timeout:60000});await expect(page.getByLabel('Page 2 line 1',{exact:true})).toHaveValue('Alpha searchable document',{timeout:60000});await page.getByLabel('Page 1 line 1',{exact:true}).fill('Reviewed first page');await page.getByLabel('Page 2 line 1',{exact:true}).fill('Reviewed second page');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download reviewed searchable PDF',exact:true}).click();const bytesOut=await readFile((await (await download).path())!);expect(await textOf(bytesOut)).toEqual(['Reviewed first page','Reviewed second page Review the second line.']);
});
test('unsupported reviewed text can be corrected without dispatching an export',async({page})=>{
 test.setTimeout(90000);await open(page);await page.getByRole('button',{name:'Download searchable PDF',exact:true}).click();const line=page.getByLabel('Page 1 line 1',{exact:true});await expect(line).toBeVisible({timeout:60000});await line.fill('漢字');let downloads=0;page.on('download',()=>downloads++);await page.getByRole('button',{name:'Download reviewed searchable PDF',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review searchable PDF'}).getByRole('status')).toContainText('supports English');expect(downloads).toBe(0);await line.fill('Supported correction');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download reviewed searchable PDF',exact:true}).click();expect(await textOf(await readFile((await (await download).path())!))).toEqual(['Supported correction Review the second line.']);
});
