import {test,expect} from '@playwright/test';
async function open(page:any,theme='light'){await page.goto('/?theme='+theme);await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=400;canvas.height=300;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#111';ctx.fillRect(0,0,400,300);ctx.beginPath();ctx.moveTo(100,30);ctx.lineTo(300,30);ctx.lineTo(370,270);ctx.lineTo(30,270);ctx.closePath();ctx.fillStyle='white';ctx.fill();ctx.save();ctx.clip();ctx.fillStyle='red';ctx.fillRect(0,108,400,22);ctx.fillStyle='blue';ctx.fillRect(0,145,400,12);ctx.restore();const blob=await new Promise<Blob>(r=>canvas.toBlob(b=>r(b!)));(window as any).scanOriginal=blob;const {openScanDocument}=await import('/src/prototype/scan-document.ts');(window as any).closeScan=openScanDocument(blob);});}
async function corners(page:any){for(const [label,value] of Object.entries({'Top left horizontal (%)':'25','Top left vertical (%)':'10','Top right horizontal (%)':'75','Top right vertical (%)':'10','Bottom right horizontal (%)':'92.5','Bottom right vertical (%)':'90','Bottom left horizontal (%)':'7.5','Bottom left vertical (%)':'90'}))await page.getByLabel(label,{exact:true}).fill(value);}
test('perspective correction maps a trapezoid using projective sampling',async({page})=>{
 await open(page);const result=await page.evaluate(async()=>{const {correctScanPage}=await import('/src/browser/scan-correction.ts');const image=(window as any).scanOriginal,original=await image.arrayBuffer();const blob=await correctScanPage(image,[{x:.25,y:.1},{x:.75,y:.1},{x:.925,y:.9},{x:.075,y:.9}],new AbortController().signal);const bitmap=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(bitmap,0,0);const pixel=(x:number,y:number)=>[...ctx.getImageData(Math.round(x*canvas.width),Math.round(y*canvas.height),1,1).data];const result={width:bitmap.width,height:bitmap.height,center:pixel(.5,.5),margin:pixel(.1,.1),originalSame:original.byteLength===(await image.arrayBuffer()).byteLength};bitmap.close();return result;});
 expect(result.width).toBeGreaterThan(260);expect(result.width).toBeLessThan(280);expect(result.height).toBeGreaterThan(240);expect(result.center[0]).toBeGreaterThan(220);expect(result.center[1]).toBeLessThan(40);expect(result.center[2]).toBeLessThan(40);expect(result.margin.slice(0,3).every((v:number)=>v>230)).toBe(true);expect(result.originalSame).toBe(true);
});
test('reviewed correction saves and reloads only after adoption, then exports PDF',async({page},info)=>{
 await open(page);await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await corners(page);await page.getByRole('button',{name:'Preview correction',exact:true}).click();await expect(page.getByRole('img',{name:'Corrected page preview',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Use corrected page',exact:true})).toBeEnabled();await page.screenshot({path:info.outputPath('correction-preview.png')});await page.getByRole('button',{name:'Use corrected page',exact:true}).click();await expect(page.getByRole('status')).toContainText('Corrected page applied');await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');await page.reload();await page.evaluate(async()=>{const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument();});await page.getByRole('button',{name:'Load saved draft',exact:true}).click();await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();const dimensions=await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');const b=await createImageBitmap((await readScanDraft())!.pages[0]);const size={width:b.width,height:b.height};b.close();return size;});expect(dimensions.width).toBeLessThan(300);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download document PDF',exact:true}).click();expect((await download).suggestedFilename()).toMatch(/\.pdf$/);
});
test('invalid and changed corners cannot adopt stale preview; Back cancels only correction',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await page.getByLabel('Top left horizontal (%)',{exact:true}).fill('100');await page.getByRole('button',{name:'Preview correction',exact:true}).click();await expect(page.getByRole('dialog',{name:'Correct document page'}).getByRole('status')).toContainText('clockwise');await expect(page.getByRole('button',{name:'Use corrected page',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reset corners',exact:true}).click();await page.getByRole('button',{name:'Preview correction',exact:true}).click();await expect(page.getByRole('button',{name:'Use corrected page',exact:true})).toBeEnabled();await page.getByLabel('Top left horizontal (%)',{exact:true}).fill('5');await expect(page.getByRole('button',{name:'Use corrected page',exact:true})).toBeDisabled();await expect(page.getByRole('img',{name:'Corrected page preview',exact:true})).toBeHidden();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('dialog',{name:'Correct document page'})).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Review scan document'})).toBeVisible();await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');expect(await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');const saved=await (await readScanDraft())!.pages[0].arrayBuffer(),original=await (window as any).scanOriginal.arrayBuffer();return saved.byteLength===original.byteLength&&new Uint8Array(saved).every((v,i)=>v===new Uint8Array(original)[i]);})).toBe(true);
});
test('closing during image decode discards correction and releases the late bitmap',async({page})=>{
 await open(page);await page.evaluate(()=>{const original=createImageBitmap;window.createImageBitmap=(async(...args:any[])=>{const bitmap=await (original as any)(...args);await new Promise<void>(r=>(window as any).releaseCorrection=r);const close=bitmap.close.bind(bitmap);bitmap.close=()=>{(window as any).correctionClosed=true;close();};return bitmap;}) as typeof createImageBitmap;});await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await page.getByRole('button',{name:'Preview correction',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseCorrection)).toBe('function');await page.getByRole('button',{name:'Cancel correction',exact:true}).click();await page.evaluate(()=>(window as any).releaseCorrection());await expect.poll(()=>page.evaluate(()=>(window as any).correctionClosed)).toBe(true);await expect(page.getByRole('dialog',{name:'Correct document page'})).toHaveCount(0);await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();
});
test('page retirement closes both reviews and revokes correction image URLs',async({page})=>{
 await open(page);await page.evaluate(()=>{const revoke=URL.revokeObjectURL.bind(URL);(window as any).revoked=[];URL.revokeObjectURL=url=>{(window as any).revoked.push(url);revoke(url);};});await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await page.getByRole('button',{name:'Preview correction',exact:true}).click();await expect(page.getByRole('button',{name:'Use corrected page',exact:true})).toBeEnabled();await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).revoked.length)).toBe(3);
});

test('dragging a corner updates its accessible coordinates and invalidates the preview',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Correct page 1',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Correct document page'});const overlay=dialog.locator('svg');await overlay.scrollIntoViewIfNeeded();const box=(await overlay.boundingBox())!;await page.mouse.move(box.x+2,box.y+2);await page.mouse.down();await page.mouse.move(box.x+box.width*.2,box.y+box.height*.15);await page.mouse.up();expect(Number(await page.getByLabel('Top left horizontal (%)',{exact:true}).inputValue())).toBeCloseTo(20,0);expect(Number(await page.getByLabel('Top left vertical (%)',{exact:true}).inputValue())).toBeCloseTo(15,0);await expect(page.getByRole('button',{name:'Use corrected page',exact:true})).toBeDisabled();
});
test('invalid selections reject before decoding and processing yields to cancellation',async({page})=>{
 await open(page);const result=await page.evaluate(async()=>{const {correctScanPage,fullPageCorners}=await import('/src/browser/scan-correction.ts');const original=createImageBitmap;let decodes=0;window.createImageBitmap=((...args:any[])=>{decodes++;return (original as any)(...args);}) as typeof createImageBitmap;let invalid=0;for(const points of [[{x:-1,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}],[{x:0,y:0},{x:.01,y:0},{x:.01,y:.01},{x:0,y:.01}],[{x:0,y:0},{x:1,y:1},{x:1,y:0},{x:0,y:1}]]){try{await correctScanPage((window as any).scanOriginal,points as any,new AbortController().signal);}catch{invalid++;}}const before=decodes;const controller=new AbortController(),timer=window.setTimeout;window.setTimeout=((callback:()=>void,delay:number)=>timer(()=>{controller.abort();callback();},delay)) as typeof setTimeout;let cancelled=false;try{await correctScanPage((window as any).scanOriginal,fullPageCorners(),controller.signal);}catch(error){cancelled=(error as Error).name==='AbortError';}finally{window.setTimeout=timer;window.createImageBitmap=original;}return {invalid,before,cancelled};});expect(result).toEqual({invalid:3,before:0,cancelled:true});
});

for(const theme of ['light','dark'] as const)test(`correction preview controls fit a compact ${theme} viewport`,async({page},info)=>{
 await page.setViewportSize({width:360,height:740});await open(page,theme);await page.getByRole('button',{name:'Correct page 1',exact:true}).click();await page.getByRole('button',{name:'Preview correction',exact:true}).click();const use=page.getByRole('button',{name:'Use corrected page',exact:true});await expect(use).toBeEnabled();await use.scrollIntoViewIfNeeded();const box=(await use.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(360);expect(box.y+box.height).toBeLessThanOrEqual(740);expect(await page.getByRole('dialog',{name:'Correct document page'}).evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:info.outputPath(`correction-${theme}.png`)});await page.getByRole('button',{name:'Cancel correction',exact:true}).click();
});
