import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PDFDocument} from 'pdf-lib';
async function open(page:any){await page.goto('/');return page.evaluate(async()=>{
 const canvas=document.createElement('canvas');canvas.width=200;canvas.height=400;const ctx=canvas.getContext('2d')!;ctx.fillStyle='red';ctx.fillRect(0,0,200,400);const first=await new Promise<Blob>(r=>canvas.toBlob(b=>r(b!),'image/png'));const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument(first);
 canvas.width=400;canvas.height=200;ctx.fillStyle='blue';ctx.fillRect(0,0,400,200);return canvas.toDataURL().split(',')[1];
});}
test('document review adds, reorders, replaces and removes pages then downloads the reviewed order',async({page},info)=>{
 const data=await open(page);const dialog=page.getByRole('dialog',{name:'Review scan document'});
 async function select(label:string){const chooser=page.waitForEvent('filechooser');await dialog.getByRole('button',{name:label,exact:true}).click();await(await chooser).setFiles({name:'blue.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')});}
 await select('Add page');await expect(dialog.getByRole('img')).toHaveCount(2);await dialog.getByRole('button',{name:'Move page 2 earlier',exact:true}).click();
 await select('Add page');await expect(dialog.getByRole('img')).toHaveCount(3);await select('Replace page 3');await dialog.getByRole('button',{name:'Remove page 3',exact:true}).click();await expect(dialog.getByRole('img')).toHaveCount(2);
 const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download document PDF',exact:true}).click();const file=await download,path=info.outputPath('document.pdf');await file.saveAs(path);const pdf=await PDFDocument.load(await readFile(path));expect(pdf.getPageCount()).toBe(2);expect(pdf.getPages().map(p=>p.getWidth()>p.getHeight())).toEqual([true,false]);await expect(dialog.getByRole('button',{name:'Download document PDF',exact:true})).toBeDisabled();await page.screenshot({path:info.outputPath('document.png')});
});
test('closing during selection removes the input and releases all page previews',async({page})=>{
 await open(page);await page.evaluate(()=>{const original=URL.revokeObjectURL;(window as any).revoked=[];URL.revokeObjectURL=url=>{(window as any).revoked.push(url);original(url);};});page.on('filechooser',()=>{});await page.getByRole('button',{name:'Add page',exact:true}).click();await expect(page.locator('input[type=file]')).toHaveCount(1);await page.getByRole('button',{name:'Close document',exact:true}).click();await expect(page.locator('input[type=file]')).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Review scan document'})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).revoked.length)).toBe(1);
});
test('invalid added image retains existing pages and permits correction',async({page})=>{
 await open(page);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add page',exact:true}).click();await(await chooser).setFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(page.getByRole('button',{name:'Add page',exact:true})).toBeEnabled();await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();await expect(page.getByRole('dialog').getByRole('status')).not.toBeEmpty();
});
test('conversion failure is recoverable before an export is attempted',async({page})=>{
 await open(page);await page.evaluate(()=>{const original=window.createImageBitmap;(window as any).restoreBitmap=()=>window.createImageBitmap=original;window.createImageBitmap=(()=>Promise.reject(Error('Decode failed'))) as typeof createImageBitmap;});await page.getByRole('button',{name:'Download document PDF',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Decode failed');await expect(page.getByRole('button',{name:'Download document PDF',exact:true})).toBeEnabled();await page.evaluate(()=>(window as any).restoreBitmap());const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download document PDF',exact:true}).click();await download;
});
test('PDF page limits reject empty and oversized documents',async({page})=>{
 await page.goto('/');expect(await page.evaluate(async()=>{const {createScanPdf}=await import('/src/prototype/scan-pdf.ts');const results=[];for(const pages of [[],Array(21).fill(new Blob(['x'],{type:'image/png'}))]){try{await createScanPdf(pages,new AbortController().signal);results.push(false);}catch{results.push(true);}}return results;})).toEqual([true,true]);
});
test('scan review opens a document and Back returns to the reviewed text',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const {openScanReview}=await import('/src/prototype/scan-review.ts');const c=document.createElement('canvas');c.width=200;c.height=400;openScanReview(await new Promise<Blob>(r=>c.toBlob(b=>r(b!))),async()=>true);});const parent=page.getByRole('dialog',{name:'Review scanned text'});await parent.getByRole('button',{name:'Build multi-page PDF',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review scan document'})).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('dialog',{name:'Review scan document'})).toHaveCount(0);await expect(parent).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(parent).toHaveCount(0);
});

test('closing during conversion releases a late bitmap and makes no export request',async({page})=>{
 await open(page);await page.evaluate(async()=>{const {BrowserNoteDocuments}=await import('/src/runtime/browser-note-documents.ts');(window as any).exports=0;BrowserNoteDocuments.prototype.exportPdf=async()=>{(window as any).exports++;return {status:'requested',message:'Unexpected export'};};const original=createImageBitmap;(window as any).bitmapClosed=false;window.createImageBitmap=(async(...args:any[])=>{const bitmap=await (original as any)(...args);await new Promise<void>(resolve=>(window as any).releaseBitmap=resolve);const close=bitmap.close.bind(bitmap);bitmap.close=()=>{(window as any).bitmapClosed=true;close();};return bitmap;}) as typeof createImageBitmap;});
 await page.getByRole('button',{name:'Download document PDF',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseBitmap)).toBe('function');await page.getByRole('button',{name:'Close document',exact:true}).click();await page.evaluate(()=>(window as any).releaseBitmap());await expect.poll(()=>page.evaluate(()=>(window as any).bitmapClosed)).toBe(true);expect(await page.evaluate(()=>(window as any).exports)).toBe(0);await expect(page.getByRole('dialog',{name:'Review scan document'})).toHaveCount(0);
});
test('a lost export response retains the reviewed pages and blocks automatic retry',async({page})=>{
 await open(page);await page.evaluate(async()=>{const {BrowserNoteDocuments}=await import('/src/runtime/browser-note-documents.ts');const original=BrowserNoteDocuments.prototype.exportPdf;(window as any).exports=0;BrowserNoteDocuments.prototype.exportPdf=async function(input){(window as any).exports++;await original.call(this,input);throw Error('Lost export response');};});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download document PDF',exact:true}).click();await download;await expect(page.getByRole('status')).toHaveText('Export unconfirmed. Check Downloads before exporting again.');await expect(page.getByRole('button',{name:'Download document PDF',exact:true})).toBeDisabled();await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).exports)).toBe(1);
});
