import {test,expect} from '@playwright/test';
async function open(page:any){await page.goto('/');await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=200;c.height=400;c.getContext('2d')!.fillRect(0,0,200,400);const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument(await new Promise<Blob>(r=>c.toBlob(b=>r(b!))));});}
test('saved draft survives reload and opens from Camera without a new image',async({page},info)=>{
 await open(page);await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Document draft saved in this browser.');await page.reload();await page.getByRole('button',{name:'Camera',exact:true}).click();await page.screenshot({path:info.outputPath('camera-document-entry.png')});await page.getByRole('button',{name:'Scan document',exact:true}).click();await page.getByRole('button',{name:'Load saved draft',exact:true}).click();await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();await expect(page.getByRole('status')).toHaveText('Saved document draft loaded.');await page.screenshot({path:info.outputPath('loaded-draft.png')});const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download document PDF',exact:true}).click();await download;
});
test('draft revision conflicts preserve the other writer and delete retains reviewed images',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Document draft saved in this browser.');await page.evaluate(async()=>{const {readScanDraft,saveScanDraft}=await import('/src/browser/scan-draft.ts');const d=(await readScanDraft())!;await saveScanDraft([...d.pages,...d.pages],d.revision,new AbortController().signal);});await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('changed');page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Load saved draft',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review scan document'}).getByRole('img')).toHaveCount(2);await page.getByRole('button',{name:'Delete saved draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Saved draft deleted. Reviewed pages remain open.');await expect(page.getByRole('dialog',{name:'Review scan document'}).getByRole('img')).toHaveCount(2);expect(await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');return !!await readScanDraft();})).toBe(false);
});
test('quota failure never reports saved and cancellation cannot publish a draft',async({page})=>{
 await open(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;(window as any).restorePut=()=>IDBObjectStore.prototype.put=put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){if(this.name==='drafts')throw new DOMException('Storage full','QuotaExceededError');return put.call(this,value,key);};});await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Storage full');expect(await page.evaluate(async()=>{(window as any).restorePut();const {readScanDraft,saveScanDraft}=await import('/src/browser/scan-draft.ts');const controller=new AbortController();controller.abort();try{await saveScanDraft([new Blob(['x'],{type:'image/png'})],undefined,controller.signal);}catch{}return !!await readScanDraft();})).toBe(false);
});
test('cancellation after queuing a write rolls back the draft transaction',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {saveScanDraft,readScanDraft}=await import('/src/browser/scan-draft.ts');const controller=new AbortController(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){const request=put.call(this,value,key);if(this.name==='drafts')queueMicrotask(()=>controller.abort());return request;};let rejected=false;try{await saveScanDraft([new Blob(['image'],{type:'image/png'})],undefined,controller.signal);}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}return {rejected,saved:!!await readScanDraft()};});expect(result).toEqual({rejected:true,saved:false});
});

test('cancellation after queuing draft deletion retains the saved revision and pages',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {saveScanDraft,readScanDraft,deleteScanDraft}=await import('/src/browser/scan-draft.ts');const draft=await saveScanDraft([new Blob(['retained'],{type:'image/png'})],undefined,new AbortController().signal);const controller=new AbortController(),remove=IDBObjectStore.prototype.delete;IDBObjectStore.prototype.delete=function(key){const request=remove.call(this,key);if(this.name==='drafts')queueMicrotask(()=>controller.abort());return request;};let rejected=false;try{await deleteScanDraft(draft.revision,controller.signal);}catch{rejected=true;}finally{IDBObjectStore.prototype.delete=remove;}const saved=await readScanDraft();return {rejected,same:saved?.revision===draft.revision,text:await saved?.pages[0].text()};});expect(result).toEqual({rejected:true,same:true,text:'retained'});
});

test('draft binary page bytes and order survive reload without storing Blobs',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const {saveScanDraft}=await import('/src/browser/scan-draft.ts');await saveScanDraft([new Blob([new Uint8Array([0,255,128,1])],{type:'image/png'}),new Blob([new Uint8Array([99,0,42])],{type:'image/jpeg'})],undefined,new AbortController().signal);});await page.reload();
 const result=await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');const draft=(await readScanDraft())!;const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('alpha.browser.scan-draft.v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const row:any=await new Promise((resolve,reject)=>{const r=db.transaction('drafts').objectStore('drafts').get('document');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();return {pages:await Promise.all(draft.pages.map(async p=>({type:p.type,bytes:[...new Uint8Array(await p.arrayBuffer())]}))),format:row.format,storedBytes:row.pages.every((p:any)=>p.bytes instanceof ArrayBuffer&&!(p instanceof Blob))};});
 expect(result).toEqual({pages:[{type:'image/png',bytes:[0,255,128,1]},{type:'image/jpeg',bytes:[99,0,42]}],format:2,storedBytes:true});
});
test('failed page read and cancellation during serialization retain the saved draft',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {saveScanDraft,readScanDraft}=await import('/src/browser/scan-draft.ts');const initial=await saveScanDraft([new Blob(['original'],{type:'image/png'})],undefined,new AbortController().signal);let failed=false,cancelled=false;
 const broken=new Blob(['broken'],{type:'image/png'});broken.arrayBuffer=async()=>{throw Error('Unreadable page');};try{await saveScanDraft([broken],initial.revision,new AbortController().signal);}catch{failed=true;}
 const controller=new AbortController(),held=new Blob(['held'],{type:'image/png'});let release!:()=>void;held.arrayBuffer=async()=>{await new Promise<void>(resolve=>release=resolve);return new Uint8Array([1,2,3,4]).buffer;};const pending=saveScanDraft([held],initial.revision,controller.signal).catch(error=>{cancelled=error.name==='AbortError';});controller.abort();release();await pending;const saved=(await readScanDraft())!;return {failed,cancelled,same:saved.revision===initial.revision,text:await saved.pages[0].text()};});expect(result).toEqual({failed:true,cancelled:true,same:true,text:'original'});
});
test('a newer draft wins while an older save is serializing page bytes',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {saveScanDraft,readScanDraft}=await import('/src/browser/scan-draft.ts');const initial=await saveScanDraft([new Blob(['original'],{type:'image/png'})],undefined,new AbortController().signal);let release!:()=>void;const held=new Blob(['held'],{type:'image/png'});held.arrayBuffer=async()=>{await new Promise<void>(resolve=>release=resolve);return new Uint8Array([1,2,3,4]).buffer;};const pending=saveScanDraft([held],initial.revision,new AbortController().signal).then(()=>false,()=>true);const latest=await saveScanDraft([new Blob(['latest'],{type:'image/png'})],initial.revision,new AbortController().signal);release();const rejected=await pending,saved=(await readScanDraft())!;return {rejected,same:saved.revision===latest.revision,text:await saved.pages[0].text()};});expect(result).toEqual({rejected:true,same:true,text:'latest'});
});
test('legacy Blob drafts remain readable and upgrade on the next explicit save',async({page,browserName})=>{
 test.skip(browserName==='webkit','WebKit cannot write the historical Blob representation');await page.goto('/');const result=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('alpha.browser.scan-draft.v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put({id:'document',revision:'legacy',updated:Date.now(),pages:[new Blob(['legacy'],{type:'image/png'})]});tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);});db.close();const {readScanDraft,saveScanDraft}=await import('/src/browser/scan-draft.ts');const old=(await readScanDraft())!;const saved=await saveScanDraft(old.pages,old.revision,new AbortController().signal);return {before:await old.pages[0].text(),after:await (await readScanDraft())!.pages[0].text(),changed:saved.revision!==old.revision};});expect(result).toEqual({before:'legacy',after:'legacy',changed:true});
});
