import {test,expect} from '@playwright/test';
async function open(page:any){await page.goto('/');await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=200;c.height=400;c.getContext('2d')!.fillRect(0,0,200,400);const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument(await new Promise<Blob>(r=>c.toBlob(b=>r(b!))));});}
test('saved draft survives reload and opens from Camera without a new image',async({page},info)=>{
 await open(page);await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Document draft saved in this browser.');await page.reload();await page.getByRole('button',{name:'Camera',exact:true}).click();await page.screenshot({path:info.outputPath('camera-document-entry.png')});await page.getByRole('button',{name:'Scan document',exact:true}).click();await page.getByRole('button',{name:'Load saved draft',exact:true}).click();await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();await expect(page.getByRole('status')).toHaveText('Saved document draft loaded.');await page.screenshot({path:info.outputPath('loaded-draft.png')});const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download document PDF',exact:true}).click();await download;
});
test('draft revision conflicts preserve the other writer and delete retains reviewed images',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Document draft saved in this browser.');await page.evaluate(async()=>{const {readScanDraft,saveScanDraft}=await import('/src/browser/scan-draft.ts');const d=(await readScanDraft())!;await saveScanDraft([...d.pages,...d.pages],d.revision,new AbortController().signal);});await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toContainText('changed');page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Load saved draft',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review scan document'}).getByRole('img')).toHaveCount(2);await page.getByRole('button',{name:'Delete saved draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Saved draft deleted. Reviewed pages remain open.');await expect(page.getByRole('dialog',{name:'Review scan document'}).getByRole('img')).toHaveCount(2);expect(await page.evaluate(async()=>{const {readScanDraft}=await import('/src/browser/scan-draft.ts');return !!await readScanDraft();})).toBe(false);
});
test('quota failure never reports saved and cancellation cannot publish a draft',async({page})=>{
 await open(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;(window as any).restorePut=()=>IDBObjectStore.prototype.put=put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){if(this.name==='drafts')throw new DOMException('Storage full','QuotaExceededError');return put.call(this,value,key);};});await page.getByRole('button',{name:'Save document draft',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Storage full');expect(await page.evaluate(async()=>{(window as any).restorePut();const {readScanDraft,saveScanDraft}=await import('/src/browser/scan-draft.ts');const controller=new AbortController();controller.abort();try{await saveScanDraft([new Blob(['x'],{type:'image/png'})],undefined,controller.signal);}catch{}return !!await readScanDraft();})).toBe(false);
});
test('cancellation after queuing a write rolls back the draft transaction',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {saveScanDraft,readScanDraft}=await import('/src/browser/scan-draft.ts');const controller=new AbortController(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){const request=put.call(this,value,key);if(this.name==='drafts')queueMicrotask(()=>controller.abort());return request;};let rejected=false;try{await saveScanDraft([new Blob(['image'],{type:'image/png'})],undefined,controller.signal);}catch{rejected=true;}finally{IDBObjectStore.prototype.put=put;}return {rejected,saved:!!await readScanDraft()};});expect(result).toEqual({rejected:true,saved:false});
});

test('cancellation after queuing draft deletion retains the saved revision and pages',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {saveScanDraft,readScanDraft,deleteScanDraft}=await import('/src/browser/scan-draft.ts');const draft=await saveScanDraft([new Blob(['retained'],{type:'image/png'})],undefined,new AbortController().signal);const controller=new AbortController(),remove=IDBObjectStore.prototype.delete;IDBObjectStore.prototype.delete=function(key){const request=remove.call(this,key);if(this.name==='drafts')queueMicrotask(()=>controller.abort());return request;};let rejected=false;try{await deleteScanDraft(draft.revision,controller.signal);}catch{rejected=true;}finally{IDBObjectStore.prototype.delete=remove;}const saved=await readScanDraft();return {rejected,same:saved?.revision===draft.revision,text:await saved?.pages[0].text()};});expect(result).toEqual({rejected:true,same:true,text:'retained'});
});
