import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=240;const ctx=c.getContext('2d')!;ctx.fillStyle='red';ctx.fillRect(0,0,320,240);const image=await new Promise<Blob>(r=>c.toBlob(b=>r(b!)));const {openScanDocument}=await import('/src/prototype/scan-document.ts');openScanDocument(image);const state=(window as any).scanCamera={streams:[] as MediaStream[],calls:0,held:false,denied:false};const mediaDevices=navigator.mediaDevices;Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:mediaDevices});mediaDevices.getUserMedia=async()=>{state.calls++;if(state.denied)throw new DOMException('Denied','NotAllowedError');if(state.held)await new Promise<void>(r=>state.release=r);const stream=c.captureStream(20);state.streams.push(stream);return stream;};setInterval(()=>{ctx.fillStyle='blue';ctx.fillRect(0,0,320,240);},40);});
});
test('captured and retaken pages enter the document only after review',async({page},info)=>{
 const document=page.getByRole('dialog',{name:'Review scan document'});await document.getByRole('button',{name:'Capture new page',exact:true}).click();let camera=page.getByRole('dialog',{name:'Capture document page'});await expect(camera.getByRole('button',{name:'Capture page',exact:true})).toBeEnabled();await expect.poll(()=>camera.locator('video').evaluate((v:HTMLVideoElement)=>{const c=document.createElement('canvas');c.width=320;c.height=240;const ctx=c.getContext('2d')!;ctx.drawImage(v,0,0);return ctx.getImageData(50,50,1,1).data[2];})).toBeGreaterThan(230);await camera.getByRole('button',{name:'Capture page',exact:true}).click();await expect(camera.getByRole('img')).toBeVisible();await expect(document.getByRole('img')).toHaveCount(1);await camera.getByRole('button',{name:'Retake capture',exact:true}).click();await expect.poll(()=>camera.locator('video').evaluate((v:HTMLVideoElement)=>{const c=document.createElement('canvas');c.width=320;c.height=240;const ctx=c.getContext('2d')!;ctx.drawImage(v,0,0);return ctx.getImageData(50,50,1,1).data[2];})).toBeGreaterThan(230);await camera.getByRole('button',{name:'Capture page',exact:true}).click();await camera.getByRole('button',{name:'Use captured page',exact:true}).click();await expect(document.getByRole('img')).toHaveCount(2);const previousPage=await document.getByRole('img',{name:'Document page 1',exact:true}).getAttribute('src');await document.getByRole('button',{name:'Retake page 1',exact:true}).click();camera=page.getByRole('dialog',{name:'Capture document page'});await expect(camera.getByRole('button',{name:'Capture page',exact:true})).toBeEnabled();await expect.poll(()=>camera.locator('video').evaluate((v:HTMLVideoElement)=>{const c=document.createElement('canvas');c.width=320;c.height=240;const ctx=c.getContext('2d')!;ctx.drawImage(v,0,0);return ctx.getImageData(50,50,1,1).data[2];})).toBeGreaterThan(230);await camera.getByRole('button',{name:'Capture page',exact:true}).click();await expect(camera.getByRole('img')).toBeVisible();await page.screenshot({path:info.outputPath('capture-review.png')});await camera.getByRole('button',{name:'Use captured page',exact:true}).click();await expect(document.getByRole('img')).toHaveCount(2);await expect(document.getByRole('img',{name:'Document page 1',exact:true})).not.toHaveAttribute('src',previousPage!);await expect(document.getByRole('button',{name:'Retake page 1',exact:true})).toBeEnabled();const pixel=await document.getByRole('img',{name:'Document page 1',exact:true}).evaluate(async(img:HTMLImageElement)=>{await img.decode();const c=document.createElement('canvas');c.width=320;c.height=240;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);return Array.from(ctx.getImageData(50,50,1,1).data);});expect(pixel[2]).toBeGreaterThan(230);expect(pixel[0]).toBeLessThan(20);expect(await page.evaluate(()=>(window as any).scanCamera.streams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);
});
test('Back cancels a pending camera request and stops its late stream without closing the document',async({page})=>{
 await page.evaluate(()=>(window as any).scanCamera.held=true);await page.getByRole('button',{name:'Capture new page',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).scanCamera.calls)).toBe(1);await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(page.getByRole('dialog',{name:'Capture document page'})).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Review scan document'})).toBeVisible();await page.evaluate(()=>(window as any).scanCamera.release());await expect.poll(()=>page.evaluate(()=>(window as any).scanCamera.streams[0]?.getVideoTracks()[0].readyState)).toBe('ended');await expect(page.getByRole('img',{name:'Document page 1',exact:true})).toBeVisible();
});
test('denial permits a fresh capture and page retirement stops the camera',async({page})=>{
 await page.evaluate(()=>(window as any).scanCamera.denied=true);await page.getByRole('button',{name:'Capture new page',exact:true}).click();const camera=page.getByRole('dialog',{name:'Capture document page'});await expect(camera.getByRole('status')).toHaveText('Choose an image or close and try camera access again.');await camera.getByRole('button',{name:'Cancel capture',exact:true}).click();await page.evaluate(()=>(window as any).scanCamera.denied=false);await page.getByRole('button',{name:'Capture new page',exact:true}).click();await expect(camera.getByRole('button',{name:'Capture page',exact:true})).toBeEnabled();await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).scanCamera.streams.every((s:MediaStream)=>s.getTracks().every(t=>t.readyState==='ended')))).toBe(true);
});
test('document camera borrows cloned tracks and does not stop the active Camera preview',async({page})=>{
 await page.evaluate(()=>{const frame=document.createElement('div');frame.setAttribute('aria-label','Viewfinder. Test');const video=document.createElement('video');const c=document.createElement('canvas');c.width=320;c.height=240;const ctx=c.getContext('2d')!;setInterval(()=>{ctx.fillStyle='green';ctx.fillRect(0,0,320,240);},40);const stream=c.captureStream(20);(window as any).originalScanCamera=stream;video.srcObject=stream;frame.append(video);document.body.append(frame);});await page.getByRole('button',{name:'Capture new page',exact:true}).click();const camera=page.getByRole('dialog',{name:'Capture document page'});await expect(camera.getByRole('button',{name:'Capture page',exact:true})).toBeEnabled();await camera.getByRole('button',{name:'Cancel capture',exact:true}).click();expect(await page.evaluate(()=>({calls:(window as any).scanCamera.calls,ready:(window as any).originalScanCamera.getVideoTracks()[0].readyState}))).toEqual({calls:0,ready:'live'});
});
