import {test,expect} from '@playwright/test';
for(const theme of ['light','dark'])test(`normal app reviews selected file before composing ${theme}`,async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?theme='+theme);
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaFiles').importFile(new File(['Public excerpt\nPRIVATE OMIT'],'review-normal.txt',{type:'text/plain'}));const {alphaClient}=await import('/src/runtime/alpha-client.ts');(window as any).unexpectedContentSends=0;alphaClient.send=async()=>{(window as any).unexpectedContentSends++;throw Error('Review must not send');};});
 await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByText('App files',{exact:true}).first().click();await page.getByRole('button',{name:'Open review-normal.txt',exact:true}).click();await expect(page.getByText('PRIVATE OMIT',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Ask Alpha',exact:true}).click();const review=page.getByRole('dialog',{name:'Ask about selected content'});await expect(review).toBeVisible();await expect(review.getByRole('textbox',{name:'Content excerpt'})).toHaveValue('Public excerpt\nPRIVATE OMIT');
 await review.getByRole('button',{name:'Cancel',exact:true}).click();await expect(review).toHaveCount(0);await expect(page.getByText('PRIVATE OMIT',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Ask Alpha',exact:true}).click();await review.getByRole('textbox',{name:'Content excerpt'}).fill('Public excerpt');await review.getByRole('textbox',{name:'Question about content'}).fill('Summarize and propose a note; wait for my approval.');await review.getByRole('button',{name:'Use in conversation',exact:true}).click();
 await expect(review).toHaveCount(0);await expect(page.getByRole('textbox',{name:'Message Alpha',exact:true})).toHaveValue('Summarize and propose a note; wait for my approval.\n\nSource: review-normal.txt\n\nPublic excerpt');expect(await page.evaluate(()=>(window as any).unexpectedContentSends)).toBe(0);
});
