import {test,expect} from '@playwright/test';
for(const theme of ['light','dark'])for(const height of [640,360])test(`selected document fits large text: ${theme} ${height}`,async({page},info)=>{
 await page.setViewportSize({width:360,height});await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev&theme='+theme);
 await page.evaluate(async()=>{const {BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent:150});});const trigger=page.getByRole('button',{name:'Files',exact:true});await trigger.focus();
 await page.evaluate(async()=>{const {registerPlugin}=await import('/src/platform-plugins.ts');const files=registerPlugin<any>('AlphaFiles');const selected=await files.importFile(new File(['<h1>Selected content</h1>'],'Document'+'longname'.repeat(26)+'.html',{type:'text/html'}));(window as any).documentSelection=selected;await files.openSelected(selected);});
 const dialog=page.getByRole('dialog',{name:'Selected document'}),done=dialog.getByRole('button',{name:'Done',exact:true});expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await expect(done).toBeInViewport();expect((await done.boundingBox())!.height).toBeGreaterThanOrEqual(44);await expect(done).toHaveCSS('font-size','24px');await expect(done).toHaveCSS('color-scheme',theme);await expect(dialog.locator('iframe')).toHaveAttribute('sandbox','');await expect(dialog.frameLocator('iframe').getByRole('heading',{name:'Selected content'})).toBeVisible();expect((await dialog.locator('iframe').boundingBox())!.height).toBeGreaterThan(80);const heading=dialog.getByRole('heading');await heading.focus();await page.keyboard.press('End');await expect.poll(()=>heading.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);await expect(done).toBeInViewport();await page.screenshot({path:info.outputPath('selected-document.png')});await done.click();await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
});
for(const action of ['back','background','forget','replace','escape'])test(`selected document cleans up on ${action}`,async({page})=>{
 await page.goto('/?mode=dev');const trigger=page.getByRole('button',{name:'Files',exact:true});await trigger.focus();await page.evaluate(async()=>{const {BrowserFiles}=await import('/src/browser/files.ts');const w=window as any;w.testFiles=new BrowserFiles();w.testSelection=await w.testFiles.importFile(new File(['<h1>First file</h1>'],'first.html',{type:'text/html'}));await w.testFiles.openSelected(w.testSelection);});
 const dialog=page.getByRole('dialog',{name:'Selected document'});
 if(action==='escape')await page.keyboard.press('Escape');else await page.evaluate(async action=>{const w=window as any;if(action==='back')window.dispatchEvent(new Event('alpha-back',{cancelable:true}));if(action==='background'){Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));}if(action==='forget')await w.testFiles.forgetSelected(w.testSelection);if(action==='replace'){await w.testFiles.openSelected(w.testSelection);await w.testFiles.forgetSelected(w.testSelection);}},action);
 await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
});
