import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const raw='{broken original';
async function seed(page:any,records:Record<string,string>){await page.addInitScript(records=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));if(!sessionStorage.getItem('recovery-test-seeded')){for(const [name,value] of Object.entries(records))localStorage.setItem('alpha.dev.app.'+name,value);sessionStorage.setItem('recovery-test-seeded','1');}},records);await page.goto('/?mode=dev&tools=1');}
test('malformed saved apps preserve bytes, isolate recovery and let healthy apps open',async({page},info)=>{
 await page.setViewportSize({width:360,height:640});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await seed(page,{inbox:raw,contacts:JSON.stringify({list:[]})});await expect(page.getByRole('button',{name:'Open your calendar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Inbox',exact:true}).click();const d=page.getByRole('dialog',{name:'Saved app recovery'});await expect(d).toContainText('original data is retained');expect(await page.evaluate(async()=>{const {Component}=await import('/src/prototype/model.js');try{Component.prototype.vset.call({},'inbox',{mails:[],sent:[]});return false;}catch{return true;}})).toBe(true);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(raw);
 await page.screenshot({path:info.outputPath('recovery-light.png')});const download=page.waitForEvent('download');await d.getByRole('button',{name:'Download Inbox backup',exact:true}).click();expect(await readFile((await (await download).path())!,'utf8')).toBe(raw);await d.getByRole('button',{name:'Close recovery',exact:true}).click();await page.getByRole('button',{name:'Contacts',exact:true}).click();await expect(page.getByRole('button',{name:'New contact',exact:true})).toBeVisible();expect(errors).toEqual([]);
 await page.reload();await page.getByRole('button',{name:'Inbox',exact:true}).click();await expect(d).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(raw);
});
test('incompatible containers and unreadable storage cannot crash Home or overwrite saved data',async({page},info)=>{
 await page.setViewportSize({width:360,height:640});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await seed(page,{phone:'[]',messages:JSON.stringify({threads:{maya:null}}),contacts:JSON.stringify({list:[null]}),inbox:JSON.stringify({mails:{}}),workflows:'null',wallet:JSON.stringify({transit:'bad'})});await expect(page.getByRole('button',{name:'Open your calendar',exact:true})).toBeVisible();
 await page.goto('/?mode=dev&theme=dark&tools=1');await page.getByRole('button',{name:'Device controls',exact:true}).click();await page.getByRole('button',{name:'Saved app recovery',exact:true}).click();const d=page.getByRole('dialog',{name:'Saved app recovery'});for(const name of ['Phone','Messages','Contacts','Inbox','Workflows','Wallet'])await expect(d.getByRole('button',{name:'Reset '+name,exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('recovery-dark.png')});expect(await d.evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new Event('alpha-back',{cancelable:true})));await expect(d).toHaveCount(0);expect(errors).toEqual([]);
});
test('reset is explicit, preserves unrelated apps, and refuses concurrent replacement or failed removal',async({page})=>{
 await seed(page,{inbox:raw,contacts:JSON.stringify({list:[]})});await page.getByRole('button',{name:'Inbox',exact:true}).click();const d=page.getByRole('dialog',{name:'Saved app recovery'});await d.getByRole('button',{name:'Reset Inbox',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(raw);
 await page.evaluate(()=>localStorage.setItem('alpha.dev.app.inbox',JSON.stringify({mails:[],sent:[]})));await d.getByRole('button',{name:'Confirm reset Inbox',exact:true}).click();await expect(d.getByRole('status')).toContainText('could not be confirmed');expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(JSON.stringify({mails:[],sent:[]}));
 await page.evaluate(raw=>{localStorage.setItem('alpha.dev.app.inbox',raw);const remove=Storage.prototype.removeItem;(window as any).restoreRemoval=()=>Storage.prototype.removeItem=remove;Storage.prototype.removeItem=function(k){if(k==='alpha.dev.app.inbox')throw Error('Denied');return remove.call(this,k);};},raw);await d.getByRole('button',{name:'Reset Inbox',exact:true}).click();await d.getByRole('button',{name:'Confirm reset Inbox',exact:true}).click();await expect(d.getByRole('status')).toContainText('could not be confirmed');expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(raw);await page.evaluate(()=>(window as any).restoreRemoval());
 await d.getByRole('button',{name:'Reset Inbox',exact:true}).click();await d.getByRole('button',{name:'Confirm reset Inbox',exact:true}).click();await expect(d).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBeNull();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.contacts'))).toBe(JSON.stringify({list:[]}));await page.getByRole('button',{name:'Inbox',exact:true}).click();await expect(d).toHaveCount(0);
});
test('unreadable app storage retains the recovery route without offering a destructive reset',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));const get=Storage.prototype.getItem;Storage.prototype.getItem=function(k){if(k==='alpha.dev.app.inbox')throw Error('Denied');return get.call(this,k);};});await page.goto('/?mode=dev&tools=1');await page.getByRole('button',{name:'Inbox',exact:true}).click();const d=page.getByRole('dialog',{name:'Saved app recovery'});await expect(d.getByRole('button',{name:'Reset Inbox',exact:true})).toBeDisabled();await expect(d.getByRole('button',{name:'Download Inbox backup',exact:true})).toBeDisabled();
});

test('background polling cannot reopen dismissed recovery for an invalid workflow store',async({page})=>{await seed(page,{workflows:'null'});await page.getByRole('button',{name:'Workflows',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Saved app recovery'});await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Close recovery',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(1500);await expect(dialog).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.workflows'))).toBe('null');});

test('a second development tab cannot reset data owned by the first writer',async({page,context})=>{
 await seed(page,{inbox:raw,contacts:JSON.stringify({list:[]})});
 await expect.poll(()=>page.evaluate(async()=>(await navigator.locks.query()).held?.some(lock=>lock.name==='alpha.dev.simulator-writer.v1'))).toBe(true);
 const other=await context.newPage();await other.goto('/?mode=dev');await other.getByRole('button',{name:'Inbox',exact:true}).click();const dialog=other.getByRole('dialog',{name:'Saved app recovery'});
 await dialog.getByRole('button',{name:'Reset Inbox',exact:true}).click();await dialog.getByRole('button',{name:'Confirm reset Inbox',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Another development tab owns');expect(await other.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(raw);
 await page.close();await other.reload();await other.getByRole('button',{name:'Inbox',exact:true}).click();await dialog.getByRole('button',{name:'Reset Inbox',exact:true}).click();await dialog.getByRole('button',{name:'Confirm reset Inbox',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await other.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBeNull();expect(await other.evaluate(()=>localStorage.getItem('alpha.dev.app.contacts'))).toBe(JSON.stringify({list:[]}));
});
test('a retired page cannot reset its captured malformed data',async({page})=>{
 await seed(page,{inbox:raw});await page.getByRole('button',{name:'Inbox',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Saved app recovery'});await dialog.getByRole('button',{name:'Reset Inbox',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await dialog.getByRole('button',{name:'Confirm reset Inbox',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Safe development storage is unavailable');expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.inbox'))).toBe(raw);
});
test('successful reset retires stale reducers before they can recreate erased data',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?tools=1');
 expect(await page.evaluate(async()=>{const {SimulatorWriter}=await import('/src/browser/simulator-writer.ts'),key='alpha.dev.app.inbox',raw='{broken';localStorage.setItem(key,raw);const writer=new SimulatorWriter(new Map([[key,raw]]));for(let i=0;i<100&&!writer.ready;i++)await new Promise(r=>setTimeout(r,10));if(!writer.ready)throw Error('Fixture writer unavailable');writer.reset(key,raw);let refused=false;try{writer.write(key,JSON.stringify({mails:[]}));}catch{refused=true;}return {refused,ready:writer.ready,saved:localStorage.getItem(key)};})).toEqual({refused:true,ready:false,saved:null});
});
