import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'})));await page.goto('/?mode=dev');});
async function edit(page:any,name:string){await page.getByRole('button',{name:'Contacts',exact:true}).click();await page.getByRole('button',{name:'New contact',exact:true}).click();await page.getByPlaceholder('First name',{exact:true}).fill(name);}
test('another development tab cannot replace the current writers saved contacts',async({page,context})=>{
 const other=await context.newPage();await other.goto(page.url());await edit(page,'First writer');await edit(other,'Second writer');await page.getByRole('button',{name:'Save',exact:true}).click();await other.getByRole('button',{name:'Save',exact:true}).click();await expect(other.getByPlaceholder('First name',{exact:true})).toHaveValue('Second writer');expect(await other.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.filter((p:any)=>/writer/.test(p.first)).map((p:any)=>p.first))).toEqual(['First writer']);await expect(other.getByText(/Another development tab/)).toBeVisible();await page.close();await other.reload();await edit(other,'Second writer');await other.getByRole('button',{name:'Save',exact:true}).click();expect(await other.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.filter((p:any)=>/writer/.test(p.first)).map((p:any)=>p.first).sort())).toEqual(['First writer','Second writer']);
});
test('storage changed outside the writer lease is retained and the current draft stays open',async({page})=>{
 await edit(page,'Unsaved draft');const replacement=JSON.stringify({list:[]});await page.evaluate(raw=>localStorage.setItem('alpha.dev.app.contacts',raw),replacement);await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByPlaceholder('First name',{exact:true})).toHaveValue('Unsaved draft');await expect(page.getByText(/Saved app data changed/)).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.contacts'))).toBe(replacement);
});
test('unavailable Web Locks refuses persistence without clearing the draft',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(navigator,'locks',{value:undefined,configurable:true}));await page.reload();await edit(page,'No lock');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByPlaceholder('First name',{exact:true})).toHaveValue('No lock');await expect(page.getByText(/Safe development storage is unavailable/)).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alpha.dev.app.contacts'))).toBeNull();
});
test('page retirement revokes the old tab before a new writer can save',async({page,context})=>{
 await edit(page,'Retired draft');await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));const other=await context.newPage();await other.goto(page.url());await edit(other,'Current writer');await other.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByPlaceholder('First name',{exact:true})).toHaveValue('Retired draft');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.dev.app.contacts')!).list.filter((p:any)=>/writer|draft/.test(p.first)).map((p:any)=>p.first))).toEqual(['Current writer']);
});
