import { returnToApps } from './app-navigation';
import {test,expect,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
const contents='Public fact: twelve raised beds.\nPRIVATE OMIT: do not send this line.';
async function setup(page:Page,legacy=false){
 await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await returnToApps(page);
 await page.evaluate(async(contents)=>{const{registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaFiles').importFile(new File([contents],'summary-source.txt',{type:'text/plain'}));},contents);
 if(legacy)await page.evaluate(async()=>{const{BrowserMailAttachments}=await import('/src/browser/mail-attachments.ts');const read=BrowserMailAttachments.prototype.readSelected;BrowserMailAttachments.prototype.readSelected=async function(input:any){const value=await read.call(this,input);delete (value as any).sourceReferenceVersion;return value;};BrowserMailAttachments.prototype.retainSourceReference=async()=>{throw Error('Old bridge has no source reference method');};});
 await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByText('App files',{exact:true}).first().click();await page.getByRole('button',{name:'Open summary-source.txt',exact:true}).click();await page.getByRole('button',{name:'Ask Alpha',exact:true}).click();const review=page.getByRole('dialog',{name:'Ask about selected content'});await review.getByRole('textbox',{name:'Content excerpt'}).fill('Public fact: twelve raised beds.');await review.getByRole('button',{name:'Use in conversation',exact:true}).click();await expect(review).toHaveCount(0);await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByText('Review summary note',{exact:true})).toBeVisible();
}
async function notes(page:Page){return page.evaluate(async ()=>JSON.parse((await (await import('/src/runtime/browser-notes-document.ts')).readBrowserNotesRaw())||'{"records":[]}').records);}
test('displayed answer requires review and saves exactly edited text with source provenance',async({page},info)=>{
 await setup(page);expect(await notes(page)).toEqual([]);await page.getByText('Review summary note',{exact:true}).click();const review=page.getByRole('dialog',{name:'Save reviewed summary note'});await expect(review.getByRole('textbox',{name:'Summary note text'})).toHaveValue('Development reply. Edit this response in Agent connection.');await review.getByRole('button',{name:'Cancel',exact:true}).click();expect(await notes(page)).toEqual([]);
 await page.getByText('Review summary note',{exact:true}).click();await review.getByRole('textbox',{name:'Summary note title'}).fill('Reviewed garden summary');await review.getByRole('textbox',{name:'Summary note text'}).fill('There are twelve raised beds.');await page.screenshot({path:info.outputPath('review-summary.png')});await review.getByRole('button',{name:'Save reviewed note',exact:true}).click();await expect(review).toHaveCount(0);const retained=await notes(page);expect(retained).toHaveLength(1);expect(retained[0].body).toBe('There are twelve raised beds.');expect(retained[0].documentSource).toEqual({version:1,name:'summary-source.txt',mimeType:'text/plain',size:Buffer.byteLength(contents),sha256:createHash('sha256').update(contents).digest('hex'),reference:expect.stringMatching(/^b1:[a-f0-9-]{36}$/)});expect(JSON.stringify(retained)).not.toContain('PRIVATE OMIT');await expect(page.getByText('Summary note saved',{exact:true})).toBeVisible();await page.reload();expect(await notes(page)).toEqual(retained);await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Reviewed garden summary',exact:true}).click();await expect(page.getByRole('button',{name:'Source document linked',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Source document linked',exact:true}).click();const source=page.getByRole('dialog',{name:'Note source document'});await source.getByRole('button',{name:'Open linked source',exact:true}).click();const preview=page.getByRole('dialog',{name:'Reviewed attachment'});await expect(preview).toContainText(contents);await preview.getByRole('button',{name:'Done',exact:true}).click();
 await page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles'),row=(await f.list({})).entries[0];await f.rename({id:row.id,expectedRevision:row.revision,name:'renamed-source.txt'});});
 await source.getByRole('button',{name:'Open linked source',exact:true}).click();await expect(preview).toContainText('renamed-source.txt');await expect(preview).toContainText(contents);await preview.getByRole('button',{name:'Done',exact:true}).click();
 await page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');const f=registerPlugin<any>('AlphaFiles'),row=(await f.list({})).entries[0];await f.delete({id:row.id,expectedRevision:row.revision,confirmPermanent:true});});
 await source.getByRole('button',{name:'Open linked source',exact:true}).click();await expect(source.getByRole('status')).toContainText('access is unavailable');await expect(preview).toHaveCount(0);expect(await notes(page)).toEqual(retained);

});
test('save refusal cannot turn into repeated note creation from the same answer',async({page})=>{
 await setup(page);await page.getByText('Review summary note',{exact:true}).click();await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(key==='alpha.browser.notes.v1')throw new DOMException('Full','QuotaExceededError');return original.call(this,value,key);};});const review=page.getByRole('dialog',{name:'Save reviewed summary note'});await review.getByRole('button',{name:'Save reviewed note',exact:true}).click();await expect(review.getByRole('status')).toContainText('Save is unconfirmed');await expect(review.getByRole('button',{name:'Save reviewed note',exact:true})).toBeDisabled();expect(await notes(page)).toEqual([]);await review.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByText('Review summary note',{exact:true})).toHaveCount(0);await expect(page.getByText('Check Notes before retrying',{exact:true})).toBeVisible();
});
test('an agent change during summary review refuses saving',async({page})=>{
 await setup(page);await page.getByText('Review summary note',{exact:true}).click();await page.evaluate(async()=>{const{connectionController:c}=await import('/src/runtime/connection-ui.tsx');const snapshot=c.getSnapshot();c.getSnapshot=()=>({...snapshot,session:{...snapshot.session,sessionId:'replaced-session'}} as any);});const review=page.getByRole('dialog',{name:'Save reviewed summary note'});await review.getByRole('button',{name:'Save reviewed note',exact:true}).click();await expect(review.getByRole('status')).toContainText('Agent or conversation changed');expect(await notes(page)).toEqual([]);
});
test('unverifiable source can be explicitly omitted without blocking the reviewed question',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const{reviewContentQuestion}=await import('/src/browser/content-question.ts');(window as any).sourceOptOut=null;reviewContentQuestion({name:'large-document.txt',text:'Reviewed excerpt',current:()=>true,source:async()=>{throw Error('Over attachment limit');},compose:(text,source)=>(window as any).sourceOptOut={text,source:source??null}});});
 const review=page.getByRole('dialog',{name:'Ask about selected content'});await review.getByRole('button',{name:'Use in conversation',exact:true}).click();await expect(review.getByRole('status')).toContainText('turn off the source link');await review.getByRole('checkbox').uncheck();await review.getByRole('textbox',{name:'Content excerpt'}).fill('Edited excerpt');await review.getByRole('button',{name:'Use in conversation',exact:true}).click();await expect(review).toHaveCount(0);expect(await page.evaluate(()=>(window as any).sourceOptOut)).toEqual({text:'Summarize this excerpt.\n\nSource: large-document.txt\n\nEdited excerpt',source:null});
});

test('older document bridges retain fingerprint-only summary saving',async({page})=>{
 await setup(page,true);await page.getByText('Review summary note',{exact:true}).click();const review=page.getByRole('dialog',{name:'Save reviewed summary note'});await expect(review).toContainText('requires choosing matching file bytes');await review.getByRole('button',{name:'Save reviewed note',exact:true}).click();await expect(review).toHaveCount(0);const saved=await notes(page);expect(saved).toHaveLength(1);expect(saved[0].documentSource.sha256).toBe(createHash('sha256').update(contents).digest('hex'));expect(saved[0].documentSource.reference).toBeUndefined();
});
