import {test,expect} from '@playwright/test';
// Synthetic camera/microphone sources; real MediaRecorder, codecs and IndexedDB.
test.beforeEach(async({page},info)=>{
 if(/cancellation settles held audio startup|encoder startup failure|video export falls back/.test(info.title))await page.addInitScript(()=>{(window as any).VideoEncoder=undefined;});
 await page.addInitScript(()=>{
  localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));
  const state=(window as any).videoTest={streams:[] as MediaStream[],audioCalls:0,held:false,deny:false};
  const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;const context=canvas.getContext('2d')!;let n=0;setInterval(()=>{context.fillStyle=n++%2?'#2266aa':'#aa6622';context.fillRect(0,0,320,240);},50);
  Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async (constraints:MediaStreamConstraints)=>{
   if(constraints?.audio){state.audioCalls++;if(state.deny)throw new DOMException('Denied','NotAllowedError');if(state.held)await new Promise<void>(resolve=>{state.release=resolve;});const ac=new AudioContext(),osc=ac.createOscillator(),out=ac.createMediaStreamDestination();osc.connect(out);osc.start();await ac.resume();state.audioContext=ac;state.streams.push(out.stream);return out.stream;}
   const stream=canvas.captureStream(20);state.streams.push(stream);return stream;
  }}});
 });
 await page.goto('/');await page.getByRole('button',{name:'Camera',exact:true}).click();await expect.poll(()=>page.locator('[aria-label^="Viewfinder."] video').evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);
});
async function record(page:any){return page.evaluate(async()=>{const {browserCamera,browserPhotoLibrary}=await import('/src/prototype/browser-camera.ts');await browserCamera.startRecording({audio:true,maxDuration:1.5,maxFileSize:1000000});await new Promise(r=>setTimeout(r,1700));await browserCamera.stopRecording();return (await browserPhotoLibrary.list()).items[0];});}
test('trimmed rotated copy retains audio, original bytes and exactly one receipt after reload',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async(source)=>{const {browserPhotoLibrary:photos}=await import('/src/prototype/browser-camera.ts');const operationId=crypto.randomUUID(),input={id:source.id,revision:source.mutationRevision,operationId,edit:{start:.2,end:1,rotation:90,crop:true}};const first=await photos.saveVideoCopy(input,new AbortController().signal),again=await photos.saveVideoCopy(input,new AbortController().signal);const rows=(await photos.list()).items,copy=rows.find(r=>r.id===first.id)!;const video=document.createElement('video');video.muted=true;video.src=copy.path!;document.body.append(video);await video.play();const tracks=typeof (video as any).captureStream==='function'?(video as any).captureStream().getTracks().map((t:MediaStreamTrack)=>t.kind):null;const decodedWidth=video.videoWidth;video.pause();video.remove();const ac=new AudioContext(),buffer=await ac.decodeAudioData(await(await fetch(copy.path!)).arrayBuffer());const samples=buffer.getChannelData(0);const rms=Math.sqrt(samples.reduce((sum,n)=>sum+n*n,0)/samples.length);await ac.close();return {rms,decodedWidth,decodedDuration:buffer.duration,first,again,count:rows.length,original:rows.find(r=>r.id===source.id)!.path===source.path,copy:{width:copy.width,height:copy.height,duration:copy.duration},tracks};},source);
 expect(result.rms).toBeGreaterThan(.05);expect(result.decodedDuration).toBeGreaterThan(.6);expect(result.decodedDuration).toBeLessThan(.9);expect(result.first.status).toBe('saved');expect(result.again).toEqual(result.first);expect(result.count).toBe(2);expect(result.original).toBe(true);expect(result.copy.width).toBeLessThan(result.copy.height);expect(result.copy.duration).toBeCloseTo(.8);expect(result.decodedWidth).toBeGreaterThan(0);if(result.tracks)expect(result.tracks.sort()).toEqual(['audio','video']);await page.reload();expect(await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return (await p.list()).items.length;})).toBe(2);
});
test('cancelled encoding and stale source cannot commit video copies',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async(source)=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');const support=VideoEncoder.isConfigSupported;let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);VideoEncoder.isConfigSupported=async config=>{started();await gate;return support.call(VideoEncoder,config);};const controller=new AbortController(),operationId=crypto.randomUUID();const pending=p.saveVideoCopy({id:source.id,revision:source.mutationRevision,operationId,edit:{start:0,end:1.2,rotation:90,crop:false}},controller.signal);await ready;controller.abort();try{await pending;}catch{}finally{VideoEncoder.isConfigSupported=support;release();}const receipt=await p.editResult({operationId});await p.setFavorite({id:source.id,revision:source.mutationRevision,favorite:true});let stale=false;try{await p.saveVideoCopy({id:source.id,revision:source.mutationRevision,operationId:crypto.randomUUID(),edit:{start:0,end:1,rotation:0,crop:false}},new AbortController().signal);}catch{stale=true;}return {receipt,stale,count:(await p.list()).items.length};},source);expect(result.receipt.status).not.toBe('saved');expect(result.stale).toBe(true);expect(result.count).toBe(1);
});
test('rendered Photos edit opens trim controls and saves a playable video copy',async({page},info)=>{
 await record(page);await page.reload();await page.getByRole('button',{name:'Photos',exact:true}).click();await page.getByRole('button',{name:/Captured video/}).first().click();await page.getByRole('button',{name:'Edit photo',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit video'});await expect(dialog).toBeVisible();await dialog.getByLabel('Start seconds').fill('0.2');await dialog.getByLabel('End seconds').fill('1');await dialog.getByRole('button',{name:'Rotate video',exact:true}).click();await expect.poll(()=>dialog.locator('canvas').evaluate((c:HTMLCanvasElement)=>{const data=c.getContext('2d')!.getImageData(Math.floor(c.width/2),Math.floor(c.height/2),1,1).data;return data[0]+data[1]+data[2];})).toBeGreaterThan(50);await page.screenshot({path:info.outputPath('video-editor.png')});await dialog.getByRole('button',{name:'Save video copy',exact:true}).click();await expect(dialog).toHaveCount(0);await expect.poll(()=>page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return (await p.list()).items.length;})).toBe(2);
});
test('failed copy transaction leaves original and a failed receipt without publishing media',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async(source)=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(value:any,key?:IDBValidKey){if(this.name==='photos'&&value.kind==='video'&&value.id!==source.id)throw new DOMException('Quota','QuotaExceededError');return add.call(this,value,key);};const operationId=crypto.randomUUID();let failed=false;try{await p.saveVideoCopy({id:source.id,revision:source.mutationRevision,operationId,edit:{start:0,end:.5,rotation:90,crop:false}},new AbortController().signal);}catch{failed=true;}finally{IDBObjectStore.prototype.add=add;}return {failed,receipt:await p.editResult({operationId}),rows:(await p.list()).items.map(r=>r.id)};},source);expect(result.failed).toBe(true);expect(result.receipt.status).toBe('failed');expect(result.rows).toEqual([source.id]);
});
for(const event of ['alpha-back','pagehide','launcher-home'])test(`video review retires pending save on ${event}`,async({page})=>{
 const source=await record(page);await page.reload();await page.getByRole('button',{name:'Photos',exact:true}).click();await page.getByRole('button',{name:/Captured video/}).first().click();await page.getByRole('button',{name:'Edit photo',exact:true}).click();await page.getByRole('dialog',{name:'Edit video'}).getByRole('button',{name:'Save video copy',exact:true}).click();await page.evaluate(event=>window.dispatchEvent(new Event(event,{cancelable:true})),event);await expect(page.getByRole('dialog',{name:'Edit video'})).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>localStorage.getItem('alpha.photos.pending-copy.v1'))).toBeNull();expect(await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return (await p.list()).items.map(r=>r.id);})).toEqual([source.id]);
});
test('reload recovery retires an interrupted operation and never resumes its copy',async({page})=>{
 const source=await record(page);await page.evaluate(async(source)=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');const operationId=crypto.randomUUID();localStorage.setItem('alpha.photos.pending-copy.v1',operationId);const original=VideoEncoder.isConfigSupported;VideoEncoder.isConfigSupported=()=>new Promise(()=>{});void p.saveVideoCopy({id:source.id,revision:source.mutationRevision,operationId,edit:{start:0,end:1,rotation:90,crop:false}},new AbortController().signal).catch(()=>{});(window as any).restoreCodecSupport=()=>VideoEncoder.isConfigSupported=original;},source);await expect.poll(()=>page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('alpha.browser.photos.v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return new Promise<string>(resolve=>{const tx=db.transaction('photos'),r=tx.objectStore('photos').get('edit:'+localStorage.getItem('alpha.photos.pending-copy.v1'));r.onsuccess=()=>{resolve(r.result?.status||'');db.close();};});})).toBe('saving');await page.reload();await page.getByRole('button',{name:'Photos',exact:true}).click();await expect.poll(()=>page.evaluate(()=>localStorage.getItem('alpha.photos.pending-copy.v1'))).toBeNull();expect(await page.evaluate(async()=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return (await p.list()).items.map(r=>r.id);})).toEqual([source.id]);
});
test('cancellation settles held audio startup and releases the encoding stream',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async(source)=>{const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');const resume=AudioContext.prototype.resume,close=AudioContext.prototype.close;const capture=HTMLCanvasElement.prototype.captureStream,streams:MediaStream[]=[];HTMLCanvasElement.prototype.captureStream=function(rate){const stream=capture.call(this,rate);streams.push(stream);return stream;};let started!:()=>void,closed=0;const ready=new Promise<void>(resolve=>started=resolve);AudioContext.prototype.resume=function(){started();return new Promise<void>(()=>{});};AudioContext.prototype.close=function(){closed++;return close.call(this);};const controller=new AbortController(),operationId=crypto.randomUUID();const pending=p.saveVideoCopy({id:source.id,revision:source.mutationRevision,operationId,edit:{start:0,end:1,rotation:90,crop:false}},controller.signal).then(()=>false,()=>true);await ready;controller.abort();const cancelled=await pending;AudioContext.prototype.resume=resume;AudioContext.prototype.close=close;HTMLCanvasElement.prototype.captureStream=capture;return {streamsEnded:streams.length>0&&streams.every(s=>s.getTracks().every(t=>t.readyState==='ended')),cancelled,closed,receipt:await p.editResult({operationId}),count:(await p.list()).items.length};},source);expect(result.cancelled).toBe(true);expect(result.closed).toBe(1);expect(result.streamsEnded).toBe(true);expect(result.receipt.status).toBe('failed');expect(result.count).toBe(1);
});

test('encoder startup failure clears its deadline and releases every output track',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async(source)=>{
  const {renderVideoEdit}=await import('/src/browser/video-edit.ts');
  const start=MediaRecorder.prototype.start,capture=HTMLCanvasElement.prototype.captureStream,set=window.setTimeout,clear=window.clearTimeout;
  const deadlines=new Set<number>(),streams:MediaStream[]=[];
  window.setTimeout=((fn:TimerHandler,delay?:number,...args:any[])=>{const id=set(fn,delay,...args);if(delay&&delay>15000)deadlines.add(id);return id;}) as typeof set;
  window.clearTimeout=(id)=>{deadlines.delete(id!);clear(id);};
  HTMLCanvasElement.prototype.captureStream=function(rate){const stream=capture.call(this,rate);streams.push(stream);return stream;};
  MediaRecorder.prototype.start=function(){throw new DOMException('Encoder unavailable','NotSupportedError');};
  let failed=false;try{await renderVideoEdit({path:source.path!,duration:source.duration!},{start:0,end:1,rotation:0,crop:false},new AbortController().signal);}catch{failed=true;}
  finally{MediaRecorder.prototype.start=start;HTMLCanvasElement.prototype.captureStream=capture;window.setTimeout=set;window.clearTimeout=clear;}
  const pending=deadlines.size;for(const id of deadlines)clear(id);
  return {failed,pending,ended:streams.length>0&&streams.every(s=>s.getTracks().every(t=>t.readyState==='ended'))};
 },source);expect(result.failed).toBe(true);expect(result.ended).toBe(true);expect(result.pending).toBe(0);
});

for(const failure of ['support','constructor','start'])test(`video export falls back after codec ${failure} failure`,async({page})=>{
 const source=await record(page);const result=await page.evaluate(async({source,failure})=>{
  const {renderVideoEdit}=await import('/src/browser/video-edit.ts');const Original=MediaRecorder;const attempts:string[]=[];let rejected=false;
  (window as any).MediaRecorder=class extends Original{
   static isTypeSupported(type:string){return failure==='support'?false:Original.isTypeSupported(type);}
   constructor(stream:MediaStream,options?:MediaRecorderOptions){attempts.push(options?.mimeType||'default');if(failure==='constructor'&&options?.mimeType)throw new DOMException('Codec allocation failed','NotSupportedError');super(stream,options);}
   start(timeslice?:number){if(failure==='start'&&!rejected){rejected=true;throw new DOMException('Codec startup failed','NotSupportedError');}super.start(timeslice);}
  };
  try{const copy=await renderVideoEdit({path:source.path!,duration:source.duration!},{start:0,end:.5,rotation:90,crop:false},new AbortController().signal);const video=document.createElement('video');video.muted=true;video.src=copy.path;document.body.append(video);await video.play();const decoded={width:video.videoWidth,height:video.videoHeight};video.pause();video.remove();return {attempts,decoded,type:copy.path.split(';')[0]};}finally{(window as any).MediaRecorder=Original;}
 },{source,failure});
 expect(result.decoded.width).toBe(240);expect(result.decoded.height).toBe(320);expect(result.type).toMatch(/^data:video\/(webm|mp4)$/);if(failure==='start')expect(result.attempts.length).toBeGreaterThan(1);else expect(result.attempts.at(-1)).toBe('default');
});

test('delayed playback acknowledgement does not discard the selected opening audio',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async(source)=>{const {renderVideoEdit}=await import('/src/browser/video-edit.ts');const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){return play.call(this).then(()=>new Promise<void>(resolve=>setTimeout(resolve,400)));};try{const copy=await renderVideoEdit({path:source.path!,duration:source.duration!},{start:0,end:.8,rotation:0,crop:false},new AbortController().signal);const audio=new AudioContext();try{const buffer=await audio.decodeAudioData(await(await fetch(copy.path)).arrayBuffer());return {duration:buffer.duration};}finally{await audio.close();}}finally{HTMLMediaElement.prototype.play=play;}},source);expect(result.duration).toBeGreaterThan(.65);expect(result.duration).toBeLessThan(.9);
});

test('unsupported timestamp encoder falls back without dropping source audio',async({page})=>{
 const warnings:string[]=[];page.on('console',message=>{if(message.type()==='warning')warnings.push(message.text());});
 const source=await record(page);const result=await page.evaluate(async source=>{const {renderVideoEdit}=await import('/src/browser/video-edit.ts'),support=VideoEncoder.isConfigSupported;VideoEncoder.isConfigSupported=async config=>({supported:false,config});try{const copy=await renderVideoEdit({path:source.path!,duration:source.duration!},{start:0,end:.8,rotation:90,crop:false},new AbortController().signal),audio=new AudioContext();try{const buffer=await audio.decodeAudioData(await(await fetch(copy.path)).arrayBuffer()),samples=buffer.getChannelData(0);return {width:copy.width,height:copy.height,rms:Math.sqrt(samples.reduce((s,n)=>s+n*n,0)/samples.length)};}finally{await audio.close();}}finally{VideoEncoder.isConfigSupported=support;}},source);expect(result.width).toBe(240);expect(result.height).toBe(320);expect(result.rms).toBeGreaterThan(.05);expect(warnings.filter(message=>message.includes('discarded'))).toEqual([]);
});


test('legacy untyped recordings remain editable without changing their stored original',async({page})=>{
 const source=await record(page);const result=await page.evaluate(async source=>{
  const {renderVideoEdit}=await import('/src/browser/video-edit.ts');const legacy=source.path!.replace(/^data:video\/(?:webm|mp4);base64,/, 'data:application/octet-stream;base64,');
  const copy=await renderVideoEdit({path:legacy,duration:source.duration!},{start:0,end:.5,rotation:90,crop:false},new AbortController().signal);
  const video=document.createElement('video');video.muted=true;video.src=copy.path;document.body.append(video);await video.play();const width=video.videoWidth;video.pause();video.remove();
  let rejected=false;try{await renderVideoEdit({path:'data:application/octet-stream;base64,'+btoa('<html>not video</html>'),duration:1},{start:0,end:.5,rotation:0,crop:false},new AbortController().signal);}catch{rejected=true;}
  const {browserPhotoLibrary:p}=await import('/src/prototype/browser-camera.ts');return {width,rejected,unchanged:(await p.list()).items[0].path===source.path,prefix:copy.path.split(';')[0]};
 },source);expect(result).toEqual({width:240,rejected:true,unchanged:true,prefix:expect.stringMatching(/^data:video\/(webm|mp4)$/)});
});
