import {test,expect,type Page} from '@playwright/test';
async function audio(page:Page){await page.evaluate(()=>{const w=window as any;w.voiceSave={sources:[],chunks:0,writes:0,held:false,settled:false};const devices=navigator.mediaDevices;Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:devices});devices.getUserMedia=async()=>{const context=new AudioContext(),osc=context.createOscillator(),sink=context.createMediaStreamDestination();osc.connect(sink);osc.start();await context.resume();w.voiceSave.sources.push({context,osc,stream:sink.stream});return sink.stream;};const Original=MediaRecorder;w.MediaRecorder=class extends Original{constructor(stream:MediaStream,options?:MediaRecorderOptions){super(stream,options);this.addEventListener('dataavailable',e=>{if(e.data.size)w.voiceSave.chunks++;});}};});}
async function review(page:Page){await page.getByRole('button',{name:'Record without transcription',exact:true}).click();const previous=await page.evaluate(()=>(window as any).voiceSave.chunks);await page.getByRole('button',{name:'Start recording',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).voiceSave.chunks)).toBeGreaterThan(previous);await page.getByRole('button',{name:'Stop recording',exact:true}).click();await page.getByRole('button',{name:'Review transcript',exact:true}).click();await expect(page.getByRole('textbox',{name:'Review transcript'})).toBeVisible();}
for(const destination of ['new','dictation'] as const)for(const outcome of ['success','failure'] as const){test(`late ${destination} save ${outcome} preserves replacement recording`,async({page})=>{
 await page.goto('/?mode=dev');await audio(page);await page.getByRole('button',{name:'Notes',exact:true}).click();
 if(destination==='dictation'){await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Original target');await page.getByRole('textbox',{name:'Note',exact:true}).fill('Original body');await page.getByRole('button',{name:'Dictate',exact:true}).click();}else await page.getByRole('button',{name:'Record and transcribe',exact:true}).click();
 await review(page);await page.getByRole('textbox',{name:'Review transcript'}).fill('Old reviewed transcript');
 await page.evaluate(async(outcome)=>{const {NotesStore}=await import('/src/runtime/notes-store.ts');const original=NotesStore.prototype.replace;NotesStore.prototype.replace=function(...args:any[]){const w=window as any;w.voiceSave.writes++;const result=original.apply(this,args as any);if(w.voiceSave.held)return result;w.voiceSave.held=true;return new Promise<void>((resolve,reject)=>{w.voiceSave.release=()=>{outcome==='failure'?reject(Error('Synthetic lost storage response')):resolve();};}).finally(()=>{w.voiceSave.settled=true;});} as any;},outcome);
 await page.getByRole('button',{name:destination==='dictation'?'Apply transcript':'Save note',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).voiceSave.held)).toBe(true);
 await page.getByRole('button',{name:'Discard recording',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Record and transcribe',exact:true}).click();
 if(outcome==='failure'){await review(page);await page.getByRole('textbox',{name:'Review transcript'}).fill('New session transcript');}else{await page.getByRole('button',{name:'Record without transcription',exact:true}).click();await page.getByRole('button',{name:'Start recording',exact:true}).click();await expect(page.getByRole('button',{name:'Stop recording',exact:true})).toBeVisible();}
 await page.evaluate(async()=>{const w=window as any;w.voiceSave.release();await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await expect.poll(()=>page.evaluate(()=>(window as any).voiceSave.settled)).toBe(true);
 if(outcome==='failure'){await expect(page.getByRole('textbox',{name:'Review transcript'})).toHaveValue('New session transcript');await expect(page.getByText('The note save is unconfirmed. The recording and transcript are retained; inspect saved Notes before saving again.',{exact:true})).toHaveCount(0);await expect(page.getByText('The note save is unconfirmed. Your transcript is retained; inspect saved Notes before applying again.',{exact:true})).toHaveCount(0);}else{await expect(page.getByRole('button',{name:'Stop recording',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).voiceSave.sources.at(-1).stream.getTracks().every((t:MediaStreamTrack)=>t.readyState==='live'))).toBe(true);}
 expect(await page.evaluate(()=>(window as any).voiceSave.writes)).toBe(1);const notes=await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records);expect(notes.filter((n:any)=>n.body.includes('Old reviewed transcript'))).toHaveLength(1);
 await page.getByRole('button',{name:'Discard recording',exact:true}).click();await page.evaluate(async()=>{for(const s of (window as any).voiceSave.sources){s.osc.stop();await s.context.close();}});
});}
for(const destination of ['new','dictation'] as const)for(const outcome of ['success','failure'] as const){test(`owned ${destination} save ${outcome} retains the reviewed transcript`,async({page})=>{
 await page.goto('/?mode=dev');await audio(page);await page.getByRole('button',{name:'Notes',exact:true}).click();
 if(destination==='dictation'){await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Note',exact:true}).fill('Before ');await page.getByRole('button',{name:'Dictate',exact:true}).click();}else await page.getByRole('button',{name:'Record and transcribe',exact:true}).click();
 await review(page);const editor=page.getByRole('textbox',{name:'Review transcript'});await editor.fill('Reviewed retained words');
 await page.evaluate(async(outcome)=>{const {NotesStore}=await import('/src/runtime/notes-store.ts');const original=NotesStore.prototype.replace;NotesStore.prototype.replace=function(...args:any[]){const w=window as any;w.voiceSave.writes++;original.apply(this,args as any);w.voiceSave.held=true;return new Promise<void>((resolve,reject)=>{w.voiceSave.release=()=>{outcome==='failure'?reject(Error('Synthetic lost response')):resolve();};});} as any;},outcome);
 const commit=page.getByRole('button',{name:destination==='dictation'?'Apply transcript':'Save note',exact:true});await commit.click();await expect.poll(()=>page.evaluate(()=>(window as any).voiceSave.held)).toBe(true);await expect(commit).toBeDisabled();await expect(editor).toBeDisabled();
 await page.evaluate(async()=>{(window as any).voiceSave.release();await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});
 if(outcome==='success'){await expect(editor).toHaveCount(0);}else{await expect(editor).toBeEnabled();await expect(editor).toHaveValue('Reviewed retained words');await expect(page.getByText(destination==='dictation'?'The note save is unconfirmed. Your transcript is retained; inspect saved Notes before applying again.':'The note save is unconfirmed. The recording and transcript are retained; inspect saved Notes before saving again.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Discard recording',exact:true}).click();}
 expect(await page.evaluate(()=>(window as any).voiceSave.writes)).toBe(1);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.filter((n:any)=>n.body.includes('Reviewed retained words')).length)).toBe(1);await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')!).records.filter((n:any)=>n.body.includes('Reviewed retained words')).length)).toBe(1);
});}
