import {installCloudVoiceFixture} from './cloud-voice-fixture';
import { returnToApps } from './app-navigation';
import {test,expect} from '@playwright/test';
async function source(page:any){await page.evaluate(async()=>{const context=new AudioContext(),osc=context.createOscillator(),gain=context.createGain(),sink=context.createMediaStreamDestination();gain.gain.value=.1;osc.connect(gain);gain.connect(sink);osc.start();await context.resume();const devices=navigator.mediaDevices;Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:devices});devices.getUserMedia=async()=>sink.stream;(window as any).levelSource={context,osc,gain,stream:sink.stream};const Original=AudioContext;(window as any).meterContexts=[];(window as any).AudioContext=class extends Original{constructor(){super();(window as any).meterContexts.push(this);}createMediaStreamSource(stream:MediaStream){(this as any).meter=true;return super.createMediaStreamSource(stream);}};});}
test('rendered voice bars follow actual microphone amplitude and leaving the recorder closes metering',async({page})=>{
 await page.goto('/?mode=dev');await installCloudVoiceFixture(page);await source(page);await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Record and transcribe',exact:true}).click();await page.getByRole('button',{name:'Start recording',exact:true}).click();
 const bars=page.getByRole('img',{name:'Microphone levels'}).locator('span');await expect(bars).toHaveCount(44);await expect.poll(()=>bars.evaluateAll(items=>Math.max(...items.map(item=>parseFloat((item as HTMLElement).style.height))))).toBeGreaterThan(8);
 await page.evaluate(()=>(window as any).levelSource.gain.gain.value=0);await expect.poll(()=>bars.evaluateAll(items=>Math.max(...items.map(item=>parseFloat((item as HTMLElement).style.height))))).toBe(4);
 await page.getByRole('button',{name:'Discard recording',exact:true}).click();await returnToApps(page);await expect.poll(()=>page.evaluate(()=>(window as any).meterContexts.filter((ctx:any)=>ctx.meter).every((ctx:AudioContext)=>ctx.state==='closed'))).toBe(true);expect(await page.evaluate(()=>(window as any).levelSource.stream.getTracks().every((track:MediaStreamTrack)=>track.readyState==='ended'))).toBe(true);await page.evaluate(async()=>{const s=(window as any).levelSource;s.osc.stop();await s.context.close();});
});
test('stopping a browser recording retires its meter and retains playable clip bytes',async({page})=>{
 await page.goto('/?mode=dev');await installCloudVoiceFixture(page);await source(page);await page.evaluate(()=>{const Recorder=MediaRecorder;(window as any).recordedLevelBytes=0;(window as any).MediaRecorder=class extends Recorder{constructor(stream:MediaStream,options?:MediaRecorderOptions){super(stream,options);this.addEventListener('dataavailable',event=>{(window as any).recordedLevelBytes+=event.data.size;});}};});const id=await page.evaluate(async()=>{const {BrowserAudioCapture}=await import('/src/browser/audio-capture.ts');const capture=(window as any).levelCapture=new BrowserAudioCapture(()=>{});return (await capture.start()).recordingId;});await expect.poll(()=>page.evaluate(async id=>{const {recordingLevels}=await import('/src/browser/audio-levels.ts');return Math.max(...recordingLevels(id).map(v=>v.h));},id)).toBeGreaterThan(8);
 // Meter readiness can precede the encoder's first chunk on hosted Chromium.
 await expect.poll(()=>page.evaluate(()=>(window as any).recordedLevelBytes)).toBeGreaterThan(0);
 const result=await page.evaluate(async id=>{const capture=(window as any).levelCapture;await capture.stop();const {recordingLevels}=await import('/src/browser/audio-levels.ts');const s=(window as any).levelSource;s.osc.stop();await s.context.close();return {levels:recordingLevels(id).map(v=>v.h),bytes:capture.get(id).blob.size};},id);expect(result.levels).toEqual(Array(44).fill(4));expect(result.bytes).toBeGreaterThan(0);await expect.poll(()=>page.evaluate(()=>(window as any).meterContexts.filter((ctx:any)=>ctx.meter).every((ctx:AudioContext)=>ctx.state==='closed'))).toBe(true);
});
