import {test,expect} from '@playwright/test';
import {cloudNotesVoiceFixture,notesRecorder,openNotesRecorder,recordClosedClip,noPhysicalOrLocalVoice} from './cloud-notes-voice-fixture';
for(const development of [false,true])test(`unsigned Cloud conversation connects its account without Notes or microphone: ${development?'development':'normal'} browser`,async({page})=>{
 const f=await cloudNotesVoiceFixture(page,false,development);await page.getByRole('button',{name:'Talk',exact:true}).click();const voice=page.getByRole('region',{name:'Voice conversation',exact:true});await expect(voice).toBeVisible();await expect(page.locator('[data-alpha-subview="notes-recording"]')).toHaveCount(0);await expect(voice.getByRole('button',{name:'Connect Eliza Cloud',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:/Record without transcription|Use on-device voice|Use browser voice/})).toHaveCount(0);
 await voice.getByRole('button',{name:'Connect Eliza Cloud',exact:true}).click();await expect(page.getByRole('dialog',{name:'Eliza Cloud',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Sign in with Eliza Cloud',exact:true})).toBeVisible();await noPhysicalOrLocalVoice(page);expect(await page.evaluate(()=>(window as any).cloudNotesVoice.starts)).toBe(0);expect(f.foreign).toEqual([]);
 await page.getByRole('button',{name:'Close Cloud account',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Models',exact:true}).click();await expect(page.getByText('Conversation uses the selected agent. Voice uses Eliza Cloud.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Check on-device speech',exact:true})).toHaveCount(0);
});
test('Cloud Notes recorder uses the official microphone and requires explicit upload and retry',async({page})=>{
 const f=await cloudNotesVoiceFixture(page,true,true);await openNotesRecorder(page);const panel=notesRecorder(page),start=panel.getByRole('button',{name:'Start recording',exact:true});await expect(start).toBeEnabled();await expect(start.locator('[data-alpha-icon]')).toHaveAttribute('data-alpha-icon','/icons/lucide/mic.svg');expect(await start.locator('[data-alpha-icon]').evaluate(icon=>getComputedStyle(icon).maskImage)).toContain('/icons/lucide/mic.svg');await recordClosedClip(page);expect(await page.evaluate(()=>(window as any).cloudNotesVoice.uploads)).toBe(0);await page.evaluate(()=>(window as any).cloudNotesVoice.billing=true);await panel.getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();await expect(panel).toContainText('Add credits in Settings');await page.evaluate(()=>(window as any).cloudNotesVoice.billing=false);await panel.getByRole('button',{name:'Transcribe with Eliza Cloud',exact:true}).click();await expect(panel.getByRole('textbox',{name:'Review transcript',exact:true})).toHaveValue('Closed Cloud transcript');expect(await page.evaluate(()=>{const f=(window as any).cloudNotesVoice;return {uploads:f.uploads,environment:f.requests[0].environment,credentialId:f.requests[0].credentialId};})).toEqual({uploads:2,environment:'production',credentialId:'fixture-credential-a'});await noPhysicalOrLocalVoice(page);expect(f.foreign).toEqual([]);
});
