import {test,expect,type Page} from '@playwright/test';
const url='https://public-fixture.test/garden',html='<article><h1>Garden report</h1><p>Twelve raised beds are open.</p><p>OMIT THIS: internal planning detail.</p></article>';
async function setup(page:Page,body=html){
 await page.route(url,r=>r.fulfill({contentType:'text/html',headers:{'access-control-allow-origin':'*'},body}));
 await page.goto('/?mode=dev');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Browser',exact:true}).click();await page.getByRole('button',{name:'Search or type address',exact:true}).click();await page.getByRole('textbox',{name:'Address',exact:true}).fill(url);await page.getByRole('textbox',{name:'Address',exact:true}).press('Enter');await expect(page.frameLocator('iframe[title="Website"]').locator('article')).toBeVisible();
}
async function ask(page:Page){await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'Ask about page',exact:true}).click();return page.getByRole('dialog',{name:'Ask about selected content'});}
async function notes(page:Page){return page.evaluate(()=>JSON.parse(localStorage.getItem('alphaphone:notes:v2')||'{"records":[]}').records);}
test('page excerpt becomes a reviewed summary note and reopens its durable web source',async({page},info)=>{
 await setup(page);const review=await ask(page);await expect(review.getByRole('textbox',{name:'Content excerpt'})).toHaveValue(/Twelve raised beds/);
 await review.getByRole('textbox',{name:'Content excerpt'}).fill('Twelve raised beds are open.');await page.screenshot({path:info.outputPath('page-question.png')});await review.getByRole('button',{name:'Use in conversation',exact:true}).click();expect(await notes(page)).toEqual([]);await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByText('Review summary note',{exact:true}).click();const summary=page.getByRole('dialog',{name:'Save reviewed summary note'});await expect(summary).toContainText('contents may have changed');await summary.getByRole('textbox',{name:'Summary note title'}).fill('Garden summary');await summary.getByRole('textbox',{name:'Summary note text'}).fill('The garden has twelve raised beds.');await summary.getByRole('button',{name:'Save reviewed note',exact:true}).click();await expect(summary).toHaveCount(0);const saved=await notes(page);expect(saved).toHaveLength(1);expect(saved[0].webSource).toMatchObject({kind:'web-page',version:1,url});expect(saved[0].documentSource).toBeUndefined();expect(saved[0].body).toBe('The garden has twelve raised beds.');expect(JSON.stringify(saved)).not.toContain('OMIT THIS');
 await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Garden summary',exact:true}).click();await page.getByRole('button',{name:'Web source linked',exact:true}).click();const source=page.getByRole('dialog',{name:'Note web source'});await expect(source).toContainText(url);await page.screenshot({path:info.outputPath('web-source.png')});await source.getByRole('button',{name:'Open source page',exact:true}).click();await expect(source).toHaveCount(0);await expect(page.frameLocator('iframe[title="Website"]').getByRole('heading',{name:'Garden report'})).toBeVisible();expect(await notes(page)).toEqual(saved);
});
test('sensitive document is refused before any question editor opens',async({page})=>{
 await setup(page,'<article>Garden report</article><input type="password" value="synthetic-secret">');await ask(page);await expect(page.getByText('This page may contain credentials or verification codes. Open a different page.',{exact:true})).toBeVisible();await expect(page.getByRole('dialog',{name:'Ask about selected content'})).toHaveCount(0);expect(await notes(page)).toEqual([]);
});
test('unavailable CORS source supports explicit paste and HOME cancels the review',async({page})=>{
 await setup(page);await page.route(url,r=>r.request().resourceType()==='fetch'?r.abort():r.fulfill({contentType:'text/html',body:html}));const review=await ask(page);await expect(review.getByRole('textbox',{name:'Content excerpt'})).toHaveValue('');await expect(review.getByRole('button',{name:'Use in conversation'})).toBeDisabled();await review.getByRole('textbox',{name:'Content excerpt'}).fill('Pasted public excerpt.');await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));await expect(review).toHaveCount(0);expect(await notes(page)).toEqual([]);
});
test('HOME while fetching retires the page question instead of opening a stale review',async({page})=>{
 await setup(page);let release!:()=>void;const gate=new Promise<void>(r=>release=r);let requested=false;await page.route(url,async r=>{if(r.request().resourceType()==='fetch'){requested=true;await gate;}await r.fulfill({contentType:'text/html',headers:{'access-control-allow-origin':'*'},body:html}).catch(()=>{});});await ask(page);await expect.poll(()=>requested).toBe(true);await page.evaluate(()=>window.dispatchEvent(new Event('launcher-home')));release();await expect(page.getByRole('button',{name:'Browser',exact:true})).toBeVisible();await expect(page.getByRole('dialog',{name:'Ask about selected content'})).toHaveCount(0);
});
test('review refuses pasted credentials and rejects unsafe saved source addresses',async({page})=>{
 await setup(page);const review=await ask(page);await review.getByRole('textbox',{name:'Content excerpt'}).fill('Account recovery codes: TEST-ONLY');await review.getByRole('button',{name:'Use in conversation'}).click();await expect(review.getByRole('status')).toContainText('may contain credentials');await review.getByRole('button',{name:'Cancel',exact:true}).click();
 const accepted=await page.evaluate(async()=>{const{webSourceOf}=await import('/src/prototype/summary-source.ts');return ['javascript:alert(1)','http://example.com','https://u:p@example.com','https://example.com/#/vault','https://example.com/?token=secret','https://public-fixture.test/garden'].map(url=>!!webSourceOf({kind:'web-page',version:1,name:'Source',url}));});expect(accepted).toEqual([false,false,false,false,false,true]);
});
for(const theme of ['light','dark'])test(`compact ${theme} source review keeps actions reachable and removes only its link`,async({page})=>{
 await page.setViewportSize({width:360,height:640});await page.goto('/?theme='+theme);await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Retained source note');await page.getByRole('textbox',{name:'Note',exact:true}).fill('Keep this summary');await expect.poll(async()=>(await notes(page))[0]?.body).toBe('Keep this summary');await page.evaluate(()=>{const store=JSON.parse(localStorage.getItem('alphaphone:notes:v2')!);store.records[0].webSource={kind:'web-page',version:1,name:'https://public-fixture.test/'+('longpath'.repeat(10)),url:'https://public-fixture.test/'+('longpath'.repeat(20))};localStorage.setItem('alphaphone:notes:v2',JSON.stringify(store));});await page.reload();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByRole('button',{name:'Open Retained source note',exact:true}).click();await page.getByRole('button',{name:'Web source linked',exact:true}).click();const source=page.getByRole('dialog',{name:'Note web source'});await page.evaluate(async()=>{const{BrowserDevice}=await import('/src/browser/device.ts');await BrowserDevice.prototype.setTextScale({percent:150});});await expect(source.getByRole('button',{name:'Open source page'})).toBeInViewport();await expect(source.getByRole('button',{name:'Remove web source'})).toBeInViewport();expect(await source.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await source.getByRole('button',{name:'Remove web source'}).click();await expect(source).toHaveCount(0);await page.reload();const saved=await notes(page);expect(saved).toHaveLength(1);expect(saved[0].body).toBe('Keep this summary');expect(saved[0].webSource).toBeUndefined();
});

test('a changed native-style document identity retires the pending page excerpt',async({page})=>{
 await setup(page);await page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');await registerPlugin<any>('AlphaBrowser').addListener('stateChanged',(event:any)=>(window as any).webNavigation=event);});
 await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'Reload page',exact:true}).click();await expect(page.frameLocator('iframe[title="Website"]').getByRole('heading',{name:'Garden report'})).toBeVisible();
 let release!:()=>void;const gate=new Promise<void>(r=>release=r);let requested=false;await page.route(url,async r=>{if(r.request().resourceType()==='fetch'){requested=true;await gate;}await r.fulfill({contentType:'text/html',headers:{'access-control-allow-origin':'*'},body:html}).catch(()=>{});});await page.route('https://public-fixture.test/replacement',r=>r.fulfill({contentType:'text/html',body:'<h1>Replacement document</h1>'}));
 await ask(page);await expect.poll(()=>requested).toBe(true);await page.evaluate(async()=>{const{registerPlugin}=await import('/src/platform-plugins.ts');const event=(window as any).webNavigation;await registerPlugin<any>('AlphaBrowser').navigate({session:event.session,id:event.id,url:'https://public-fixture.test/replacement'});});release();await expect(page.frameLocator('iframe[title="Website"]').getByRole('heading',{name:'Replacement document'})).toBeVisible();await expect(page.getByRole('dialog',{name:'Ask about selected content'})).toHaveCount(0);expect(await notes(page)).toEqual([]);
});
