import {test,expect,type Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>({notices:JSON.parse((await (await import('/src/browser/workflow-notices.ts')).workflowNoticesDocument.readRaw())||'{"rows":[]}').rows,runs:JSON.parse(localStorage.getItem('alpha.browser.workflows.local.v1')||'{"runs":[]}').runs,spoken:(window as any).presentation.spoken}));
for(const theme of ['light','dark'])for(const outcome of ['complete','stop'] as const)test(`typed Notify and Speak require separate approval and retain ${outcome} outcome in ${theme}`,async({page},info)=>{
 await page.setViewportSize({width:360,height:640});
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));const s=(window as any).presentation={spoken:[] as string[],current:null as any};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>[{name:'Local fixture',lang:'en-US',localService:true}],speak:(u:any)=>{s.spoken.push(u.text);s.current=u;},cancel:()=>{}});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{constructor(public text:string){}}});});
 await page.goto('/?mode=dev&workflows=agent&theme='+theme);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'New workflow',exact:true}).click();
 await page.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Presentation workflow');await page.getByRole('button',{name:'Add Read step',exact:true}).click();await page.getByRole('textbox',{name:'Text supplied to workflow',exact:true}).fill('Exact presentation text');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Add Notify step',exact:true}).click();await page.getByRole('textbox',{name:'Notification title',exact:true}).fill('Exact presentation title');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Add Speak step',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await page.getByRole('button',{name:'Review phone steps',exact:true}).click();
 const card=page.getByRole('region',{name:'Workflow phone step review'}),details=page.getByLabel('Workflow execution details',{exact:true});await expect(details).not.toHaveAttribute('open','');await expect(card).toContainText('Exact presentation title');await expect(card).toContainText('Exact presentation text');await details.locator('summary').click();await expect(details).toHaveAttribute('open','');await expect(details).toContainText('Spec:');await details.locator('summary').click();const approve=page.getByRole('button',{name:'Approve phone step',exact:true});await approve.evaluate(el=>el.scrollIntoView({block:'center'}));expect(await approve.evaluate(el=>{const r=el.getBoundingClientRect();return r.width>=200&&[r.left+6,r.left+r.width/2,r.right-6].every(x=>el.contains(document.elementFromPoint(x,r.top+r.height/2)));})).toBe(true);await page.screenshot({path:info.outputPath('compact-approval.png')});
 expect((await state(page)).notices).toEqual([]);await page.getByRole('button',{name:'Approve phone step',exact:true}).click();expect((await state(page)).notices).toEqual([]);await page.getByRole('button',{name:'Confirm phone step',exact:true}).click();await expect.poll(async()=>(await state(page)).notices.length).toBe(1);expect((await state(page)).notices[0]).toMatchObject({title:'Exact presentation title',text:'Exact presentation text'});expect((await state(page)).spoken).toEqual([]);
 await page.getByRole('button',{name:'Refresh execution receipt',exact:true}).click();await page.getByRole('button',{name:'Review phone steps',exact:true}).click();await page.getByRole('button',{name:'Approve phone step',exact:true}).click();expect((await state(page)).spoken).toEqual([]);await page.getByRole('button',{name:'Confirm phone step',exact:true}).click();await expect.poll(async()=>(await state(page)).spoken).toEqual(['Exact presentation text']);expect((await state(page)).runs[0].finished).toBe(false);
 if(outcome==='complete')await page.evaluate(async()=>(window as any).presentation.current.onend());else await page.getByRole('button',{name:'Stop workflow speech',exact:true}).click();
 await page.getByRole('button',{name:'Refresh execution receipt',exact:true}).click();
 if(outcome==='complete')await expect.poll(async()=>(await state(page)).runs[0].status).toBe('succeeded');else {expect((await state(page)).runs[0].finished).toBe(false);const journal=await page.evaluate(async()=>JSON.parse(localStorage.getItem('alpha.browser.agent.actions.local.v1')!).journal);expect(journal.filter((e:any)=>e.record.operation.type==='speak_text')).toMatchObject([{phase:'terminal',status:'unknown'}]);}
 await page.getByRole('button',{name:'Sync saved phone receipts',exact:true}).click();expect((await state(page)).spoken).toHaveLength(1);expect((await state(page)).notices).toHaveLength(1);await page.reload();expect((await state(page)).notices).toHaveLength(1);expect((await state(page)).spoken).toEqual([]);
});
