import {test,expect,type Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(()=>({notices:JSON.parse(localStorage.getItem('alpha.browser.workflow-notices.v1')||'{"rows":[]}').rows,runs:JSON.parse(localStorage.getItem('alpha.browser.workflows.local.v1')||'{"runs":[]}').runs,spoken:(window as any).presentation.spoken}));
for(const outcome of ['complete','stop'] as const)test(`typed Notify and Speak require separate approval and retain ${outcome} outcome`,async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('alpha.connection.selection.v1',JSON.stringify({kind:'offline'}));const s=(window as any).presentation={spoken:[] as string[],current:null as any};const engine=new EventTarget();Object.assign(engine,{getVoices:()=>[{name:'Local fixture',lang:'en-US',localService:true}],speak:(u:any)=>{s.spoken.push(u.text);s.current=u;},cancel:()=>{}});Object.defineProperty(window,'speechSynthesis',{value:engine});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{constructor(public text:string){}}});});
 await page.goto('/?mode=dev&workflows=agent');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Agent connection',exact:true}).click();await page.getByRole('button',{name:'Connect development profile'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'New workflow',exact:true}).click();
 await page.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Presentation workflow');await page.getByRole('button',{name:'Add Read step',exact:true}).click();await page.getByRole('textbox',{name:'Text supplied to workflow',exact:true}).fill('Exact presentation text');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Add Notify step',exact:true}).click();await page.getByRole('textbox',{name:'Notification title',exact:true}).fill('Exact presentation title');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Add Speak step',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await page.getByRole('button',{name:'Save workflow',exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await page.getByRole('button',{name:'Run now',exact:true}).click();await page.getByRole('button',{name:'Review phone steps',exact:true}).click();
 expect((await state(page)).notices).toEqual([]);await page.getByRole('button',{name:'Approve phone step',exact:true}).click();expect((await state(page)).notices).toEqual([]);await page.getByRole('button',{name:'Confirm phone step',exact:true}).click();await expect.poll(async()=>(await state(page)).notices.length).toBe(1);expect((await state(page)).notices[0]).toMatchObject({title:'Exact presentation title',text:'Exact presentation text'});expect((await state(page)).spoken).toEqual([]);
 await page.getByRole('button',{name:'Refresh execution receipt',exact:true}).click();await page.getByRole('button',{name:'Review phone steps',exact:true}).click();await page.getByRole('button',{name:'Approve phone step',exact:true}).click();expect((await state(page)).spoken).toEqual([]);await page.getByRole('button',{name:'Confirm phone step',exact:true}).click();await expect.poll(async()=>(await state(page)).spoken).toEqual(['Exact presentation text']);expect((await state(page)).runs[0].finished).toBe(false);
 if(outcome==='complete')await page.evaluate(()=>(window as any).presentation.current.onend());else await page.getByRole('button',{name:'Stop workflow speech',exact:true}).click();
 await page.getByRole('button',{name:'Refresh execution receipt',exact:true}).click();
 if(outcome==='complete')await expect.poll(async()=>(await state(page)).runs[0].status).toBe('succeeded');else {expect((await state(page)).runs[0].finished).toBe(false);const journal=await page.evaluate(()=>JSON.parse(localStorage.getItem('alpha.browser.agent.actions.local.v1')!).journal);expect(journal.filter((e:any)=>e.record.operation.type==='speak_text')).toMatchObject([{phase:'terminal',status:'unknown'}]);}
 await page.getByRole('button',{name:'Sync saved phone receipts',exact:true}).click();expect((await state(page)).spoken).toHaveLength(1);expect((await state(page)).notices).toHaveLength(1);await page.reload();expect((await state(page)).notices).toHaveLength(1);expect((await state(page)).spoken).toEqual([]);
});
