/** Product storage contracts qualified across Chromium, Firefox and WebKit. */
export const STORAGE_SPECS = Object.freeze([
  "test/browser/device-storage-migration.spec.ts",
  "test/browser/password-provider-storage.spec.ts",
  "test/browser/album-storage-migration.spec.ts",
  "test/browser/photo-albums.spec.ts",
  "test/browser/notification-storage-migration.spec.ts",
  "test/browser/calendar-storage-migration.spec.ts",
  "test/browser/calendar-backup-restore.spec.ts",
  "test/browser/calendar-recovery.spec.ts",
  "test/browser/preference-storage-migration.spec.ts",
  "test/browser/reminder-storage-migration.spec.ts",
  "test/browser/storage-usage.spec.ts",
  "test/browser/domain-atomicity.spec.ts",
  "test/browser/location-settings-recovery.spec.ts",
  "test/browser/connection-preference-storage.spec.ts",
  "test/browser/appearance-storage.spec.ts",
  "test/browser/workflow-intent-storage.spec.ts",
  "test/browser/notes-document-storage.spec.ts",
  "test/browser/notes-save-failure.spec.ts",
  "test/browser/note-audio-delete-recovery.spec.ts",
  "test/browser/media-copy-intent-storage.spec.ts",
  "test/browser/conversation-selection-storage.spec.ts",
  "test/browser/browser-photo-edit.spec.ts",
  "test/browser/reminder-action-storage.spec.ts",
  "test/browser/reminder-delete-review.spec.ts",
  "test/browser/reminder-decision-review.spec.ts",
  "test/browser/browser-reminder-edit-recovery.spec.ts",
  "test/browser/reminder-creation-storage.spec.ts",
  "test/browser/reminder-create-review.spec.ts",
  "test/browser/domain-initialization.spec.ts",
  "test/browser/dev-cloud-setup.spec.ts",
  "test/browser/dev-cloud-scenarios.spec.ts",
  "test/browser/cloud-personal-intent-storage.spec.ts",
  "test/browser/cloud-personal-onboarding.spec.ts",
  "test/browser/cloud-account-migration.spec.ts",
  "test/browser/cloud-setup-migration.spec.ts",
]);
export const storageSpecPattern = new RegExp(`(?:^|[\\\\/])(${STORAGE_SPECS.map(file =>
  file.slice("test/browser/".length, -".spec.ts".length)).join("|")})\\.spec\\.ts$`);
