package ai.elizaresearch.alphaphone;
import android.os.SystemClock;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.runner.lifecycle.*;
import com.getcapacitor.JSObject;
import java.io.*;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;
import org.json.*;
import org.junit.*;
import static org.junit.Assert.*;
/** One normal pairing, one selected origin and enrollment across actual agent/device/voice/workflow flows. */
public final class CombinedAgentRestartInstrumentedTest {
 private static final String ORIGIN="http://10.0.2.2:47859";
 private JSONObject config;private String credentialHash,deviceHash,deviceSlot;
 private static void until(String expression,long timeout)throws Exception{long end=SystemClock.elapsedRealtime()+timeout;while(SystemClock.elapsedRealtime()<end){if("true".equals(NotesSecureFixture.evaluate("Boolean("+expression+")")))return;SystemClock.sleep(100);}fail("Combined stage did not reach its asserted state");}
 private static void click(String label)throws Exception{String q="[...document.querySelectorAll('button')].find(e=>(e.getAttribute('aria-label')==="+JSONObject.quote(label)+"||e.textContent.trim()==="+JSONObject.quote(label)+")&&e.getClientRects().length&&!e.disabled)";until(q,30000);NotesSecureFixture.evaluate("("+q+").click()");}
 private static MainActivity activity(){for(android.app.Activity a:ActivityLifecycleMonitorRegistry.getInstance().getActivitiesInStage(Stage.RESUMED))if(a instanceof MainActivity)return (MainActivity)a;throw new IllegalStateException("No resumed Alpha");}
 private static AlphaConnectionPlugin store(){return (AlphaConnectionPlugin)activity().getBridge().getPlugin("AlphaConnection").getInstance();}
 private static AlphaVoiceCloudPlugin voice(){return (AlphaVoiceCloudPlugin)activity().getBridge().getPlugin("AlphaVoiceCloud").getInstance();}
 private static void field(Object o,String name,Object value)throws Exception{Field f=o.getClass().getDeclaredField(name);f.setAccessible(true);f.set(o,value);}
 private static String hash(String raw)throws Exception{assertNotNull("Required private native credential",raw);StringBuilder out=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)))out.append(String.format(java.util.Locale.ROOT,"%02x",b&255));return out.toString();}
 // Match production JSON.stringify bytes: Android JSONArray escapes URL slashes.
 private static String arrayHash(JSONArray values)throws Exception{String encoded=NotesSecureFixture.evaluate("JSON.stringify("+values.toString()+")");return hash(new JSONArray("["+encoded+"]").getString(0));}
 private static String credential(String slot)throws Exception{AtomicReference<String> value=new AtomicReference<>();BoundedActivityScenario.main(()->{try{value.set(store().readCredentialSlot(slot));}catch(Exception e){throw new IllegalStateException("Private store read failed");}});return value.get();}
 private void checkpoint(String stage)throws Exception{assertTrue("Same paired native session",credentialHash.equals(hash(credential("remote:"+ORIGIN))));if(deviceHash!=null)assertTrue("Same native device enrollment",deviceHash.equals(hash(credential(deviceSlot))));assertEquals("Chooser never reopened between stages","false",NotesSecureFixture.evaluate("Boolean(document.querySelector('.alpha-connection-scrim'))"));android.os.Bundle b=new android.os.Bundle();b.putString("combinedStage",stage);InstrumentationRegistry.getInstrumentation().sendStatus(0,b);}
 private void open(String name)throws Exception{NotesSecureFixture.evaluate(AppNavigation.request(name));until(AppNavigation.selected(name),30000);until("window.__alphaTestNavigation?.status==='complete'",30000);}
 private void send(String prompt)throws Exception{NotesSecureFixture.evaluate(AppNavigation.type());until(AppNavigation.composer(),15000);NotesSecureFixture.evaluate("(()=>{const e=("+AppNavigation.composer()+");Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(e,"+JSONObject.quote(prompt)+");e.dispatchEvent(new Event('input',{bubbles:true}));})()");click("Send");}
 private void workflow(String title)throws Exception{open("Home");open("Workflows");String q="[...document.querySelectorAll('button')].find(e=>e.getClientRects().length&&e.textContent.includes("+JSONObject.quote(title)+"))";until(q,30000);NotesSecureFixture.evaluate("("+q+").click()");until("document.querySelector('button[aria-label=\"Run now\"]')",30000);}
 private void terminalReceipt()throws Exception{
  for(int i=0;i<60;i++){if("true".equals(NotesSecureFixture.evaluate("Boolean(document.querySelector('button[aria-label=\"Run again\"]'))")))return;String refresh="document.querySelector('button[aria-label=\"Refresh execution receipt\"]')";if("true".equals(NotesSecureFixture.evaluate("Boolean("+refresh+"&&!"+refresh+".disabled)")))NotesSecureFixture.evaluate(refresh+".click()");SystemClock.sleep(1000);}fail("Actual workflow did not reach terminal receipt");
 }
 private void progress(String stage){android.os.Bundle b=new android.os.Bundle();b.putString("combinedStage",stage);InstrumentationRegistry.getInstrumentation().sendStatus(0,b);}
 private void approvedReceipt()throws Exception{
  String approved="[...document.querySelectorAll('section[aria-label=\"Workflow approval review\"] p')].some(e=>e.textContent.trim()==='approved')";
  String refresh="document.querySelector('button[aria-label=\"Refresh execution receipt\"]')",idle="document.querySelector('button[aria-label=\"Cancel execution\"],button[aria-label=\"Run again\"]')";
  long deadline=SystemClock.elapsedRealtime()+120000;boolean announced=false;
  while(SystemClock.elapsedRealtime()<deadline){
   if("true".equals(NotesSecureFixture.evaluate(approved)))return;
   if("true".equals(NotesSecureFixture.evaluate("Boolean("+refresh+"&&("+idle+")&&!(("+idle+").disabled))"))){if(!announced){progress("approval-canonical-get-reconciliation");announced=true;}NotesSecureFixture.evaluate(refresh+".click()");}
   SystemClock.sleep(250);
  }
  fail("Approval confirmation did not reconcile through canonical receipt GET; no decision was resubmitted");
 }
 private void nativeJournal(String title,String notes)throws Exception{
  JSONObject enrollment=new JSONObject(credential(deviceSlot));String scope=arrayHash(new JSONArray().put(deviceSlot.substring("device:".length())).put(enrollment.getString("installationId")));
  NotesSecureFixture.evaluateSensitive("window.__combinedJournal=null;Capacitor.Plugins.AlphaActionJournal.list({scope:"+JSONObject.quote(scope)+"}).then(r=>window.__combinedJournal=r.entries.some(e=>e.phase==='terminal'&&e.status==='succeeded'&&e.record.operation.type==='create_note'&&e.record.operation.title==="+JSONObject.quote(title)+"&&e.operationId===("+notes+")[0].id),()=>window.__combinedJournal=false)");until("window.__combinedJournal!==null",15000);assertEquals("Exact native terminal journal points to actual note","true",NotesSecureFixture.evaluate("window.__combinedJournal"));
 }
 private void voiceFlow()throws Exception{
  android.content.Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();File audio=File.createTempFile("combined-voice-",".m4a",context.getCacheDir());
  try(InputStream in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("paired-whisper-fixture.m4a");OutputStream out=new FileOutputStream(audio)){byte[] bytes=new byte[8192];int n;while((n=in.read(bytes))!=-1)out.write(bytes,0,n);}
  try{
AppNavigation.liveMode();NotesSecureFixture.evaluate(AppNavigation.request("Notes"));until(AppNavigation.selected("Notes"),30000);until("window.__alphaTestNavigation?.status==='complete'",30000);NotesSecureFixture.evaluate("window.__voiceStatusTrace=[];window.__voiceStatusOriginal=Capacitor.nativePromise;Capacitor.nativePromise=function(plugin,method,options){const result=window.__voiceStatusOriginal.apply(this,arguments);if(plugin==='AlphaVoiceCloud'&&['pairedVoiceStatus','pairedTranscriptionStatus','localSpeechStatus','cancelRecording'].includes(method)){window.__voiceStatusTrace.push({method,state:'requested'});return result.then(value=>{window.__voiceStatusTrace.push({method,state:'resolved',ready:value?.ready===true,provider:value?.provider==='standalone-whisper.cpp'?'whisper':value?.provider==='sherpa-onnx-cpu'?'device':'other'});return value},error=>{const messages={'Voice request already active or unavailable':'active-or-unavailable','Voice request cancelled':'cancelled','Voice request failed':'failed','Voice unavailable':'unavailable'};window.__voiceStatusTrace.push({method,state:'rejected',category:messages[error?.message]||'other'});throw error});}return result;}");click("Record and transcribe");click("Use selected agent voice");
    String clip=UUID.randomUUID().toString();
    // Intercept only recording ingress. All capability, synthesis, playback and cancellation calls remain native.
    NotesSecureFixture.evaluate("window.__voiceOriginalPromise=Capacitor.nativePromise;Capacitor.nativePromise=function(plugin,method,options){if(plugin==='AlphaVoiceCloud'&&method==='startRecording')return Promise.resolve({recordingId:"+JSONObject.quote(clip)+",maxDurationMs:59000});return window.__voiceOriginalPromise.apply(this,arguments)}");
    click("Start recording");until("document.querySelector('button[aria-label=\"Stop recording\"]')",10000);
    BoundedActivityScenario.main(()->{try{Field f=AlphaVoiceCloudPlugin.class.getDeclaredField("capture");f.setAccessible(true);Object capture=f.get(voice());field(capture,"file",audio);field(capture,"id",clip);field(capture,"durationMs",1000L);JSObject stopped=new JSObject();stopped.put("recordingId",clip);stopped.put("durationMs",1000);Field events=AlphaCloudVoiceCapture.class.getDeclaredField("events");events.setAccessible(true);((java.util.function.Consumer<JSObject>)events.get(capture)).accept(stopped);}catch(Exception e){throw new RuntimeException(e);}});
    NotesSecureFixture.evaluate("Capacitor.nativePromise=window.__voiceOriginalPromise;delete window.__voiceOriginalPromise");click("Transcribe with agent Whisper");
    until("document.querySelector('textarea[aria-label=\"Review transcript\"]')?.value.toLowerCase().includes('water the plants tomorrow morning')",150000);
    until("document.querySelector('textarea[aria-label=\"Review transcript\"]')",10000);
    NotesSecureFixture.evaluate("(()=>{const e=document.querySelector('textarea[aria-label=\"Review transcript\"]');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(e,'Alpha Phone synthetic paired voice verification. The recording stays on this phone.');e.dispatchEvent(new Event('input',{bubbles:true}));})()");
    NotesSecureFixture.evaluate("window.__voiceEnded=0;window.__voiceFailed=0;window.__voiceListenersReady=false;Promise.all([Capacitor.Plugins.AlphaVoiceCloud.addListener('playbackEnded',()=>window.__voiceEnded++),Capacitor.Plugins.AlphaVoiceCloud.addListener('playbackFailed',()=>window.__voiceFailed++)]).then(handles=>{window.__voiceHandles=handles;window.__voiceListenersReady=true})");until("window.__voiceListenersReady",10000);
    click("Listen to transcript");until("window.__voiceEnded===1",150000);assertEquals("0",NotesSecureFixture.evaluate("window.__voiceFailed"));
    // Stop is visible during synthesis; wait for the exact second native play promise to resolve after MediaPlayer.start.
    NotesSecureFixture.evaluate("window.__voiceSecondStarted=false;window.__voiceSecondPlayback=null;window.__voicePlaybackOriginal=Capacitor.nativePromise;Capacitor.nativePromise=function(plugin,method,options){const result=window.__voicePlaybackOriginal.apply(this,arguments);if(plugin!=='AlphaVoiceCloud')return result;return result.then(value=>{if(method==='synthesizePaired'&&typeof value?.playbackId==='string')window.__voiceSecondPlayback=value.playbackId;if(method==='play'&&window.__voiceSecondPlayback!==null&&options?.playbackId===window.__voiceSecondPlayback)window.__voiceSecondStarted=true;return value;});}");
    click("Listen to transcript");until("window.__voiceSecondStarted===true",150000);
    String secondPlayback=(String)new JSONTokener(NotesSecureFixture.evaluate("window.__voiceSecondPlayback")).nextValue();
    BoundedActivityScenario.main(()->{try{AlphaVoiceCloudPlugin plugin=voice();Field id=AlphaVoiceCloudPlugin.class.getDeclaredField("playbackId"),player=AlphaVoiceCloudPlugin.class.getDeclaredField("player");id.setAccessible(true);player.setAccessible(true);assertTrue("Exact second native playback remains selected",secondPlayback.equals(id.get(plugin)));android.media.MediaPlayer actual=(android.media.MediaPlayer)player.get(plugin);assertNotNull("Second native player exists",actual);assertTrue("Second native playback actually started before Stop",actual.isPlaying());}catch(ReflectiveOperationException error){throw new AssertionError("Native playback fixture access failed",error);}});
    NotesSecureFixture.evaluate("Capacitor.nativePromise=window.__voicePlaybackOriginal;delete window.__voicePlaybackOriginal");until("document.querySelector('button[aria-label=\"Stop audio\"]')",10000);click("Stop audio");until("document.querySelector('button[aria-label=\"Listen to transcript\"]')",15000);
    assertEquals("1",NotesSecureFixture.evaluate("window.__voiceEnded"));
    NotesSecureFixture.evaluate("window.dispatchEvent(new Event('alpha-back'))");until("!document.querySelector('textarea[aria-label=\"Review transcript\"]')",15000);

  }catch(Exception|AssertionError failure){
    try{android.os.Bundle diagnostic=new android.os.Bundle();diagnostic.putString("voiceFailureDiagnostic",NotesSecureFixture.evaluate("JSON.stringify({capabilities:window.__voiceStatusTrace||[],controls:['Start recording','Stop recording','Transcribe with agent Whisper','Transcribe with Eliza Cloud','Use selected agent voice','Use on-device voice','Review transcript'].map(label=>({label,present:[...document.querySelectorAll('[aria-label],button')].some(e=>(e.getAttribute('aria-label')===label||e.textContent.trim()===label)&&e.getClientRects().length),enabled:[...document.querySelectorAll('button')].some(e=>(e.getAttribute('aria-label')===label||e.textContent.trim()===label)&&e.getClientRects().length&&!e.disabled)}))})"));InstrumentationRegistry.getInstrumentation().sendStatus(0,diagnostic);}catch(Exception diagnosticFailure){android.os.Bundle diagnostic=new android.os.Bundle();diagnostic.putString("voiceFailureDiagnostic","unavailable");InstrumentationRegistry.getInstrumentation().sendStatus(0,diagnostic);}
    throw failure;
  }finally{NotesSecureFixture.evaluate("if(window.__voicePlaybackOriginal){Capacitor.nativePromise=window.__voicePlaybackOriginal;delete window.__voicePlaybackOriginal;}delete window.__voiceSecondStarted;delete window.__voiceSecondPlayback;if(window.__voiceOriginalPromise)Capacitor.nativePromise=window.__voiceOriginalPromise;if(window.__voiceStatusOriginal){Capacitor.nativePromise=window.__voiceStatusOriginal;delete window.__voiceStatusOriginal;}delete window.__voiceStatusTrace;delete window.__voiceOriginalPromise;window.__voiceHandles?.forEach(h=>h.remove());window.__combinedVoiceCleanup=false;Promise.all([Capacitor.Plugins.AlphaVoiceCloud.cancelRecording(),Capacitor.Plugins.AlphaVoiceCloud.stopPlayback()]).then(()=>window.__combinedVoiceCleanup=true)");until("window.__combinedVoiceCleanup",15000);audio.delete();}
 }
 @Test public void prepareAcrossActualFlows()throws Exception{
  Assume.assumeTrue("Prepare phase only","prepare".equals(InstrumentationRegistry.getArguments().getString("restartPhase")));
  Assume.assumeTrue("Explicit combined runtime only","1".equals(InstrumentationRegistry.getArguments().getString("combinedAgentRestart")));assertTrue("Loopback HTTP fixtures require a -PELIZA_DEV_ALLOW_TEST_MOCKS=1 debug build",BuildConfig.ELIZA_DEV_ALLOW_TEST_MOCKS);
  assertFalse("Clean up the existing restart checkpoint before another prepare",stateFile().exists());
  File fixture=new File(InstrumentationRegistry.getInstrumentation().getTargetContext().getFilesDir(),"combined-agent-restart-fixture.json");config=new JSONObject(new String(Files.readAllBytes(fixture.toPath()),StandardCharsets.UTF_8));assertEquals(ORIGIN,config.getString("origin"));assertEquals(UUID.fromString(config.getString("runId")).toString(),config.getString("runId"));
  String title="Combined note "+config.getString("runId"),body="Synthetic combined agent note.";String notes="__notesEnvelope.records.filter(n=>n.title==="+JSONObject.quote(title)+")";
  String previous=null;boolean retained=false,paired=false,pairingAttempted=false;Throwable primary=null;
  try(BoundedActivityScenario<MainActivity> scenario=BoundedActivityScenario.launch(MainActivity.class)){
   until("document.querySelector('.os')",30000);deviceSlot="device:"+arrayHash(new JSONArray().put(ORIGIN).put(config.getString("ownerId")).put(config.getString("agentId")));previous=NotesSecureFixture.evaluate("localStorage.getItem('alpha.connection.selection.v1')");
   assertNull("Do not overwrite prior combined pairing",credential("remote:"+ORIGIN));assertNull("Do not overwrite prior combined enrollment",credential(deviceSlot));assertNull("No Cloud voice override in fixture",credential("cloud:production"));assertNull("No Cloud staging voice override",credential("cloud:staging"));
   try{
    String time=NotesSecureFixture.evaluate("performance.timeOrigin");
    assertEquals("Connection selection clear must be acknowledged before recreation","true",NotesSecureFixture.evaluate("(()=>{localStorage.removeItem('alpha.connection.selection.v1');return localStorage.getItem('alpha.connection.selection.v1')===null;})()"));
    scenario.recreate();
    until("performance.timeOrigin!=="+time+"&&document.querySelector('.alpha-connection-scrim')",30000);
    assertEquals("Recreated chooser must retain cleared selection","true",NotesSecureFixture.evaluate("localStorage.getItem('alpha.connection.selection.v1')===null"));
    NotesSecureFixture.evaluate("[...document.querySelectorAll('.alpha-connection summary')].find(e=>e.textContent==='Local development agent').click()");NotesSecureFixture.evaluateSensitive("(()=>{const inputs=[...document.querySelectorAll('.alpha-connection details')].find(e=>e.querySelector('summary')?.textContent==='Local development agent').querySelectorAll('input');inputs[0].value="+JSONObject.quote(ORIGIN)+";inputs[1].value="+JSONObject.quote(config.getString("code"))+";})()");pairingAttempted=true;click("Connect local agent");until("!document.querySelector('.alpha-connection-scrim')",90000);paired=true;credentialHash=hash(credential("remote:"+ORIGIN));checkpoint("paired-once");
    open("Settings");click("Agent connection");until("document.querySelector('.alpha-connection-scrim')",15000);NotesSecureFixture.evaluate("[...document.querySelectorAll('.alpha-connection summary')].find(e=>e.textContent==='Conversation history').click()");click("Load conversations");String restore="[...document.querySelectorAll('.alpha-connection-agent')].find(e=>e.querySelector('strong')?.textContent==="+JSONObject.quote(config.getString("conversationTitle"))+")?.querySelector('button')";until(restore+"&&!("+restore+").disabled",30000);NotesSecureFixture.evaluate("("+restore+").click()");until("!document.querySelector('.alpha-connection-scrim')",30000);
    open("Home");int answer=config.getInt("answer");assertTrue(answer>=100000&&answer<900000);send("Reply with only the integer "+answer+". This is a synthetic connection check; do not use tools.");until("[...document.querySelectorAll('[data-alpha-layer=conversation] *')].some(e=>e.children.length===0&&e.textContent.trim()==="+JSONObject.quote(String.valueOf(answer))+")",150000);checkpoint("real-cerebras-chat");
    open("Home");assertEquals("0",NotesSecureFixture.evaluate(notes+".length"));send("Use PROPOSE_DEVICE_ACTION to propose exactly one create_note operation for this enrolled phone with title "+JSONObject.quote(title)+" and body "+JSONObject.quote(body)+". Await explicit approval.");String approval="[...document.querySelectorAll('button')].find(e=>e.textContent.includes('Approve: create note')&&e.getClientRects().length&&!e.disabled)";until(approval,180000);assertEquals("No effect before review","0",NotesSecureFixture.evaluate(notes+".length"));NotesSecureFixture.evaluate("("+approval+").click()");until(notes+".length===1",60000);assertEquals(JSONObject.quote(body),NotesSecureFixture.evaluate("("+notes+")[0].body"));until("[...document.querySelectorAll('button')].some(e=>e.textContent.includes('Completed'))",30000);deviceHash=hash(credential(deviceSlot));nativeJournal(title,notes);checkpoint("approved-native-note");
    voiceFlow();checkpoint("real-whisper-kokoro");
    workflow(config.getString("workflowTitle"));click("Run now");click("Run now");until("document.querySelector('button[aria-label=\"Refresh execution receipt\"]')",30000);terminalReceipt();checkpoint("reviewed-workflow-run");
    workflow(config.getString("approvalTitle"));String history="[...document.querySelectorAll('button')].filter(e=>e.getAttribute('aria-label')?.endsWith(' execution')&&e.getClientRects().length)";until(history+".length===1",30000);NotesSecureFixture.evaluate("("+history+")[0].click()");until("document.querySelector('section[aria-label=\"Workflow approval review\"]')",30000);progress("approval-review-visible");click("Approve");click("Confirm approval");progress("approval-confirmation-submitted");approvedReceipt();checkpoint("canonical-workflow-approval");
    workflow(config.getString("workflowTitle"));click("Change");until("document.querySelector('input[aria-label=\"Workflow name\"]')",15000);String changed="Changed "+config.getString("workflowTitle");NotesSecureFixture.evaluate("(()=>{const e=document.querySelector('input[aria-label=\"Workflow name\"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,"+JSONObject.quote(changed)+");e.dispatchEvent(new Event('input',{bubbles:true}));})()");click("Save");until("document.body.textContent.includes('Save outcome unknown')&&document.body.textContent.includes('Workflow request unavailable. Refresh history before repeating any run.')",30000);scenario.recreate();until("document.documentElement.dataset.activeView==='home'&&!document.querySelector('.alpha-connection-scrim')",60000);workflow(changed);until("!document.body.textContent.includes('Save outcome unknown')",30000);checkpoint("metadata-loss-reconciled");
    click("Remove workflow");click("Remove workflow; keep execution history");until("document.body.textContent.includes('Removed; execution history retained')",30000);scenario.recreate();until("document.documentElement.dataset.activeView==='home'&&!document.querySelector('.alpha-connection-scrim')",60000);open("Workflows");String removed="[...document.querySelectorAll('button')].find(e=>e.getClientRects().length&&e.textContent.includes('Removed workflows'))";until(removed,30000);NotesSecureFixture.evaluate("("+removed+").click()");String card="[...document.querySelectorAll('button')].find(e=>e.getClientRects().length&&e.textContent.includes("+JSONObject.quote(changed)+"))";until(card,30000);NotesSecureFixture.evaluate("("+card+").click()");until(history+".length===1",30000);click("Restore workflow");click("Confirm restore");until("document.body.textContent.includes('Paused on remote agent')",30000);checkpoint("removed-history-restored-paused");
    assertEquals("Persisted exact note","1",NotesSecureFixture.evaluate(notes+".length"));nativeJournal(title,notes);checkpoint("campaign-complete");
    JSONObject checkpoint=new JSONObject().put("format",1).put("phonePid",android.os.Process.myPid()).put("runId",config.getString("runId")).put("credentialHash",credentialHash).put("deviceHash",deviceHash).put("deviceSlot",deviceSlot).put("previousSelection",previous);
    File state=new File(fixture.getParentFile(),"combined-agent-restart-state.json");assertFalse("Never overwrite an unfinished restart checkpoint",state.exists());
    try(FileOutputStream out=new FileOutputStream(state)){out.write(checkpoint.toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}
    state.setReadable(false,false);state.setWritable(false,false);assertTrue(state.setReadable(true,true));assertTrue(state.setWritable(true,true));
    config.remove("code");try(FileOutputStream out=new FileOutputStream(fixture)){out.write(config.toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}
    retained=true;checkpoint("restart-prepared");
   }catch(Exception|AssertionError error){primary=error;throw error;}finally{if(!retained)try{
    NotesSecureFixture.replaceRecords("records=>records.filter(n=>!(n.title==="+JSONObject.quote(title)+"&&n.body==="+JSONObject.quote(body)+"))");
    // Restore only once, after all feature stages; never repair identity between stages.
    if(pairingAttempted){NotesSecureFixture.evaluateSensitive("window.__combinedRemoved=false;Promise.all([Capacitor.Plugins.AlphaConnection.secureRemove({slot:"+JSONObject.quote("remote:"+ORIGIN)+"}),Capacitor.Plugins.AlphaConnection.secureRemove({slot:"+JSONObject.quote(deviceSlot)+"})]).then(()=>window.__combinedRemoved=true)");until("window.__combinedRemoved",15000);}
    NotesSecureFixture.evaluate("(()=>{const prior="+previous+";if(prior===null)localStorage.removeItem('alpha.connection.selection.v1');else localStorage.setItem('alpha.connection.selection.v1',prior);})()");scenario.recreate();until("document.querySelector('.os')",30000);
   }catch(Exception|AssertionError cleanup){if(primary!=null)primary.addSuppressed(cleanup);else throw cleanup;}}
  }finally{if(!retained)fixture.delete();}
 }
 private File stateFile(){return new File(InstrumentationRegistry.getInstrumentation().getTargetContext().getFilesDir(),"combined-agent-restart-state.json");}
 private JSONObject loadCheckpoint()throws Exception{JSONObject saved=new JSONObject(new String(Files.readAllBytes(stateFile().toPath()),StandardCharsets.UTF_8));assertEquals(1,saved.getInt("format"));return saved;}
 @Test public void verifyAfterBothProcessesRestart()throws Exception{
  Assume.assumeTrue("Verify phase only","verify".equals(InstrumentationRegistry.getArguments().getString("restartPhase")));
  Assume.assumeTrue("Explicit combined restart","1".equals(InstrumentationRegistry.getArguments().getString("combinedAgentRestart")));assertTrue("Loopback HTTP fixtures require a -PELIZA_DEV_ALLOW_TEST_MOCKS=1 debug build",BuildConfig.ELIZA_DEV_ALLOW_TEST_MOCKS);
  JSONObject saved=loadCheckpoint();assertNotEquals("Real Android process replacement",saved.getInt("phonePid"),android.os.Process.myPid());
  File fixture=new File(stateFile().getParentFile(),"combined-agent-restart-fixture.json");config=new JSONObject(new String(Files.readAllBytes(fixture.toPath()),StandardCharsets.UTF_8));assertFalse("Consumed pairing code is not retained",config.has("code"));assertEquals(saved.getString("runId"),config.getString("runId"));assertEquals(ORIGIN,config.getString("origin"));
  credentialHash=saved.getString("credentialHash");deviceHash=saved.getString("deviceHash");deviceSlot=saved.getString("deviceSlot");
  String title="Combined note "+config.getString("runId"),body="Synthetic combined agent note.",notes="__notesEnvelope.records.filter(n=>n.title==="+JSONObject.quote(title)+")";
  try(BoundedActivityScenario<MainActivity> scenario=BoundedActivityScenario.launch(MainActivity.class)){
   until("document.querySelector('.os')&&document.documentElement.dataset.connectionMode==='live'&&!document.querySelector('.alpha-connection-scrim')",90000);checkpoint("same-session-after-process-restart");
   assertEquals("1",NotesSecureFixture.evaluate(notes+".length"));nativeJournal(title,notes);open("Notes");click("Open "+title);until("document.querySelector('textarea[aria-label=Note]')?.value==="+JSONObject.quote(body),30000);checkpoint("same-native-note-and-journal");
   open("Settings");click("Agent connection");until("document.querySelector('.alpha-connection-scrim')",15000);NotesSecureFixture.evaluate("[...document.querySelectorAll('.alpha-connection summary')].find(e=>e.textContent==='Conversation history').click()");click("Load conversations");
   String restore="[...document.querySelectorAll('.alpha-connection-agent')].find(e=>e.querySelector('strong')?.textContent==="+JSONObject.quote(config.getString("conversationTitle"))+")?.querySelector('button')";until(restore+"&&!("+restore+").disabled",30000);NotesSecureFixture.evaluate("("+restore+").click()");until("!document.querySelector('.alpha-connection-scrim')",30000);checkpoint("same-canonical-conversation");
   workflow("Changed "+config.getString("workflowTitle"));until("document.body.textContent.includes('Paused on remote agent')",30000);String history="[...document.querySelectorAll('button')].filter(e=>e.getAttribute('aria-label')?.endsWith(' execution')&&e.getClientRects().length)";until(history+".length===1",30000);NotesSecureFixture.evaluate("("+history+")[0].click()");terminalReceipt();checkpoint("same-retained-workflow-execution");
   workflow(config.getString("approvalTitle"));until(history+".length===1",30000);NotesSecureFixture.evaluate("("+history+")[0].click()");until("document.querySelector('section[aria-label=\"Workflow approval review\"]')?.textContent.includes('approved')",30000);checkpoint("same-canonical-approved-receipt");
   saved.put("verifiedPhonePid",android.os.Process.myPid()).put("verified",true);try(FileOutputStream out=new FileOutputStream(stateFile())){out.write(saved.toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}
  }
 }
 @Test public void cleanupOwnedRestartFixture()throws Exception{
  Assume.assumeTrue("Cleanup phase only","cleanup".equals(InstrumentationRegistry.getArguments().getString("restartPhase")));
  Assume.assumeTrue("Explicit combined restart","1".equals(InstrumentationRegistry.getArguments().getString("combinedAgentRestart")));assertTrue("Loopback HTTP fixtures require a -PELIZA_DEV_ALLOW_TEST_MOCKS=1 debug build",BuildConfig.ELIZA_DEV_ALLOW_TEST_MOCKS);
  if(!stateFile().exists())return;JSONObject saved=loadCheckpoint();String title="Combined note "+saved.getString("runId"),body="Synthetic combined agent note.";deviceSlot=saved.getString("deviceSlot");
  try(BoundedActivityScenario<MainActivity> scenario=BoundedActivityScenario.launch(MainActivity.class)){
   until("document.querySelector('.os')",30000);
   assertEquals("Cleanup only owned paired identity",saved.getString("credentialHash"),hash(credential("remote:"+ORIGIN)));assertEquals("Cleanup only owned enrollment",saved.getString("deviceHash"),hash(credential(deviceSlot)));
   NotesSecureFixture.replaceRecords("records=>records.filter(n=>!(n.title==="+JSONObject.quote(title)+"&&n.body==="+JSONObject.quote(body)+"))");
   NotesSecureFixture.evaluateSensitive("window.__combinedRestartClean=false;Promise.all([Capacitor.Plugins.AlphaConnection.secureRemove({slot:"+JSONObject.quote("remote:"+ORIGIN)+"}),Capacitor.Plugins.AlphaConnection.secureRemove({slot:"+JSONObject.quote(deviceSlot)+"})]).then(()=>window.__combinedRestartClean=true)");until("window.__combinedRestartClean",15000);
   NotesSecureFixture.evaluate("(()=>{const prior="+saved.getString("previousSelection")+";if(prior===null)localStorage.removeItem('alpha.connection.selection.v1');else localStorage.setItem('alpha.connection.selection.v1',prior);})()");scenario.recreate();until("document.querySelector('.os')",30000);
  }
  assertTrue(stateFile().delete());File fixture=new File(stateFile().getParentFile(),"combined-agent-restart-fixture.json");assertTrue(!fixture.exists()||fixture.delete());
 }

}
